### PR TITLE
Import service - better visual feedback

### PR DESCRIPTION
**Pull request by AleksueiR**
Provide better feedback to the user when actions are occurring behind the scenes (i.e. trying to connect to a service, loading a file, etc).

In support of #770;

__________
Fix for #800;

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/803)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/legend-entry.service.js, line 232 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnAmv7rfOF03utbJy8:-KKnAmv7rfOF03utbJy9:1514294871) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/geo/legend-entry.service.js#L232)):*
> ```JavaScript
>             this.bindListeners();
> 
>             // since the main purpose of these placholders is to indicate that layers are loading (or failed to load),
> ```

typo placeholders

---

*[src/app/ui/common/stepper/stepper.class.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnBzgx3VnxhsYVxWBE:-KKnBzgyPK9WPcnGyr1V:-170875001) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/common/stepper/stepper.class.js#L194)):*
> ```JavaScript
> 
>             /**
>              * Calls `reset` functio on the step object if one is present
> ```

typo: function

---

*[src/app/ui/loader/loader-file.directive.js, line 237 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnCOR_S9nXWxgiKGy_:-KKnCOR_S9nXWxgiKGya:-1536372587) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/loader/loader-file.directive.js#L237)):*
> ```JavaScript
>         }
> 
>         function selectOnContinue() {
> ```

jsdoc missing on this and the next three functions

---

*[src/app/ui/loader/loader-service.directive.js, line 58 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnCkR3rGkikkmmmKgO:-KKnCkR3rGkikkmmmKgP:1224095372) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/loader/loader-service.directive.js#L58)):*
> ```JavaScript
>             form: null,
>             serviceUrl: null,
>             serviceResetValidation: serviceResetValidation
> ```

replace with object shorthand?

---

*[src/app/ui/loader/loader-service.directive.js, line 188 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnD06wKUuQim_JRbsC:-KKnD06wKUuQim_JRbsD:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/loader/loader-service.directive.js#L188)):*
> ```JavaScript
>         }
> 
>         function configureReset() {
> ```

jsdoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803)*

**Comment by AleksueiR** [comment]
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/legend-entry.service.js, line 232 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnAmv7rfOF03utbJy8:-KKnFOGIlYUdRD_6WLvk:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/geo/legend-entry.service.js#L232)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo placeholders
</details>
Done.

---

*[src/app/ui/common/stepper/stepper.class.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnBzgx3VnxhsYVxWBE:-KKnDaYwVQgb-3g1fW0I:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/common/stepper/stepper.class.js#L194)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: function
</details>
Done.

---

*[src/app/ui/loader/loader-file.directive.js, line 237 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnCOR_S9nXWxgiKGy_:-KKnEHO5xEQfYgKkBlCy:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/loader/loader-file.directive.js#L237)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc missing on this and the next three functions
</details>
Done.

---

*[src/app/ui/loader/loader-service.directive.js, line 58 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnCkR3rGkikkmmmKgO:-KKnELJl-dnoVkTi_CM5:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/loader/loader-service.directive.js#L58)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> replace with object shorthand?
</details>
Done.

---

*[src/app/ui/loader/loader-service.directive.js, line 188 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803#-KKnD06wKUuQim_JRbsC:-KKnEqAVJi4bkfh9MORP:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82374f6225cd8a4d8e94414fe3b015235b7f50a4/src/app/ui/loader/loader-service.directive.js#L188)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803)*

**Comment by spencerwahl** [comment]
Reviewed 6 of 10 files at r1, 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803)*

**Comment by cynngah** [comment]
Reviewed 6 of 10 files at r1, 1 of 4 files at r2, 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/803)*

**Pull request merged**
