### PR TITLE
fix(ui): remove displayed info panels when layer is removed

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Before: when a layer is removed, corresponding displayed panel
(Settings or Metadata) is still displayed
After: when a layer is removed, corresponding displayed panel
(Settings or Metadata) is removed too. If the toast UNDO button is pushed,
the previously displayed info panel reappears with the layer entry.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1322)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/toc/toc.service.js, line 443 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVaGzy9NxDxfXGxkaN5:-KVaGzyAgFpe3LSCei2e:bdmclca) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63743139a1ee74041bfad5505db0dea5686bd85f/src/app/ui/toc/toc.service.js#L443)):*
> ```JavaScript
>                     errorService.display($translate.instant('toc.error.resource.loadfailed'),
>                             layoutService.panes.metadata);
>                 });
> ```

These changes work, but I think the problem was with the original code.

It looks like this catch is added in the wrong place: a promise returned by `toggleDisplayPanel` will reject if the data cannot be displayed for some reason (request is stale or the panel is closed). The catch here is supposed to display an error message in case the metadata cannot be loaded, but it's being wrongly triggered by data being displayed.

This catch
```js
.catch(() => {
                    errorService.display($translate.instant('toc.error.resource.loadfailed'),
                            layoutService.panes.metadata); })
```
need to be added to the data promise above (line 413) (also notice I added  a `catch` with a `reject` after the `transofrmXml` promise:
```js
const dataPromise = $q((fulfill, reject) => {
    // check if metadata is cached
    if (layer.cache.metadata) {
        fulfill(layer.cache.metadata);
    } else {
        metadataService.transformXml(layer.metadataUrl).then(mdata => {
            // result is wrapped in an array due to previous setup
            // TODO: chagee the following when changing associated directive service
            layer.cache.metadata = mdata;

            if (layer.metadataUrl) {
                layer.cache.metadata.metadataUrl = layer.metadataUrl;
            }

            if (layer.catalogueUrl) {
                layer.cache.metadata.catalogueUrl = layer.catalogueUrl;
            }

            fulfill(layer.cache.metadata);
        }).catch(error => reject(error));
    }
}).catch(() => {
    errorService.display($translate.instant('toc.error.resource.loadfailed'),
        layoutService.panes.metadata);
});


```
With this, the error message will only be displayed if the metadata cannot be retrieved; the closing of the metada panel won't trigger the error and the toast with layer removal undo button will not be close early. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/toc/toc.service.js, line 443 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVaGzy9NxDxfXGxkaN5:-KVaNjiPtMA6bgtMcT6J:b-qxqc22) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63743139a1ee74041bfad5505db0dea5686bd85f/src/app/ui/toc/toc.service.js#L443)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> These changes work, but I think the problem was with the original code.
> 
> It looks like this catch is added in the wrong place: a promise returned by `toggleDisplayPanel` will reject if the data cannot be displayed for some reason (request is stale or the panel is closed). The catch here is supposed to display an error message in case the metadata cannot be loaded, but it's being wrongly triggered by data being displayed.
> 
> This catch
> ```js
> .catch(() => {
>                     errorService.display($translate.instant('toc.error.resource.loadfailed'),
>                             layoutService.panes.metadata); })
> ```
> need to be added to the data promise above (line 413) (also notice I added  a `catch` with a `reject` after the `transofrmXml` promise:
> ```js
> const dataPromise = $q((fulfill, reject) => {
>     // check if metadata is cached
>     if (layer.cache.metadata) {
>         fulfill(layer.cache.metadata);
>     } else {
>         metadataService.transformXml(layer.metadataUrl).then(mdata => {
>             // result is wrapped in an array due to previous setup
>             // TODO: chagee the following when changing associated directive service
>             layer.cache.metadata = mdata;
> 
>             if (layer.metadataUrl) {
>                 layer.cache.metadata.metadataUrl = layer.metadataUrl;
>             }
> 
>             if (layer.catalogueUrl) {
>                 layer.cache.metadata.catalogueUrl = layer.catalogueUrl;
>             }
> 
>             fulfill(layer.cache.metadata);
>         }).catch(error => reject(error));
>     }
> }).catch(() => {
>     errorService.display($translate.instant('toc.error.resource.loadfailed'),
>         layoutService.panes.metadata);
> });
> 
> 
> ```
> With this, the error message will only be displayed if the metadata cannot be retrieved; the closing of the metada panel won't trigger the error and the toast with layer removal undo button will not be close early. 
> 
</details>
Ok, let me try that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/toc/toc.service.js, line 443 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVaGzy9NxDxfXGxkaN5:-KVaRTLquu3RU6sXmO0I:b-a060uk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63743139a1ee74041bfad5505db0dea5686bd85f/src/app/ui/toc/toc.service.js#L443)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary>
> Ok, let me try that.
</details>
First, the catch with the errorService call works great in place of  .catch(error => reject(error))
Do we want the close button from the toast to close the panel ? Actually it just close itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 443 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVaGzy9NxDxfXGxkaN5:-KVeHjXXLwYl-aWsVZ98:bz4zzsu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63743139a1ee74041bfad5505db0dea5686bd85f/src/app/ui/toc/toc.service.js#L443)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary>
> First, the catch with the errorService call works great in place of  .catch(error => reject(error))
> Do we want the close button from the toast to close the panel ? Actually it just close itself.
</details>
Yes, it works there as well, I just tried to avoid too much nesting.

The toast never closed the panel before (just itself), so I think we should keep this behaviour four now. If you think we need to change it, you can open an issue for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/toc/toc.service.js, line 435 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVj3_Og4ru_gsy3lZI-:-KVj3_Og4ru_gsy3lZI0:b-5b4ucr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd7f2b8bbedc7a0b4d61b513e7eb7c8d83b22a56/src/app/ui/toc/toc.service.js#L435)):*
> ```JavaScript
>             const layer = entry.master ? entry.master : entry;
> 
>             if (typeof state === 'undefined' || state === false) {
> ```

I don't think this is needed since we moved the error handling to the data retrieval part.

---

*[src/app/ui/toc/toc.service.js, line 457 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVj3Pm8YHSgmKfPdBys:-KVj3Pm9uK0x5b3r2UmF:b-5l7cjh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd7f2b8bbedc7a0b4d61b513e7eb7c8d83b22a56/src/app/ui/toc/toc.service.js#L457)):*
> ```JavaScript
>                             fulfill(layer.cache.metadata);
> 
>                         }).catch(() => {
> ```

There is no need for custom toast,
```js
errorService.display($translate.instant('toc.error.resource.loadfailed'),
        layoutService.panes.metadata);
```
should be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/toc/toc.service.js, line 435 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVj3_Og4ru_gsy3lZI-:-KVjNXCYYV5Om860zZ0W:b9neewi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd7f2b8bbedc7a0b4d61b513e7eb7c8d83b22a56/src/app/ui/toc/toc.service.js#L435)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I don't think this is needed since we moved the error handling to the data retrieval part.
</details>
I'll test without state stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/toc/toc.service.js, line 457 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVj3Pm8YHSgmKfPdBys:-KVjNg1C-2lvVLOdNDHY:b-jxz5ln) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd7f2b8bbedc7a0b4d61b513e7eb7c8d83b22a56/src/app/ui/toc/toc.service.js#L457)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> There is no need for custom toast,
> ```js
> errorService.display($translate.instant('toc.error.resource.loadfailed'),
>         layoutService.panes.metadata);
> ```
> should be enough.
</details>
Yes Master (didn't find Yoda emoji)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 457 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-KVj3Pm8YHSgmKfPdBys:-KVjY38ehQui7Vp23hzB:b-vnibsu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd7f2b8bbedc7a0b4d61b513e7eb7c8d83b22a56/src/app/ui/toc/toc.service.js#L457)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary>
> Yes Master (didn't find Yoda emoji)
</details>
Here: http://imgur.com/gallery/vBmWO


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322#-:-KVkFNCdQ70_pUWuJ6Xj:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1322)*

**Comment by mweech** [comment]
for #1308

**Pull request merged**
