### PR TITLE
fix(enhancedTable): enable accessible list navigation

### PR DESCRIPTION
**Pull request by ShrutiVellanki**
## Description

- Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3294
- cell navigation is broken see: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3414
- This is basically this: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3418 with a couple fixes added in:  https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3418#issuecomment-483418517
- Sister PR: https://github.com/fgpv-vpgf/plugins/pull/78

## [Testing](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/accessibility-5/dev/samples/index-samples.html?sample=2)

- tab for list navigation, right and left arrows for item navigation, tab again for object navigation
- should highlight for items and have a border for lists
- should focus out to the parent element and remove any item highlights when tabbing is finished

### Checklist

- [ ] works in IE11
- [ ] works in Edge
- [ ] works with projection change
- [ ] works with language change
- [ ] works via config file
- [ ] works via wizard
- [ ] works via API
- [ ] works via RCS
- [ ] works via bookmark load
- [ ] works in auto-legend
- [ ] works in structured legend
- [ ] works on layer reload
- [x] datagrid works
- [ ] identify works

## Documentation

inline comments

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- ~[ ] Help files and documentation have been updated~
- [x] original issue has been reviewed & updated to reflect the PR content

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3421)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Some unexpected behaviours:
- tab to a list and select an item with arrow keys
- press `tab` to focus on the first focusable node inside the list item
- observe that nothing happened

You need to press tab several times before any focusable nodes inside the item are highlighted. The number of time you need to press tab varies, but it seems it's related to the position of the item - the farther the item, the more you need to press tab.



---

- tab to a list and select an item with arrow keys
- press `tab` to focus on the first focusable node inside the list item
- press `up` or `down` key to select an adjacent item
- notice that the focus node in the previous list item is still focused (the actual focus should have gone back to the list container)
- press `tab` again
- notice that the item right after the list (the filter list) got focus instead of the first focusable node inside the selected list item



---

this one is weird: tabbing between the menu and panel close button slowly scrolls the body of the table to the right



---

- tab to a list and select an item with arrow keys
- focus on the first focusable node inside the list item
- press `shift+tab`
- notice that the item right after the list (the filter list) got focus instead of the focus moving back to the panel close button

**Comment by spencerwahl** [comment]
Tabbing past the table to the nav buttons then hitting `shift + tab` sends you to the layers/legend button and not the table. I'm not sure if that's in scope though, since its an overall tab order issue and not internal to the table.

**Comment by dane-thomas** [comment]
Also an issue when tabbing through the header. After tabbing through all the buttons, pressing tab again doesn't take you to the filters but skips straight to the nav buttons.

**Comment by dane-thomas** [comment]
Clicking into a cell sometimes highlights and sometimes does not. The cell does get selected as using the arrow keys after seems to move the focus to the cells around them. When it does highlight (in chrome) it gets stuck highlighting the clicked cell and also highlights the cell being moved to. 

Clicking or using the keyboard to activate the details or zoom buttons works but the cell doesn't stay highlighted although it is still focused. 

Pressing `shift+tab` while moving through list items goes back to a seemingly random focusable element on the page and also keeps the highlight on the list item. 

Tabbing into the header list or filter list causes the table to scroll all the way left or all the way right. 

Tabbing from the filter lists to the grid without highlighting any of the filters doesn't focus a cell in the table.

**Comment by ShrutiVellanki** [comment]
@dane-thomas summarizing our gitter conversation about table cells

For points 1, 2 and 5:
- I think cell stuff (for the most part) belongs here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3414 so I'll move it there because your list will be useful for that issue

In this issue: 
- I'll try and make sure the grid takes you into the first cell (since that's a FM issue) and try to make sure that it always enters into the grid so that its navigable by arrows
- I'll also double check that apart from tabbing in and out of the "cell list" as a whole, my code isn't overriding default `ag-grid` behaviour

I'll address your other points in this issue as well.

**Comment by dane-thomas** [comment]
There's a bit of lag when tabbing through certain parts of the table:
- close button -> header
- header -> filters
- filters -> grid

For some reason the reverse seems to work without any problems.

**Comment by dane-thomas** [comment]
A few more things:
- Using the keyboard to change a  column position prevents any further keyboard navigation in Firefox.
- Sometimes moving left on the headers causes the highlighted header to snap left. Seems to only be in Firefox as well. Not sure how important this is but it would be somewhat jarring to a user. 
- Can't navigate through text of a filter. Using the arrow keys when typing into a filter moves to an adjacent filter rather than navigating through character. Again, not sure if this is an issue or expected behavior.

**Comment by AleksueiR** [comment]
> There's a bit of lag when tabbing through certain parts of the table:

Yeah, I noticed that too. If it were FM, I would think the lag is from iterating though the DOM tree looking for focusables. Focused on the filter row, you can press the key twice or three times (if you do it quickly), and the focus will only move once.

When navigating using arrow keys, pressing and holding an arrow key only moves the selection once (only the adjacent item is highlighted). However, if you let go and press again, the selection moves to the last item in the direction of the key you were holding before (seems like internally the proper selection is tracked, but is not rendered).

**Comment by ShrutiVellanki** [comment]
Resolved the following which should wrap up this PR: 

> ### TODO:
> * Using the keyboard to change a column position prevents any further keyboard navigation in Firefox.
> * Sometimes moving left on the headers causes the highlighted header to snap left. Seems to only be in Firefox as well. Not sure how important this is but it would be somewhat jarring to a user.
>   keyboard with an input added
> * `esc` shifts table weridly
> * when you use arrow keys to go through table cells and backtab, it shifts the header weirdly


### Remaining things: 
- > * bit of a lag when tabbing through certain parts of the table
- also there is a bit of a lag when using the keyboard to move a column to the left (when compared to moving to the right), this is because I am using [this code](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3421/files#diff-44f6d9cfee9dca5205c7134180d52558R401) to steal back focus from Focus Manager 
                                                         - as @AleksueiR pointed out the columns destroy themselves on move left, focus goes to the body, so I need to steal focus back and give it to `InternalFocusManager`

**Pull request merged**
