### PR TITLE
merge dgeni based project/api doc site code

### PR DESCRIPTION
**Pull request by ec-dev**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/34)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 47 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[docs/content/gulp-i18n-csv.md, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0a4w7oDjrpFj0CkTLG)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/content/gulp-i18n-csv.md#L1)):</sup>
Why do we need this file here? Or is this just an example?


---

<sup>**[src/app/common/router/router.module.js, line 6 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0a3TdlBHAadYV18EDS)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/src/app/common/router/router.module.js#L6)):</sup>
You also need to change the dependency name in `core.module.js`, line 20, to `app.common.router`. 


---

<sup>**[src/app/layout/layout.route.js, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0a2UGE1AC9KH3Y-UKw)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4fc0f6616a43fc0d680c5cda2ddcb66f0801511/src/app/layout/layout.route.js#L5)):</sup>
Is the `ngdoc` tag something that we don't need?


---

<sup>**[src/app/ui/toc/toc.controller.js, line 17 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0a3tW8OC7UYinWBT-S)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4fc0f6616a43fc0d680c5cda2ddcb66f0801511/src/app/ui/toc/toc.controller.js#L17)):</sup>
Why did you remove the `ngInject` comment?
@alyec, I think you mentioned the comment is no longer necessary, but I can't find anything about that. We are still planning to use https://github.com/olov/ng-annotate, right?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by alyec** [comment]
Reviewed 47 of 47 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gpagupAkgQV39Smv2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/app/js/app.js#L1)):</sup>
Can we add an entry to the gulp config so that `docs/app/js` is included in the JSCS and JSHint checks?


---

<sup>**[docs/content/getting_started.md, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gzmaDTGxrMEim37Rh)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/content/getting_started.md#L8)):</sup>
We now have this in our README file


---

<sup>**[docs/content/getting_started.md, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gzrWtf3Jw2SUmsHFV)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/content/getting_started.md#L9)):</sup>
Our repo isn't private so you can clone without a github account


---

<sup>**[docs/content/getting_started.md, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0h-1nW6ucE70nnu0D9)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/content/getting_started.md#L11)):</sup>
The rest of this should follow the README, we may want to split a separate question for how to contribute and point them to the contributing guidelines.


---

<sup>**[docs/content/getting_started.md, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gzSNJpWCf1oW_tDcl)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/content/getting_started.md#L28)):</sup>
We should probably revise this to either a proper link or a short inline description saying the viewer isn't ready yet.


---

<sup>**[gulpfile.js, line 514 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0h-esfOVrJ_cOl_p9z)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/gulpfile.js#L514)):</sup>
If docs-resources already depends on docs-build then docs-build is probably redundant here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by AleksueiR** [comment]
Reviewed 47 of 47 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/common/router/statehelper.js, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0km1OS5_SRW3dcAqxX)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/src/app/common/router/statehelper.js#L5)):</sup>
I guess this should read `provider`, not `service`. See here: https://github.com/angular/angular.js/blob/d077966ff1ac18262f4615ff1a533db24d4432a7/src/ngCookies/cookies.js#L21


---

<sup>**[src/app/ui/toc/toc.controller.js, line 17 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0kmM-AtM1tdw4_v7y4)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/90542ae8441ee6692db54a801ae3a6ba3065a132/src/app/ui/toc/toc.controller.js#L17)):</sup>
`@ngdoc` is missing and need to restore `@ngInject`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gpagupAkgQV39Smv2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/app/js/app.js#L1)):</sup>
Is it possible to submit a PR to another PR?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gpagupAkgQV39Smv2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/app/js/app.js#L1)):</sup>
don't know until you try :)


---

<sup>**[src/app/ui/toc/toc.controller.js, line 17 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0kmM-AtM1tdw4_v7y4)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/90542ae8441ee6692db54a801ae3a6ba3065a132/src/app/ui/toc/toc.controller.js#L17)):</sup>
Agree `@ngdoc`; but don't need to worry about `nginject`: https://gitter.im/fgpv-vpgf?at=562137c3fc3237f04a0c74b2


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r6.
Review status: 47 of 48 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/ui/toc/toc.controller.js, line 17 \[r7\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K10dqpIsCprovATyYtq)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d0e881785967ba56d6d879e08aac6f8d3b3948e7/src/app/ui/toc/toc.controller.js#L17)):</sup>
`@ngInject` if it is needed at all should be in the function preamble to be ES6 transpiler friendly.  Usually the inject plugin is smart enough to parse stuff like `function foo(... bunch of injected dependencies)` and do the right thing.  `'ngInject';` is only needed if the parser can't figure this out on its own.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gpagupAkgQV39Smv2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/app/js/app.js#L1)):</sup>
I think we should leave it out the current pull request, add it after. Also, I would like it as it's own independent JSCS JSHint check for the next sprint, and do the clean up during next sprint, then include in the main JSCS & JSHint check.


---

<sup>**[docs/content/gulp-i18n-csv.md, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0a4w7oDjrpFj0CkTLG)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/content/gulp-i18n-csv.md#L1)):</sup>
This is just an example.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gpagupAkgQV39Smv2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/app/js/app.js#L1)):</sup>
Sure, but to clarify I only think we should validate the code we write.  If we're just taking a bunch of stuff from Angular material I don't think we should waste time reformatting it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gpagupAkgQV39Smv2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/app/js/app.js#L1)):</sup>
Aly, I agree with you 100%. I want to clean up my code as well as the stuff I got from Angular Materia. I know for sure I need to pay more attentions to coding style. Just worry that the result of JSHint and JSCS might be massive. I should of run those in my gulp task at first place, were eager to produce something after the "redmine 6hr task" kept getting pushed to next iteration. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[docs/app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34#-K0gpagupAkgQV39Smv2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/927f2990c787e6b491d6ad03701277f94b1adfe5/docs/app/js/app.js#L1)):</sup>
Let's just merge this in and fix any style issues later.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by alyec** [comment]
Reviewed 10 of 10 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5, 10 of 10 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/34)

**Pull request merged**
