### PR TITLE
Major update to bookmark guide

### PR DESCRIPTION
**Pull request by james-rae**
## Description

Brought bookmark guide to a whole new level of glory

## Testing

Many unit tests added.

## Documentation

The file I changed is the documentation

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2735)

### CODE REVIEW

**Comment by AleksueiR** [comment]
This was kind of .... underwhelming ?...

**Comment by JahidAhmed** [comment]
Love the unit tests, good work!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2735#-:-LDMAd0x107lTmk4-ELk:b6cg1j2)*

**Comment by AleksueiR** [comment]
---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2735#-:-LDMIY2S3izVclBaMtYv:bvvsnyi)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2735)*

**Pull request merged**
