### PR TITLE
Interface for viewing per-layer datagrid

### PR DESCRIPTION
**Pull request by AleksueiR**
Shows data for individual layers in the filters panel.

No tests included yet.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/226)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 14 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8Kk9feI9YenSATrWBK:-K8Kk9feI9YenSATrWBL:-354119110) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d72ce1b012227677f8ed8139f31a06968ea7c47e/src/app/ui/filters/filters-default.directive.js#L9)):*
Not part of this changeset, but can someone add more to this comment?

---

*[src/app/ui/filters/filters-default.directive.js, line 35 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8KkKhfsmccGkmp-FLe:-K8KkKhgusM51psG4igL:-393293726) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d72ce1b012227677f8ed8139f31a06968ea7c47e/src/app/ui/filters/filters-default.directive.js#L35)):*
This comment is no longer valid as it seems the body is substantial now, and same with others below.

---

*[src/app/ui/toc/toc.service.js, line 879 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8KpvgUofCS5qPrp3_J:-K8KpvgUofCS5qPrp3_K:1045257272) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d72ce1b012227677f8ed8139f31a06968ea7c47e/src/app/ui/toc/toc.service.js#L879)):*
Can we change the name to something that indicates that this is layer specific?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by james-rae** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by spencerwahl** [comment]
Reviewed 14 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by AleksueiR** [comment]
Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/toc/toc.service.js, line 879 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8KpvgUofCS5qPrp3_J:-K8L3CwNUYXaC3t4RUIu:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d72ce1b012227677f8ed8139f31a06968ea7c47e/src/app/ui/toc/toc.service.js#L879)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 872 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8L2rJs1sHQGo7wIxAJ:-K8L2rJs1sHQGo7wIxAK:916843901) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4de70c22f70da8e00ab7a4355ef65a78a020b223/src/app/ui/toc/toc.service.js#L872)):*
typo *like like*

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/common/router/statemanager.constant.service.js, line 1 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8LAYVzm77rc3Qyx3zb:-K8LAYVzm77rc3Qyx3zc:-1755477349) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4725775818bb522b991344bd3996cad5b735684c/src/app/common/router/statemanager.constant.service.js#L1)):*
arrow?

---

*[src/app/common/router/statemanager.service.spec.js, line 50 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8LAssiO8I5Cfl0dp73:-K8LAssiO8I5Cfl0dp74:437051276) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4725775818bb522b991344bd3996cad5b735684c/src/app/common/router/statemanager.service.spec.js#L50)):*
use console.log(s1 + s2)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/common/router/statemanager.constant.service.js, line 1 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8LAYVzm77rc3Qyx3zb:-K8LCM4rCyraZLFlwEJp:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4725775818bb522b991344bd3996cad5b735684c/src/app/common/router/statemanager.constant.service.js#L1)):*
Done.

---

*[src/app/common/router/statemanager.service.spec.js, line 50 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8LAssiO8I5Cfl0dp73:-K8LBaWDBl-k74UNxriq:1371989713) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4725775818bb522b991344bd3996cad5b735684c/src/app/common/router/statemanager.service.spec.js#L50)):*
Will do.
I forgot to delete this log call actually - it's not needed.

---

*[src/app/ui/filters/filters-default.directive.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8Kk9feI9YenSATrWBK:-K8LAOG7nMl3qqT_U5lL:-479871297) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d72ce1b012227677f8ed8139f31a06968ea7c47e/src/app/ui/filters/filters-default.directive.js#L9)):*
Is it okay if I add comments in the next PR?

---

*[src/app/ui/toc/toc.service.js, line 872 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8L2rJs1sHQGo7wIxAJ:-K8LBpJnKVae6u9i5Qz4:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4de70c22f70da8e00ab7a4355ef65a78a020b223/src/app/ui/toc/toc.service.js#L872)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 4 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/ui/filters/filters-default.directive.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226#-K8Kk9feI9YenSATrWBK:-K8LIHR1b2UVSHK3LLom:1156104331) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d72ce1b012227677f8ed8139f31a06968ea7c47e/src/app/ui/filters/filters-default.directive.js#L9)):*
Yeah, it's not even covered in this PR.  I just noticed it as I was looking around.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/226)*

**Pull request merged**
