### PR TITLE
Basemap projection switch zooms to Canada instead of Africa

### PR DESCRIPTION
**Pull request by cynngah**
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1069

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1070)

### CODE REVIEW

**Comment by alyec** [comment]
Can you explain why we need to revert (i.e. could we patch this into `basemapService` instead)?  `geoService.mapManager.BasemapControl.basemapGallery` is just a really ugly chain.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1070#-:-KPnn4AjnLBeA_9cM9_U:b-yedf2r)*

**Comment by cynngah** [comment]
So it seems like something with the async timings where the select function in basemapService resolves before the bookmarkService resolves. So the source projection going into the localProjectPoint from the centerAndZoom function isn't actually the original source projection but the newly selected projection. This is because it already got updated from basemapService to the new projection. The call to geoService.mapManager.BasemapControl.basemapGallery avoids that.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1070#-:-KPnniQt5GnuGUy5tucb:b-7poag7)*

**Comment by alyec** [comment]
Can you leave a TODO comment in the code for that?  It sounds like either we have a race condition to clean up, or we need basemapService to expose the original projection somehow.  I haven't looked at all the code involved yet so I don't know all the details, but it might be worth looking at when we get some of this mythical refactoring time.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1070#-:-KPnpJWi3FY3PIBjWyoO:bpgri99)*

**Comment by cynngah** [comment]
:+1: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1070#-:-KPnrQ9Jd8y201EDqLdc:b-8fx2u7)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1070)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1070)*

**Pull request merged**
