### PR TITLE
fix(ui): add metadata url to results

### LINKED ISSUE #1155: Metadata Panel does not have a Link to go to the Metadata URL or Catalogue URL
When viewing a layers metadata panel, the user should be able to click a link to access the full Metadata document, or a the well formatted catalogue record.  These links should be present if either value is set for the record.

- [x] add Catalogue URL (`catalogueUrl`) field to layer nodes in the config schema to go along with the Metadata URL (`metadataUrl`)

### PR DESCRIPTION
**Pull request by milesap**
There is no Catalogue url currently specified in the schema, so only Metadata url is included. Metadata url's must be XML or the viewer won't be able to process them.

Closes #1155

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1185)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Metadata links should not be displayed in the "Contact information" section:


They should be probably given their own section, something like this:


---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-KRmv1pS7pwsDYEs8Qon:-KRmv1pTlrzli-C9sitN:b9lqxfb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74fc5fc278d415d88e1d46ad4df41aaf19ecfc07/src/app/ui/metadata/metadata-content.directive.js#L54)):*
> ```JavaScript
>                     // jscs:disable maximumLineLength
>                     if (self.display.requester.catalogueUrl) {
>                         metadata.append(`<p><a href="${self.display.requester.catalogueUrl}" target="_blank">Catalogue</a></p>`);
> ```

Metadata and catalogue labels need translations.

---

*[src/app/ui/toc/toc.service.js, line 382 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-KRmuPhRP3vnPNJU5nPD:-KRmuPhRP3vnPNJU5nPE:b-ow8o5u) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74fc5fc278d415d88e1d46ad4df41aaf19ecfc07/src/app/ui/toc/toc.service.js#L382)):*
> ```JavaScript
>             const requester = {
>                 id: entry.id,
>                 name: entry.name,
> ```

Extra comma.

---

*[src/app/ui/toc/toc.service.js, line 393 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-KRmugoQI7TtKeu8op0x:-KRmugoQI7TtKeu8op0y:btab7sn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74fc5fc278d415d88e1d46ad4df41aaf19ecfc07/src/app/ui/toc/toc.service.js#L393)):*
> ```JavaScript
> 
>             if (layer.metadataUrl) {
>                 requester.metadataUrl = layer.metadataUrl;
> ```

Pass metadata links to the panel through the data promise and not the requester object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-:-KRmtZPZvcotu6aSDyFH:b9caaw2)*

**Comment by mweech** [comment]
schema requires update to include catalogue URL in order to satisfy this requirement.  this cannot be merged until that has been done.

**Comment by milesap** [comment]
Schema update is part of this PR

**Comment by AleksueiR** [comment]
Schema is updated in this PR.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-:-KRnEpxzur1j6ce1XroV:bnrvq4k)*

**Comment by mweech** [comment]
then why is your PR comment saying the catalog URL is not included?

**Comment by milesap** [comment]
Issue #1155 was updated after first commit, second commit has the change

**Comment by AleksueiR** [comment]
Do we need to up bump schema's version number with this change?

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-:-KRnGIgJDIckl2wT8xS8:byubksp)*

**Comment by milesap** [comment]
It's not a breaking change, and not a part of bookmark so I'd say no. 

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-KRmv1pS7pwsDYEs8Qon:-KRnLFQ7w-XDaBFgslqu:b-isohll) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74fc5fc278d415d88e1d46ad4df41aaf19ecfc07/src/app/ui/metadata/metadata-content.directive.js#L54)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Metadata and catalogue labels need translations.
</details>
Added translations

---

*[src/app/ui/toc/toc.service.js, line 382 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-KRmuPhRP3vnPNJU5nPD:-KRnLvhSBf2JZjoUrOMb:bhofej8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74fc5fc278d415d88e1d46ad4df41aaf19ecfc07/src/app/ui/toc/toc.service.js#L382)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Extra comma.
</details>
Deleted

---

*[src/app/ui/toc/toc.service.js, line 393 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-KRmugoQI7TtKeu8op0x:-KRnM8C24LA6SJdh22so:b-gnn6p0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74fc5fc278d415d88e1d46ad4df41aaf19ecfc07/src/app/ui/toc/toc.service.js#L393)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Pass metadata links to the panel through the data promise and not the requester object.
</details>
Ok moved to data from requester object

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-:-KRnMH3OfdQ0UNfaCoYe:b-5e9hky)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-:-KRnNqvM_ickA6JGweo2:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185)*

**Comment by AleksueiR** [comment]
:lgtm: again :)

---

Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185#-:-KS1FMr-w2EyOc93CIr0:b41gkf2)*

**Comment by AleksueiR** [comment]
Reviewed 10 of 10 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1185)*

**Pull request merged**
