### PR TITLE
fix(geo): failing feature count retrieval

### PR DESCRIPTION
**Pull request by cynngah**
#570

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/775)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 270 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775#-KKE8MClaRXbCkMOnpHv:-KKE8MClaRXbCkMOnpHw:-1771094868) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44d33b86afa9f87cbded2771f7c7a7111e22e264/src/app/geo/legend.service.js#L270)):*
> ```JavaScript
>          * @return {Promise}          promise resolving with a feature count
>          */
>         function getServiceFeatureCount(layerUrl) {
> ```

You can reuse the function to avoid duplication:
```js
function getServiceFeatureCount(layerUrl, finalTry = false) {
    return $http.jsonp(
            `${layerUrl}/query?where=1=1&returnCountOnly=true&returnGeometry=false&f=json&callback=JSON_CALLBACK`) 
        .then(result => { 
            if (result) {
                return result.data.count;
            } else if (!finalTry) {
                return getServiceFeatureCount(layerUrl, true)
            } else {
                // return something to indicate failure
            }
        });
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend.service.js, line 280 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775#-KKEHVBB0w5vA-QZPFF4:-KKEHVBB0w5vA-QZPFF5:-118744975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e663830b8f39668afdb9262b95b41a2f5b954432/src/app/geo/legend.service.js#L280)):*
> ```JavaScript
>                         return getServiceFeatureCount(layerUrl, true);
>                     } else {
>                         return 'Could not get number of';
> ```

Translation please :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775)*

**Comment by cynngah** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend.service.js, line 270 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775#-KKE8MClaRXbCkMOnpHv:-KKFNfW24gFKYEfvBS2b:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44d33b86afa9f87cbded2771f7c7a7111e22e264/src/app/geo/legend.service.js#L270)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> You can reuse the function to avoid duplication:
> ```js
> function getServiceFeatureCount(layerUrl, finalTry = false) {
>     return $http.jsonp(
>             `${layerUrl}/query?where=1=1&returnCountOnly=true&returnGeometry=false&f=json&callback=JSON_CALLBACK`) 
>         .then(result => { 
>             if (result) {
>                 return result.data.count;
>             } else if (!finalTry) {
>                 return getServiceFeatureCount(layerUrl, true)
>             } else {
>                 // return something to indicate failure
>             }
>         });
> ```
</details>
Done.

---

*[src/app/geo/legend.service.js, line 280 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775#-KKEHVBB0w5vA-QZPFF4:-KKFNfpj76I1JEQalEJq:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e663830b8f39668afdb9262b95b41a2f5b954432/src/app/geo/legend.service.js#L280)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Translation please :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/775#-:-KKIjGmAo_jjzHXinpy_:1417088721)*

**Pull request merged**
