### PR TITLE
Add layer placeholders

### PR DESCRIPTION
**Pull request by spencerwahl**
issue #551

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/587)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 5 files at r1, 4 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 246 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHR9YUo7eqowNdhtR4g:-KHR9YUo7eqowNdhtR4h:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00d67ef9c702bf80a2f2f0fa914ab6460ecde3a5/src/app/geo/layer-registry.service.js#L246)):*
> ```JavaScript
> 
>                                 // replace placeholder with actual layer
>                                 let index = ref.legendService.legend.remove(layerRecord.state);
> ```

const

---

*[src/app/geo/layer-registry.service.js, line 310 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHRAabVPBTz6KWf7b08:-KHRAabVPBTz6KWf7b09:520741021) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00d67ef9c702bf80a2f2f0fa914ab6460ecde3a5/src/app/geo/layer-registry.service.js#L310)):*
> ```JavaScript
>                 // TODO: don't fail silently; throw an error; maybe shown message to the user.
>                 if (!l) {
>                     console.error(`Could not find layer to remove: ${layerId}`);
> ```

Can this be converted to `throw new Error` since we're pretty sure it shouldn't happen in normal usage?

---

*[src/app/geo/legend.service.js, line 186 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHRAtwe1Z3jSffKp5GE:-KHRAtwe1Z3jSffKp5GF:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00d67ef9c702bf80a2f2f0fa914ab6460ecde3a5/src/app/geo/legend.service.js#L186)):*
> ```JavaScript
>             }
> 
>             function addPlaceholder(layer) {
> ```

jsdoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Comment by spencerwahl** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 246 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHR9YUo7eqowNdhtR4g:-KHRDoxBXHv2Y-au1arj:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00d67ef9c702bf80a2f2f0fa914ab6460ecde3a5/src/app/geo/layer-registry.service.js#L246)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> const</details>
Done.

---

*[src/app/geo/layer-registry.service.js, line 310 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHRAabVPBTz6KWf7b08:-KHRDpYh7_1zM2KM25Wq:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00d67ef9c702bf80a2f2f0fa914ab6460ecde3a5/src/app/geo/layer-registry.service.js#L310)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can this be converted to `throw new Error` since we're pretty sure it shouldn't happen in normal usage?</details>
Done.

---

*[src/app/geo/legend.service.js, line 186 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHRAtwe1Z3jSffKp5GE:-KHRDqTYxqc3JgYGDVgm:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00d67ef9c702bf80a2f2f0fa914ab6460ecde3a5/src/app/geo/legend.service.js#L186)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 5 files at r1, 4 of 7 files at r2, 2 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/app/geo/layer-registry.service.js, line 218 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUasTfzcS73l6wF_Ij:-KHUasTfzcS73l6wF_Ik:1298687105) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/geo/layer-registry.service.js#L218)):*
> ```JavaScript
>                     const layer = service.generateLayer(layerConfig);
> 
>                     const layerRecord = {
> ```

Can you add a todo here to create layer record only once?

---

*[src/app/geo/layer-registry.service.js, line 225 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUb6KL6MIACuytOpV1:-KHUb6KL6MIACuytOpV2:2010001138) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/geo/layer-registry.service.js#L225)):*
> ```JavaScript
>                     // add a placeholder and store it
>                     ref.legendService.addPlaceholder(layerRecord);
>                     ref.legendService.setLayerLoadingFlag(layerRecord.state, true);
> ```

Not needed, I think, as the placeholders start with the loading state turned on.

---

*[src/app/geo/layer-registry.service.js, line 258 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUbJycl74_21BLNVnp:-KHUbJydL_Soa2XFqmdb:-1897205351) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/geo/layer-registry.service.js#L258)):*
> ```JavaScript
>                             // FIXME layers that fail on initial load will never be added to the layers list
>                             ref.legendService.setLayerState(layerRecord.state, layerStates.error, 10100);
>                             ref.legendService.setLayerLoadingFlag(layerRecord.state, false, 10100);
> ```

I think delay should be `100`, not `10100`.

---

*[src/app/ui/toc/toc.service.js, line 213 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUbjiLN3oC61Mq0rBq:-KHUbjiLN3oC61Mq0rBr:746781809) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/ui/toc/toc.service.js#L213)):*
> ```JavaScript
>                         // restore original visibility, so if he removed and restored already invisible layer,
>                         // it is restored also invisible
>                         entry.setVisibility(isEntryVisible);
> ```

I think you need to reset `entry.removed` to `false` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 218 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUasTfzcS73l6wF_Ij:-KHVAzU48AJFRWugNXBQ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/geo/layer-registry.service.js#L218)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Can you add a todo here to create layer record only once?</details>
Done.

---

*[src/app/geo/layer-registry.service.js, line 225 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUb6KL6MIACuytOpV1:-KHVAzlIvQZAd2AS1Sdj:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/geo/layer-registry.service.js#L225)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Not needed, I think, as the placeholders start with the loading state turned on.</details>
Done.

---

*[src/app/geo/layer-registry.service.js, line 258 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUbJycl74_21BLNVnp:-KHVB-AFJdJFVEjylbAe:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/geo/layer-registry.service.js#L258)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I think delay should be `100`, not `10100`.</details>
Done.

---

*[src/app/ui/toc/toc.service.js, line 213 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587#-KHUbjiLN3oC61Mq0rBq:-KHVB-anEPEOyn-LIpFv:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c9f38d1b7040b682f1737706f45f2cb0a50f89a/src/app/ui/toc/toc.service.js#L213)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I think you need to reset `entry.removed` to `false` here.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/587)*

**Pull request merged**
