### PR TITLE
fix (ui): migrate metadata and settings to panels api

### PR DESCRIPTION
**Pull request by ShrutiVellanki**
## Description

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3364

Converts Settings and Metadata to `PanelsAPI`
- migrated panels, separated header + body
- doesn't rely on `stateManager.setActive`
- migrated expand metadata panel to dialog (before I knew I didn't have to do that)
- mobile compatible (test with small and medium screen sizes)
- see [here](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3364#issuecomment-477261488) under discussed/resolved for approach to using panels api to toggle settings and metadata

## [Testing](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/migrate-metadata/dev/samples/index-samples.html?sample=29)

:eyes: 
- good samples for metadata testing: `29`, `48`, `49`

### Checklist

- [ ] works in IE11
- [ ] works in Edge
- [ ] works with projection change
- [ ] works with language change
- [ ] works via config file
- [ ] works via wizard
- [ ] works via API
- [ ] works via RCS
- [ ] works via bookmark load
- [ ] works in auto-legend
- [ ] works in structured legend
- [ ] works on layer reload
- [ ] datagrid works
- [ ] identify works

## Documentation

inline comments

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated
- [x] original issue has been reviewed & updated to reflect the PR content

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3385)

### CODE REVIEW

**Comment by spencerwahl** [comment]
___
*[src/app/ui/settings/settings.run.js, line 2 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3385#-LbP-gPC5Rh8bO_AvkLq:-LbP18O0Ec1aZobvcVA7:bqmxsf9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/56760c23023de40f985f64137e9c3a6647dfb9d3/src/app/ui/settings/settings.run.js#L2)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

This file was changed from TypeScript to JavaScript, any reason it can't be TypeScript?
</blockquote></details>

It was causing that prod build error

**Comment by dane-thomas** [comment]
Just as a note, the table isn't opening in the test build. Not sure if this is an actual problem in the code or if it's just something wrong with the build.

**Comment by ShrutiVellanki** [comment]
> Just as a note, the table isn't opening in the test build. Not sure if this is an actual problem in the code or if it's just something wrong with the build.

Hi the table is building: http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/migrate-metadata/dev/samples/index-samples.html

**Comment by dane-thomas** [comment]
:+1: does seem to be working now

**Pull request merged**
