### PR TITLE
fix(ui): navcontrols misplaced in full-screen mode

### LINKED ISSUE #1325: Right hand side toolbar moves up and overlaps the Overview Map in some scenarios
Tested on build :http://fgpv.cloudapp.net/demo/v1.4.0-4/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

Toolbar on the right hand side of the Viewer overlaps the Overview Map in some scenarios. Issue seen in all 3 browsers. Steps to reproduce

-  Load the FGP site
- Select "Export" on the left hand side navigation
- Close the export window with or without saving
- Navigate to "Full Screen"
- When the map loads completely, RHS toolbar is seen on the top right corner with the overview map

screenhunter_2595 nov 02 15 55

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #1325

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1327)

### CODE REVIEW

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1327#-:-KVeGCiFFXtrFw2Sk6o0:bnfp4nl)*

**Comment by AleksueiR** [comment]
No typos? Success! :dancer: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1327#-:-KVeINUPN6tSW7i9Wmf5:b-1sszv1)*

**Comment by milesap** [comment]
Fullscreen mode is broken when testing on [this page](http://fgpv.cloudapp.net/demo/users/AleksueiR/1325-navcontrols-not-behaving-in-full-screen-mode/samples/index-fgp-en.html?keys=Airports). Clicking on the menu, then fullscreen expands the map and everything goes blank. Reproduced in Firefox as well

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1327#-:-KVeHmz_3cMBAfBbKsik:b6jb6mi)*

**Comment by AleksueiR** [comment]
Good catch - git reset didn't work properly. Fixed now.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1327#-:-KVeJoGkNFOzmEGNchQt:bx9usyb)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1327)*

**Comment by milesap** [comment]
:+1: :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1327#-:-KVeMcJymAINGNpuxnIA:buan1gt)*

**Pull request merged**
