### PR TITLE
docs: resolve markdown not rendered in configService

### PR DESCRIPTION
**Pull request by ec-dev**
caused by template issue: common.template.html missing marked filter.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/67)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[docs/config/templates/common.template.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/67#-K2E1ZX74KB0rwtZ-fJx)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/39a2259aa2a28d603e8afb75e7850d015072711f/docs/config/templates/common.template.html#L5)):</sup>
We use spaces after opening curly bracket and space before closing curly bracket in fgpv code. Do you want to do the same for consistency?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/67)

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/67)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/67)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/67)

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[docs/config/templates/common.template.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/67#-K2E1ZX74KB0rwtZ-fJx)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/39a2259aa2a28d603e8afb75e7850d015072711f/docs/config/templates/common.template.html#L5)):</sup>
sorry Johann, my bad, this {$ ... $} is eval expression for the nunjucks template. The bracket gets rendered as is. I added this to common template to catch anything that does not have dedicated template; e.g. function and service. Hence, in function, we get (function) or in service we get (service). Will remove them after I've create the specific template.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/67)

**Pull request merged**
