### PR TITLE
Prevent the north pole icon being set when the spatial reference is not Lambert

### LINKED ISSUE #2771: Console error when Mercator is set as default projection
An error related to projection shows up in console when setting Mercator as the default projection.

capture

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes #2771 

Prevent the north pole icon being set when the spatial reference is not Lambert and add some constants.
## Testing

sample 44
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)

### CODE REVIEW

**Comment by ShrutiVellanki** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae, @dane-thomas, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Comment by dane-thomas** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @barryytm and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Comment by barryytm** [comment]
Review status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ShrutiVellanki, @dane-thomas, @james-rae, and @JahidAhmed)

---

*[src/app/geo/geo.constant.service.js, line 61 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-LEoMxSWANkWmnoAQoej:-LEtTbk49gHuJWTgEYHb:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7c342ae54b4353e60e5d080ff20e9dea56e1825f/src/app/geo/geo.constant.service.js#L61)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this is backwards to what ESRI publishes on their web servers. `3857` should be the `latestWkid`
</blockquote></details>

Done, thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Comment by barryytm** [comment]
I will modify the other sample config files in another PR since there are too many.

---

Review status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ShrutiVellanki, @dane-thomas, @james-rae, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-:-LEtU4T_B-OZUPXcDcj9:blq28zv)*

**Comment by dane-thomas** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Comment by JahidAhmed** [comment]
I don't see the flag anymore for lambert basemaps

---

Review status: all files reviewed, 1 unresolved discussion (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-:-LEt_7hq09srjsgDxFdd:bf0bd8t)*

**Comment by JahidAhmed** [comment]
Wait nvm, just saw the comment above. My bad. :lgtm: 

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-:-LEt_crw5N7TwQbUy6Ya:b-swzzyu)*

**Comment by james-rae** [comment]
> I will modify the other sample config files in another PR since there are too many.

Will want this done before our next QA build.

---

Reviewed 4 of 7 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @james-rae and @barryytm)

---

*[src/app/core/config.service.js, line 446 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-LEtgmQ_2PKLQpd5GZ27:-LEtgmQ_2PKLQpd5GZ28:b-c17ndj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50fb2ffb4d8bcefe497635caa6db6ed6fd09a83f/src/app/core/config.service.js#L446)):*
> ```JavaScript
>                         "enabled": false,
>                         "spatialReference": {
>                             "wkid": Geo.SpatialReference.WEB_MERCATOR.latestWkid
> ```

this would be incorrect now.  want `102100` being assigned.

---

*[src/content/samples/config/config-sample-44.json, line 331 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-LEtgEQJD-91kropB3of:-LEtgEQJD-91kropB3og:b-j43gbg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50fb2ffb4d8bcefe497635caa6db6ed6fd09a83f/src/content/samples/config/config-sample-44.json#L331)):*
> ```JSON
>         "extentSetId": "EXT_NRCAN_Lambert_3978",
>         "lodSetId": "LOD_NRCAN_Lambert_3978",
>         "hasNorthPole": true
> ```

we're going to need to update all the relevant sample files. else all of them will have north pole turned off (edit just saw comment on main thread of PR).  we'll need to put something on the release notes notifying people of this too...ugly :(

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-:-LEthCGq0IUS6FxvY-E4:b-1lcya7)*

**Comment by dane-thomas** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @james-rae and @barryytm)

---

*[src/content/samples/config/config-sample-44.json, line 331 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-LEtgEQJD-91kropB3of:-LEtiGfX9Qo-EHb80r4p:b-b3y7qc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50fb2ffb4d8bcefe497635caa6db6ed6fd09a83f/src/content/samples/config/config-sample-44.json#L331)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

we're going to need to update all the relevant sample files. else all of them will have north pole turned off (edit just saw comment on main thread of PR).  we'll need to put something on the release notes notifying people of this too...ugly :(
</blockquote></details>

What happens if someone decides to put `"hasNorthPole: true"` for an unsupported projection (i.e. Mercator)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Comment by barryytm** [comment]
Review status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @JahidAhmed, @dane-thomas, and @james-rae)

---

*[src/app/core/config.service.js, line 446 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-LEtgmQ_2PKLQpd5GZ27:-LEtnPEL6SX5TaYfwDd0:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50fb2ffb4d8bcefe497635caa6db6ed6fd09a83f/src/app/core/config.service.js#L446)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this would be incorrect now.  want `102100` being assigned.
</blockquote></details>

Done, thanks

---

*[src/content/samples/config/config-sample-44.json, line 331 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-LEtgEQJD-91kropB3of:-LEtoAMa2z2C-3wleuew:bp5y10n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50fb2ffb4d8bcefe497635caa6db6ed6fd09a83f/src/content/samples/config/config-sample-44.json#L331)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

What happens if someone decides to put `"hasNorthPole: true"` for an unsupported projection (i.e. Mercator)?
</blockquote></details>

If `hasNorthPole` is set to false, it will result the same error as before.  The point of having `hasNorthPole` is to let users to make that decision and they should know if the projection has north pole mapped to it or not.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Comment by dane-thomas** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @james-rae)

---

*[src/content/samples/config/config-sample-44.json, line 331 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772#-LEtgEQJD-91kropB3of:-LEtqzvMBXwqy_cR3cMN:bxqe6pj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50fb2ffb4d8bcefe497635caa6db6ed6fd09a83f/src/content/samples/config/config-sample-44.json#L331)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

If `hasNorthPole` is set to false, it will result the same error as before.  The point of having `hasNorthPole` is to let users to make that decision and they should know if the projection has north pole mapped to it or not.
</blockquote></details>

Sounds good to me :+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Comment by james-rae** [comment]
Reviewed 2 of 7 files at r2, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)*

**Pull request merged**
