### PR TITLE
XSLT Injection and SVG Caching

### PR DESCRIPTION
**Pull request by alyec**
Adds two items for the build cleanup #768 (will be split into 2 or 3 PRs)

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/804)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 10 files at r1, 12 of 12 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 10 files at r1, 12 of 12 files at r2, 4 of 5 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulp.config.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804#-KKnS-p2Mu8_l9moBt_E:-KKnS-p2Mu8_l9moBt_F:-269000770) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8efd9fa7762bc1f9f1deb683c3103b8ab45464e8/gulp.config.js#L101)):*
> ```JavaScript
>         watchhtml: src + '**/*.html',
>         watchconfig: src + '*.json',
>         xslt: src + 'content/metadata/xstyle_default_en-CA.xsl',
> ```

`${src}content/metadata/xstyle_default_en-CA.xsl` for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulp.config.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804#-KKnS-p2Mu8_l9moBt_E:-KLIaD4gDxLpm-I8Mc6Z:-775117143) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8efd9fa7762bc1f9f1deb683c3103b8ab45464e8/gulp.config.js#L101)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `${src}content/metadata/xstyle_default_en-CA.xsl` for consistency?
</details>
I wanted to make it clear that this is a language neutral file.  I don't think `en-CA` makes sense but I'm open to other suggestions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulp.config.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804#-KKnS-p2Mu8_l9moBt_E:-KLLic48dbM4d3NDlPNn:-270826267) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8efd9fa7762bc1f9f1deb683c3103b8ab45464e8/gulp.config.js#L101)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I wanted to make it clear that this is a language neutral file.  I don't think `en-CA` makes sense but I'm open to other suggestions.
</details>
Oh, didn't mean to write `en-CA`. I was just pointing out that a line above (`svgCache: ${src}content/svgCache`) uses es6 string template instead of `+`.

My comment should have read as `${src}content/metadata/xstyle_default_i18n.xsl`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by alyec** [comment]
Review status: 21 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[gulp.config.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804#-KKnS-p2Mu8_l9moBt_E:-KLME0mSl7UlQr49Ue6M:-1660640342) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8efd9fa7762bc1f9f1deb683c3103b8ab45464e8/gulp.config.js#L101)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Oh, didn't mean to write `en-CA`. I was just pointing out that a line above (`svgCache: ${src}content/svgCache`) uses es6 string template instead of `+`.
> 
> My comment should have read as `${src}content/metadata/xstyle_default_i18n.xsl`
</details>
I changed over the last few entries.  Most of the gulp config still uses + concatenation but I'm not changing all of it right now (that sounds like a student task).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulp.config.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804#-KKnS-p2Mu8_l9moBt_E:-KLN5T3BTahk0YlSUFhN:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8efd9fa7762bc1f9f1deb683c3103b8ab45464e8/gulp.config.js#L101)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I changed over the last few entries.  Most of the gulp config still uses + concatenation but I'm not changing all of it right now (that sounds like a student task).
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804#-:-KLN5_N_BsgKDEBdlwDs:1417088721)*

**Comment by james-rae** [comment]
Reviewed 4 of 5 files at r4, 5 of 5 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Comment by cynngah** [comment]
Reviewed 3 of 10 files at r1, 11 of 12 files at r2, 2 of 5 files at r3, 3 of 5 files at r4, 5 of 5 files at r5, 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/804)*

**Pull request merged**
