### PR TITLE
fix(ui): basemap check in front, set on init

### PR DESCRIPTION
**Pull request by james-rae**
Place selected basemap checkmark before the text, so people can see it.  
Set the selected property at init so the first basemap has the checkmark.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/436)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/436)*

**Comment by cynngah** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/436)*

**Comment by AleksueiR** [comment]
Check mark should be on the right; truncate the long basemap name to fit it in instead.

---

Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/436#-:-KEGeJp1H1sM99MygvjS:808270232)*

**Comment by james-rae** [comment]
Abandoned, relevant code used in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/441

**Pull request closed without merging**
