### PR TITLE
ENHANCE zoom to details for scale dependent layers

### PR DESCRIPTION
**Pull request by cynngah**
#777 

Also fix the scale dependent layer endpoint URL

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/856)

### CODE REVIEW

**Comment by alyec** [comment]
`bug(config)` isn't a valid commit type
Also, I don't think this addresses the second suggestion within #777 (not moving the center if the current extent overlaps with the scale dependent layer's extent)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856#-:-KMFL_YJcnCT3cB9WYaa:-336176695)*

**Comment by AleksueiR** [comment]
Agree, second suggestion is not implemented.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856#-:-KMOn0yhx6TDQUPirBs-:786370916)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/layer-registry.service.js, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856#-KMUWuP8dUIXF1jODJWi:-KMUWuP8dUIXF1jODJWj:-1812698586) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbae2a317b425d0b9756a043f6b76b9444e33dbc/src/app/geo/layer-registry.service.js#L416)):*
> ```JavaScript
>                         gextent.x1, gextent.y1, gextent.sr);
> 
>                     // check if current map extent already in layer extent
> ```

Can you update the comment? "Check if map extent and layer extent intersect".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856#-:-KMUWs6sFhAZbMvajtTW:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/856)*

**Pull request merged**
