### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by milesap**
develop v1.6.0 to master

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1777)

### CODE REVIEW

**Comment by milesap** [comment]
Reviewed 103 of 103 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1777)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bower.json, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1777#-KfS7ibtRMy_0J0pxV_g:-KfS7ibtRMy_0J0pxV_h:ba7sjxk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8b0d5815c91e70b5523535558bcea9899eeb5c67/bower.json#L4)):*
> ```JSON
>   "name": "r2v2",
>   "description": "FGP R2 Viewer",
>   "version": "1.6.0",
> ```

Did you update the version number in `package.json` as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1777)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bower.json, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1777#-KfS7ibtRMy_0J0pxV_g:-KfS8zGa1iyuLGTdGOc8:b-x0nk7a) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8b0d5815c91e70b5523535558bcea9899eeb5c67/bower.json#L4)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Did you update the version number in `package.json` as well?
</blockquote></details>

Yessir

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1777)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bower.json, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1777#-KfS7ibtRMy_0J0pxV_g:-KfS98vQynnegHKf6Pgg:bsf33o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8b0d5815c91e70b5523535558bcea9899eeb5c67/bower.json#L4)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Yessir
</blockquote></details>

cool :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1777)*

**Pull request merged**
