### PR TITLE
feat(ui): second part of the layer import ui component

### PR DESCRIPTION
**Pull request by AleksueiR**
incremental update
no comments yet
no tests yet
more sass

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/348)

### CODE REVIEW

**Comment by alyec** [comment]
I've added some feedback on comments.  Feel free to address them in a separate PR.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/stepper-item.html, line 42 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KB9sSrfm5RRN7RXww9f:-KB9sSrfm5RRN7RXww9g:-2054281002) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f64be1722365eb16a501f0a1f4c07ef4300c2d35/src/app/ui/common/stepper-item.html#L42)):*
Either here or in the directive top comments can you document the onComplete trigger (and under which conditions it should be used)?

---

*[src/app/ui/loader/loader-file.directive.js, line 110 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KB9tHmheydMR-oUbi0I:-KB9tHmheydMR-oUbi0J:2016646595) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f64be1722365eb16a501f0a1f4c07ef4300c2d35/src/app/ui/loader/loader-file.directive.js#L110)):*
docs on `forward` and `back` would help as tracking state changes can get tricky

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-:-KB9tXrvuhcc5YN1w9o3:333620774)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/stepper-item.html, line 42 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KB9sSrfm5RRN7RXww9f:-KB9ulnBucVU-x0hG34Q:640348047) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f64be1722365eb16a501f0a1f4c07ef4300c2d35/src/app/ui/common/stepper-item.html#L42)):*
Now that you mentioned it, `onContinue` would be the better name.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348)*

**Comment by AleksueiR** [comment]
Added some comments.

---

Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/loader/loader-file.directive.js, line 110 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KB9tHmheydMR-oUbi0I:-KBDL6KprfiCPCcrY3C9:1888026826) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f64be1722365eb16a501f0a1f4c07ef4300c2d35/src/app/ui/loader/loader-file.directive.js#L110)):*
Will add later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-:-KBDL9tM7wnUKDB4rdOw:-57658285)*

**Comment by spencerwahl** [comment]
Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/ui/common/stepper-item.directive.js, line 11 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KBEH3LQMVFBLTB9uhsi:-KBEH3LQMVFBLTB9uhsj:578955464) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2b450097d221b0f5af66d78f58599aeff2601eb4/src/app/ui/common/stepper-item.directive.js#L11)):*
Out of context `is a step` is a bit confusing.  I'm assuming this is part of a workflow provided by that fancy angular library you found?  Can you add a bit about where it should be used (i.e. does stepper-item need to be / recommended to be nested within any other directives), and its relation to the library?  Feel free to mark a TODO and move on for now.

---

*[src/app/ui/common/stepper-item.directive.js, line 14 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KBEGwUQ1wD-3LdKxxIu:-KBEGwUQ1wD-3LdKxxIv:960608115) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2b450097d221b0f5af66d78f58599aeff2601eb4/src/app/ui/common/stepper-item.directive.js#L14)):*
should this read `not shown`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/stepper-item.directive.js, line 11 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KBEH3LQMVFBLTB9uhsi:-KBEIURfHwyVcFFSbZ3G:-176588279) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2b450097d221b0f5af66d78f58599aeff2601eb4/src/app/ui/common/stepper-item.directive.js#L11)):*
Will add in the next PR.  Marked as todo in my code.

---

*[src/app/ui/common/stepper-item.directive.js, line 14 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348#-KBEGwUQ1wD-3LdKxxIu:-KBEISLZzaXJXuiRZmAc:-1461567895) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2b450097d221b0f5af66d78f58599aeff2601eb4/src/app/ui/common/stepper-item.directive.js#L14)):*
Will be fixed in the next PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/348)*

**Pull request merged**
