### PR TITLE
fix(export): corrected canvas-to-blob polyfill

### LINKED ISSUE #2243: Unable to save the exported map in IE
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc4/dev/samples/index-samples.html
http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc4/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction

For some reason, export image cannot be saved in IE.  I cannot save this in Firefox too.Please investigate

image

image

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2243

## Testing
eagle eyes
on IE & Chrome

## Documentation
None

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2258)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Demo works :lgtm: 

---

Reviewed 54 of 54 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2258#-:-Kpu4U-QGYcQSXSVZO6S:bed8066)*

**Comment by AleksueiR** [comment]
I tested export in Chrome, IE, and Firefox.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2258#-:-Kpu513F8Wa3B0dAluhM:b-kcy3c2)*

**Comment by JahidAhmed** [comment]
:lgtm: WOMM in Firefox and IE

---

Reviewed 54 of 54 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2258#-:-Kpu5COhUBSR_Ix_Xfj3:b-11707m)*

**Comment by james-rae** [comment]
Reviewed 54 of 54 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2258)*

**Pull request merged**
