### PR TITLE
RCS Support

### PR DESCRIPTION
**Pull request by james-rae**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1961 , https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1666

Re-enables RCS Layer support for the following

* Keys on Site URL
* Keys on Map HTML Tag
* Back to Cart
* Bookmark Restore
* Projection Change
* Language Change

Re-adds `bookmark-decode.html`.

Updated the `fpg` test pages.

Removed piles of pre-refactor code.

Pending fix: Prevent RCS Layers that are `Removed` but still in the "undoable" state from getting piped onto the Back-to-Cart output.

## Testing

Testing against local build, including modded tags, modded back-to-cart switcheroos, medleys of config based, tag based, and URL based layers.

## Documentation

I have a lovely text file that somewhat explains things.

## Checklist

- [x] commits messages follow the guidelines
- [ ] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is no longer a *muffin offence* to open a PR with any of the above checklist items incomplete, as we have removed unit tests (a wise decision).

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2132)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Any RCS keys to test the demo with?

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132#-KomhXVIMo8S35bIKeDA:-KomhXVIMo8S35bIKeDB:byn8282) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f14ca5d43b976d6356c54b1c9cf543fd69d55f7a/src/app/geo/legend.service.js#L55)):*
> ```JavaScript
>     }
> 
>     function addLayerDefinition(layerDefinition) {
> ```

Just the comments are missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132#-:-Komhua1oLPCGF56Wsz1:bpyj495)*

**Comment by james-rae** [comment]
same as before.  any of
`JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132#-:-KomiuoSpYjCN5CTtDXp:btaj82s)*

**Comment by james-rae** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132#-KomhXVIMo8S35bIKeDA:-KomoZh8sDYrX7xoPJ2o:bn1r2q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f14ca5d43b976d6356c54b1c9cf543fd69d55f7a/src/app/geo/legend.service.js#L55)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Just the comments are missing.
</blockquote></details>

Aly's commit. Assigning full blame. Donethanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132)*

**Comment by AleksueiR** [comment]
Demo works :lgtm:

One thing I noticed though - order of RCS layers is no preserved in the bookmark. 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132#-:-Komt_99z4jlkSNs7BDl:b-lo2bwn)*

**Comment by james-rae** [comment]
Yeah.  We can investigate more. It's a bit funny because the process is constantly removing and re-adding things to the config's `layers` array. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132#-:-KomuPxtVq8mCslLtRKc:bnh69np)*

**Comment by AleksueiR** [comment]
Can you make an issue for that?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2132#-:-KomurYsRRMFCIC7RiRb:bv1dkcj)*

**Pull request merged**
