### PR TITLE
refactor(ui): remove objId dependency on column 0

### LINKED ISSUE #495: Datagrid zoom-to-feature depends on object-id in first column
See file `filters-default.directive.js`
`// FIXME: Assumes OBJECTID always first column`

This code always assumes the object id of the feature is in the first column of the grid.  In reality, it could be in any column, or not in a column at all (object id has no meaning to a user, there is no value in showing it).

In RAMP, we had an always-hidden grid column at the end of the table that contained system-ish information, including the objectid.  This is a potential fix for this.

### PR DESCRIPTION
**Pull request by cynngah**
Closes #495 

- OBJECTID no longer assumed to be first column in datatable.
- Created hidden last column to store OBJECTID.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/532)

### CODE REVIEW

**Comment by james-rae** [comment]
*[src/app/ui/filters/filters-default.directive.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJH-3Oi7Qg6Fv7qQ5u:-KGJH-3Oi7Qg6Fv7qQ5v:1173799650) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L75)):*
it will not always be named `OBJECTID`.  Instead, use `data[featureIdx].oidField`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 98 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJJaZVVp-Iq-qp_piH:-KGJJaZVVp-Iq-qp_piI:-853101688) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L98)):*
You should be able to remove the code from the FIXME to this curly brace

---

*[src/app/ui/filters/filters-default.directive.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJJOAx4o8hbWlXKdpA:-KGJJOAyvm2UHcZlJNqZ:-1482100741) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L99)):*
Should this be row[oidInd]?

---

*[src/app/ui/filters/filters-default.directive.js, line 150 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJHasFyblJ3beYhPbf:-KGJHasGoQEp7yhPl9RC:-1755124555) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L150)):*
This can go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by cynngah** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJH-3Oi7Qg6Fv7qQ5u:-KGJPGXXcRzjhvqvlM5j:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L75)):*
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 98 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJJaZVVp-Iq-qp_piH:-KGJPEk4f6eu7eiBVabl:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L98)):*
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJJOAx4o8hbWlXKdpA:-KGJPF75YclZHERI6SJe:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L99)):*
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 150 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGJHasFyblJ3beYhPbf:-KGJPF_ZtnrrI_mQFVwx:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9c43d277b2f0cf11e6bdb324428c20d569c8567/src/app/ui/filters/filters-default.directive.js#L150)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 74 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGMZiEkWKqmUIaAsPbm:-KGMZiEkWKqmUIaAsPbn:-1208683001) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/86ed556a5b5ebce4897ec77a71624ee4208e8b13/src/app/ui/filters/filters-default.directive.js#L74)):*
Why not use [`Array.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)? We have a polyfill for that now.

---

*[src/app/ui/filters/filters-default.directive.js, line 143 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGMZCSt_Y3mL5mnugKl:-KGMZCSt_Y3mL5mnugKm:-1294383065) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/86ed556a5b5ebce4897ec77a71624ee4208e8b13/src/app/ui/filters/filters-default.directive.js#L143)):*
Why do you need two listeners? Isn't just a click listener enough?
You can use arrow functions for callbacks as well.

---

*[src/app/ui/filters/filters-default.directive.js, line 147 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGMYw6rFE06yqsj7lF1:-KGMYw6rFE06yqsj7lF2:1881247700) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/86ed556a5b5ebce4897ec77a71624ee4208e8b13/src/app/ui/filters/filters-default.directive.js#L147)):*
What is `featureIndex` and where is it coming from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by cynngah** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 74 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGMZiEkWKqmUIaAsPbm:-KGNCoTgHsz-fzv9rM5u:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/86ed556a5b5ebce4897ec77a71624ee4208e8b13/src/app/ui/filters/filters-default.directive.js#L74)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by james-rae** [comment]
*[src/app/ui/filters/filters-default.directive.js, line 147 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGMYw6rFE06yqsj7lF1:-KGNKeiH-zo5FkL9ItXS:568302374) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/86ed556a5b5ebce4897ec77a71624ee4208e8b13/src/app/ui/filters/filters-default.directive.js#L147)):*
It is the integer index of the service.  Sub-layer ID would be an alternate term.  It comes from the `featureId` property of the legend entry (that triggers the grid)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 147 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532#-KGMYw6rFE06yqsj7lF1:-KGNLhbgQHHQYwln9K-u:-550538064) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/86ed556a5b5ebce4897ec77a71624ee4208e8b13/src/app/ui/filters/filters-default.directive.js#L147)):*
Yeap, I just couldn't understand what it was doing in `self.display.data.featureIndex`. It's all good now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/532)*

**Pull request merged**
