### PR TITLE
feat(ui): add rudimentary layer tree

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/43)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 9 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/ui/toc/layer-item.directive.js, line 17 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K15hnJ-l14_eX9mWPhV)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5dd91cb835fbc9b1f308b5f5ba7c4648f4ed6d36/src/app/ui/toc/layer-item.directive.js#L17)):</sup>
const


---

<sup>**[src/app/ui/toc/toc.controller.js, line 33 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K15i7Xlfw_9_aHd_0nj)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5dd91cb835fbc9b1f308b5f5ba7c4648f4ed6d36/src/app/ui/toc/toc.controller.js#L33)):</sup>
Arrow functions!


---

<sup>**[src/app/ui/toc/toc.service.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K15iP6gwKUFACvcB8Am)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5dd91cb835fbc9b1f308b5f5ba7c4648f4ed6d36/src/app/ui/toc/toc.service.js#L20)):</sup>
const


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43)

**Comment by AleksueiR** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[src/app/ui/toc/layer-item.directive.js, line 17 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K15hnJ-l14_eX9mWPhV)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5dd91cb835fbc9b1f308b5f5ba7c4648f4ed6d36/src/app/ui/toc/layer-item.directive.js#L17)):</sup>
The danger of using snippets. For people using Atom, try `angularjs-styleguide-snippets-es6`.

Done.


---

<sup>**[src/app/ui/toc/toc.controller.js, line 33 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K15i7Xlfw_9_aHd_0nj)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5dd91cb835fbc9b1f308b5f5ba7c4648f4ed6d36/src/app/ui/toc/toc.controller.js#L33)):</sup>
Done.


---

<sup>**[src/app/ui/toc/toc.service.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K15iP6gwKUFACvcB8Am)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5dd91cb835fbc9b1f308b5f5ba7c4648f4ed6d36/src/app/ui/toc/toc.service.js#L20)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43)

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43)

**Comment by jolevesq** [comment]
Reviewed 5 of 9 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/ui/sidenav/menulink.directive.js, line 37 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19eIBVryhcX_lSMcUD)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/sidenav/menulink.directive.js#L37)):</sup>
Is there a typo in Sceleton?


---

<sup>**[src/app/ui/sidenav/menulink.directive.js, line 46 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19ealWZNXtNplLDC3T)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/sidenav/menulink.directive.js#L46)):</sup>
Typo again?


---

<sup>**[src/app/ui/toc/layer-item.directive.js, line 10 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19eiyAASPHd7UzilM_)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/layer-item.directive.js#L10)):</sup>
Does it miss a word between is a represents?


---

<sup>**[src/app/ui/toc/layer-item.html, line 1 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19f5nigYcPkOr6Tsva)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/layer-item.html#L1)):</sup>
Question: I know we use a space after opening curly bracket in js file. Are we suppose to do it in html file?


---

<sup>**[src/app/ui/toc/toc.controller.js, line 22 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19fWox8xhUbRFqiHQv)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/toc.controller.js#L22)):</sup>
Should we change var for const?


---

<sup>**[src/app/ui/toc/toc.controller.js, line 33 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19ffOEu4MI-LUfv2aL)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/toc.controller.js#L33)):</sup>
In last PR if I remember, we didn't put the param between paranthesis (group) when you have only one param for the arrow function. We can do both (airbnb 8.1) just make sure to be consistent.


---

<sup>**[src/app/ui/toc/toc.html, line 16 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19gTjp4j9JKQlkt_bA)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/toc.html#L16)):</sup>
Same as my other comment, do we have spaces after and before curly brackets in HTML? I think not but just want to make sure.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/ui/toc/layer-item.html, line 1 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19f5nigYcPkOr6Tsva)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/layer-item.html#L1)):</sup>
I didn't see anything about templates in a fairly quick look at the style guide.  I'm okay with either but I think consistency between code and templates makes sense and I don't see any obvious downsides.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43)

**Comment by AleksueiR** [comment]
Review status: 5 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

<sup>**[src/app/ui/sidenav/menulink.directive.js, line 37 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19eIBVryhcX_lSMcUD)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/sidenav/menulink.directive.js#L37)):</sup>
Done.


---

<sup>**[src/app/ui/toc/layer-item.directive.js, line 10 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19eiyAASPHd7UzilM_)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/layer-item.directive.js#L10)):</sup>
Done.


---

<sup>**[src/app/ui/toc/layer-item.html, line 1 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19f5nigYcPkOr6Tsva)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/layer-item.html#L1)):</sup>
:+1: to consistency. Done.


---

<sup>**[src/app/ui/toc/toc.controller.js, line 22 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19fWox8xhUbRFqiHQv)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/toc.controller.js#L22)):</sup>
Done.


---

<sup>**[src/app/ui/toc/toc.controller.js, line 33 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19ffOEu4MI-LUfv2aL)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/toc.controller.js#L33)):</sup>
Done.


---

<sup>**[src/app/ui/toc/toc.html, line 16 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43#-K19gTjp4j9JKQlkt_bA)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72edf15b59daf90cad9f8d7a31f4764c6970601b/src/app/ui/toc/toc.html#L16)):</sup>
Will leave like that for now. Will be fixed in my next PR.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43)

**Comment by alyec** [comment]
Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/43)

**Pull request merged**
