### PR TITLE
Transpiler

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/18)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[gulp.config.js, line 37 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18#-K-Zid3kikwOLByfG27B)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/940cfa1f40b42f9c7508ad4dece8fdfb12c751b9/gulp.config.js#L37)):</sup>
We decided that ordering `.js` files is not important except for having `app-seed.js` added to the concatenated file last. 


---

<sup>**[src/app/ui/sidenav/menulink.directive.js, line 17 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18#-K-ZjW3JPt2JwPWqyulU)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/940cfa1f40b42f9c7508ad4dece8fdfb12c751b9/src/app/ui/sidenav/menulink.directive.js#L17)):</sup>
Use `const` and wait until it breaks? :)
Does anyone know of a good ES6 primer?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18)

**Comment by alyec** [comment]
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[gulp.config.js, line 37 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18#-K-Zid3kikwOLByfG27B)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/940cfa1f40b42f9c7508ad4dece8fdfb12c751b9/gulp.config.js#L37)):</sup>
fixed


---

<sup>**[src/app/ui/sidenav/menulink.directive.js, line 17 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18#-K-ZjW3JPt2JwPWqyulU)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/940cfa1f40b42f9c7508ad4dece8fdfb12c751b9/src/app/ui/sidenav/menulink.directive.js#L17)):</sup>
I won't patch in this PR since this is really just for making sure it works.  I think we'll have to do a much bigger refactor to apply ES6 delcarations.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r7, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[bower.json, line 23 \[r9\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18#-K-cG_YGywODlJYvLVBL)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13331ff883ce3cadeb9d3b071a5dc56419f264eb/bower.json#L23)):</sup>
Could you please remove `html5-boilerplate` from the list? It's a leftover from angular-seed and we aren't using it anyway.


---

<sup>**[package.json, line 22 \[r9\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18#-K-cFmOrcttsKCuKN8H6)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13331ff883ce3cadeb9d3b071a5dc56419f264eb/package.json#L22)):</sup>
:+1: 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18)

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r4, 2 of 2 files at r6, 3 of 4 files at r9, 1 of 1 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/18)

**Pull request merged**
