### PR TITLE
Support for esriFieldTypeDate

### LINKED ISSUE #455: Support for esriFieldTypeDate
Current version of RAMP is not interpreting numeric value defined as 'esriFieldTypeDate' and displays them as plain numeric value.

Here is an example of ESRI service using this datatype: 
http://services.aadnc-aandc.gc.ca/geomatics/rest/services/Donnees_Ouvertes-Open_Data/Bail_minier_NU_Mining_Lease/MapServer/0/query?where=OBJECTID%3E-1&outFields=*&returnGeometry=false&f=json&callback=dojo_request_script_callbacks.dojo_request_script10

Here is also a screenshot of how those fields are currently displayed in RAMP:
image

As well as a screenshoot of the expected date format (as it is displayed in ArcGIS desktop)
image

### PR DESCRIPTION
**Pull request by cynngah**
Now converts date attribute to ISO format

closes #455

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/571)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFDOGi87zbKdFNZoK:-KGxFDOHDG1PdnUYg7RQ:-1211266133) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ec07e0664bebd68fb5a0aedecab423080f51be6/src/app/geo/identify.service.js#L106)):*
can use `val` instead of `attribs[key]`  (pedantic :trophy: )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFE2T2lAwIU8xsb2D:-KGxFE2T2lAwIU8xsb2E:-1325149357) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ec07e0664bebd68fb5a0aedecab423080f51be6/src/app/geo/identify.service.js#L106)):*
const and `Date(val)`

---

*[src/app/geo/layer-registry.service.js, line 384 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFk2GsHpkEGf2bzXV:-KGxFk2GsHpkEGf2bzXW:-1130959951) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ec07e0664bebd68fb5a0aedecab423080f51be6/src/app/geo/layer-registry.service.js#L384)):*
type should be {Array}
missing `@returns` and should probably avoid returning undefined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFDOGi87zbKdFNZoK:-KGxGEc8nw5IAZuxRHVi:-272588313) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ec07e0664bebd68fb5a0aedecab423080f51be6/src/app/geo/identify.service.js#L106)):*
James wins, I was too slow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxR1lSIhDdpXkxnDJA:-KGxR1lSIhDdpXkxnDJB:1168685503) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ec07e0664bebd68fb5a0aedecab423080f51be6/src/app/geo/identify.service.js#L107)):*
Use Angular date filter instead: [$filter('date')(date, format, timezone)](https://docs.angularjs.org/api/ng/filter/date)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxR1lSIhDdpXkxnDJA:-KGyHujp1L0Sv6WHDm_f:-1847811099) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ec07e0664bebd68fb5a0aedecab423080f51be6/src/app/geo/identify.service.js#L107)):*
I can see `$filter('date')` being pretty useful in the general case.  In this particular case where we want the ISO representation what is the benefit (`toISOString()` doesn't even need an IE polyfill)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxR1lSIhDdpXkxnDJA:-KH-f6f35exhrt2wu3_Z:-1585517835) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ec07e0664bebd68fb5a0aedecab423080f51be6/src/app/geo/identify.service.js#L107)):*
Might not be a big benefit, but I think `$filter('date')(1153785600000, 'yyyy-MM-dd')` is more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFDOGi87zbKdFNZoK:-KH0DdnorX5edBvUci8B:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/265ee4d1369d40da7793d4b0fde8e8b89c50f7f1/src/app/geo/identify.service.js#L106)):*
Done.

---

*[src/app/geo/identify.service.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFE2T2lAwIU8xsb2D:-KH0De8ocQgO8Lseu-uO:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/265ee4d1369d40da7793d4b0fde8e8b89c50f7f1/src/app/geo/identify.service.js#L106)):*
Done.

---

*[src/app/geo/identify.service.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxR1lSIhDdpXkxnDJA:-KH0DetBBsZ41Jggg338:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/265ee4d1369d40da7793d4b0fde8e8b89c50f7f1/src/app/geo/identify.service.js#L107)):*
Done.

---

*[src/app/geo/layer-registry.service.js, line 384 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFk2GsHpkEGf2bzXV:-KH0MDdi_ldrFNjLAzR_:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/265ee4d1369d40da7793d4b0fde8e8b89c50f7f1/src/app/geo/layer-registry.service.js#L384)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 384 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFk2GsHpkEGf2bzXV:-KH0Q4TwPhhNC2KLyqay:1702231117) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/265ee4d1369d40da7793d4b0fde8e8b89c50f7f1/src/app/geo/layer-registry.service.js#L384)):*
If fields is empty this will return undefined.  You may want to add a `return false` at the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by cynngah** [comment]
Moving logic into geoApi so we don't have to format date everywhere else and just do it once.

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 344 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KH1JpCtxDaKZ1e3k_1_:-KH1JpCtxDaKZ1e3k_1a:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/87fadeb2c132157a852c2c285df2b0b70b8ae326/src/app/geo/layer-registry.service.js#L344)):*
const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 384 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KGxFk2GsHpkEGf2bzXV:-KH1M_YiH9HFm-c6B23H:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/265ee4d1369d40da7793d4b0fde8e8b89c50f7f1/src/app/geo/layer-registry.service.js#L384)):*
Done.

---

*[src/app/geo/layer-registry.service.js, line 344 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571#-KH1JpCtxDaKZ1e3k_1_:-KH1M_xXMSx3e8MSAbl2:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/87fadeb2c132157a852c2c285df2b0b70b8ae326/src/app/geo/layer-registry.service.js#L344)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/571)*

**Pull request merged**
