### PR TITLE
fix(ui): Sample pages updated to new GcGEO layout

### LINKED ISSUE #861: Update index-fgp-en/fr.html sample pages to reflect new look and feel of GcGEO
Update sample pages to reflect the new look and feel:
http://redmine.gcgeo.gc.ca/redmine/issues/4478

### PR DESCRIPTION
**Pull request by milesap**
Closes #861

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/914)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 23 of 30 files at r1, 1 of 3 files at r2.
Review status: 12 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[gulp.config.js, line 17 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/914#-KMzQM2mBYiVx9qJyJvt:-KMzQM2mBYiVx9qJyJvu:1672132352) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b5c568d69542a508b96a95c564f641ab65f55c40/gulp.config.js#L17)):*
> ```JavaScript
>     var root = path.resolve('./');
>     var src = './src/'; // source files
>     var build = './build/samples/'; // build target, suitable for usage as a dev server
> ```

This will affect libBuild as well as sampleBuild which is probably not intended.

`build` is no longer an exposed property so it shouldn't need to be edited anymore.

---

*[gulp.config.js, line 32 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/914#-KMzQZLfSktXLyv9PfV8:-KMzQZLfSktXLyv9PfV9:894962079) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b5c568d69542a508b96a95c564f641ab65f55c40/gulp.config.js#L32)):*
> ```JavaScript
> 
>         index: [
>             src + 'samples/index-many.html',
> ```

Creating a var for `src + 'samples/'` would clean this up a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/914)*

**Comment by spencerwahl** [comment]
Review status: 12 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/samples/index-fgp-en.html, line 154 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/914#-KMzQg9ODXrGrokdOSma:-KMzQg9PGPWKVrSmb_uq:678695376) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b5c568d69542a508b96a95c564f641ab65f55c40/src/samples/index-fgp-en.html#L154)):*
> ```HTML
>     
>     
> ```

We need the bookmark/keys scripts moved into these new samples

---

*[src/samples/index-fgp-fr.html, line 153 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/914#-KMzQu9fH0McH0NGh961:-KMzQu9fH0McH0NGh962:1310558240) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b5c568d69542a508b96a95c564f641ab65f55c40/src/samples/index-fgp-fr.html#L153)):*
> ```HTML
>     
>     
> ```

same as fgp-en

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/914)*

**Comment by mweech** [comment]
This: http://fgpv.cloudapp.net/demo/users/milesap/861-update-demo-pages/samples/index-fgp-en.html

Does not look like this: 

signin

**Comment by AleksueiR** [comment]
Let's keep `lib` folder outside of `samples` as it was before. Should be less troubles getting this to work.

---

Review status: 9 of 18 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/914#-:-KN7tGwhfFTzYvYNlgsq:-1272497125)*

**Pull request closed without merging**
