### PR TITLE
fix(ui): svg elements inside buttons no longer focusable in IE 11

### LINKED ISSUE #1031: Tab issue in IE11
In chrome and firefox a tab press will send you from button to button.

In IE11 a tab press will send you from a button to the icon within the button. This means that double the key-presses are needed to navigate the controls and half the time the focus isn't on a usable element.

Notice that SVGs are targets in focus/blur events:
ie_focus_svg

### PR DESCRIPTION
**Pull request by milesap**
Closes #1031

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1034)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ5lVRbDeuo8waUo2k:-KOQ5lVRbDeuo8waUo2l:br6n50s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
> ```JavaScript
>                     // $timeout needed since there is a delay md-icon has when adding svg elements
>                     // see https://github.com/angular/material/blob/master/src/components/icon/js/iconDirective.js#L236
>                     $timeout(() => {
> ```

nitpick: you don't need braces for a single line arrow function `$timeout(() => el[0].childNodes[0].setAttribute('focusable', false));` should work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Comment by AleksueiR** [comment]
Lots of 
 
in the console.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ6qGk54CgvPoQXv1r:-KOQ6qGk54CgvPoQXv1s:b3znuf7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
> ```JavaScript
>                     // $timeout needed since there is a delay md-icon has when adding svg elements
>                     // see https://github.com/angular/material/blob/master/src/components/icon/js/iconDirective.js#L236
>                     $timeout(() => {
> ```

This will not pick up icon changes done through the binding since the decorated link function is executed only once. You need to do something similar to what the `md-icon` itself does: set observer on the svg source attribute and when it rendered, add the `focusable=false` attribute. See if you can use `$apply` or `$asyncApply` instead of `$timeout`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-:-KOQ6jI8vdzrhIhwBGf7:bb2e7wf)*

**Comment by milesap** [comment]
Errors corrected

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ5lVRbDeuo8waUo2k:-KOQdtgMSY_nLVQ4XWtj:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> nitpick: you don't need braces for a single line arrow function `$timeout(() => el[0].childNodes[0].setAttribute('focusable', false));` should work
</details>
:+1: 

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ6qGk54CgvPoQXv1r:-KOQduvA6vIZTBEoQZol:bs4xojp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This will not pick up icon changes done through the binding since the decorated link function is executed only once. You need to do something similar to what the `md-icon` itself does: set observer on the svg source attribute and when it rendered, add the `focusable=false` attribute. See if you can use `$apply` or `$asyncApply` instead of `$timeout`.
</details>
The `DOMSubtreeModified` listener will now trigger whenever an SVG (or some other child element) is changed inside `md-icon` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-:-KOQeJlLnVVrQ0EOUrBX:b-815adj)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ6qGk54CgvPoQXv1r:-KOQg_41WlB14WnwITd5:badsb89) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> The `DOMSubtreeModified` listener will now trigger whenever an SVG (or some other child element) is changed inside `md-icon` 
</details>
If an `svg` element is not found and the DOM is not changed is it possible for this to miss an event because `allowDOMSubtreeModified` is left at true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ6qGk54CgvPoQXv1r:-KOQjrCzppYFfC_jFj7q:b1j8u38) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> If an `svg` element is not found and the DOM is not changed is it possible for this to miss an event because `allowDOMSubtreeModified` is left at true?
</details>
Unlikely, but certainly possible - made this more explicit 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ6qGk54CgvPoQXv1r:-KOQkTFU0pbTwCTd_3nz:b-n87j8e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Unlikely, but certainly possible - made this more explicit 
</details>
Can you also add a comment on `allowDOMSubtreeModified` to indicate that its purpose is to prevent multiple triggers of the `DOMSubtreeModified` event?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/icon.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034#-KOQ6qGk54CgvPoQXv1r:-KOQnU9jJShAhWkqqyfI:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68f47d6b11559fde335f26418f1a1d1742d0d030/src/app/ui/common/icon.decorator.js#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you also add a comment on `allowDOMSubtreeModified` to indicate that its purpose is to prevent multiple triggers of the `DOMSubtreeModified` event?
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1034)*

**Pull request merged**
