### PR TITLE
feat(ui): Add filter icon and right align datatable options

### LINKED ISSUE #1195: Add filter icon to the "Filter by Extent" datatable option
Place the filter icon on the data grid top menu same way you have for Print and Export.

Thank you @bkutty for the suggestion!

### PR DESCRIPTION
**Pull request by milesap**
Closes #1195

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1246)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/ui/common/menuItem.decorator.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246#-KSqwPX6GhPHKy6wb6om:-KSqwPX7DwKgxX-qtd17:b7ksge2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8f033a8d2c4b039e3069f2ca3affb252bda81438/src/app/ui/common/menuItem.decorator.js#L53)):*
> ```JavaScript
>                     if ((attrs.type === 'checkbox' || attrs.type === 'radio') && attrs.rvRightIcon) {
>                         button.append($compile(
>                             `<md-icon md-svg-icon="${attrs.rvRightIcon}" style="margin-right: 0px;"></md-icon>`
> ```

No inline CSS please.

---

*[src/app/ui/common/menuItem.decorator.js, line 59 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246#-KSqwTVthvD4TvF58I3M:-KSqwTVthvD4TvF58I3N:bgqno2q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8f033a8d2c4b039e3069f2ca3affb252bda81438/src/app/ui/common/menuItem.decorator.js#L59)):*
> ```JavaScript
>                     if (icon.length > 0 && button.length > 0) {
>                         // append empty icon to non checkbox/radio items so that they have a common alignment
>                         if (attrs.rvRightIcon && attrs.type !== 'checkbox' && attrs.type !== 'radio') {
> ```

Instead of appending an empty icon as a spacer, it's better to align icons with css:

This should go into the `md-menu-content md-menu-item`  selector in `_special.scss`, line 46~.
```css
      &[rv-right-icon] .md-button {
            padding-right: rem(1.6) !important;

            md-icon:last-of-type {
                margin-right: 0;
            }
        }

        &[rv-right-icon="true"] .md-button {
            padding-left: rem(1.6) + rem(4);
        }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246)*

**Comment by milesap** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/menuItem.decorator.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246#-KSqwPX6GhPHKy6wb6om:-KSuvQBcqHHiqYOaqgwg:b25aa3f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8f033a8d2c4b039e3069f2ca3affb252bda81438/src/app/ui/common/menuItem.decorator.js#L53)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> No inline CSS please.
</details>
Old habits die hard - removed

---

*[src/app/ui/common/menuItem.decorator.js, line 59 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246#-KSqwTVthvD4TvF58I3M:-KSuvgsL8umx9lHplRJ8:bg8ptrt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8f033a8d2c4b039e3069f2ca3affb252bda81438/src/app/ui/common/menuItem.decorator.js#L59)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of appending an empty icon as a spacer, it's better to align icons with css:
> 
> This should go into the `md-menu-content md-menu-item`  selector in `_special.scss`, line 46~.
> ```css
>       &[rv-right-icon] .md-button {
>             padding-right: rem(1.6) !important;
> 
>             md-icon:last-of-type {
>                 margin-right: 0;
>             }
>         }
> 
>         &[rv-right-icon="true"] .md-button {
>             padding-left: rem(1.6) + rem(4);
>         }
> ```
</details>
Added css to `_special.scss`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246)*

**Comment by AleksueiR** [comment]
Nice! :lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246#-:-KSvAaLKFRIEPlguwy84:bfd61qr)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1246)*

**Pull request merged**
