### PR TITLE
feat(ui): implement symbology stack cover icon

### LINKED ISSUE #2650: Add cover icon functionality to the symbology stack
The cover icon concept was included into the config schema but never implemented properly. 
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/schema.json#L352

- the cover icon is placed on top of the symbology stack, but it doesn't move when the rest of the stack is expanded. 
- the cover icon has a different wiggle animation - it scales up a bit on hover

The stack behaviour without a cover image should remain the same.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Implements the cover image for symbology stacks.

Closes #2650

## Testing
:eyes: 

## Documentation
Inline comments.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651)*

**Comment by JahidAhmed** [comment]
While testing `index-samples`, there was an error being thrown for the first sample when I try to expand the symbology for any layer:



---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651#-:-LAIV4KwAqqqcpUQYpEr:bbywf47)*

**Comment by AleksueiR** [comment]
So strange - it works fine on my local build. Digging deeper.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651#-:-LAIg9xW3N-L7ILsI9as:b-w1vvwd)*

**Comment by AleksueiR** [comment]
@jahidahmed errors should be fixed now. Thanks for spotting that :+1: 

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651#-:-LAJ4RkFEa4ZSpgmcOgE:b-lbuua6)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651)*

**Pull request merged**
