### PR TITLE
feat(map): show lat/long coordinates in degree decimal and degree, mi…

### LINKED ISSUE #1795: Add mouse coordinates on map
When mouse move, show mouse coordinates lat/long in decimal degree and degree, minute second on map.

### PR DESCRIPTION
**Pull request by jolevesq**
…nute, second

Closes #1795

## Description

Add coordinates for mouse position on map #1795 

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1799)

### CODE REVIEW

**Comment by milesap** [comment]
fyi base changed to v1.7 from develop

**Comment by AleksueiR** [comment]
Strange, no demo. Can you restart the travis build please?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KfusWfEkSUAMMy62Kxx:b-4bupc6)*

**Comment by milesap** [comment]
I'm thinking this should be a plugin like scale bar and north arrow. Just a thought, but we could have a section of the map which allows these plugin types to be displayed, but would also allow these coordinates to be displayed outside the viewer. What do you think? 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-Kfv5kbtGbQduAmKIIkD:b-l42tj0)*

**Comment by jolevesq** [comment]
It can be a good idea. If we need to convert this to a plugin I will need a little course on how to do that.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-Kfv82OpEdBl4Sj_5CM5:b-zg8z9l)*

**Comment by milesap** [comment]
If you'd like I can create a north arrow or scalebar plugin in the next day or two which you can use as a reference for converting this one.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KfvAj0igiRat9nNgUh0:b-fh8fll)*

**Comment by jolevesq** [comment]
Good idea! Thanks

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KfvBc19YUDjfTHPu477:bvxashp)*

**Comment by milesap** [comment]
Change of plans; discussed with @aleksueir and @alyec and we agreed that north arrow, scalebar, and this PR should not be a plugin. However, internally we should be calling our external API functions exclusively (and adding them if they don't yet exist) so that it is possible for users to create a plugin if they need to. You can add external API functions in `bootstrap.js` via proxy, which are referenced in `core.run.js`. If you have any questions let me know

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KfvFrH9OvqZAsd9VL_I:bizp3uj)*

**Comment by milesap** [comment]
I'll do this for the north arrow today if you'd like to see an example

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KfvHk-IoaZC6CPYLq7m:b1j56w6)*

**Comment by jolevesq** [comment]
I will follow your lead :smile:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KfvI1O-XExKYdnP1zM1:bi6xk)*

**Comment by AleksueiR** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/layout/_main.scss, line 128 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KfvRxQv6-k_ln6uULQY:-KfvRxQv6-k_ln6uULQZ:b-qlilr7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19735b45e236d1c818ee9c761992878e16c7a515/src/content/styles/layout/_main.scss#L128)):*
> ```SCSS
> 
>     @include include-size(rv-gt-sm) {
>         @include active-panel-plug($left: $viewport-gutter, $top: $viewport-gutter + $toolbar-height + 1, $bottom: $viewport-gutter + 40, $width: $toolbar-width, $from: top);
> ```

Can we keep the coordinate info to the right of the panel:


and move it under the main panel when it's collapsed:


?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by jolevesq** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/layout/_main.scss, line 128 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KfvRxQv6-k_ln6uULQY:-KfwOt6rO5ZErXdbjdKd:b244nlp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19735b45e236d1c818ee9c761992878e16c7a515/src/content/styles/layout/_main.scss#L128)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can we keep the coordinate info to the right of the panel:


and move it under the main panel when it's collapsed:


?
</blockquote></details>

We can but we should do it for the scale bar as well. Do you want me to do it for both of them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by jolevesq** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/layout/_main.scss, line 128 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KfvRxQv6-k_ln6uULQY:-KgK2TT9yi7pZIqqyhR4:bm8jdzr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19735b45e236d1c818ee9c761992878e16c7a515/src/content/styles/layout/_main.scss#L128)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We can but we should do it for the scale bar as well. Do you want me to do it for both of them?
</blockquote></details>

For users, you don't think moving stuff will confuse them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by AleksueiR** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/layout/_main.scss, line 128 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KfvRxQv6-k_ln6uULQY:-KgK37hC0f1cy0izeRIk:b-4i1s83) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19735b45e236d1c818ee9c761992878e16c7a515/src/content/styles/layout/_main.scss#L128)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For users, you don't think moving stuff will confuse them?
</blockquote></details>

Oh, the scalebar doesn't move? Never noticed :) I think it should, otherwise it's hidden most of the time anyway.
I don't think it will confuse users as this movement is self explanatory - scalebar and coordinate info move to stay visible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by jolevesq** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/layout/_main.scss, line 128 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KfvRxQv6-k_ln6uULQY:-KgP05DFg0LdN5KCoiM3:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19735b45e236d1c818ee9c761992878e16c7a515/src/content/styles/layout/_main.scss#L128)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Oh, the scalebar doesn't move? Never noticed :) I think it should, otherwise it's hidden most of the time anyway.
I don't think it will confuse users as this movement is self explanatory - scalebar and coordinate info move to stay visible.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by AleksueiR** [comment]
Looks nice. 

Can you add the semi-transparent white background under the scalebar as well? Something like this:


---

Reviewed 11 of 17 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_shell.scss, line 37 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KgPN2rIihClBGcBuLiw:-KgPN2rIihClBGcBuLix:btey99e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/317a8af1bf4016c23253e36057e529fd0717b7c3/src/content/styles/modules/_shell.scss#L37)):*
> ```SCSS
>         .rv-map-coordinates {
>             position: absolute;
>             left: 175px;
> ```

Can you change this to `rem(1.75)`, etc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KgPPLV2FuCAInQyP5YO:brjfj3b)*

**Comment by jolevesq** [comment]
No problem!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KgU11EzihKDQ8f3_KQ0:blyphgc)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_shell.scss, line 37 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KgPN2rIihClBGcBuLiw:-KgUqCuVXcTcoXEDC22p:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/317a8af1bf4016c23253e36057e529fd0717b7c3/src/content/styles/modules/_shell.scss#L37)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you change this to `rem(1.75)`, etc?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by milesap** [comment]
:+1: looks good!

---

Reviewed 9 of 17 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KgZmz4hCk4Vy7r76T5X:br4tmdz)*

**Comment by AleksueiR** [comment]
:lgtm: Looks good!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-Kg__WE4spfgmrgW3mD-:b276ill)*

**Comment by james-rae** [comment]
looks good.  some of the stateless functions in `map-tools.service` could eventually migrate to geoApi, but for now they are happy where they are.

---

Reviewed 9 of 17 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-Kg_fiwoUWeaSkQfc340:bkaysft)*

**Comment by jolevesq** [comment]
I added wkid for output. in index-fgp it is in lambert and in index-one it is in lat/long. I enable coords or north arrow with value from config like like mentioned at the meeting this afternoon

---

Review status: 8 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-Kga3E86h-fXL6YHvuO1:b2pqzq8)*

**Comment by AleksueiR** [comment]
Review status: 8 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/config.en-CA.json, line 39 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KgnXnHwuU54W98cqQpy:-KgnXnHwuU54W98cqQpz:b8dlvae) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d63a25b5b57dab9af20e7e2c069276723b30aa5/src/config.en-CA.json#L39)):*
> ```JSON
>         "enabled": true,
>         "spatialReference": {
>           "wkid": 4326
> ```

I'm not completely sure how this works, but shouldn't this match the spatial references of the currently selected basemap?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by milesap** [comment]
Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/config.en-CA.json, line 39 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KgnXnHwuU54W98cqQpy:-KgnsRAWWvV2I5MdnFJm:b-3g5iu5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d63a25b5b57dab9af20e7e2c069276723b30aa5/src/config.en-CA.json#L39)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I'm not completely sure how this works, but shouldn't this match the spatial references of the currently selected basemap?
</blockquote></details>

Usually users use lat/long coordinates even with a projected map. If you do not use lat/long, it can make sense to have coord in same sr as basemap. I can use lat/long if sr is specified in config file. If value is not there, use basemap projection

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/config.en-CA.json, line 39 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-KgnXnHwuU54W98cqQpy:-KgnuGhXOPo2TYjYwPcZ:bb4wwin) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d63a25b5b57dab9af20e7e2c069276723b30aa5/src/config.en-CA.json#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Usually users use lat/long coordinates even with a projected map. If you do not use lat/long, it can make sense to have coord in same sr as basemap. I can use lat/long if sr is specified in config file. If value is not there, use basemap projection
</blockquote></details>

Ok, this sounds reasonable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by jolevesq** [comment]
Made a modification to the animation. Scalebar animation stop working on projection change. Also, if no spatial reference is set in the configuration file it took basemap spatial reference

---

Review status: 10 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799#-:-KgoSJUBrXUnwsgXpiay:bsrco47)*

**Comment by james-rae** [comment]
Reviewed 5 of 8 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 8 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1799)*

**Pull request merged**
