### PR TITLE
Remove options in export settings with no value

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Remove options with no value in the export settings
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2501
## Testing

Manually
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2506)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2506)*

**Comment by AleksueiR** [comment]
Demo works :+1: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/export/export-component.class.js, line 34 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2506#-L-fois2nVxOUd8zdBJg:-L-fois2nVxOUd8zdBJh:b-dwr0w) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/86595c46d431c177fce0ef40cf059639e7c9242a/src/app/ui/export/export-component.class.js#L34)):*
> ```JavaScript
>         constructor(id, { value = {}, generators = [], graphicOrder = null, isVisible = true,
>             isSelectable = true, isSelected = true }) {
>             const validToSelect = typeof value !== 'string' || value.length !== 0;
> ```

Please, add some comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2506#-:-L-folmTtANeACyyYWEA:b-gm168)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2506)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2506)*

**Pull request merged**
