### PR TITLE
fix(ui): remove scrollbar on collapsed group layer

### LINKED ISSUE #482: Style Collisions Occuring in WET Pages
Scrollbar appears when mousing over the edge of a layer entry for a group layer that has been collapsed.

image

### PR DESCRIPTION
**Pull request by milesap**
Closes #482

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/609)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/609)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/content/styles/modules/_toc.scss, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/609#-KHtrTIgg5oaIOHgMafu:-KHtrTIgg5oaIOHgMafv:-229700258) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/932816a7071cc387e5dd17f2ae91e1885c36267e/src/content/styles/modules/_toc.scss#L47)):*
> ```SCSS
>         > li {
>             position: relative;
>             overflow: hidden;
> ```

Great solution!
If anyone is curious why this is happening, check out [MDN overflow](https://developer.mozilla.org/en/docs/Web/CSS/overflow) and [MDN block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context) and maybe [MDN margin collapse](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing).

Instead of `overflow: hidden` this can also be fixed by `display: inline-block` for example.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/609)*

**Comment by AleksueiR** [comment]
:lgtm: 

<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### fix\(ui\): remove scrollbar on collapsed group layer
> 
> Closes #482
> 
> 
> </details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/609#-:-KHy_jv1esCqwdhttyCl:980077423)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/609)*

**Pull request merged**
