### PR TITLE
Add quotes to translate

### PR DESCRIPTION
**Pull request by barryytm**
## Description

#1918 
Add missing queotes to translate for it to render properly.

## Testing

No, because it is an UI/UX and accessibility issue.

## Documentation

NA

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1919)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/templates/visibility-menu.html, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlV5EFXygJRMcQEluy6:-KlV5EFYN2ofTI3Lx6j4:byw2cnu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/58e958e8e0120c72e67b68f22ad7a2ba4fcee946/src/app/ui/toc/templates/visibility-menu.html#L19)):*
> ```HTML
>                 ng-click="self.showAllLegendEntries()"
>                 ng-disabled="self.isAllLegendEntriesVisible()"
>                 aria-label="{{ 'toc.menu.visibility.allon'| translate }}">
> ```

do you need a space here? (before the | )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Comment by barryytm** [comment]
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/templates/visibility-menu.html, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlV5EFXygJRMcQEluy6:-KlV6ZEMRi1GzgJtPTqP:b-zgaq31) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/58e958e8e0120c72e67b68f22ad7a2ba4fcee946/src/app/ui/toc/templates/visibility-menu.html#L19)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

do you need a space here? (before the | )
</blockquote></details>

yes and done.  Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Comment by AleksueiR** [comment]
Not directly related to this, but I see some translation strings missing from the translation file, like `toc.entry.aria.openData` and `export.size.selector` for example.

---

Reviewed 21 of 22 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/layout/shell.html, line 21 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYKCSW1Vz8UJlqvziO:-KlYKCSW1Vz8UJlqvziP:bc083ew) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9413a87b96507f7e4791926c60c6c50605dd59ee/src/app/layout/shell.html#L21)):*
> ```HTML
> </div>
> 
> <div class="rv-esri-map" rv-init-map rv-overview-toggle tabindex="0" aria-label="{{ 'geo.aria.mapdescription' | translate }}"></div>
> ```

One more overview toggle label here: https://github.com/AleksueiR/fgpv-vpgf/blob/bookmark/src/app/geo/overview-toggle.directive.js#L8

---

*[src/app/ui/export/export.html, line 108 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYJRAqSd_BIU2ARR6k:-KlYJRAqSd_BIU2ARR6l:b-npnvvl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9413a87b96507f7e4791926c60c6c50605dd59ee/src/app/ui/export/export.html#L108)):*
> ```HTML
>                     md-mode="indeterminate"></md-progress-linear>
> 
>             <md-select aria-label="{{ 'export.size.selector' | translate }}" translate
> ```

Something is broken here - aria-lable just repeats 'export.size.selector'.

---

*[src/app/ui/toc/templates/legend-control-body.html, line 2 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYLzwprTKHs0XjBrMq:-KlYLzwprTKHs0XjBrMr:boj8xac) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9413a87b96507f7e4791926c60c6c50605dd59ee/src/app/ui/toc/templates/legend-control-body.html#L2)):*
> ```HTML
> <md-button
>     aria-label="{{ 'self.uiControl.label' | translate }}"
> ```

This one (and a couple in the files below) doesn't need quotes as this is a true variable, not just a string pointing to the translation file. As a rule, anything starting with `self.` is a variable attached to the scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-:-KlYLi2oDvLxTWh9wqNv:b58rldu)*

**Comment by AleksueiR** [comment]
Can you also fix a typo here: https://github.com/AleksueiR/fgpv-vpgf/blob/bookmark/src/app/ui/toc/legend-element-factory.class.js#L208
It should be "boundaryZoom".

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-:-KlYXSMJpNQYfbEgoPFT:b-z3zz3a)*

**Comment by barryytm** [comment]
Review status: 21 of 24 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/layout/shell.html, line 21 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYKCSW1Vz8UJlqvziO:-KlYeix0uwUPtAfK8os-:beaonvk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4cf8500c48c2bbf3ad4939f862c5b71cdb2844aa/src/app/layout/shell.html#L21)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

One more overview toggle label here: https://github.com/AleksueiR/fgpv-vpgf/blob/bookmark/src/app/geo/overview-toggle.directive.js#L8
</blockquote></details>

done, thanks.

---

*[src/app/ui/export/export.html, line 108 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYJRAqSd_BIU2ARR6k:-KlYtFx5MsDQbe8rDZvf:b1mz4sq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4cf8500c48c2bbf3ad4939f862c5b71cdb2844aa/src/app/ui/export/export.html#L108)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Something is broken here - aria-lable just repeats 'export.size.selector'.
</blockquote></details>

Just added it in the translation file. it should work now.  Thanks!

---

*[src/app/ui/toc/templates/legend-control-body.html, line 2 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYLzwprTKHs0XjBrMq:-KlYtOxcy3HyWrSgiaP3:b-r18wie) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4cf8500c48c2bbf3ad4939f862c5b71cdb2844aa/src/app/ui/toc/templates/legend-control-body.html#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This one (and a couple in the files below) doesn't need quotes as this is a true variable, not just a string pointing to the translation file. As a rule, anything starting with `self.` is a variable attached to the scope.
</blockquote></details>

done, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/mapnav/mapnav-button.html, line 2 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYwZ9nWgXOSR6Mt1Je:-KlYwZ9oeP_lK_VDDjeq:bx0e2ai) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7a349dbd10d4c75b4a349ea7ea2415bc3c44abef/src/app/ui/mapnav/mapnav-button.html#L2)):*
> ```HTML
> <md-button
>     aria-label="{{ 'self.control.label' | translate }}"
> ```

Missing this one, and there are four more below in other files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/mapnav/mapnav-button.html, line 2 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-KlYwZ9nWgXOSR6Mt1Je:-KlYzp4S-OjTghXFZhzg:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7a349dbd10d4c75b4a349ea7ea2415bc3c44abef/src/app/ui/mapnav/mapnav-button.html#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Missing this one, and there are four more below in other files.
</blockquote></details>

Done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 5 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919#-:-KlZ-Kcm3RQ35PGlLEEy:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r3, 1 of 5 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1919)*

**Pull request merged**
