### PR TITLE
fix(ui): add support for autoscrolling during layer drag-n-drop

### LINKED ISSUE #750: Add autoscroll to drag-n-drop legend reordering
If the legend section is scrollable because of too many entries, drag-n-drop reorder will not scroll to the hidden parts of the selector. Need to implement something like https://github.com/hollowdoor/dom_autoscroller to get that working.

reorder_scroll

Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/272.

### PR DESCRIPTION
**Pull request by milesap**
Closes #750

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/903)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/toc/toc.directive.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiSJWZv6dafI4Gst_x:-KMiSJW_5anUMSICY1eu:335930958) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L76)):*
> ```JavaScript
>             // on drag start, add data attribute to the list indicating which sort group the dragged layer can be accepted into
>             // this will highlight invalid drop target
>             scope.$on('toc-bag.drag', (evt, elem, source) => {
> ```

el / elem naming: can we do one of the following
- document the difference between the variables
- name them such that the difference is clear
- if they are the same can we drop `elem` altogether and only use `el` (pretty sure this is not the case)

---

*[src/app/ui/toc/toc.directive.js, line 81 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiSoMGEa4GyZcnaeDz:-KMiSoMGEa4GyZcnaeE-:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L81)):*
> ```JavaScript
> 
>                 // handle autoscroll when dragging layers
>                 let scrollElem = source.closest('md-content');
> ```

const

---

*[src/app/ui/toc/toc.directive.js, line 90 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiTsBOQrbHb8A_L4tp:-KMiTsBOQrbHb8A_L4tq:-2109054666) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L90)):*
> ```JavaScript
>                     // scrolling upwards
>                     if (scrollElem.offset().top > event.pageY) {
>                         scrollAnimation = !scrollAnimation.isActive() ?
> ```

How about:
```js
if (!scrollAnimation.isActive()) {
  scrollAnimation = TweenLite.to(scrollElem, scrollSpeed, { scrollTo: { y: 0 } });
}
```
To me this reads better than the ternary statement split over multiple lines.

---

*[src/app/ui/toc/toc.directive.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiUKN5J0bVA5Wfl8dC:-KMiUKN5J0bVA5Wfl8dD:-1006207160) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L96)):*
> ```JavaScript
>                     // scrolling downwards
>                     } else if (scrollElem.height() - event.pageY <= 0) {
>                         scrollAnimation = !scrollAnimation.isActive() ?
> ```

Similar to the previous comment (we should either pick one style or the other for both):
```js
if (!scrollAnimation.isActive()) {
  scrollAnimation = TweenLite.to(scrollElem, 3 - scrollSpeed, { scrollTo: { y: scrollElem[0].scrollHeight - scrollElem.height() } });
}
```
If we don't want the if statement version, this statement could use some indentation fixes as the lines are not split clearly between the main `then` and `else` branches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903)*

**Comment by milesap** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/toc/toc.directive.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiSJWZv6dafI4Gst_x:-KMj3YkbUbWH9i7GtYB9:701701372) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L76)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> el / elem naming: can we do one of the following
> - document the difference between the variables
> - name them such that the difference is clear
> - if they are the same can we drop `elem` altogether and only use `el` (pretty sure this is not the case)
</details>
Renamed them so it is clear throughout

---

*[src/app/ui/toc/toc.directive.js, line 90 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiTsBOQrbHb8A_L4tp:-KMj3qmlD6kuYNM18gk3:-962271273) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L90)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> How about:
> ```js
> if (!scrollAnimation.isActive()) {
>   scrollAnimation = TweenLite.to(scrollElem, scrollSpeed, { scrollTo: { y: 0 } });
> }
> ```
> To me this reads better than the ternary statement split over multiple lines.
</details>
:+1:  agreed

---

*[src/app/ui/toc/toc.directive.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiUKN5J0bVA5Wfl8dC:-KMj3t8UZkY8GKVGtrEy:-962271273) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L96)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Similar to the previous comment (we should either pick one style or the other for both):
> ```js
> if (!scrollAnimation.isActive()) {
>   scrollAnimation = TweenLite.to(scrollElem, 3 - scrollSpeed, { scrollTo: { y: scrollElem[0].scrollHeight - scrollElem.height() } });
> }
> ```
> If we don't want the if statement version, this statement could use some indentation fixes as the lines are not split clearly between the main `then` and `else` branches.
</details>
:+1:  agreed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.directive.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-KMiSJWZv6dafI4Gst_x:-KMj5WmKZeGuPtmLHgjn:-1221266418) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc0de2e9450a6c7d462ee5d549cc07a0dae21980/src/app/ui/toc/toc.directive.js#L76)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Renamed them so it is clear throughout
</details>
thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903)*

**Comment by spencerwahl** [comment]
The scrolling trigger seems very high when dragging group names, are they dragula controlled or are we able to mess with the numbers?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903#-:-KMjBZFuhHOkWqVSGIL6:1642994920)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/903)*

**Pull request merged**
