### PR TITLE
Release tutorial

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Cloeses #2796 

Tutorial on how to do a release.
## Testing

NA
## Documentation

`index.html`, `release_tutorial.md`
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Good guide :lgtm:  :+1: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @barryytm, @ShrutiVellanki, @james-rae, @dane-thomas, and @JahidAhmed)

---

*[docs/developer/release_tutorial.md, line 25 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802#-LFbdXmD0Lt2FA7SXw3D:-LFbdXmD0Lt2FA7SXw3E:b55kx5d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ddf4bcdca9775acd22b13dfbab07c44cb7781dee/docs/developer/release_tutorial.md#L25)):*
> ```Markdown
> 
>     <p class="danger">
>         Please ensure upstream master and upstream develop are aligned i.e. mergeable.
> ```

People can use `git branch -f master upstream/master` to force-point their local master branch to the upstream one. Since you shouldn't really do anything to your master branch, I think it should be fine to just re-point it if it gets out of sync.

---

*[docs/developer/release_tutorial.md, line 77 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802#-LFbeDUx080s6z-pXOaW:-LFbeDUx080s6z-pXOaX:benpsw9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ddf4bcdca9775acd22b13dfbab07c44cb7781dee/docs/developer/release_tutorial.md#L77)):*
> ```Markdown
> 
>     <p class="danger">
>         Please ensure upstream master and upstream develop are aligned i.e. mergeable.
> ```

Same comment as above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802#-:-LFbeSs0-MZ5NGgOuxcs:b-nueylk)*

**Comment by dane-thomas** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @barryytm, @ShrutiVellanki, @james-rae, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)*

**Comment by ShrutiVellanki** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @barryytm, @james-rae, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)*

**Comment by barryytm** [comment]
Review status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @AleksueiR, @ShrutiVellanki, @dane-thomas, @barryytm, @james-rae, and @JahidAhmed)

---

*[docs/developer/release_tutorial.md, line 25 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802#-LFbdXmD0Lt2FA7SXw3D:-LFbtY1eBSSpUL7_K9Y0:bixmvxo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ddf4bcdca9775acd22b13dfbab07c44cb7781dee/docs/developer/release_tutorial.md#L25)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

People can use `git branch -f master upstream/master` to force-point their local master branch to the upstream one. Since you shouldn't really do anything to your master branch, I think it should be fine to just re-point it if it gets out of sync.
</blockquote></details>

It didn't mean to do anything to the local master branch but the need to ensure that the upstream develop is not behind upstream master.  I've reworded it to make it more clear and put it a step before to avoid the confusion.  Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @AleksueiR, @barryytm, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)*

**Comment by AleksueiR** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)

---

*[docs/developer/release_tutorial.md, line 25 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802#-LFbdXmD0Lt2FA7SXw3D:-LFs3KFP90JsD8GptTXz:b-v2lh64) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/39fc414d4d88b1b8908f0ae880dab98a66e590f4/docs/developer/release_tutorial.md#L25)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

It didn't mean to do anything to the local master branch but the need to ensure that the upstream develop is not behind upstream master.  I've reworded it to make it more clear and put it a step before to avoid the confusion.  Thanks.
</blockquote></details>

Sound good. Thanks :+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)*

**Pull request merged**
