### PR TITLE
2131 2345 confusing opacity slider and stuck legend stack

### LINKED ISSUE #2131: Opacity control confusing on Non-Dynamic Dynamics
^ Issue title is also confusing 🏆 

Add http://section917.cloudapp.net/arcgis/rest/services/TestData/Nest/MapServer as a dynamic layer, selecting the `0` index (`Group1`) as the only item.  
Then open the Settings for one of the child layers. You will see the opacity slider, but cannot interact with it.  Changing opacity at the root will update the child slider accordingly.  Since service is not Dynamic (esri term, different from Dynamic Layer on client), this is expected.

Suggest there be a more clear indication that the slider is disabled (more faded? an icon? the text ` (NO!)` beside the word Opacity?).  When I opened the panel I tried to adjust it fully expecting it to work.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
- [bug #2345] legend block symbology stack got stuck when expanded from the menu
- [bug #2131] opacity controls for `not-true-dynamic` dynamic layers are confusing - added jump link to parent block

Closes #2131, #2345

## Testing
Eyeballs.

## Documentation
Inline comments.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2347)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2347)*

**Comment by AleksueiR** [comment]
Please, check config `47` from the `index-samples` page.

---

Review status: 14 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2347#-:-KshuAbXw0ody4KivqtA:b-mdqmgk)*

**Comment by JahidAhmed** [comment]
:lgtm: nice descriptions in the sample!

---

Reviewed 10 of 17 files at r1, 3 of 4 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2347#-:-Ksi4eypCTsj45xaNYa5:b-qo30u6)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2347)*

**Pull request merged**
