### PR TITLE
fix(ui): fixed failed to load indication

### LINKED ISSUE #1433: Intermittent Bug with Layers being indicated as Failed to Load
Intermittent bug that indicates a layer has failed to load if it fails an initial load attempt.  Successful attempt is not indicated in the legend.  

May be wise to wait until Thematic Map related refactoring is complete.

**Usability Issue:**
V16. Thin red vertical bar in legend (Type: Labelling)

At some points in the usability tests, a thin red vertical bar appears beside someof the layers in the legend section and the testers would ask why (maybe it hasto do with the point information functions?). Testers tried to scroll it, and tried to click on it and still did notknow what it was for.

Comments:

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1433

## Testing
Yes

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1748)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 664 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748#-KesbZNLITZGavbUd15v:-KesbZNLITZGavbUd15w:b-fnvg1l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b9f99c5394ef52ed8c016262263a6799caddd4db/src/app/geo/layer-registry.service.js#L664)):*
> ```JavaScript
> 
>                 // reset error state - fixes issue where error state persists after reload
>                 l.state = l.state === 'rv-error' ? '' : l.state;
> ```

Since the layer is reloaded, it makes sense to reset its state to `GEO.Layer.States.NEW`, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 664 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748#-KesbZNLITZGavbUd15v:-KfBvdDp3hGZ_Kf2-ec9:bk3yy67) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b9f99c5394ef52ed8c016262263a6799caddd4db/src/app/geo/layer-registry.service.js#L664)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Since the layer is reloaded, it makes sense to reset its state to `GEO.Layer.States.NEW`, no?
</blockquote></details>

Yeah, if state is never updated then this is a good idea. Made the change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1748)*

**Pull request merged**
