### PR TITLE
bug(ui): bottom toast notification blocks panels

### LINKED ISSUE #597: bug(ui): bottom toast notification blocks panels
The toast notification appearing at the bottom of the page (about RCS not being available) extends the width of the screen (toast's container does) and it blocks elements on the main panel.

toast_blocks_panel

Rough solution idea:
position toast relatively, set the app container to flexbox, and align toast using justify-content and align-items.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #597

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/741)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/741)*

**Comment by AleksueiR** [comment]
Any way it can be tested on http://fgpv.cloudapp.net/demo/users/jolevesq/bottomToast/index-one.html ?

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> #### bug\(ui\): bottom toast notification blocks panels
> 
> Closes #597
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/741#-:-KJpUhckrojQeQ8E-1-H:-1680780516)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/741)*

**Comment by jolevesq** [comment]
I had to set show(true) to the panel to test because sometimes it appears and sometimes not.

**Pull request merged**
