### PR TITLE
Strengthen CSV validation when importing as a layer

### LINKED ISSUE #2254: Strengthen validation of the latitude and longitude fields of a  CSV when importing
Need to check all the cell values of a CSV file before going to step 3 letting users to pick the costumed latitude and longitude fields.  Otherwise it would cause errors when using the values the user selected.

capture

### PR DESCRIPTION
**Pull request by barryytm**
## Description

As title, and please see https://github.com/fgpv-vpgf/geoApi/pull/250 for the geoApi portion of this PR

Closes #2254, #2230 
## Testing

Manually

## Documentation

NA

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2270)

### CODE REVIEW

**Comment by james-rae** [comment]
You are not updating your geoApi reference.  This PR will not know about your changes in geoApi

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2270#-:-Kpzt5_E3rRi-PxTHwP9:bcuvtnv)*

**Comment by milesap** [comment]
The "Release notes have been updated" is checked but I can't see the notes have been updated:
https://github.com/fgpv-vpgf/fgpv-vpgf/releases/tag/untagged-6cacb33c51089ded1a48

**Comment by barryytm** [comment]
Just updated the release note, thanks.  Don't merge this yet, it needs to wait until the geoAPI side merged.

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2270)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2270)*

**Pull request merged**
