### PR TITLE
Integer OID from Identify

### PR DESCRIPTION
**Pull request by james-rae**
Pass integer OID from identify to details pane. Prevents local feature search from breaking 

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1041

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1120)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Need to remember to switch back to Github links in eight months. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1120#-:-KQ74w_TnFj07mAct6hZ:bkd2qu9)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1120#-:-KQLhXZbhFFd6hdSYNkX:bnfp4nl)*

**Comment by milesap** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1120)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1120)*

**Pull request merged**
