### PR TITLE
perf(ui): data panel content creation from ng-repeat to document frag

### LINKED ISSUE #542: Efficiency of Data Panel content creation
Right now ng-repeat inserts list items containing two divs one at a time, this is inefficient in both DOM manipulations and content layout.

Proposal from @AleksueiR: (paraphrased)
- Construct details list using without ng-repeat by creating dom elements in a document fragment and inserting them into the template in one go

### PR DESCRIPTION
**Pull request by milesap**
Closes #542

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/657)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/details/details-data.directive.js, line 34 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-KIhNY0tlDCASApnHkvZ:-KIhNY0tlDCASApnHkv_:1575977133) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41a11cde3befb2fcfacf45adec9f8cbbace88b82/src/app/ui/details/details-data.directive.js#L34)):*
> ```JavaScript
>                 if (data) {
>                     element.empty(); // clear existing data elements
>                     const frag = angular.element(document.createDocumentFragment());
> ```

You are turning dom fragments into jquery objects right away. Doesn't it negate any performance gain? Have you see any improvements?

---

*[src/app/ui/details/details-data.directive.js, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-KIhQX4GwKch4IC6QaW7:-KIhQX4GwKch4IC6QaW8:1639298215) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41a11cde3befb2fcfacf45adec9f8cbbace88b82/src/app/ui/details/details-data.directive.js#L49)):*
> ```JavaScript
>                         frag.append(ul);
>                     });
>                     element.append(frag);
> ```

Can you add the original template as a comment for future reference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/details/details-data.directive.js, line 34 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-KIhNY0tlDCASApnHkvZ:-KIhbpuqFoRN_ACgoDqX:-1221262473) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41a11cde3befb2fcfacf45adec9f8cbbace88b82/src/app/ui/details/details-data.directive.js#L34)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> You are turning dom fragments into jquery objects right away. Doesn't it negate any performance gain? Have you see any improvements?
</details>
The performance gain is achieved by only having one DOM append. There doesn't seem to be any quantifiable performance loss by converting to jquery objects. Fastest fragment generation and appending time is 1.52ms, highest is 5.96ms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-data.directive.js, line 34 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-KIhNY0tlDCASApnHkvZ:-KIhyCGnbjGRjeMhAxMn:1794731161) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41a11cde3befb2fcfacf45adec9f8cbbace88b82/src/app/ui/details/details-data.directive.js#L34)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> The performance gain is achieved by only having one DOM append. There doesn't seem to be any quantifiable performance loss by converting to jquery objects. Fastest fragment generation and appending time is 1.52ms, highest is 5.96ms.
</details>
Great!

---

*[src/app/ui/details/details-data.directive.js, line 21 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-KIhyULyPd7VjEq95lOT:-KIhyULyPd7VjEq95lOU:1496642263) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e14856a270e2b53fc2e2cb17536f60d880c4f884/src/app/ui/details/details-data.directive.js#L21)):*
> ```JavaScript
>     function rvDetailsData() {
>         const directive = {
>             restrict: 'E',
> ```

If it's not a big change, can you turn this in an attribute directive?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Comment by milesap** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/details/details-data.directive.js, line 21 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-KIhyULyPd7VjEq95lOT:-KIi0_ZhMK7QhyrYiiBY:-1407218161) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e14856a270e2b53fc2e2cb17536f60d880c4f884/src/app/ui/details/details-data.directive.js#L21)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> If it's not a big change, can you turn this in an attribute directive?
</details>
changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-data.directive.js, line 21 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-KIhyULyPd7VjEq95lOT:-KIi0v7ComLp-soe4DBQ:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e14856a270e2b53fc2e2cb17536f60d880c4f884/src/app/ui/details/details-data.directive.js#L21)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> changed
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Comment by AleksueiR** [comment]
:lgtm:

<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### perf\(ui\): data panel content creation from ng\-repeat to document frag
> 
> Closes #542
> 
> 
> 
</details>


---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657#-:-KIi11wZcWQlWXLrUq6C:1417088721)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/657)*

**Pull request merged**
