### PR TITLE
Keep state on projection switch

### PR DESCRIPTION
**Pull request by spencerwahl**
issue #715

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/809)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 140 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809#-KKsWQXgXdAGVsx1qM_I:-KKsWQXgXdAGVsx1qM_J:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0ff9332bc0f8e1722aa218ca51ade8c46b0aea06/src/app/core/bookmark.service.js#L140)):*
> ```JavaScript
>         }
> 
>         function updateConfig() {
> ```

jsdoc

---

*[src/app/core/reload.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809#-KKsWMkaGzuchvuypVxz:-KKsWMkaGzuchvuypVy-:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0ff9332bc0f8e1722aa218ca51ade8c46b0aea06/src/app/core/reload.service.js#L1)):*
> ```JavaScript
> angular
> ```

jsdoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 140 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809#-KKsWQXgXdAGVsx1qM_I:-KKs_gyRlpsBmMDWTxgk:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0ff9332bc0f8e1722aa218ca51ade8c46b0aea06/src/app/core/bookmark.service.js#L140)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> jsdoc
</details>
Done.

---

*[src/app/core/reload.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809#-KKsWMkaGzuchvuypVxz:-KKs_gKKDyWk9Sue1Ry8:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0ff9332bc0f8e1722aa218ca51ade8c46b0aea06/src/app/core/reload.service.js#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> jsdoc
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809)*

**Comment by cynngah** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/809)*

**Pull request merged**
