### PR TITLE
feat(help): add markdown support

### LINKED ISSUE #1555: Allow for inclusion of images in Help section
At the moment, in-app help can only contain text. Need a way to include images with the text and to allow for more formatting options (headings, bold, lists, etc.).

Any ideas on how to do that?

Use markdown in translation file and run markdown processor during the build step, so we don't have to store any html in the translations?

### PR DESCRIPTION
**Pull request by milesap**
## Description
Help documents now reside in src/locales/help/ and there should be one
file per supported language. There is also an image folder. Everything
in this help folder is rolled up into the build/samples/help/ folder to
be accessible by the viewer.

Help sections always begin with one hashbang, and end with a double new
line.

Closes #1555

## Testing
In browser testing

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1787)

### CODE REVIEW

**Comment by milesap** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/help/help.service.js, line 162 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfgrAcZpQuTr9tE6vKf:-KfgrAcZpQuTr9tE6vKg:b454t3u) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad4fe2c337a6d2203fff6f32fb5edf511220a9e5/src/app/ui/help/help.service.js#L162)):*
> ```JavaScript
>                         // parse markdown on info section only. Note that the split/splice/join removes the header
>                         // and is a workaround for not being able to put info section into its own regex grouping like the header
>                         info: marked(section[0].split('\n').splice(2).join('\n'), { renderer }),
> ```

I wrote an alternative regex `^#\s(.*)\n*([^#]*)` which is able the capture info as a second grouping. The downside is that hashbangs cannot be used in the markdown. The upside is performance. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by milesap** [comment]
Just an fyi, a put the image samples under the `help` section

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-:-KfgtmSuHwsyuTWaHvpW:b8szcm4)*

**Comment by milesap** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/help/help.service.js, line 145 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfguVNhi9H47qWaeekG:-KfguVNhi9H47qWaeekH:bginc65) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6a8ea3d74b103af8a485115d518ddae178b1df85/src/app/ui/help/help.service.js#L145)):*
> ```JavaScript
>                 // matches help sections from markdown file where each section begins with one hashbang and a space
>                 // followed by the section header, exactly 2 spaces, then up to but not including a double space
>                 // note that the {5,} below is used as the double line deparator since each double new line is actually 6
> ```

Update this from {5,} to {2,} - not sure why but the {5,} is needed locally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by AleksueiR** [comment]
Do help images make it into the release package?

The help search highlighter needs to be fixed, but I guess it's a separate task:

Normal:


Highlighted:


---

Reviewed 7 of 9 files at r1, 1 of 1 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/help/help.service.js, line 162 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfgrAcZpQuTr9tE6vKf:-KfkY5K7Ynetg7DsOqyy:btyirf0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad4fe2c337a6d2203fff6f32fb5edf511220a9e5/src/app/ui/help/help.service.js#L162)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I wrote an alternative regex `^#\s(.*)\n*([^#]*)` which is able the capture info as a second grouping. The downside is that hashbangs cannot be used in the markdown. The upside is performance. 
</blockquote></details>

How big is the performance hit?

---

*[src/locales/help/en-CA.md, line 59 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfkYD7qtKj-2zbkqxwp:-KfkYD7qtKj-2zbkqxwq:b-9c3vn7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6a8ea3d74b103af8a485115d518ddae178b1df85/src/locales/help/en-CA.md#L59)):*
> ```Markdown
> 
> 
> # Help
> ```

Please remove these sample sections and the corresponding images.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-:-KfkXaGnKltLL832w8So:bk2n3sz)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/help/help.service.js, line 162 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfgrAcZpQuTr9tE6vKf:-KfkvEKQHQ_IyDNAL5Hi:b-cyf94k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad4fe2c337a6d2203fff6f32fb5edf511220a9e5/src/app/ui/help/help.service.js#L162)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

How big is the performance hit?
</blockquote></details>

Nevermind, did a formal performance test between the two and the current implementation is roughly twice as fast. Initial regex run on average  7.89ms then drops to an average of 1.3625ms on subsequent same page loads (I assume regex caching is causing this nice improvement). The alternative is roughly 14.817ms initial, with 3ms subsequent. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/help/help.service.js, line 162 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfgrAcZpQuTr9tE6vKf:-Kfkw_651oOnpG7m-gx9:b-poeqch) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad4fe2c337a6d2203fff6f32fb5edf511220a9e5/src/app/ui/help/help.service.js#L162)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Nevermind, did a formal performance test between the two and the current implementation is roughly twice as fast. Initial regex run on average  7.89ms then drops to an average of 1.3625ms on subsequent same page loads (I assume regex caching is causing this nice improvement). The alternative is roughly 14.817ms initial, with 3ms subsequent. 
</blockquote></details>

:+1: :1st_place_medal: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by milesap** [comment]
Images make it into the release package along with the markdown files. Seems highlighting also targets html element attributes, so this should be corrected in another PR (opened #1797)

---

Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/help/help.service.js, line 145 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfguVNhi9H47qWaeekG:-Kfl0SLRymU9wcD6n2f5:b-a2ujfz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6a8ea3d74b103af8a485115d518ddae178b1df85/src/app/ui/help/help.service.js#L145)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Update this from {5,} to {2,} - not sure why but the {5,} is needed locally
</blockquote></details>

Changed 

---

*[src/locales/help/en-CA.md, line 59 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfkYD7qtKj-2zbkqxwp:-Kfl0UGx4J7PufC5agJC:ba3dfob) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6a8ea3d74b103af8a485115d518ddae178b1df85/src/locales/help/en-CA.md#L59)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please remove these sample sections and the corresponding images.
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-:-Kfl-OYORPgopBHCoGar:b-2gudym)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/locales/help/en-CA.md, line 59 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfkYD7qtKj-2zbkqxwp:-Kfl0o_DRPS2g3b6DSkO:b-xsdhmt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6a8ea3d74b103af8a485115d518ddae178b1df85/src/locales/help/en-CA.md#L59)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Forgot to remove the actual files (rebase, architecture).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 7 of 9 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/help/help.service.js, line 136 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-Kfl0InSqXXuXwIrbfRB:-Kfl0InSqXXuXwIrbfRC:bp5nhg4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/34d659c39094b660d4280189d5acbc4c73668ea2/src/app/ui/help/help.service.js#L136)):*
> ```JavaScript
>             renderer.image = (href, title) => {
>                 if (href.indexOf('http') === -1) {
>                     href = 'help/images/' + href;
> ```

I think help and help images will need to be configurable for certain deployments (like openmaps), but this can be in a separate task.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-:-Kfl1AzCk3I2v950Pz4l:bnfp4nl)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/help/help.service.js, line 136 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-Kfl0InSqXXuXwIrbfRB:-Kfl2v_0_u8h5Kt9D8Ix:br4mqqr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/34d659c39094b660d4280189d5acbc4c73668ea2/src/app/ui/help/help.service.js#L136)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

I think help and help images will need to be configurable for certain deployments (like openmaps), but this can be in a separate task.
</blockquote></details>

agreed :+1: 

---

*[src/locales/help/en-CA.md, line 59 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787#-KfkYD7qtKj-2zbkqxwp:-Kfl3X0BNgu8b4GEPLEA:be6pwhe) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6a8ea3d74b103af8a485115d518ddae178b1df85/src/locales/help/en-CA.md#L59)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Forgot to remove the actual files (rebase, architecture).
</blockquote></details>



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by alyec** [comment]
Reviewed 2 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1787)*

**Pull request merged**
