### PR TITLE
feat(config): only load config and RCS as needed.

### LINKED ISSUE #498: Efficiency of config load and language switch
## Current Situation

When the application loads, it generates a configuration file for each supported language. This includes pulling in RCS configuration snippets; RCS is called once per language.

The advantage is that having cached versions of configs allows for a quick and 'easy to code' language switch.

The disadvantage is it is a performance hit (magnitude has not been tested) at startup.
## Proposal 1: RCS Returns All Languages

Have RCS return all languages for keys in one bundle.  This removes the need for multiple calls, which is the heavy part of the transaction (the data itself is moderately sized json data).  
Requires a change to RCS (guts and interface).  Also a change to the config loader in the app, but minimal.

Future enhancement: if large pieces of data start getting stored in the RCS (e.g. full blown legends), make that downloadable with a separate call and grab them as needed, not at startup.
## Proposal 2: Only Load Config Information For Current Language

No longer load all language configs at startup.  Only the active language.  When a language switch occurs, download and process the new config info.
Faster startup than Proposal 1, slower language switch.  
RCS is not changed
Significant refactor to config load and language switch code in the viewer.

Future enhancement: cache configs after first load, optimizing the rare case where someone can't make up their mind about language and keeps switching it.

### PR DESCRIPTION
**Pull request by milesap**
## Description

Follows `Proposal 2: Only Load Config Information For Current Language` from https://github.com/fgpv-vpgf/fgpv-vpgf/issues/498

Closes #498

## Testing
`index-sample.html` with and without RCS

## Documentation
inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2414)

### CODE REVIEW

**Comment by james-rae** [comment]
I can't get RCS layers to load via the URL. I usually use the [FGP test page](http://fgpv.cloudapp.net/demo/users/milesap/498-config-loading/dev/samples/index-fgp-en.html?keys=JOSM) (so don't need to worry about the config swapper on the samples test page).  Looking at the network tab, I don't see any request being made to RCS.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2414#-:-KvhtSu-3xwFvIDXX5Pi:b-w9x7ai)*

**Comment by milesap** [comment]
Fixed RCS issue

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2414#-:-KwLnz41NvP-RdOGtSA-:bd2r3t6)*

**Comment by james-rae** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2414#-:-KwLrKRO0iGMa02dHdCB:bnfp4nl)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2414#-:-KwegbaW0M7eSL0InlR4:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2414)*

**Pull request merged**
