### PR TITLE
feat(logs): implement a logging library

### LINKED ISSUE #981: Investigate options for exception management and logging libraries

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #981

## Testing
Yes

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1836)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836)*

**Comment by AleksueiR** [comment]
:lgtm: I did ~~read~~ scroll through all the files!

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gulpfile.js, line 362 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836#-Kh2Phq0ugFIHtoEI4qp:-Kh2Phq1M4s6AfMId8wK:bh9425n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b8f7a66d115e2d61245543aafe40b7d96f9bf04/gulpfile.js#L362)):*
> ```JavaScript
>         return gulp
>             .src(index)
>             .pipe($.injectString.before('', `<script>window.PROD_MODE = ${!!PROD_MODE}</script>
> ```

Better to created `window.RV` and store `PROD_MODE` there. `PROD_MODE` sounds pretty common and can be used as a global on host pages. Bootstrap should handle an existing `window.RV` object.

---

*[src/app/common/router/displaymanager.service.js, line 172 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836#-Kh2QOedIxSGMX3-cQhd:-Kh2QOedIxSGMX3-cQhe:b1pvxqs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b8f7a66d115e2d61245543aafe40b7d96f9bf04/src/app/common/router/displaymanager.service.js#L172)):*
> ```JavaScript
>                             $timeout.cancel(display.loadingTimeout);
>                         } else {
>                             RV.logger.log('displayManager', `${displayName}: data rejected for request id ` +
> ```

Clearing up TODOs :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836#-:-Kh2R9RiQLuso138CYE6:b7lhz5v)*

**Comment by milesap** [comment]
It is a lot of scrolling :+1: 

---

Review status: 37 of 40 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gulpfile.js, line 362 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836#-Kh2Phq0ugFIHtoEI4qp:-Kh2Uj3-jOcFrlrFfKC2:b-l4yggl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b8f7a66d115e2d61245543aafe40b7d96f9bf04/gulpfile.js#L362)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Better to created `window.RV` and store `PROD_MODE` there. `PROD_MODE` sounds pretty common and can be used as a global on host pages. Bootstrap should handle an existing `window.RV` object.
</blockquote></details>

Good idea, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836#-:-Kh2Ul7wcYUut-JfomTR:b-mo6ayi)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836)*

**Comment by AleksueiR** [comment]
Nice colours :D

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1836#-:-Kh82c3U_0IlHpjGkHbJ:b-siebsv)*

**Pull request merged**
