### PR TITLE
Config loading for language switching

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/362)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/core/config.service.js, line 151 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBUBJ_fdTpL1yW7w03K:-KBUBJ_fdTpL1yW7w03L:1437302844) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6c4c54d2f7c14410e51c313be29cd0feea9dbe4c/src/app/core/config.service.js#L151)):*
Missing `@returns`

---

*[src/app/ui/basemap/basemap.directive.js, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBUAq_lQC7_8EC1gEiH:-KBUAq_mSFxvb82qmPyh:467550332) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ce468014dcbd2d9f89de6c40317cf141ba42294/src/app/ui/basemap/basemap.directive.js#L100)):*
Why did the FIXME disappear?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by spencerwahl** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 151 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBUBJ_fdTpL1yW7w03K:-KBUPcJjsw18zKebjesN:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6c4c54d2f7c14410e51c313be29cd0feea9dbe4c/src/app/core/config.service.js#L151)):*
Done.

---

*[src/app/ui/basemap/basemap.directive.js, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBUAq_lQC7_8EC1gEiH:-KBUD0ZFCS2DqBGhd54G:290608672) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ce468014dcbd2d9f89de6c40317cf141ba42294/src/app/ui/basemap/basemap.directive.js#L100)):*
Probably got caught in a rebase conflict. Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by ec-dev** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 7 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/index-one.html, line 20 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh1tnmAtaqPgBRcQIW:-KBh1tnmAtaqPgBRcQIX:-901533793) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/index-one.html#L20)):*
Let's add brackets around `lang`, something like es6 template string: `${lang}`.
Otherwise it may look like periods act as boundaries.

---

*[src/app/core/config.service.js, line 116 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh4Fp-ibiAIMiGm0_t:-KBh4Fp00sWliBD_BPeo:-1298108414) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/app/core/config.service.js#L116)):*
This looks like the initialization will fail if one of the language configs (not even the current one) can't be loaded.  I think if any of the non-current languages fail to load, they should be taken from the array of available languages, but the app should still initialize properly.

---

*[src/app/layout/shell.directive.js, line 153 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh4ohnbFJVY5D9Sx9J:-KBh4ohnbFJVY5D9Sx9K:1610292884) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/app/layout/shell.directive.js#L153)):*
As I said before, please, don't use dom manipulations outside link functions. `init-map` directive should register its node with the config service or geo service when it's initialized. Moreover, this selector will get all map nodes on the page, not only the node from the currently running app instance.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/layout/shell.directive.js, line 153 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh4ohnbFJVY5D9Sx9J:-KBhFwPwSL7CJMVlxz3G:-736911885) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/app/layout/shell.directive.js#L153)):*
All configs are equal, but some are more equal than others.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by ec-dev** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/layout/shell.directive.js, line 153 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh4ohnbFJVY5D9Sx9J:-KBo5IV2zOIxtAzb_5jM:1463468253) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/app/layout/shell.directive.js#L153)):*
I think this one can wait. As I have the change already done for the geo service. Will update this when I resolve my PR

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index-one.html, line 20 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh1tnmAtaqPgBRcQIW:-KBt751sl8f2dNBg-Bnj:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/index-one.html#L20)):*
Done.

---

*[src/app/core/config.service.js, line 116 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh4Fp-ibiAIMiGm0_t:-KBt6lWGbqhPl14cCsTJ:381825809) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/app/core/config.service.js#L116)):*
It should now wait for only the "default" language to load (currently hardcoded to en). At some point we should have a way to notify that the initial language has been set.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/layout/shell.directive.js, line 153 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh4ohnbFJVY5D9Sx9J:-KBxzftgfqyFrnIvaydw:1850022013) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/app/layout/shell.directive.js#L153)):*
Please, add a `TODO` to fix it. Thanks.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.directive.js, line 153 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362#-KBh4ohnbFJVY5D9Sx9J:-KBy-uwLURKN4cOMANvm:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc6dbedbcd65fd6b487357ca9b40f90927390441/src/app/layout/shell.directive.js#L153)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by ec-dev** [comment]
Reviewed 5 of 8 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by ec-dev** [comment]
Reviewed 2 of 8 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by AleksueiR** [comment]
Reviewed 7 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Comment by ec-dev** [comment]
Reviewed 1 of 8 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/362)*

**Pull request merged**
