### PR TITLE
feat(details): add pictures to details panel and hovering. when click…

### PR DESCRIPTION
**Pull request by jolevesq**
… on the link, open the picture in a lightbox

Closes 1864

## Description

Add a picture inside details panel and hovering tooltip

## Testing

Chrome, FF and Safari (regular and fullscreen)

Use this layer: http://geoappext.nrcan.gc.ca/arcgis/rest/services/test/pointimage/MapServer/0

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1881)

### CODE REVIEW

**Comment by milesap** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-KjscROSWcMMMxIKMeoT:-KjscROSWcMMMxIKMeoU:b-l7qer1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb584585d097e87dd2d645e53dd406f3820f36f/bower.json#L55)):*
> ```JSON
>     },
>     "magnific-popup": {
>         "main": "dist/jquery.magnific-popup.min.js"
> ```

Avoid using `.min` where possible as it makes it hard to debug on `develop`. Our build will minimize it anyways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881)*

**Comment by AleksueiR** [comment]
Are there any benefits to using `magnific-popop` over [Angular Material dialogs](https://material.angularjs.org/latest/demo/dialog) we use for everything else? You get the same functionality (opening picture in a separate dialog) without importing another library.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-:-KjwT0S9UScFEN3g5Dsj:bqsqdit)*

**Comment by jolevesq** [comment]
For only one images maybe not but magnific popup have the gallery images as well so controls to navigate between images are already implemented. In This PR I only have a service with 1 image but in GCViz we have the ability to have multiples images in one field so it creates an image gallery.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-KjscROSWcMMMxIKMeoT:-KkB5WeMxoCYkOeVB9Xc:b-29x2k1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb584585d097e87dd2d645e53dd406f3820f36f/bower.json#L55)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Avoid using `.min` where possible as it makes it hard to debug on `develop`. Our build will minimize it anyways.
</blockquote></details>

Thanks, good to know

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-:-KkB52IdanyrgHjuKz_O:b-kzb5p0)*

**Comment by AleksueiR** [comment]
Can we use something like https://github.com/alirezamirian/angular-material-lightbox to keep the UI consistent with Material Design guidelines?

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-:-KkL7Ov14AD2B7UaHmd4:boqtxd0)*

**Comment by AleksueiR** [comment]
Reviewed 16 of 18 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 385 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-Kl-oDdT3VPYG3ffD1ff:-Kl-oDdT3VPYG3ffD1fg:banr6xy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27a7a047398d174dbd032e771bc219263b306835/src/app/geo/layer-registry.service.js#L385)):*
> ```JavaScript
>                         if (tipContent && tipContent.graphic === e.target) {
>                             tipContent.name = e.name;
>                             tipContent.name = $filter('picture')(e.name);
> ```

I think it should be responsibility of the hover tip template to figure out if it should display an image in the tooltip or a feature symbol with its name. 
Trying to display in image inside the regular tooltip, will still show the feature symbol to the left of the image, which looks wierd to me:


---

*[src/app/ui/lightbox/lightbox.directive.js, line 14 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-Kl-m58Y_X3i_kUUQQP6:-Kl-m58Y_X3i_kUUQQP7:bz6wxuo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27a7a047398d174dbd032e771bc219263b306835/src/app/ui/lightbox/lightbox.directive.js#L14)):*
> ```JavaScript
>      */
>     angular
>         .module('app.ui.lightbox')
> ```

Please just use `app,ui` module. We want to move all `app.ui.x` modules to just `app.ui` for simplicity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881)*

**Comment by jolevesq** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 385 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-Kl-oDdT3VPYG3ffD1ff:-Kl3v5uk5mzmy4vC4VPs:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27a7a047398d174dbd032e771bc219263b306835/src/app/geo/layer-registry.service.js#L385)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think it should be responsibility of the hover tip template to figure out if it should display an image in the tooltip or a feature symbol with its name. 
Trying to display in image inside the regular tooltip, will still show the feature symbol to the left of the image, which looks wierd to me:



</blockquote></details>

Done.

---

*[src/app/ui/lightbox/lightbox.directive.js, line 14 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-Kl-m58Y_X3i_kUUQQP6:-Kl3o3AfU61XrRlFjdba:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27a7a047398d174dbd032e771bc219263b306835/src/app/ui/lightbox/lightbox.directive.js#L14)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please just use `app,ui` module. We want to move all `app.ui.x` modules to just `app.ui` for simplicity.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-:-Kl3zo-KywI623KQ2pWB:bnfp4nl)*

**Comment by milesap** [comment]
Reviewed 11 of 18 files at r2, 2 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881)*

**Comment by milesap** [comment]
Please rebase for merge

---

Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-:-Klx-RT0SoFAkEWI5XBp:b9h8vna)*

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 7 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-:-KlyJza7GIk8Z0QKts3H:bg7igkv)*

**Comment by AleksueiR** [comment]
I think a couple of old files have been resurrected:
- `src/app/common/formatters` - the common module was removed, so there shouldn't be any files in that folder; the proper file should be in `src/app/core/formatters`;
- `gulp.config` file is not longer used, replaced by webpack

Can you remove them?

---

Reviewed 7 of 8 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1881#-:-KlyMO1yGu3ZTFXFiib1:bph4u8z)*

**Pull request merged**
