### PR TITLE
Add fgp template sites

### PR DESCRIPTION
**Pull request by spencerwahl**
Also adds language switching to index-wet

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/480)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/480)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/480)*

**Comment by spencerwahl** [comment]
Don't merge, there are some language-code consistency changes coming

**Comment by AleksueiR** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/480)*

**Comment by ec-dev** [comment]
Reviewed 11 of 11 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/480)*

**Pull request merged**
