### PR TITLE
fix(core): map export respects config values

### LINKED ISSUE #2062: Download export map - missing Footnote
Tested build:  http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html

Footnote check mark is checked under map export settings.
image

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
In 2.0, map export service was ignoring config export values and using all export components except the footnote. This is fixed now, and only export components specified in the config will be available in the map export dialog.

- piggy backing a bit of documentation #1096
- fix layer type flags by using `parentLayerType` from geoApi proto 72 #2067 

Closes #2062, #1096, #2067 

## Testing
Some eyeballs

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ unreleased bug - was working in 1.7
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2074)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/developer/function/symbology.md, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoJS7YYXumvTxcg_gt:-KnoJS7ZMbaCevv0wmLh:b-6t4a4n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ac243d2fc37cc57a937d483e26ebf7e10fcac1ad/docs/developer/function/symbology.md#L3)):*
> ```Markdown
> A layer's symbology or legend is a collection of image-labels pairs explaining features available in the layer. Internally, it's referred to as a "symbology stack" with the "stack" bit describing its vertical orientation when rendered in the UI.
> 
> As of version 2.0, symbology is only an information devices, and provides no interactivity. However, there are plans to provide additional filtering capabilities to layers support filtering using the renderer clauses, see issue [#1442](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1442) for more details.
> ```

`informational device` ?
`there are plans to provide layer filtering by symbol, see issue...`

---

*[src/app/ui/toc/legend-element-factory.class.js, line 385 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoKzT0BSE8N_QtWVUF:-KnoKzT1Ly-MhmlumF1s:b-uhw2b6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/src/app/ui/toc/legend-element-factory.class.js#L385)):*
> ```JavaScript
> 
>         get style () {   return this._styles[this.block.parentLayerType || TypeFlag.unresolvedType]; }
>         get icon () {    return this._icons[this.block.parentLayerType || TypeFlag.unresolvedType]; }
> ```

Not sure how this will behave with Raster Layer child. Perhaps it no longer matters (we always show `Dynamic` if a child is in a dynamic layer).  But it means (far as I can tell) that we no longer indicate if a child is feature based or raster based.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by JahidAhmed** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/function/index.json, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoLS6xC-fQLDI_-K1Y:-KnoLS6xC-fQLDI_-K1Z:bo8guut) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/docs/developer/function/index.json#L11)):*
> ```JSON
>     },
> 
>     "symboloyg": {
> ```

Possible Typo: symbology

---

*[src/app/core/config.class.js, line 1538 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoMKOGaS6mFzs9Z3GR:-KnoMKOGaS6mFzs9Z3GS:b-xvdpb5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/src/app/core/config.class.js#L1538)):*
> ```JavaScript
> 
>         get JSON() {
>             return {
> ```

Should this be using the getters instead of the variables. ie. `this.isSelected` instead of `this._isSelected`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by AleksueiR** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/function/symbology.md, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoJS7YYXumvTxcg_gt:-KnoM_62QWUulpiM4cIT:bh1060k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ac243d2fc37cc57a937d483e26ebf7e10fcac1ad/docs/developer/function/symbology.md#L3)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`informational device` ?
`there are plans to provide layer filtering by symbol, see issue...`
</blockquote></details>

Nonsense fixed.

---

*[src/app/ui/toc/legend-element-factory.class.js, line 385 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoKzT0BSE8N_QtWVUF:-KnoMyVLctcL94TEAOy5:b-47qa2e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/src/app/ui/toc/legend-element-factory.class.js#L385)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Not sure how this will behave with Raster Layer child. Perhaps it no longer matters (we always show `Dynamic` if a child is in a dynamic layer).  But it means (far as I can tell) that we no longer indicate if a child is feature based or raster based.
</blockquote></details>

Yes, a Raster Layer get a dynamic flag:


Need to remove empty parens though.

Do we want to indicate if a layer is feature/raster based? How would this look like and how would your word it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by AleksueiR** [comment]
Review status: 8 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/function/index.json, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoLS6xC-fQLDI_-K1Y:-KnoNZfNbYRrbX19Z66I:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/docs/developer/function/index.json#L11)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Possible Typo: symbology
</blockquote></details>

Done.

---

*[src/app/core/config.class.js, line 1538 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoMKOGaS6mFzs9Z3GR:-KnoNfXEs-2VUihs-uuf:b-9w715g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/src/app/core/config.class.js#L1538)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Should this be using the getters instead of the variables. ie. `this.isSelected` instead of `this._isSelected`
</blockquote></details>

True. Fixed. Thanks for noticing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/legend-element-factory.class.js, line 385 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoKzT0BSE8N_QtWVUF:-KnoOsqKX6yyeEBm016s:b-ekwu4e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/src/app/ui/toc/legend-element-factory.class.js#L385)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Yes, a Raster Layer get a dynamic flag:


Need to remove empty parens though.

Do we want to indicate if a layer is feature/raster based? How would this look like and how would your word it?

</blockquote></details>

Two options I can think of. One is a two icon approach, but that would be inconsistent with other legend blocks. 
I think in the past (RAMP1?) if it was raster we has `No Features` in the brackets. We could also put `Raster Layer`, `Raster`,  `Raster Source` in the brackets.
Will defer to your UI sensibilities.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/toc/legend-element-factory.class.js, line 385 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074#-KnoKzT0BSE8N_QtWVUF:-KnoUzPDgW4wM_PL4kF0:b157xz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cd514ecbe35de6b9ab906ef7ef8b5b78316a1979/src/app/ui/toc/legend-element-factory.class.js#L385)):*
>Dynamic Layer (100 lines)
Dynamic Layer (200 polygons)
Dynamic Layer (300 lines)
Dynamic Layer (imagery)

Having a number in the brackets indicates it's feature-based.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Comment by JahidAhmed** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2074)*

**Pull request merged**
