### PR TITLE
apply babel to typescript loader

### PR DESCRIPTION
**Pull request by milesap**
## Description
Fixes IE

## Testing
muffinengineer

## Documentation
None

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2447)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2447)*

**Comment by milesap** [comment]
http://fgpv.cloudapp.net/demo/users/milesap/ie-babel-fix/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale seems to be working in IE now as well

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2447#-:-KxO0HZTCYYynWvi35KG:b-tuy6dn)*

**Comment by AleksueiR** [comment]
The above link works in IE11, but fails in IE Edge with:

> geoService failed to assemble the map with error Error: Attempted to access config synchronously before loading completed.  Either use the promise based API or wait for rvReady.

> Microsoft Edge 38.14393.1066.0
> Microsoft EdgeHTML 14.14393

Should I put it into a separate issue? 

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2447#-:-KxO7pTDplJkB7LFDOG8:b-glwfrx)*

**Comment by milesap** [comment]
I would imagine a fix on https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2442 would work for this as well. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2447#-:-KxO8PjTOiNVoaCRpPlR:bkexbso)*

**Pull request merged**
