### PR TITLE
feat(ui): add aria to data panel menu

### PR DESCRIPTION
**Pull request by AleksueiR**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/483)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/menuItem.decorator.js, line 12 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483#-KFKjxqnQA0e3l3gJHor:-KFKjxqnQA0e3l3gJHos:-453353497) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f79aa8ace0d084a74bc61a466a40dac4a915b686/src/app/ui/common/menuItem.decorator.js#L12)):*
typos: inconsistence, possitioning

---

*[src/app/ui/common/menuItem.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483#-KFKjc-R31nv70NdPkwX:-KFKjc-R31nv70NdPkwY:-1701105023) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f79aa8ace0d084a74bc61a466a40dac4a915b686/src/app/ui/common/menuItem.decorator.js#L47)):*
const?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483)*

**Comment by ec-dev** [comment]
Reviewed 4 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483)*

**Comment by AleksueiR** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/menuItem.decorator.js, line 12 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483#-KFKjxqnQA0e3l3gJHor:-KFKvM7fBKJynvyj7tgV:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f79aa8ace0d084a74bc61a466a40dac4a915b686/src/app/ui/common/menuItem.decorator.js#L12)):*
Done.

---

*[src/app/ui/common/menuItem.decorator.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483#-KFKjc-R31nv70NdPkwX:-KFKvLL_bHreQUjthz3o:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f79aa8ace0d084a74bc61a466a40dac4a915b686/src/app/ui/common/menuItem.decorator.js#L47)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483)*

**Comment by ec-dev** [comment]
Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/483)*

**Pull request merged**
