### PR TITLE
WMS GetFeatureInfo Integration

### PR DESCRIPTION
**Pull request by alyec**
This PR doesn't completely address #283 or #271 but it does give people a chance to start complaining if they don't like the way it is written.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/503)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 220 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503#-KFesK5pKfbKffFQVmDJ:-KFesK5pKfbKffFQVmDK:1471880920) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc3799173837b1a24ecbb48c8e855aae8b04bc39/src/app/geo/identify.service.js#L220)):*
Comments are for WMS, function is for Feature Layer (cut n paste glory)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503)*

**Comment by alyec** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 220 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503#-KFesK5pKfbKffFQVmDJ:-KFetVVfIxtWBbUrIvhc:-69264550) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fc3799173837b1a24ecbb48c8e855aae8b04bc39/src/app/geo/identify.service.js#L220)):*
Fixed, but there may be more lurking around.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 335 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503#-KFeukfPA0hdx6ff0wEq:-KFeukfPA0hdx6ff0wEr:2003787166) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fa4ea567f46dd948c6ccbf6eb9513f3139648aa0/src/app/geo/identify.service.js#L335)):*
typo: dynmaic (repeated again below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503)*

**Comment by alyec** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 335 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503#-KFeukfPA0hdx6ff0wEq:-KFewb7vuPSXEys7kP2U:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fa4ea567f46dd948c6ccbf6eb9513f3139648aa0/src/app/geo/identify.service.js#L335)):*
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/503)*

**Pull request merged**
