### PR TITLE
Language switching

### PR DESCRIPTION
**Pull request by spencerwahl**
Temporary buttons, will be replaced asap with a proper implementation along with multiple config support.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/306)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/core/config.service.js, line 130 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306#-KA61e5LOXO7lE9xADii:-KA61e5LOXO7lE9xADij:269175605) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6308d49ea238a80f0d25e42f9bb0a3d2167cdd0d/src/app/core/config.service.js#L130)):*
I think this check is superfluous; just set the promise to undefined.

---

*[src/app/geo/geo.service.js, line 268 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306#-KA62TXmqmgDP_vt9_Lp:-KA62TXnZc2S6UbPMJwK:1323275074) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6308d49ea238a80f0d25e42f9bb0a3d2167cdd0d/src/app/geo/geo.service.js#L268)):*
Does `destroy` remove DOM listeners? Do we have any set up anyway?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by alyec** [comment]
*[src/app/geo/geo.service.js, line 268 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306#-KA62TXmqmgDP_vt9_Lp:-KA6E9Cr0mZ8Nf6gND9i:-2146315494) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6308d49ea238a80f0d25e42f9bb0a3d2167cdd0d/src/app/geo/geo.service.js#L268)):*
I don't think we setup any DOM listeners directly.  ESRI JSAPI might and I would hope those get removed by map.destroy .

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by spencerwahl** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 130 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306#-KA61e5LOXO7lE9xADii:-KA6F7-gJQkbAafU6mKT:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6308d49ea238a80f0d25e42f9bb0a3d2167cdd0d/src/app/core/config.service.js#L130)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 268 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306#-KA62TXmqmgDP_vt9_Lp:-KA6Fq_SQnuJBIVkrT52:-1839239243) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6308d49ea238a80f0d25e42f9bb0a3d2167cdd0d/src/app/geo/geo.service.js#L268)):*
@spencerwahl, can you add a note here about residual dom listeners potentially remaining after the node is destroyed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by spencerwahl** [comment]
*[src/app/geo/geo.service.js, line 268 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306#-KA62TXmqmgDP_vt9_Lp:-KA6J88AR_0izLZix2vx:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6308d49ea238a80f0d25e42f9bb0a3d2167cdd0d/src/app/geo/geo.service.js#L268)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by cynngah** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Comment by james-rae** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/306)*

**Pull request merged**
