### PR TITLE
Restore details panel open from datatable

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Details panel can be opened from the datatable. 

## Testing
Nope.

## Documentation
No changes.

## Checklist

- ~~[ ] commits messages follow the guidelines~~ geo4 will be squashed
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ no functionality changes
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1883)

### CODE REVIEW

**Comment by alyec** [comment]
General note: several places have TODO for the refactor.  I think these should be FIXME for any functionality that worked in `develop` before the refactor but has been disabled.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 527 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883#-KkBcu6Rr73SHoJylJ2J:-KkBcu6S0DsaKtefQTEu:bcadxkx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ba1a17de20c7212018edbfb03f47f4f0855c9326/src/app/ui/filters/filters-default.directive.js#L527)):*
> ```JavaScript
>                                 symbology: {
>                                     stack: [{ svgcode: data.rvSymbol }],
>                                     isInteractire: false,
> ```

typo isInteractive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883#-:-KkBc3lweqa7kI1zSeAw:b-81kxfg)*

**Comment by AleksueiR** [comment]
Very good point. Done.

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 527 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883#-KkBcu6Rr73SHoJylJ2J:-KkBdhATKMasg0i7wS9w:b-js81vd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ba1a17de20c7212018edbfb03f47f4f0855c9326/src/app/ui/filters/filters-default.directive.js#L527)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo isInteractive
</blockquote></details>

Perfect eyesight!
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883#-:-KkBeFnu9SFnmBjb5UjU:b-z10uk8)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-header.html, line 5 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883#-KkGWiqQ3QVpDlzqMiXM:-KkGWiqQ3QVpDlzqMiXN:bts2dt4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/15fafaad40468078839a9bf7b77a5ec2e50e58f4/src/app/ui/details/details-header.html#L5)):*
> ```HTML
>     <div layout="column" class="rv-header-content">
>         <h4 class="md-subhead">{{ self.selectedItem.requester.layerProxy.name }}</h4>
>         
> ```

typo: caption (or just remove this altogether)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-header.html, line 5 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883#-KkGWiqQ3QVpDlzqMiXM:-KkGX4MvQ4A_AZsuHdaW:b-axn4yk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/15fafaad40468078839a9bf7b77a5ec2e50e58f4/src/app/ui/details/details-header.html#L5)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: caption (or just remove this altogether)
</blockquote></details>

Will remove in the next PR, if that's okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1883)*

**Pull request merged**
