### PR TITLE
optimize(bundle): reduce bundle size

### PR DESCRIPTION
**Pull request by milesap**
## Description

1. Removes `gsap` animation library as an npm dependency and instead injects the minified code into the bundle manually. This removes `TweenMax` from being loaded. `gsap` advises proper ES6 module loading will arrive with v2+.

2. `rxjs` incorrectly bundles all operators when importing any operator as ` import { map } from 'rxjs/operators`.  Corrected how operators are loaded.

Current production size: ~ 2852 kB
New production size: ~ 2671 kB
Reduction: ~ 181 kB

## Testing
👀 

## Documentation
inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2715)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2715#-:-LCYYha01ri5cJM1pOW_:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2715)*

**Comment by milesap** [comment]
`moment-timezone` contains worldwide data that has been trimmed to Canada/US regions. Also pulled in `moment` library. 

Final prod size 2,432kB from 3,139 kB @ v2.3.0 :trophy:  

No more optimizing 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2715#-:-LCZ0JCD7Trjkf57th_z:b-qhv9m0)*

**Comment by JahidAhmed** [comment]
Reviewed 12 of 14 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2715)*

**Pull request merged**
