### PR TITLE
API map class observables

### PR DESCRIPTION
**Pull request by milesap**
## Description
This PR implements all current map instance observables:
- click
- doubleClick
- zoomChanged
- centerChanged
- mouseMove
- mouseUp
- mouseDown

Pay close attention to `config.class.js` and how `setZoom` and  `centerAt` map instance functions are wrapped to support being observable. 

## Testing
Using `index-samples.html` in dev tools type:

```js
RZ.mapInstances[0].click.subscribe(console.log);
```

You can replace the `click` part with any of the above mentioned observables. Only `centerChanged` is partially working (currently not working when panning with mouse).

## Documentation
http://fgpv-vpgf.github.io/fgpv-vpgf/api-map-class-observables/api/classes/_map_.map.html

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2450)

### CODE REVIEW

**Comment by milesap** [comment]
[Documentation on map](http://fgpv-vpgf.github.io/fgpv-vpgf/api-map-class-observables/api/classes/_map_.map.html)

**Comment by AleksueiR** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[api/src/map.ts, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmFm31uiDUjGodjmrw:-KxmFm31uiDUjGodjmrx:b-326gzq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L54)):*
> ```XML
> 
>     /**
>      * Emits whenever a user lifts a previous down left click.
> ```

Duplicated description

---

*[api/src/map.ts, line 57 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmFnnMQEd9lx-CdOUp:-KxmFnnMQEd9lx-CdOUq:b-jhyjcl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L57)):*
> ```XML
>      * @event zoomChanged
>     */
>     zoomChanged: Observable<number>;
> ```

There are zoom-start and zoom-end events. Do we want to pass them through as well?
What about pan-start and pan-end?

---

*[api/src/map.ts, line 83 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmEf6D8q-H2mXKmORP:-KxmEf6D8q-H2mXKmORQ:bpx565q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L83)):*
> ```XML
> 
>     return clickStream
>         .buffer(clickStream.debounceTime(250))
> ```

Is this related to a double click? I thought a double click had its own event. Is there another way we can detect a double click except for buffering click events? 

---

*[api/src/map.ts, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmEARiXDbHDDPN3NJA:-KxmEARiXDbHDDPN3NJB:b-3hvd2c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L89)):*
> ```XML
> 
> function initObservables(this: Map) {
>     const esriMapElement = this.mapDiv.find('.rv-esri-map')[0];
> ```

What happens when we destroy the map to switch projection or reload the config?  A new API Map instance needs to be created and somehow passed to the API user.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Comment by milesap** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[api/src/map.ts, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmFm31uiDUjGodjmrw:-KxmaxaF53eN3EF6q0so:b-886gsx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L54)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Duplicated description
</blockquote></details>

Fixed

---

*[api/src/map.ts, line 57 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmFnnMQEd9lx-CdOUp:-KxmltWRbxr3Un5iqNL_:b-e2s85y) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L57)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

There are zoom-start and zoom-end events. Do we want to pass them through as well?
What about pan-start and pan-end?
</blockquote></details>

To this I'll say Maybe™ - though certainly something we can add down the road if the need arises and how much time I have to get this thing out.

---

*[api/src/map.ts, line 83 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmEf6D8q-H2mXKmORP:-KxmcWmT5luGg_PuhlJO:b-v9qqz2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L83)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Is this related to a double click? I thought a double click had its own event. Is there another way we can detect a double click except for buffering click events? 
</blockquote></details>

Yeah there is a built in event, made the switch. Only downside is no future support for:
3 triple
4 quadruple
5 quintuple pentadruple
6 sextuple hexatruple
7 septuple
8 octuple
9 nonuple
10 decuple
11 undecuple hendecuple
12 duodecuple
13 tredecuple or
100 centuple clicks

---

*[api/src/map.ts, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmEARiXDbHDDPN3NJA:-Kxmj2oq719FnQymlx8f:b-tlb5h0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L89)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

What happens when we destroy the map to switch projection or reload the config?  A new API Map instance needs to be created and somehow passed to the API user.
</blockquote></details>

An API map instance is "loosely bound" to the DOM element that contains the map. I tested subscribing to double clicks on `index-samples.html` (after patching it to work) and the double click events continued to fire when the map reloaded.

In general I'd like to avoid issuing new map instances and instead modify the existing instance. Plus reloading configs/projections will emit data which extension authors can use (layers removed/added, center changed etc.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[api/src/map.ts, line 57 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmFnnMQEd9lx-CdOUp:-Kxmz1Le1e9nSAx1Rmsg:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L57)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

To this I'll say Maybe™ - though certainly something we can add down the road if the need arises and how much time I have to get this thing out.
</blockquote></details>

:+1: 

---

*[api/src/map.ts, line 83 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmEf6D8q-H2mXKmORP:-Kxmz3aa-ML0GuVkmONw:bt1b0ok) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L83)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Yeah there is a built in event, made the switch. Only downside is no future support for:
3 triple
4 quadruple
5 quintuple pentadruple
6 sextuple hexatruple
7 septuple
8 octuple
9 nonuple
10 decuple
11 undecuple hendecuple
12 duodecuple
13 tredecuple or
100 centuple clicks
</blockquote></details>

Nooooo! My octuple click!

---

*[api/src/map.ts, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxmEARiXDbHDDPN3NJA:-Kxmz8393p--jNjxScvZ:bnqp1rp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8f50b4481812d550550e1fe4f778f4117fb3778/api/src/map.ts#L89)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

An API map instance is "loosely bound" to the DOM element that contains the map. I tested subscribing to double clicks on `index-samples.html` (after patching it to work) and the double click events continued to fire when the map reloaded.

In general I'd like to avoid issuing new map instances and instead modify the existing instance. Plus reloading configs/projections will emit data which extension authors can use (layers removed/added, center changed etc.)
</blockquote></details>

Nice, as long as it works :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Comment by james-rae** [comment]
Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[api/src/map.ts, line 65 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxnP3rlpwRjkcZBwRrv:-KxnP3rlpwRjkcZBwRrw:b-33twn9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5cdb27fcc7e493c0ea98d0cd98ae7eaaa3292c41/api/src/map.ts#L65)):*
> ```XML
>      * @event centerChanged
>     */
>     centerChanged: Observable<MouseEvent>;
> ```

`extentChanged` might be better. otherwise we'd have to store and track previous center points. ESRI map emits extent-change events, so easy to link.  That said, a zoom is also an extent change, meaning zooming in would trigger this and `zoomChanged`, which may be a problem in your grand scheme of things (not sure, you'll know best).

---

*[api/src/map.ts, line 69 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxnPkVJaUR3HUib_rFo:-KxnPkVJaUR3HUib_rFp:b-fby5my) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5cdb27fcc7e493c0ea98d0cd98ae7eaaa3292c41/api/src/map.ts#L69)):*
> ```XML
>     /**
>      * Creates a new map inside of the given HTML container, which is typically a DIV element. If opts is a string then it is considered to be
>      * a url to a json config snippet of a map.
> ```

I'm assuming opts is supposed to align to our config schema for the `map` section? Can we state this?

---

*[api/src/event/MouseEvent.ts, line 8 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxnX9hy14cvnjK9vQmt:-KxnX9i-PzCJzgUmq6ha:b-jew74q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5cdb27fcc7e493c0ea98d0cd98ae7eaaa3292c41/api/src/event/MouseEvent.ts#L8)):*
> ```XML
>     xy: XY | null;
>     /** The number of pixels from the top of the viewport. */
>     pageY: number;
> ```

pedantic: `screen` instead of `page`? Don't change if you like page, no biggie.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Comment by milesap** [comment]
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[api/src/map.ts, line 65 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxnP3rlpwRjkcZBwRrv:-KxrNRk97DOPM1Ciirt5:bqwjt4o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5cdb27fcc7e493c0ea98d0cd98ae7eaaa3292c41/api/src/map.ts#L65)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`extentChanged` might be better. otherwise we'd have to store and track previous center points. ESRI map emits extent-change events, so easy to link.  That said, a zoom is also an extent change, meaning zooming in would trigger this and `zoomChanged`, which may be a problem in your grand scheme of things (not sure, you'll know best).
</blockquote></details>

Yeah I think I'll leave this as `centerChanged`, internally I'll track it by the ESRI emits (zooms shouldn't change the center anyways). This PR omits another one down the pipe called `boundsChanged` which is tied to the extent changing based on viewport sizing changes.

---

*[api/src/map.ts, line 69 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxnPkVJaUR3HUib_rFo:-KxraJ-7n1waG1v7G0UA:b-vl7ghi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5cdb27fcc7e493c0ea98d0cd98ae7eaaa3292c41/api/src/map.ts#L69)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I'm assuming opts is supposed to align to our config schema for the `map` section? Can we state this?
</blockquote></details>

:+1: good idea. Removed the string option

---

*[api/src/event/MouseEvent.ts, line 8 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450#-KxnX9hy14cvnjK9vQmt:-Kxrar1mAUgZhlTLXUiH:b1at3bb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5cdb27fcc7e493c0ea98d0cd98ae7eaaa3292c41/api/src/event/MouseEvent.ts#L8)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

pedantic: `screen` instead of `page`? Don't change if you like page, no biggie.
</blockquote></details>

I like screen, changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2450)*

**Pull request merged**
