### PR TITLE
Dynamic layer zoom and symbology

### PR DESCRIPTION
**Pull request by cynngah**
#635

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/720)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 77 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720#-KJf4iY4FvYfvcOR9Lp5:-KJf4iY4FvYfvcOR9Lp6:-2054169961) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c3ab1926073c61f99a8a57462b51b00284bb473d/src/app/ui/filters/filters-default.directive.js#L77)):*
> ```JavaScript
>                 // add icons and zoom to button only to the feature layers
>                 if ((requester.legendEntry.layerType === 'esriFeature' && requester.legendEntry.url) ||
>                     requester.legendEntry.layerType === 'esriDynamicLayerEntry') {
> ```

If this `if` still necessary? Only feature and dynamic layers have attribute tables anyway.

---

*[src/app/ui/filters/filters-default.directive.js, line 165 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720#-KJf4H7q7NsqTnZovTkf:-KJf4H7q7NsqTnZovTkg:2038197468) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c3ab1926073c61f99a8a57462b51b00284bb473d/src/app/ui/filters/filters-default.directive.js#L165)):*
> ```JavaScript
>                     const tr = $(event.target).closest('tr');
>                     const layerName = $(event.target).closest('.rv-content-pane')
>                         .find('.md-title').html().substring(10);
> ```

What's 10? You can probably use `requester.name` if you need the layer name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720)*

**Comment by cynngah** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 77 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720#-KJf4iY4FvYfvcOR9Lp5:-KJfCd9GHt27k58P8C2R:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c3ab1926073c61f99a8a57462b51b00284bb473d/src/app/ui/filters/filters-default.directive.js#L77)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> If this `if` still necessary? Only feature and dynamic layers have attribute tables anyway.
</details>
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 165 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720#-KJf4H7q7NsqTnZovTkf:-KJfCdklPJlGjrAKPpfx:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c3ab1926073c61f99a8a57462b51b00284bb473d/src/app/ui/filters/filters-default.directive.js#L165)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> What's 10? You can probably use `requester.name` if you need the layer name.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/720)*

**Pull request merged**
