### PR TITLE
Show the tooltips for hidden legends

### LINKED ISSUE #2322: Tooltips not triggering/shown when a legend entry has property "hidden"

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes #2322 

As title.
## Testing

Manually, try sample 42 in `index-samples.html`
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2326)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 798 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326#-KrWq2xAs_RRkuXa-2_1:-KrWq2xAs_RRkuXa-2_2:bldziou) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3b2ef664db54863353d70fbaaff1081f7ddebcfa/src/app/geo/legend.service.js#L798)):*
> ```JavaScript
>             if (blockConfig.hidden) {
>                 blueprint.config.hovertipEnabled = false;
>                 blueprint.config.state.query = false;
> ```

Keep the query disalbed for hidden layer for now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326)*

**Comment by barryytm** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 798 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326#-KrWq2xAs_RRkuXa-2_1:-KrWt-ONQMQAt3Bl8Qyk:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3b2ef664db54863353d70fbaaff1081f7ddebcfa/src/app/geo/legend.service.js#L798)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Keep the query disalbed for hidden layer for now. 
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326)*

**Comment by AleksueiR** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/config-test.json, line 1 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326#-KrWtR-3ytMrtOXxeR6b:-KrWtR-3ytMrtOXxeR6c:b-ofjiso) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6d79b0597489a1480659fada75a5f7ce52b413cf/src/content/samples/config-test.json#L1)):*
> ```JSON
> {
> ```

What are these extra files?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326)*

**Comment by barryytm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/config-test.json, line 1 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326#-KrWtR-3ytMrtOXxeR6b:-KrWuZ_NEWxo-WuDBLhz:b-jtzo6o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6d79b0597489a1480659fada75a5f7ce52b413cf/src/content/samples/config-test.json#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

What are these extra files?
</blockquote></details>

They were committed by mistakes.  I'd just taken them off.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326)*

**Comment by milesap** [comment]
Reviewed 1 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2326)*

**Pull request merged**
