### PR TITLE
Api 06 - SimpleLayer, BaseGeometry, Point

### LINKED ISSUE #2588: API feature: SimpleLayer, BaseGeometry, Point
### SimpleLayer extends existing `BaseLayer` with the following special observables and methods:
- `geometry_added`
- `geometry_removed`
- `setGeometry`
- `removeGeometry`

### BaseGeometry
http://fgpv-vpgf.github.io/fgpv-vpgf/api/classes/_index_d_.rv.geometry.basegeometry.html

### Point 
http://fgpv-vpgf.github.io/fgpv-vpgf/api/classes/_index_d_.rv.geometry.point.html

The `icon` property can be improved to include in-line svg/images along with urls.

### To be discussed (BaseLayer update) optional
- We'll want to be able to observe both `ConfigLayer` features and `SimpleLayer` geometry clicks, mouseover, and mouseout events. This can be a separate PR, let me know if you foresee any issues with this as you complete this issue.

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2588 
Adds functionality to add `SimpleLayers` and custom points on the map

Also fixes a couple small related bugs:
- Datatable updating content on reload if it was previously open
- Refresh interval not appearing for incorrect layers in settings panel

To be completed in another PR (added TODOs):
- `enhancements to `icon` property to allow for non-urls
- observing features / geometry clicks, and mouse events

## Testing
```js
SETUP
    // add layer to map
    RZ.mapById('mobile-map').layers.addLayer('simpleLayer');

    // set the config layer to a constant for ease of use
    const simpleLayer = RZ.mapById('mobile-map').layers.getLayersById('simpleLayer')[0];

ADD GEOMETRY
    // subscribe to geometry added
    simpleLayer.geometryAdded.subscribe(l => console.log('Geometry added'));

    // create different types of API points
    const pointA = new RZ.GEO.Point(0, 'https://image.flaticon.com/icons/svg/17/17799.svg', [-79, 43]);
    const pointB = new RZ.GEO.Point(1, '', [-79, 32]);

    // add points to layer using the different available options
    simpleLayer.addGeometry(pointA);

    // pointA was already added, will be ignored this time and only pointB will be added
    simpleLayer.addGeometry([ pointA, pointB ]);

    // expect 'Geometry added' to appear in the console after every time a point was added

REMOVE GEOMETRY
    // subscribe to geometry removed
    simpleLayer.geometryRemoved.subscribe(l => console.log('Geometry removed'));

    // remove single geometry instance
    simpleLayer.removeGeometry('0');

    // expect 'Geometry removed' to appear in the console

...
```

## Documentation
https://jahidahmed.github.io/docs/api/developer/index.html

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2591)

### CODE REVIEW

**Comment by milesap** [comment]
Reviewed 42 of 47 files at r1.
Review status: 42 of 47 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591)*

**Comment by milesap** [comment]
Thoughts/ideas, feel free to object or share alternate ideas (or push to a subsequent PR):

1. Would we want one `simpleLayer` to be created automatically for each map instance for quicker/easier access to adding geometry on the map? Like a `mapInstance.simpleLayer` is a getter which creates the layer on its first invocation.

2. Add a `description` to `Point` which is used as the text for hovertip.

3. Show the point in the `toc` when a user clicks on the map (Under the `simpleLayer` name).

Let me know what you think, otherwise everything else looks good. Minor changes in comments.

---

Reviewed 5 of 47 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[api/src/geometry.ts, line 197 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-L75JgoW8MiSHUFlujnN:-L75JgoW8MiSHUFlujnO:b65q6yd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75a40ad83d9421940ceeeaf1601538a352da463/api/src/geometry.ts#L197)):*
> ```XML
> 
>     /**
>      * Returns the type of the geometry object. Possibilities are 'Point', 'MultiPoint', 'LineString', or 'MultiLineString'.
> ```

Remove or todo `'MultiPoint', 'LineString', or 'MultiLineString'`

---

*[api/src/layers.ts, line 755 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-L75avWCovgWvejlDLHu:-L75avWCovgWvejlDLHv:bn7zl57) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75a40ad83d9421940ceeeaf1601538a352da463/api/src/layers.ts#L755)):*
> ```XML
> 
>     /** Providing a layer json snippet creates a `ConfigLayer`.*/
>     addLayer(layerJSONOrName: JSON | string): void {       // change return type after if we want to return something  ?
> ```

I think a return type of  `layer[]` would be nice here instead of `void` so users don't need to lookup/search the layer they created. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-:-L75ccXd1SItJo4WNR9-:b-lhs87z)*

**Comment by james-rae** [comment]
Miles; all good suggestions. Think they need a longer conversation instead of amendments to this PR.  I could type paragraphs here lol.

---

Reviewed 11 of 47 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[api/src/layers.ts, line 734 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2591#-L75SfGeAXNoB_TWF_4x:-L75SfGeAXNoB_TWF_4y:b-pav8vh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75a40ad83d9421940ceeeaf1601538a352da463/api/src/layers.ts#L734)):*
> ```XML
> 
>     /** Providing a layer json snippet returns a `ConfigLayer`.*/
>     addLayer(layerJSON: JSON): void;    // change return type after if we want to return something  ?
> ```

if its available, you probably want to return the ConfigLayer / SimpleLayer object that was created. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2591#-:-L75n5EODE9rTRlLS2KX:b-l0sjw6)*

**Comment by milesap** [comment]
Agreed - things to keep in mind for sure. Maybe I'll schedule a meeting for Monday or Tuesday to review next steps and to save our fingers from typing.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-:-L75nRU_aTWfFJ_IQkhL:bbsmzsf)*

**Comment by JahidAhmed** [comment]
Made changes where applicable for comments below and left these discussion points till after the meeting Monday

---

Review status: 8 of 46 files reviewed at latest revision, 3 unresolved discussions.

---

*[api/src/geometry.ts, line 197 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-L75JgoW8MiSHUFlujnN:-L79rnwxZfQ9XHubvGtN:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75a40ad83d9421940ceeeaf1601538a352da463/api/src/geometry.ts#L197)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Remove or todo `'MultiPoint', 'LineString', or 'MultiLineString'`
</blockquote></details>

done thanks

---

*[api/src/layers.ts, line 734 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-L75SfGeAXNoB_TWF_4x:-L79rqfPaJFqIJhnk4v_:b-wm79uc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75a40ad83d9421940ceeeaf1601538a352da463/api/src/layers.ts#L734)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

if its available, you probably want to return the ConfigLayer / SimpleLayer object that was created. 
</blockquote></details>

we would be able to return for `SimpleLayers` but for `ConfigLayers` since it happens asynch (we wait for the layerRecord to load) i don't think it would work

---

*[api/src/layers.ts, line 755 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-L75avWCovgWvejlDLHu:-L79rzp12hQ-MNRWhmwe:b-wm79uc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75a40ad83d9421940ceeeaf1601538a352da463/api/src/layers.ts#L755)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I think a return type of  `layer[]` would be nice here instead of `void` so users don't need to lookup/search the layer they created. 
</blockquote></details>

we would be able to return for `SimpleLayers` but for `ConfigLayers` since it happens asynch (we wait for the layerRecord to load) i don't think it would work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-:-L79s2cjgE9ChdbuEnKF:b-ufc6qo)*

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 38 of 39 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591#-:-L7Au0NJKslnY5vqMOEC:bg7igkv)*

**Comment by james-rae** [comment]
Reviewed 38 of 39 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2591)*

**Pull request merged**
