### PR TITLE
feat(test): add initial protractor test support

### PR DESCRIPTION
**Pull request by milesap**
## Description
Runs basic side panel test in chrome. Runs selenium server and webpack dev server concurrently for tests.

Will expand this to include IE and FF concurrent testing, as well as review chromes new headless state.

## Testing
No

## Documentation
No

## Checklist

- [x] commits messages follow the guidelines
- [x] ~~code passes unit tests~~
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1963)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 6 of 8 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/protractor/run.js, line 25 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmWYb9S-DLJyDl8I5_v:-KmWYb9TCLBDqE6sLQ5Q:bozfx8h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53ad6799dd49218b951bb4ba1d0cbbd14058de21/scripts/protractor/run.js#L25)):*
> ```JavaScript
>     }
> 
>     kill () {
> ```

Don't these scripts kill whatever is listening on the port (not necessarily the processes that were started by us)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by milesap** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/protractor/run.js, line 25 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmWYb9S-DLJyDl8I5_v:-KmWb42bG1L6hQ9wq9rq:b2lvb8o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53ad6799dd49218b951bb4ba1d0cbbd14058de21/scripts/protractor/run.js#L25)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Don't these scripts kill whatever is listening on the port (not necessarily the processes that were started by us)?
</blockquote></details>

Correct, this is needed to kill rogue child processes we start or child processes of processes we start but can't gracefully close.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/protractor/run.js, line 89 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmWzeVL96EtrazAzmhs:-KmWzeVMbUt16fuYjUdc:b-bon6ia) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/604949478e8964ac609f43c773c249c2860e420c/scripts/protractor/run.js#L89)):*
> ```JavaScript
>         });
>     });
> }).catch(cp => 1);
> ```

Wouldn't a failed update be worth logging?  Same for the other silent failures in the script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by milesap** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/protractor/run.js, line 89 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmWzeVL96EtrazAzmhs:-KmXCcRb9PuTPbvEIEur:buhjmhp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/604949478e8964ac609f43c773c249c2860e420c/scripts/protractor/run.js#L89)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Wouldn't a failed update be worth logging?  Same for the other silent failures in the script.
</blockquote></details>

I've added a log msg if selenium server updates fail. We can't log everything as some always fail when the processes are shut down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 8 files at r1, 1 of 3 files at r2, 3 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 39 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmbK-05uLtpqOwaxKyr:-KmbK-06s-EjNUG99xXj:bixe6c1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce9ba654c03f294b0ecfca5c329b832c94fb49b6/.travis.yml#L39)):*
> ```YAML
>   apt:
>     sources:
>     - ubuntu-toolchain-r-test
> ```

Was this needed for gulp?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 39 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmbK-05uLtpqOwaxKyr:-KmfMTxo9ZtnT5Jqtjyg:b-rfpakf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce9ba654c03f294b0ecfca5c329b832c94fb49b6/.travis.yml#L39)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Was this needed for gulp?
</blockquote></details>

Not sure, though it has the word `secure` so I figured it was important and should stay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 39 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmbK-05uLtpqOwaxKyr:-Kmgu_s6eku_58RqoSqc:b3kxoxu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce9ba654c03f294b0ecfca5c329b832c94fb49b6/.travis.yml#L39)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Not sure, though it has the word `secure` so I figured it was important and should stay.
</blockquote></details>

Oh, no, I was asking about `- ubuntu-toolchain-r-test`.
Secure stuff above are our ssh keys to allow demo deployment to cloud app.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[.travis.yml, line 39 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmbK-05uLtpqOwaxKyr:-KmkTAWkGcHpgBP62tqW:b-oz0doj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce9ba654c03f294b0ecfca5c329b832c94fb49b6/.travis.yml#L39)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Oh, no, I was asking about `- ubuntu-toolchain-r-test`.
Secure stuff above are our ssh keys to allow demo deployment to cloud app.
</blockquote></details>

ah lol `ubuntu-toolchain-r-test` is now gone

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 39 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KmbK-05uLtpqOwaxKyr:-Kn-eftoP_vg5LMDxKb2:b-qn5lay) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce9ba654c03f294b0ecfca5c329b832c94fb49b6/.travis.yml#L39)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

ah lol `ubuntu-toolchain-r-test` is now gone
</blockquote></details>

Perfect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Comment by milesap** [comment]
throwing an error:
> { Error: Command failed: node_modules/.bin/webpack-dev-server 
/home/travis/build/fgpv-vpgf/fgpv-vpgf/webpack.common.js:73
            new webpack.optimize.ModuleConcatenationPlugin(),
            ^
TypeError: webpack.optimize.ModuleConcatenationPlugin is not a constructor

watching https://stackoverflow.com/questions/44692289/webpack-optimize-moduleconcatenationplugin-is-not-a-constructor

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-:-KnF4XUyEsN5uaHIKCmU:b-kug21l)*

**Comment by milesap** [comment]
It's good to merge :+1: 

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-:-KnZjgm8ArwlEPtRAcC8:b-athbzc)*

**Comment by AleksueiR** [comment]
Tried running inside a Vagrant VM, but got only to:
> Selenium Server update completed.
Starting Selenium Server.
Starting Webpack Dev Server.
Selenium Server started on port 4444
Webpack Dev Server started on port 6001
Protractor tests are starting.
[11:23:51] I/launcher - Running 1 instances of WebDriver
[11:23:51] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[11:24:52] E/launcher - unknown error: Chrome failed to start: exited abnormally

It needs something else :(

This is good to merge since it's working on Travis. :lgtm: 

---

Reviewed 3 of 4 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 12 at r9](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KniPVdZbZwh3clFv-xy:-KniPVdZbZwh3clFv-xz:b-btgxo2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6d8b97e52f87d6d6c0d04c63f80b60769974d415/.travis.yml#L12)):*
> ```YAML
> before_install:
>   - export CHROME_BIN=/usr/bin/google-chrome
>   - "export DISPLAY=:99.0"
> ```

Why do we need quotes here and on the next line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-:-KniS0O4CgHHGHlbtH3F:bsxemol)*

**Comment by milesap** [comment]
:-1: for vagrant

---

Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 12 at r9](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-KniPVdZbZwh3clFv-xy:-KniU_uzPYT_MFHtv03u:b2hwp9o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6d8b97e52f87d6d6c0d04c63f80b60769974d415/.travis.yml#L12)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Why do we need quotes here and on the next line?
</blockquote></details>

Removed the quotes - let's see if Travis stays happy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-:-KniUidc6K5b6eTzvfOX:b-3fv0xx)*

**Comment by AleksueiR** [comment]
`xvfb` seems to be the culprit; do Travis VMs come with it pre-installed?

---

Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-:-KniV1X-rBhCIK5vDafd:b-8h5kc5)*

**Comment by milesap** [comment]
yes

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-:-KniVK-L9XUXh9btXZk_:b2nign6)*

**Comment by milesap** [comment]
Travis is very user-friendly, it only needs three servers running concurrently on the same host...
- virtual framebuffer server
- selenium java server
- local dev server

what can go wrong?

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963#-:-KniVwpz2zWVhwqPVlW8:b8m9tfq)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1963)*

**Pull request merged**
