### PR TITLE
Update doc deployment for GitHub Actions

### LINKED ISSUE #3786: API JsDoc Site is not up to date
Appears the API docs generated from JsDocs are not getting updated on pushes to `master`

e.g. [ConfigLayer page](http://fgpv-vpgf.github.io/fgpv-vpgf/ghpages-docs/developer/api_tech_docs/classes/_api_src_layers_.configlayer.html) does not have `setFilterSql` function anywhere on it.

### PR DESCRIPTION
**Pull request by milespetrov**
- Creates a GH action workflow `docs.yml`
- Updates some internal doc links in `README.md` to point to `master` instead of `v3.2.0`. Ideally when tagging a release you update those links manually to point to the tag.
- Removes/ignores private variables and methods in the API generated docs.
- Updates some dependencies like `jsdoc` and `typedoc` to fix issues likely introduced with our node version bump.
- Updates/adds other dependencies like `@types/jquery` and `@types/sizzle` and ignores `startup.js` to fix typescript issues with `typedoc` updating the TS version it uses internally.
- Cleaned up our [docs folder](http://fgpv-vpgf.github.io/fgpv-vpgf/) by moving most doc versions into the `backups` folder.

[Demo docs folder](http://milespetrov.github.io/fgpv-vpgf/)
[Demo of new docs](http://milespetrov.github.io/fgpv-vpgf/v0.0.6/#/) (Double check everything looks up-to-date)

Closes #3786 and #3660

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943)

### CODE REVIEW

**Review by spencerwahl — COMMENTED** [review]
Should the pnpm lock be completely changed, it looks like a new version or something?

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943#-:-McQb92292oC9iTSnIzR:b-nhbv0x)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @milespetrov)

**Review by james-rae — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943)* status: all files reviewed, 1 unresolved discussion (waiting on @milespetrov)

___
*[packages/ramp-core/README.md, line 11 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943#-McU6Pjx3wQxNQ7XESAU:-McU6Pjx3wQxNQ7XESAV:bo5z82c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05532c21bbbe976c59e45c34244171692b070201/packages/ramp-core/README.md#L11)):*
> ```Markdown
> 
> The Reusable Accessible Mapping Platform (RAMP), also known as the Federal Geospatial Platform Visualiser (FGPV), is a Javascript based web mapping platform that provides a reusable, WCAG 2.0 AA compliant common viewer platform for the Government of Canada.
> ```

This file is half duplicate of the readme sitting in repo-root, and half out of date. Might be better to just delete it?

**Review by yileifeng — COMMENTED** [review]
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943)* status: all files reviewed, 2 unresolved discussions (waiting on @milespetrov)

___
*[packages/ramp-core/docs/index.html, line 156 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943#-McUC0ff5kg6vnaizVNO:-McUC0ff5kg6vnaizVNP:b-puuhp7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05532c21bbbe976c59e45c34244171692b070201/packages/ramp-core/docs/index.html#L156)):*
> ```HTML
>                                 {
>                                     title: 'Geosearch',
>                                     path: 'https://geosearch-docs.fgpv-vpgf.com/v2.0.3/#/',
> ```

Can this dead link be removed?

**Review by milespetrov — COMMENTED** [review]
The entire file was replaced after I ran `rush update`. It might be caused by a version bump of pnpm/rushjs and `rush update` being called for the first time after that update (since the lockfile has a different format).

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943#-:-McUUZgIEYng6Lx6SQ1z:bs1yt2c)* status: 21 of 25 files reviewed, 2 unresolved discussions (waiting on @james-rae, @spencerwahl, and @yileifeng)

___
*[packages/ramp-core/README.md, line 11 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943#-McU6Pjx3wQxNQ7XESAU:-McUWlQ78lZsTFmy6faJ:bhofej8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05532c21bbbe976c59e45c34244171692b070201/packages/ramp-core/README.md#L11)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

This file is half duplicate of the readme sitting in repo-root, and half out of date. Might be better to just delete it?
</blockquote></details>

Deleted
___
*[packages/ramp-core/docs/index.html, line 156 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943#-McUC0ff5kg6vnaizVNO:-McUWnPW1Cd7X2ciH2So:bhofej8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05532c21bbbe976c59e45c34244171692b070201/packages/ramp-core/docs/index.html#L156)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Can this dead link be removed?
</blockquote></details>

Deleted

**Review by spencerwahl — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943)* status: all files reviewed, 2 unresolved discussions (waiting on @james-rae and @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 21 of 25 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943)* status: all files reviewed, 2 unresolved discussions (waiting on @james-rae and @yileifeng)

**Review by yileifeng — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

**Review by james-rae — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3943)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @milespetrov)

**Pull request merged**
