### PR TITLE
Build Cleanup

### LINKED ISSUE #768: Define and Build Library for Viewer Release
- [x] figure out what we are building (as opposed to zipping up our whole repo) ideally include 1-2 minified JS files
- [x] inject XSLTs into the build
- [x] apply translations on an XSLT constant so both XSLTs do not need to be loaded
- [x] remove favicon from assetcopy
- ~~convert map-icon to SVG (find an appropriate SVG)~~ moving to a new task
- ~~apply prefix to iconsets~~
- [x] write a script to cache actively used SVG icons
- [x] load cached SVG icons using template cache
- [x] convert datatables images to data URLs
- [x] add datatables images to CSS
- [x] rename injector to bootstrap
- ~~add support in injector for arbitrarily named lib / css file to be loaded~~ moving to a new task
- [x] split build task to output separately to `build/examples` and `build/lib`
- [x] convert dist task to uglify `build/lib`
- [x] tar/zip should only use source from `build/lib`

### PR DESCRIPTION
**Pull request by alyec**
Closes #768 some tasks split off into #851

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/852)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 436 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/852#-KLr2s8c3Oc2IrAMpl2-:-KLr2X5eMGOxhcWxD1-0:494503474) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0d4cb0d733eced797ec8296b0e50a6789c8a76f1/gulpfile.js#L436)):*
> ```JavaScript
>     $.connect.server({
>         root: config.root,
>         livereload: false,
> ```

Why is livereload off?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/852)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 436 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/852#-KLr2s8c3Oc2IrAMpl2-:-KLr2ztFxbk6g-fUnRhR:-362309231) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0d4cb0d733eced797ec8296b0e50a6789c8a76f1/gulpfile.js#L436)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Why is livereload off?
</details>
debugging residue, will fix after I get workshop stuff done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/852)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/852)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/852#-:-KM9sdtt_A00Iutz0hbN:1417088721)*

**Comment by spencerwahl** [comment]
Reviewed 6 of 7 files at r1, 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/852)*

**Pull request merged**
