### PR TITLE
Put the help in the viewer

### PR DESCRIPTION
**Pull request by spencerwahl**
This prompted a talk about translation file loading, the part concerning this PR: the `$http.get` will be replaced by a `translation` constant.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/549)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/layout/shell.directive.js, line 90 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549#-KGlF7iuUaF-4LurTScI:-KGlF7iuUaF-4LurTScJ:44764170) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d648c5448eafbe205bb9a702cea26631ea02fe76/src/app/layout/shell.directive.js#L90)):*
Use `rootElement$` here as this will pick up all app instances.

---

*[src/app/layout/shell.directive.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549#-KGlF4N09V6vVGSLNlFk:-KGlF4N09V6vVGSLNlFl:2047998459) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d648c5448eafbe205bb9a702cea26631ea02fe76/src/app/layout/shell.directive.js#L106)):*
This probably needs to be moved to a separate file now.

---

*[src/app/layout/shell.directive.js, line 110 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549#-KGlE4ulyamsYazVP5Ck:-KGlE4ulyamsYazVP5Cl:-525032339) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d648c5448eafbe205bb9a702cea26631ea02fe76/src/app/layout/shell.directive.js#L110)):*
I guess we need new issues to have translations files embedded in the core.js and have help content react to language changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Comment by spencerwahl** [comment]
*[src/app/layout/shell.directive.js, line 110 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549#-KGlE4ulyamsYazVP5Ck:-KGlj8A576h4jHVWxbEF:-1157589380) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d648c5448eafbe205bb9a702cea26631ea02fe76/src/app/layout/shell.directive.js#L110)):*
I can have this use the current language, I didn't think it was necessary as all languages would have every section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Comment by spencerwahl** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/layout/shell.directive.js, line 90 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549#-KGlF7iuUaF-4LurTScI:-KGlr92ACgmfhILuFCxY:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d648c5448eafbe205bb9a702cea26631ea02fe76/src/app/layout/shell.directive.js#L90)):*
Done.

---

*[src/app/layout/shell.directive.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549#-KGlF4N09V6vVGSLNlFk:-KGlr9deLYMIkqkCZj_0:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d648c5448eafbe205bb9a702cea26631ea02fe76/src/app/layout/shell.directive.js#L106)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Comment by cynngah** [comment]
Reviewed 2 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/549)*

**Pull request merged**
