### PR TITLE
feat(plugin): Add bookmark plugin

### LINKED ISSUE #2709: Create a bookmark extension
Create a extension for bookmars. It can go inside the plugin section and open a list of bookmarks from a sliding panel.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2709

## Description

Add the area of interest plugin

## Testing

Chrome

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[schema.json, line 764 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725#-LDCMx-z-iUfdW-Faujd:-LDCMx000-2KGnnMQeEf:b-awcfx9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/79f37ae39acd3f919ded1aa456c79436903d8a44/schema.json#L764)):*
> ```JSON
>                          "properties": {
>                             "title": { "type": "string" },
>                             "xmin": { "type": "number" },
> ```

Can we add a `description` tag that indicates the extent co-ords must be in lat/long?  Probably fine if just one item has description, and refers to all the co-ords

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725)*

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/plugins/core/area-of-interest.js, line 76 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725#-LDCq7Ej19n-CNjyqiz2:-LDCq7Ej19n-CNjyqiz3:bldlkwm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/79f37ae39acd3f919ded1aa456c79436903d8a44/src/plugins/core/area-of-interest.js#L76)):*
> ```
> for (let zone of zoneList) {
> ```

I'm getting an error on `index-samples.html` (sample 1) `Uncaught (in promise) TypeError: r[Symbol.iterator] is not a function`

Try changing this to `for (let zone of zoneList || []) { ... ` or similar to avoid this (when plugin is registered without a config entry.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725#-:-LDCsym4CR7mbCTL6n3A:bg7igkv)*

**Comment by jolevesq** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[schema.json, line 764 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725#-LDCMx-z-iUfdW-Faujd:-LDDB4DNEcJfPRFiJX6h:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/79f37ae39acd3f919ded1aa456c79436903d8a44/schema.json#L764)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Can we add a `description` tag that indicates the extent co-ords must be in lat/long?  Probably fine if just one item has description, and refers to all the co-ords
</blockquote></details>

Done

---

*[src/plugins/core/area-of-interest.js, line 76 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725#-LDCq7Ej19n-CNjyqiz2:-LDDE40a34Q8jEMJfz51:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/79f37ae39acd3f919ded1aa456c79436903d8a44/src/plugins/core/area-of-interest.js#L76)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

> ```
> for (let zone of zoneList) {
> ```

I'm getting an error on `index-samples.html` (sample 1) `Uncaught (in promise) TypeError: r[Symbol.iterator] is not a function`

Try changing this to `for (let zone of zoneList || []) { ... ` or similar to avoid this (when plugin is registered without a config entry.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725)*

**Comment by milesap** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725#-:-LEEptxU-X-sto5qg1c-:bnfp4nl)*

**Pull request merged**
