### PR TITLE
feat(ui): Implement custom keyboard navigation

### LINKED ISSUE #808: Implement custom keyboard navigation support
Implement keyboard navigation support similar to [Google Maps](https://www.google.ca/maps). Keyboard support should activate only when the map is focused (see related issue #52).

#### Overview
- Up/Down/Left/Right arrow keydown pans map north/south/west/east respectively by some arbitrary distance.
- + key zooms in one level if possible
- - key zooms out one level if possible
- Enter key selects point information from map center

#### Additional Information 
Existing ArcGIS keyboard navigation support only works if the users mouse is hovering over the map. If the user does not have a mouse or is hovering over a panel/navbar then keyboard support does not work.

See #52

### PR DESCRIPTION
**Pull request by milesap**
Closes #808

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/988)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/init-map.directive.js, line 121 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/988#-KNbEWmv0d0U-MHOHxyw:-KNbEWmv0d0U-MHOHxyx:509231753) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/609ab387d4feacbed6cdfd0d6cb8b3d22b6e391d/src/app/geo/init-map.directive.js#L121)):*
> ```JavaScript
>             let x = 0;
>             let y = 0;
>             let hasShiftMultiplier = false;
> ```

Maybe use a number instead of a boolean. `1` for inactive; anything else for active modification. 
` mapPntCntr.x += hasShiftMultiplier * x; `

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/988)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/988)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/init-map.directive.js, line 121 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/988#-KNbEWmv0d0U-MHOHxyw:-KNbjdrwZvHBZv6P73vf:5173697) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/609ab387d4feacbed6cdfd0d6cb8b3d22b6e391d/src/app/geo/init-map.directive.js#L121)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Maybe use a number instead of a boolean. `1` for inactive; anything else for active modification. 
> ` mapPntCntr.x += hasShiftMultiplier * x; `
</details>
Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/988)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/988)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/988)*

**Pull request merged**
