### PR TITLE
Fix entry-about on the side navigation

### PR DESCRIPTION
**Pull request by barryytm**
## Description

#2089, fix entry `about` on the sidenav.  If the required attributes were not given for `about`, the about panel would be blank.
## Testing

Manually

## Documentation

NA
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2100)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/app/core/config.class.js, line 1865 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHS9YiJ2jkKKDoxPGh:-KoHS9YjiERFZQob3CtE:b-gidg7m) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/core/config.class.js#L1865)):*
> ```JavaScript
>                 'touch',
>                 'help',
>                 "about"
> ```

Single quotes please.

---

*[src/app/core/config.class.js, line 1970 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHSMo--_ivDDZwInme:-KoHSMo--_ivDDZwInmf:bhb4tny) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/core/config.class.js#L1970)):*
> ```JavaScript
>         constructor(aboutSource) {
>             this._source = aboutSource;
>             this._isMarkdown = true;
> ```

I think the string content can also be markdown.

---

*[src/app/core/config.class.js, line 2065 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHS_UjRrbzymjSVNpn:-KoHS_UjRrbzymjSVNpo:b-wx45z8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/core/config.class.js#L2065)):*
> ```JavaScript
>                 fullscreen: this.fullscreen,
>                 filterIsOpen: this.filterIsOpen.JSON,
>                 about: this.about.JSON
> ```

Since `this._about` doesn't have a default value, `this.about.JSON` will fail with `about is undefined` error.

---

*[src/app/ui/sidenav/sidenav.service.js, line 267 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHT7R9i2IqTDnApBRZ:-KoHT7R9i2IqTDnApBR_:b3hjt8r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/ui/sidenav/sidenav.service.js#L267)):*
> ```JavaScript
>         configService.onEveryConfigLoad(config => {
>             if (config.ui.about) {
>                 if (config.ui.about.isMarkdown) {
> ```

This is a strange condition, `if markdown, use content; if not markdown, use markdown`?
I think both content and folder files should be parsed as if it were markdown. If it's just regular text, it will stay that way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/sidenav/sidenav.service.js, line 267 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHT7R9i2IqTDnApBRZ:-KoHsi7jLXhbwvuLk6nu:b-imelyh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/ui/sidenav/sidenav.service.js#L267)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This is a strange condition, `if markdown, use content; if not markdown, use markdown`?
I think both content and folder files should be parsed as if it were markdown. If it's just regular text, it will stay that way.
</blockquote></details>

I have found it strange too and confusing.  Since I didn't write this code, I don't know what the author's intention was.  Should I modify this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by AleksueiR** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.service.js, line 267 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHT7R9i2IqTDnApBRZ:-KoI3kAu5WPQjHRy3nE3:bezafzi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/ui/sidenav/sidenav.service.js#L267)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

I have found it strange too and confusing.  Since I didn't write this code, I don't know what the author's intention was.  Should I modify this?
</blockquote></details>

Yes, I think this should be modified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/core/config.class.js, line 1865 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHS9YiJ2jkKKDoxPGh:-KoI3gHR12bzB6bemvX8:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/core/config.class.js#L1865)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Single quotes please.
</blockquote></details>

done, thanks

---

*[src/app/core/config.class.js, line 1970 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHSMo--_ivDDZwInme:-KoI4GxbFCGMjUPkiPQN:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/core/config.class.js#L1970)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think the string content can also be markdown.
</blockquote></details>

done, thanks

---

*[src/app/core/config.class.js, line 2065 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHS_UjRrbzymjSVNpn:-KoI3lxs_8HdwKsgaVUO:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/core/config.class.js#L2065)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Since `this._about` doesn't have a default value, `this.about.JSON` will fail with `about is undefined` error.
</blockquote></details>

done, thanks

---

*[src/app/ui/sidenav/sidenav.service.js, line 267 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100#-KoHT7R9i2IqTDnApBRZ:-KoI43xtUEeQvhDs1wiR:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/20f1f4c486d8e3f2557f99c57ddb198b6944b065/src/app/ui/sidenav/sidenav.service.js#L267)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Yes, I think this should be modified.
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2100)*

**Pull request merged**
