### PR TITLE
feat(bootstrap): load dependencies via host page url scheme

### LINKED ISSUE #1824: Load dependencies over host page URL's scheme
Request from user:
> ... It would also be awesome if you guys could update the jquery cdn you are using in your source code to use https instead of http. The live site will use https so if this is not changed the map will break. We also found the same issue in the core.js with this link https://js.arcgis.com/3.14/

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1824

## Testing
Yes

No

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1831)

### CODE REVIEW

**Comment by AleksueiR** [comment]
How do we really test this? cloudapp.net doesn't support https :(.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1831#-:-KgnaHnyStAAuU-1f6o6:brjtl9d)*

**Comment by milesap** [comment]
Merge and :pray: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1831#-:-KgnaTVbKMecTCGaG4qa:b42xp44)*

**Comment by AleksueiR** [comment]
Ha-ha :laughing: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1831#-:-KgnbpPcE-O82iabbZS6:bla0d55)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1831#-:-KgnpT0_fSj-026HGlwI:bnfp4nl)*

**Pull request merged**
