### PR TITLE
feat(ui): Add language switching inside the application in the side n…

### LINKED ISSUE #1150: Add Language Switching when in Fullscreen Application mode

### PR DESCRIPTION
**Pull request by jolevesq**
…avigation panel

Closes #1150

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1200)

### CODE REVIEW

**Comment by mweech** [comment]
need to add the Language icon google uses next to "Language" in the menu.

**Comment by milesap** [comment]
@jolevesq making an RC2 build this morning - if possible this can be included. Otherwise it'll go into schedule 1.3.0

**Comment by jolevesq** [comment]
It is ready to go but someone need to check the PR

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSHIu75nZnDhefrqpFF:b-9ikw61)*

**Comment by AleksueiR** [comment]
Will check a bit later.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSHKRPkraWsaEoQVkUQ:bf1eas5)*

**Comment by milesap** [comment]
Please include the [international language icon](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1150#issuecomment-247329216)

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/config.service.js, line 104 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHN3LCoEzISVRbOMC4:-KSHN3LDPpbv3FxL2GNJ:bb7phvt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6978611faa1641243b06d262ce2ba5e70d46c982/src/app/core/config.service.js#L104)):*
> ```JavaScript
>                     }
> 
>                     // set avialable languages
> ```

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSHJu6ozHOKZrH-1km6:b-csv9fs)*

**Comment by jolevesq** [comment]
If we use option 2 instead of do we still use the language icon?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSHVy65ECyzrviqfbcD:b-su277q)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by milesap** [comment]
Yes - it helps people find it who may not be able to distinguish it from all the other foreign (to them) language elements in the page

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSH_2X8Ndpat9aS0A9u:b-pcymb)*

**Comment by milesap** [comment]
^ for option 1, option 2 no

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSHaK1s3lGF4YWRowr0:b-h2ff0e)*

**Comment by jolevesq** [comment]
Mike ask me to put it for option 2 as well. It is in my latest push

---

Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSHb3ccgCT7TqWJRu1Y:b-d0itym)*

**Comment by jolevesq** [comment]
Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 104 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHN3LCoEzISVRbOMC4:-KSHgPWKAWUO5J04jptl:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6978611faa1641243b06d262ce2ba5e70d46c982/src/app/core/config.service.js#L104)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> typo
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by milesap** [comment]
I reviewed branch `1150-langswitch` by mistake since the actual branch `1150-langswitch-menu` [failed to build](https://travis-ci.org/jolevesq/fgpv-vpgf/builds/161381056)  originally so I didn't see it until now :+1:

---

Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSHeMl6KDHCI2cyF01-:b-3w8lo0)*

**Comment by milesap** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/sidenav/sidenav.html, line 32 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHi9W4i5-xHlubxa18:-KSHi9W5t3COn11tQEYD:b-1forz8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L32)):*
> ```HTML
>         <md-content role="language">
>             <span class="rv-language md-ink-rippled">{{ 'sidenav.label.language' | translate }}
>                 language icon</img>
> ```

doesn't the alt text need translations?
also, I guess we don't have an SVG link for the icon itself?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/sidenav/sidenav.html, line 30 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHgjM8i9RVkU1OD0nv:-KSHgjM8i9RVkU1OD0nw:by9sg5l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L30)):*
> ```HTML
>         <md-divider></md-divider>
> 
>         <md-content role="language">
> ```

A small change to the heading to make it a real heading and move the icon to the right:

```html
<h2 class="rv-language menu-heading md-subhead">{{ 'sidenav.label.language' | translate }}

    <span flex></span>
    <div>
        <img class="rv-language-icon" alt="language icon" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAYCAYAAAD6S912AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAwOS8wNi8xMy48nZQAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAACd0lEQVQ4jY2VP0/bQBjGHyKPIVgCM0QCn8Sc1JIlRnQLI8L4E3gjUoay9htEAgkmOjp7BiK+QD22k0+3VEw2HVu1cVO1SF2eDrEtY2KXR3qH851/73N/X5AESQAIAHhF+38BwARwYVnWFwAsv1cGRAAIIAVwA8BpgARCiE9CiO9XV1dPSZLQdd1FG7AaCsAFgHf9fv9+f3//22g0WsZxzKqqQAMt6vV6bzqdzvVyucTx8TGklPA8D6ZpNv9Ud9jr9WhZFk9OTnh3d0eS3NzcfOb89PSUYRhysVi8cAgAotvtvu92u3+llAzDkHXVgXW4bdu/AQiSwPb29rKabZ3agC/WPLdbSmvNyWTSCjRNk1EU0fO8l9Aq0Pd9GoZB27ZbgUEQkCTTNG0HFg4HgwEBcDabrQUqpcrxQoj1wKOjIxqGweFwyPF4zN3d3bUOHcchSUZRRJIMgmA9UGtNrTVJ0rbt0l0dOJ1OSZJSSqZpyul02j7l2WxG3/cbgVmWkSSVUkzTlFmWtQN936fWmkIIWpZFrXUJLDZDKVWCSdJxnBLYqd6a4XCIw8NDDAYDJEmC29tbPDw8lP1CCACAlBKmaeLs7KxslyocTiaTcg3rOjg4eGo6zEopzufz5imvk+u6iyaglPL5xrQB4zjm+fn5z62trR8AklddvzqwgOzt7X3t9/v3qLziABwA161w13UXSZLw8vLyz87Ozi/btj9iVQ5MtpcAB8BbAHENCr4WkoNusHo7i3AAiAp89Y5VskYAZAvQBPC5cFTvN0imlaOY5vFhY2PjEcA8T5DlLhwAXg5Vefu5GlwIrIpTlCcoCta8ujQAwvq//wD7F5sgS+yPtgAAAABJRU5ErkJggg==">
    </div>
</h2>
```

and some CSS:

```css
.rv-language {
    display: flex;
    align-items: center;
}

.rv-language-icon {
    margin-right: rem(0.8);
    display: block;
}
```

Should look like this: 


---

*[src/app/ui/sidenav/sidenav.html, line 32 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHi9W4i5-xHlubxa18:-KSHilJbSNJS7DolbonZ:bdskq1d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L32)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> doesn't the alt text need translations?
> also, I guess we don't have an SVG link for the icon itself?
</details>
We do, actually: https://upload.wikimedia.org/wikipedia/commons/9/98/Language_icon.svg

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.html, line 30 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHgjM8i9RVkU1OD0nv:-KSHwB-LHRO8FgF5vAqx:bk2ya9u) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L30)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> A small change to the heading to make it a real heading and move the icon to the right:
> 
> ```html
> <h2 class="rv-language menu-heading md-subhead">{{ 'sidenav.label.language' | translate }}
> 
>     <span flex></span>
>     <div>
>         language icon
>     </div>
> </h2>
> ```
> 
> and some CSS:
> 
> ```css
> .rv-language {
>     display: flex;
>     align-items: center;
> }
> 
> .rv-language-icon {
>     margin-right: rem(0.8);
>     display: block;
> }
> ```
> 
> Should look like this: 
> 
</details>
You want the check mark at the left, not the right like it is right now?

---

*[src/app/ui/sidenav/sidenav.html, line 32 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHi9W4i5-xHlubxa18:-KSHwRk4qRI8S4nD5oz5:bt6fpmj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L32)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> We do, actually: https://upload.wikimedia.org/wikipedia/commons/9/98/Language_icon.svg
</details>
You prefer I use the link instead of the base64 svg?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.html, line 30 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHgjM8i9RVkU1OD0nv:-KSHwqVoGB7k35VRxUB0:blpwp9u) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> You want the check mark at the left, not the right like it is right now?
</details>
oh, sorry, no check mark should be on the right, you are correct.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.html, line 32 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHi9W4i5-xHlubxa18:-KSHx4ohRSTD28mk_baz:b-mj9a10) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> You prefer I use the link instead of the base64 svg?
</details>


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.html, line 30 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHgjM8i9RVkU1OD0nv:-KSHxNeXcGreUXMeVGyE:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L30)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> oh, sorry, no check mark should be on the right, you are correct.
> 
</details>
Done.

---

*[src/app/ui/sidenav/sidenav.html, line 32 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHi9W4i5-xHlubxa18:-KSI3GCWwyUm1gI5Xa5e:b-sug7ov) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> 
</details>
Replace img tag by a div with the svg as background image.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.html, line 32 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-KSHi9W4i5-xHlubxa18:-KSI7Uy-K9SfDcPjm8DC:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/780f6764849ed611003997307db53df03feae073/src/app/ui/sidenav/sidenav.html#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Replace img tag by a div with the svg as background image.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by james-rae** [comment]
Reviewed 1 of 8 files at r1, 4 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 8 files at r1, 4 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1200#-:-KSM7h52QrbJC4aMSEjl:bnfp4nl)*

**Pull request merged**
