### PR TITLE
fix(ui): layers no longer appear after their placeholders are removed

### LINKED ISSUE #985: Removing legend placeholders does not remove layers
Layers removed in their loading state are loaded and added to the legend anyway:
removing_placeholders

### PR DESCRIPTION
**Pull request by milesap**
Closes #985

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1052)

### CODE REVIEW

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1052)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/legend.service.js, line 213 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1052#-KPNUfGUFlR1xS8WtxXU:-KPNUfGUFlR1xS8WtxXV:b-um982o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f54f714393c47e260de1829b88bb630a4494d9fc/src/app/geo/legend.service.js#L213)):*
> ```JavaScript
>              * @param {Object} layerRecord object from `layerRegistry` `layers` object
>              */
>             function addPlaceholder(layerRecord) {
> ```

can you add a TODO somewhere around here that this should be moved into `LegendEntry` when we (hopefully) get around to refactoring it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1052)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 213 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1052#-KPNUfGUFlR1xS8WtxXU:-KPSaKkInpa2Z0rQlJFQ:bvxtmuv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f54f714393c47e260de1829b88bb630a4494d9fc/src/app/geo/legend.service.js#L213)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> can you add a TODO somewhere around here that this should be moved into `LegendEntry` when we (hopefully) get around to refactoring it?
</details>
Ok added the `TODO` statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1052)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1052)*

**Pull request merged**
