### PR TITLE
fix(datatable): column headings scroll with body

### LINKED ISSUE #2141: More service layers (both Feature and Dynamic) - Datagrid Column Headings not scrolling with body
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html
Test data: http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0

This is a similar issue as previous logged in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2081, just realize this behavior is not only happened with scale dependency layers.

image

### PR DESCRIPTION
**Pull request by milesap**
## Description

Closes #2141

## Testing
:eyes: on chrome and FF

## Documentation
None

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2149)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
:lgtm: WOMM

Do we want to do anything about the extra space though, specifically when we hide all the columns?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2149#-:-Komy2tJBfefhEqswJo6:bsxpx3d)*

**Comment by AleksueiR** [comment]
This does seem to fix the problem, but with this option removed, some columns are getting extremely wide, and when there is not enough columns, that extra space looks ugly, if I may say so. I'm not really sure what to do at this point. I guess functionality beats ugliness... If we can somehow make the white space prettier, that would be nice.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2149#-:-KoqTPX-dVG-0LwSVn51:b-fntvtf)*

**Comment by milesap** [comment]
I personally like the look better than stretching a column past its useful size. I'll leave it as is for now. @aleksueir I believe DataTables sets the width to fit the largest value in the column. This can be changed by providing a `columns.width`. See https://datatables.net/reference/option/columns.width. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2149#-:-KoqpooZ80DoJV_rYS8W:b-g0sgxq)*

**Comment by AleksueiR** [comment]
The :eagle: has spoken. Please rebase for merging.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2149#-:-KpFvep_D0hDEB09SXsC:b-umf6p8)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2149)*

**Pull request merged**
