### PR TITLE
fix(config): maintain scale on language switch

### PR DESCRIPTION
**Pull request by cynngah**
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/784

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1073)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073)*

**Comment by AleksueiR** [comment]
Not sure I understand how this solves the issue. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073#-:-KPwREDV3d2rtqckanhk:b-8i0lsg)*

**Comment by cynngah** [comment]
French version uses the full extent on start up which is a lot more zoomed out than the default. English config doesn't have this full extent part so they have a different starting extent.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073#-:-KPwYGGKM9G3D6h3G-P5:b9u4b1i)*

**Comment by AleksueiR** [comment]
Why is full extent used on start up at all? 

According to the schema, default is the starting extent:
```json
"default": { "$ref": "#/definitions/extentWithReferenceNode", "description": "The default (starting) extent." },
"full": { "$ref": "#/definitions/extentWithReferenceNode", "description": "The full extent (should give good view of the whole map, not necessarily the maximum extent); default will be used if not supplied." },
```

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073#-:-KPwZDOsjTDVKMY-T3ra:b3qjlta)*

**Comment by cynngah** [comment]
It says at the end of the description for full extent that "default will be used if not supplied." So I assume full extent takes priority over the default.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073#-:-KPw_JiI0DJz44Lwc3nV:b-gwhm8n)*

**Comment by AleksueiR** [comment]
`default will be used if not supplied.` just means that in places where the `full` extent is required, the `default` extent should be used if the `full` extent is not specified.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073#-:-KPw_a9139uoIjOke7DV:b-3qw32v)*

**Comment by cynngah** [comment]
All right so I just investigated the code and it seems like it just always uses full extent if it's present, even on map load. There's a `getFullExtFromExtentSets` function which does that but doesn't seem to be anything that tries to get the default extent.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073#-:-KPx4y9JItN1_krWJOnM:b-z1cr8a)*

**Comment by AleksueiR** [comment]
Map startup now uses the default extent. :lgtm: 

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1073#-:-KQ0TxfZXz2C_jNz6BcB:byn4b64)*

**Pull request merged**
