### PR TITLE
fix(legend): menu can no longer be opened if empty

### LINKED ISSUE #2126: Remove is not an option in legend
When `remove` was added in `layers` under `controls` in a config file.  

capture2

The following appeared when the "more options icon" was clicked.

image

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2126

## Testing
:eyes: on chrome

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2148)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/legend-block.directive.js, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148#-KomY2OdnPmxD6usgpmd:-KomY2OdnPmxD6usgpme:btsw1x2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ea21341d3acc24740b8e822ee3de76d31333afcf/src/app/ui/toc/legend-block.directive.js#L32)):*
> ```JavaScript
>     .directive('rvLegendBlock', rvLegendBlock);
> 
> function rvLegendBlock($compile, $templateCache, layoutService, appInfo, common, configService, ConfigObject, LegendBlock) {
> ```

`LegendBlock` doesn't seem to be used.

---

*[src/app/ui/toc/templates/legend-node.html, line 38 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148#-KomXHsPIFL1NS4D4Ude:-KomXHsPIFL1NS4D4Udf:b-m09zd9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ea21341d3acc24740b8e822ee3de76d31333afcf/src/app/ui/toc/templates/legend-node.html#L38)):*
> ```HTML
> <div class="rv-list-item-controls" ng-if="!self.isReorder">
>     <md-menu md-position-mode="target-right target" class="rv-list-item-control"
>         ng-if="self.hasMenu()">
> ```

Can we do one time binding here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148)*

**Comment by AleksueiR** [comment]
Can you modify one of the sample configs so this condition can be tested? 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148#-:-KorRkcUVpa_wPtwt-9z:bskkof9)*

**Comment by milesap** [comment]
Modified samples #1

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148#-:-KordLUXpqsqeUm0--81:b82gcbb)*

**Comment by JahidAhmed** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2148)*

**Pull request merged**
