### PR TITLE
Basic RCS integration

### LINKED ISSUE #269: Instantiation of map from RCS
- [x] Need to define how viewer consumes RCS config (https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Custom-Attributes)
- [x] Need to implement logic for merging of configuration fragments (port from RAMP)

Traceability Matrix ID#040

### PR DESCRIPTION
**Pull request by alyec**
Should close #269 when approved (might want to have a split task for consumption of additional data from the RCS).

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/375)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 5 of 7 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[bower.json, line 3 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG4aK4E_-dxppKTLUt:-KCG4aK4E_-dxppKTLUu:-1510386875) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/bower.json#L3)):*
Good call!

---

*[src/index-one.html, line 20 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG4gS_SLg2Bz4eacSz:-KCG4gS_SLg2Bz4eacT-:1170011238) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/index-one.html#L20)):*
Rename `th-config` to `rv-config`.

---

*[src/app/core/config.service.js, line 214 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG6A_APg0kO9vGyiZ_:-KCG6A_APg0kO9vGyiZa:-2136012181) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/app/core/config.service.js#L214)):*
Unless I'm wrong, there ever will only be one item per array. Why array?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by alyec** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 214 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG6A_APg0kO9vGyiZ_:-KCGG5RjLWSctDysBBdV:2095790660) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/app/core/config.service.js#L214)):*
Are you talking about the `partials[lang]` array?  For files, yes it will only ever be a single element, but once RCS entries load it will also add elements to this array (each one being a partial config promise).  All of them eventually get resolved, then all the config fragments should get merged.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by AleksueiR** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 214 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG6A_APg0kO9vGyiZ_:-KCGGnm-c8e5D5uXFoPT:1986600344) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/app/core/config.service.js#L214)):*
Makes sense. Can we add this to the comments?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by alyec** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 214 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG6A_APg0kO9vGyiZ_:-KCGH3ZDsU_MCUwQ-_Sv:-289600170) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/app/core/config.service.js#L214)):*
Will do, after discussing with everyone if this is actually the way we want to continue loading or if there are better options (this was written mainly to have *something* in place for the alpha release).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by spencerwahl** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 214 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG6A_APg0kO9vGyiZ_:-KCHKts-vCq_Wra-JPsQ:1633244679) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/app/core/config.service.js#L214)):*
NOTE: based on discussions with the team we're going to leave this alone for now.  There is a potential for optimization if we know there is a basic config supplied + other entries which would not affect the initial rendering of the map.  We can revisit that after the initial release.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by AleksueiR** [comment]
Review status: 5 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 214 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG6A_APg0kO9vGyiZ_:-KCHMolHQYe5nLww2JaL:-1880448064) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/app/core/config.service.js#L214)):*
Can we record this decision somewhere?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index-one.html, line 20 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG4gS_SLg2Bz4eacSz:-KCHNqwNep7_hQ3ttL5L:676635175) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/index-one.html#L20)):*
Done

---

*[src/app/core/config.service.js, line 214 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375#-KCG6A_APg0kO9vGyiZ_:-KCHQD7GLTVQPCOOvRoR:1198181769) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e28d7b659af7cfd8924e78a757a58ec046c3a741/src/app/core/config.service.js#L214)):*
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/380
https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Config-Schema#parsing-notes

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/375)*

**Pull request merged**
