### PR TITLE
feat(ui): add layer from the config to the layer selector

### PR DESCRIPTION
**Pull request by AleksueiR**
For now I want to keep fake layers in the layer selector as well to demo group functionality and other stuff. I'll add real layers in a group with the same name.
Layer items will display their initial visibility and layertype but cannot be toggled at the moment. Fake metadata and settings are available; attributes not available yet.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/286)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by spencerwahl** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/geo.service.js, line 251 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286#-K9cmkUQO7pwtwEPOjmK:-K9cmkURT36ijnCUkHBm:968699824) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0421cbcde37b1f2b453b5ecb0c698b450e13e0a9/src/app/geo/geo.service.js#L251)):*
I think this caused a problem with registering the layer before all the needed info was attached, which then caused a problem when registering attributes. I could always be wrong/remembering it incorrectly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 251 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286#-K9cmkUQO7pwtwEPOjmK:-K9cxGOZmAuKwCWmaDbT:-1648437021) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0421cbcde37b1f2b453b5ecb0c698b450e13e0a9/src/app/geo/geo.service.js#L251)):*
@james-rae, any thoughts on that?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 251 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286#-K9cmkUQO7pwtwEPOjmK:-K9hB5We7Po2dxsapYBA:677940215) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0421cbcde37b1f2b453b5ecb0c698b450e13e0a9/src/app/geo/geo.service.js#L251)):*
ping

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by james-rae** [comment]
*[src/app/geo/geo.service.js, line 251 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286#-K9cmkUQO7pwtwEPOjmK:-K9hZnj2ubTR42-JdVpZ:580305750) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0421cbcde37b1f2b453b5ecb0c698b450e13e0a9/src/app/geo/geo.service.js#L251)):*
No thoughts :blowfish: :dash: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by AleksueiR** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 251 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286#-K9cmkUQO7pwtwEPOjmK:-K9hZkeBKt8C0KPAulbm:58933929) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0421cbcde37b1f2b453b5ecb0c698b450e13e0a9/src/app/geo/geo.service.js#L251)):*
@spencerwahl, Attributes are registered strictly after the layer is registered; see line [263](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4b922d93349630d912dff12250edd5c4bde9c4f7/src/app/geo/geo.service.js#L263). 

I'll add a comment linking back here in case we ever get related errors.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by spencerwahl** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 251 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286#-K9cmkUQO7pwtwEPOjmK:-K9haDXx0a_eY-mWapIQ:1116473300) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0421cbcde37b1f2b453b5ecb0c698b450e13e0a9/src/app/geo/geo.service.js#L251)):*
Yeah, I can't remember the exact problem so this is fine with me :+1:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/286)*

**Pull request merged**
