### PR TITLE
Schema changes

### LINKED ISSUE #334: Investigate Legend schema for supporting Grouped layers
Review current schema and add definitions to support nested group layers

### PR DESCRIPTION
**Pull request by alyec**
When accepted this should close #334 .

Will probably need some discussion, and the WMS layers won't work right away.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/363)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/config-demo.json, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhBcTpO7twRvHjKOV7:-KBhBcTpO7twRvHjKOV8:983781944) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/config-demo.json#L53)):*
What happens if `layerEntries` is an empty array?

---

*[src/schema.json, line 490 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhBEmZdv8nYKPVQCwH:-KBhBEmZdv8nYKPVQCwI:2104071026) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/schema.json#L490)):*
I forget: Does this mean the layer is visible or the visibility control is available?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/config-demo.json, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhBcTpO7twRvHjKOV7:-KBhIeq5d40g_jwAqNH_:404052422) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/config-demo.json#L53)):*
At the moment nothing.  I'm not sure if there is ever a use case for an entry with no layers selected so maybe I should add a min length restriction on the array once the map consumes these properly.  @james-rae any thoughts?

---

*[src/schema.json, line 490 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhBEmZdv8nYKPVQCwH:-KBhJPxXmM8mCisCUzkA:1612981241) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/schema.json#L490)):*
Based on our discussion I will split this up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/schema.json, line 397 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhJYpQFWEQPfh4Ju8x:-KBhJYpR7kiJnEMzUBBq:-960844509) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/schema.json#L397)):*
Would it be worth noting that this will be text "layer id" for WMS and an integer in string form for ArcGIS Server?  This detail may be more appropriate in online architecture docs.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by james-rae** [comment]
*[src/config-demo.json, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhBcTpO7twRvHjKOV7:-KBhVUlt8SXYIXxUTHlR:-446211570) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/config-demo.json#L53)):*
I'd suggest either a min restriction as suggested (will be nicer when we have a config-builder-app), or alternately an empty array becomes "show everything" -- nice from a default perspective (benefits lazy people making configs), bad from a code perspective as we have to transform the empty array into a pile of config nuggets.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by alyec** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/config-demo.json, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhBcTpO7twRvHjKOV7:-KBhn8qXIv2VcG0PHb98:1291429996) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/config-demo.json#L53)):*
Added `minItems` since we can relax the restriction more easily than imposing it later.

---

*[src/schema.json, line 397 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363#-KBhJYpQFWEQPfh4Ju8x:-KBhnH5y57tUKtjPLc0w:-1683307661) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a8739c258f7ff81547e1902f67c5517495a38481/src/schema.json#L397)):*
Fixed the docs.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Comment by ec-dev** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/363)*

**Pull request merged**
