### PR TITLE
fix(ui): add details icon to dynamic layers

### LINKED ISSUE #416: Enable Point Information Display when viewing Datagrid
When selecting a record in the datagrid the point information panel should provide an output similar to that which is provided by Identify.

- [x] reuse map click (in identifyService) to display the proper data and trigger the point click details panel
- [x] make another button in datagrid which triggers the above logic
- [x] make tooltip so people know they're getting details when clicking on said button

### PR DESCRIPTION
**Pull request by cynngah**
Closes #416

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/634)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/634)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 116 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/634#-KI8OZliIOx-nWqLfpfs:-KI8OZliIOx-nWqLfpft:702137848) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/637c3f48edf0aef60ef443d98dc2f247f1ee2475/src/app/ui/filters/filters-default.directive.js#L116)):*
> ```JavaScript
>                     addColumnInteractivity(interactiveColumn, [ZOOM_TO_ICON(zoomText), DETAILS_ICON(descriptionsText)]);
>                 } else {
>                     // TODO:move interactiveColumn section out of esriFeature if block and remove else block when zoom supports dynamic layers
> ```

Do we have a separate task to add zoom support for dynamic layers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/634)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 116 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/634#-KI8OZliIOx-nWqLfpfs:-KI8Ot8b2NdbapnrcOlN:-699648462) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/637c3f48edf0aef60ef443d98dc2f247f1ee2475/src/app/ui/filters/filters-default.directive.js#L116)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Do we have a separate task to add zoom support for dynamic layers?
</details>
Nope. Will add one now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/634)*

**Comment by AleksueiR** [comment]
:lgtm:

<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> #### fix\(ui\): add details icon to dynamic layers
> 
> Closes #416
> 
> 
> 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/634#-:-KID0A4LKCoWWwlkC0I_:1417088721)*

**Pull request merged**
