### PR TITLE
Datatable translations

### PR DESCRIPTION
**Pull request by spencerwahl**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/921)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 53 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921#-KN2vmHQNG49seebmQ9A:-KN2vmHQNG49seebmQ9B:-1703778109) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3782355897b41256be105ecbec8b05a8acea5e5d/src/app/ui/filters/filters-default.directive.js#L53)):*
> ```JavaScript
> 
>             /**
>              * Creates a new datatables instance (destroying existing if any). It pulls the data from the stateManager display store.
> ```

please add the param and function name to the jsdoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921)*

**Comment by spencerwahl** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 53 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921#-KN2vmHQNG49seebmQ9A:-KN34vrxyYgOuB4EHZ6K:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3782355897b41256be105ecbec8b05a8acea5e5d/src/app/ui/filters/filters-default.directive.js#L53)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> please add the param and function name to the jsdoc
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921#-:-KN37-ASV7_kM4cxwqZQ:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/921)*

**Pull request merged**
