### PR TITLE
Fix projection switching after adding a layer

### PR DESCRIPTION
**Pull request by spencerwahl**
issue #920

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/923)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/loader/loader-file.directive.js, line 193 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/923#-KN364I46bUed8XP3V_T:-KN364I46bUed8XP3V_U:379393131) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab13fa64c851e23f61cdcdcfc93fd964b6a3d120/src/app/ui/loader/loader-file.directive.js#L193)):*
> ```JavaScript
>             );
> 
>             self.layerBlueprint.initialConfig = { flags: { user: { visible: true } } };
> ```

Please, add TODOs here and in `loader-service` to refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/923)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/923)*

**Comment by spencerwahl** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/loader/loader-file.directive.js, line 193 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/923#-KN364I46bUed8XP3V_T:-KN37n2DciM0a4LvxJO8:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab13fa64c851e23f61cdcdcfc93fd964b6a3d120/src/app/ui/loader/loader-file.directive.js#L193)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Please, add TODOs here and in `loader-service` to refactor.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/923)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/923)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/923)*

**Pull request merged**
