### PR TITLE
Scrollbar for detail selector

### PR DESCRIPTION
**Pull request by spencerwahl**
Issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/545
__________________

This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/594)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/ui/details/details.directive.js, line 70 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594#-KHdxGtf_5vrBrKgsmQH:-KHdxGtf_5vrBrKgsmQI:-1482492221) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f72e0386cdef389fe70ef4e896e3e009eaffb145/src/app/ui/details/details.directive.js#L70)):*
> ```JavaScript
>                         .set(layerList, {
>                             'overflow-y': 'auto'
>                         }, RV_SLIDE_DURATION / 2)
> ```

I think there is a tad better way to do it without having to force clear props on the reverseComplete event:
```js
.fromTo(layerList, 0.01, {
	'overflow-y': 'hidden'
	}, {
	'overflow-y': 'auto'
}, RV_SLIDE_DURATION / 2)
```
This will explicitly "animate" the `overflow` property from `hidden` to `auto` and not try to figure out what it was initially on the reverse run. Maybe add this comment to the code as well.

---

*[src/content/styles/modules/_details.scss, line 74 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594#-KHdylXq8jQp8eV1EDz0:-KHdylXq8jQp8eV1EDz1:86484373) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f72e0386cdef389fe70ef4e896e3e009eaffb145/src/content/styles/modules/_details.scss#L74)):*
> ```SCSS
>             bottom: - rem(0.8);
>             border-right: solid 1px $divider-color-light;
>             overflow: hidden;
> ```

While you at it, please add `padding: rem(0.8) 0;` here. It add a nice padding on top and bottom of the mini layer selector.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_details.scss, line 13 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594#-KHeYupif9vEDMW0R0Gk:-KHeYupif9vEDMW0R0Gl:1556407648) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72086a40975a45b96514ce31d7d0c308101aeb41/src/content/styles/modules/_details.scss#L13)):*
> ```SCSS
> 
>         .rv-subheader {
>             padding-right: 25px;
> ```

use `rem(0.25)` instead of pixels

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/details/details.directive.js, line 70 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594#-KHdxGtf_5vrBrKgsmQH:-KHeZ0uANd9ZJya8Jxps:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f72e0386cdef389fe70ef4e896e3e009eaffb145/src/app/ui/details/details.directive.js#L70)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I think there is a tad better way to do it without having to force clear props on the reverseComplete event:
> ```js
> .fromTo(layerList, 0.01, {
> 	'overflow-y': 'hidden'
> 	}, {
> 	'overflow-y': 'auto'
> }, RV_SLIDE_DURATION / 2)
> ```
> This will explicitly "animate" the `overflow` property from `hidden` to `auto` and not try to figure out what it was initially on the reverse run. Maybe add this comment to the code as well.</details>
Done.

---

*[src/content/styles/modules/_details.scss, line 74 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594#-KHdylXq8jQp8eV1EDz0:-KHeZ4d5AY0uMJMqbRjJ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f72e0386cdef389fe70ef4e896e3e009eaffb145/src/content/styles/modules/_details.scss#L74)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> While you at it, please add `padding: rem(0.8) 0;` here. It add a nice padding on top and bottom of the mini layer selector.</details>
Done.

---

*[src/content/styles/modules/_details.scss, line 13 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594#-KHeYupif9vEDMW0R0Gk:-KHe_VVyfFMo2ANeP7cq:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72086a40975a45b96514ce31d7d0c308101aeb41/src/content/styles/modules/_details.scss#L13)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> use `rem(0.25)` instead of pixels</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594)*

**Comment by AleksueiR** [comment]
:lgtm_strong:

<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> #### Scrollbar for detail selector
> 
> Issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/545
> 
> __________________
> 
> 
> 
> 
> 
> </details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/594#-:-KHe_cZ14c21n8Yj6hzZ:-1168659251)*

**Pull request merged**
