### PR TITLE
chore(docs): expand tutorial documentation

### PR DESCRIPTION
**Pull request by milesap**
## Description
Remaining documentation for tutorial

## Testing
yes

## Documentation
yes

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1690)

### CODE REVIEW

**Comment by milesap** [comment]
Documentation URL: http://fgpv-vpgf.github.io/fgpv-vpgf/docReview/index.html

**Comment by james-rae** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by jolevesq** [comment]
Reviewed 29 of 30 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[docs/developer/translations.md, line 43 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwuidcZMDbjoSYjKrB:-KcwuidcZMDbjoSYjKrC:b-6nzv92) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/translations.md#L43)):*
> ```Markdown
> 
> ```html
> <div class="fgpv" rv-langs='["en-CA", "fr-CA", "es-ES"]'
> ```

Shouyld you cahnge class="fgpv" for is="rv-map"?

---

*[docs/developer/technical/datatables.md, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwwBYZlTEcK9vkX5fU:-KcwwBY_KT2_8F0bFMYo:b-sx7chs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/technical/datatables.md#L32)):*
> ```Markdown
> ### filters-default-menu.directive.js
> 
> Simple directive which defines the popup menu items (visually represented in the above screenshot in blue).
> ```

Do you want to add information about filters in filters-definition.directive.js for filtering the table, filters-serach.directive for the global search capability, filters-setting-panel.directive.js to access filters, sort, display and column reorder, filters-setting-cluster.directive to access filters setting panel, clear filters and apply filters on map for esriDynamic and esriFeature layer format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by alyec** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/contributing_guide.md, line 70 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-Kcwy3xONH-sVy_t3--C:-Kcwy3xONH-sVy_t3--D:bg9pid4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/contributing_guide.md#L70)):*
> ```Markdown
> ```
> 
> ## Pull Request Process
> ```

I think a link to the wiki makes more sense for this, but I'm open to discussion.  I think process documentation can stay on the wiki, while actual coding dev docs belong in the docs repo.  Maybe just leave a link to the wiki here?

---

*[src/app/bootstrap.js, line 148 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-Kcx04V4NyY6B4rwmO-P:-Kcx04V4NyY6B4rwmO-Q:bad7n6u) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/src/app/bootstrap.js#L148)):*
> ```JavaScript
> 
>         /**
>          * Initializes the viewer with this bookmark.
> ```

We definitely need to describe the difference between initialBookmark and useBookmark

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by jolevesq** [comment]
Reviewed 1 of 30 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by milesap** [comment]
Review status: 27 of 30 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/contributing_guide.md, line 70 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-Kcwy3xONH-sVy_t3--C:-Kcxc--YnZYPOlQblNOj:barcpjb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/contributing_guide.md#L70)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

I think a link to the wiki makes more sense for this, but I'm open to discussion.  I think process documentation can stay on the wiki, while actual coding dev docs belong in the docs repo.  Maybe just leave a link to the wiki here?
</blockquote></details>

That makes sense, moved back to wiki and linked to it from docs

---

*[docs/developer/translations.md, line 43 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwuidcZMDbjoSYjKrB:-Kcxc50WpeNVDHOfCu3O:bni11n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/translations.md#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Shouyld you cahnge class="fgpv" for is="rv-map"?
</blockquote></details>

Good catch, added `is="rv-map"`. I believe `class="fgpv"` can stay.

---

*[docs/developer/technical/datatables.md, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwwBYZlTEcK9vkX5fU:-KcxeRvDpnvHhQVn-76m:b-7g1o08) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/technical/datatables.md#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you want to add information about filters in filters-definition.directive.js for filtering the table, filters-serach.directive for the global search capability, filters-setting-panel.directive.js to access filters, sort, display and column reorder, filters-setting-cluster.directive to access filters setting panel, clear filters and apply filters on map for esriDynamic and esriFeature layer format.
</blockquote></details>

Would you be able to write up some of that preliminary documentation while it is still fresh in your mind? At least in point form outlining the general architecture, I can then fill in any missing gaps and integrate it with the rest of the docs. Let me know if this is ok with you.

---

*[src/app/bootstrap.js, line 148 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-Kcx04V4NyY6B4rwmO-P:-KcxfksDo3TfdwVSrB2R:b8bempt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/src/app/bootstrap.js#L148)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

We definitely need to describe the difference between initialBookmark and useBookmark
</blockquote></details>

Put a more detailed doc for initialBookmark

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by jolevesq** [comment]
Review status: 27 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/developer/technical/datatables.md, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwwBYZlTEcK9vkX5fU:-KcyLoaOSJw2T4c-vPz6:b-4a8r1p) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/technical/datatables.md#L32)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Would you be able to write up some of that preliminary documentation while it is still fresh in your mind? At least in point form outlining the general architecture, I can then fill in any missing gaps and integrate it with the rest of the docs. Let me know if this is ok with you.
</blockquote></details>

It is ok whit me. I will send you something soon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by AleksueiR** [comment]
:trophy: :trophy: :trophy: 

---

Reviewed 27 of 30 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/developer/technical/datatables.md, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwwBYZlTEcK9vkX5fU:-Kd0wfUBaq1S4UFH6P0L:biyhrbd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/technical/datatables.md#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is ok whit me. I will send you something soon
</blockquote></details>

Do we want the docs on enhanced datatable to be public before we release these features?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-:-Kd0xE-mqWm9dwOifqlG:bb59bvv)*

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/bootstrap.js, line 148 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-Kcx04V4NyY6B4rwmO-P:-Kd1Ie0BbU9yPMdawUOR:bjabrt4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/src/app/bootstrap.js#L148)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Put a more detailed doc for initialBookmark
</blockquote></details>

I'm not sure if you know what's going on behind the scenes, but `initialBookmark` also gets out of the way if a `useBookmark` call comes in before it triggers (in some kind of really odd race condition where a user can click on something before full map load).

Suggested text:
```plain
initialBookmark is intended to be the first bookmark loaded by the map application (for example, when a bookmark comes in the URL bar) and should only be used if the `rv-wait` attribute is set on the map DOM node.  `rv-wait` will inform the viewer to wait until an unblocking call like initialBookmark is called.

If a useBookmark call happens to be triggered before initialBookmark it will take priority (useBookmark is typically triggered by user actions which should take priority over automated actions).
```

I think we should put something similar in `useBookmark`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by milesap** [comment]
Review status: 28 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/bootstrap.js, line 148 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-Kcx04V4NyY6B4rwmO-P:-Kd1fNV2HqNdGM4l2djw:bvcv1ig) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/src/app/bootstrap.js#L148)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

I'm not sure if you know what's going on behind the scenes, but `initialBookmark` also gets out of the way if a `useBookmark` call comes in before it triggers (in some kind of really odd race condition where a user can click on something before full map load).

Suggested text:
```plain
initialBookmark is intended to be the first bookmark loaded by the map application (for example, when a bookmark comes in the URL bar) and should only be used if the `rv-wait` attribute is set on the map DOM node.  `rv-wait` will inform the viewer to wait until an unblocking call like initialBookmark is called.

If a useBookmark call happens to be triggered before initialBookmark it will take priority (useBookmark is typically triggered by user actions which should take priority over automated actions).
```

I think we should put something similar in `useBookmark`
</blockquote></details>

:+1:  made the changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/developer/technical/datatables.md, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwwBYZlTEcK9vkX5fU:-Kd1hOJ85evpacP0BJZP:b-bf61ny) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/technical/datatables.md#L32)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Do we want the docs on enhanced datatable to be public before we release these features?
</blockquote></details>

We can add these details in a future PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/developer/technical/datatables.md, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690#-KcwwBYZlTEcK9vkX5fU:-Kd1meX1D9oCpyxYsu4u:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6415bc71011d9e0b1c96611c49890e36eca97c22/docs/developer/technical/datatables.md#L32)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

We can add these details in a future PR.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1690)*

**Pull request merged**
