### PR TITLE
feat(ui): small mobile layout optimizations

### LINKED ISSUE #1242: Small Mobile Layout Optimizations
Implement optimization for the viewer to be visible on a small layout (0-480 pixels)
- [x] update panels to occupy the whole screen
- [ ] ~~adjust row/column spacing to allow for more data to be visible~~ (This is done automagically by datatables)
- [x] add back arrows instead of the close buttons in the top-left corner to child panels when overlaying their parent panels.
- [x] remove split view from datatable
- [x] datatable is maximized by default

### PR DESCRIPTION
**Pull request by milesap**
Closes #1242, #1245 

Existing sass will be considered default, can modify sass files inline for
changes needed for specific layout types like this:

```
@include media($sm-only) {
    css here...
}
```

Currently there are three types of pre-built media query:
- `$sm-only`: Less than or equal to 480px
- `$md-only`: Greater than 480px but less than or equal to 840px
- `$lg-only`: Greater than 840px

You can also create custom queries inline, see
[include-media](http://include-media.com/#features) for full examples.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1253)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 20 files at r1.
Review status: 4 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/content/styles/_include-media.scss, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEpWiWD3WiakDJxzyC:-KTEpWiXl5tSOu28vWrJ:b51k3zc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/_include-media.scss#L1)):*
> ```SCSS
> @charset "UTF-8";
> ```

This should be included through bower, not directly in our source.

---

*[src/content/styles/main.scss, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEsUGs8KTE4TmF4Pzr:-KTEsUGs8KTE4TmF4Pzs:b-on28yd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/main.scss#L19)):*
> ```SCSS
> }
> 
> @include media($sm-only) {
> ```

Make a separate file for this, call it `_breakpoints` and put it in `common`. `main` is just to pull stuff in.

---

*[src/content/styles/common/_all.scss, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEq_4nyykxmb4ssorR:-KTEq_4nyykxmb4ssorS:b-1kafx4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/common/_all.scss#L10)):*
> ```SCSS
> $breakpoints: (small: 480px, medium: 840px);
> $sm-only: "<=small";
> $md-only: ">small", "<=medium";
> ```

`md-` is Angular Material prefix, it's better to use something else. 

Use `rv`, I guess. 

`rv-sm` "<=small";
`rv-md` ">small", "<=medium";
`rv-lg` ">medium"

We can also add `rv-gt-sm` ">small" to indicate `medium` and `large` layouts.

---

*[src/content/styles/modules/_mapnav.scss, line 22 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEsoyqOnjnx-F_y_6E:-KTEsoyrxBbUCh22uS1f:b7mml53) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/modules/_mapnav.scss#L22)):*
> ```SCSS
> 
>         .rv-button-group {
>             @include media(">small") {
> ```

We don't necessarily want to remove opacity effect on every small screen. Only on ones that are touch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by milesap** [comment]
Review status: 4 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/content/styles/common/_all.scss, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEq_4nyykxmb4ssorR:-KTFCwcZSFYUl2rFh-FG:bud9rrf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/common/_all.scss#L10)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `md-` is Angular Material prefix, it's better to use something else. 
> 
> Use `rv`, I guess. 
> 
> `rv-sm` "<=small";
> `rv-md` ">small", "<=medium";
> `rv-lg` ">medium"
> 
> We can also add `rv-gt-sm` ">small" to indicate `medium` and `large` layouts.
> 
> 
</details>
Ok made the change

---

*[src/content/styles/modules/_mapnav.scss, line 22 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEsoyqOnjnx-F_y_6E:-KTFE9uvsdSXngz1ZVMt:b-3zsvb9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/modules/_mapnav.scss#L22)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> We don't necessarily want to remove opacity effect on every small screen. Only on ones that are touch.
</details>
Ok removed for now - there is no reliable way to detect touch devices with media queries

---

*[src/content/styles/_include-media.scss, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEpWiWD3WiakDJxzyC:-KTFCVLfHfkLTqsHGTIh:bj8r970) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/_include-media.scss#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This should be included through bower, not directly in our source.
</details>
Now using bower

---

*[src/content/styles/main.scss, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEsUGs8KTE4TmF4Pzr:-KTFCcjSAwQffSDm5h_8:b-phc3ya) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/main.scss#L19)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Make a separate file for this, call it `_breakpoints` and put it in `common`. `main` is just to pull stuff in.
</details>
Created file `_breakpoints.scss`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by AleksueiR** [comment]
I noticed the slide out animation for the main panel doesn't use the full width (it resizes after finishing though):



Also, details panel doesn't open from the datatable.

---

Reviewed 5 of 20 files at r1, 9 of 12 files at r2.
Review status: 16 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/content/styles/modules/_app-menu.scss, line 10 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFk126MNIjHIZcIL1n:-KTFk126MNIjHIZcIL1o:bv3f0m9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_app-menu.scss#L10)):*
> ```SCSS
> 
>             @include media($rv-sm) {
>                 max-width: 100%;
> ```

Let's keep the side nav width at 80%, when it takes the full width, it appears as a more permanent component than just a side menu.

---

*[src/content/styles/modules/_content-pane.scss, line 77 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFjJRJZTZzmZL3s49y:-KTFjJRJZTZzmZL3s49z:bsa8a80) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_content-pane.scss#L77)):*
> ```SCSS
>     > .md-headline,
>     > .md-title,
>     > .md-subhead {
> ```

Add 16px margin to the left of the title to space the text and the arrow a little bit.

---

*[src/content/styles/modules/_mapnav.scss, line 22 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEsoyqOnjnx-F_y_6E:-KTFeU3jqpy7H3JCT2Nq:b-vsgh61) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/modules/_mapnav.scss#L22)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Ok removed for now - there is no reliable way to detect touch devices with media queries
</details>
Ok. Make a note of that somewhere, so we don't forget to bring it back.

---

*[src/content/styles/modules/_mapnav.scss, line 13 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFlGj8IwTBg-46az41:-KTFlGj8IwTBg-46az42:bfatrwo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_mapnav.scss#L13)):*
> ```SCSS
> 
>         @include media($rv-sm) {
>             bottom: 5px;
> ```

I like the smaller gutter for nav bar :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KTFk_3_tS1I7n1cG8LH:bfchbk1)*

**Comment by milesap** [comment]
Corrected the animation width issue and the details panel is now visible. 

---

Review status: 14 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/content/styles/modules/_content-pane.scss, line 77 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFjJRJZTZzmZL3s49y:-KTFnhLsosrrKWIHb-K9:bkjknbx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_content-pane.scss#L77)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Add 16px margin to the left of the title to space the text and the arrow a little bit.
</details>
Changed the arrow position from front to back since there were issues with arrow placement for details panel (wanted to keep back arrow uniform across the panels). Margin seems ok after this change

---

*[src/content/styles/modules/_mapnav.scss, line 22 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTEsoyqOnjnx-F_y_6E:-KTFom7PE5WZ7O6tPtuS:brfrxvr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1ee3e9e3d77c2e3a3233bed006969d6fe6e96fcf/src/content/styles/modules/_mapnav.scss#L22)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Ok. Make a note of that somewhere, so we don't forget to bring it back.
</details>
Ok noted as a line item in #1241

---

*[src/content/styles/modules/_mapnav.scss, line 13 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFlGj8IwTBg-46az41:-KTFnkSEGVTGyqadJCwT:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_mapnav.scss#L13)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I like the smaller gutter for nav bar :+1: 
</details>
:+1: 

---

*[src/content/styles/modules/_app-menu.scss, line 10 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFk126MNIjHIZcIL1n:-KTFnKRS3UtOflLkuwL6:b27s9zi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_app-menu.scss#L10)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Let's keep the side nav width at 80%, when it takes the full width, it appears as a more permanent component than just a side menu.
</details>
Ok reverted change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KTKJncaEFhaE_NJKMQ_:b1phg7y)*

**Comment by AleksueiR** [comment]
Animation is the correct size now, but it overlaps the main appbar during the transition.

---

Reviewed 3 of 9 files at r3.
Review status: 16 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/content/styles/modules/_content-pane.scss, line 77 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFjJRJZTZzmZL3s49y:-KTKr89PMW3_lar6bBWw:b-1ftsh6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_content-pane.scss#L77)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Changed the arrow position from front to back since there were issues with arrow placement for details panel (wanted to keep back arrow uniform across the panels). Margin seems ok after this change
</details>
Yeah, we need the arrow on the left - it's a very recognizable pattern (also material design says it should be on the left).
What was the problem?

---

*[src/content/styles/modules/_details.scss, line 34 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTKs9IwB6YWuFCaRSof:-KTKs9IwB6YWuFCaRSog:b-at2aj6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fd45f86b59558fddef5e2473985d817f2b43247/src/content/styles/modules/_details.scss#L34)):*
> ```SCSS
>             .md-subhead {
>                 display: block;
> ```

This is a bit random. Is it to make the details subheader look like a header? Better to switch the details panel's floating header to the normal one in the small layout (not sure about the best way to do that though). 

---

*[src/content/styles/modules/_app-menu.scss, line 10 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFk126MNIjHIZcIL1n:-KTKrtp200EALrSrwXnJ:b-y9kcsi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_app-menu.scss#L10)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Ok reverted change
</details>
Set it to 80% for small layouts; it reverts to 256 otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KTKqGsjgMQzQxvOivvp:bx8cgzo)*

**Comment by milesap** [comment]
Fixed overlap during transition

---

Review status: 14 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_app-menu.scss, line 10 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFk126MNIjHIZcIL1n:-KTnhusv8I57zzONdaDi:bud9rrf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_app-menu.scss#L10)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Set it to 80% for small layouts; it reverts to 256 otherwise.
</details>
Ok made the change

---

*[src/content/styles/modules/_content-pane.scss, line 77 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTFjJRJZTZzmZL3s49y:-KTncRL_uC1OHcUMeYF9:brziodv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4e87c9d2df280ac297255e7dcc73a613ec16a087/src/content/styles/modules/_content-pane.scss#L77)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Yeah, we need the arrow on the left - it's a very recognizable pattern (also material design says it should be on the left).
> What was the problem?
</details>
Ok moved arrow to the left. Had trouble with the point information panel since the layer selector would take up the space needed for the arrow. I moved the layer title to make room for the arrow.

---

*[src/content/styles/modules/_details.scss, line 34 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTKs9IwB6YWuFCaRSof:-KTnfNsqyu9bVJWjttV1:b-oprvl4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fd45f86b59558fddef5e2473985d817f2b43247/src/content/styles/modules/_details.scss#L34)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This is a bit random. Is it to make the details subheader look like a header? Better to switch the details panel's floating header to the normal one in the small layout (not sure about the best way to do that though). 
</details>
Removed this formatting - kept same for all screen sizes. Was done originally for small screens since the layer name is the topmost item("point information" text is not shown). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KTncLeSE7y1kHTttnu9:b-4es8za)*

**Comment by milesap** [comment]
Minor element positional/background changes in R6 for point information panel.

---

Review status: 14 of 23 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KToVbQ6qx1RH4EuClWt:bhntne6)*

**Comment by alyec** [comment]
Reviewed 6 of 20 files at r1, 6 of 12 files at r2, 3 of 9 files at r3, 7 of 8 files at r4, 1 of 1 files at r5.
Review status: 20 of 23 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 8 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/layout/_main.scss, line 123 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KToxbaQ4lk21M_mmloC:-KToxbaQ4lk21M_mmloD:b-h3yuea) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/acf0d49cfedbfc96eca9c081916e06ab998990e1/src/content/styles/layout/_main.scss#L123)):*
> ```SCSS
> 
>         @include media($rv-gt-sm...) {
>             border-top: 1px solid $divider-color;
> ```

Why no border on small layouts?

---

*[src/content/styles/modules/_details.scss, line 34 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTKs9IwB6YWuFCaRSof:-KTovUwqXQRlv_ZLzQv3:b-mln8cz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fd45f86b59558fddef5e2473985d817f2b43247/src/content/styles/modules/_details.scss#L34)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Removed this formatting - kept same for all screen sizes. Was done originally for small screens since the layer name is the topmost item("point information" text is not shown). 
</details>
Not sure when this happened, but the details panel now occupies the whole screen when opened by clicking on the map.

In the small layout, the details panel opens inside the main panel (it doesn't overlay it), so it doesn't need the back arrow (it keeps its close button instead):



Same applies to layer/service import (no arrow needed - keep close button).

On the other hand, when the details panel is opened from the datapanel, it overlays the main panel and should have a back arrow instead of the close button.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by milesap** [comment]
Review status: 17 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/layout/_main.scss, line 123 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KToxbaQ4lk21M_mmloC:-KTsrz4u2REKIeZ6zNsi:b-oxntj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/acf0d49cfedbfc96eca9c081916e06ab998990e1/src/content/styles/layout/_main.scss#L123)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Why no border on small layouts?
</details>
Should be included for all layouts - changed.

---

*[src/content/styles/modules/_details.scss, line 34 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KTKs9IwB6YWuFCaRSof:-KTss90vt1Qw3_mGhaPC:bs1u2su) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fd45f86b59558fddef5e2473985d817f2b43247/src/content/styles/modules/_details.scss#L34)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Not sure when this happened, but the details panel now occupies the whole screen when opened by clicking on the map.
> 
> In the small layout, the details panel opens inside the main panel (it doesn't overlay it), so it doesn't need the back arrow (it keeps its close button instead):
> 
> 
> 
> Same applies to layer/service import (no arrow needed - keep close button).
> 
> On the other hand, when the details panel is opened from the datapanel, it overlays the main panel and should have a back arrow instead of the close button.
</details>
Makes sense - made the changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by AleksueiR** [comment]
- Appbar now overlaps the main panel "casting" a shadow  on it:


- In the small layout the separator between the main panel and the appbar disappears during the animation.
- Details panel when opened from the datatable has a different header than the datatable for some reason

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KTtH7_PH6T7d2pAfe0u:bj5233s)*

**Comment by milesap** [comment]
- Not entirely sure this is fixed; I noticed the `top` css property of the main panel was off by 1 pixel, let me know if you're ok with it now
- Fixed; z-index values have been corrected
- The header html is different since there are two possible ways details panel can be rendered on mobile (one for identify, the other by clicking on datatable icon). Resolved this with additional css which brings the header more in line with other headers.

---

Review status: 20 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KTtpMkefaPoaLnvXMo2:b-99fjeh)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by AleksueiR** [comment]
Yeah, shadow is still there. It's likely caused by a change to z-index.

Right, make sense. Would it be better to open details from the datatable in an "expanded" popup (it should take all the screen space)? It has the same header as the datatable (only the close button need to be replaced by an arrow and moved to the left).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KU1xxLnykC2kPkngrxC:b53jfb3)*

**Comment by milesap** [comment]
Good idea - datatable now opens expanded popup dialog for mobile layouts.

The shadow is now gone as some z-index manipulations could be removed as a result.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KU2GODVHvhwmqrbH4IJ:bi4qv97)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 8 files at r4, 3 of 7 files at r7, 2 of 4 files at r8, 3 of 5 files at r10.
Review status: 25 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 19 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KU2RKK4bMeg-DkuoTm-:-KU2RKK4bMeg-DkuoTm0:b-72mbex) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ff1d6165a3e8e365b3540dc8d434f1464a08e782/src/app/ui/filters/filters-default.directive.js#L19)):*
> ```JavaScript
>             }
>         },
>         // for small layouts - opens detail panel as a dialog
> ```

Looks good now, just need to fix some duplication. Instead of cloning a details button, we can determine the size of the current layout in code as well (`$rootElement.width` should work for that), so you can just do something like:
```js
ROW_BUTTONS.details.self.action = row =>
    switch(layoutService.currentLayout) {
         case 'small':
              onDetailsClick(row, true);
         case 'large':
              onDetailsClick();
};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by milesap** [comment]
Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 19 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KU2RKK4bMeg-DkuoTm-:-KU2dM2ZvSxoYNvmnp7s:b-p1katl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ff1d6165a3e8e365b3540dc8d434f1464a08e782/src/app/ui/filters/filters-default.directive.js#L19)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Looks good now, just need to fix some duplication. Instead of cloning a details button, we can determine the size of the current layout in code as well (`$rootElement.width` should work for that), so you can just do something like:
> ```js
> ROW_BUTTONS.details.self.action = row =>
>     switch(layoutService.currentLayout) {
>          case 'small':
>               onDetailsClick(row, true);
>          case 'large':
>               onDetailsClick();
> };
> ```
</details>
:+1: changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by AleksueiR** [comment]
Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 19 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-KU2RKK4bMeg-DkuoTm-:-KU2qqrQ4ONdqjflh18h:b-acownm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ff1d6165a3e8e365b3540dc8d434f1464a08e782/src/app/ui/filters/filters-default.directive.js#L19)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> :+1: changed
</details>
Great :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253#-:-KU2r4uvbAm6JmSt8Ddb:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 3 of 5 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1253)*

**Pull request merged**
