### PR TITLE
fix(ui): show visibility tooltip

### LINKED ISSUE #599: bug(ui): visibility tooltip is broken
Visibility toolitp doesn't display the proper string.

### PR DESCRIPTION
**Pull request by milesap**
Closes #599

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/642)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Please sync your branch.

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/templates/entry-control-button.html, line 9 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642#-KIQC8HVYV-oh3nSDRPQ:-KIQC8HVYV-oh3nSDRPR:1882352755) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/959a364019977907d4449cdc5471db2fa0e0d621/src/app/ui/toc/templates/entry-control-button.html#L9)):*
> ```HTML
>     rv-help="{{ self.option }}">
> 
>     <md-tooltip md-direction="top">{{ self.template.label[self.control.value ? 'on' : 'off'] || self.template.label | translate }}</md-tooltip>
> ```

There may be other label values apart from `on` and `off`. This is an abstract template which is supposed to work with any legend toggle, and using specific values like can break something in the future. 

To keep it abstract, we probaly need to change [label presets](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/toc/toc.service.js#L66) (if there are more than one) from objects to functions, similar to how the icon preset for the visibility toggle is now a function. Below there is a check if `icon` is a function or not.

---

*[src/app/ui/toc/templates/entry-control-button.html, line 13 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642#-KIQF09I4QBOl-pz1szP:-KIQF09JW9LDRGx5FWAv:1117482741) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/959a364019977907d4449cdc5471db2fa0e0d621/src/app/ui/toc/templates/entry-control-button.html#L13)):*
> ```HTML
>          https://github.com/angular/angular.js/pull/6886
>     -->
>     <md-icon md-svg-src="{{ self.template.icon.call ? self.template.icon(self.control.value) : self.template.icon }}"></md-icon>
> ```

BTW: @alyec, Aly, I think a less terrible way would be to dump the `angular.isFunction` function to the scope and use that:
in directive:
```js
self.isFunction = angular.isFunction;
```

in template:
```js
{{ self.isFunction(self.template.icon) ? self.template.icon(self.control.value) : self.template.icon }}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642)*

**Comment by milesap** [comment]
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Please sync your branch.
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/templates/entry-control-button.html, line 9 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642#-KIQC8HVYV-oh3nSDRPQ:-KIbqKAQFhV5T9MiSTYB:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/959a364019977907d4449cdc5471db2fa0e0d621/src/app/ui/toc/templates/entry-control-button.html#L9)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> There may be other label values apart from `on` and `off`. This is an abstract template which is supposed to work with any legend toggle, and using specific values like can break something in the future. 
> 
> To keep it abstract, we probaly need to change [label presets](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/toc/toc.service.js#L66) (if there are more than one) from objects to functions, similar to how the icon preset for the visibility toggle is now a function. Below there is a check if `icon` is a function or not.
</details>
:+1: 

---

*[src/app/ui/toc/templates/entry-control-button.html, line 13 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642#-KIQF09I4QBOl-pz1szP:-KIbqH5gExyK4ssD-9db:1608351537) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/959a364019977907d4449cdc5471db2fa0e0d621/src/app/ui/toc/templates/entry-control-button.html#L13)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> BTW: @alyec, Aly, I think a less terrible way would be to dump the `angular.isFunction` function to the scope and use that:
> in directive:
> ```js
> self.isFunction = angular.isFunction;
> ```
> 
> in template:
> ```js
> {{ self.isFunction(self.template.icon) ? self.template.icon(self.control.value) : self.template.icon }}
> ```
</details>
Sounds good to me, implemented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642#-:-KIbqLuusaCcF0xLDHd5:122088356)*

**Comment by cynngah** [comment]
Reviewed 3 of 4 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642)*

**Comment by cynngah** [comment]
Reviewed 2 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/642)*

**Pull request merged**
