### PR TITLE
feat(ui): i18n support for toc

### PR DESCRIPTION
**Pull request by james-rae**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/340)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/layer-item-flag.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340#-KApgQIvqXBFy8LKOEcR:-KApgQIvqXBFy8LKOEcS:498532568) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/57ef14323ba83f54a366595a5ef9d22bfb82fcef/src/app/ui/toc/layer-item-flag.html#L1)):*
trailing space?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340)*

**Comment by AleksueiR** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340)*

**Comment by james-rae** [comment]
*[src/app/ui/toc/layer-item-flag.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340#-KApgQIvqXBFy8LKOEcR:-KApiRqZzCt9mcFZDFco:-945269916) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/57ef14323ba83f54a366595a5ef9d22bfb82fcef/src/app/ui/toc/layer-item-flag.html#L1)):*
suprised the `gulp test` didn't bark at me

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340)*

**Comment by spencerwahl** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340)*

**Comment by alyec** [comment]
What percentage gains did you see?  We need some graphs.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/layer-item-flag.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340#-KApgQIvqXBFy8LKOEcR:-KApj4TPHm6vw5yW5zNc:-228340492) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/57ef14323ba83f54a366595a5ef9d22bfb82fcef/src/app/ui/toc/layer-item-flag.html#L1)):*
I don't think we have anything that looks at HTML fragments

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340#-:-KApjG4mxWB8m16n3pcY:248299870)*

**Comment by james-rae** [comment]
---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340#-:-KApkA5Tw3kzDkAh3CWc:-1336945602)*

**Comment by alyec** [comment]
There is no emoji to express how impressed I am.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/340#-:-KApkdackai_HiKP2PqQ:-780210200)*

**Pull request merged**
