### PR TITLE
Zoom to feature on select

### LINKED ISSUE #344: feat(core): datatable zoom to feature
Port existing functionality from RAMP

Traceability Matrix ID#024

### PR DESCRIPTION
**Pull request by cynngah**
closes #344

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/350)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 84 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBE7dRgppjJkc-qQ6y_:-KBE7dRgppjJkc-qQ6ya:1817668676) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f2bcda806bea2b6215ea7addd33abd4fe4bbb59/src/app/ui/filters/filters-default.directive.js#L84)):*
Why do we need to change it? What's bad about `select`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 486 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBE6wehPm9qrz1N5gTI:-KBE6wehPm9qrz1N5gTJ:-1963177975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f2bcda806bea2b6215ea7addd33abd4fe4bbb59/src/app/geo/geo.service.js#L486)):*
Are we planning to add zoomTo for dynamic layers?  (WMSes will never work because they don't expose geometry)

Also, add jsdoc annotations.

---

*[src/app/ui/filters/filters-default.directive.js, line 89 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBE7M4hzejf8Fm80UiA:-KBE7M4hzejf8Fm80UiB:1619506117) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f2bcda806bea2b6215ea7addd33abd4fe4bbb59/src/app/ui/filters/filters-default.directive.js#L89)):*
Minor issue, you can clean up the repeated parts of the URL construction:
```js
let layerUrl = geoService.layers[layerId].layer.url + '/';
if (geoService.layers[layerId].layer.layerInfos) {
  layerUrl += featureIndex + '/';
}

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*
<!-- Sent from Reviewable.io -->

**Comment by james-rae** [comment]
*[src/app/geo/geo.service.js, line 486 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBE6wehPm9qrz1N5gTI:-KBEAJodneGy7a_NtrYs:1863992676) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f2bcda806bea2b6215ea7addd33abd4fe4bbb59/src/app/geo/geo.service.js#L486)):*
we have the supporting functions to allow dynamic layer.  it currently doesn't work because the table of contents is not grabbing the correct grids / indexes.  comment should be marked as `FIXME`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by cynngah** [comment]
*[src/app/ui/filters/filters-default.directive.js, line 84 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBE7dRgppjJkc-qQ6y_:-KBEIEbAFrKPwL-kCsuV:-1704501778) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f2bcda806bea2b6215ea7addd33abd4fe4bbb59/src/app/ui/filters/filters-default.directive.js#L84)):*
We don't have to, but I thought maybe you'd want it for metadata

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by cynngah** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 89 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBE7M4hzejf8Fm80UiA:-KBEKO5gdXiv1m_FpPmk:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f2bcda806bea2b6215ea7addd33abd4fe4bbb59/src/app/ui/filters/filters-default.directive.js#L89)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 84 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBE7dRgppjJkc-qQ6y_:-KBEKcHa-3L2rqx7NIzb:-358647971) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f2bcda806bea2b6215ea7addd33abd4fe4bbb59/src/app/ui/filters/filters-default.directive.js#L84)):*
Metadata? Not sure I follow.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 86 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBENGurRTYmQRoXxYmH:-KBENGurRTYmQRoXxYmI:-494494541) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/56f483a950806f5f01b2fd8e1c9c722247659273/src/app/ui/filters/filters-default.directive.js#L86)):*
This looks like we are assuming the object id is the first column?  If so, we might want a FIXME comment to change to a more robust solution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by james-rae** [comment]
Reviewed 2 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by cynngah** [comment]
*[src/app/ui/filters/filters-default.directive.js, line 86 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350#-KBENGurRTYmQRoXxYmH:-KBIoW4xPajEVoV2Wu_h:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/56f483a950806f5f01b2fd8e1c9c722247659273/src/app/ui/filters/filters-default.directive.js#L86)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Comment by ec-dev** [comment]
Reviewed 2 of 4 files at r1, 2 of 11 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/350)*

**Pull request merged**
