### PR TITLE
add gulp-i18n-csv to the build

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/99)

### CODE REVIEW

**Comment by cynngah** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[gulpfile.js, line 16 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99#-K5aSRexkLWeHnuzTweY:-K5aSRexkLWeHnuzTweZ:934823860) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c2e7ac060c0a9d77cb7bd77688c44ec8ca8786e5/gulpfile.js#L16)):*
Probably no need to do this. Check if `gulp-load-plugins` loads it.

---

*[gulpfile.js, line 172 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99#-K5aS3S4gdQUreMEE3zS:-K5aS3S4gdQUreMEE3zT:1268760725) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c2e7ac060c0a9d77cb7bd77688c44ec8ca8786e5/gulpfile.js#L172)):*
Try using `.pipe($.i18nCsv())`.  `$` is `gulp-load-plugins` which lazy-loads gulp plugins (plugins starting with `gulp-`).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99)*

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99)*

**Comment by spencerwahl** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[gulpfile.js, line 16 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99#-K5aSRexkLWeHnuzTweY:-K5aVNuYqlfG_v_Q1rQk:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c2e7ac060c0a9d77cb7bd77688c44ec8ca8786e5/gulpfile.js#L16)):*
Done.

---

*[gulpfile.js, line 172 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99#-K5aS3S4gdQUreMEE3zS:-K5aVNeJHJJbrBXswtrM:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c2e7ac060c0a9d77cb7bd77688c44ec8ca8786e5/gulpfile.js#L172)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99)*

**Comment by cynngah** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99)*

**Comment by AleksueiR** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/99#-:-K5ekOQcxfSJ2U3qHm9F:980077423)*

**Pull request merged**
