### PR TITLE
Zoom to Feature support for client side data

### LINKED ISSUE #445: Zoom to Feature support for client side data
Allow file based data to support Zoom to Feature.  Geometry for zoom to currently relies on the server response for each feature selected.  Once done, extend this approach to feature layers for efficiency.

- [x] Detect if layer is feature-based and not on-demand
- [x] Obtain object id from grid, `layerData.oidField` from layer bundle
- [x] Use approach [similar to RAMP](https://github.com/RAMP-PCAR/RAMP-PCAR/blob/master/src/js/RAMP/Modules/graphicExtension.js#L182) to find feature in layer
- [x] Use feature's geometry rather than a server call to determine the zoom location

### PR DESCRIPTION
**Pull request by cynngah**
Also refactored the offset part out into a separate function

Closes #445

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/628)

### CODE REVIEW

**Comment by james-rae** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 299 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI3ZziEH6y7SyT-8gGP:-KI3ZziEH6y7SyT-8gGQ:-1578198069) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c7ecf25acd0b081d3cf0c8d182df47ccf8a4ffa5/src/app/geo/map.service.js#L299)):*
> ```JavaScript
> 
>                 // snapshot mode is set by the constant MODE_SNAPSHOT that maps to 0 in esri's api for FeatureLayer
>                 if (!layer.url || layer.mode === 0) {
> ```

Comment explaining what is going on here.  E.g. "Layer has no service, or all geometry is on client. Use local geometry"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/map.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI3_J8SsIdpjLqE427m:-KI3_J8SsIdpjLqE427n:-332467152) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c7ecf25acd0b081d3cf0c8d182df47ccf8a4ffa5/src/app/geo/map.service.js#L288)):*
> ```JavaScript
>             }
> 
>             // only handles feature layers right now (both on demand and snapshot). zoom to dynamic/wms layers obj won't work
> ```

Can you move this inside the jsdoc as a note / warning?

---

*[src/app/geo/map.service.js, line 336 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI3_Px5AtMRsJO9pMkS:-KI3_Px5AtMRsJO9pMkT:-2146829802) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c7ecf25acd0b081d3cf0c8d182df47ccf8a4ffa5/src/app/geo/map.service.js#L336)):*
> ```JavaScript
>              * to the map's spatialReference, then zooms to the maximum level such that the geometry is still visible
>              *
>              * @param  {geo} geo is the geometry to be zoomed to
> ```

geo, attr, sr and zoomLevel are not types.  For jsdoc you are probably looking for `{Object}` in most cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by cynngah** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/map.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI3_J8SsIdpjLqE427m:-KI3q-tvfWz4XTTzrlQE:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c7ecf25acd0b081d3cf0c8d182df47ccf8a4ffa5/src/app/geo/map.service.js#L288)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you move this inside the jsdoc as a note / warning?
</details>
Done.

---

*[src/app/geo/map.service.js, line 299 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI3ZziEH6y7SyT-8gGP:-KI3q-H_e1C8FYufoyDR:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c7ecf25acd0b081d3cf0c8d182df47ccf8a4ffa5/src/app/geo/map.service.js#L299)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Comment explaining what is going on here.  E.g. "Layer has no service, or all geometry is on client. Use local geometry"
</details>
Done.

---

*[src/app/geo/map.service.js, line 336 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI3_Px5AtMRsJO9pMkS:-KI3pzj3-S4ZfBEaYVJ7:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c7ecf25acd0b081d3cf0c8d182df47ccf8a4ffa5/src/app/geo/map.service.js#L336)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> geo, attr, sr and zoomLevel are not types.  For jsdoc you are probably looking for `{Object}` in most cases.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/map.service.js, line 322 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI7l2aJKIwJ01KJqOvr:-KI7l2aJKIwJ01KJqOvs:-1116091464) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1da07c45e53be5e790264404dc4860543d1e1ade/src/app/geo/map.service.js#L322)):*
> ```JavaScript
> 
>                     // FIXME: support file based layers with no url
>                     const geo = gapiService.gapi.layer.getFeatureInfo(layerUrl, objId);
> ```

Since `geo` doesn't seem to be used anywhere, you can rewrite this as 
```js
gapiService.gapi.layer.getFeatureInfo(layerUrl, objId)
    .then(geoInfo => { 
        ... 
    });
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 322 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-KI7l2aJKIwJ01KJqOvr:-KI8B0m0Zt7IN_MV1LOb:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1da07c45e53be5e790264404dc4860543d1e1ade/src/app/geo/map.service.js#L322)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Since `geo` doesn't seem to be used anywhere, you can rewrite this as 
> ```js
> gapiService.gapi.layer.getFeatureInfo(layerUrl, objId)
>     .then(geoInfo => { 
>         ... 
>     });
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Comment by AleksueiR** [comment]
:lgtm: 

<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> #### Zoom to Feature support for client side data
> 
> Also refactored the offset part out into a separate function
> 
> 
> 
> Closes #445
> 
> 
> 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628#-:-KI8BfSHP6NlU0Ln2_wj:980077423)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/628)*

**Pull request merged**
