### PR TITLE
Legend schema

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/288)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Can you also add a legend config sample? 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288#-K9gmL4FXtrdGUqW3FIr:-K9gmL4FXtrdGUqW3FIs:549601394) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c6ff31b46b941e670555303415ecf6c37a8223c/src/schema.json#L269)):*
Why use `enum` if there is always only once item?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288#-:-K9gn4C-n6H2AKlXGwF-:-1822885033)*

**Comment by alyec** [comment]
Probably in a separate step, for now I wanted to get the schema working which was painful enough.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288#-K9gmL4FXtrdGUqW3FIr:-K9gnTy75o_aluTIMN02:2079899164) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c6ff31b46b941e670555303415ecf6c37a8223c/src/schema.json#L269)):*
So it can coexist with the `structured` entry in the other definition

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288#-:-K9gnar-MPF3lWjZWkKX:939755805)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288#-K9gmL4FXtrdGUqW3FIr:-K9gsDaYlVILq3IC4X84:-1470717263) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c6ff31b46b941e670555303415ecf6c37a8223c/src/schema.json#L269)):*
I don't think I understand. Why does it need to coexist? The legend can be either structured or not.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288#-K9gmL4FXtrdGUqW3FIr:-K9gsfMJ3MjmbqQ_45Kr:161721018) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c6ff31b46b941e670555303415ecf6c37a8223c/src/schema.json#L269)):*
I want both entries to have a `type` property.  I only want `autopopulate` and `structured` as valid entries.  Each one should not overlap with the value of the other one (otherwise auto would be a subset of structured and cause validation issues) so each one is an enum of length one and when combined they form the complete list of accepted values.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288#-K9gmL4FXtrdGUqW3FIr:-K9gvCYE1FVZttw8fBaF:1491535840) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c6ff31b46b941e670555303415ecf6c37a8223c/src/schema.json#L269)):*
Thanks for explaining. :+1: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/288)*

**Pull request merged**
