### PR TITLE
Layer attribute loading

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/232)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 215 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8QOmwX3G86YqIL4p0v:-K8QOmwYkHV0_HWn7Rar:277950859) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/171880f9ddeb8e27aed5d9b0adc020b08da4b03a/src/app/geo/geo.service.js#L215)):*
Use `.error()` instead of a second arg to `.then()`.  Mostly for readability.

---

*[src/app/geo/geo.service.js, line 217 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8QPsiipFy8JYazRrjc:-K8QPsiipFy8JYazRrjd:1539026120) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/171880f9ddeb8e27aed5d9b0adc020b08da4b03a/src/app/geo/geo.service.js#L217)):*
console.log probably doesn't work exactly as you think it does: https://developer.mozilla.org/en-US/docs/Web/API/Console/log

---

*[src/app/geo/geo.service.spec.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8QQRqRrdqp6xpErOAO:-K8QQRqSavY9vPpsTA7M:1187007711) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/171880f9ddeb8e27aed5d9b0adc020b08da4b03a/src/app/geo/geo.service.spec.js#L143)):*
add a comment about why this is disabled

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by spencerwahl** [comment]
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 215 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8QOmwX3G86YqIL4p0v:-K8QVyXJ4qo09CO9W3s7:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/171880f9ddeb8e27aed5d9b0adc020b08da4b03a/src/app/geo/geo.service.js#L215)):*
Done.

---

*[src/app/geo/geo.service.js, line 217 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8QPsiipFy8JYazRrjc:-K8QVq7mWa9wBqv39VWd:-1594250195) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/171880f9ddeb8e27aed5d9b0adc020b08da4b03a/src/app/geo/geo.service.js#L217)):*
I wasn't too far off... sort of...

...done.

---

*[src/app/geo/geo.service.spec.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8QQRqRrdqp6xpErOAO:-K8QVzT_1za3c096rMal:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/171880f9ddeb8e27aed5d9b0adc020b08da4b03a/src/app/geo/geo.service.spec.js#L143)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/geo/geo.service.js, line 217 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8QPsiipFy8JYazRrjc:-K8QXowIBbN7MMRDQS7g:-451094949) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/171880f9ddeb8e27aed5d9b0adc020b08da4b03a/src/app/geo/geo.service.js#L217)):*
It's a horrible overload.  I just try to catch them so it doesn't come back at some point when you are debugging in IE and the console log doesn't work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by AleksueiR** [comment]
Reviewed 11 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/geo.service.spec.js, line 144 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8U1BKEmR-P8TkrYBuy:-K8U1BKEmR-P8TkrYBuz:33733967) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e5dbc973094dc8833767e5f717a7ce55ae05bd79/src/app/geo/geo.service.spec.js#L144)):*
Add `TODO` to the comment to make it easier to find in the future.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by spencerwahl** [comment]
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.spec.js, line 144 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8U1BKEmR-P8TkrYBuy:-K8V8ABeiN1_c451Gtk8:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e5dbc973094dc8833767e5f717a7ce55ae05bd79/src/app/geo/geo.service.spec.js#L144)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 116 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8V8Y6DO6RjD5Kti2z-:-K8V8Y6DO6RjD5Kti2z0:-2111295818) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/063af128ba2431f4be765ea523619e2b81fb3988/src/app/geo/geo.service.js#L116)):*
`featureIndex` missing from the function comment block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 116 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8V8Y6DO6RjD5Kti2z-:-K8VA3KVceO864DDFXXA:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/063af128ba2431f4be765ea523619e2b81fb3988/src/app/geo/geo.service.js#L116)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/app/geo/geo.service.js, line 116 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8V8Y6DO6RjD5Kti2z-:-K8VAlakHQmhLcMN-L8u:-652911688) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/063af128ba2431f4be765ea523619e2b81fb3988/src/app/geo/geo.service.js#L116)):*
Out of curiosity, isn't this one of the things our build checks for?

---

*[src/app/geo/geo.service.js, line 111 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8VB1ljrTNNhDU5zpnF:-K8VB1ljrTNNhDU5zpnG:369470632) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5ea75fa3cb25500b1390f0f466785d2198596692/src/app/geo/geo.service.js#L111)):*
This should either throw an error if it can't find the layer / attributes, or the behaviour if data is not found should be documented.  And I'd push strongly for a thrown error unless there is a good use case for the alternative.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by james-rae** [comment]
Reviewed 9 of 12 files at r1, 3 of 4 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 123 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8VFPxj06fizwWRgtW8:-K8VFPxk7c5m2oBqZL--:1189715593) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2df280f624e9ab7bd47bdf0959dd35ae340f9d9/src/app/geo/geo.service.js#L123)):*
Might want another level of error check (can come later).  It's possible for .attribs to not be defined.

---

*[src/app/geo/geo.service.js, line 149 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8VFdhqqpczeZ4_N31f:-K8VFdhrPCiNqX7Et_Vd:-271398909) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2df280f624e9ab7bd47bdf0959dd35ae340f9d9/src/app/geo/geo.service.js#L149)):*
Excellent in-line commenting in this function.  Easy to follow what is happening

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 111 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8VB1ljrTNNhDU5zpnF:-K8VWsx5xIuQxxF0OmtD:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5ea75fa3cb25500b1390f0f466785d2198596692/src/app/geo/geo.service.js#L111)):*
Done.

---

*[src/app/geo/geo.service.js, line 123 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232#-K8VFPxj06fizwWRgtW8:-K8VWtkrn-of9a-g8dM1:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2df280f624e9ab7bd47bdf0959dd35ae340f9d9/src/app/geo/geo.service.js#L123)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/232)*

**Pull request merged**
