### PR TITLE
fix(ui): Improve help section text

### LINKED ISSUE #1521: Help Document should be updated to include Export feature
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-3/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

While testing daily build for resolved issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1444, searching key word "Export" will return "Nothing is found". It is suggested Export should be added in Help.

image

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1521, #1522, #1523

## Testing
👁 

## Documentation
None needed

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1567)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm:  Changes look good.

Since we are updating help, new functionality like `reorder`, `expand/collapse all`, `hide/show all` are not explained. Should this be a separate issue?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/locales/translations.csv, line 306 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-Ka8Um9eg2mNrB8qJUXa:-Ka8Um9eg2mNrB8qJUXb:b-amrk1l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/baf3e00e5a4733024e98cb1c81055af7f24e7eea/src/locales/translations.csv#L306)):*
> ```CSV
> * Menu : Cliquez sur 'Menu' pour afficher le menu déroulant. Cliquez en dehors du menu déroulant pour le fermer"
> ,help.fullScreen.header,Full Screen,Plein écran
> ,help.fullScreen.info,"Full Screen is used to collapse the departmental headers and footers to provide larger screen space for mapping.<br>
> ```

Not directly related to this PR, but `full screen` description seems to specific and assumes R2 is running inside a template. Can we reword this saying something like `"Full screen presents map content using the entire page. Full screen option is only available when the map is embedded into another page." `?

---

*[src/locales/translations.csv, line 329 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-Ka8aWvul_8CuC4FXMyI:-Ka8aWvul_8CuC4FXMyJ:bwjxzu0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/baf3e00e5a4733024e98cb1c81055af7f24e7eea/src/locales/translations.csv#L329)):*
> ```CSV
> Utilisation:<br>
> 'Aide' : Cliquez sur l'option 'Aide' pour afficher une fenêtre et voir ce texte d'aide"
> ,help.legend.header,Legend,Legend
> ```

This one should be "Layers", not "Legend"; and below as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-:-Ka8WYcCCLtMyVBBwk9X:b-1zixx3)*

**Comment by milesap** [comment]
A separate issue would be best, there's likely a lot of sections that need to be added/updated.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/locales/translations.csv, line 306 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-Ka8Um9eg2mNrB8qJUXa:-KaCe470qLi-uO0GrYM-:b91xrt5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/baf3e00e5a4733024e98cb1c81055af7f24e7eea/src/locales/translations.csv#L306)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Not directly related to this PR, but `full screen` description seems to specific and assumes R2 is running inside a template. Can we reword this saying something like `"Full screen presents map content using the entire page. Full screen option is only available when the map is embedded into another page." `?
</blockquote></details>

Ok updated the description

---

*[src/locales/translations.csv, line 329 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-Ka8aWvul_8CuC4FXMyI:-KaCh7Ye_P46k7mgF1oM:bcxcw9h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/baf3e00e5a4733024e98cb1c81055af7f24e7eea/src/locales/translations.csv#L329)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This one should be "Layers", not "Legend"; and below as well.
</blockquote></details>

Ok changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-:-KaCcJkv4u9jX676RQ3t:b-ga4os)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-:-KaCmgHBoagAg5YeeGGr:bnfp4nl)*

**Comment by AleksueiR** [comment]
:lgtm: 
Created a separate issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1568

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567#-:-KaCnI4KsDnzoDrEP89x:b-g9j40r)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1567)*

**Pull request merged**
