### PR TITLE
Small UI layout update

### PR DESCRIPTION
**Pull request by AleksueiR**
Added states to appbar buttons (default, hover, and selected);
resized side panel down to match the height of the main panel;
added options to specify the title size in content panes;
made content pane transition faster and less jarring;

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/19)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 5 of 6 files at r1, 12 of 12 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/19)

**Comment by alyec** [comment]
are we still calling layers "Sets"?


---

Reviewed 5 of 6 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/appbar/appbar.controller.js, line 25 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/19#-K-cuK61cNcsz_zXmj5o)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/282cbc1412fdf848ee82c14791db38c5489f1289/src/app/ui/appbar/appbar.controller.js#L25)):</sup>
maybe use FIXME for stuff that needs changing, unless you don't think we'll be able to get to it for a while


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/19)

**Comment by AleksueiR** [comment]
In code? I guess, not. Should be `toc` now, to match the ui component's name. Will change that as well. 


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/appbar/appbar.controller.js, line 25 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/19#-K-cuK61cNcsz_zXmj5o)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/282cbc1412fdf848ee82c14791db38c5489f1289/src/app/ui/appbar/appbar.controller.js#L25)):</sup>
Good idea, I'll do that.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/19)

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/19)

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/19)

**Pull request merged**
