### PR TITLE
feat(core,ui,locales): french toasts and french msg in toc

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
1- toast messages are now manage by translate service
2- use translate service inside placeholder-entry.html
3- add entries in translations.csv accordingly

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/837)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/core/config.service.js, line 126 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837#-KLGoWFoEs56jCdtzn8h:-KLGoWFoEs56jCdtzn8i:-1185656289) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab9b68cfa56106d5f04710bac659a81300445b8a/src/app/core/config.service.js#L126)):*
> ```JavaScript
>                                 console.warn('RCS failed, starting app with file-only config.');
>                                 const toast = $mdToast.simple()
>                                     .textContent($translate.instant('config.service.rcs.error', lang))
> ```

Don't really need a `lang` parameter here. `$translate` will use the current language by default.

---

*[src/app/ui/toc/toc.service.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837#-KLGn7yUjVhmV6ndkeqW:-KLGn7yUjVhmV6ndkeqX:1921915672) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab9b68cfa56106d5f04710bac659a81300445b8a/src/app/ui/toc/toc.service.js#L194)):*
> ```JavaScript
>             // create notification toast
>             const undoToast = $mdToast.simple()
>                 .textContent($filter('translate')('toc.label.state.remove'))
> ```

Why not use `$translate.instant('toc.label.state.remove')`? It should be faster than creating a filter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837#-:-KLIC4nj2_IaXAyiO-6J:1417088721)*

**Comment by alyec** [comment]
Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837)*

**Comment by ChrisLatRNCan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 126 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837#-KLGoWFoEs56jCdtzn8h:-KLRQOLFVnHgVATrAedA:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab9b68cfa56106d5f04710bac659a81300445b8a/src/app/core/config.service.js#L126)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Don't really need a `lang` parameter here. `$translate` will use the current language by default.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/837)*

**Pull request merged**
