### PR TITLE
feat(core): load esri api from custom location

### LINKED ISSUE #2654: Import ESRI API from custom location
Currently we load the ESRI API from ```dojoURL: '//js.arcgis.com/3.20/'```. It would be a good thing if we can customize the url from the schema so that we can host the api ourselves. It will solve some bugs we had with NRCan network and ESRI api site.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2654

## Testing

Chrome

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq and @james-rae)

---

*[src/app/core/config.service.js, line 318 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816#-LGUpc0V74x6vAJRSAPi:-LGUpc0V74x6vAJRSAPj:br94ao6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0137982ebfdbf8e4f33e1d6e12e81c71b6f9e32f/src/app/core/config.service.js#L318)):*
> ```JavaScript
>                  defConfigAttr = generateDefaultConfig(lang.slice(0,2));
>             }
>             configList.push(new Config(configAttr || defConfigAttr, svcAttr, lang));
> ```

Would this try to load esriLib again if you load a new config file?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816)*

**Comment by james-rae** [comment]
*[src/content/samples/index-samples.tpl, line 163 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816#-LGVmQmA69EC5BrmbdLi:-LGVmQmB5ZRo_EjsUKC4:b-v7z8ul) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0137982ebfdbf8e4f33e1d6e12e81c71b6f9e32f/src/content/samples/index-samples.tpl#L163)):*
> ```Smarty
>                 <option value="">67. Map with no config provided</option>
>                 <option value="config/config-sample-68.json">68. WFS layer defined in config</option>
>                 <option value="config/config-sample-69.json">69. Custom ESRI API location</option>
> ```

Another recent PR added a #69 file.  Can you rename to 71?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816)*

**Comment by AleksueiR** [comment]
Review status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @AleksueiR and @james-rae)

---

*[src/app/core/config.service.js, line 318 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816#-LGUpc0V74x6vAJRSAPi:-LG_TnguAMSI84d9EE4o:bil7lsv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0137982ebfdbf8e4f33e1d6e12e81c71b6f9e32f/src/app/core/config.service.js#L318)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

> ```
> // load first config, other configs will be loaded as needed
> ```
Doesn't looks like. When we switch to another config (another file), gapiService is always null. When we switch language it doesn't go through this function.
</blockquote></details>

Sounds good. Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816)*

**Pull request merged**
