### PR TITLE
feat(ui): layer tree updates

### PR DESCRIPTION
**Pull request by AleksueiR**
Submitting PR before it gets too large:

- adds layer items
- adds templating (icons, tooltips, labels, and click actions) for layer toggles and flags

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/68)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/app/ui/common/morph.directive.spec.js, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NM82cSVZL6XT7ks2x)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/common/morph.directive.spec.js#L3)):</sup>
Why don't you use the arrow notation here and in the beforeEach below?


---

<sup>**[src/app/ui/mapnav/mapnav.service.spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NMijJ8Sz8UGiekb9n)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/mapnav/mapnav.service.spec.js#L11)):</sup>
Why do you use sometime angular.mock.module (shell.controller.spec.js) and sometime bard.appModule?


---

<sup>**[src/app/ui/toc/layer-item.html, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NV-aIv1T4ixtMmVOC)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/toc/layer-item.html#L2)):</sup>
Spaces after and before curly brackets


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

<sup>**[src/app/ui/common/morph.directive.spec.js, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NM82cSVZL6XT7ks2x)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/common/morph.directive.spec.js#L3)):</sup>
Missed this one. Thanks.


---

<sup>**[src/app/ui/mapnav/mapnav.service.spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NMijJ8Sz8UGiekb9n)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/mapnav/mapnav.service.spec.js#L11)):</sup>
`bard.appModule` disables routing services, so you can't use it when testing components using routing as in `ShellController` for example. Need to use `angular.mock.module` for that.


---

<sup>**[src/app/ui/toc/layer-item.html, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NV-aIv1T4ixtMmVOC)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/toc/layer-item.html#L2)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by jolevesq** [comment]
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/mapnav/mapnav.service.spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NMijJ8Sz8UGiekb9n)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/mapnav/mapnav.service.spec.js#L11)):</sup>
Ok, so it is because layout use route in layout.route.js?  For app.ui you could have use bard because it is not using routing?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by AleksueiR** [comment]
Review status: 14 of 16 files reviewed at latest revision, all discussions resolved.

---

<sup>**[src/app/ui/mapnav/mapnav.service.spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2NMijJ8Sz8UGiekb9n)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c28adf3b79b86130d12c62fe3324cca2ca8649a4/src/app/ui/mapnav/mapnav.service.spec.js#L11)):</sup>
Yes, for most of the `app.ui` components, we can use bard if routing is not used.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by ec-dev** [comment]
Reviewed 7 of 16 files at r1, 1 of 2 files at r2.
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by ec-dev** [comment]
Reviewed 6 of 16 files at r1, 1 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by ec-dev** [comment]
Reviewed 1 of 16 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by alyec** [comment]
Reviewed 13 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/toc/layer-item.html, line 8 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2iN9YBj51rNRv7VLRD)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8aca3e1d59f04402fd65fc165fc8e053e5ef4590/src/app/ui/toc/layer-item.html#L8)):</sup>
do we create all flags for all layers up front in this case?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/toc/layer-item.html, line 8 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2iN9YBj51rNRv7VLRD)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8aca3e1d59f04402fd65fc165fc8e053e5ef4590/src/app/ui/toc/layer-item.html#L8)):</sup>
Yes, I feel it's easier to declare everything upfront than dynamically generate from some template. `ng-if` is used to hide unused flags so they don't add to the size of the html page.
Do you think it would be better to generate the markup or is this approach good enough?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by alyec** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/toc/layer-item.html, line 8 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68#-K2iN9YBj51rNRv7VLRD)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8aca3e1d59f04402fd65fc165fc8e053e5ef4590/src/app/ui/toc/layer-item.html#L8)):</sup>
Works for me, but it's fairly different than what I thought would be happening (basically a directive that just consumed an array of flags).  Maybe more docs would help (not sure if that needs to be code level or something we can pull into a separate doc).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Comment by james-rae** [comment]
Reviewed 14 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/68)

**Pull request merged**
