### PR TITLE
Feat/toastonloadfailure

### LINKED ISSUE #564: Add error message to datatable if attribute fail to load
There is no message or any visible indication that attribute loading failed.

If a user opens a datatable and loading fails, he can wait a long time not realizing nothing is happening anymore.

Maybe we can also retrying to load attributes on fail.

### PR DESCRIPTION
**Pull request by milesap**
Original PR #601, switched working environments and somehow ended up with a new branch name! Toast appears on bottom of panel.

Closes #564, #591

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/646)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Please sync your branch.

**Comment by milesap** [comment]
Please merge #636 first then this (other is synced)

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Please sync your branch.
</details>


---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/646#-:-KIZ4U5WJVH9vw587Nb_:-955786063)*

**Comment by milesap** [comment]
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Please merge #636 first then this (other is synced)
</details>


---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/646#-:-KIbjKZydXqLLHd4y8Oq:-695601899)*

**Comment by cynngah** [comment]
Reviewed 3 of 10 files at r1, 1 of 5 files at r3, 1 of 3 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/646)*

**Pull request merged**
