### PR TITLE
feat(ui): add individual loading indicators for each layer in details panel

### PR DESCRIPTION
**Pull request by AleksueiR**
Some refactoring included;
Broken tests fixed;
No new tests yet;

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/231)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/common/router/statemanager.constant.service.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231#-K8QLYp-8iwdkKGZBE5z:-K8QLYp-8iwdkKGZBE6-:31675644) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/98d21855a9b794377ab583b253caec13ae6822b3/src/app/common/router/statemanager.constant.service.js#L101)):*
wouldn't a default of `null` make more sense for `requestId`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/common/router/statemanager.constant.service.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231#-K8QLYp-8iwdkKGZBE5z:-K8QOwpKOui2CCojuNN9:-1822810247) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/98d21855a9b794377ab583b253caec13ae6822b3/src/app/common/router/statemanager.constant.service.js#L101)):*
I guess, for consistency if nothing else. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by spencerwahl** [comment]
Reviewed 31 of 31 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_symbology.scss, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231#-K8QOxSzsSF4xszeYzxE:-K8QOxSzsSF4xszeYzxF:-61581060) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/98d21855a9b794377ab583b253caec13ae6822b3/src/content/styles/modules/_symbology.scss#L4)):*
extra semicolon

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by AleksueiR** [comment]
Review status: 30 of 31 files reviewed at latest revision, all discussions resolved.

---

*[src/content/styles/modules/_symbology.scss, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231#-K8QOxSzsSF4xszeYzxE:-K8QQKYBeKGEcGyKS-qA:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/98d21855a9b794377ab583b253caec13ae6822b3/src/content/styles/modules/_symbology.scss#L4)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by james-rae** [comment]
Reviewed 27 of 31 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/231)*

**Pull request merged**
