### PR TITLE
Extension loading and api startup routine

### PR DESCRIPTION
**Pull request by milesap**
## Description

Apparently I can't spell, its extension not extention :disappointed: (updated throughout)

There are three ways to load an extension:
1. Via `rv-extensions` property on the map dom element
    Extension will be loaded when API is ready - with `mapInstance` scoped in
2. Plain Jane `script` loading
3. Via `RV.loadExtension`

See `welcome.md` file for complete extension loading guide.

## Testing
eagle eyes

## Documentation
Updated `welcome.md` however API docs will update over time once changes settle down.

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2433)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tsconfig.json, line 6 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-KxD5PG39WvoSQQrJhd2:-KxD5PG39WvoSQQrJhd3:b-tf77oo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7c86147b3412a44d5c4223d943e605fe9f4a3bbf/tsconfig.json#L6)):*
> ```JSON
>         "baseUrl": "./node_modules",
>         "target": "ES2016",
>         "paths": {
> ```

I suggest adding some typescript compiler options:
```
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
```

---

*[src/app/api-loader.ts, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-KxD5zqkI2HprRemIfdZ:-KxD5zqkI2HprRemIfd_:bwpxiw7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7c86147b3412a44d5c4223d943e605fe9f4a3bbf/src/app/api-loader.ts#L17)):*
> ```XML
> }
> 
> (<any>window).RZ = (<any>window).RZ ? (<any>window).RZ : new RZ();
> ```

You can do something like this, to avoid casing window to `any`.

```ts
interface EnhancedWindow extends Window {
    RZ: RZ
};

(<EnhancedWindow>window).RZ = (<EnhancedWindow>window).RZ ? (<EnhancedWindow>window).RZ : new RZ();
```

---

*[src/app/geo/init-map.directive.js, line 73 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-KxD6nD1wqt0bfAzfUC6:-KxD6nD1wqt0bfAzfUC7:b4u1vfq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7c86147b3412a44d5c4223d943e605fe9f4a3bbf/src/app/geo/init-map.directive.js#L73)):*
> ```JavaScript
>          */
>         function loadExtensions(apiMap) {
>             const rvextensions = el.closest('[is=rv-map]').attr('rv-extensions');
> ```

Can you use `$rootElement` instead of `el.closest('[is=rv-map]')`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433)*

**Comment by milesap** [comment]
Review status: 8 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[tsconfig.json, line 6 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-KxD5PG39WvoSQQrJhd2:-KxDMiQZFU8mhJt68MuU:b-g1iah5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7c86147b3412a44d5c4223d943e605fe9f4a3bbf/tsconfig.json#L6)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I suggest adding some typescript compiler options:
```
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
```
</blockquote></details>

Good idea, added

---

*[src/app/api-loader.ts, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-KxD5zqkI2HprRemIfdZ:-KxDMlcKgQpnKShcJ7Tw:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7c86147b3412a44d5c4223d943e605fe9f4a3bbf/src/app/api-loader.ts#L17)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can do something like this, to avoid casing window to `any`.

```ts
interface EnhancedWindow extends Window {
    RZ: RZ
};

(<EnhancedWindow>window).RZ = (<EnhancedWindow>window).RZ ? (<EnhancedWindow>window).RZ : new RZ();
```
</blockquote></details>

Done

---

*[src/app/geo/init-map.directive.js, line 73 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-KxD6nD1wqt0bfAzfUC6:-KxDNxtNaVKEH9YWGXF6:b-iz1ft) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7c86147b3412a44d5c4223d943e605fe9f4a3bbf/src/app/geo/init-map.directive.js#L73)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you use `$rootElement` instead of `el.closest('[is=rv-map]')`?
</blockquote></details>

Yeah I changed it, for some reason I thought `$rootElement` was `rv-shell`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-:-KxDjBEAoWEy-64cghNY:bnfp4nl)*

**Comment by milesap** [comment]
Normal docs and API doc links working (http://fgpv-vpgf.github.io/fgpv-vpgf/). Ok to merge when ready

---

Review status: 14 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433#-:-KxECbVA-gN-inS637Wk:b-rf677o)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433)*

**Comment by james-rae** [comment]
Reviewed 8 of 13 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2433)*

**Pull request merged**
