### PR TITLE
Use geoApi event wrapping

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/249)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/249)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/geo.service.js, line 250 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/249#-K98vWGcNIKDQG95uJyY:-K98vWGdrSQHYJhoh3iW:-2000329497) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92bc33978ea1f321d1ab8d52e15fac1784e6e537/src/app/geo/geo.service.js#L250)):*
this comment needs updating

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/249)*

**Comment by spencerwahl** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 250 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/249#-K98vWGcNIKDQG95uJyY:-K98yLJeP77onPZsgMQw:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92bc33978ea1f321d1ab8d52e15fac1784e6e537/src/app/geo/geo.service.js#L250)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/249)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/249)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/249)*

**Pull request merged**
