### PR TITLE
feat(geo): set scale flag for off-scale layers

### LINKED ISSUE #552: Update Legend Service to Account for Scale Dependent Layers
Stolen from James's post below: 
- [x] Determine if a layer is visible, yet off-scale. Steal [ramp code](https://github.com/RAMP-PCAR/RAMP-PCAR/blob/master/src/js/RAMP/Modules/filterManager.js#L757) for the way to do this.
- [x] Check the state of each layer every time the zoom level changes.  Utilize the `extent-change.levelChange` event property so we are not checking on pans.
- [x] Also run the check when a layer has it's initial load
- [x] Update the legend item's state using the `setLayerState` function in legend service

### PR DESCRIPTION
**Pull request by james-rae**
Closes #552

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/596)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 152 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596#-KHaBCTJTfhvKvFD2hOU:-KHaBCTKW1v7oVlaOlTN:1360410018) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ec27c102762452bc38116709219407e369ec96/src/app/geo/layer-registry.service.js#L152)):*
> ```JavaScript
>              * @private
>              */
>             function setScaleDepStateBulk() {
> ```

If this is only called from one place maybe it's better inlined since it's a single line function?  Unless it's going to see more use later.

---

*[src/app/geo/layer-registry.service.js, line 182 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596#-KHa8oCRGBgfvR06kfaE:-KHa8oCRGBgfvR06kfaF:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ec27c102762452bc38116709219407e369ec96/src/app/geo/layer-registry.service.js#L182)):*
> ```JavaScript
>              */
>             function isOffScale(scale, minScale, maxScale) {
>                 // GIS for dummies.
> ```

:+1: 

---

*[src/app/geo/layer-registry.service.js, line 203 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596#-KHa9UVPhwpVUFYTdmZX:-KHa9UVPhwpVUFYTdmZY:59632729) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ec27c102762452bc38116709219407e369ec96/src/app/geo/layer-registry.service.js#L203)):*
> ```JavaScript
> 
>                 // TODO _attributeBundle -- someone made it private-named, but is a useful object.
>                 //      making a function to just return it seems redundant.  discuss in code review.
> ```

I'm not looking through all the code, but isn't _attributeBundle set within a promise and therefore a direct reference is risky?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 152 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596#-KHaBCTJTfhvKvFD2hOU:-KHaCzZIAaM9gLekp85B:277535168) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ec27c102762452bc38116709219407e369ec96/src/app/geo/layer-registry.service.js#L152)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> If this is only called from one place maybe it's better inlined since it's a single line function?  Unless it's going to see more use later.</details>
Yeah...I can't think of any cases off the top of my head.  Any mass-reload would trigger layer re-adds anyways.  The function was originally much larger was well.  Will in-line it.

---

*[src/app/geo/layer-registry.service.js, line 203 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596#-KHa9UVPhwpVUFYTdmZX:-KHaQgb_IyInPaoXJWwT:-1281897979) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ec27c102762452bc38116709219407e369ec96/src/app/geo/layer-registry.service.js#L203)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I'm not looking through all the code, but isn't _attributeBundle set within a promise and therefore a direct reference is risky?</details>
it used to be that way, but we refactored it so that properties of children in the bundle are now promises.  this allows us to get metadata on layers fast, and not download attributes until they are required.   So maybe this was made private when it was still a promise (which would make sense for the reason you gave), but now it is no longer a risk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 203 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596#-KHa9UVPhwpVUFYTdmZX:-KHaReBx_xrsHd6lOyhc:-32105230) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ec27c102762452bc38116709219407e369ec96/src/app/geo/layer-registry.service.js#L203)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> it used to be that way, but we refactored it so that properties of children in the bundle are now promises.  this allows us to get metadata on layers fast, and not download attributes until they are required.   So maybe this was made private when it was still a promise (which would make sense for the reason you gave), but now it is no longer a risk.</details>
Makes sense.  In that case I'm also in favour of dropping the _ prefix and allowing general access.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596)*

**Comment by cynngah** [comment]
Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/596)*

**Pull request merged**
