### PR TITLE
Allow viewer to have map extent restricted

### LINKED ISSUE #1320: Allow Viewer to have Map Extent Restricted
The viewer should allow for the viewable area (extent) of the map set via configuration.  The user would then be unable to pan to areas of the map outside of this extent.  i.e. Joint Oil Sands Monitoring Portal should not allow users to pan outside of the relevant area.

Investigate porting code from RAMP1.

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #1320

## Testing

:eyes:
Config `66. Map with navigation restricted` in index-samples

## Documentation

In-line comments

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742)

### CODE REVIEW

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742)*

**Comment by dane-thomas** [comment]
Added a config to index-samples with the navigation restricted

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742#-:-LDllE5Y3qbsDReoJIKd:bw9d8l7)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742)*

**Comment by ShrutiVellanki** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742#-:-LDqBrAxAofTYME6gjnA:b-a2hz5k)*

**Comment by dane-thomas** [comment]
Don't pull yet. Awaiting discussion

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742#-:-LDqfWhK2ygQH6N52pLM:bfyb554)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742)*

**Pull request merged**
