### PR TITLE
feat(ui): enhance symbology icon stack in layer selector on hover

### LINKED ISSUE #150: feat(ui): enhance symbology icon stack in layer selector on hover
Symbology icon stack should react on hover, indicating that it can be interacted with. For example, top and bottom icons might rotate slightly and move out of the stack a bit, showing there are more than one item.

This should increase discoverability of this feature.

Traceability Matrix ID#102

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #150

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/320)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/toc/layer-item-symbology.directive.js, line 21 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320#-KALMersMKdq6a3BqoUw:-KALMersMKdq6a3BqoUx:-108217502) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fb2a446c1f3a103fea8e0fd0f47ceba3d5736a/src/app/ui/toc/layer-item-symbology.directive.js#L21)):*
typo: the

---

*[src/app/ui/toc/layer-item-symbology.directive.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320#-KALNQ42SYsrXf17t52a:-KALNQ42SYsrXf17t52b:556576432) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fb2a446c1f3a103fea8e0fd0f47ceba3d5736a/src/app/ui/toc/layer-item-symbology.directive.js#L66)):*
add that these are jquery objects to the comment, maybe even rename to jqItems (that might be a bit much)

---

*[src/app/ui/toc/layer-item-symbology.directive.js, line 184 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320#-KALNy9dzaHU1y9BrnKq:-KALNy9ef9n_HmwG-g_f:1386589988) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fb2a446c1f3a103fea8e0fd0f47ceba3d5736a/src/app/ui/toc/layer-item-symbology.directive.js#L184)):*
IMO the indentation makes this hard to read
```
icons.slice(-1).pop(),
RV_DURATION,
{...}
```
makes it easier to see where the args are separated

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320)*

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/toc/layer-item-symbology.directive.js, line 21 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320#-KALMersMKdq6a3BqoUw:-KALOn1oGJRjkCKcg6Ha:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fb2a446c1f3a103fea8e0fd0f47ceba3d5736a/src/app/ui/toc/layer-item-symbology.directive.js#L21)):*
Done.

---

*[src/app/ui/toc/layer-item-symbology.directive.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320#-KALNQ42SYsrXf17t52a:-KALOzD6J7JeZ_XtNaAM:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fb2a446c1f3a103fea8e0fd0f47ceba3d5736a/src/app/ui/toc/layer-item-symbology.directive.js#L66)):*
Done.

---

*[src/app/ui/toc/layer-item-symbology.directive.js, line 184 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320#-KALNy9dzaHU1y9BrnKq:-KALPMC2jVDYWaikyMX_:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fb2a446c1f3a103fea8e0fd0f47ceba3d5736a/src/app/ui/toc/layer-item-symbology.directive.js#L184)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/320)*

**Pull request merged**
