### PR TITLE
feat(ui): basemap panel changed to $mdSideNav

### LINKED ISSUE #1244: Change Basemap Selector to a Right Sided Navigation Component
Basemap Selector is currently implemented as a panel.  It should be implemented to operate the same as the Left sided menu.

### PR DESCRIPTION
**Pull request by milesap**
Closes #1244

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1249)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249)*

**Comment by AleksueiR** [comment]
Looks nice! just needs some enhancements :)

- keep width of the basemap selector as 300px
- make the backdrop fully transparent
- when the basemap selector opens, animate opacity of all open panels to transparent (animate it back to fully opaque when the basemap selector closes) (this will show how the basemap changes)
- do not move the navbar, let it be hidden by the basemap selector

---

Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/basemap/basemap.service.js, line 62 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-KTF3Ol3g49uXodEsyo6:-KTF3Ol3g49uXodEsyo7:bmhm34l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9586cea5a10e40d8eceff14e8047c30698f6abe/src/app/ui/basemap/basemap.service.js#L62)):*
> ```JavaScript
>          * @return  {Promise}   resolves to undefined when panel animation is complete
>          */
>         function open() {
> ```

Trying to avoid defer - create a new close promise on every open (don't need `init` anymore, I think): 

```js
closePromise = $q(resolve =>
      $mdSidenav('right').onClose(() => 
           resolve));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-:-KTF-Hn58qS2OzhCmSp8:b-yk2qip)*

**Comment by milesap** [comment]
- width increased to 300px
- backdrop is fully transparent
- all `rv-panel` elements transition to fully transparent when the basemap selector is open (and revert on close)
- navbar remains in place

Set basemap selector to close on basemap change, not sure I'd like to keep it that way, what do you think?

---

Review status: 2 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 62 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-KTF3Ol3g49uXodEsyo6:-KTFjZ213OLsmmgYlqYJ:b-7fm0yj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9586cea5a10e40d8eceff14e8047c30698f6abe/src/app/ui/basemap/basemap.service.js#L62)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Trying to avoid defer - create a new close promise on every open (don't need `init` anymore, I think): 
> 
> ```js
> closePromise = $q(resolve =>
>       $mdSidenav('right').onClose(() => 
>            resolve));
> ```
</details>
:+1:  great - made the change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-:-KTFiekoiHA02cKKpBMi:bhs43od)*

**Comment by alyec** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249)*

**Comment by AleksueiR** [comment]
I guess I misspoke somewhere - no need to close the selector on basemap change (I agree with you - the way it was is better).

When you are hiding panels with `basemap` morph, panel's size and position is also affected (since previous morph no longer applies). If you open the basemap selector and unhide the datatable you will see it's distorted. Opacity should be applied on top of the current morph, so it doesn't modify the panel further.

One more thing: fade in animation works, but fade out doesn't seem to (panels just disappear without any animation.)

---

Reviewed 8 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 62 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-KTF3Ol3g49uXodEsyo6:-KTFleb339IO0VqOLQ3D:b-qf4giv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e9586cea5a10e40d8eceff14e8047c30698f6abe/src/app/ui/basemap/basemap.service.js#L62)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> :+1:  great - made the change
</details>
Even better :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-:-KTFnFKvwUifEmVU2Efi:b-7qeaiq)*

**Comment by AleksueiR** [comment]
Wonderful, looks much better now!
Another change, if you don't mind: make it 0.2 opacity and include the main appbar in that, so the user could see that panels didn't just close by themselves all of a sudden.
Thanks.

---

Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-:-KTKglwBTCWOsU9u5qof:bhzjbcp)*

**Comment by milesap** [comment]
Excellent, updated to include appbar and changed from `0` opacity to `0.2`

---

Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-:-KTKiKT20HLNlqAAKDX-:boquzqq)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: 9 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249#-:-KTKn3yZDv-ticZxzMy_:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 2 of 5 files at r3, 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1249)*

**Pull request merged**
