### PR TITLE
fix(ui): close filters when layer is removed

### LINKED ISSUE #1112: Removing the Layer from the Legend list does not remove the data table if it is open
Tested on build: http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.htm

Steps to Reproduce
1. Open the viewer
2. Load all layers.
3. Select a layer to load the data grid
4. Remove the layer while the data grid is open
5. Layer is removed from the Legend. However, data grid is not removed.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1112

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1165)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/toc/toc.service.js, line 228 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165#-KR93ittA7BRxGpyavVZ:-KR93itui1l16sq5Nh4I:b2vx5l6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/802e71647743e45726baf0fadc6398f2b06e135b/src/app/ui/toc/toc.service.js#L228)):*
> ```JavaScript
>                         // restore layer visibility on undo; and add it back to layer selector
>                         entryParent.add(entry, entryPosition);
> ```

It would be a nice touch to restore the datatable if the remove action is undone.

Just add this here:
```js
toggleLayerFiltersPanel(entry);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 228 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165#-KR93ittA7BRxGpyavVZ:-KR96Kld1k8ZuN-rv7_W:b-uwfk8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/802e71647743e45726baf0fadc6398f2b06e135b/src/app/ui/toc/toc.service.js#L228)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> It would be a nice touch to restore the datatable if the remove action is undone.
> 
> Just add this here:
> ```js
> toggleLayerFiltersPanel(entry);
> ```
</details>
Good idea. The code you provide me open the filters even if it was close. I will modify it so if the filters are close they will not open.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 228 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165#-KR93ittA7BRxGpyavVZ:-KR9F2x1RaxUABJBruD3:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/802e71647743e45726baf0fadc6398f2b06e135b/src/app/ui/toc/toc.service.js#L228)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Good idea. The code you provide me open the filters even if it was close. I will modify it so if the filters are close they will not open.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165#-:-KR9SOY_O_RA4XnHy5ZU:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1165)*

**Pull request merged**
