### PR TITLE
Fix highlights not working for keyboard based identify

### LINKED ISSUE #2785: Keyboard based identify doesn't highlight in 'highlight' mode
When `RZ.mapInstances[0].layers.identifyMode = 'highlight'` is called, keyboard based identify will not cause a highlight on a feature. Tooltips also do not appear.

The identify results are properly piped still, so the identify is being triggered.

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #2785

## Testing

:eyes: 

## Documentation

in-line commenting 

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789)

### CODE REVIEW

**Comment by ShrutiVellanki** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm, @james-rae, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789)*

**Comment by AleksueiR** [comment]
What was the problem here? Not sure what has actually changed with all the moved code.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789#-:-LFXYrTU1s5Pugq6maLr:bak44oa)*

**Comment by dane-thomas** [comment]
In `highlight` mode the icons wouldn't highlight when using the keyboard. Basically the problem was that the highlight was only being checked when the icons were being clicked so it wouldn't trigger when using the keyboard. The code was moved so the highlight would be triggered on identify instead.

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789#-:-LFXZG9OCzITRN7A81a8:byfe8fw)*

**Comment by AleksueiR** [comment]
Ah, yes, pressing `Enter` does not make a fake `click` event as I thought, [it calls identify service directly](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/init-map.directive.js#L245).

Thanks for clarification.

:lgtm:  

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789#-:-LFXa7Jc4T9Y6bZ2ZTy-:ber1mck)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789#-:-LFXifEoDdUE5u1ekZdi:bnfp4nl)*

**Pull request merged**
