### PR TITLE
Fix the problem where north arrow was not showing

### LINKED ISSUE #1929: North Arrow shown in top left when set to false in config file
fgpv_north_arrow_false

in version 1.7.0 [142f4f9]

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Fixes #1929 and #1942 
Fix the problem when north arrow was not showing up when the viewer loads and should be able to switch to snowman when it is at the north pole.

## Testing

No, it was a UI bug

## Documentation

NA

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1950)

### CODE REVIEW

**Comment by AleksueiR** [comment]
What's up with demos not building...

---

Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-:-KmCkUO0FKxK6gupzm8R:bips1a5)*

**Comment by barryytm** [comment]
It did build but it is under 1929/ because I accidentally put a `/` in `1929/1942-north-arrow`.  Should put a hyphen instead.

**Comment by AleksueiR** [comment]
Yes, but it wasn't picked up by our glitch bot. Strange.

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-:-KmClI68d28Fwo47x3in:b-v4tjqu)*

**Comment by AleksueiR** [comment]
http://fgpv.cloudapp.net/demo/users/barryytm/1929/1942-north-arrow/dev/samples/index-mobile.html

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-:-KmClYK2g2QPcHOYRxZS:b-8avyl3)*

**Comment by barryytm** [comment]
Do I need to do anything to fix it?

**Comment by AleksueiR** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/north-arrow.directive.js, line 45 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-KmCm4nVTAUd9DdwrO5n:-KmCm4nVTAUd9DdwrO5o:b-j26f03) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/894522b90d69d13ae16e80e4df5c337d49971a06/src/app/ui/common/north-arrow.directive.js#L45)):*
> ```JavaScript
>                 self.arrowIcon = north.screenY > 0 ? 'snowman' : 'northarrow'; // change icon for north pole
> 
>                 // remove the icon if it had any then apend the new icon
> ```

This will keep recompiling the arrow on every extent change - very often in other words. I think you should be able to compile it once every `rvApiReady` event and it should be fine.
You can also add the `arrowIcon` to the new scope like this:
```js
const northArrowTemplate = `<md-icon md-svg-src="{{ self.arrowIcon }}"></md-icon>`
const northArrowScope = $rootScope.$new();
northArrowScope.self = self;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950)*

**Comment by AleksueiR** [comment]
No, it's okay for now. It might be because of the extra `/` in the path, but I'm not sure. 

---

Reviewed 2 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-:-KmCnD--S4a2fbrjvKJb:b-h7mglf)*

**Comment by barryytm** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/north-arrow.directive.js, line 45 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-KmCm4nVTAUd9DdwrO5n:-KmCuoHG6ubAYxKXVapk:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/894522b90d69d13ae16e80e4df5c337d49971a06/src/app/ui/common/north-arrow.directive.js#L45)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This will keep recompiling the arrow on every extent change - very often in other words. I think you should be able to compile it once every `rvApiReady` event and it should be fine.
You can also add the `arrowIcon` to the new scope like this:
```js
const northArrowTemplate = `<md-icon md-svg-src="{{ self.arrowIcon }}"></md-icon>`
const northArrowScope = $rootScope.$new();
northArrowScope.self = self;
```


</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/north-arrow.directive.js, line 28 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-KmCwKZKrW7-2IBKQlfb:-KmCwKZKrW7-2IBKQlfc:b-z0jtc3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5999dd25bd5200347937aedb77b782fccf59a529/src/app/ui/common/north-arrow.directive.js#L28)):*
> ```JavaScript
>                 $rootElement.find('.rv-esri-map > .esriMapContainer').first().after(element);
> 
>                 // append the icon
> ```

It seems you do need to clear the children here after all, as they are multiplied when switching projections. :)


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950)*

**Comment by barryytm** [comment]
I just tested on cloud, there was only one icon though.

**Comment by AleksueiR** [comment]
Proof :D


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-:-KmCyfr8JfNCee40DSp4:b-gilnxx)*

**Comment by AleksueiR** [comment]
:lgtm: Works nicely!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950#-:-KmD1Vy4TmdI2hx1HvA5:bazk3je)*

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950)*

**Comment by alyec** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1950)*

**Pull request merged**
