### PR TITLE
Help fixes + space under image symbol labels

### LINKED ISSUE #2470: Image style items have unneeded extra space under the label in the legend
Problem may be related to [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.1.0-daily07/src/app/ui/toc/symbology-stack.directive.js#L436) as it is providing false (larger) values when it executes vs. when you inspect the element in dev. tools. 

68747470733a2f2f692e696d6775722e636f6d2f72585176394b392e706e67

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #2470
Getting the `outerHeight` would return strange values when the symbology stack was collapsed so there was no way to get the proper height of the label. Now, there's some convoluted math that calculates the size of the label without unneeded extra space. 

#2634 #2631 still require french translations

## Testing

:eyes:

## Documentation

in-line commenting

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm, @ShrutiVellanki, and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by JahidAhmed** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm and @ShrutiVellanki)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by barryytm** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 542 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788#-LFXXrnj8E86x4rrxoRF:-LFXXrnj8E86x4rrxoRG:b-mcbnah) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5534ee2d5a5c5dab4067e8c188da233b637e354c/src/app/ui/toc/symbology-stack.directive.js#L542)):*
> ```JavaScript
>             const itemHeight = imageWidth !== 0 ? itemWidth / imageWidth * imageHeight : 0; // in cases when image urls are broken its size is 0
> 
>             // extremely convoluted math to calculate an aproximation of the label's height
> ```

Maybe you can use the `getTextWidth` function to get the width of the label:
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/core/graphics.service.js#L122

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by dane-thomas** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 542 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788#-LFXXrnj8E86x4rrxoRF:-LFbdMv5946LqrEZlCvH:b2iwjo5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5534ee2d5a5c5dab4067e8c188da233b637e354c/src/app/ui/toc/symbology-stack.directive.js#L542)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Maybe you can use the `getTextWidth` function to get the width of the label:
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/core/graphics.service.js#L122
</blockquote></details>

donethanks. Just waiting to push until after PRs are pulled 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @AleksueiR)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @AleksueiR)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 542 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788#-LFXXrnj8E86x4rrxoRF:-LFvrtEfEkylm_Rsmmwg:b-bhugfn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5534ee2d5a5c5dab4067e8c188da233b637e354c/src/app/ui/toc/symbology-stack.directive.js#L542)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

donethanks. Just waiting to push until after PRs are pulled 
</blockquote></details>

A small change: a canvas is already created in this file on line [312](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/078474ce077b2f1a56fe207e639e4ad3bfdc4d03/src/app/ui/toc/symbology-stack.directive.js#L312) specifically to get label widths on line [345](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/078474ce077b2f1a56fe207e639e4ad3bfdc4d03/src/app/ui/toc/symbology-stack.directive.js#L345). You can reuse that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by dane-thomas** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 542 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788#-LFXXrnj8E86x4rrxoRF:-LFvtB9V7YU7F3rOcz_0:b81giyf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5534ee2d5a5c5dab4067e8c188da233b637e354c/src/app/ui/toc/symbology-stack.directive.js#L542)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

A small change: a canvas is already created in this file on line [312](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/078474ce077b2f1a56fe207e639e4ad3bfdc4d03/src/app/ui/toc/symbology-stack.directive.js#L312) specifically to get label widths on line [345](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/078474ce077b2f1a56fe207e639e4ad3bfdc4d03/src/app/ui/toc/symbology-stack.directive.js#L345). You can reuse that.
</blockquote></details>

The canvas defined is in the scope of `initializeTimelines` so should I move it out of the function into the directive?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @AleksueiR)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 542 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788#-LFXXrnj8E86x4rrxoRF:-LFvyGqN8-ya3JleWVMU:b-as804e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5534ee2d5a5c5dab4067e8c188da233b637e354c/src/app/ui/toc/symbology-stack.directive.js#L542)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

The canvas defined is in the scope of `initializeTimelines` so should I move it out of the function into the directive?
</blockquote></details>

Sure, it should be sage to move it out as far as needed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by dane-thomas** [comment]
Review status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @james-rae and @dane-thomas)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 542 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788#-LFXXrnj8E86x4rrxoRF:-LFw-cXJBD2IxXVc19Ii:bcze0ta) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5534ee2d5a5c5dab4067e8c188da233b637e354c/src/app/ui/toc/symbology-stack.directive.js#L542)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Sure, it should be sage to move it out as far as needed.
</blockquote></details>

donethanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2788)*

**Pull request merged**
