### PR TITLE
feat(core): add history to state items with children

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/233)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/common/router/statemanager.constant.service.js, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233#-K8Un-wOqVOEaPe9Kfi1:-K8Un-wOqVOEaPe9Kfi2:1105103151) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ca6baf31c6bcce6924f0733da38f9cca0cac04f3/src/app/common/router/statemanager.constant.service.js#L29)):*
general note: if all of these objects are so similar wouldn't it make sense to create a general type and have all of them derive from a common base?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/common/router/statemanager.constant.service.js, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233#-K8Un-wOqVOEaPe9Kfi1:-K8Uo5EiKWSlOE1_na9P:357422542) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ca6baf31c6bcce6924f0733da38f9cca0cac04f3/src/app/common/router/statemanager.constant.service.js#L29)):*
Sure, sounds like a good idea.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/common/router/statemanager.constant.service.js, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233#-K8Un-wOqVOEaPe9Kfi1:-K8UtoMn6zCoCGipU7No:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ca6baf31c6bcce6924f0733da38f9cca0cac04f3/src/app/common/router/statemanager.constant.service.js#L29)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/233)*

**Pull request merged**
