### PR TITLE
refactor(core): add event broadcasting to state manager

### PR DESCRIPTION
**Pull request by AleksueiR**
Refactoring, name changing, not much useful code.
Fix issue with datatable styles not being included.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/200)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Comment by spencerwahl** [comment]
Reviewed 17 of 18 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 18 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Comment by alyec** [comment]
Reviewed 17 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/app/common/router/statemanager.service.js, line 115 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200#-K7m3XXOfA23bWkt-ukj:-K7m3XXOfA23bWkt-ukk:-1701105023) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/94d0563c736ed33bdb85958daa321bf041be036f/src/app/common/router/statemanager.service.js#L115)):*
const?

---

*[src/app/common/router/statemanager.service.js, line 245 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200#-K7m4G0TH9Yj7s1foOyN:-K7m4G0U1WLfSizkYUwn:-1952072479) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/94d0563c736ed33bdb85958daa321bf041be036f/src/app/common/router/statemanager.service.js#L245)):*
add a comment to explain that this isn't a memory leak

---

*[src/app/ui/common/morph.directive.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200#-K7m68bS-ehGh3-itWWi:-K7m68bTH9J7kuHUFV5B:508703014) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/94d0563c736ed33bdb85958daa321bf041be036f/src/app/ui/common/morph.directive.js#L75)):*
since we're not in a promise call it something besides resolve?

---

*[src/app/ui/common/state.directive.js, line 35 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200#-K7m6HyYUTbUdpA2nR2Q:-K7m6HyYUTbUdpA2nR2R:-1659719376) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/94d0563c736ed33bdb85958daa321bf041be036f/src/app/ui/common/state.directive.js#L35)):*
since we're not in a promise call it something besides resolve? (same as previous)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Comment by AleksueiR** [comment]
Review status: 13 of 25 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 115 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200#-K7m3XXOfA23bWkt-ukj:-K7mG6aIPPeI-MNWBU18:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/94d0563c736ed33bdb85958daa321bf041be036f/src/app/common/router/statemanager.service.js#L115)):*
Done.

---

*[src/app/ui/common/morph.directive.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200#-K7m68bS-ehGh3-itWWi:-K7mG6w6_A4HPAMnCFu9:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/94d0563c736ed33bdb85958daa321bf041be036f/src/app/ui/common/morph.directive.js#L75)):*
Done.

---

*[src/app/ui/common/state.directive.js, line 35 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200#-K7m6HyYUTbUdpA2nR2Q:-K7mG7Dv3dkee__MrerH:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/94d0563c736ed33bdb85958daa321bf041be036f/src/app/ui/common/state.directive.js#L35)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Comment by james-rae** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Comment by alyec** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Comment by spencerwahl** [comment]
Reviewed 12 of 12 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/200)*

**Pull request merged**
