### PR TITLE
fix(test): add rv-langs with French as default in index-fgp-fr.html

### LINKED ISSUE #1539: Left Sided Menu defaulted to English when loaded FGP Visualiser from index-fgp-fr.html
Tested build URL: http://fgpv.cloudapp.net/demo/v1.5.0-5/prod/samples/index-fgp-fr.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

When loading Visualiser from French URL, the left sided menu should default to French.

image

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
Left Sided Menu defaulted to English when loaded FGP Visualiser from index-fgp-fr.html #1539

## Testing
Manual test with index-fgp-fr.html

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Closes #1539

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1582)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/index-fgp-fr.html, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582#-KaJCo0gqiUIr9kwL4M0:-KaJCo0gqiUIr9kwL4M1:b-t3d8tl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c643918bb698155c6b941122cab1a5eefeb156a/src/index-fgp-fr.html#L453)):*
> ```HTML
>                         <button onclick="testBackToCart()">backToCart</button>
>                     </div>
>                     <div id="fgpmap" class="fgpv" rv-config="config.rcs.fr-CA.json" rv-langs='["fr-CA","en-CA"]' rv-service-endpoint="http://section917.cloudapp.net:8000/" rv-wait>
> ```

`rv-langs` were previously removed in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1528/files trying to fix https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1468. Aren't we re-introducing this bug again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582)*

**Comment by ChrisLatRNCan** [comment]
*[src/index-fgp-fr.html, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582#-KaJCo0gqiUIr9kwL4M0:-KaJIavJqQ7hdcY1aS37:bwpyg2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1c643918bb698155c6b941122cab1a5eefeb156a/src/index-fgp-fr.html#L453)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`rv-langs` were previously removed in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1528/files trying to fix https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1468. Aren't we re-introducing this bug again.
</blockquote></details>

No, I've put a comment about this matter in #1539 . So, basically it is mandatory to mention both languages in the right order (fr-CA,en-CA) to overwrite the default value (en-CA, fr-CA).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index-fgp-fr.html, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582#-KaJCo0gqiUIr9kwL4M0:-KaK7Th1l45W7kPAwR2o:bbvwg15) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/40f82907f449a53b23affa243721e82a2ed24995/src/index-fgp-fr.html#L453)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

No, I've put a comment about this matter in #1539 . So, basically it is mandatory to mention both languages in the right order (fr-CA,en-CA) to overwrite the default value (en-CA, fr-CA).
</blockquote></details>

Missed it. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582#-:-KaN3kuBjqp0HhonMUt9:bnfp4nl)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582#-:-KaN4BwC3Kc7vGGkdRlX:bnfp4nl)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1582#-:-KaN82TJOFtxhvFnjGHp:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
I'll rebase

**Pull request merged**
