### PR TITLE
geo module

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/46)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/geo/geo.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46#-K1EejmjqSIwoTQ7LhVW)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/77a6e7e09b89e305c51b7040bb9be3e0192ba3ea/src/app/geo/geo.service.js#L24)):</sup>
This will start loading dojo as soon as the service is created, right? Should we do something similar with the config service as well? It has a little more convoluted init sequence.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/geo/geo.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46#-K1EejmjqSIwoTQ7LhVW)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/77a6e7e09b89e305c51b7040bb9be3e0192ba3ea/src/app/geo/geo.service.js#L24)):</sup>
Yes, this will trigger on creation.  Not sure about the config service as I'm not that familiar with it yet, but it probably is worth looking into.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46)

**Comment by jolevesq** [comment]
Reviewed 5 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/geo/init-map.directive.js, line 28 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46#-K1F4D0WNFk48oZJvbVT)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7803ba43a0f097f0c588a601b5cefed87a985018/src/app/geo/init-map.directive.js#L28)):</sup>
Remove parenthesis when there is only one element as argument function for arrow function.


---

<sup>**[src/app/layout/layout.module.js, line 1 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46#-K1F4XzZnn98Y3u2R1B2)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7803ba43a0f097f0c588a601b5cefed87a985018/src/app/layout/layout.module.js#L1)):</sup>
Aleks start to change those to arrow function in other files. Can you do the same thing for consistency.


---

<sup>**[src/app/layout/shell.html, line 2 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46#-K1F4pD6xvE36730GpwS)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7803ba43a0f097f0c588a601b5cefed87a985018/src/app/layout/shell.html#L2)):</sup>
We put spaces after and before curly brackets in JS. We said we will do the same thing in html


---

<sup>**[src/app/layout/shell.html, line 38 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46#-K1F55WtA-bpcYo8PpS6)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7803ba43a0f097f0c588a601b5cefed87a985018/src/app/layout/shell.html#L38)):</sup>
Same here, space before and after.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46)

**Comment by jolevesq** [comment]
Reviewed 1 of 2 files at r2.
Review status: 5 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46)

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46)

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/46)

**Pull request merged**
