### PR TITLE
Import service - service type checks

### PR DESCRIPTION
**Pull request by AleksueiR**
Adds a check when the user selects a service type different from a predicted one.

In support of #770

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/812)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/812)*

**Comment by AleksueiR** [comment]
Hold on merging this one, need to fix one thing.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/812#-:-KKxSS0f4DKtXeQ6oqLk:-1185972568)*

**Comment by AleksueiR** [comment]
Merge at will. :)

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/812#-:-KKx_XN7LvTBtvnnXfDT:1657515539)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/812)*

**Pull request merged**
