### PR TITLE
Small UI changes

### PR DESCRIPTION
**Pull request by spencerwahl**
- Deleted extra mapnav, sidenav and filters menu buttons
- Removed temp buttons on the main panel (layer loader, language switch)
- Re-enabled the extent on the overview map
- Fixed and enhanced settings panel controls

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/395)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Please, add `TODO`s everywhere something is commented out explaining why it was needed.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_buttons.scss, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3SGAGJrn5ISxdE99C:-KD3SGAGJrn5ISxdE99D:-159270628) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/modules/_buttons.scss#L8)):*
Switch on the right, clickable label: http://codepen.io/AleksueiR/pen/zqNzEJ

---

*[src/content/styles/modules/_setting-controls.scss, line 51 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3SVwNqdf1KuVvdF48:-KD3SVwNqdf1KuVvdF49:2011137258) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/modules/_setting-controls.scss#L51)):*
Why 5%? Margins shouldn't generally be in %, except for 100% or 33% or 50% when you want to align things.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-:-KD3MhnnJxM7TxIWmUaw:-1489424543)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/vendor/_esri.scss, line 192 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3U94EjPqkEwJYqyAM:-KD3U94EjPqkEwJYqyAN:-1656410331) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/vendor/_esri.scss#L192)):*
Keep the background color and override the border color with this.
```css
{
    border: 1px solid $primary-color-dark !important;
    background-color: rgba(0, 0, 0, 0.1) !important;
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395)*

**Comment by alyec** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_setting-controls.scss, line 51 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3SVwNqdf1KuVvdF48:-KD3VpvH3ht9uUz_Kf9f:-1768461435) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/modules/_setting-controls.scss#L51)):*
I suggest 50% in this case

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_setting-controls.scss, line 51 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3SVwNqdf1KuVvdF48:-KD3YUt2--bRjxTKnvJz:-2143912881) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/modules/_setting-controls.scss#L51)):*
There is an example of a slider with an icon: https://material.angularjs.org/HEAD/demo/slider


---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395)*

**Comment by spencerwahl** [comment]
>Please, add TODOs everywhere something is commented out explaining why it was needed.

done

---

Review status: 2 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_buttons.scss, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3SGAGJrn5ISxdE99C:-KD4marSJZaXz6QRodEf:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/modules/_buttons.scss#L8)):*
done

---

*[src/content/styles/modules/_setting-controls.scss, line 51 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3SVwNqdf1KuVvdF48:-KD4mYrG7QhbgcDhSxVX:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/modules/_setting-controls.scss#L51)):*
done

---

*[src/content/styles/vendor/_esri.scss, line 192 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-KD3U94EjPqkEwJYqyAM:-KD4m_EeCVeRnR_7bgR9:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f9a2a9e60f364b9a3fc0e2a201d00c9b121b258/src/content/styles/vendor/_esri.scss#L192)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-:-KD4mdy4JbxHA7PaOzvI:-778737597)*

**Comment by ec-dev** [comment]
Reviewed 5 of 9 files at r1, 1 of 6 files at r2, 2 of 4 files at r3.
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395)*

**Comment by ec-dev** [comment]
Reviewed 2 of 6 files at r2, 2 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395)*

**Comment by alyec** [comment]
Reviewed 3 of 6 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395)*

**Comment by alyec** [comment]
So long, and thanks for all the muffins.  :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/395#-:-KD53JgUqjszfQ71mD4O:-2027020808)*

**Pull request merged**
