### PR TITLE
feat(ui): reduce logo size on small layouts

### LINKED ISSUE #1857: Collapse logo in the side nav on small layouts
On small layouts (low vertical height), the logo on the side nav pushes all menu items down, below the fold, making them mostly unusable.

#### Affected: 
all version

#### Solution:
If the height of the viewer is below 450px, reduces the size of the logo to 50px x 50px, it's top margin to 10px, font and line size of the title to 18px and 36px respectively.

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes #1857
reduce logo size on small layouts when its height is less than 450px
## Testing

Try change the height to less than 450px

## Documentation

None
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1909)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by barryytm** [comment]
Yes

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-:-Kl5Ow_Mm86uuDGOgZtC:b2nhswy)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/modules/_app-menu.scss, line 103 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-KlJ2Z0uAZOGK07ExGWN:-KlJ2Z0uAZOGK07ExGWO:brcif1v) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2341f68cada6c85fb18f56b74f6229cbc48199de/src/content/styles/modules/_app-menu.scss#L103)):*
> ```SCSS
>                     align-items: center;
> 
>                     @media (max-height: 450px) {
> ```

The `@media` rule applies to the viewport, not a single node. If the viewer is embedded into a page, it will not work unfortunately.



`layoutService` would probably needs to be changed - right now it's only detecting the width of viewer instance. Get the viewer height (450 < or > 450) and add a corresponding class to the root element, similarly how the width is being handled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by barryytm** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_app-menu.scss, line 103 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-KlJ2Z0uAZOGK07ExGWN:-KlJnqwe81RR5l2wnvxc:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d274da9f393d868663dad128f03c55f8e19502a8/src/content/styles/modules/_app-menu.scss#L103)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

The `@media` rule applies to the viewport, not a single node. If the viewer is embedded into a page, it will not work unfortunately.



`layoutService` would probably needs to be changed - right now it's only detecting the width of viewer instance. Get the viewer height (450 < or > 450) and add a corresponding class to the root element, similarly how the width is being handled.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/modules/_app-menu.scss, line 125 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-KlKEnjxKFTq7L_345TU:-KlKEnjxKFTq7L_345TV:bkgaz0t) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fd7f9a1f3c873645f980ea0bd6938956493b0e9/src/content/styles/modules/_app-menu.scss#L125)):*
> ```SCSS
>                 h1 {
>                     // when height >= 450
>                     @include include-size(rv-tl) {
> ```

Probably no need to explicitly define this as "tall" since you have only two options: "tall" and "short". These should be default values, and `font-size` and `line-height` will be overridden when the layout changes to "short". Same with the change above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-:-KlKLQ0jRu9a_2pgadob:bnfp4nl)*

**Comment by barryytm** [comment]
Not done yet, don't close

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.directive.js, line 122 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-KlKVJAH4iCGIfGMk3mF:-KlKVJAH4iCGIfGMk3mG:b-b8msn2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/134b152d440c2f51d6d278b9b97ab115e12ee677/src/app/layout/shell.directive.js#L122)):*
> ```JavaScript
>             .addClass('rv-' + layoutService.currentLayout())
> 
>         if (layoutService.isShort()) {
> ```

Small change:

```js
$rootElement.toggleClass('rv-short', layoutService.isShort());
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by barryytm** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/layout/shell.directive.js, line 122 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-KlKVJAH4iCGIfGMk3mF:-KlKWhpxLf6MpaGHJL61:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/134b152d440c2f51d6d278b9b97ab115e12ee677/src/app/layout/shell.directive.js#L122)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Small change:

```js
$rootElement.toggleClass('rv-short', layoutService.isShort());
```

</blockquote></details>

done, thanks

---

*[src/content/styles/modules/_app-menu.scss, line 125 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909#-KlKEnjxKFTq7L_345TU:-KlKWc7XwHniwUP5VSAM:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ba08d486f0455ba358ce890e5d78fdf8a71822e1/src/content/styles/modules/_app-menu.scss#L125)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Probably no need to explicitly define this as "tall" since you have only two options: "tall" and "short". These should be default values, and `font-size` and `line-height` will be overridden when the layout changes to "short". Same with the change above.
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1909)*

**Pull request merged**
