### PR TITLE
Conditionally load DataTables

### PR DESCRIPTION
**Pull request by spencerwahl**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/478)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/478)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/injector.js, line 41 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/478#-KF53S01qsa_bVMpPOQR:-KF53S01qsa_bVMpPOQS:-168842138) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/31350f0309cc341731e12e104719aaeee8915acf/src/app/injector.js#L41)):*
Maybe store urls in a variable to avoid duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/478)*

**Comment by spencerwahl** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/injector.js, line 41 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/478#-KF53S01qsa_bVMpPOQR:-KF5GLl9sn6D7oVBsI66:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/31350f0309cc341731e12e104719aaeee8915acf/src/app/injector.js#L41)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/478)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/478)*

**Pull request merged**
