### PR TITLE
fix(table): disable focus inside second header of table

### LINKED ISSUE #2320: Unable to tab past data filters
Steps:
- tab to a layer with data
- open datatable
- wait for it to load and the focus to shift to the datatable close button
- start tabbing (focus goes to the datatable filters)
- when tabbed to the input field in the last filter, focus gets stuck there, and then disappears
- further tabbing of shift+tabbing doesn't have any effect

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2320 

## Testing
Visually tested

## Documentation
In-line comments

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2325)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/table/table-default.directive.js, line 669 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325#-KrWvjBBO3aY89-9bkbB:-KrWvjBBO3aY89-9bkbC:brraly2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c5c274db55513f88d2f7d2ee56c2d4859dded75/src/app/ui/table/table-default.directive.js#L669)):*
> ```JavaScript
>                 $rootElement.find('.dataTables_scrollBody td').attr('tabindex', '-3');
> 
>                 if (self.tableBody) {
> ```

Do we need to run this on every table draw event? Can it be called once?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/table/table-default.directive.js, line 669 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325#-KrWvjBBO3aY89-9bkbB:-KrWz1jF--tc4IDwU1AC:b-ncl5ok) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c5c274db55513f88d2f7d2ee56c2d4859dded75/src/app/ui/table/table-default.directive.js#L669)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Do we need to run this on every table draw event? Can it be called once?
</blockquote></details>

I initially tried adding it inside `onTableInit` but it gets added and then removed when the table is actually drawn I think and couldn't trace down why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/table/table-default.directive.js, line 669 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325#-KrWvjBBO3aY89-9bkbB:-Kr_lgYazqD-wJ6eFQra:b-takt44) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c5c274db55513f88d2f7d2ee56c2d4859dded75/src/app/ui/table/table-default.directive.js#L669)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

I initially tried adding it inside `onTableInit` but it gets added and then removed when the table is actually drawn I think and couldn't trace down why.
</blockquote></details>

Does the datatable re-render the headers on draw? I'm worried this might slow the datatable even more if we run this selector too often.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325)*

**Comment by JahidAhmed** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/table/table-default.directive.js, line 669 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325#-KrWvjBBO3aY89-9bkbB:-Kravc1baPMNNlCCtZDh:bcfpfiw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c5c274db55513f88d2f7d2ee56c2d4859dded75/src/app/ui/table/table-default.directive.js#L669)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Does the datatable re-render the headers on draw? I'm worried this might slow the datatable even more if we run this selector too often.
</blockquote></details>

Modified it accordingly, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2325)*

**Pull request merged**
