### PR TITLE
feat(ui): layers are now 0.86 transparent when basemap open

### LINKED ISSUE #1296: Make all layer 0.2 transparent when basemap selector is open
When the basemap selector is opened, panels have their opacity reduced to make the changes of the basemap more visible. I think it would make sense to reduce the opacity of the visible layers for the same purpose.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1296

## Testing
In browser

## Documentation
None

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1769)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/basemap/basemap.service.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-KfHq2tgfz2l_ge80fwv:-KfHq2tgfz2l_ge80fww:bc58mxp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4d0db571c4540c4025b24983a2c78f73fd7ecf49/src/app/ui/basemap/basemap.service.js#L66)):*
> ```JavaScript
>             function setOtherChromeOpacity(panelOpacity, layerOpacity) {
>                 $rootElement.find(`rv-panel, rv-appbar`).css('opacity', panelOpacity);
>                 $rootElement.find(`.rv-esri-map .layersDiv > svg`).css('opacity', layerOpacity);
> ```

This will only affect feature layers. Need to also hide dynamic and wms layers as well layers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/basemap/basemap.service.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-KfHq2tgfz2l_ge80fwv:-KfHqecJfScI9B0Ao5Jc:bqkryy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4d0db571c4540c4025b24983a2c78f73fd7ecf49/src/app/ui/basemap/basemap.service.js#L66)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This will only affect feature layers. Need to also hide dynamic and wms layers as well layers.
</blockquote></details>

Also, let's go with 0.2 opacity for both; 0.86 is not low enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-KfHq2tgfz2l_ge80fwv:-KfHw-qNNMv4X40SIuGQ:bpdc4pi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4d0db571c4540c4025b24983a2c78f73fd7ecf49/src/app/ui/basemap/basemap.service.js#L66)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Also, let's go with 0.2 opacity for both; 0.86 is not low enough.
</blockquote></details>

Ah, good catch - tested on feature, dynamic, wms, and tile. Changed to 0.2 opacity 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-:-KfHz1IW4ePlxxghCIwF:bnfp4nl)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-KfHq2tgfz2l_ge80fwv:-KfHyNrvPvlxQQqRqhFx:bk5rgyr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4d0db571c4540c4025b24983a2c78f73fd7ecf49/src/app/ui/basemap/basemap.service.js#L66)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Ah, good catch - tested on feature, dynamic, wms, and tile. Changed to 0.2 opacity 
</blockquote></details>

You can probably use the * selector here -> `.rv-esri-map .layersDiv > *:not(:first)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-:-KfHzepAnjOUR1sahU6C:bnfp4nl)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-KfHq2tgfz2l_ge80fwv:-KfI02a8nmS7brMYV-tq:b-w7svyt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4d0db571c4540c4025b24983a2c78f73fd7ecf49/src/app/ui/basemap/basemap.service.js#L66)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can probably use the * selector here -> `.rv-esri-map .layersDiv > *:not(:first)`
</blockquote></details>

:+1: re-tested on feature, dynamic, wms, and tile with no issues

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769#-:-KfI9tp7NaQkxdPoDolc:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1769)*

**Pull request merged**
