### PR TITLE
Dynamic and WMS layers

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/216)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 146 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/216#-K84GtiJp_NE-TrWykJz:-K84GtiJp_NE-TrWykK-:1379660377) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e183b5d1e933e4dda7670b7d153afc5a38b77f75/src/app/geo/geo.service.js#L146)):*
Do we always need to set proxy?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/216)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 146 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/216#-K84GtiJp_NE-TrWykJz:-K84QlP5wfqEVuy9Ki11:192396245) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e183b5d1e933e4dda7670b7d153afc5a38b77f75/src/app/geo/geo.service.js#L146)):*
It does not, and I've added a check and will resync the PR if bower ever finishes its update.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/216)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/216)*

**Comment by james-rae** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/216)*

**Pull request merged**
