### PR TITLE
fix(ui): check mark visible on basemap/projection change with blank b…

### LINKED ISSUE #1362: Missing check mark on blank map selector when switching from other projection
Tested build: http://fgpv.cloudapp.net/demo/weekly-1.4.0-5/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

This issue refers to two scenarios:
1.From any base map in Lambert gallery, select Blank Map in Mercator Maps gallery.
2.From any base map in Mercator gallery, select Blank Map in Lambert Maps gallery.

image

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
Missing check mark on blank map selector when switching from other projection #1362

## Testing
Manual testing done

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Closes #1362

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1488)

### CODE REVIEW

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/basemap/basemap.service.js, line 144 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1488#-KYUPWBdr1JRfKqYYNc_:-KYUPWBdr1JRfKqYYNca:b-q8129u) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92011579138c3e81215434235c75f9242fbc169c/src/app/ui/basemap/basemap.service.js#L144)):*
> ```JavaScript
>             // To avoid double checkmark on basemap selection
>             if (bmBlankSelected !== null) {
>                 bmBlankSelected.selected = bmBlankSelected.type === 'blank' ? false : true;
> ```

FYI `===` and `!==` never do type coercion so `bmBlankSelected.type !== 'blank'` will always return a boolean

---

*[src/app/ui/basemap/basemap.service.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1488#-KYUQ6pV2X1sIQOZAh0g:-KYUQ6pV2X1sIQOZAh0h:bxtf3i2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92011579138c3e81215434235c75f9242fbc169c/src/app/ui/basemap/basemap.service.js#L206)):*
> ```JavaScript
>                 const idBlank = 'blank_basemap_' + p.basemaps[0].wkid;
>                 // do we have a selected blank basemap
>                 let selectedBlank = idBlank === bmSelected.id ? true : false;
> ```

const, and `===` is safe (see note above)

---

*[src/app/ui/basemap/basemap.service.js, line 208 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1488#-KYUQ8qR8BWzc2s3ZVmk:-KYUQ8qR8BWzc2s3ZVml:b-7s4sqq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92011579138c3e81215434235c75f9242fbc169c/src/app/ui/basemap/basemap.service.js#L208)):*
> ```JavaScript
>                 let selectedBlank = idBlank === bmSelected.id ? true : false;
> 
>                 let index = p.basemaps.push({
> ```

const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1488#-:-KYUQzjbIoWvSJXLzSVw:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1488)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1488#-:-KYUk-Gm-_2_f6tUZvhg:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1488)*

**Pull request merged**
