### PR TITLE
Legend icons come from local SVG legend

### PR DESCRIPTION
**Pull request by james-rae**
Legend control no longer fetches icons from ArcGIS Server for Dynamic Layers, Feature Layers, or files
Enables support for icons from files and endpoints hosted in FeatureServers

@AleksueiR you will probably have some comments on the image padding

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/902

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/907)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/legend.service.js, line 259 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907#-KMzIpLHtO44Hez4zU_w:-KMzIpLHtO44Hez4zU_x:1366063509) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/761831c41a09e49ecb24130272697d9d4f8fde92/src/app/geo/legend.service.js#L259)):*
> ```JavaScript
>          * @returns {Array} array of legend items
>          *
>         function getMapServerSymbology(layerUrl) {
> ```

Do we still need this function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907)*

**Comment by james-rae** [comment]
*[src/app/geo/legend.service.js, line 259 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907#-KMzIpLHtO44Hez4zU_w:-KMzK8msh1_y6X0gq5y7:780788829) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/761831c41a09e49ecb24130272697d9d4f8fde92/src/app/geo/legend.service.js#L259)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Do we still need this function?
</details>
I'm unsure. If we want a map tile layer to fully populate it's symbols / legend in the TOC, we will likely use this. Currently it does not, it just makes a single entry in the legend with the default icon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/legend.service.js, line 259 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907#-KMzIpLHtO44Hez4zU_w:-KMzORYgWu_GByoh57rE:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/761831c41a09e49ecb24130272697d9d4f8fde92/src/app/geo/legend.service.js#L259)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> I'm unsure. If we want a map tile layer to fully populate it's symbols / legend in the TOC, we will likely use this. Currently it does not, it just makes a single entry in the legend with the default icon.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/907)*

**Pull request merged**
