### PR TITLE
Feature/details

### PR DESCRIPTION
**Pull request by james-rae**
PR is mainly for review by experienced UI peoples :person_with_blond_hair: :thought_balloon: 

See a sample of the hideousness [here](http://sncr01wbingsdv1.ncr.int.ec.gc.ca/ramp_sample/listguts/index-one.html).

Main issues I havn't been able to solve

* text in key column is covered or bleeding into the value column (depending on `overflow` setting).  may need some concatenation magic, or bigger pane.
* zebra striping fail. internet searches for SCSS examples quite scarce or i search with bad terms. the colour is being applied but list item heights are 0 :rooster: 
* I'm certain my SCSS classes are not structured properly (e.g. key and value classes are almost identical)

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/368)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368)*

**Comment by spencerwahl** [comment]
^ I can show you the css tomorrow, not too many changes to make

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368#-:-KBybr2Y1k3ujWe84SxS:-1074382758)*

**Comment by AleksueiR** [comment]
:+1: 

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 207 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368#-KC0sQ9Fi0-_Uvpkvy37:-KC0sQ9Fi0-_Uvpkvy38:2119791806) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9c135aac50807cdd5f841524527352bd2d2d1890/src/app/geo/identify.service.js#L207)):*
Put `format` in the `requester` property, that's what it's here for. Make it an object to also store `name`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368#-:-KC0tv9sAKQux_72n7LY:-510466975)*

**Comment by james-rae** [comment]
Thanks for the secrets, spencer.

Only remaining issues:
- We probably want some type of "enhance" on the ellipsis'd text, similar to RAMP.  Right now it looks fine but you can't see the full text without dev tools
- Some list items are generating a scrollbar if the "value" field is very long with no breaking characters (spaces, dashes)

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368#-:-KC1Or3I90sTQZgQuanr:2106801776)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368)*

**Comment by AleksueiR** [comment]
I think this would do for now. You can open an issue on Github to solve these problems later.

---

Reviewed 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368#-:-KC1Q-CK40fGECBHXdT_:-1469936133)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 3 files at r1, 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/368)*

**Pull request merged**
