### PR TITLE
feat(geo): use aliases in identify results

### PR DESCRIPTION
**Pull request by james-rae**
Apply aliases to feature layer click results.
Needs fix for proper formatting in detail pane
Tests Later™

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/349)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBA0unSYmMrffSEyTR_:-KBA0unTPh80KPy1lkix:95155552) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L59)):*
How about `Array.find`?

```js
field = fields.find(f => f.name === key && f.alias && f.alias.length > 0);
if (field) {
  fieldName = field.alias;
}
```

---

*[src/app/geo/identify.service.js, line 71 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KB9u6vyRWqBxOHXSsFk:-KB9u6vyRWqBxOHXSsFl:1837177818) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L71)):*
I think identifyService should only be responsible for structuring the data in a tabular fashion.  Actual rendering of the table / styling should be handled by a directive.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 71 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KB9u6vyRWqBxOHXSsFk:-KBDCnH4MCAZSZTC_wmE:1807615272) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L71)):*
Agree, rendering should be done by a directive.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBA0unSYmMrffSEyTR_:-KBDSDmUUdHGhEaFepBZ:1139065165) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L59)):*
.find is [not supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility) in IE, unfortunately.

---

*[src/app/geo/identify.service.js, line 71 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KB9u6vyRWqBxOHXSsFk:-KBDSHW2JcVhuCgRX2cS:-1461896182) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L71)):*
Sounds good to me.  If we have an appropriate "tabular structure" I can apply it now, otherwise I will insert a FIXME to apply it once we decide what it is.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBA0unSYmMrffSEyTR_:-KBOEGYh3EcogyGL-dOU:1854835411) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L59)):*
How about we add find [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill)? It is a useful function.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBA0unSYmMrffSEyTR_:-KBOFVFvpLiKislv23tR:605290326) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L59)):*
array.find seems to be even faster than array.indexOf: http://jsperf.com/indexof-angularjs-vs-native/4

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBA0unSYmMrffSEyTR_:-KBOkQXbTszNWkuyyyIt:269512156) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L59)):*
:white_check_mark: nothing is ever supported in IE, but I think adding polyfills makes more sense than limiting our code (unless the polyfills are really bad like the CORS XHR one from RAMP).

---

*[src/app/geo/identify.service.js, line 71 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KB9u6vyRWqBxOHXSsFk:-KBOjDpFnjVIY3XKSs_L:603360774) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L71)):*
I think a FIXME is fine.  If this is always going to be a 2 column table then we can go with `[ [label1, value1], [label2, value2], ... ]` I'm guessing this would be relatively easy for a repeat directive to consume.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBA0unSYmMrffSEyTR_:-KBOrU0S6tKweFjDGVsP:-1489167872) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L59)):*
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/356

I'll add it to `app.seed` for now. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBA0unSYmMrffSEyTR_:-KBOsJg5NUsEEeqBQKYD:1295753406) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9171a16b7ff6f05bb5a56b42e9abc8c2895b49da/src/app/geo/identify.service.js#L59)):*
"limiting our code" uhhh looks to me like the mighty `every` function smashed the limitations like a steam locomotive :boom: :no_bicycles: :steam_locomotive: :railway_car: :railway_car: :dash:  . But since i can easily trick a student into applying the polyfill at a later date, i will agree to your schemes.  TODO and github tasks created.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 61 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349#-KBOuY2eBX_haeRAjvxn:-KBOuY2f63Fs_69prKVs:677419780) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d1c60659a158eba95dcdc90c0ec7b65031c94cbb/src/app/geo/identify.service.js#L61)):*
`=>`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/349)*

**Pull request merged**
