### PR TITLE
feat(mrnu): add about map in main menu to show map description

### LINKED ISSUE #1790: Create an about button in sidenav for map description
Add a button in sidenav panel where map author can add map description text.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1790

## Description

Add about map for map description to main menu

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1806)

### CODE REVIEW

**Comment by milesap** [comment]
I think it would be better to have markdown support for the about map text, following a similar structure to the recently added help section. Split english and french into two separate markdown files in the src/locales/** folder then use the `marked` library (see `help.directive.js` for an example) 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-Kg-43KKQa0QdhgEYbvw:bhevili)*

**Comment by milesap** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/about-dialog.html, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-Kg-79mBcvBT2Ww3PyTW:-Kg-79mBcvBT2Ww3PyTX:b-w5lajm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c582d385b0b2772ec1f83500cc617f15c760d140/src/app/ui/sidenav/about-dialog.html#L3)):*
> ```HTML
> <md-dialog aria-label="{{'sidenav.label.about' | translate}}" class="side-nav-about">
>     <rv-content-pane close-panel="self.close()" title-style="title" title-value="{{'sidenav.label.about' | translate}}">
>         <p class="rv-aboutDesc" ng-bind-html="self.about" tabindex="-2"></p> 
> ```

:+1: for tabindex="-2", your becoming a FM expert

---

*[src/app/ui/sidenav/sidenav.service.js, line 271 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-Kg-6U4I1p3cipd-a-sU:-Kg-6U4I1p3cipd-a-sV:b-rcs3m3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c582d385b0b2772ec1f83500cc617f15c760d140/src/app/ui/sidenav/sidenav.service.js#L271)):*
> ```JavaScript
> 
>             // get about map description
>             configService.getCurrent().then(conf => self.about = conf.about ? conf.about : null);
> ```

This should be equivalent: `configService.getCurrent().then(conf => self.about = conf.about);`

---

*[src/content/styles/modules/_side-nav.scss, line 34 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-Kg-6AGqB1o331PytMye:-Kg-6AGqB1o331PytMyf:btb9isi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c582d385b0b2772ec1f83500cc617f15c760d140/src/content/styles/modules/_side-nav.scss#L34)):*
> ```SCSS
> 
>         p {
>             overflow-y: scroll;
> ```

This may be causing a double scroll bar:



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806)*

**Comment by AleksueiR** [comment]
I think this is a great idea, since we already have markdown parser added to the core. :+1: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-Kg-7sIbFi7HtrdVIc9g:b-pyzakw)*

**Comment by jolevesq** [comment]
But the text in the about should be inside the config file so when author creates a map with the config he can add a description. Can we have the text in the config file and use markdown?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-Kg-K543ScYKFWbiRECC:b-t9l17d)*

**Comment by AleksueiR** [comment]
We can add markdown to the config, but it will be ugly since JSON doesn't allow real line breaks. Any long text will look ugly in there anyway. I guess it all depends on how long the "about" descriptions will be. If it's just one or two sentences, it's okay to put them into a config, but if you want more text, with formatting and images, it's really cumbersome to add it  to the config (need to stringify that html) and will be hard to debug.

What about a two-sided approach: if the description is small and without formatting, add it directly to the config; if long and required formatting and images, it will be loaded from a markdown file.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-Kg-L9SIbnkXT93k5-NH:buy1ass)*

**Comment by jolevesq** [comment]
This can be a good compromise. I think, from what users put in their map with GCViz, it will be mostly few text lines some of then with links.  But some user will want to have a nice description with images for sure. I will update the code for this. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-Kg-T5Shyew3U1HEMp61:b-bwcqnj)*

**Comment by jolevesq** [comment]
Review status: 2 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.service.js, line 271 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-Kg-6U4I1p3cipd-a-sU:-Kg0GWSYMqnUvpplBvhZ:bxmn59l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c582d385b0b2772ec1f83500cc617f15c760d140/src/app/ui/sidenav/sidenav.service.js#L271)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

This should be equivalent: `configService.getCurrent().then(conf => self.about = conf.about);`
</blockquote></details>

You are right, better like this. Done

---

*[src/content/styles/modules/_side-nav.scss, line 34 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-Kg-6AGqB1o331PytMye:-Kg-gP4gs3RBsnrL9Ack:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c582d385b0b2772ec1f83500cc617f15c760d140/src/content/styles/modules/_side-nav.scss#L34)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

This may be causing a double scroll bar:



</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806)*

**Comment by AleksueiR** [comment]
This looks great! Works fine on `index-one` and `index-fgp-en/fr`.

Noticed that `index-mobile` throws an error when trying to open the about widnow:
> TypeError: Cannot read property 'type' of undefined
    at core.js:110774
    at angular.js:16696
    at m.$eval (angular.js:17994)
    at m.$digest (angular.js:17808)
    at m.$apply (angular.js:18102)
    at HTMLButtonElement.<anonymous> (angular.js:26597)
    at HTMLButtonElement.dispatch (jquery-2.2.0.min.js:3)
    at HTMLButtonElement.r.handle (jquery-2.2.0.min.js:3)

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-Kg0ZGICe4fkt6j5bUka:b-uh2fuv)*

**Comment by jolevesq** [comment]
it is because the about is in the array of button but the type is not define in the about property I will update the config file.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-KgJnnYc42lKsVyEJ8Dy:bh5oqp5)*

**Comment by jolevesq** [comment]
I removed the about from the default array of control. if a user wants the button he needs to explicitly say it in the config.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-KgJt7LGBQ6bXRQi14pK:b-2t4j5u)*

**Comment by jolevesq** [comment]
Review status: 12 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/sidenav/about-dialog.html, line 3 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-Kg-79mBcvBT2Ww3PyTW:-KgJtMQblcTBZWRGG642:b-awrxcq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c582d385b0b2772ec1f83500cc617f15c760d140/src/app/ui/sidenav/about-dialog.html#L3)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

:+1: for tabindex="-2", your becoming a FM expert
</blockquote></details>

Thanks :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806)*

**Comment by AleksueiR** [comment]
If you require the map author to explicitly add `about` button to the map nav section, should the `about` button be also turned off by default in the side menu?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-KgUeZD-PkrQKHt2wYAT:bny79pl)*

**Comment by jolevesq** [comment]
if it is not inside the config file it will not appear on the menu. In config.rcs.en-CA there is an about description but about is not inside the array of button so it will not be added to the map.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-KgUezXx6CU_bbH1n8o2:b-1j6kdr)*

**Comment by AleksueiR** [comment]
Ah, I see, you just added it to the menu, but not the map nav cluster through the config. Thanks. :+1: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-KgVT9HFtkEEcJYC_ZHC:b-gqq0iy)*

**Comment by alyec** [comment]
Reviewed 2 of 7 files at r1, 10 of 12 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806)*

**Comment by milesap** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r1, 10 of 12 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1806#-:-KgZHQ9G_7V1T-2qw_qx:bnfp4nl)*

**Comment by milesap** [comment]
Muffin basket offence

**Pull request merged**
