### PR TITLE
feat(core): add support for extension loading

### PR DESCRIPTION
**Pull request by milesap**
## Description
- Adds support for loading extensions via the `rz-extensions` map property. Since `rv-extensions` is being used as a script loader for the deprecated plugin system I denoted it as `rz`. 
- Changed how intentions are loaded - `plugin-loader.ts` now handles both types
- `preInit` can only return void or promises that resolve to void (instead of any type). RAMP assumes it is well defined with all needed methods and properties.

## Testing
- `index-extention.html` loads both an extension that halts map creation by 5 seconds and a custom epsg intention.

## Documentation
None, yet

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773)

### CODE REVIEW

**Comment by barryytm** [comment]
Reviewed 320 of 326 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: 325 of 326 files reviewed, 2 unresolved discussions (waiting on @milesap, @barryytm, and @james-rae)

---

*[src/app/geo/map.service.js, line 151 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LEzo1ZRAhhm_CqfUkFV:-LEzo1ZS-1JEEnL7s7QI:b-b96ad5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/61bca1f44394a2c9a87b0cef6d8bd2ad5d3b0525/src/app/geo/map.service.js#L151)):*
> ```JavaScript
> 
>         // unsubscribe events
>         events.$unsubscribe(events.rvFeatureMouseOver, events.rvEPSGPreInited, events.rvIntentionsPreInited);
> ```

Since this is the only only place 

---

*[src/content/samples/index-extention.tpl, line 29 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LEzpseeEGGXfTs7qQd9:-LEzpseeEGGXfTs7qQdA:byp37u0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/050ae5712a688d3d4dfc2934b34ad4e8086a05dd/src/content/samples/index-extention.tpl#L29)):*
> ```Smarty
>         preInit: () => {
>             console.warn('Loading delayed by 5 seconds.');
>             return new Promise(a => setTimeout(a, 5000));
> ```

What would happen if the page doesn't halt for 5 seconds?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773)*

**Comment by milesap** [comment]
Review status: 325 of 326 files reviewed, 2 unresolved discussions (waiting on @barryytm, @milesap, and @james-rae)

---

*[src/app/geo/map.service.js, line 151 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LEzo1ZRAhhm_CqfUkFV:-LF2MQcI9qBiR5sp2cDN:b-8ssttt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/61bca1f44394a2c9a87b0cef6d8bd2ad5d3b0525/src/app/geo/map.service.js#L151)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Since this is the only only place 
</blockquote></details>

 |
 V

---

*[src/content/samples/index-extention.tpl, line 29 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LEzpseeEGGXfTs7qQd9:-LF2MB-9BGJg4nmXBFKP:b-jum68q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/050ae5712a688d3d4dfc2934b34ad4e8086a05dd/src/content/samples/index-extention.tpl#L29)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

What would happen if the page doesn't halt for 5 seconds?
</blockquote></details>

Anarchy. The page should always halt until all plugin promises have resolved (otherwise its a :bug: )

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773)*

**Comment by barryytm** [comment]
Review status: 325 of 326 files reviewed, 1 unresolved discussion (waiting on @barryytm and @james-rae)

---

*[src/app/geo/map.service.js, line 151 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LEzo1ZRAhhm_CqfUkFV:-LFI-Dpp6EMDkedgi01e:b-cy4m69) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/61bca1f44394a2c9a87b0cef6d8bd2ad5d3b0525/src/app/geo/map.service.js#L151)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

 |
 V
</blockquote></details>

Sorry, please ignore it.

---

*[src/content/samples/index-extention.tpl, line 29 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LEzpseeEGGXfTs7qQd9:-LFI-R7g0h1HSknd85vU:b-3r295a) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/050ae5712a688d3d4dfc2934b34ad4e8086a05dd/src/content/samples/index-extention.tpl#L29)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Anarchy. The page should always halt until all plugin promises have resolved (otherwise its a :bug: )
</blockquote></details>

I've tried loading the the other samples pages and they all seemed to be working to me.  Assuming intentions are loaded by default, shouldn't those pages fail referring to what you said?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773)*

**Comment by james-rae** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @milesap)

---

*[api/plugin-loader.ts, line 13 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LFI5ZomCCeyFcutC1MJ:-LFI5ZomCCeyFcutC1MK:b-8ib6l8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/050ae5712a688d3d4dfc2934b34ad4e8086a05dd/api/plugin-loader.ts#L13)):*
> ```XML
>     private mapElem: JQuery<HTMLElement>;
>     private preInitPromises: Promise<void>[] = []; // all preInit promises must resolve prior to map loading
>     
> ```

evil spaces.
will leave this comment open until v2.4.0 is released (blocking an early pull)

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773)*

**Comment by barryytm** [comment]
Reviewed 2 of 326 files at r1, 7 of 7 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773)*

**Comment by james-rae** [comment]
*[api/plugin-loader.ts, line 63 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773#-LGVoaqQ0NZE6mXc_Hwy:-LGVoaqQ0NZE6mXc_Hwz:bqeczpt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ace01bd0da785d00ccacde91768cc77bdcaa0fe5/api/plugin-loader.ts#L63)):*
> ```XML
>             if (p.preInit) {
>                 let returnedValue = p.preInit(this.config);
>     
> ```

lol EVIL!!!!!

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2773)*

**Pull request merged**
