### PR TITLE
Feat/stylemetadata

### PR DESCRIPTION
**Pull request by milesap**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/636)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 71 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KI9BwNsnPd5CFizHo_8:-KI9BwNtccFetr98kjcy:-650452652) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1206d7eeadf764d41812e32c7185f28b55cb49fb/src/app/ui/metadata/metadata-content.directive.js#L71)):*
> ```JavaScript
> 
>                             if (correctedLength > maxTextLength) {
>                                 textArr[index].shortText += '... <br><a href="#" ng-click="show(' +
> ```

Using ES6 string substitution might be nicer (this isn't in our style guide so it's up to the dev's preference):
```js
`... <br><a href="#" ng-click="show(${index})">Show More</a>`
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by milesap** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 71 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KI9BwNsnPd5CFizHo_8:-KID-NzdGe4M1WM_E9ro:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1206d7eeadf764d41812e32c7185f28b55cb49fb/src/app/ui/metadata/metadata-content.directive.js#L71)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Using ES6 string substitution might be nicer (this isn't in our style guide so it's up to the dev's preference):
> ```js
> `... <br><a href="#" ng-click="show(${index})">Show More</a>`
> ```
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 48 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KID12kVVYwNwO5kihSD:-KID12kVVYwNwO5kihSE:1134351368) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2128b4ce2a4f87224589031f1313622ba21b722a/src/app/ui/metadata/metadata-content.directive.js#L48)):*
> ```JavaScript
>             scope.$watch('self.display.data', metadata => {
>                 if (metadata) {
>                     el.append(angular.copy(metadata)); // copy fragment so that it is inserted for both panels and modals
> ```

Does the `metadata` get modified if you are not using `copy`? What about `angular.element`?

---

*[src/app/ui/metadata/metadata-content.directive.js, line 49 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KID1AdbsErOb79WLDIm:-KID1AdbsErOb79WLDIn:1133907846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2128b4ce2a4f87224589031f1313622ba21b722a/src/app/ui/metadata/metadata-content.directive.js#L49)):*
> ```JavaScript
>                 if (metadata) {
>                     el.append(angular.copy(metadata)); // copy fragment so that it is inserted for both panels and modals
>                     el.find('h5').addClass('md-title').css('margin', '0');
> ```

This should be done in the `xsl` file itself, not in code.
Also, please add the `xsl` file to the source under the `content/medatata` folder, we need to stop referencing RAMP's repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 49 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KID1AdbsErOb79WLDIm:-KID8Wq_XBgzckSRI0i7:-1326337929) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2128b4ce2a4f87224589031f1313622ba21b722a/src/app/ui/metadata/metadata-content.directive.js#L49)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This should be done in the `xsl` file itself, not in code.
> Also, please add the `xsl` file to the source under the `content/medatata` folder, we need to stop referencing RAMP's repo.
</details>
Idea, maybe not for now: how about pulling in the xsl file as a string constant during the build process?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 49 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KID1AdbsErOb79WLDIm:-KID9Dg_F7FCE9tl_aMd:39382008) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2128b4ce2a4f87224589031f1313622ba21b722a/src/app/ui/metadata/metadata-content.directive.js#L49)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Idea, maybe not for now: how about pulling in the xsl file as a string constant during the build process?
</details>
Good idea! Can you add it to our [Optimization Epic](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/519)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 48 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KID12kVVYwNwO5kihSD:-KIDA8PMib4jzFpsxXfY:833810407) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2128b4ce2a4f87224589031f1313622ba21b722a/src/app/ui/metadata/metadata-content.directive.js#L48)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Does the `metadata` get modified if you are not using `copy`? What about `angular.element`?
</details>
This corrects an issue where metadata does not display in the modal since a node can't be in two points of the document simultaneously.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 48 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KID12kVVYwNwO5kihSD:-KIDBcJW8GTBczBVIvB6:1125345276) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2128b4ce2a4f87224589031f1313622ba21b722a/src/app/ui/metadata/metadata-content.directive.js#L48)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> This corrects an issue where metadata does not display in the modal since a node can't be in two points of the document simultaneously.
</details>
Makes sense. :heavy_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by milesap** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 49 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KID1AdbsErOb79WLDIm:-KIDIDGAEzBIf-I-eEha:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2128b4ce2a4f87224589031f1313622ba21b722a/src/app/ui/metadata/metadata-content.directive.js#L49)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Good idea! Can you add it to our [Optimization Epic](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/519)?
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/toc.service.js, line 316 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIDIxeelAwBxxMkmVMP:-KIDIxefjpIFFr_rOcXS:1877401962) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/30294c26cc11ce2b37417ff49de74f5819ca4126/src/app/ui/toc/toc.service.js#L316)):*
> ```JavaScript
>                     // TODO: xsl should come from service constant? or is this layer specific
>                     // following is a test xsl from RAMP, should be updated for FGPV
>                     const xslUrl = 'content/metadata/xstyle_default_en.xsl';
> ```

Now that we are doing this properly, do we need the French version as well or will we be doing some string substitution on the English version to get translated output?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by milesap** [comment]
Review status: 5 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/toc.service.js, line 316 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIDIxeelAwBxxMkmVMP:-KIEI7TmJ9wnknCZBjhR:1206793710) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/30294c26cc11ce2b37417ff49de74f5819ca4126/src/app/ui/toc/toc.service.js#L316)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Now that we are doing this properly, do we need the French version as well or will we be doing some string substitution on the English version to get translated output?
</details>
french support added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 2 of 5 files at r3, 4 of 21 files at r4.
Review status: 8 of 25 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 51 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ4KGtrSpJrPQMDTAr:-KIQ4KGtrSpJrPQMDTAs:1368134160) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L51)):*
> ```JavaScript
>                 }
> 
>                 attr.$observe('maxTextLength', function (maxTextLength) {
> ```

Non-blocking: I think this should be its own directive; it might be useful for truncating text elsewhere. Have you looked at any existing truncate directives? Are there any good ones?

---

*[src/app/ui/metadata/metadata-content.directive.js, line 61 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ2o6hcYp9GA9Dthww:-KIQ2o6hcYp9GA9Dthwx:-567882003) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L61)):*
> ```JavaScript
> 
>                             // do not count HTML tags, more than one successive whitespace, or newlines towards the maxTextLength
>                             const correctedLength = longText.replace(/<[^>]+>/gm, '').replace(/ +(?= )/g, '').replace(/(\r\n|\n|\r)/gm, '').length;
> ```

Non-blocking: Would `longText.innerText.length` work?

---

*[src/app/ui/metadata/metadata-content.directive.js, line 71 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ4F8ys-602Srryjza:-KIQ4F8ys-602Srryjzb:-1256701180) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L71)):*
> ```JavaScript
>                             if (correctedLength > maxTextLength) {
>                                 textArr[index].shortText +=
>                                     `... <br><a href="#" ng-click="show(${index})">Show More</a>`;
> ```

Needs translations.

---

*[src/content/metadata/xstyle_default_en-CA.xsl, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ6hjbh6FuM1YG0P4u:-KIQ6hjbh6FuM1YG0P4v:-262673331) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/content/metadata/xstyle_default_en-CA.xsl#L22)):*
> ```XSLT
> 
>       <xsl:if test="//gmd:abstract/gco:CharacterString/text() != ''">
>         <h5 class="md-title" style="margin:0;">Abstract</h5>
> ```

I know some people love inline CSS :smile: , but in general we avoid them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by milesap** [comment]
Review status: 6 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 51 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ4KGtrSpJrPQMDTAr:-KIZ2KvGd3iwpNHtD7JX:499603632) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L51)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Non-blocking: I think this should be its own directive; it might be useful for truncating text elsewhere. Have you looked at any existing truncate directives? Are there any good ones?
</details>
Good idea, moved as own directive. Briefly looked for alternatives but mine is the best :smile: 

---

*[src/app/ui/metadata/metadata-content.directive.js, line 61 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ2o6hcYp9GA9Dthww:-KIZ3vABZoaJzNSFCwJX:-918628093) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L61)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Non-blocking: Would `longText.innerText.length` work?
</details>
I briefly tried this, but caused an error where length is undefined. I will read up on innerText for possible future use.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 71 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ4F8ys-602Srryjza:-KIZ3rFfq0YG0aeByAZ5:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L71)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Needs translations.
</details>
:+1: 

---

*[src/content/metadata/xstyle_default_en-CA.xsl, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ6hjbh6FuM1YG0P4u:-KIZ3tm5hUSwvpu3M0Q1:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/content/metadata/xstyle_default_en-CA.xsl#L22)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I know some people love inline CSS :smile: , but in general we avoid them.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by alyec** [comment]
Reviewed 6 of 21 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/ui/common/truncate.directive.js, line 15 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIZ62EXbBFSF-5e8xjf:-KIZ62EXbBFSF-5e8xjg:-247980955) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e44e6dd7dec5d7703dfc78a4ae94df68aba0990/src/app/ui/common/truncate.directive.js#L15)):*
> ```JavaScript
>      * If maxTextLength is not defined or less than 1 this directive has no effect.
>      *
>      * <rv-truncate limit="7">Some text to shorten</rv-truncate>
> ```

Should this be `maxTextLength` in the example?

---

*[src/app/ui/common/truncate.directive.js, line 66 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIZ6H79TKu5cAr-mUGS:-KIZ6H79TKu5cAr-mUGT:-1581246246) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e44e6dd7dec5d7703dfc78a4ae94df68aba0990/src/app/ui/common/truncate.directive.js#L66)):*
> ```JavaScript
>                     changeTxt(shortText);
> 
>                     scope.show = () => {
> ```

style question: we may want to encourage dropping braces for single line functions (`scope.show = () => changeTxt(longText);`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by milesap** [comment]
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### Feat/stylemetadata
</details>


---

Review status: 14 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/ui/common/truncate.directive.js, line 15 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIZ62EXbBFSF-5e8xjf:-KIbf4NjoyE678W9o90y:817434397) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e44e6dd7dec5d7703dfc78a4ae94df68aba0990/src/app/ui/common/truncate.directive.js#L15)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Should this be `maxTextLength` in the example?
</details>
Nice catch

---

*[src/app/ui/common/truncate.directive.js, line 66 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIZ6H79TKu5cAr-mUGS:-KIbf0wnujluz9l38wdK:432021016) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e44e6dd7dec5d7703dfc78a4ae94df68aba0990/src/app/ui/common/truncate.directive.js#L66)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> style question: we may want to encourage dropping braces for single line functions (`scope.show = () => changeTxt(longText);`)
</details>
I like it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-:-KIbfCgvxsrODTx33hTY:-1544071435)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r1, 2 of 4 files at r2, 1 of 5 files at r3, 6 of 21 files at r4, 5 of 6 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/metadata/metadata-content.directive.js, line 51 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ4KGtrSpJrPQMDTAr:-KIcMqvJXarnsSapd9hS:5174689) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L51)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Good idea, moved as own directive. Briefly looked for alternatives but mine is the best :smile: 
</details>
ok

---

*[src/app/ui/metadata/metadata-content.directive.js, line 71 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636#-KIQ4F8ys-602Srryjza:-KIcN-fK58qqjA46AWZn:5174689) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecc588457e51b2ac36967f349f548d18451d819b/src/app/ui/metadata/metadata-content.directive.js#L71)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> :+1: 
</details>
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/636)*

**Comment by mweech** [comment]
address #608

**Pull request merged**
