### PR TITLE
fix(filters): not able to load sublayer in Eco

### LINKED ISSUE #1593: Datagrid not loading for all sub-layers under EcoAction Community Funded Projects
Tested build http://fgpv.cloudapp.net/demo/v1.5.0-11/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

image

Console error:
> core.js:12798 RangeError: Invalid string length
    at Array.join (native)
    at getColumnWidth (http://fgpv.cloudapp.net/demo/develop/dev/lib/core.js:132393:73)

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Closes #1593

## Testing

Eye

## Documentation

Inline
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1615)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 263 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615#-KaxGydrx9l2EuU-HUaa:-KaxGydrx9l2EuU-HUab:b-pd9ig) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/af5be79339b63f17312950c2804dffaab21508a4/src/app/ui/filters/filters-default.directive.js#L263)):*
> ```JavaScript
>                         // some layer like http://section917.cloudapp.net/arcgis/rest/services/EcoGeo/MapServer/6
>                         // can have length = 2147483647 and it make the function crash
>                         length = (length < 500) ? length : 500;
> ```

Can you move 500 into a constant and put it at the top of the file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 263 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615#-KaxGydrx9l2EuU-HUaa:-KbAToq-A7VYF0dqiAfw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/af5be79339b63f17312950c2804dffaab21508a4/src/app/ui/filters/filters-default.directive.js#L263)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you move 500 into a constant and put it at the top of the file?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 263 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615#-KaxGydrx9l2EuU-HUaa:-KbAV0XkAPtR13r6vYwU:b556ppv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/af5be79339b63f17312950c2804dffaab21508a4/src/app/ui/filters/filters-default.directive.js#L263)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Awesome, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615#-:-KbAVUXrrHYeMO7sUdrG:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1615)*

**Pull request merged**
