### PR TITLE
fix(ui): fix datagrid blank out afyter morph

### LINKED ISSUE #372: bug(ui): datatable grid blanks out after morph
Steps:
1. Open datatable panel
2. Switch to the maximized view
3. Scroll to the very bottom
4. Switch to the split view
5. Observe bottom of the grid blanking out

It's restores after scrolling up and down a bit.

Probably need to call draw on the table after the morph event.

datatable_draw_after_morph

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #372

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/672)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 307 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImhwEuuGBCfeWUNQXK:-KImhwEuuGBCfeWUNQXL:-1914815314) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L307)):*
> ```JavaScript
>                     // because of no redraw datatable info does not update, set info manually
>                     // TODO: make sure it works for French translation as well
>                     let info = self.table.containers()[0].getElementsByClassName('dataTables_info')[0];
> ```

This can potentially break if the class name changes or datatables changes how they structure the info line. I looked through their API and there doesn't seem to be a good way to actually edit the info line, so I don't think there is a better way.

---

*[src/app/ui/filters/filters-default.directive.js, line 308 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImjy9pqrpbnaZlqKiW:-KImjy9pqrpbnaZlqKiX:812854819) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L308)):*
> ```JavaScript
>                     // TODO: make sure it works for French translation as well
>                     let info = self.table.containers()[0].getElementsByClassName('dataTables_info')[0];
>                     let infos = info.innerText.split(' ');
> ```

Both `let`s can be `const`s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 307 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImhwEuuGBCfeWUNQXK:-KImuiAGEM3bYey8Zmuv:-1042741412) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L307)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This can potentially break if the class name changes or datatables changes how they structure the info line. I looked through their API and there doesn't seem to be a good way to actually edit the info line, so I don't think there is a better way.
</details>
I agree, I search a while to find a better way but no luck

---

*[src/app/ui/filters/filters-default.directive.js, line 308 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImjy9pqrpbnaZlqKiW:-KImv0Cmvx1_-_oavOVK:312694991) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L308)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Both `let`s can be `const`s.
</details>
Should i use let when I modify the value and const when I dont?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 308 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImjy9pqrpbnaZlqKiW:-KImvIz5q-Zaol1x_5Sh:-113399545) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L308)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Should i use let when I modify the value and const when I dont?
</details>
Exactly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 308 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImjy9pqrpbnaZlqKiW:-KImvb31hwTKtGC9eCh9:-1445760554) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L308)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Exactly.
</details>
in this case I modify infos and info.innerText. It is why I put let instead of const. I am a little bit confuse on let vs const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 308 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImjy9pqrpbnaZlqKiW:-KImw8VJrcib1MV8B80i:-2101381472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L308)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> in this case I modify infos and info.innerText. It is why I put let instead of const. I am a little bit confuse on let vs const
</details>
If `const` is an object, you can modify its properties; you just can't.

```js
const a = 1;
a = 2 // this is wrong

const a = {};
a.a = 1; // this is okay
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 308 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImjy9pqrpbnaZlqKiW:-KImzSZuB6FhKLTZ5eXL:2085201536) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L308)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> If `const` is an object, you can modify its properties; you just can't.
> 
> ```js
> const a = 1;
> a = 2 // this is wrong
> 
> const a = {};
> a.a = 1; // this is okay
> ```
</details>
... you just can't reassign it to something else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 308 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672#-KImjy9pqrpbnaZlqKiW:-KIn2ej6PNk8cU7Qqy_I:570779025) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0060ecb7fdd4dea08416d2744fac335417c8addc/src/app/ui/filters/filters-default.directive.js#L308)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> ... you just can't reassign it to something else.
</details>
Thanks for the info, I do the modifications and I will resubmit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/672)*

**Pull request merged**
