### PR TITLE
chore(build): update angular and other dependencies

### LINKED ISSUE #370: Upgrade to Angular 1.6.3
Release notes: http://angularjs.blogspot.ca/2016/02/angular-150-ennoblement-facilitation.html
Migration guide: https://docs.angularjs.org/guide/migration#migrating-from-1-4-to-1-5

### PR DESCRIPTION
**Pull request by milesap**
## Description
- updates angular to v1.6.3
- updates angular related dependencies to v1.6.3
- updates many other packages such as jasmine-core, phantomjs and some
karma libs so that they are compatible with v1.6.3
- minor changes to viewer

Closes #370

## Testing
Yes

## Documentation
No

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1820)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 90 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1820#-KgV3dE-xPDAbkLWuJjL:-KgV3dE-xPDAbkLWuJjM:bb76mu4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd10b92eadd5c70197b5b062060d3a144bc844c7/package.json#L90)):*
> ```JSON
>   },
>   "scripts": {
>     "postinstall": "bower install",
> ```

Why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1820)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index-mobile.html, line 20 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1820#-KgV4TErQPD6GEGk7Ova:-KgV4TErQPD6GEGk7Ovb:bclh53c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8bd659dbd93d33487a0f975843c3dcbc3e015f8f/src/index-mobile.html#L20)):*
> ```HTML
>     
>     <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
>     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.11/angular.min.js"></script>
> ```

I think we still need a mismatched angular version to test against (we can change the specific version if it makes sense to).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1820)*

**Comment by AleksueiR** [comment]
Maybe this should be in 2.0 - needs more testing to make sure nothing is broken.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1820#-:-KgV5sRkzTtFarJN7y_v:bhpy82p)*

**Comment by milesap** [comment]
New PR #1821 targets v2.0 - moving to 1.6.3 is a breaking change. Closing this one

**Pull request closed without merging**
