### PR TITLE
Add expand buttons to large images

### LINKED ISSUE #1298: Add expand button to large images in layer info sections and symbology stacks
If an info section or symbology image is wider than the main panel, shrink it to fit and add an expand button that will show the full original image.

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #1298

Add button to expand large images in the symbology stacks and layer info sections. 

## Testing

Sample `69. Big images in layer info/symbology`

## Documentation

in-line comments

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)

### CODE REVIEW

**Comment by dane-thomas** [comment]
If you see this on the last image try refreshing. It seems to be an issue with how the samples page loads the config. Should be fixed in #2769

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-:-LEVVfAk3SfXC5qB2a_O:b-wcx5ov)*

**Comment by ShrutiVellanki** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
! get lots of these:


Maybe the onload event fires before the element container width has settled. 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/app/ui/toc/symbology-stack.directive.js, line 170 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEk3qUqD02zbzZnwxCR:-LEk3qUrCWfVFnYbaakm:b-uqhy2t) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7225fdb962434aa78bca8649b7d14735318c626e/src/app/ui/toc/symbology-stack.directive.js#L170)):*
> ```JavaScript
>         self.onExpandClick = name => {
>             const image = self.symbology.images[name];
>             const htmlContent = "</img>";
> ```

You can use ES6 string literal here:
```html
`<img src="${image}"></img>`
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-:-LEk4KwEAUB510Y-aBz9:b-a3um3)*

**Comment by dane-thomas** [comment]
The width of the element was negative when not expanded so it was giving a false positive. Should be fixed now. Thanks

---

Review status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @ShrutiVellanki, @AleksueiR, @barryytm, @james-rae, and @JahidAhmed)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 170 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEk3qUqD02zbzZnwxCR:-LEom2G24-wNTlzIHAm9:b7kzj3s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7225fdb962434aa78bca8649b7d14735318c626e/src/app/ui/toc/symbology-stack.directive.js#L170)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can use ES6 string literal here:
```html
`<img src="${image}"></img>`
```
</blockquote></details>

done thanks :+1:

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-:-LEom5vwE63insXnFdnD:bcenwce)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 11 files at r1, 3 of 5 files at r2, 6 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas, @barryytm, @james-rae, and @JahidAhmed)

---

*[src/app/ui/common/expand-image.service.js, line 32 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEpEPB72ou671wCBdtZ:-LEpEPB72ou671wCBdt_:bqyq0rz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/app/ui/common/expand-image.service.js#L32)):*
> ```JavaScript
>         // if size is bigger than 80% of window make dialog 80% and have the image handled with overflow
>         const img = new Image();
>         img.onload = function() {
> ```

Is this `onLoad` listener needed? The image should be loaded by now since the expand button won't show up unless the image is loaded.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas, @barryytm, @james-rae, and @JahidAhmed)

---

*[src/app/ui/common/expand-image.service.js, line 32 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEpEPB72ou671wCBdtZ:-LEpFsnD8tHo4hBRpGiG:b-1qpxqc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/app/ui/common/expand-image.service.js#L32)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Is this `onLoad` listener needed? The image should be loaded by now since the expand button won't show up unless the image is loaded.
</blockquote></details>

This `onload` is just a way to get the natural dimensions of the image. Couldn't traverse the DOM to find the image because sometimes it wouldn't load in time. 

https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/app/ui/common/expand-image.service.js#L54  gives `img` the source url and triggers the `onload`

If there's a better way to do this I'd be happy to change it. I just did it this way because I couldn't find another way to get it working.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by JahidAhmed** [comment]
Reviewed 4 of 11 files at r1, 2 of 5 files at r2, 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @AleksueiR, @dane-thomas, @barryytm, and @james-rae)

---

*[src/locales/translations.csv, line 202 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEtMrGFCilWscoy74Cw:-LEtMrGFCilWscoy74Cx:bbfz6jx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/locales/translations.csv#L202)):*
> ```CSV
> Table of Content view full-size image,toc.tooltip.viewFullsizeImage,View full-size image,1,Agrandir image,0
> Table of Content close full-size image,toc.fullsizeImage.close,Close,1,Fermer,1
> Table of Content full-size image, toc.tooltip.fullsizeImage, Full-size image, 1, L’image pleine grandeur, 0
> ```

A couple extra spaces were added after the commas for the translation bit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Review status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @AleksueiR, @dane-thomas, @barryytm, and @james-rae)

---

*[src/locales/translations.csv, line 202 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEtMrGFCilWscoy74Cw:-LEtNgI09WCokCveg0ZD:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/locales/translations.csv#L202)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

A couple extra spaces were added after the commas for the translation bit.
</blockquote></details>

donethanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @AleksueiR, @barryytm, and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed, 2 unresolved discussions (waiting on @AleksueiR, @dane-thomas, @barryytm, and @james-rae)

---

*[src/app/ui/common/expand-image.service.js, line 32 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEpEPB72ou671wCBdtZ:-LEuM96GBwj5h44lR64S:b-isr95n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/app/ui/common/expand-image.service.js#L32)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

This `onload` is just a way to get the natural dimensions of the image. Couldn't traverse the DOM to find the image because sometimes it wouldn't load in time. 

https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/app/ui/common/expand-image.service.js#L54  gives `img` the source url and triggers the `onload`

If there's a better way to do this I'd be happy to change it. I just did it this way because I couldn't find another way to get it working.
</blockquote></details>

Yeah, the dialog doesn't want to self-size to fit the image - we have several extra layers on top of the vanilla dialog and something there is breaking the autosizing. Should be fine as is I think. :+1: 

Could you also change the var `image` to `imageUrl` to make it clear this is just a string, not an actual image object.

---

*[src/app/ui/toc/toc.html, line 56 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEuLj2OEq5FcBifzQIV:-LEuLj2OEq5FcBifzQIW:b72gzrk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d28ea9e8ad5889e4eb65c5af6537c5109a832fbe/src/app/ui/toc/toc.html#L56)):*
> ```HTML
>                     ng-class="{ 'rv-selected': block.isSelected }"
>                     ng-click="self.notifyApiClick(block)"></rv-legend-block>
>                 <md-button
> ```

Could you please move this from toc.html to legend-info.html template? The legend itself shouldn't not be rendering additional elements on top of the legend blocks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Review status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @AleksueiR, @dane-thomas, @barryytm, and @james-rae)

---

*[src/app/ui/common/expand-image.service.js, line 32 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEpEPB72ou671wCBdtZ:-LEuPqI6063AAwhkYSs8:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fc017e70ac4b6a42450679e9ba1a3e3473f2f18/src/app/ui/common/expand-image.service.js#L32)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Yeah, the dialog doesn't want to self-size to fit the image - we have several extra layers on top of the vanilla dialog and something there is breaking the autosizing. Should be fine as is I think. :+1: 

Could you also change the var `image` to `imageUrl` to make it clear this is just a string, not an actual image object.
</blockquote></details>

done thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by barryytm** [comment]
Reviewed 4 of 11 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @dane-thomas)

---

*[src/content/samples/config/config-sample-66.json, line 0 at r6](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LF2g75o0A4TqAK71lLr:-LF2g75pA4QByp1BDe9c:b2syoq4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/747a4a36b217989d6f0442af6fd3b6fdeaa89c80/src/content/samples/config/config-sample-66.json#L0)):*
Github is complaining about this file having conflict.  Please resolve this in your next push.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Review status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @AleksueiR, @JahidAhmed, @james-rae, @dane-thomas, @barryytm, and @ShrutiVellanki)

---

*[src/app/ui/toc/toc.html, line 56 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEuLj2OEq5FcBifzQIV:-LF2n43z-5-2VEs_7umo:bltv7r8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c6d8b81a912c1eabd67858a3616215cde55e9e1d/src/app/ui/toc/toc.html#L56)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Could you please move this from toc.html to legend-info.html template? The legend itself shouldn't not be rendering additional elements on top of the legend blocks.
</blockquote></details>

Missed this before. Should be donethanks now

---

*[src/content/samples/config/config-sample-66.json, line  at r6](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LF2g75o0A4TqAK71lLr:-LF2n89D1TH6TPiEiaz7:b-ov13dt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/747a4a36b217989d6f0442af6fd3b6fdeaa89c80/src/content/samples/config/config-sample-66.json#L)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Github is complaining about this file having conflict.  Please resolve this in your next push.
</blockquote></details>

Yep the changes to this config were put in #2781. Donethanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by barryytm** [comment]
Reviewed 2 of 11 files at r1, 2 of 5 files at r2, 2 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 5 of 6 files at r7.
Review status: all files reviewed, 2 unresolved discussions (waiting on @AleksueiR and @dane-thomas)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r6, 4 of 6 files at r7.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by james-rae** [comment]
Reviewed 3 of 6 files at r7.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas)

---

*[src/app/geo/legend-block.class.js, line 400 at r6](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LEyfoV2Ek0vsNL6hxUR:-LFXUqflDMZJU_626x6K:bmx3uty) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/747a4a36b217989d6f0442af6fd3b6fdeaa89c80/src/app/geo/legend-block.class.js#L400)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

everything good here.  this is a blocking comment to prevent a merge prior to v2.4.0 being released.
</blockquote></details>

2.4 is out. Should be okay to merge.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 11 files at r1, 1 of 1 files at r6, 3 of 6 files at r7.
Review status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by barryytm** [comment]
Reviewed 3 of 5 files at r8.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dane-thomas)

---

*[src/app/ui/common/expand-image.service.js, line 33 at r8](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LFrLczJ1LTUuZbjTZhO:-LFrLczJ1LTUuZbjTZhP:b-5jqysc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4e2040a4e104a77745e853be713d6abddf65eb/src/app/ui/common/expand-image.service.js#L33)):*
> ```JavaScript
>         const img = new Image();
>         img.onload = function() {
>             const w = Math.min(this.width + 50, shellNode.width() * 0.8);
> ```

Please change the name of `w` to a more meaningful name.  Same for `h`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by barryytm** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @dane-thomas)

---

*[src/app/ui/common/expand-image.service.js, line 37 at r8](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LFrMYtGD7Onfvpm-Vlr:-LFrMYtGD7Onfvpm-Vls:b-h4e2sa) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4e2040a4e104a77745e853be713d6abddf65eb/src/app/ui/common/expand-image.service.js#L37)):*
> ```JavaScript
> 
>             const template =
>                 `<md-dialog aria-label="{{\'toc.tooltip.fullsizeImage\' | translate}}" class="rv-expanded-dialog" style="width: ${w}px; height: ${h}px;">`+
> ```

Will need Alex's opinion on this.  Should this be turned into a directive or it's fine as it is?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Review status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @AleksueiR, @JahidAhmed, @barryytm, @james-rae, and @dane-thomas)

---

*[src/app/ui/common/expand-image.service.js, line 33 at r8](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LFrLczJ1LTUuZbjTZhO:-LFrOtZS23frM3NaPL05:bcze0ta) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4e2040a4e104a77745e853be713d6abddf65eb/src/app/ui/common/expand-image.service.js#L33)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Please change the name of `w` to a more meaningful name.  Same for `h`.
</blockquote></details>

donethanks.

---

*[src/app/ui/common/expand-image.service.js, line 37 at r8](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LFrMYtGD7Onfvpm-Vlr:-LFrO1t8EgNehQ1kWf_C:bfab7i2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4e2040a4e104a77745e853be713d6abddf65eb/src/app/ui/common/expand-image.service.js#L37)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Will need Alex's opinion on this.  Should this be turned into a directive or it's fine as it is?
</blockquote></details>

Doing this would add a lot of complexity because of how the dialogs are handled by the focus manager. The width and height need to be set per image when the template is compiled. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by barryytm** [comment]
Review status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @AleksueiR, @JahidAhmed, @barryytm, and @james-rae)

---

*[src/app/ui/common/expand-image.service.js, line 37 at r8](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LFrMYtGD7Onfvpm-Vlr:-LFrQSeFD3_WbwWEQm88:b-fqk52g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4e2040a4e104a77745e853be713d6abddf65eb/src/app/ui/common/expand-image.service.js#L37)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

Doing this would add a lot of complexity because of how the dialogs are handled by the focus manager. The width and height need to be set per image when the template is compiled. 
</blockquote></details>

Correct me if I am wrong.  Wouldn't the template needs to be recompiled every time when we open it anyways?   There is also a controller in this file already, so would it be a good idea to turn this file into a directive instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
Review status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @AleksueiR, @JahidAhmed, @barryytm, @james-rae, and @dane-thomas)

---

*[src/app/ui/common/expand-image.service.js, line 37 at r8](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LFrMYtGD7Onfvpm-Vlr:-LFrTPxx8cENiDPPIPNd:b-vznku3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4e2040a4e104a77745e853be713d6abddf65eb/src/app/ui/common/expand-image.service.js#L37)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Correct me if I am wrong.  Wouldn't the template needs to be recompiled every time when we open it anyways?   There is also a controller in this file already, so would it be a good idea to turn this file into a directive instead?
</blockquote></details>

I think this might be a good idea after all. You are compiling the dialog template through the dialog service anyway, so `expandImage` doesn't have to a be service. It can be an attribute directive. Having this as a directive, you can inject the expand button directly after the image node and avoid adding it through the template every time; also, you can avoid adding duplicates of the the trigger code (`expandImageService.open`) to other files.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
Reviewed 12 of 14 files at r11.
Review status: all files reviewed, 3 unresolved discussions (waiting on @barryytm and @dane-thomas)

---

*[src/app/ui/common/failure-image.directive.js, line 15 at r11](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LG0fm9c919jT3Ol42Tv:-LG0fm9c919jT3Ol42Tw:b-pzky2j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd09ad5d4da92a333eb126791c15c48ff0901919/src/app/ui/common/failure-image.directive.js#L15)):*
> ```JavaScript
> function rvFailureImage(configService) {
>     const directive = {
>         restrict: 'A',
> ```

Any reason to change this on to the attribute directive? I don't see any corresponding changes to the templates where it's used.

---

*[src/app/ui/toc/symbology-stack.directive.js, line 631 at r11](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LG0h-km7vohImXKMOk-:-LG0h-km7vohImXKMOk0:bt587c4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd09ad5d4da92a333eb126791c15c48ff0901919/src/app/ui/toc/symbology-stack.directive.js#L631)):*
> ```JavaScript
>             const itemSize = 32; // icon size is fixed
> 
>             const element = symbolItem.image.parent().find('.rv-symbol-expand');
> ```

What does this do? Can you set the display to `none` directly in the CSS `.rv-image-expand` rule instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 5 files at r8.
Review status: all files reviewed, 3 unresolved discussions (waiting on @barryytm and @dane-thomas)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Review status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @AleksueiR, @JahidAhmed, @ShrutiVellanki, @barryytm, @james-rae, and @dane-thomas)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 631 at r11](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LG0h-km7vohImXKMOk-:-LG0iNUYCnUc7uexDgk8:b80geq0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd09ad5d4da92a333eb126791c15c48ff0901919/src/app/ui/toc/symbology-stack.directive.js#L631)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

What does this do? Can you set the display to `none` directly in the CSS `.rv-image-expand` rule instead?
</blockquote></details>

This isn't actually needed any more. Forgot to remove. Donethanks. 

---

*[src/app/ui/common/failure-image.directive.js, line 15 at r11](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LG0fm9c919jT3Ol42Tv:-LG0i-Jj4ON5ZfrLZcS1:b-odpjyb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd09ad5d4da92a333eb126791c15c48ff0901919/src/app/ui/common/failure-image.directive.js#L15)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Any reason to change this on to the attribute directive? I don't see any corresponding changes to the templates where it's used.
</blockquote></details>

accidentally changed. Donethanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r12.
Review status: all files reviewed, 1 unresolved discussion (waiting on @barryytm)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by barryytm** [comment]
Reviewed 10 of 14 files at r11, 1 of 3 files at r12.
Review status: all files reviewed, 2 unresolved discussions (waiting on @barryytm and @dane-thomas)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 760 at r11](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LG0hy-e40iwAWe3sC80:-LG0hy-fC_0MtNe7SyNS:b-80x5a7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd09ad5d4da92a333eb126791c15c48ff0901919/src/app/ui/toc/symbology-stack.directive.js#L760)):*
> ```JavaScript
>                     symbols.length > 0 && symbols[0].image ? renderStyleSwitch[renderStyle](symbols) : symbols;
>             }
> ```

Space

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @barryytm and @dane-thomas)

---

*[src/app/ui/toc/symbology-stack.directive.js, line 760 at r11](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-LG0hy-e40iwAWe3sC80:-LG0las61PhIAxClVjqF:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd09ad5d4da92a333eb126791c15c48ff0901919/src/app/ui/toc/symbology-stack.directive.js#L760)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Space
</blockquote></details>

donethanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by barryytm** [comment]
Reviewed 1 of 1 files at r13.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by AleksueiR** [comment]
:lgtm: :+1: 

---

Reviewed 1 of 1 files at r13.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770#-:-LGUnlHX5NojwoGVIINM:b-8sos09)*

**Comment by james-rae** [comment]
Reviewed 9 of 14 files at r11, 1 of 3 files at r12, 1 of 1 files at r13, 2 of 2 files at r14.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2770)*

**Comment by dane-thomas** [comment]
Small issue found after merging PR console was being flooded with error messages about being unable to find image for icon symbology. Should be fixed in #2817

**Pull request merged**
