### PR TITLE
DataTable UI language switchable and miscellaneous translations

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
- Put in place $translate.instant() wherever needed
- Set language for DataTable on DT creation and DT update (language switch)
- Update translations.csv file

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/857)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/layout/shell.directive.js, line 68 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857#-KMOoGSqQlVmkgakAgvp:-KMOoGSrOBolPpwKKZlw:-88083308) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b17de7024cb26f56e276723b62262d4d98021f40/src/app/layout/shell.directive.js#L68)):*
> ```JavaScript
>                 type: 'heading',
>                 children: [{
>                         name: $translate.instant('sidenav.label.fullscreen'),
> ```

Better to keep translations in templates. 
Use `{{ self.section.name | translate }}` in sidenav/menulink.html.

---

*[src/app/ui/filters/filters-default.directive.js, line 246 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857#-KMOp8CSiBwO5Rw037qJ:-KMOp8CSiBwO5Rw037qK:-1666581449) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b17de7024cb26f56e276723b62262d4d98021f40/src/app/ui/filters/filters-default.directive.js#L246)):*
> ```JavaScript
>         self.display = stateManager.display.filters;
> 
>         self. setDToLang =  setDToLang;
> ```

Space between `self.` and `setDToLang`.

---

*[src/app/ui/filters/filters-default.directive.js, line 307 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857#-KMOtqXoJGcDfDn_TkeP:-KMOtqXoJGcDfDn_TkeQ:10953275) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b17de7024cb26f56e276723b62262d4d98021f40/src/app/ui/filters/filters-default.directive.js#L307)):*
> ```JavaScript
>             // load language object on language switch
>             $rootScope.$on('$translateChangeSuccess', () => {
>                 if (self.table) {
> ```

I would suggest caching strings on initial load and every language change for efficiency, so `getDoLang` function is not called every time a table is created.

---

*[src/app/ui/filters/filters-default.directive.js, line 317 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857#-KMOuGjhmQApzhfPgH3I:-KMOuGji3fR3YlwhuI4B:-1489316057) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b17de7024cb26f56e276723b62262d4d98021f40/src/app/ui/filters/filters-default.directive.js#L317)):*
> ```JavaScript
> 
>         // set language for table
>         function setDToLang() {
> ```

Needs function block comments.

---

*[src/app/ui/filters/filters-default.directive.js, line 321 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857#-KMOtilWxIP1TsJnKURM:-KMOtilWxIP1TsJnKURN:-76186828) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b17de7024cb26f56e276723b62262d4d98021f40/src/app/ui/filters/filters-default.directive.js#L321)):*
> ```JavaScript
>             let oLang = self.table.context[0].oLanguage;
> 
>             oLang = Object.assign(oLang, newLang);
> ```

Can we use `angular.merge` for consistency here? It should work the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 327 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857#-KMOwxHy-wp6dW5rdbd-:-KMOwxHy-wp6dW5rdbd0:350575141) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b17de7024cb26f56e276723b62262d4d98021f40/src/app/ui/filters/filters-default.directive.js#L327)):*
> ```JavaScript
>         function getDToLang() {
>             let oLang = {
>                 sProcessing: $translate.instant('filter.default.label.processing'),
> ```

Some of the repetition here can be cut down a bit.  Unfortunately there is no `Object.map` which would recurse into other objects but since there are only two object properties they could be handled separately:
```js
const prefix = 'filter.default.label';
const oLangSrc = {
  sProcessing: 'processing',
  sInfo: 'info',
  sInfoEmpty: 'zero',
  ...
};
const oPaginateSrc = {
  sFirst: 'first'
};
const oLang = { oPaginate: {} };
Object.keys(oLangSrc).forEach(key => oLang[key] = $translate.instant(`${prefix}.${oLangSrc[key]}`));
Object.keys(oPaginateSrc).forEach(key => oLang.oPaginate[key] = $translate.instant(`${prefix}.${oLangSrc[key]}`));
```

---

*[src/app/ui/filters/filters-default.directive.js, line 329 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857#-KMOxiwkQp-AwmWIao85:-KMOxiwlk_lmuVgPOr0C:1381404245) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b17de7024cb26f56e276723b62262d4d98021f40/src/app/ui/filters/filters-default.directive.js#L329)):*
> ```JavaScript
>                 sProcessing: $translate.instant('filter.default.label.processing'),
>                 sSearch: $translate.instant('filter.default.label.search'),
>                 sLengthMenu: $translate.instant('filter.default.label.lenght.menu'),
> ```

typo: length

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/857)*

**Comment by mweech** [comment]
@ChrisLatRNCan please estimate the effort to address the PR comments and we will pull in to the sprint.

**Comment by AleksueiR** [comment]
Merged as part of #921.

**Pull request closed without merging**
