### PR TITLE
Part 2: basemap re-projection, full extent, overviewmap; 3rd attempt

### PR DESCRIPTION
**Pull request by ec-dev**
Require geoAPI's PR #90 to be completed first and referenced in order to function properly.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/393)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/map.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzrDchrNf17bmGGb0a:-KCzrDcidJEPqfOLg8-1:-514149000) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L24)):*
If we are adding stuff to the global map state, `ref` is probably a bad name for it.

---

*[src/app/geo/map.service.js, line 280 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzpn08jBNKDaqPhgTa:-KCzpn09ogQSkY1o7fBx:754192486) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L280)):*
Shouldn't we be using @private ?

---

*[src/app/geo/map.service.js, line 283 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzpuYE7WZAsaFhT2hR:-KCzpuYE7WZAsaFhT2hS:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L283)):*
const

---

*[src/app/geo/map.service.js, line 321 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzq4dqMM240lmQEsTH:-KCzq4dqMM240lmQEsTI:-21425773) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L321)):*
`basemapConfig => { return (basemapConfig.id === id); }` is the same as `basemapConfig => (basemapConfig.id === id)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/geo.service.spec.js, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzwLjWpqMrzwSUK90F:-KCzwLjXd_nIWaW_8J5V:1543229953) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/geo.service.spec.js#L53)):*
Please, add a `todo` to re-enable this later.

---

*[src/app/geo/map.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzrDchrNf17bmGGb0a:-KCzvXmUCSfDpnIWJwZZ:1937176196) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L24)):*
Why does it need to be on global state? Who else needs access to it? Can it be intrinsic to `mapService`?

---

*[src/app/geo/map.service.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzwg4vJ6cqZNezQTQd:-KCzwg4vJ6cqZNezQTQe:1717894651) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L43)):*
Minor point: Can we rename this to just `selectBasemap`? `setSelectedBasemap` sounds to me as it should be called with no arguments as the basemap was already selected. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/map.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzrDchrNf17bmGGb0a:-KD-5UW9VrhW_Y9-dAC5:34594418) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L24)):*
@alyec what do you think of just adding them to the `geoState`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/map.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzrDchrNf17bmGGb0a:-KD-777RZbXRj4nC_Zyf:805713931) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L24)):*
Could go either way.  Some stuff like basemapId may make sense to expose beyond mapService but I'm not sure.  We could also say keep it local to mapService for now and only expose what we need.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by ec-dev** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/map.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzrDchrNf17bmGGb0a:-KD-YrqIAbGPLJAKj4Sb:1123717229) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L24)):*
move ref stuff to geoState for now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by ec-dev** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/geo.service.spec.js, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzwLjWpqMrzwSUK90F:-KD-Z60gy7lsdrTqoRRc:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/geo.service.spec.js#L53)):*
Done.

---

*[src/app/geo/map.service.js, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzrDchrNf17bmGGb0a:-KD-Z6uAaVIIxhKLMLzL:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L24)):*
Done.

---

*[src/app/geo/map.service.js, line 280 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzpn08jBNKDaqPhgTa:-KD-Z8Uv78rqrMQMX5XW:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L280)):*
Done.

---

*[src/app/geo/map.service.js, line 283 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzpuYE7WZAsaFhT2hR:-KD-Z97uAYzwaebln4X0:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L283)):*
Done.

---

*[src/app/geo/map.service.js, line 321 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393#-KCzq4dqMM240lmQEsTH:-KD-ZA-Q__wtMsvEJBvJ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aa259c83d511cde0caf5bbdab59a0196487086b5/src/app/geo/map.service.js#L321)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/393)*

**Pull request merged**
