### PR TITLE
2499 config docs and small fullscreen update

### LINKED ISSUE #2499: Confirm config loading works for urls, window objects, and inline json
@jolevesq was having issues getting the viewer (v2.1.0)  to properly accept his config for the fgpa-apgf authoring tool which subsequently caused the viewer to fail loading. He had difficulty with both adding json directly to the `rv-config` attribute (viewer thought it was a url), and to the window object, which he eventually got working by doing the following:

window.config = JSON.parse(`{
        "language": "en-CA",
      "ui": {
...
```

- [ ] Ensure all three method work as intended
- [ ] Update documentation for each supported config type - provide any additional steps needed that may be missed for each type
    - Example: Don't add a javascript object directly into the `rv-config` html attribute. Use `JSON.stringify`
    - Example: Use `JSON.parse` when the json is of type string on when using the `window` object.

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2499 - worked with @barryytm to vaildate config loading and updated documentation for the supported config types

Also fixes small bug that didn't display the checkmark icon when in fullscreen

## Testing
Visually tested

## Documentation
Updated `custom_attributes.md`

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2508)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/user/custom_attributes.md, line 11 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2508#-L-axxA1_SSIPka05aBn:-L-axxA2Lsm6kD2A7aZl:bh2mmiu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c72b01b6770282bc88185d08867f9dc469d5e1e/docs/user/custom_attributes.md#L11)):*
> ```Markdown
> > Either a global variable structured with one key per language, and an object under each key representing the full configuration or a relative URL to a configuration file, it should contain the token `${lang}` which will be replaced by the currently configured language code
> 
>   (example: `window.config={ ... } and data-rv-config="config"`)
> ```

can we put the `and` outside of the code formatting?  this looks like one line of code with boolean logic.   e.g. `window.config={}` and `data-rv-config="config"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2508)*

**Comment by JahidAhmed** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/user/custom_attributes.md, line 11 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2508#-L-axxA1_SSIPka05aBn:-L-b-NYfRJurhFhhMfB9:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c72b01b6770282bc88185d08867f9dc469d5e1e/docs/user/custom_attributes.md#L11)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can we put the `and` outside of the code formatting?  this looks like one line of code with boolean logic.   e.g. `window.config={}` and `data-rv-config="config"`
</blockquote></details>

done thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2508)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2508)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2508)*

**Pull request merged**
