### PR TITLE
Dataset metadata xsl transformation

### PR DESCRIPTION
**Pull request by ec-dev**
1. unit test for metadata service to follow
2. need to update toc.service unit test related to metadata service

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/377)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/metadata.service.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGVDNvphs2dQAioN07:-KCGVDNvphs2dQAioN08:362437559) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L43)):*


Please remove all IE9/IE10-specific code as we don't support them anymore (only IE11). :confetti_ball: :confetti_ball: :cocktail:  :runner:  :dash: 

---

*[src/app/ui/toc/toc.service.spec.js, line 87 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGWFuFCyMIJSVSM_5F:-KCGWFuFCyMIJSVSM_5G:-1401916408) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/ui/toc/toc.service.spec.js#L87)):*
Can you `xdescribe` the whole test? We might forget that something was commented out otherwise.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/schema.json, line 429 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGZN6GrEGwQE4pnjso:-KCGZN6GrEGwQE4pnjsp:1716661143) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/schema.json#L429)):*
@AleksueiR since metadataUrl is currently an optional field with no default, what do you think about connecting the enabled / disabled status of metadata to the presence of metadataUrl?

Can we add catalogueUrl since we'll need that shortly?

---

*[src/app/geo/metadata.service.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGbhriqxMyhwtECVSP:-KCGbhriqxMyhwtECVSQ:429808965) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L75)):*
I think this works better as a function declaration instead of a function expression.  Mostly a style question, maybe others on the team have different ideas?

---

*[src/app/geo/metadata.service.js, line 78 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGbXQKbKBxqXXHR1lQ:-KCGbXQKbKBxqXXHR1lR:1556618205) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L78)):*
const, maybe we should use one of the other retrieval options like angular's $http service or a custom one that handles CORS proxying?

---

*[src/app/geo/metadata.service.js, line 137 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcJC4XromJsRnipFH:-KCGcJC4XromJsRnipFI:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L137)):*
const

---

*[src/app/geo/metadata.service.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcJtnT2_P9o0lyaKt:-KCGcJtnT2_P9o0lyaKu:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L138)):*
const

---

*[src/app/geo/metadata.service.js, line 139 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcL3wdKe9URueXrf6:-KCGcL3wdKe9URueXrf7:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L139)):*
const

---

*[src/app/geo/metadata.service.js, line 174 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcSW15cNjN-nOor_I:-KCGcSW15cNjN-nOor_J:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L174)):*
const

---

*[src/app/geo/metadata.service.js, line 227 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcnghKigl42LuNQz8:-KCGcnghKigl42LuNQz9:-799134320) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L227)):*
This might work (and read) better as:
```js
const loadPromises = [loadFunction(xmlUrl), loadFunction(xslUrl)];
return $q.all(loadPromises)
  .then(([xmlData, xslData]) => applyXslt(xmlData, xslData, returnFragment, params) )
  .catch(err => cry());
```

---

*[src/app/geo/metadata.service.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGe8517b3-NTHiwlyK:-KCGe852EGqla5Bn2UR0:636081767) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L249)):*
return service should be hoisted according the the style guide (basically define all the exported stuff up front, return the object, then define the inner workings)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/schema.json, line 429 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGZN6GrEGwQE4pnjso:-KCGy6owikGXFZPV0rPy:-264120926) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/schema.json#L429)):*
@alyec I would prefer to keep all layer settings in one place.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/schema.json, line 429 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGZN6GrEGwQE4pnjso:-KCGyMvoHh_vmnyvz7bl:87505312) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/schema.json#L429)):*
Sure.  I'd also say that if we aren't going to assign any meaning to the absence of metadataUrl we should have a default null (I've been trying to follow a guideline of an entry should be required, have a default or a clear meaning behind it's absence in the schema).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/schema.json, line 429 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGZN6GrEGwQE4pnjso:-KCGzJWiOe7MeCJRLShA:-730763195) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/schema.json#L429)):*
Sounds like a good idea.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/app/geo/metadata.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCHm5fTB__pofAw1HX6:-KCHm5fTB__pofAw1HX7:1002562469) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L1)):*
ActiveXObject is gone.  :fireworks: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Comment by spencerwahl** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/app/geo/metadata.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCHm5fTB__pofAw1HX6:-KCL8aBH8Mh66bHOlTSF:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L1)):*
Done.

---

*[src/app/geo/metadata.service.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGVDNvphs2dQAioN07:-KCL8b_wUunk6gusK6SC:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L43)):*
Done.

---

*[src/app/geo/metadata.service.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGbhriqxMyhwtECVSP:-KCL8cjDE8V0VKf3IuLK:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L75)):*
Done.

---

*[src/app/geo/metadata.service.js, line 78 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGbXQKbKBxqXXHR1lQ:-KCL8c9g4RxmDYYK2u5J:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L78)):*
Done.

---

*[src/app/geo/metadata.service.js, line 137 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcJC4XromJsRnipFH:-KCL8d8cdxq5H9_TDeVK:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L137)):*
Done.

---

*[src/app/geo/metadata.service.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcJtnT2_P9o0lyaKt:-KCL8da8HEH-jnsj6gFW:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L138)):*
Done.

---

*[src/app/geo/metadata.service.js, line 139 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcL3wdKe9URueXrf6:-KCL8dv-CH0N3E9O4iYk:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L139)):*
Done.

---

*[src/app/geo/metadata.service.js, line 174 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcSW15cNjN-nOor_I:-KCL8g506otnvUQ7NXYw:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L174)):*
Done.

---

*[src/app/geo/metadata.service.js, line 227 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGcnghKigl42LuNQz8:-KCL8htS3ERNu716HCBy:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L227)):*
Done.

---

*[src/app/geo/metadata.service.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGe8517b3-NTHiwlyK:-KCL8iP3typdxlgP0FgG:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/geo/metadata.service.js#L249)):*
Done.

---

*[src/app/ui/toc/toc.service.spec.js, line 87 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377#-KCGWFuFCyMIJSVSM_5F:-KCL8jBgOc4_Ni5VDZf4:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/578da7d3c37c6d61cba7132b3f99ce34e6332e79/src/app/ui/toc/toc.service.spec.js#L87)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/377)*

**Pull request merged**
