### PR TITLE
chore(build): update angular and other dependencies

### LINKED ISSUE #370: Upgrade to Angular 1.6.3
Release notes: http://angularjs.blogspot.ca/2016/02/angular-150-ennoblement-facilitation.html
Migration guide: https://docs.angularjs.org/guide/migration#migrating-from-1-4-to-1-5

### PR DESCRIPTION
**Pull request by milesap**
## Description
Now on branch 2.0 as this is a breaking change - viewer will no longer
load if host page has angular versions < 1.6.3. This is caused by
updates to all other angular libraries including angular-animate,
angular-aria, angular-messages etc.

Closes #370

## Testing
Yes

## Documentation
No

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1821)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgnarRXibW3Y7zHCnU8:bded0xx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
> ```JSON
>   },
>   "scripts": {
>     "postinstall": "rm -r -f lib/angular-dragula && bower install && git apply fix-ui-delay-drag-start.patch",
> ```

Not applying dragula patch anymore, why? Was it included in 1.2.8?

---

*[src/index-mobile.html, line 20 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnaeOrb2xlrIc-wX-0:-KgnaeOrb2xlrIc-wX-1:b8s5o8r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/src/index-mobile.html#L20)):*
> ```HTML
>     
>     <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
>     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.11/angular.min.js"></script>
> ```

Please, keep this. It's needed to test bootstraps warning messages about possible incompatible library versions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by milesap** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgndwYAK_7DoKqvW5Xd:b9myvr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Not applying dragula patch anymore, why? Was it included in 1.2.8?
</blockquote></details>

I tested on develop with patch and on 2.0 without - I didn't notice any differences between them. I did see [this merged](https://github.com/bevacqua/dragula/pull/424).

---

*[src/index-mobile.html, line 20 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnaeOrb2xlrIc-wX-0:-KgneCtYsnr2xopyx7a3:b-w9yqlf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/src/index-mobile.html#L20)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, keep this. It's needed to test bootstraps warning messages about possible incompatible library versions.
</blockquote></details>

Ok kept

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by AleksueiR** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgngGc4QaCH4QproCEK:b-jqjzrp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I tested on develop with patch and on 2.0 without - I didn't notice any differences between them. I did see [this merged](https://github.com/bevacqua/dragula/pull/424).
</blockquote></details>

Not sure how this is related.
Our patch prevents drag from starting on tiny mouse movements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by milesap** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgniMJufzPa6KEWA8m_:bvr97s8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Not sure how this is related.
Our patch prevents drag from starting on tiny mouse movements.
</blockquote></details>

Either patch is broken on develop, or fix was merged into dragula. There is no difference between drags on small mouse movements. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by AleksueiR** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgniuS7u2vQHQj52G5Z:b-8zrvfd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Either patch is broken on develop, or fix was merged into dragula. There is no difference between drags on small mouse movements. 
</blockquote></details>

Please, find out what happened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by milesap** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgnmEhWDrcrKMddotZt:b-t3dwch) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, find out what happened.
</blockquote></details>

I looked into it, it seems this patch doesn't fix any bug with dragula, instead it doesn't allow dragula to start the pickup until x and y coords have moved a combined 6 pixels. I added it back - it is working on develop. I don't think anyone will ever notice it, I could barely notice a change if I knew exactly what I was looking at. But if it ain't broke dont fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by AleksueiR** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgnnlvJULD8n21sTzat:b-xtgx7g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I looked into it, it seems this patch doesn't fix any bug with dragula, instead it doesn't allow dragula to start the pickup until x and y coords have moved a combined 6 pixels. I added it back - it is working on develop. I don't think anyone will ever notice it, I could barely notice a change if I knew exactly what I was looking at. But if it ain't broke dont fix it.
</blockquote></details>

That what it does and it does fix an annoying tendency to drag  a layer when you quickly clicking on on the layer to open the datatable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by milesap** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[package.json, line 91 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821#-KgnarRXibW3Y7zHCnU7:-KgnoArYlFOakoX98Avi:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/be1395b3df16fa8bcee6adf626b0bdb97ab3dc46/package.json#L91)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

That what it does and it does fix an annoying tendency to drag  a layer when you quickly clicking on on the layer to open the datatable.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1821)*

**Comment by milesap** [comment]
Rolling this into webpack PR hopefully in a day or two. Bower will be replaced with npm packages.

**Pull request closed without merging**
