### PR TITLE
Apply layer option defaults to layer config blocks + random changes too small for their own PRs

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/264)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264#-K9YHvTijdf2dr3G0ta7:-K9YHvTijdf2dr3G0ta8:-949736120) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a14b69e702567d274911f0b041410eb7ac57c966/src/app/geo/geo.service.js#L75)):*
Why not?  User added layers need to be in the registry but will not have a config.

---

*[src/index-wet.html, line 94 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264#-K9YINDu-MX2olpS9eer:-K9YINDvhxW-O882Df1I:-1357303214) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a14b69e702567d274911f0b041410eb7ac57c966/src/index-wet.html#L94)):*
`//` doesn't work in this case?

---

*[src/schema.json, line 224 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264#-K9YIiO-3OhRAzqIetJv:-K9YIiO01kms9xDQG1mL:-1852553672) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a14b69e702567d274911f0b041410eb7ac57c966/src/schema.json#L224)):*
`items` is a bad name in this context since it's also a json-schema keyword.  How about `children` or `sublayers`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264#-K9YHvTijdf2dr3G0ta7:-K9YLI2NjJrje9xZ2f6G:-1873542507) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a14b69e702567d274911f0b041410eb7ac57c966/src/app/geo/geo.service.js#L75)):*
Renaming `config` to `initialState`which should be built and passed to `registerLayer`  in case of a user-added layer.

---

*[src/index-wet.html, line 94 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264#-K9YINDu-MX2olpS9eer:-K9YJXXppAEoBRxb1Sqq:-1075955388) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a14b69e702567d274911f0b041410eb7ac57c966/src/index-wet.html#L94)):*
Haven't noticed there was `http`. Will fix.

---

*[src/schema.json, line 224 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264#-K9YIiO-3OhRAzqIetJv:-K9YLB4mtJEhsk-YsGt9:-1264971019) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a14b69e702567d274911f0b041410eb7ac57c966/src/schema.json#L224)):*
We decided to keep `items`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264)*

**Comment by spencerwahl** [comment]
Reviewed 7 of 9 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/264)*

**Pull request merged**
