### PR TITLE
fix(grids): Filter by extent doesn't work after refactor

### LINKED ISSUE #2036: Datagrid "Filter by Extent" function not working as expected
Tested build: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html

Related to #884 

Filter by Extent option available in a datagrid is not filtering the data by the current extent.  Tried this on thematic maps with structured legends and also by importing a service layer. Please investigate

image

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2036, #2017

## Testing

Safari, Chrome

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2093)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm: demo works :+1: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/core/config.class.js, line 250 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoD4sdiHklqsxQN2b4r:-KoD4sdiHklqsxQN2b4s:b-s98whu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13cc3b8320ce31b1e580168d9c25a09829ebdd4a/src/app/core/config.class.js#L250)):*
> ```JavaScript
>             this._snapshot = source.snapshot;
>             this._userAdded = source.userAdded;
>             this._filters = source.filters;
> ```

I don't see this is being used anywhere.

---

*[src/app/core/config.class.js, line 427 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoD4UmnosNHJP6PPIQv:-KoD4UmnosNHJP6PPIQw:b-j88g1d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13cc3b8320ce31b1e580168d9c25a09829ebdd4a/src/app/core/config.class.js#L427)):*
> ```JavaScript
>         get searchable () { return this._searchable; }
>         get filter () { return this._filter; }
>         get queryUrl () { return this._queryUrl; }
> ```

No need to define `queryUrl` here, as it's property on geoApi's layer proxy object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-:-KoD5IojACw_6VSS_OCP:b-z726na)*

**Comment by JahidAhmed** [comment]
When a layer is reloaded, the filter flag is still displayed but `Filter by Extent` is not active

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-:-KoDIkJdAMnxhTIoijuf:b-bz2g10)*

**Comment by jolevesq** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/core/config.class.js, line 250 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoD4sdiHklqsxQN2b4r:-KoHezOOOv7UHOTCvS6-:bss4a2b) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13cc3b8320ce31b1e580168d9c25a09829ebdd4a/src/app/core/config.class.js#L250)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I don't see this is being used anywhere.
</blockquote></details>

Removed.

---

*[src/app/core/config.class.js, line 427 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoD4UmnosNHJP6PPIQv:-KoHfgfnHPbZdD1NoM0p:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13cc3b8320ce31b1e580168d9c25a09829ebdd4a/src/app/core/config.class.js#L427)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

No need to define `queryUrl` here, as it's property on geoApi's layer proxy object.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 57 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoNspdi1SfuqTipV4vH:-KoNspdi1SfuqTipV4vI:b-wavjg4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dd6fc18cc7efd895be68da0946eaa73d3b44149b/src/app/ui/toc/toc.service.js#L57)):*
> ```JavaScript
>         // get filters configuration and check if static field were used. If so, filters can't be remove and flag need to stay
>         const config = configService.getSync.map.layerRecords.find(item =>
>             item.initialConfig._id === legendBlock.layerRecordId).initialConfig.filters;
> ```

You can use `item.config.id` instead of `initialConfig`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by JahidAhmed** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by JahidAhmed** [comment]
Related issue: #2120

**Comment by jolevesq** [comment]
The issue #2120 will be done in an new issue/PR

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 57 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoNspdi1SfuqTipV4vH:-KoT-gtiauHWuVij0Ln9:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dd6fc18cc7efd895be68da0946eaa73d3b44149b/src/app/ui/toc/toc.service.js#L57)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can use `item.config.id` instead of `initialConfig`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-:-KoSw4YkPbde0t6v-368:b-yjwplo)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/filters/filters.service.js, line 531 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoT1yBXv34ZKtE5pxZD:-KoT1yBXv34ZKtE5pxZE:buidrd5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/71c50776e9293ec6dc606c060175dbcc2fccf1d3/src/app/ui/filters/filters.service.js#L531)):*
> ```JavaScript
> 
>         const layer =
>             layerRegistry.getLayerRecord(stateManager.display.filters.requester.legendEntry.layerRecordId)._layer;
> ```

Will leave this as is right now, but `_layer` is an esri object. In the future we should try to push some of the interaction to the geoApi.

---

*[src/app/ui/toc/toc.service.js, line 57 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093#-KoNspdi1SfuqTipV4vH:-KoT2Y-lhgEAp2shQeR3:b3dasa0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dd6fc18cc7efd895be68da0946eaa73d3b44149b/src/app/ui/toc/toc.service.js#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Adding comment to override Alex

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by milesap** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by JahidAhmed** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2093)*

**Pull request merged**
