### PR TITLE
Feature/clickeroo

### PR DESCRIPTION
**Pull request by james-rae**
Click handler for feature layers
Mainly looking for architectural feedback.  I imagine a lot of things will change from what is in this commit.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/315)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by cynngah** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by alyec** [comment]
no files are changed in the ui module, all commits should be scoped to geo

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 207 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315#-KACtXhuECEWd8EfbcMZ:-KACtXhuECEWd8EfbcM_:-522788056) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/377c9f831e17c96c5a1b12e18aa0234b1e91a4f1/src/app/geo/identify.service.js#L207)):*
as JS is single threaded the `detailsPanel.isLoading = true` earlier will never have an effect (except if an exception occurs in which case the panel will always remain in a loading state)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315#-:-KACua6OiSqsCUHDYgPe:481643436)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 38 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315#-KAFa8auKQeLjZZOFbXq:-KAFa8auKQeLjZZOFbXr:-79188671) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/377c9f831e17c96c5a1b12e18aa0234b1e91a4f1/src/app/geo/identify.service.js#L38)):*
Why do we need to do this?

---

*[src/app/geo/identify.service.js, line 161 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315#-KAFaT7Bu2ZYWeHA3Yce:-KAFaT7Bu2ZYWeHA3Ycf:2057852566) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/377c9f831e17c96c5a1b12e18aa0234b1e91a4f1/src/app/geo/identify.service.js#L161)):*
It has been done. Check `singlePoint` and `multiplePoints` functions in`shellController`.
No need to touch `stateManager.display` object now.

---

*[src/app/geo/identify.service.js, line 207 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315#-KACtXhuECEWd8EfbcMZ:-KAFav2l4u518q8qzjTa:1792329045) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/377c9f831e17c96c5a1b12e18aa0234b1e91a4f1/src/app/geo/identify.service.js#L207)):*
This is true, but the loading state is handled by `stateManager.toggleDisplayPanel` function which should be used when setting details data. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 38 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315#-KAFa8auKQeLjZZOFbXq:-KAFnYHAygQ3HNDS5ylh:-1267871227) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/377c9f831e17c96c5a1b12e18aa0234b1e91a4f1/src/app/geo/identify.service.js#L38)):*
map and feature clicks trigger at same time. this prevents both handlers from clearing detail pane (see function comment).  alternate architecture discussed this morning should allow this to be removed.

---

*[src/app/geo/identify.service.js, line 161 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315#-KAFaT7Bu2ZYWeHA3Yce:-KAFntyKLSGfe3lXCf2T:441493745) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/377c9f831e17c96c5a1b12e18aa0234b1e91a4f1/src/app/geo/identify.service.js#L161)):*
good news

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/315)*

**Pull request merged**
