### PR TITLE
Basic Help Screen

### PR DESCRIPTION
**Pull request by spencerwahl**
Includes unit tests

_flag any poorly named variables/functions_

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/207)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by alyec** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[src/app/layout/shell.html, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7srSPxnnpbljhoHJNP:-K7srSPxnnpbljhoHJNQ:1147527275) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/layout/shell.html#L28)):*
inline styling approved

---

*[src/app/ui/help/help-overlay.directive.js, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7sreDQklgWDpn5XKU3:-K7sreDQklgWDpn5XKU4:-1493617990) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L32)):*
most of the `let`s in the functions below should be `const`s (reminder: `const` just means that the reference is constant, not that the object it is pointing to cannot change any internal properties)

---

*[src/app/ui/help/help-overlay.directive.js, line 79 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7ssJfnXd_Srhlo3dV5:-K7ssJfnXd_Srhlo3dV6:1390205886) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L79)):*
From reading the function I'm only partially clear on what *valid* means here.  Might want to expand on the comment to explain.

---

*[src/app/ui/help/help-overlay.directive.js, line 112 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7stExR3imzqeE1nIMR:-K7stExSWP5HD9v-RtAD:-849077798) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L112)):*
Instead of `if (cond) { return false; } return true;` `return !(cond)` is probably easier.  I very much approve of the efficient collision check itself.

---

*[src/app/ui/help/help.directive.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7suvIJ1LN0XdSjgXoc:-K7suvIKN_mf14addsac:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help.directive.js#L30)):*
const

---

*[src/app/ui/help/help.service.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7svr98BbLZgQXFg6dj:-K7svr98BbLZgQXFg6dk:1124343269) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help.service.js#L52)):*
Is it certain that object will always be in the registry (i.e. could we ever run into a bug where we end up splicing on -1 because of a mistake somewhere else)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by AleksueiR** [comment]
Reviewed 18 of 19 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/layout/shell.html, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7srSPxnnpbljhoHJNP:-K7uuAYz-EajFiVwKPSd:-1096366002) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/layout/shell.html#L28)):*
He is joking. Create `_help.scss` file under `content/styles/modules`; add help styling there. Make sure to `@import` and `@include` it in the `_all.scss` file.

---

*[src/app/ui/help/help-overlay.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7uv5kWiPKoDHEJlGAI:-K7uv5kWiPKoDHEJlGAJ:936625299) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.html#L4)):*
`position:absolute;` can be moved to styles.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/layout/shell.html, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7srSPxnnpbljhoHJNP:-K7vn3LcxyLs36jnCuEL:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/layout/shell.html#L28)):*
Done.

---

*[src/app/ui/help/help-overlay.directive.js, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7sreDQklgWDpn5XKU3:-K7vn4tmjeOHh51ZUACR:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L32)):*
Done.

---

*[src/app/ui/help/help-overlay.directive.js, line 112 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7stExR3imzqeE1nIMR:-K7vWC12miYnDpea7Qoj:-1454227507) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L112)):*
d'oh... fixed.

---

*[src/app/ui/help/help-overlay.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7uv5kWiPKoDHEJlGAI:-K7vnE-8WmrwESzWNcoD:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.html#L4)):*
Done.

---

*[src/app/ui/help/help.directive.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7suvIJ1LN0XdSjgXoc:-K7vnEXGoZ5kuojrVtKS:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help.directive.js#L30)):*
Done.

---

*[src/app/ui/help/help.service.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7svr98BbLZgQXFg6dj:-K7vnGO5jPYKCBjAUFNn:1543745033) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help.service.js#L52)):*
The way we use it now the object _should_ always be in the registry. I added the check anyways just in case we use it in a different place in the future.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/help/help.service.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7svr98BbLZgQXFg6dj:-K7voUTDSK9VyNKg_K5J:500784063) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help.service.js#L52)):*
Sure, I wasn't really certain if the object was guaranteed or not, and if there's any possibility of someone using this without properly reading the comments.  If you think the someone would have to do something pretty extreme to get into that case I'm also okay with leaving the check out.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by AleksueiR** [comment]
:lgtm: 

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-:-K7vp7RIALjDLSNQPMQw:980077423)*

**Comment by james-rae** [comment]
Reviewed 5 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/help/help-overlay.directive.js, line 79 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7ssJfnXd_Srhlo3dV5:-K7vpdobPfkaW5VYqIG6:-81802178) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L79)):*
Is this better?

---

*[src/app/ui/help/help.service.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7svr98BbLZgQXFg6dj:-K7vpysNuE6AT-ODudQq:1448507577) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help.service.js#L52)):*
Nope it definitely wouldn't need to be extreme :smile:, the check was a good suggestion

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/help/help-overlay.directive.js, line 79 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7ssJfnXd_Srhlo3dV5:-K7vq_t27eal_ElrEIZa:524011354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L79)):*
Yes.  Bonus points for using `iff`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by spencerwahl** [comment]
Review status: 20 of 21 files reviewed at latest revision, all discussions resolved.

---

*[src/app/ui/help/help-overlay.directive.js, line 79 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207#-K7ssJfnXd_Srhlo3dV5:-K7vsW9jlO_i4JSBRQm6:1185695303) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d7063cf235a33a3ffb8ee0d74cb52175e8feaaa3/src/app/ui/help/help-overlay.directive.js#L79)):*
:smile:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/207)*

**Pull request merged**
