### PR TITLE
1493 feature as single dynamic + two more changes

### LINKED ISSUE #1967: Add option to disable layer import
Layer import is by default allowed for structured and auto mode.
This config option lets the map author disable layer import.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Three PRs in one:
- add Feature layers as single dynamic
- option to disallow layer import
- option to hide layer from the legend UI, but still be displayed on the map

Involves changes to the schema.

Closes #1967, #1493 

## Testing
Eyeballs.

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated (not yet)
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1968)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/content/samples/schema.json, line 561 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-KmXAkMtRJjz5P91071_:-KmXAkMtRJjz5P91071a:bq7yt9z) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/658ffc1e9110a8da174d2ce100cf187fd2beed4d/src/content/samples/schema.json#L561)):*
> ```JSON
>                 "catalogueUrl": { "type": "string", "default": null, "description": "The catalogue url of the layer service" },
>                 "layerType": { "type": "string", "enum": [ "esriDynamic" ] },
>                 "singleEntryCollapse": { "type": "boolean", "default": false, "description": "Indicates that the dynamic layer with a signle layer entry should be rendered without the root group." },
> ```

typo: single

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-:-KmXClGdFdy1yKUR54qm:bnfp4nl)*

**Comment by AleksueiR** [comment]
Don't merge yet - forgot to update layer wizard.

---

Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/schema.json, line 561 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-KmXAkMtRJjz5P91071_:-KmaRQGS4nTbBbMI09HS:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/658ffc1e9110a8da174d2ce100cf187fd2beed4d/src/content/samples/schema.json#L561)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: single
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-:-Kmak_nqVceSpJeBlPCe:bph7ydp)*

**Comment by AleksueiR** [comment]
Updated, good to merge when satisfied.

---

Review status: 5 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-:-Kmb3OQ4KV_z2WBGDvck:bkzmkq6)*

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r2, 9 of 9 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968)*

**Comment by alyec** [comment]
issue with import:
- add a mapserver endpoint
- select a single layer
- click select all
- "display as group" is still disabled and unchecked, "group name" is hidden
- layer still loads as a group with the default title

this can be split into a separate bug if the fix is not trivial

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-:-KmbADcjDVMh0nssYUz1:bkwhyyt)*

**Comment by AleksueiR** [comment]
Thanks Aly, that was a good find. It should be fixed now.

---

Review status: 16 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-:-KmbiSKbOOGWR8r5MxzY:b92l0wq)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1968#-:-KmbohVCsMRtjjEQDpy0:bnfp4nl)*

**Pull request merged**
