### PR TITLE
API bug fixes #2585, #2579, #2581 and documentation changes

### LINKED ISSUE #2585: Fix typedoc error and check/add docs/examples to current API if needed
Error thrown by TS compiler in `app-seed.ts` when it imports from `bootstrap.js` (doesn't like JS).

### PR DESCRIPTION
**Pull request by milesap**
## Description
All documentation will now reside in the `docs` folder. 
- `docs/api` is for the api guide, `docs/api/developer` is where tsDocs go.
- `docs/developer` is for our existing tutorial `*.md` files, `docs/developer/jsDocs` replaces the `docbuild` folder.
- All documentation is now generated during the build process
- `npm run docute` allows you to view `docs` folder

### Other changes
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2585 error fixed by creating a new file `src/app/startup.ts` which removes some functionality from `src/app/bootstrap.js` which is required by the API. The typescript compiler throws an exception importing from a javascript file. `startup.ts` runs before `bootstrap.js` and is meant to eventually deprecate `bootstrap.js` (didn't want to convert entire bootstrap into TS now).
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2579 zoom now returns proper result
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2581 `mouseMove` will not emit the same screen position twice in a row.
- `scripts/docdeploy.sh` no longer needed, using github hosted documentation 
- jsdoc was using docdash template, this was currently throwing errors so it has been removed. I will update on next PR either with docdash or similar (jsDocs still generates, just looks different)

### Documentation Sample
- https://milesap.github.io/fgpv-vpgf/#/

### Todo in another PR
- Only `master` branch docs are available through github sites, need to have a way to see docs for any branch/tag.

Closes #2585, #2579, #2581

## Testing
Mostly the documentation generation, build works, local serving in chrome looks good as well

## Documentation
Just the start

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2586)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 457 of 457 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/api/welcome.md, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5jWNQPyk4YOOo00yVu:-L5jWNQQEBbF_a8YDyDG:bk6xemm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c9a64825a44802106a9f69c03f53d2b3552b8e41/docs/api/welcome.md#L2)):*
> ```Markdown
> ### STOP!
> THE CODE HEREIN IS A WORK IN PROGRESS - DO NOT USE, BREAKING CHANGES WILL OCCUR FREQUENTLY.
> ```

Do we want to keep the scary warnings for now?

---

*[docs/developer/jsDocs/app.ui%0D%0DProvides%20ability%20to%20place%20this%20viewer%20into%20fullscreen%20mode,%20and%20whether%20it%20is%20actively%20in%20fullscreen%20mode.fullScreenServicemodule_.html, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5jXykCDsfxcBeBjCi8:-L5jXykCDsfxcBeBjCi9:b5fq2m6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/15fb28a8948743ad712650d3deaa34138efbfe9d/docs/developer/jsDocs/app.ui%0D%0DProvides%20ability%20to%20place%20this%20viewer%20into%20fullscreen%20mode,%20and%20whether%20it%20is%20actively%20in%20fullscreen%20mode.fullScreenServicemodule_.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

whats up with that file name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by milesap** [comment]
Review status: 94 of 438 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/api/welcome.md, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5jWNQPyk4YOOo00yVu:-L5mu8AeShORym-xKzNU:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c9a64825a44802106a9f69c03f53d2b3552b8e41/docs/api/welcome.md#L2)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Yeah, I'll put it in a danger box. Not sure if we're just b-lining it to v3, but can't hurt.
</blockquote></details>

Done

---

*[docs/developer/jsDocs/app.ui%0D%0DProvides%20ability%20to%20place%20this%20viewer%20into%20fullscreen%20mode,%20and%20whether%20it%20is%20actively%20in%20fullscreen%20mode.fullScreenServicemodule_.html, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5jXykCDsfxcBeBjCi8:-L5mx__L8-vJwwNiSUvu:b-ep0b2l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/15fb28a8948743ad712650d3deaa34138efbfe9d/docs/developer/jsDocs/app.ui%0D%0DProvides%20ability%20to%20place%20this%20viewer%20into%20fullscreen%20mode,%20and%20whether%20it%20is%20actively%20in%20fullscreen%20mode.fullScreenServicemodule_.html#L1)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

whats up with that file name?
</blockquote></details>

Must have been a jsDoc issue caused by inline documentation followed by block documentation. Seems the file is now gone :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by james-rae** [comment]
Reviewed 1 of 484 files at r1, 372 of 372 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by JahidAhmed** [comment]
Reviewed 120 of 484 files at r1, 370 of 372 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/common/full-screen.service.js, line 15 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5nTv5QEF1v8qGJ7Hg1:-L5nTv5QEF1v8qGJ7Hg2:bvchctj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a9a4ef24bc6d153a9ab4ebfe55116fc186b69f60/src/app/ui/common/full-screen.service.js#L15)):*
> ```JavaScript
>  * @memberof app.ui
>  *
>  * Provides ability to place this viewer into fullscreen mode, and whether it is actively in fullscreen mode.
> ```

I think the file name issue was because we were missing the `@description` before the 'Provides ...' sentence. We could potentially add that and leave this block in as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by milesap** [comment]
Added to `MouseEvent`:
- `pageX`, `pageY`
- `offsetX`, `offsetY`

Corrected `xy` property as esri provided `mapPoints` is in the current maps wkid, so added conversion to API's  `XY` `4326` standard.

---

Review status: 100 of 440 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/full-screen.service.js, line 15 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5nTv5QEF1v8qGJ7Hg1:-L5sPqvlrfE7CNBt3hME:b4ph1nx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a9a4ef24bc6d153a9ab4ebfe55116fc186b69f60/src/app/ui/common/full-screen.service.js#L15)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

I think the file name issue was because we were missing the `@description` before the 'Provides ...' sentence. We could potentially add that and leave this block in as well
</blockquote></details>

ty for info, added `@description` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-:-L5sPx-eC08_W4VDknho:bfolr3q)*

**Comment by JahidAhmed** [comment]
Reviewed 26 of 372 files at r3, 340 of 340 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/full-screen.service.js, line 15 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5nTv5QEF1v8qGJ7Hg1:-L5sTpr4gPu9bsl3J8O-:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a9a4ef24bc6d153a9ab4ebfe55116fc186b69f60/src/app/ui/common/full-screen.service.js#L15)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

ty for info, added `@description` 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/full-screen.service.js, line 15 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-L5nTv5QEF1v8qGJ7Hg1:-L5sU-gqeaiw41uHH028:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a9a4ef24bc6d153a9ab4ebfe55116fc186b69f60/src/app/ui/common/full-screen.service.js#L15)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by james-rae** [comment]
Reviewed 26 of 372 files at r3, 340 of 340 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by AleksueiR** [comment]
Reviewed 15 of 484 files at r1, 7 of 372 files at r3, 5 of 340 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2586#-:-L5xd8zkpI3r85hN9ur0:bnfp4nl)*

**Pull request merged**
