### PR TITLE
Feature/smallkey

### PR DESCRIPTION
**Pull request by james-rae**
Allow RCS Smallkeys to be fed to the app after initial startup, and have those layers appear

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/484)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/core/config.service.js, line 222 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLFX_POfT_ewyT1YOH:-KFLFX_POfT_ewyT1YOI:-319497292) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L222)):*
how about `langs = Object.keys(service.data)` ?

---

*[src/app/core/config.service.js, line 255 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLHO0dVT0fnoF6wsLH:-KFLHO0e2fGtr3i83GBm:-1476528569) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L255)):*
Is the intention to load the current language and resolve as soon as that is done?  If not there should probably be a Promise.all() to ensure all languages are loaded before proceeding.

---

*[src/app/core/config.service.js, line 276 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLE_H9HBNoLJzewKbw:-KFLE_H9HBNoLJzewKbx:1080288523) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L276)):*
if we're doing this we should probably add a call to RCS that returns data for all languages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/config.service.js, line 222 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLFX_POfT_ewyT1YOH:-KFPHmKu3an2SbrmRI22:-57955860) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L222)):*
much nicer.  will add pronto.

---

*[src/app/core/config.service.js, line 255 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLHO0dVT0fnoF6wsLH:-KFPHqP9idhuxpY-F58L:-184089237) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L255)):*
we can do either.  updating the non-active languages is only to support the language switch, so no real benefit to waiting (one possibility -- if crazy person loads smallkey then instantly switches language, and RCS was slow to respond with non-active language, then something could be lost in the switch).

---

*[src/app/core/config.service.js, line 276 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLE_H9HBNoLJzewKbw:-KFPepUXZw1Txb73MHyZ:-365009540) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L276)):*
I'm basing this approach off of how RCS loads at startup (from the app tag `rv-keys` properties), but you are correct, the way the viewer is architected now it is always calling RCS for each language.  My assumption is to cache the config in the alternate languages.  Approaches could be as you suggest, loading multiple languages in one call from RCS, or changing how we swap languages (i.e. don't do web calls until that language is loaded).  Solution would be a new issue, not in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Comment by alyec** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 276 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLE_H9HBNoLJzewKbw:-KFPyVn11x2d5Eojax3Z:964367422) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L276)):*
I believe this discussion is being moved elsewhere, can you leave a link here when it's posted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Comment by james-rae** [comment]
*[src/app/core/config.service.js, line 276 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484#-KFLE_H9HBNoLJzewKbw:-KFdRSCui7yFNXu52a4_:-898827272) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4ed0541a57737557effe1f4f9256a3ea6873bc03/src/app/core/config.service.js#L276)):*
The discussion issue can be found here https://github.com/fgpv-vpgf/fgpv-vpgf/issues/498

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/484)*

**Pull request merged**
