### PR TITLE
Adds service-based layer import (with caveats)

### PR DESCRIPTION
**Pull request by AleksueiR**
In support of #612

Notes:

- errors (like mismatch between detected and user selected file type) are not handled; no error messages (except for invalid urls and required fields)
- if a service url provided is some random url or a broken service, in some cases, the error is not immediately detected (it timeouts eventually) (the error message is not shown right away); this can be confusing as nothing seem to happen; one suggestion is to block the “continue” button so the user can’t click multiple times;
- the user can force a service into any type and there is no validation available right now; in some cases it looks that something is broken on our end;
- does not compute smart defaults
- no colour picker yet

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/762)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 140 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK938ON1tfXWRG92eqY:-KK938ON1tfXWRG92eqZ:1393489800) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L140)):*
> ```JavaScript
> 
>             /**
>              * Get service info from the supplied url. Service infor usually include information like service type, name, available fields, etc.
> ```

Typo: service info

---

*[src/app/geo/layer-blueprint.class.js, line 141 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93IUjksHQQnpe4ngF:-KK93IUjksHQQnpe4ngG:-1210624305) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L141)):*
> ```JavaScript
>             /**
>              * Get service info from the supplied url. Service infor usually include information like service type, name, available fields, etc.
>              * TODO: there is a lot of workarounds since wms layers need special handling, and it's not possible to immediattely detect if the layer is not a service endpoint .
> ```

Typo: immediately

---

*[src/app/geo/layer-blueprint.class.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93XgnF39tLYS-EU5x:-KK93XgnF39tLYS-EU5y:1746528461) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L153)):*
> ```JavaScript
>                             console.log(`${this.config.url} is a WMS, yak!`);
> 
>                             // return an object resembing fileInfo object returned by GeoAPi
> ```

Typo: resembling; GeoApi

---

*[src/app/geo/layer-blueprint.class.js, line 170 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK96mMboXuwis0hC3Ey:-KK96mMboXuwis0hC3Ez:1284576267) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L170)):*
> ```JavaScript
>                         // this is not a service URL;
>                         // in some cases, if URL is not a service URL, dojo script used to interogate the address
>                         // will throw a page-level error which cannot be caugth; in such cases, it's not clear to the user what has happened;
> ```

Typo: caught

---

*[src/app/geo/layer-blueprint.class.js, line 205 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9KgTppucX1jeMTTUA:-KK9KgTppucX1jeMTTUB:2059131656) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L205)):*
> ```JavaScript
>                  * @param  {Array} layers array of layer objects
>                  * @param  {Number} level  =             0 tells how deep the layer is in the hierarchy
>                  * @return {Object}        layer description
> ```

Doesn't this return an array?

---

*[src/app/ui/loader/loader-service.directive.js, line 122 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9FLhPD7-wHPeuxNvW:-KK9FLhPD7-wHPeuxNvX:578305463) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.directive.js#L122)):*
> ```JavaScript
>         }
> 
>         function connectOnContinue() {
> ```

jsdoc for the `connect*` functions

---

*[src/app/ui/loader/loader-service.html, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9Iu5MLGkv6LJpFHkX:-KK9Iu5MLGkv6LJpFHkY:-665679864) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.html#L3)):*
> ```HTML
> <rv-content-pane close-panel="self.closeLoaderService()" floating-header="true">
> 
>     
> ```

I think you caught all the translations in this file and this can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by AleksueiR** [comment]
Review status: 8 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 140 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK938ON1tfXWRG92eqY:-KK9hIoiJWJ0wK4zTbca:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L140)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Typo: service info
</details>
Done.

---

*[src/app/geo/layer-blueprint.class.js, line 141 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93IUjksHQQnpe4ngF:-KK9hPiM03MwHu0pTe2o:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L141)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Typo: immediately
</details>
Done.

---

*[src/app/geo/layer-blueprint.class.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93XgnF39tLYS-EU5x:-KK9hTYLSVwI5rCLpmfY:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L153)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Typo: resembling; GeoApi
</details>
Done.

---

*[src/app/geo/layer-blueprint.class.js, line 170 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK96mMboXuwis0hC3Ey:-KK9hXWMdR0qwD5Jit0E:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L170)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Typo: caught
</details>
Done.

---

*[src/app/geo/layer-blueprint.class.js, line 205 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9KgTppucX1jeMTTUA:-KK9hhWn5i3qXW9SfTkZ:34126021) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L205)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Doesn't this return an array?
</details>
Yes, it's an array. Fixed.

---

*[src/app/ui/loader/loader-service.directive.js, line 122 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9FLhPD7-wHPeuxNvW:-KK9iMjwZukXZmv-vXUm:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.directive.js#L122)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc for the `connect*` functions
</details>
Done.

---

*[src/app/ui/loader/loader-service.html, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9Iu5MLGkv6LJpFHkX:-KK9iZDN2fhXfQ76Kc0H:1534842225) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.html#L3)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think you caught all the translations in this file and this can be removed.
</details>
Nice!

Do I keep the unicorn service type?


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93XgnF39tLYS-EU5x:-KK9kYDmMrDWZiOSLnUI:160353967) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L153)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Done.
</details>
1/2

---

*[src/app/ui/loader/loader-service.directive.js, line 122 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9FLhPD7-wHPeuxNvW:-KK9klxANz7Mxygy3uGe:926181472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.directive.js#L122)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Done.
</details>
There are more below (also `select*` comments maybe, but those are one liners)

---

*[src/app/ui/loader/loader-service.html, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9Iu5MLGkv6LJpFHkX:-KK9kwfW_epbdzIxMPbV:1672174364) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.html#L3)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Nice!
> 
> Do I keep the unicorn service type?
> 
</details>
Ask @cynngah 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/loader/loader-service.html, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9Iu5MLGkv6LJpFHkX:-KK9mz-r-HT_SQ3ydj_0:472869301) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.html#L3)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Ask @cynngah 
</details>
:+1: :+1:  :100: :100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by AleksueiR** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93XgnF39tLYS-EU5x:-KK9nS5EpweZU3B3cUs1:1706342534) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L153)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> 1/2
</details>
Done ?

---

*[src/app/ui/loader/loader-service.directive.js, line 122 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9FLhPD7-wHPeuxNvW:-KK9nU3-epqGaE5SJqgd:2072273722) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/ui/loader/loader-service.directive.js#L122)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> There are more below (also `select*` comments maybe, but those are one liners)
</details>
Done again! :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93XgnF39tLYS-EU5x:-KK9okf-sscFPerTn062:-1300681936) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L153)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Done ?
</details>
Missed resembling

---

*[src/app/ui/loader/loader-service.directive.js, line 147 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9ox5EgNwvbjhrP1b8:-KK9ox5EgNwvbjhrP1b9:579452775) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b1e9f27a59f27c1ea024f0efce2302dbfac78da2/src/app/ui/loader/loader-service.directive.js#L147)):*
> ```JavaScript
> 
>         /**
>          * Clears service url field and all error displayed; sets the form into prestine, untouched state (so no default validation errors (like "required" or "not a proper url") will show)
> ```

Typo: pristine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by AleksueiR** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK93XgnF39tLYS-EU5x:-KK9qiIVJhiLsVIMWA2E:5173007) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fb01bb529a150b11d767bbc1043d1b71fac4b31/src/app/geo/layer-blueprint.class.js#L153)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Missed resembling
</details>
:D

---

*[src/app/ui/loader/loader-service.directive.js, line 147 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762#-KK9ox5EgNwvbjhrP1b8:-KK9qhklIJdPAekszwjb:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b1e9f27a59f27c1ea024f0efce2302dbfac78da2/src/app/ui/loader/loader-service.directive.js#L147)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Typo: pristine
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/762)*

**Pull request merged**
