### PR TITLE
Zoom to Feature offset

### LINKED ISSUE #378: bug(ui): datatable zoomTo target should be offset
When zooming to a feature from a datatable, the map centers on the point which gets positioned on the lower edge of the datatable panel. As the panel takes half of the vertical space, the zoomto target should be offset "up" so the actual point ends up in the center of the visible half of the map.

### PR DESCRIPTION
**Pull request by cynngah**
Closes #378 

Zoom to feature now centers at middle of visible map

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/520)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/map.service.js, line 304 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFtIMDXFi_5YaBvwuSN:-KFtIMDY2ZI-t4p3gsx_:1060282042) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5da1fc06d754135d38183002ef75469280a42bef/src/app/geo/map.service.js#L304)):*
Will this work correctly for multiple app instances?

---

*[src/app/geo/map.service.js, line 305 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFtIBjwRLrFEWkKChK0:-KFtIBjxAYkwZziIFpjJ:1412930397) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5da1fc06d754135d38183002ef75469280a42bef/src/app/geo/map.service.js#L305)):*
Can you add a comment as to why this is the proper ratio?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/map.service.js, line 304 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFtIMDXFi_5YaBvwuSN:-KFtoSFtCWVN6j8bWmcl:362995429) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5da1fc06d754135d38183002ef75469280a42bef/src/app/geo/map.service.js#L304)):*
To work around this, use `layoutService` from the `layout` module. It has placeholders for node references related to map components. In the `shell.directive`'s `link` function you can add something like this `layoutService.panels.shell = el;` to store a reference to the map container node and then use it when you need to find its dimensions. You can do the same to the side panel. This way we don't care if there is more than one instance of the map.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by cynngah** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/map.service.js, line 304 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFtIMDXFi_5YaBvwuSN:-KFufpdqOUBigpyWBAQp:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5da1fc06d754135d38183002ef75469280a42bef/src/app/geo/map.service.js#L304)):*
Done.

---

*[src/app/geo/map.service.js, line 305 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFtIBjwRLrFEWkKChK0:-KFufqe37Jj5jR0ElcqR:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5da1fc06d754135d38183002ef75469280a42bef/src/app/geo/map.service.js#L305)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 6 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/layout/storage.service.js, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFy-CJ-lnF47Yly7vxA:-KFy-CJ-lnF47Yly7vxB:-1188128591) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82c53239f057b7d57795ca587aa1741cb45a9e7e/src/app/layout/storage.service.js#L27)):*
Services don't need controllers. You can remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by AleksueiR** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index-many.html, line 24 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFy-k3tenqRoCD5A5m3:-KFy-k3tenqRoCD5A5m4:-254818926) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82c53239f057b7d57795ca587aa1741cb45a9e7e/src/index-many.html#L24)):*
For consistency, put styles in the style block above please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by cynngah** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index-many.html, line 24 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFy-k3tenqRoCD5A5m3:-KFy8WdSSXt9W98va50z:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82c53239f057b7d57795ca587aa1741cb45a9e7e/src/index-many.html#L24)):*
Done.

---

*[src/app/layout/storage.service.js, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520#-KFy-CJ-lnF47Yly7vxA:-KFy8VCdzxM9U8xP9vrT:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82c53239f057b7d57795ca587aa1741cb45a9e7e/src/app/layout/storage.service.js#L27)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 6 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/520)*

**Pull request merged**
