### PR TITLE
Bookmarking

### PR DESCRIPTION
**Pull request by spencerwahl**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/798)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiSir_vrdrPHl5HI68:-KKiSir_vrdrPHl5HI69:-1401187647) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/bookmark.service.js#L9)):*
> ```JavaScript
>      *
>      * @description
>      *
> ```

Excellent description.

---

*[src/app/core/bookmark.service.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiYBP3nRpr7-PRYL47:-KKiYBP44trWUg7PSsFA:-703523673) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/bookmark.service.js#L47)):*
> ```JavaScript
>             });
> 
>             const bookmark =  basemap + ',' + extent.x + ',' + extent.y + ',' + extent.zoom +
> ```

This seems like a good candidate for ES6 template strings.

---

*[src/app/core/bookmark.service.js, line 70 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiZI_EBxPgHkM7MixY:-KKiZI_EBxPgHkM7MixZ:588520051) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/bookmark.service.js#L70)):*
> ```JavaScript
>             const info = bookmark.match(pattern);
> 
>             const basemap = decode64(info[1]);
> ```

`const [basemap, x, y, zoom] = [1,2,3,4].map(i => decode64(info[i]));` ?

---

*[src/app/core/core.run.js, line 45 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiPq4ydzENeHW6cYil:-KKiPq4ydzENeHW6cYim:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/core.run.js#L45)):*
> ```JavaScript
>         /********************/
> 
>         function bookmarkCallback(config) {
> ```

jsdoc

---

*[src/app/core/core.run.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiOjnAG4UPo_IpLjNB:-KKiOjnAG4UPo_IpLjNC:186539474) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/core.run.js#L46)):*
> ```JavaScript
> 
>         function bookmarkCallback(config) {
>         const bookmarkAttr = $rootElement.attr('rv-restore-bookmark');
> ```

indentation seems to be off, but jscs didn't complain?

---

*[src/app/core/core.run.js, line 116 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiPx7axbHVbXG1KwEU:-KKiPx7axbHVbXG1KwEV:-2139152306) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/core.run.js#L116)):*
> ```JavaScript
>         }
> 
>         function getBookmark() {
> ```

jsdoc (also on centerAndZoom)

---

*[src/app/geo/layer-record.class.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiSB2TsLnnQ3uLXJyp:-KKiSB2TsLnnQ3uLXJyq:-1942132919) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/geo/layer-record.class.js#L107)):*
> ```JavaScript
>             }
> 
>             makeLayerBookmark () { throw new Error('This should be overridden in subclasses'); }
> ```

I realize most of this file wasn't `jsdoc`ed initially (mostly because I wasn't sure if this version would get through the PR).  But we should start now (feel free to doc only the top level functions and use `@see` liberally in subclasses)

---

*[src/app/geo/layer-record.class.js, line 121 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiQd6Jnat1pX38eNUE:-KKiQd6Jnat1pX38eNUF:-109153589) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/geo/layer-record.class.js#L121)):*
> ```JavaScript
> 
>                 props.forEach((prop, index) => {
>                     result.options[prop] = {};
> ```

`result.options[prop] = { value: lookup[prop](info[index]) };` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by spencerwahl** [comment]
Review status: 12 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiSir_vrdrPHl5HI68:-KKj-7Bmbrgv8P5F8Kjd:-734653125) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/bookmark.service.js#L9)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Excellent description.
</details>
Fixed :smile:

---

*[src/app/core/bookmark.service.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiYBP3nRpr7-PRYL47:-KKiwXZ52GOB3rzDBvsx:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/bookmark.service.js#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> This seems like a good candidate for ES6 template strings.
</details>
Done.

---

*[src/app/core/bookmark.service.js, line 70 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiZI_EBxPgHkM7MixY:-KKiwTOoMyZaz4zwnCnP:-1687320219) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/bookmark.service.js#L70)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `const [basemap, x, y, zoom] = [1,2,3,4].map(i => decode64(info[i]));` ?
</details>
magic :sparkles: 

---

*[src/app/core/core.run.js, line 45 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiPq4ydzENeHW6cYil:-KKjOrxSeZUE6aOEBsBy:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/core.run.js#L45)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---

*[src/app/core/core.run.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiOjnAG4UPo_IpLjNB:-KKiwfvoUUF1zNkBb2_A:1109011882) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/core.run.js#L46)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> indentation seems to be off, but jscs didn't complain?
</details>
Yeah it didn't get picked up. Good catch :+1: 

---

*[src/app/core/core.run.js, line 116 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiPx7axbHVbXG1KwEU:-KKjHQpyg_2hYvJ4Mats:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/core/core.run.js#L116)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc (also on centerAndZoom)
</details>
Done.

---

*[src/app/geo/layer-record.class.js, line 121 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiQd6Jnat1pX38eNUE:-KKiwxj6H6_DPxIGme0K:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/geo/layer-record.class.js#L121)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `result.options[prop] = { value: lookup[prop](info[index]) };` ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by spencerwahl** [comment]
Review status: 12 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/geo/layer-record.class.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiSB2TsLnnQ3uLXJyp:-KKjXtP5UWDVND5818fK:1810668884) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/geo/layer-record.class.js#L107)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I realize most of this file wasn't `jsdoc`ed initially (mostly because I wasn't sure if this version would get through the PR).  But we should start now (feel free to doc only the top level functions and use `@see` liberally in subclasses)
</details>
Could you give an example of how to link with see? `@see layerRecord.makeLayerBookmark` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjf1vM9CkB2eyQ-c96:-KKjf1vM9CkB2eyQ-c97:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L27)):*
> ```JavaScript
>         /************************/
> 
>         function getBookmark() {
> ```

jsdoc

---

*[src/app/core/bookmark.service.js, line 54 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjewitIN5j5Wi34xaL:-KKjewitIN5j5Wi34xaM:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L54)):*
> ```JavaScript
>         }
> 
>         function parseBookmark(bookmark, config) {
> ```

jsdoc

---

*[src/app/core/bookmark.service.js, line 127 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjfx_mTVc99zz-M-XL:-KKjfx_ncIGmUJF9BQi_:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L127)):*
> ```JavaScript
>         }
> 
>         function encode64(string) {
> ```

jsdoc

---

*[src/app/core/bookmark.service.js, line 131 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjfyUZESFPF1OmB5le:-KKjfyUZESFPF1OmB5lf:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L131)):*
> ```JavaScript
>         }
> 
>         function decode64(string) {
> ```

jsdoc

---

*[src/app/geo/layer-record.class.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiSB2TsLnnQ3uLXJyp:-KKjfXEAWA6rgt8D38FP:-1164283382) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/geo/layer-record.class.js#L107)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> Could you give an example of how to link with see? `@see layerRecord.makeLayerBookmark` ?
</details>
We'll have to test a bit.  I believe what you wrote should work, but it may need the full namespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by spencerwahl** [comment]
Review status: 16 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjf1vM9CkB2eyQ-c96:-KKjjiEdB4E9mBWWDkAS:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L27)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---

*[src/app/core/bookmark.service.js, line 54 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjewitIN5j5Wi34xaL:-KKjjiU8y_pyNtuCGF51:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L54)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---

*[src/app/core/bookmark.service.js, line 127 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjfx_mTVc99zz-M-XL:-KKjjimnKH2ChFjnN8kj:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L127)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---

*[src/app/core/bookmark.service.js, line 131 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjfyUZESFPF1OmB5le:-KKjjj6OxG7KHH0aoYIZ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L131)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---

*[src/app/geo/layer-record.class.js, line 107 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKiSB2TsLnnQ3uLXJyp:-KKjjn-WO924wPYITXZ1:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74e7cbbe03162b328a5474984a4c588f333f99ab/src/app/geo/layer-record.class.js#L107)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> We'll have to test a bit.  I believe what you wrote should work, but it may need the full namespace.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/bookmark.service.js, line 127 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjfx_mTVc99zz-M-XL:-KKkjbvrFQOVDH6JOt2I:-354590241) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L127)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> Done.
</details>
Sorry for the extra request, can you also add that this is a url safe base64 encoding: https://tools.ietf.org/html/rfc4648#page-7 (same with decode)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by AleksueiR** [comment]
Reviewed 13 of 18 files at r1, 4 of 6 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 141 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKmexPC270u9Vqficn9:-KKmexPC270u9VqficnA:-1488313480) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0d42aafcbe1a1dd205e45ec59c33d45260193e4a/src/app/core/config.service.js#L141)):*
> ```JavaScript
>                         .then(() => {
>                             isInitialized = true;
>                             fulfill(service.data[langs[0]]);
> ```

If `$translate.use` is removed, how do we set the initial language now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by spencerwahl** [comment]
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 127 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKjfx_mTVc99zz-M-XL:-KKnLuXaxDR-jKtoHWDY:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cdca07c7a09b57304389625fd1a9299202770c37/src/app/core/bookmark.service.js#L127)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Sorry for the extra request, can you also add that this is a url safe base64 encoding: https://tools.ietf.org/html/rfc4648#page-7 (same with decode)
</details>
Done.

---

*[src/app/core/config.service.js, line 99 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKnJ1y61yMyABYGyckZ:-KKnJ1y61yMyABYGyck_:93150427) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0d42aafcbe1a1dd205e45ec59c33d45260193e4a/src/app/core/config.service.js#L99)):*
> ```JavaScript
> 
>                     // set the language right away and not wait the initialization to be fullfilled
>                     $translate.use(langs[0]);
> ```

Christian had added this line here

---

*[src/app/core/config.service.js, line 141 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-KKmexPC270u9Vqficn9:-KKnJ-xD2n4bic2uU1m0:-826085819) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0d42aafcbe1a1dd205e45ec59c33d45260193e4a/src/app/core/config.service.js#L141)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> If `$translate.use` is removed, how do we set the initial language now?
</details>
Ill tag the line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798#-:-KKoEHlItd8YgMWRs2OC:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Comment by cynngah** [comment]
Reviewed 7 of 18 files at r1, 2 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, 7 of 7 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/798)*

**Pull request merged**
