### PR TITLE
Part 2 of basemap repojection: please review the geoApi PR first

### PR DESCRIPTION
**Pull request by ec-dev**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/358)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSYctSt8cn5jmk07bC:-KBSYctSt8cn5jmk07bD:1572313420) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L1)):*
James can give you some pointers on taming the cyclomatic beast. I think we should try to keep it under the agreed before number, 10.

---

*[src/app/geo/geo.service.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBS_xfndnKNfoaAdRfi:-KBS_xfndnKNfoaAdRfj:-129139635) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L19)):*
@/all maybe just add `configService` as a dependency, so we don't have to pass it in all the time. What do you think?

---

*[src/app/geo/geo.service.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSiQio_P1ufqMtGGlQ:-KBSiQio_P1ufqMtGGlR:13746074) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L56)):*
_Not related directly to this PR_: I think `gapi` should not be exposed on service. Only `geoService` (and `idenitfyService`) talks directly to `geoApi`, all other services should go through `geoService`.

---

*[src/app/geo/geo.service.js, line 606 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBScrBBOMHjoHWpk-xR:-KBScrBBOMHjoHWpk-xS:1730912456) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L606)):*
I might be wrong (very wrong), but I was thinking something along the following lines. @alyec, please correct me here.

```js

// keep a rejected promise here until it's replaced by a real promise; 
// this way anything trying to use `map` before it's created, will fail and can be caught
let mapPromise = $q.reject(); 


function buildMap (...) {
    // body...
    
    mapPromise = $q((resolve, reject) => {
        const esriMapObject = new service.gapi.mapManager.Map(domNode, {
            basemap: initialBasemap,
            zoom: 4,
            center: [-100, 50]
        });

        service.gapi.events.wrapEvents(esriMapObject, {
            load: () => resolve(esriMapObject), // resolve with the map object so it's passed to `then`
            error: () => reject('map failed to load.')
        });
    });
}

// ... some "code"

//  ... somewhere else

function func(...) {

    mapPromise.then(map => {
        // do stuff with map

        map.addLayer();
    })

}

```

---

*[src/app/ui/basemap/basemap.directive.js, line 169 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSZ_OiM8j55Ae0Gicj:-KBSZ_OiM8j55Ae0Gick:-461305657) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/ui/basemap/basemap.directive.js#L169)):*
As a rule, all DOM manipulation should only be done in a directive's `link` function.
In this case, the `basemap` directive should not know about the main map node; it's better, I think, for the `init-map` directive to register its node with `geoService` when first instantiated which then can be reused to rebuild the map when needed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by ec-dev** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBS_xfndnKNfoaAdRfi:-KBTIvPXUhpBypfGXcZ-:2031410789) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L19)):*
Excellent idea. Code is much cleaner after update. Will be visible in next PR Sync.

---

*[src/app/ui/basemap/basemap.directive.js, line 169 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSZ_OiM8j55Ae0Gicj:-KBTIiW4dQrM6SLu6G9K:323845967) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/ui/basemap/basemap.directive.js#L169)):*
Agreed and done for next sync.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBS_xfndnKNfoaAdRfi:-KBTLvXTaz5I8gwjbD5v:-1959442958) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L19)):*
Might be missing something, what is the benefit?  Right now it is being passed via the `init-map` directive IIRC, and by allowing for config fragments to be passed into functions directly it makes things much easier to test as opposed to having to mock `configService`.  But I might be missing something important.

---

*[src/app/geo/geo.service.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSiQio_P1ufqMtGGlQ:-KBTOnMb_hfSNkMgZFLi:1605498549) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L56)):*
:white_check_mark: 

---

*[src/app/geo/geo.service.js, line 577 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBTORF_mUiWjN4uP9l9:-KBTORFa2t-TZnnagnh_:1768951857) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L577)):*
I don't think this should be moved.  It can be split up, but config parsing is a viewer task and the `geoApi` shouldn't know about it.

---

*[src/app/geo/geo.service.js, line 606 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBScrBBOMHjoHWpk-xR:-KBTNnUi3AbNK2PqTDhD:424043989) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L606)):*
I'm not entirely sure if it's better to reject the promise early, or to allow other code to register well before the map is created.  But I do think that holding a reference to `mapPromise` is needed so we can clean up some of our dependency chains.

---

*[src/app/geo/geo.service.spec.js, line 171 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBTNIhfSbrwre3U7AUY:-KBTNIhgmapIknN3nB80:-1498058948) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.spec.js#L171)):*
It calls `buildMap` and puts a spy on `geoApi`'s ESRI Map object to make sure that `buildMap` at some point calls it.  With async initialization you may need to convert this to an async test.  I don't think it needs to be disabled.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBS_xfndnKNfoaAdRfi:-KBTrHu7p8OlomAcaLr9:437294490) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L19)):*
Alex, I run into issues with unit-test. break all other tests in UI (any modules that uses geoService). Will restore the code back to original state for now.

---

*[src/app/geo/geo.service.spec.js, line 171 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBTNIhfSbrwre3U7AUY:-KBTqkXCi67ja11jjMm6:-2142672075) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.spec.js#L171)):*
Aly, need your help on this one. How do I convert this to async test?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBS_xfndnKNfoaAdRfi:-KBTR3VqICM9cFdiZbIf:701440988) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L19)):*
Sure, that's probably what Aly was referring to.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/geo.service.spec.js, line 171 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBTNIhfSbrwre3U7AUY:-KBUCCxfLvtD5eMqJxjr:2138980074) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.spec.js#L171)):*
Adding a done callback in the part of the code you are interested in testing is usually sufficient: http://jasmine.github.io/2.1/introduction.html#section-Asynchronous_Support .  If not feel free to bug me on gitter to walk through it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by ec-dev** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 577 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBTORF_mUiWjN4uP9l9:-KBUJSetoQU1W2szzxuN:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L577)):*
Done.

---

*[src/app/geo/geo.service.js, line 606 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBScrBBOMHjoHWpk-xR:-KBUJQ_TalDx8jwMDPnp:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L606)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by ec-dev** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSYctSt8cn5jmk07bC:-KBUK9kXBD5xqYC2j5AR:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by ec-dev** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSiQio_P1ufqMtGGlQ:-KBUKAoO-LGS7m-sNRM2:-561394714) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L56)):*
Sorry guys, what do I need to do for this one? Do I just click done. as this is not for current PR?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBSiQio_P1ufqMtGGlQ:-KBUKzOUyLTN5fGAVsKc:1033531320) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1fb826d58294326ebaa65c5338badb246109656c/src/app/geo/geo.service.js#L56)):*
Can you just add a comment for now (just add to the existing FIXME as we can probably sort out both at the same time)?

---

*[src/app/geo/geo.service.js, line 349 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBULTvteQmjx0PwGhP7:-KBULTvteQmjx0PwGhP8:1487367610) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5598e585bcba409f3f2c2a72b6b5d8ef6d3cddd5/src/app/geo/geo.service.js#L349)):*
I don't think we should expose this anymore, if we have `mapPromise` that should be the method to access `map`.  Same with mapManager below, all these should become async values which are accessed via promises.

---

*[src/app/geo/geo.service.spec.js, line 133 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358#-KBUM5-WGsYQwuSMZJ_x:-KBUM5-XpM4WjeFYQREx:914599973) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5598e585bcba409f3f2c2a72b6b5d8ef6d3cddd5/src/app/geo/geo.service.spec.js#L133)):*
Calling `done()` before the `expect` calls will bypass all of them.  Same issue with the map creation test.  To test buildMap properly you probably want the `done` call inside a resolution to `mapPromise`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/358)*

**Pull request closed without merging**
