### PR TITLE
Overview map

### PR DESCRIPTION
**Pull request by ec-dev**
setup overview map using setting and geoAPI

* setup mapSettings for scalebar

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/291)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/291)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/291)*

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/291)*

**Comment by alyec** [comment]
commit scopes need to be fixed: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#commit-scopes

---

Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/291#-:-K9iF8tlte1_jBp6pGrj:1615926621)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/291)*

**Pull request merged**
