### PR TITLE
Combined reporting; expanded style checks

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/33)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 2 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 376 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0BWLzzgcJNYu79VWZd)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c451999e3a88594fbedabfa364c6dea35a490101/gulpfile.js#L376)):</sup>
If `relative` is `undefined`, it should default to `true`. Wouldn't moving the `options` declaration to the top break it?
P.S.: Can we use babel/es6 in the gulpfile somehow?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by alyec** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[gulpfile.js, line 376 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0BWLzzgcJNYu79VWZd)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c451999e3a88594fbedabfa364c6dea35a490101/gulpfile.js#L376)):</sup>
fixed, that was a really stupid mistake

I was thinking about it, but unless we run babel manually we can't do much with it.  We can adopt the subset of ES6 that node 4 supports if everyone has that installed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 376 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0BWLzzgcJNYu79VWZd)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c451999e3a88594fbedabfa364c6dea35a490101/gulpfile.js#L376)):</sup>
That would be nice. We can ask in the main chat room.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by jolevesq** [comment]
Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 175 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0Bd7AU03NdxRvvYNOq)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81adaeecab75df612d78ef05e3242df307bab442/gulpfile.js#L175)):</sup>
Why did you put the comment on the same line? In style guide 17.2 it is said it should be on the line above.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 175 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0Bd7AU03NdxRvvYNOq)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81adaeecab75df612d78ef05e3242df307bab442/gulpfile.js#L175)):</sup>
I didn't like having the extra space before the line comment and I didn't realize same line comments were against the style guide (I guess there's no enforcing option in JSCS).

I actually prefer stuff like
```js
var filtered = []; // list of features with extent filter applied
```
over the version where the comment is on a separate line (as long as it's relatively short).  Would it be worth asking on gitter to see if we should add an override to the style guide?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 175 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0Bd7AU03NdxRvvYNOq)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81adaeecab75df612d78ef05e3242df307bab442/gulpfile.js#L175)):</sup>
Yes we should do it. I am not sure what I prefer the most. Like you said, if it is on the same line it needs to be short.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 175 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0Bd7AU03NdxRvvYNOq)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81adaeecab75df612d78ef05e3242df307bab442/gulpfile.js#L175)):</sup>
@AleksueiR can you merge this version?  We can ask in the fgp room on Tuesday and if we decide against same line comments I'll patch it separately.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gulpfile.js, line 175 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33#-K0Bd7AU03NdxRvvYNOq)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81adaeecab75df612d78ef05e3242df307bab442/gulpfile.js#L175)):</sup>
It's blocked; @jolevesq, could your resolve this discussion, it's blocking the merge button :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/33)

**Pull request merged**
