### PR TITLE
feat(ui): add full-screen functionality

### LINKED ISSUE #151: feat(ui): add full-screen functionality
- [x] user can expand the viewer to fullpage via the menu option
- [x] index-wet page can be used to demo fullscreen functionality

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #151.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/539)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 11 of 13 files at r1, 2 of 3 files at r2.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index-many.html, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539#-KGSr5bnic3pPkIIiT_R:-KGSr5bnic3pPkIIiT_S:-74305021) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c4d9f83bc2ef81dbef3f947485aae59dd46e38c8/src/index-many.html#L9)):*
Glad to see you're on board with inline CSS.  Can I interest you in some inline Javascript as well?

---

*[src/app/ui/common/full-screen.service.js, line 42 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539#-KGSsEHVmupUg1o9BfaN:-KGSsEHVmupUg1o9BfaO:-1224096264) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c4d9f83bc2ef81dbef3f947485aae59dd46e38c8/src/app/ui/common/full-screen.service.js#L42)):*
jsdoc header missing (also on onComplete)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539)*

**Comment by AleksueiR** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index-many.html, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539#-KGSr5bnic3pPkIIiT_R:-KGSssRcfNfGfaqGO6eQ:899924695) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c4d9f83bc2ef81dbef3f947485aae59dd46e38c8/src/index-many.html#L9)):*
:heavy_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539#-:-KGSvd8QoJN-V1yWhWz0:1417088721)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/full-screen.service.js, line 42 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539#-KGSsEHVmupUg1o9BfaN:-KGSvlvfzilZmO6aY1WN:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c4d9f83bc2ef81dbef3f947485aae59dd46e38c8/src/app/ui/common/full-screen.service.js#L42)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539)*

**Comment by spencerwahl** [comment]
Reviewed 11 of 13 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539)*

**Comment by cynngah** [comment]
Reviewed 9 of 13 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/539)*

**Pull request merged**
