### PR TITLE
fix(geo): correct logic assigning feature layer symbology

### LINKED ISSUE #869: Feature Layers from Group Layer services can have the wrong symbology in legend
Try to add [this layer](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NorthAmerica/energy_infrastructure_of_north_america_en/MapServer/7) to the map. The logic inside `legend.service.js` assumes `layerId` matches positions of a corresponding legend object in a legend endpoint. This is true, unless the service has group nodes with no symbology, then they are skipped.

`layerId` of the aforementioned layer is 7; the legend endpoint returns the following array:
```
0 "Natural Gas Processing Plants"
1 "Liquefied Natural Gas Terminals"
2 "Refineries"
4 "Refinery"
5 "Upgrader"
6 "Asphalt Refinery"
7 "Power Plants, 100 MW or more"
9 "Biomass"
10 "Coal"
11 "Geothermal"
12 "Hydroelectric"
13 "Natural Gas"
14 "Nuclear"
15 "Other"
16 "Petroleum"
17 "Pumped Storage"
18 "Solar"
19 "Wind"
20 "Renewable Energy Power Plants, 1 MW or more"
22 "Biomass"
23 "Geothermal"
24 "Hydroelectric"
25 "Pumped Storage"
26 "Solar"
27 "Wind"
```

If you pick seventh item from the array, it's `Biomass`, not `Power Plants, 100 MW or more`.

Instead of fixing this logic, it might be better to display geoApi-generated symbology as it works correctly already.

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #869

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/885)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 152 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/885#-KM_PNxyf1rSQh8uhSYV:-KM_PNxyf1rSQh8uhSYW:-1984452003) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6afc22c67d149da0b117f94d750b5e775bcfd1d2/src/app/geo/legend.service.js#L152)):*
> ```JavaScript
>                         // TODO: switch to getting symbology from the attribute bundle
>                         applySymbology(state, data.layers.find(layer =>
>                             layer.layerId === parseInt(state.featureIdx, 10))));
> ```

FYI parseInt assumes 10 for ES5 so it should be safe to omit: https://es5.github.io/#x15.1.2.2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/885)*

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/app/geo/legend.service.js, line 152 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/885#-KM_PNxyf1rSQh8uhSYV:-KM_QlpgSMi0raTWHH2P:236591812) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6afc22c67d149da0b117f94d750b5e775bcfd1d2/src/app/geo/legend.service.js#L152)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> FYI parseInt assumes 10 for ES5 so it should be safe to omit: https://es5.github.io/#x15.1.2.2
</details>
I thought I remembered that, but I couldn't find where to look that up. MDN still says to include the radix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/885)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/885)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/legend.service.js, line 152 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/885#-KM_PNxyf1rSQh8uhSYV:-KM_RHXUcYxCeflJxmrO:1554247118) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6afc22c67d149da0b117f94d750b5e775bcfd1d2/src/app/geo/legend.service.js#L152)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I thought I remembered that, but I couldn't find where to look that up. MDN still says to include the radix.
</details>
IIRC IE9 was the last ES5 non-compliant browser so it should be safe for us (probably good to keep the radix as a general rule for other projects).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/885)*

**Pull request merged**
