### PR TITLE
Fixes the colour of basemap names

### LINKED ISSUE #1016: Basemap names not visible
Tested build: http://fgpv.cloudapp.net/demo/v1.0.1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

It looks like basemap text names are missing, or not visible

image

### PR DESCRIPTION
**Pull request by AleksueiR**
No muffins.

Closes #1016

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1017)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1017)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1017)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.html, line 30 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1017#-KOAOjeCi3teqptJsEF0:-KOAOjeCi3teqptJsEF1:1761008187) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/52003c442e692f25c4155d0bc04a45fbbf7e9eed/src/app/layout/shell.html#L30)):*
> ```HTML
> <rv-panel type="side" rv-state="side" class="rv-plug-slide-right"></rv-panel>
> 
> <rv-mapnav rv-morph="mapnav"></rv-mapnav>
> ```

This should be kept above the main panel, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1017)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.html, line 30 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1017#-KOAOjeCi3teqptJsEF0:-KOARNJT_0M8eHn-TD_9:-1653557753) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/52003c442e692f25c4155d0bc04a45fbbf7e9eed/src/app/layout/shell.html#L30)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> This should be kept above the main panel, right?
</details>
If it's between the appbar and the main panel, then the focus would jump from the app bar to the map nav controls and not to the main panel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1017)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1017)*

**Pull request merged**
