### PR TITLE
Add default blank logo

### LINKED ISSUE #888: Picture not displaying on Menu panel
Tested on Build: http://fgpv.cloudapp.net/demo/v1.0.0-rc2/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
There should be a picture displayed on top of the panel after clicking Menu button.
image

### PR DESCRIPTION
**Pull request by alyec**
Closes #888

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/909)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/layout/shell.directive.js, line 62 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909#-KMzHA8hixj-OmR7Lpo-:-KMzHA8hixj-OmR7Lpo0:-812579757) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd93884c8a2000e16a50904383f38d5552336b99/src/app/layout/shell.directive.js#L62)):*
> ```JavaScript
>         configService.getCurrent().then(data => {
>             self.markerImageSrc = data.logoUrl ||
>                                   'data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22/%3E';
> ```

Move this to the template as discussed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_app-menu.scss, line 45 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909#-KMzPUvhjm_YRgJLpkDz:-KMzPUvhjm_YRgJLpkE-:2025298054) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c820bc75b7e977954a3eab170aa8db2383700eff/src/content/styles/modules/_app-menu.scss#L45)):*
> ```SCSS
> 
>                 img {
>                     flex-shrink: 0;
> ```

Could you add comment that this is IE11 fix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_app-menu.scss, line 45 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909#-KMzPUvhjm_YRgJLpkDz:-KMzPioHNS-wb4FERmgC:1568175865) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c820bc75b7e977954a3eab170aa8db2383700eff/src/content/styles/modules/_app-menu.scss#L45)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Could you add comment that this is IE11 fix?
</details>
And maybe link to that page with flexbugs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/layout/shell.directive.js, line 62 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909#-KMzHA8hixj-OmR7Lpo-:-KMzRa05SrH9kEvlY9Xl:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd93884c8a2000e16a50904383f38d5552336b99/src/app/layout/shell.directive.js#L62)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Move this to the template as discussed.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_app-menu.scss, line 45 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909#-KMzPUvhjm_YRgJLpkDz:-KMzY3jSJKc3GANoH00Q:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c820bc75b7e977954a3eab170aa8db2383700eff/src/content/styles/modules/_app-menu.scss#L45)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> And maybe link to that page with flexbugs.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909#-:-KMzbUXQq0azaPjytAXL:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/909)*

**Pull request merged**
