### PR TITLE
V2.2.0 final

### LINKED ISSUE #1076: Create a Human Readable Doc from the Config Schema
### Current design and implementation progress
- [x] Setup [outside repo](https://github.com/milesap/schema-to-docs/tree/develop) with basic npm support 
- [x] **Stage 1 transformation:** Dereference `$ref` objects (using a schema.json copy from fgpv).
- [x] **Stage 2 transformation:** Circular references are ignored in stage one. Manually deference circular dependencies **once** and add an additional attribute to it for later identification.
- [x] **Stage 3 transformation:** Simplification -  this involves adding/removing attributes to help improve readability. For example, `allOf` would be replaced by all of its requirements. Similarly, `oneOf` is spawned into multiple possible combinations of actual implementation schema.
- [x] **Stage 4 transformation:** Convert into a JS object, which enforces any circular attributes which may cause issues on the following step.
- [x] **Rendering:** Given the JS object, render it as an interactive HTML document(s).
- [x] **Integration:** Test importing library in FGPV, schema passing and returning works as intended
- [ ] **Optional:** Allow support as a webpack plugin

Once this is complete, a new task will be assigned to go through the schema to correct any schema validation warnings (unused attributes), and to have each item well described.

### Initial issue post
From some basic testing at the time (2016) automated tools which take a JSON schema and produce docs run into issues.  Seems to be mostly an issue with following references.

Worth checking the existing tools to see if any of them produce reasonable documentation with our schema.

As an alternate approach we can use / write a tool which scraps every top level object, and then add some custom documentation showing how all the pieces link together (ideally an mspaint masterpiece from @james-rae ).

### PR DESCRIPTION
**Pull request by milesap**
## Description
- Version bump for viewer and geoApi
- Version updates on external dependencies
- Minor bug squashing

Closes #1076, #2498, #2525

## Testing
Sanity checks in chrome

## Documentation
No

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2530)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/settings/settings-content.html, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530#-L0j0DgCFKmVd7Lmo5Uo:-L0j0DgCFKmVd7Lmo5Up:bstt9xu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/90945b17d0d504b6e6a1f2c29e88459494105263/src/app/ui/settings/settings-content.html#L48)):*
> ```HTML
> </div>
> 
> <div class="rv-subsection hide-labels" ng-if="::(self.checkWMS() && !self.checkDisabledControls('styles') && self.checkStylesLength())">
> ```

Do we want to be hiding the labels? Since if there are multiple sub-layers selected with more than 1 style, the label will help to identify which style is being changed for which layer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530)*

**Comment by milesap** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/settings/settings-content.html, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530#-L0j0DgCFKmVd7Lmo5Uo:-L0j1R9r2EH68yUcFCZP:b-20n4vf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/90945b17d0d504b6e6a1f2c29e88459494105263/src/app/ui/settings/settings-content.html#L48)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Do we want to be hiding the labels? Since if there are multiple sub-layers selected with more than 1 style, the label will help to identify which style is being changed for which layer
</blockquote></details>

Wasn't sure what to do with them, I can keep them and just make them look prettier. Let me know

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/settings/settings-content.html, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530#-L0j0DgCFKmVd7Lmo5Uo:-L0j9WTlGJJoxaQnPNsg:b974wc4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/90945b17d0d504b6e6a1f2c29e88459494105263/src/app/ui/settings/settings-content.html#L48)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Wasn't sure what to do with them, I can keep them and just make them look prettier. Let me know
</blockquote></details>

I would like to keep the labels, but the top label is too close to the divider right now:


There needs to be a bit of a margin between the label and the divider, like with the refresh interval:


I noticed that the refresh interval section is wrapped in a `form`. Maybe wrapping styles in a form as well will give you the proper padding about the controls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530)*

**Comment by milesap** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/settings/settings-content.html, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530#-L0j0DgCFKmVd7Lmo5Uo:-L0jlyZH9e7afFtD04ta:bbnrf64) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/90945b17d0d504b6e6a1f2c29e88459494105263/src/app/ui/settings/settings-content.html#L48)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I would like to keep the labels, but the top label is too close to the divider right now:


There needs to be a bit of a margin between the label and the divider, like with the refresh interval:


I noticed that the refresh interval section is wrapped in a `form`. Maybe wrapping styles in a form as well will give you the proper padding about the controls.
</blockquote></details>

Wrapped in a `form` element, spacing looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530#-:-L0jpNX7NmzmNteAZ3Yv:bnfp4nl)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/settings/settings-content.html, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530#-L0j0DgCFKmVd7Lmo5Uo:-L0nqA1S1YKkIrdztOhC:b-alx8b6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/90945b17d0d504b6e6a1f2c29e88459494105263/src/app/ui/settings/settings-content.html#L48)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Wrapped in a `form` element, spacing looks good
</blockquote></details>

Indeed, looks dandy. :heavy_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2530#-:-L0nqEBxe90NTNE8a2xG:bnfp4nl)*

**Pull request merged**
