### PR TITLE
Data attribute translation

### PR DESCRIPTION
**Pull request by alyec**
## Description
#1665 

## Testing

Sample page, browser testing

## Documentation

Will get added to custom attribute doc pages.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- release notes have been updated (n/a)
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1670)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Index-one demo works. :lgtm: 

Can you update the rest of the sample pages.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index-one.html, line 21 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670#-KcOV4l0SUdZa6vnzFiL:-KcOV4l0SUdZa6vnzFiM:b-1p16wp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7288f4b8802d0a57f86dfd7e45cf4abec5965a97/src/index-one.html#L21)):*
> ```HTML
> <body>
>     
>     <div class="fgpv" is="rv-map" data-rv-config="config.${lang}.json" data-rv-langs='["en-CA", "fr-CA"]'
> ```

Do you want to remove `class="fgpv"`?

---

*[src/app/bootstrap.js, line 203 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670#-KcOVLBzEVmRDjp9D87G:-KcOVLBzEVmRDjp9D87H:be7lev0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7288f4b8802d0a57f86dfd7e45cf4abec5965a97/src/app/bootstrap.js#L203)):*
> ```JavaScript
> 
>         let appId = node.getAttribute('id');
>         customAttrs
> ```

Do we want to remove any existing `data-` attributes after convertion?

---

*[src/app/bootstrap.js, line 204 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670#-KcOW0eQ-XhNmH6VSRJv:-KcOW0eQ-XhNmH6VSRJw:b-os0s6r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7288f4b8802d0a57f86dfd7e45cf4abec5965a97/src/app/bootstrap.js#L204)):*
> ```JavaScript
>         let appId = node.getAttribute('id');
>         customAttrs
>             .filter(attrName => node.getAttribute(`data-rv-${attrName}`))
> ```

This can potentially filter out any attributes with value `false`. Maybe 
```js
typeof node.getAttribute(`data-rv-${attrName}`) !== 'undefined'
``` 
would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670#-:-KcOWL-sRO_wsFSXq0Dk:ba1p26a)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670)*

**Comment by AleksueiR** [comment]
Created a separate issue to address some comments: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1672

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670#-:-KcOiCWxmtIid4DWRoH9:bgcmgqw)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670#-:-KcOr_c9u5-3fQez-H3W:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670)*

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670)*

**Comment by AleksueiR** [comment]
Sample pages validate with no errors (some warnings). :medal_sports: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1670#-:-KcOseqMd84Qpideysyu:b97ckm2)*

**Pull request merged**
