### PR TITLE
chore(build): add schema defaults to core constant service

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/379)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gulpfile.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379#-KCGzzcWrBa7x6REkA_B:-KCGzzcWrBa7x6REkA_C:-1701105023) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6d777ef6e47f88fced4a3614a2b8e2f42e0101e4/gulpfile.js#L20)):*
const?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379)*

**Comment by AleksueiR** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379#-KCGzzcWrBa7x6REkA_B:-KCHO1hZ6KB5PZk0TG-Y:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6d777ef6e47f88fced4a3614a2b8e2f42e0101e4/gulpfile.js#L20)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/379)*

**Pull request merged**
