### PR TITLE
Queue external api calls

### PR DESCRIPTION
**Pull request by spencerwahl**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/530)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/injector.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGD_0edxp6PFd5XVOot:-KGD_0edxp6PFd5XVOou:-1558028021) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L101)):*
Maybe store nodes somewhere to avoid retrieving them again in app-seed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530)*

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/index-wet.html, line 57 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHqrtLprL6mnbWha0c:-KGHqrtLprL6mnbWha0d:-27262357) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/index-wet.html#L57)):*
first inline css, now inline javascript :+1: 

---

*[src/app/app-seed.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHqXOI89Jxijngbywy:-KGHqXOI89Jxijngbywz:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/app-seed.js#L8)):*
const

---

*[src/app/app-seed.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHq_7glZWY9jUq-iyY:-KGHq_7glZWY9jUq-iyZ:-2064383498) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/app-seed.js#L9)):*
this doesn't need to be declared in this scope, we can push the declaration into the `forEach` function

---

*[src/app/injector.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHrQTp8oWSeFJkzwiq:-KGHrQTp8oWSeFJkzwir:1198409675) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L56)):*
typo: exists

---

*[src/app/injector.js, line 63 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHrYdXvAERnv82KVet:-KGHrYdXvAERnv82KVeu:1067506085) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L63)):*
I assume `_mapRegistry` is attached to RV for `globalRegistry` to pick up.  If that is correct can you add this to the comment here?

---

*[src/app/injector.js, line 91 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHsV_isUNL_4OXthHd:-KGHsV_jiDdCRGo2f-F2:-983422128) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L91)):*
:+1: for helpful comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/app-seed.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHq_7glZWY9jUq-iyY:-KGHtB20cQUllyybO5BE:-1803787448) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/app-seed.js#L9)):*
Can just use a one-liner:
```js
node.appendChild(angular.element('<rv-shell class="md-body-1">')[0]);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530)*

**Comment by spencerwahl** [comment]
Review status: 1 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/index-wet.html, line 57 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHqrtLprL6mnbWha0c:-KGIG_uJp5Y5N1I7oU_d:1682117981) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/index-wet.html#L57)):*
I figured there wasn't much problem in a template meant for demos. I can change it if it's wanted.

---

*[src/app/app-seed.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHqXOI89Jxijngbywy:-KGI3zzwdlcsSXmeNXCP:1986673113) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/app-seed.js#L8)):*
Line removed

---

*[src/app/app-seed.js, line 9 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHq_7glZWY9jUq-iyY:-KGI3zKWbr73BQWTvBba:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/app-seed.js#L9)):*
Done.

---

*[src/app/injector.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHrQTp8oWSeFJkzwiq:-KGI3v5AFcDTEv6O8BBW:-831630370) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L56)):*
Done. (and in global registry too)

---

*[src/app/injector.js, line 63 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHrYdXvAERnv82KVet:-KGI3gKXmNt3pkmnq77m:-1196680061) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L63)):*
The `_mapRegistry` reference actually wasn't needed anymore. I replaced it with a reference to `nodes` and added a comment there.

---

*[src/app/injector.js, line 91 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHsV_isUNL_4OXthHd:-KGI3BIlP6M_9JQERSIr:-1703027219) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L91)):*
Alex gets the credit for this one

---

*[src/app/injector.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGD_0edxp6PFd5XVOot:-KGI3f8fQBpmNho4wAPB:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/app/injector.js#L101)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index-wet.html, line 57 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-KGHqrtLprL6mnbWha0c:-KGIHbZulGnIfFKGQrKh:2017127294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3988ffcb28272562c8c8a01518375adf6e03863c/src/index-wet.html#L57)):*
Not at all, please add more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530#-:-KGIILVMCrpR5mKSarfB:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/530)*

**Pull request merged**
