### PR TITLE
2236 2361 legend export

### LINKED ISSUE #2236: Legend display in Export image should be modified to reflect the top level elements
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc3/dev/samples/index-samples.html

Legend in export image reflects only immediate elements which might not be meaningful to the user. Please see below screenshot of the legend panel and the legend display in export image

image

image

### LINKED ISSUE #2361: Hide layers in export legend when out of scale
Hiding a layer in the toc will also hide it when exporting.

But if a layer is out of scale, it still shows up when we export. It should also be ignored.

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2236 
Closes #2361 

## Testing
Visually tested

## Documentation
In-line comments

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2370)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2370)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/export/export-legend.service.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2370#-Ktqx4GFDIXpEH4qC0HG:-Ktqx4GFDIXpEH4qC0HH:b-7nwnlo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbe22ca8971cb6707ff7360e1ab178533b1f5c0a/src/app/ui/export/export-legend.service.js#L53)):*
> ```JavaScript
> 
>         const legendData = extractLegendTree(configService.getSync.map.legendBlocks)
>             .filter(entry => entry.items.length > 0);
> ```

Better to move this into the `extractLegendTree` for clarity. You can append it to the its return statement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2370)*

**Comment by JahidAhmed** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/export/export-legend.service.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2370#-Ktqx4GFDIXpEH4qC0HG:-Ktr-pViwzT4n6_FtIu0:b-dtkds3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbe22ca8971cb6707ff7360e1ab178533b1f5c0a/src/app/ui/export/export-legend.service.js#L53)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Better to move this into the `extractLegendTree` for clarity. You can append it to the its return statement.
</blockquote></details>

Done, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2370)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2370)*

**Comment by AleksueiR** [comment]
:lgtm: Nice work!

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2370#-:-Ktr0z-8S0t-XLcYH9pl:bcmw7ss)*

**Pull request merged**
