### PR TITLE
fix(angular): allow multiple versions of angular on a page

### LINKED ISSUE #960: Handle cases where hosting page has Angular already
From Pauline George (NACEI):

> We tried to embed the map viewer and it is returning some errors.  After some investigation the errors maybe due to conflicts with the core.js and bootstrap.js files.  It seems like the conflict occurs if a site or application is already using angular (we are using angular).  There seems to be an open issue in github for this particular issue

### PR DESCRIPTION
**Pull request by milesap**
## Description
This allows for multiple angular versions to run on the same page. This still requires additional testing however it does currently work if:
- host page has angular app initialized prior to our, or;
- loads their version of angular after our application loads and scopes it into their bootstrap

Closes #960

## Testing
some, more needed, just an idea

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1844)

### CODE REVIEW

**Comment by milesap** [comment]
Added a working demo page for running multiple angular versions on a single page. Our viewer now loads its own version if an identical version is not already loaded on host. 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844#-:-KhX39K5E_rHNQvGfreL:b-gyx7p6)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/bootstrap.js, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844#-KiV3QW8zoJDigntEzGi:-KiV3QW8zoJDigntEzGj:bvlgohy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaa1db4ab2ab3207d308ba1015e74ae0c616af15/src/app/bootstrap.js#L98)):*
> ```JavaScript
>     // host page can continue to use their version if their app is loaded before ours, or they can manually
>     // bootstrap a scoped angular object like we do in app-seed.js
>     if (window.angular && window.angular.version.full !== dependencies.angular.ourVersion) {
> ```

Alex and I had a bit of discussion about this.  We can probably try to save the reference to the original Angular loaded on the page here and restore it after the callback in `loadScript('core.js' ...` .  This would essentially do something like `.noConflict()` for angular while still allowing all our `angular-*` libraries to load via `core.js`.  Should be fairly easy to test and if it works we aren't destroying the global scope or resorting to iframes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/bootstrap.js, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844#-KiV3QW8zoJDigntEzGi:-KiVEyuFYSuYMRe99nk6:boihdt0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaa1db4ab2ab3207d308ba1015e74ae0c616af15/src/app/bootstrap.js#L98)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Alex and I had a bit of discussion about this.  We can probably try to save the reference to the original Angular loaded on the page here and restore it after the callback in `loadScript('core.js' ...` .  This would essentially do something like `.noConflict()` for angular while still allowing all our `angular-*` libraries to load via `core.js`.  Should be fairly easy to test and if it works we aren't destroying the global scope or resorting to iframes.
</blockquote></details>

See here for an example: http://www.mattburkedev.com/multiple-angular-versions-on-the-same-page/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/bootstrap.js, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844#-KiV3QW8zoJDigntEzGi:-Kj3AQkoIM-U3zRXsFJ6:b-reqods) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaa1db4ab2ab3207d308ba1015e74ae0c616af15/src/app/bootstrap.js#L98)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

See here for an example: http://www.mattburkedev.com/multiple-angular-versions-on-the-same-page/
</blockquote></details>

Angular will not load if `window.angular` already contains a version of angular. This can be bypassed by setting `window.angular` to an empty object or null. 

Restoring the original angular version on `loadScript(`${repo}/core.js`, () => {` will cause errors for anything which is not executed immediately (as angular will then refer to the original angular version rather than the viewers version). This could be corrected by not referencing `angular` in our app but something like `RV.angular` which contains our verstion. This would affect every file however.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/bootstrap.js, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844#-KiV3QW8zoJDigntEzGi:-Kj3BziXdG9UkUmC8hyK:bi6v241) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaa1db4ab2ab3207d308ba1015e74ae0c616af15/src/app/bootstrap.js#L98)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Angular will not load if `window.angular` already contains a version of angular. This can be bypassed by setting `window.angular` to an empty object or null. 

Restoring the original angular version on `loadScript(`${repo}/core.js`, () => {` will cause errors for anything which is not executed immediately (as angular will then refer to the original angular version rather than the viewers version). This could be corrected by not referencing `angular` in our app but something like `RV.angular` which contains our verstion. This would affect every file however.
</blockquote></details>

Sounds like iframes...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/bootstrap.js, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844#-KiV3QW8zoJDigntEzGi:-Kj3BzUfjRGZdm4JPLMN:b-l9h4gh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaa1db4ab2ab3207d308ba1015e74ae0c616af15/src/app/bootstrap.js#L98)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Sounds like iframes...
</blockquote></details>

Yeah, that would be needed, but that's also why we have IIFEs everywhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/bootstrap.js, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844#-KiV3QW8zoJDigntEzGi:-Kj3I7nsq5udUy1ZI82G:bdjzsr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaa1db4ab2ab3207d308ba1015e74ae0c616af15/src/app/bootstrap.js#L98)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Yeah, that would be needed, but that's also why we have IIFEs everywhere
</blockquote></details>

Tests within `shell.directive.js` confirm the angular version is the pages version, not our own. Maybe we'll have to leave this for now and hope webpack saves the day :pray: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1844)*

**Comment by milesap** [comment]
Not ready for release, webpack should be able to handle this well.

**Pull request closed without merging**
