### PR TITLE
chore(build): add schema validation

### LINKED ISSUE #2172: Add schema validation
Was dropped during webpack integration

### PR DESCRIPTION
**Pull request by milesap**
## Description
Run the command `npm run test` for schema validation. Our configs don't pass, but once they are corrected this should also be executed by travis-ci. 

Closes #2172

## Testing
Works for me

## Documentation
None

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2175)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by AleksueiR** [comment]
Let's bring back z-schema back. This validator doesn't seem as complete. Also, this should be part of the standard build tests, not some random command no one will ever run.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-:-Kp0Wp8qcRFfzl8AyX9h:blkugpw)*

**Comment by barryytm** [comment]
Since I don't know how good https://www.npmjs.com/package/jsonschema is, so I would just assume it is good enough.  However I do agree that it should be included into the actual build because that is kind of the whole point of having a schema validation for it for whoever is making the config files to make the minimum mistakes.

**Comment by milesap** [comment]
Ok I'll check out z-schema. I don't follow that `npm run test` is a random command, and I think the intention is for it to process all tests including unit, protractor, eslint, and schema. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-:-KpFBgco7kDzZVcM0-sh:b-rr9f8y)*

**Comment by AleksueiR** [comment]
Yes, but no one runs it :) Additionally, schema validation should run on `run npm serve` initially and every time the config files chagne.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-:-KpFEDQIhojoPeyX-qmr:b-43xbzu)*

**Comment by milesap** [comment]
schema validation runs on build (prod/dev) and serve (incl. HMR)

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-:-KpFtS7nCGq1N0WbgdyI:b-56hh62)*

**Comment by james-rae** [comment]
Reviewed 1 of 4 files at r1, 12 of 13 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r1, 12 of 13 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[schema.json, line 347 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-KpFzoeQkmr56cLg2mMa:-KpFzoeQkmr56cLg2mMb:b26ehgs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82f1228789e28d92af9ec14bcb5a39715f6ad0a7/schema.json#L347)):*
> ```JSON
>                     "type": "object",
>                     "properties": {
>                         "name": { "type": "string", "default":"" },
> ```

`InfoSection` doesn't have `name` property.

---

*[schema.json, line 362 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-KpFzV0WouIZ-6mec9Tb:-KpFzV0WouIZ-6mec9Tc:bo0jlv7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82f1228789e28d92af9ec14bcb5a39715f6ad0a7/schema.json#L362)):*
> ```JSON
>                 "type": { "type": "string", "enum": [ "autopopulate" ] },
>                 "layerId": { "type": "array", "items": { "type": "string" }, "default": [] },
>                 "reorderable": {"type": "boolean", "default": true}
> ```

"reorderable" is specified under `un.legend` section and I don't think `layerId` belongs here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[schema.json, line 363 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-KpG0wnW2f3GIu1kBl-W:-KpG0wnW2f3GIu1kBl-X:b-sp3dm4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82f1228789e28d92af9ec14bcb5a39715f6ad0a7/schema.json#L363)):*
> ```JSON
>                 "layerId": { "type": "array", "items": { "type": "string" }, "default": [] },
>                 "reorderable": {"type": "boolean", "default": true}
>             },
> ```

Should `allowImport` be added here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[schema.json, line 363 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-KpG0wnW2f3GIu1kBl-W:-KpG2sFYL6DsLUhEMttj:bh5dqli) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82f1228789e28d92af9ec14bcb5a39715f6ad0a7/schema.json#L363)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Should `allowImport` be added here too?
</blockquote></details>

`allowImport` is already added alongside `reorderable`. See the bottom of this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by milesap** [comment]
Review status: 10 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[schema.json, line 347 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-KpFzoeQkmr56cLg2mMa:-KpGP6U7DB1QxnZy7RFr:ba3dfob) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82f1228789e28d92af9ec14bcb5a39715f6ad0a7/schema.json#L347)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`InfoSection` doesn't have `name` property.
</blockquote></details>

Removed

---

*[schema.json, line 362 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-KpFzV0WouIZ-6mec9Tb:-KpGU4Id67qIa5qi2yMs:b-hfpv0l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/82f1228789e28d92af9ec14bcb5a39715f6ad0a7/schema.json#L362)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

"reorderable" is specified under `un.legend` section and I don't think `layerId` belongs here.
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by james-rae** [comment]
Reviewed 1 of 4 files at r1, 1 of 13 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by barryytm** [comment]
Reviewed 1 of 4 files at r1, 10 of 13 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175)*

**Comment by AleksueiR** [comment]
I guess the demo works correctly... :lgtm: 

---

Reviewed 1 of 4 files at r1, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2175#-:-KpGXAZk_L0GarrGu3j6:b-2xdn8u)*

**Pull request merged**
