### PR TITLE
feat(ui): enable (some) nav buttons

### PR DESCRIPTION
**Pull request by AleksueiR**
Connected `zoomIn/zoomOut` buttons.
Test included.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/211)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211#-K7wLP1FwKio6T_i88E9:-K7wLP1FwKio6T_i88EA:-1614252593) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3cc326dda0b1c3fb41bbba36a46779cd959fff3e/src/app/geo/geo.service.js#L143)):*
With ES5 parseInt defaults to base 10 for all integer values so it's safe to start dropping the radix.  (base 16 is still detected with a 0x prefix but it's not a number otherwise)  https://es5.github.io/#x15.1.2.2
Browser support is there for the versions we care about.

As a follow up, do we really want to allow string input for this?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/geo.service.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211#-K7wLP1FwKio6T_i88E9:-K7wNQy-GSQVwRYuglJY:1347097552) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3cc326dda0b1c3fb41bbba36a46779cd959fff3e/src/app/geo/geo.service.js#L143)):*
Could use a boolean flag to indicate a relative shift in the zoom level instead of a string: `setZoom(zoomByValue, true)`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211#-K7wLP1FwKio6T_i88E9:-K7wOP-XfByMSbnPi_hP:-1242502963) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3cc326dda0b1c3fb41bbba36a46779cd959fff3e/src/app/geo/geo.service.js#L143)):*
What do you think about splitting: `setZoom` and `shiftZoom` (or something similar).  I almost always read `setZoom` as an absolute setting.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211#-K7wLP1FwKio6T_i88E9:-K7wPdvTdGMb8D4ieads:1087898080) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3cc326dda0b1c3fb41bbba36a46779cd959fff3e/src/app/geo/geo.service.js#L143)):*
I'm okay with either way; this one just seemed simpler. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Comment by james-rae** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Comment by AleksueiR** [comment]
Review status: 19 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211#-K7wLP1FwKio6T_i88E9:-K808yIR7SuNOhVpAp0b:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3cc326dda0b1c3fb41bbba36a46779cd959fff3e/src/app/geo/geo.service.js#L143)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/211)*

**Pull request merged**
