### PR TITLE
fix(ui): full screen in IE behaves as expected

### LINKED ISSUE #2014: Legend incorrect width in IE full screen mode
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

Enabling full screen mode causes the legend to become the entire width of the screen in IE.
Also effects the placement of the `Toggle Groups` and `Toggle Visibility` menus on click.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Updated resize watch on the root element - added a slight delay. IE reports nodes as being 0 width when full screening an element for some reason, that was causing the switch to the small layout.

- piggy-backing a fix for #2055

Closes #2014, #2055

## Testing
Eyeballs

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~[ ] release notes have been updated~ unreleased bug
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2046)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
Panel working as expected, however another problem in full screen mode (in IE) regarding menu locations.

capture

Should that be opened as a separate issue?

**Comment by AleksueiR** [comment]
Yeap, sounds like a separate issue.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2046#-:-KndgQ0MrOCHN7h36gcq:b-ng9iem)*

**Comment by JahidAhmed** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2046)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2046)*

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2046)*

**Pull request merged**
