### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by alyec**
Splitting #606 into parts for easier rebasing

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/684)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.jshintrc, line 25 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684#-KJ16jkjILKytFjrWRH_:-KJ16jkjILKytFjrWRHa:2018101605) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0fc04911b9ec7b606a9f0f7142de97bfb1cb0bfb/.jshintrc#L25)):*
> ```JSON
>     "maxstatements": 40,
>     "maxcomplexity": 8,
>     "trailing": true,
> ```

Does this allow trailing spaces?

---

*[src/app/geo/geo.constant.service.js, line 37 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684#-KJ18XxXRyBmSF7HeNKK:-KJ18XxXRyBmSF7HeNKL:1929140063) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0fc04911b9ec7b606a9f0f7142de97bfb1cb0bfb/src/app/geo/geo.constant.service.js#L37)):*
> ```JavaScript
>         }
>     };
>     GEO.Layer.NO_ATTRS = [GEO.Layer.Types.ESRI_IMAGE, GEO.Layer.Types.ESRI_TILE, GEO.Layer.Types.OGC_WMS];
> ```

How about extending? I think it looks a bit cleaner:
```js
angular.extend(GEO.Layer, {
   NO_ATTRS: [GEO.Layer.Types.ESRI_IMAGE, GEO.Layer.Types.ESRI_TILE, GEO.Layer.Types.OGC_WMS],
   QUERYABLE: [GEO.Layer.Types.ESRI_FEATURE, GEO.Layer.Types.ESRI_DYNAMIC, GEO.Layer.Types.OGC_WMS],
   SORT_GROUPS: [
        [GEO.Layer.Types.ESRI_FEATURE],
        [GEO.Layer.Types.ESRI_IMAGE, GEO.Layer.Types.ESRI_TILE, GEO.Layer.Types.ESRI_DYNAMIC, GEO.Layer.Types.OGC_WMS]
    ]
});

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.jshintrc, line 25 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684#-KJ16jkjILKytFjrWRH_:-KJ1At6CY_FVxqbLfIKu:-235023771) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0fc04911b9ec7b606a9f0f7142de97bfb1cb0bfb/.jshintrc#L25)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Does this allow trailing spaces?
</details>
No, but it's gone from jshint so it's worthless.  I'll remove it.
https://github.com/jshint/jshint/commit/0c0e19319b276b019d285bdfd2cfc49126abd814

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Comment by spencerwahl** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Comment by james-rae** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Comment by alyec** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.constant.service.js, line 37 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684#-KJ18XxXRyBmSF7HeNKK:-KJ1GrOFk8I36-3JEm1b:433263862) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0fc04911b9ec7b606a9f0f7142de97bfb1cb0bfb/src/app/geo/geo.constant.service.js#L37)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> How about extending? I think it looks a bit cleaner:
> ```js
> angular.extend(GEO.Layer, {
>    NO_ATTRS: [GEO.Layer.Types.ESRI_IMAGE, GEO.Layer.Types.ESRI_TILE, GEO.Layer.Types.OGC_WMS],
>    QUERYABLE: [GEO.Layer.Types.ESRI_FEATURE, GEO.Layer.Types.ESRI_DYNAMIC, GEO.Layer.Types.OGC_WMS],
>    SORT_GROUPS: [
>         [GEO.Layer.Types.ESRI_FEATURE],
>         [GEO.Layer.Types.ESRI_IMAGE, GEO.Layer.Types.ESRI_TILE, GEO.Layer.Types.ESRI_DYNAMIC, GEO.Layer.Types.OGC_WMS]
>     ]
> });
> 
> ```
</details>
Done, thanks for copy pasteable code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Comment by AleksueiR** [comment]
:lgtm:

<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> #### Refactoring
> 
> Splitting #606 into parts for easier rebasing
> 
> 
> 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.constant.service.js, line 37 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684#-KJ18XxXRyBmSF7HeNKK:-KJ1HGKD4e1IFpMCjUnL:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0fc04911b9ec7b606a9f0f7142de97bfb1cb0bfb/src/app/geo/geo.constant.service.js#L37)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Done, thanks for copy pasteable code.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684#-:-KJ1HIQ6bStGwFI7ZFr6:1417088721)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/684)*

**Pull request merged**
