### PR TITLE
fix(ui): deprecate class fgpv on v2.0

### LINKED ISSUE #1672: Deprecate setting fgpv class on the app container node
Continuation of #1665

- [x] display a warning when this class is set
- [x] update css files to use `is='rv-map'` instead of `fgpv` class
- [x] remove `data-` attributes after conversion

### PR DESCRIPTION
**Pull request by milesap**
Closes #1672

## Description
deprecate class fgpv on v2.0

## Testing
:eye: 

## Documentation
yes

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1701)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/bootstrap.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71qcdpVtRf1L6-oQg:-Kd71qcdpVtRf1L6-oQh:bkcuj6o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a5f48971cf4ffdb1e4deea199fa41423cb28bfd9/src/app/bootstrap.js#L285)):*
> ```JavaScript
>         }
> 
>         // provide alternative `data-is` for validation support
> ```

`is` doesn't have to be prefixed with `data`. 

---

*[src/content/styles/main.scss, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71IHZY447GQYaznMd:-Kd71IHZY447GQYaznMe:bkh93q5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/26f4bc8a8f99a7a9cf77af0460ad0f9bd1f8869a/src/content/styles/main.scss#L10)):*
> ```SCSS
> @import "common/_all.scss";
> 
> .fgpv {
> ```

Check the other style files. I found `fgpv` in `_special.scss`, maybe there other instances.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/bootstrap.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71qcdpVtRf1L6-oQg:-Kd78DPJ9dP6EE8H5Xae:b-9dblti) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a5f48971cf4ffdb1e4deea199fa41423cb28bfd9/src/app/bootstrap.js#L285)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`is` doesn't have to be prefixed with `data`. 
</blockquote></details>

Ok, on the issue description it mentions "remove data- attributes after conversion" - could you clarify what this means?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/bootstrap.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71qcdpVtRf1L6-oQg:-Kd78pYmKGH-Yr_quwBN:bkku9dd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a5f48971cf4ffdb1e4deea199fa41423cb28bfd9/src/app/bootstrap.js#L285)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Ok, on the issue description it mentions "remove data- attributes after conversion" - could you clarify what this means?
</blockquote></details>

This would be removing attributes prefixed with `data-` to pass initial validation, like `data-rv-service-endpoint`. A couple of lines below in bootstrap, `rv-` analog attributes are added, but any existing `data-` attributes are not removed creating a mess:


So, all the `data-` attributes need to be removed from the root element. The `is` attribute doesn't need the prefix, it's defined like that: https://www.w3.org/TR/custom-elements/#attr-is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Comment by alyec** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/content/styles/main.scss, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71IHZY447GQYaznMd:-Kd7B5wUQ_TJGwdSnhFM:b9fekf7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/26f4bc8a8f99a7a9cf77af0460ad0f9bd1f8869a/src/content/styles/main.scss#L10)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Check the other style files. I found `fgpv` in `_special.scss`, maybe there other instances.
</blockquote></details>

Also, we can't remove this from styling just yet as it is deprecated, not gone.  We can remove it in v2.0.0 whenever that happens.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/content/styles/main.scss, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71IHZY447GQYaznMd:-Kd7BTBT5-xfxA5Lk-nD:b-n714vb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/26f4bc8a8f99a7a9cf77af0460ad0f9bd1f8869a/src/content/styles/main.scss#L10)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Also, we can't remove this from styling just yet as it is deprecated, not gone.  We can remove it in v2.0.0 whenever that happens.
</blockquote></details>

ha-ha, so true :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Comment by milesap** [comment]
Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/bootstrap.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71qcdpVtRf1L6-oQg:-Kd7GPgUUIRAUZPBII_X:b-9ty3qm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a5f48971cf4ffdb1e4deea199fa41423cb28bfd9/src/app/bootstrap.js#L285)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This would be removing attributes prefixed with `data-` to pass initial validation, like `data-rv-service-endpoint`. A couple of lines below in bootstrap, `rv-` analog attributes are added, but any existing `data-` attributes are not removed creating a mess:


So, all the `data-` attributes need to be removed from the root element. The `is` attribute doesn't need the prefix, it's defined like that: https://www.w3.org/TR/custom-elements/#attr-is
</blockquote></details>

Ah gotcha, made the change

---

*[src/content/styles/main.scss, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701#-Kd71IHZY447GQYaznMd:-Kd7FtEUiDlGi0KABBuT:b65lqkj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/26f4bc8a8f99a7a9cf77af0460ad0f9bd1f8869a/src/content/styles/main.scss#L10)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

ha-ha, so true :)
</blockquote></details>

Very good point :smiley: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1701)*

**Pull request merged**
