### PR TITLE
Prevent excessive basemap chevrons showing

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2321, at title

## Testing

Manually
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2338)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
The chevron should not scroll with the body; it should visible on the screen at all times (when the basemap panel is open)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338#-:-KsA0Jsrd2ZollSfvKji:bx93imd)*

**Comment by barryytm** [comment]
@JahidAhmed Did you mean the chevron should fellow the scroll?

**Comment by barryytm** [comment]
@JahidAhmed done, thanks

**Comment by JahidAhmed** [comment]
Currently, when scrolling the chevron overlaps the basemaps


Can we have it so it's always positioned on top or something similar

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338#-:-KsEVQrJFbQOozELnf-3:b-yszyq2)*

**Comment by JahidAhmed** [comment]
Demo works. :lgtm: 

Might need some small adjustments to the positioning of the header text (`Basemap`) both vertically and horizontally to center it and line it up with the position of the chevron but that's me eyeballing it. Not sure.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338#-:-KsFA-MLpIdlbr36yAtS:bfgzvn9)*

**Comment by JahidAhmed** [comment]
Reviewed 2 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338)*

**Comment by james-rae** [comment]
Reviewed 2 of 5 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338#-:-KsJlEMDj1VBYygwanD_:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/content/styles/modules/_basemap.scss, line 11 at r7](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338#-KsJlSc2mAbM92z39jAS:-KsJlSc2mAbM92z39jAT:b7t4a5r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/55aff2d379d8a5c4749a464d829bc69c806c9804/src/content/styles/modules/_basemap.scss#L11)):*
> ```SCSS
>             display: flex;
>             align-items: center;
>             border-bottom: 1px solid #CFD8DC;
> ```

Can you change the color to `$primary-color-light` variable please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338)*

**Comment by barryytm** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_basemap.scss, line 11 at r7](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338#-KsJlSc2mAbM92z39jAS:-KsJnXldmAhHR5aedzFa:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/55aff2d379d8a5c4749a464d829bc69c806c9804/src/content/styles/modules/_basemap.scss#L11)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you change the color to `$primary-color-light` variable please?
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338#-:-KsJm0TU_8BbMhvB1YgM:bnfp4nl)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2338)*

**Pull request merged**
