### PR TITLE
fix(bug): not able to zoom to in deteails panel for service added layer

### LINKED ISSUE #1379: User added ESRI Ozone layer - Zoom To Feature not working on Point Info panel & expanded Info window
Tested build URL: http://fgpv.cloudapp.net/demo/users/milesap/build-1.4.0-6/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
User added scale dependency layer URL: 
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

To reproduce, when adding this layer, in step 3 select only Ozone layer.
image

image

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Issues fgpv-vpgf/fgpv-vpgf#1379

## Testing

Test it with service added layer, csv added layer and config file layer

## Documentation

none

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

Closes #1379

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1400)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1400)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1400)*

**Comment by AleksueiR** [comment]
Cannot check the demo due to firewall issues, but the fix is sound. :+1: 
Please, update the release notes, the current draft is here: https://github.com/fgpv-vpgf/fgpv-vpgf/releases/tag/untagged-535b2a58896906003704

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1400#-:-KXHctYtOYdLNOb1BJbV:b-oh4ihr)*

**Comment by jolevesq** [comment]
:thumbsup: Can you add the link inside the PR template?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1400#-:-KXHnl2INdxukyABeWQI:bc5t0bo)*

**Comment by AleksueiR** [comment]
Demo works. :lgtm: 

Can't add the link to the template since the link to the release notes changes with every edit until it's published.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1400#-:-KXLJJLnfrEmrV23uMbz:b-ckhqbb)*

**Pull request merged**
