### PR TITLE
Clean debug statements in production code

### LINKED ISSUE #2629: Debug statements in production code
Please remove debug statements (e.g. console.log) from production builds. Consider using the webpack-strip module. The console output is verbose.

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #2629 

Console output was verbose for production builds. 
Clean the production build so that the console only outputs errors and warnings. 

## Testing

Tested manually. 

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~Help files and documentation have been updated~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)

### CODE REVIEW

**Comment by AleksueiR** [comment]
If we are remove logger completely, [this](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/bootstrap.js#L270) should also be removed, I think.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720#-:-LD78-H28EF8wpubm5Oh:b-8bp1mr)*

**Comment by AleksueiR** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)*

**Comment by barryytm** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720#-:-LD7Eko41az9srTxt9X7:bnfp4nl)*

**Comment by milesap** [comment]
Reviewed 21 of 23 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[webpack.prod.js, line 40 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720#-LD7I4UmDrLbSWMWtoIq:-LD7I4UmDrLbSWMWtoIr:b-kix4w8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6ea98731fb8644c92ad89f06f5fada452922a7a0/webpack.prod.js#L40)):*
> ```JavaScript
>                 onBuildEnd: ['rm -rf build/help']
>             }),
>             new UglifyJsPlugin({
> ```

Please see https://stackoverflow.com/questions/49053215/webpack-4-how-to-configure-minimize for info on changing how this plugin is loaded. The `rv-main.js` source map is not being generated on production builds, see https://github.com/webpack/webpack/issues/6614 for setting the flag (default is false).

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)*

**Comment by dane-thomas** [comment]
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[webpack.prod.js, line 40 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720#-LD7I4UmDrLbSWMWtoIq:-LD7LgGM3ma1SLykoblY:bu8ox7e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6ea98731fb8644c92ad89f06f5fada452922a7a0/webpack.prod.js#L40)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Please see https://stackoverflow.com/questions/49053215/webpack-4-how-to-configure-minimize for info on changing how this plugin is loaded. The `rv-main.js` source map is not being generated on production builds, see https://github.com/webpack/webpack/issues/6614 for setting the flag (default is false).
</blockquote></details>

Changed thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)*

**Comment by milesap** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720#-:-LD7rY9d7jefql2lSkBW:bnfp4nl)*

**Comment by barryytm** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)*

**Pull request merged**
