### PR TITLE
feat(bootstrap): load dependencies via host page url scheme

### LINKED ISSUE #1824: Load dependencies over host page URL's scheme
Request from user:
> ... It would also be awesome if you guys could update the jquery cdn you are using in your source code to use https instead of http. The live site will use https so if this is not changed the map will break. We also found the same issue in the core.js with this link https://js.arcgis.com/3.14/

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1824

## Testing
WOMM - couldn't test https

## Documentation
no

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1827)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Does this needs an update to geoApi as well? esriApi is loaded there after all. And dojo url in `global-registry` needs to be updated.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1827#-:-Kg_FiWYdGDBdLfwWs9E:b-4nxwmh)*

**Comment by alyec** [comment]
geoApi only uses the URL provided (IIRC), so once `global-registry` is updated it should be loading from that URL

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1827#-:-Kg_NrGjprcptOT2qJq6:bt6fbnx)*

**Comment by milesap** [comment]
Updated `global-registry.js`

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1827#-:-Kg_UYnEDpVT76JNbh1a:b-s3kubq)*

**Comment by alyec** [comment]
Should this be targetting `develop`?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1827#-:-Kg_WHmJV3pDOU--tQJy:b-phnwqu)*

**Comment by milesap** [comment]
Now targets develop

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1827#-:-Kg_e1xQ21Eat0jcO2Jg:br4e9bk)*

**Pull request closed without merging**
