### PR TITLE
feat(datagrid): add ui for datagrid filters for large layout

### LINKED ISSUE #1417: UI datagrid filters for large layout
When #1416 is done.

- [x] Large Layout (Desktop)
     - [x] Add Filters Row (set filters from Datagrid for string, number, date)
     - [ ] Add filters for thematic map  (from filters setting, selection list)

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Create filters for large view viewer (Filters are on the table and they are removed for small display). Tu use with catalog layers, filter of type string, number range and date range have been added. For selection filter it should be added when we will have thematic map.

## Testing

Tested it in Chrome, Firefox and Safari

## Documentation

None

## Checklist

Added a layer "Date layer field" where all type of filter can be test. In the console, when value change, the value and the name of the field on trigger the change should be logged.

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Closes #1417

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1477)

### CODE REVIEW

**Comment by alyec** [comment]
This PR is against master, it should probably target 1.5 or 1.6 .

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-number-only.directire.js, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1477#-KYL3AejBMw7B1w3ZKTT:-KYL3Aej9yVDJJ3gEpdw:bb0wemp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9298f419e5bbb7e474a08a5a7e379c0951ef6adb/src/app/ui/filters/filters-number-only.directire.js#L1)):*
> ```JavaScript
> (() => {
> ```

The filename has a typo `directire` to `directive`

---

*[src/app/ui/filters/filters.service.js, line 104 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1477#-KYL2ug5BmROzklorLJS:-KYL2ug5BYFBcv1SNF6x:b-haz5ao) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9298f419e5bbb7e474a08a5a7e379c0951ef6adb/src/app/ui/filters/filters.service.js#L104)):*
> ```JavaScript
>          *
>          * @function preventSorting
>          */
> ```

missing doc for the event argument

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1477#-:-KYL9M5P20AOW9GxMTSx:b-53shru)*

**Comment by jolevesq** [comment]
Do you want to submit a new pull request to target 1.6?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1477#-:-KYOOTVg86oSmIonjwa0:b-s7qasl)*

**Comment by jolevesq** [comment]
Maybe just gave me comments and I will merge this with #1416 because they will reuse some directives for filters creation.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1477#-:-KYPUMmt0uWEZsPatpVB:b-i8llvc)*

**Comment by mweech** [comment]
Outdated.  Merged into new PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1527

**Pull request closed without merging**
