### PR TITLE
Add legend samples

### PR DESCRIPTION
**Pull request by barryytm**
## Description

#1786, Add a new index page as well as new config files for samples.  However the sample for hover tips regarding to hover tips still needs to be added.
## Testing

Manually and visually.
## Documentation

New json config files for new samples and a new index page called `index-samples.tpl`
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2003)

### CODE REVIEW

**Comment by barryytm** [comment]
Index-samples.html is the page for samples, the link was added to above.

**Comment by AleksueiR** [comment]
:lgtm: 

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/bootstrap.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9btLdUFlS7Xwae7dk:-Kn9btLdUFlS7Xwae7dl:b-ypz1e3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dd5eb847921cfaf41a41218958d70298af2351cd/src/app/bootstrap.js#L206)):*
> ```JavaScript
>     },
> 
>     reInitialize() {
> ```

Please add some jsdoc comments to new functions.nnn

---

*[src/content/samples/index-samples.tpl, line 9 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9dOl0Ln_qzWKIdJcO:-Kn9dOl0Ln_qzWKIdJcP:b-5c5w0h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dd5eb847921cfaf41a41218958d70298af2351cd/src/content/samples/index-samples.tpl#L9)):*
> ```Smarty
>     <title>title</title>
> 
>     <style>
> ```

Let's make this look a little nicer:
```css
body {
    display: flex;
    flex-direction: column;
}

#selectConfig {
    margin: 10px;
}

.myMap {
    height: 100%;
    margin: 10px;
}

```

---

*[src/content/samples/index-samples.tpl, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9cH6vlEXWxLxzD-p6:-Kn9cH6vlEXWxLxzD-p7:b-wmbwvs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dd5eb847921cfaf41a41218958d70298af2351cd/src/content/samples/index-samples.tpl#L17)):*
> ```Smarty
>     
>     <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
>     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.11/angular.min.js"></script>
> ```

You can remove these two scripts - they are just for testing of angular sandboxing. Having them on `index-mobile` is enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-:-Kn9dzH6q8VCAw4NZoSS:bg7igkv)*

**Comment by barryytm** [comment]
Review status: 20 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/bootstrap.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9btLdUFlS7Xwae7dk:-Kn9v5xwz3uO9cMzl55R:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/11ad2b53e702d294969f6f66dcebf4839e66202c/src/app/bootstrap.js#L206)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please add some jsdoc comments to new functions.nnn
</blockquote></details>

done thanks

---

*[src/content/samples/index-samples.tpl, line 9 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9dOl0Ln_qzWKIdJcO:-Kn9v90mHgJR_DhNvtb0:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/11ad2b53e702d294969f6f66dcebf4839e66202c/src/content/samples/index-samples.tpl#L9)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Let's make this look a little nicer:
```css
body {
    display: flex;
    flex-direction: column;
}

#selectConfig {
    margin: 10px;
}

.myMap {
    height: 100%;
    margin: 10px;
}

```
</blockquote></details>

done thanks

---

*[src/content/samples/index-samples.tpl, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9cH6vlEXWxLxzD-p6:-Kn9v9y89V91crLqV45c:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/11ad2b53e702d294969f6f66dcebf4839e66202c/src/content/samples/index-samples.tpl#L17)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can remove these two scripts - they are just for testing of angular sandboxing. Having them on `index-mobile` is enough.
</blockquote></details>

done thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by AleksueiR** [comment]
Review status: 20 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/bootstrap.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9btLdUFlS7Xwae7dk:-Kn9w8h4glwHDIOsbsOi:b-gz2299) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/11ad2b53e702d294969f6f66dcebf4839e66202c/src/app/bootstrap.js#L206)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

done thanks
</blockquote></details>

I was thinking about all the new function in this PR :) :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by james-rae** [comment]
I think each sample should have at least 4 basemaps -- 2 in each projection.  Testers will want to test the switching between projection and non-projection.  
Alternatley, provide a sample with lots of basemaps (but this means we may avoid catching basemap issues on all the other samples)

---

Reviewed 21 of 22 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-:-Kn9x44gKt6l33FUNz4L:bw8wmqa)*

**Comment by AleksueiR** [comment]
Agree about basemaps. Please add those as well.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-:-KnA0nVpaRSVqOnroQfU:bxawulw)*

**Comment by barryytm** [comment]
Review status: 20 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/bootstrap.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003#-Kn9btLdUFlS7Xwae7dk:-KnA1UpwxfCn9_ODEzTk:bdve36h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/11ad2b53e702d294969f6f66dcebf4839e66202c/src/app/bootstrap.js#L206)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I was thinking about all the new function in this PR :) :)
</blockquote></details>

Ok, I have just added them.  Thanks :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by barryytm** [comment]
Ok, I will include more base maps.

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 16 of 16 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r4, 16 of 16 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by james-rae** [comment]
Reviewed 33 of 33 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Comment by AleksueiR** [comment]
Reviewed 33 of 33 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2003)*

**Pull request merged**
