### PR TITLE
Error toast for custom projections

### PR DESCRIPTION
**Pull request by cynngah**
#616

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/740)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/740)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/740)*

**Comment by AleksueiR** [comment]
I apologize for not being on top of this, but showing an error toast in this situation is not the right approach. Imagine, user clicks on one item, gets an error, clicks another, gets an error, clicks a third one, gets another error. At this point user doesn't know if it applies to all the points or just some of them.

A better approach would be to detect if graphics can be reprojected at all when the table is first created by trying that on the first item, for example. If reprojection is not possible, disable all zoom controls and update their tooltips to say something like "Data in custom projection. Cannot zoom to feature".

<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> #### Error toast for custom projections
> 
> #616
> 
> 
> 
</details>


---

Reviewed 1 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/740#-:-KJpV3rDPqI_KXzFhcO0:-525504808)*

**Comment by cynngah** [comment]
gonna close this and work off a fresh branch then

**Pull request closed without merging**
