### PR TITLE
feat(export): Add north arrow, scale bar, foot note and border to exported map

### LINKED ISSUE #1294: Add "North Arrow" and "Scalebar" to the exported map image
Decorate the map with:

- [x] North Arrow - statically located arrow (check for arrow placement convention)
- [x] Scalebar (need to scale the scalebar if the map export image differs in size from the viewer size)
- [x] Citation (lower-right corner): allow for a footnote to indicate source of generated map (inclusion of text specified in config or no citation if missing); citation specified in the config
- [x] The user should be able to turn off inclusion of scalebar and north arrow
- [x] add a border around map image when legend is included

See this for reference:

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

#1294

## Testing

Haven't added test because I don't know how yet

## Documentation

None

## Checklist

- [x] commits messages follow the guidelines
- [ ] code passes unit tests  -- can't start phantomJS when run local
- [ ] release notes have been updated -- need more information
- [x] PR targets the correct release version

Closes #1294

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1341)

### CODE REVIEW

**Comment by alyec** [comment]
Couldn't test the border and the connection kept timing out, but did check north arrow and scale.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/geo/map.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-4BrnUTizQCaMYba:-KW8-4BsmlQmy12RwtpS:b-y9rudh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L61)):*
> ```JavaScript
>                 geolocate,
>                 getFullExtent,
>                 getNorthArrowAngle,
> ```

Both of the new functions look fine to me, but I think they can both be moved into geoApi and since they are for the most part stateless math I think it makes sense to move them there.

---

*[src/app/geo/map.service.js, line 546 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-Ir0G6LGbap2NlD2:-KW8-Ir0G6LGbap2NlD3:bmcj0uk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L546)):*
> ```JavaScript
>             * http://www.movable-type.co.uk/scripts/latlong.html
>             * @function getNorthArrowAngle
>             * @returns {number} rotation angle to apply
> ```

I believe this is in degrees, if so can you add that to the return type.

---

*[src/app/ui/export/export.html, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW81JNTJq2-btwnVU3L:-KW81JNTJq2-btwnVU3M:b4ve5dt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.html#L55)):*
> ```HTML
>                 {{ 'export.includelegend' | translate }}
>             </md-switch>
>             <md-switch translate-attr-aria-label="export.includescale" class="md-primary rv-switch"
> ```

I think in the meeting we decided that only one switch would be used for the arrow, scale and footnote.  I'm okay with this too except that the footnote is working off isArrowIncluded and I think it should probably be `isArrowIncluded || isScaleIncluded`

---

*[src/app/ui/export/export.service.js, line 120 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW82_4IMRJ-a8eaMAOQ:-KW82_4JOmgMkjWj5T2k:bi9pb5g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.service.js#L120)):*
> ```JavaScript
> 
>                 // set north arrow
>                 self.arrowRotation = `rotate(${geoService.getNorthArrowAngle()}deg)`;
> ```

Extra points for clever use of inline CSS.  :trophy: 

---

*[src/app/ui/export/export.service.js, line 260 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW81ttCy_z7UdnewfCY:-KW81ttDAq5mtqsC_spS:b-4lv6gd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.service.js#L260)):*
> ```JavaScript
>                 // add approx to warn user about using scale bar as a ruler (scalebar is always approximative)
>                 return {
>                     label:  `${parseFloat(bar.toFixed(1)).toString()}${unit} approx.`,
> ```

Does `approx` need translation (even if not for French if we decide to add other languages I think it eventually will)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KW83KP4YpyzXGyJxZeC:b-bz4t4d)*

**Comment by jolevesq** [comment]
why are you not able to test the border? It shows up when you add legend, scale or arrow. By the way, glitch links are not working. I don't have dev or prod folder in my samples

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/geo/map.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-4BrnUTizQCaMYba:-KW8ZJFpomzr6AxEsuXj:b1rxva4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L61)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Both of the new functions look fine to me, but I think they can both be moved into geoApi and since they are for the most part stateless math I think it makes sense to move them there.
</details>
Do you want me to add those functions in geoAPI now or as a refactoring later?

---

*[src/app/ui/export/export.html, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW81JNTJq2-btwnVU3L:-KW8YucSx-Ffqsuml1AK:b-nhslj3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.html#L55)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think in the meeting we decided that only one switch would be used for the arrow, scale and footnote.  I'm okay with this too except that the footnote is working off isArrowIncluded and I think it should probably be `isArrowIncluded || isScaleIncluded`
</details>
Didn't remember the one switch for every thing.  I have one switch for scale, one for arrow and footnote is always present. Don't care to put only one switch for everything.

---

*[src/app/ui/export/export.service.js, line 260 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW81ttCy_z7UdnewfCY:-KW8Yhjo2YyCGri3fmA5:b-1cdphi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.service.js#L260)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Does `approx` need translation (even if not for French if we decide to add other languages I think it eventually will)?
</details>
Same in French and English but yes it will be better to put it in the translation file. I will do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KW8YJhiAUhqHuOr2wov:blwk8w2)*

**Comment by alyec** [comment]
Ok, then it didn't work for me (on FF).  Use the links from comment above it (I believe the last comment was created by a second version of glitch that Alex was running as a test).  But now that the new build script is updated if you rebase I think you will get the new style of build as well.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/geo/map.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-4BrnUTizQCaMYba:-KW8_QViZj9w__TygJMH:b1hxfdx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Do you want me to add those functions in geoAPI now or as a refactoring later?
</details>
Now would be best, unless you run into problems in which case create a task (I think it could go with the big layer/legend refactor).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KW8_4_IG2pCS7pJJTjX:b-h7bdlu)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/geo/map.service.js, line 582 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8wbAXmusroBNP3QKX:-KW8wbAXmusroBNP3QKY:bq5dums) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L582)):*
> ```JavaScript
>             *                               - unit: array of unit [metric, imperial]
>             */
>             function getScaleRatio(mapWidth = 0) {
> ```

I might be wrong, but can't we just take the scalebar already rendered by esri on the map itself? We can detect its size and scale it up or down if the ratio of the exported map image is different from the actual map size (the ratio should be 1 right now as we don't allow for custom sizes yet). This way we don't need to make any calculations ourselves.

---

*[src/app/ui/export/export.html, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW81JNTJq2-btwnVU3L:-KW8xLLwM5Km_k8go2q3:by7hik6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.html#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Didn't remember the one switch for every thing.  I have one switch for scale, one for arrow and footnote is always present. Don't care to put only one switch for everything.
</details>
Yeah, we can keep individual controls for the legend, arrow and scalebar.

---

*[src/app/ui/export/export.service.js, line 120 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW82_4IMRJ-a8eaMAOQ:-KW8xdUgB2NAlioA8sey:b-1v4ea9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.service.js#L120)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Extra points for clever use of inline CSS.  :trophy: 
</details>
The current demo does not export the arrow and scalebar with the image, it just adds them to the export dialog. 

I think both the arrow and scalebar need to draw in SVG since they had to be rendered on a canvas for exporting (they can be drawn on canvas directly, but that's harder), instead of using html elements. 

The arrow can be easily rotated as an svg object - no need to crafty inline CSS :)

There are some nice svg arrows: https://fgpdoc.zz9.ca/index.php/s/FfHtYcLQdPQqvv0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341)*

**Comment by jolevesq** [comment]
Don't check this version, I just push from work to use it from home.

---

Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/geo/map.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-4BrnUTizQCaMYba:-KWDEdcwN52LdK1Kt1Ks:baqash1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L61)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Now would be best, unless you run into problems in which case create a task (I think it could go with the big layer/legend refactor).
</details>
Push in a new PR for geoApi

---

*[src/app/geo/map.service.js, line 546 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-Ir0G6LGbap2NlD2:-KWDEhVKr_dV1ugvG0fx:baqash1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L546)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I believe this is in degrees, if so can you add that to the return type.
</details>
Push in a new PR for geoApi

---

*[src/app/geo/map.service.js, line 582 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8wbAXmusroBNP3QKX:-KW9S22NSYwaIP5Sq5jh:bw8xgy5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L582)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I might be wrong, but can't we just take the scalebar already rendered by esri on the map itself? We can detect its size and scale it up or down if the ratio of the exported map image is different from the actual map size (the ratio should be 1 right now as we don't allow for custom sizes yet). This way we don't need to make any calculations ourselves.
</details>

You are right for most cases but if a user does not have a scalebar control on the map but want one on the print map. In this case we will need to calculate it ourselves.

---

*[src/app/ui/export/export.service.js, line 120 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW82_4IMRJ-a8eaMAOQ:-KWDCR4AN5nHulI-kr0K:boue12r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.service.js#L120)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> The current demo does not export the arrow and scalebar with the image, it just adds them to the export dialog. 
> 
> I think both the arrow and scalebar need to draw in SVG since they had to be rendered on a canvas for exporting (they can be drawn on canvas directly, but that's harder), instead of using html elements. 
> 
> The arrow can be easily rotated as an svg object - no need to crafty inline CSS :)
> 
> There are some nice svg arrows: https://fgpdoc.zz9.ca/index.php/s/FfHtYcLQdPQqvv0
</details>
I will use svg for line, arrow and text

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWDBaouGnI9ie_sgyNT:b-k5bd87)*

**Comment by jolevesq** [comment]
Review status: 2 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/ui/export/export.html, line 55 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW81JNTJq2-btwnVU3L:-KWYt_hdwBIaaBK3ek8x:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.html#L55)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Yeah, we can keep individual controls for the legend, arrow and scalebar.
</details>
Done.

---

*[src/app/ui/export/export.service.js, line 120 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW82_4IMRJ-a8eaMAOQ:-KWYtdVWRqfOm0zcgIbY:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.service.js#L120)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I will use svg for line, arrow and text
</details>
Done.

---

*[src/app/geo/map.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-4BrnUTizQCaMYba:-KWYtfJX3xPfWY2-m8E6:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Push in a new PR for geoApi
</details>
Done.

---

*[src/app/geo/map.service.js, line 546 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8-Ir0G6LGbap2NlD2:-KWYtg9gKUdA6m5qi2TV:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L546)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Push in a new PR for geoApi
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341)*

**Comment by alyec** [comment]
There is a SASS issue in the build: https://travis-ci.org/fgpv-vpgf/fgpv-vpgf/builds/175773108#L2513

---

Reviewed 3 of 4 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/ui/export/export.service.js, line 238 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KWZUfTl7z4m1LZGAACr:-KWZUfTl7z4m1LZGAACs:brenec7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c071d0d8c82cd1c01d7db65a4056368015103215/src/app/ui/export/export.service.js#L238)):*
> ```JavaScript
>                     localCanvas.width = shellWidth;
>                     localCanvas.height = self.footnoteHeight;
>                     canvg(localCanvas, footnote.node.outerHTML, {
> ```

Since canvg uses an async API this can expose race conditions.  I don't think this should block the merge as I believe legend generation also has a race condition and it probably make sense to split that off into a separate issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWZW2psbSllAzhpbdr8:b-dcs3t2)*

**Comment by jolevesq** [comment]
Error was introduce by my rebase and not caught with my gulp vet. Now it is ok.

---

Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/ui/export/export.service.js, line 260 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW81ttCy_z7UdnewfCY:-KWZzB8bGGmNSLJlO5Ir:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/ui/export/export.service.js#L260)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Same in French and English but yes it will be better to put it in the translation file. I will do it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWZvpcOEE_uIZMA6uiZ:bwc4cnm)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 7 files at r1, 4 of 7 files at r3.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/map.service.js, line 582 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KW8wbAXmusroBNP3QKX:-KWcHbp5vW-hmQDZJT_z:b8gcuyr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d5a61601f96645499a9ba1f50424d239a804003/src/app/geo/map.service.js#L582)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> You are right for most cases but if a user does not have a scalebar control on the map but want one on the print map. In this case we will need to calculate it ourselves.
</details>
Fair enough. :heavy_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341)*

**Comment by AleksueiR** [comment]
main.css file seems to be missing.

---

Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWcHlFtCFWnY6cOfYfK:b-tj8qgy)*

**Comment by jolevesq** [comment]
not removed in my branch

---

Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWcsIetR5fHH0MCcXvk:bad8qq5)*

**Comment by jolevesq** [comment]
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/export/export.service.js, line 238 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-KWZUfTl7z4m1LZGAACr:-KWnOmL2qeC64fXQOI6c:b32wtd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c071d0d8c82cd1c01d7db65a4056368015103215/src/app/ui/export/export.service.js#L238)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Since canvg uses an async API this can expose race conditions.  I don't think this should block the merge as I believe legend generation also has a race condition and it probably make sense to split that off into a separate issue.
</details>
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341)*

**Comment by alyec** [comment]
:lgtm: 
There is an issue with footnote saving, but I think we should get the PR in first and deal with that as a separate bug.

---

Reviewed 3 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWnpST6bKqFMxOgkEYQ:b-48n75s)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWoSI5BoFhHhd1Z2OPn:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r2, 1 of 3 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1341#-:-KWrfVPMO6r3xn0f542W:bnfp4nl)*

**Pull request merged**
