### PR TITLE
WET themed samples

### LINKED ISSUE #1292: Create sample pages for each WET theme
## Themes
- [x] [Base theme](http://wet-boew.github.io/themes-dist/theme-base/docs/ref/theme-base/theme-base-en.html) - A theme template to aid in the creation of new themes.
- [x] [Canada.ca theme](http://wet-boew.github.io/themes-dist/GCWeb/docs/ref/GCWeb/GCWeb-en.html) - This theme implements the layout and design requirements for Canada.ca.
- [x] [Government of Canada Web Usability Theme](http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/docs/ref/theme-gcwu-fegc/theme-gcwu-fegc-en.html) - This theme implements the requirements of the [Standard on Web Usability](http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=24227) and is recommended for use on all Government of Canada websites (except for Canada.ca).
- [x] [Government of Canada Intranet theme](http://wet-boew.github.io/themes-dist/theme-gc-intranet/docs/ref/theme-gc-intranet/theme-gc-intranet-en.html) - This theme adapts the Government of Canada Web Usability theme for intranet sites.
- [x] [Open Government Platform (OGPL) theme - The Open Government Platform (OGPL) theme](http://wet-boew.github.io/themes-dist/theme-ogpl/docs/ref/theme-ogpl/theme-ogpl-en.html) was developed to support the [Open Government Platform (OGPL)](http://ogpl.github.io/index-en.html).
- [x] [Web Experience Toolkit (WET) theme](https://wet-boew.github.io/v4.0-ci/docs/ref/theme-wet-boew/theme-wet-boew-en.html) - This theme provides an example implementation of the Base Theme.

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Add 6 WET themed samples

Closes #1292 
## Testing

http://fgpv.cloudapp.net/demo/users/barryytm/1292/dev/samples/index-theme-base.html
http://fgpv.cloudapp.net/demo/users/barryytm/1292/dev/samples/index-theme-gc-intranet.html
http://fgpv.cloudapp.net/demo/users/barryytm/1292/dev/samples/index-theme-gcweb.html
http://fgpv.cloudapp.net/demo/users/barryytm/1292/dev/samples/index-theme-gcwu-fegc.html
http://fgpv.cloudapp.net/demo/users/barryytm/1292/dev/samples/index-theme-ogpl.html
http://fgpv.cloudapp.net/demo/users/barryytm/1292/dev/samples/index-theme-wet.html
## Documentation

`theme-*.tpl`
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2445)

### CODE REVIEW

**Comment by james-rae** [comment]
I'm ok merging as is. One thing to maybe consider is pointing these pages to a less chaotic / less heavy map config.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2445#-:-KxJo97j_3e25-a95OCU:b2fpjo9)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2445)*

**Comment by barryytm** [comment]
I am going to make them to point to another page

**Comment by james-rae** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2445)*

**Comment by AleksueiR** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2445)*

**Pull request merged**
