### PR TITLE
feat(ui): truncate long layer names + tooltip

### LINKED ISSUE #59: feat(ui): create a truncate directive for long layer names
needed to truncate the long layer names. The portion of the string should be removed from the middle, leaving its ending intact.

Here's some existing truncate directives to look at:
https://github.com/sparkalow/angular-truncate/blob/master/src/truncate.js
https://github.com/dibari/angular-ellipsis/blob/master/src/angular-ellipsis.js

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Adds truncation to the long layer names and also adds full tooltips to the layer records.

Closes #59, #1739

:point_up: 
one of the oldest issues still alive

## Testing
Eyeballing.

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1740)

### CODE REVIEW

**Comment by jolevesq** [comment]
On mobile, the tooltips are often half outside the screen. Tooltips doesn't appears when a layer can't load.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KeZ8OyytAoYnt6JdZxT:byskmn5)*

**Comment by AleksueiR** [comment]
Ok, I'll change tooltips to pop up above the layer on small and medium layouts and will add tooltips to the placeholders as well.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KeZkxRBq1_r585i5-N4:b-wzsmc8)*

**Comment by alyec** [comment]
:lgtm: (didn't check mobile)

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/common/truncate.directive.js, line 74 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-Kej5J02c-5jMv93ht7K:-Kej5J02c-5jMv93ht7L:bp5a7uu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6fcaa7fe6b293479454a3429ab26da2b089f0ff5/src/app/ui/common/truncate.directive.js#L74)):*
> ```JavaScript
> 
>     /**
>      * `rvTruncateTitle` truncates a given string be taking the middle part of the string out leaving the beginning and end intact.
> ```

typo: by

---

*[src/app/ui/common/truncate.directive.js, line 77 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-Kej5LR5u_73M0BeTVkS:-Kej5LR5u_73M0BeTVkT:bl267aw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6fcaa7fe6b293479454a3429ab26da2b089f0ff5/src/app/ui/common/truncate.directive.js#L77)):*
> ```JavaScript
>      *
>      * @function rvTruncateTitle
>      * @return {object} directive body
> ```

missing graphicsService param

---

*[src/app/ui/common/truncate.directive.js, line 134 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-Kej5wADUWT_7DiujImD:-Kej5wADUWT_7DiujImE:b-3nqguw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6fcaa7fe6b293479454a3429ab26da2b089f0ff5/src/app/ui/common/truncate.directive.js#L134)):*
> ```JavaScript
>              */
>             function splitString(string, widthToFit) {
>                 const stringWidth = graphicsService.getTextWidth(canvas, string, 'normal 16px Roboto');
> ```

is the font string supposed to be hardcoded?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-Kej6cYBQyTsxeVvaYLH:b3ftrs4)*

**Comment by AleksueiR** [comment]
Review status: 5 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/common/truncate.directive.js, line 74 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-Kej5J02c-5jMv93ht7K:-Ken4o2N5zjuU48IJGPU:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27d4f702317f0debade875bc65b07548b29b5e10/src/app/ui/common/truncate.directive.js#L74)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: by
</blockquote></details>

Done.

---

*[src/app/ui/common/truncate.directive.js, line 77 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-Kej5LR5u_73M0BeTVkS:-Ken540K9t-cWAh0vlB_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27d4f702317f0debade875bc65b07548b29b5e10/src/app/ui/common/truncate.directive.js#L77)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

missing graphicsService param
</blockquote></details>

Done.

---

*[src/app/ui/common/truncate.directive.js, line 134 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-Kej5wADUWT_7DiujImD:-Ken5RKXvRXShEZ4-eL0:bua7e2w) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27d4f702317f0debade875bc65b07548b29b5e10/src/app/ui/common/truncate.directive.js#L134)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

is the font string supposed to be hardcoded?
</blockquote></details>

No. I added a todo to fix it. Maybe someone in the alternative universe can pick it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740)*

**Comment by alyec** [comment]
:lgtm: tested mobile with browser resizing

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KenHOf8BLSteRuEQbIp:bowu6kl)*

**Comment by jolevesq** [comment]
If there is no datatable or layer can't load (e.g. Land Pub Standard Zone Details on index-one) there is no tooltip because item is not clickable (no button). it works for mouse, not keyboard.

On mobile, when tooltip is long, it exceed the screen and I miss the end.

Do you want to have tooltip even if the name is not truncated?

---

Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KenNLx9U0We4ZVHB95K:br23xtk)*

**Comment by AleksueiR** [comment]
Yeah, the layer items without data or failed items are not tabbable. Do we want to make the focusable? This would solve it.

I'm not sure what can be done with long tooltips on mobile. There is no default way to make them wrap around. It can be done with some extra CSS though; here's 


This should be a separate issue though. Can you make one for that?

Good point, I think I wanted to only show a toolitp when the layer name is too long and forgot to do it. Thanks!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KenRR6YxG69wSexm-PI:b-thl8cz)*

**Comment by jolevesq** [comment]
I think we should make them tabbable only if there is a tooltip (naem is truncated). If not there is no other way for keyboard user to see the complete layer name.

I will create an issue for the wrap long tooltip.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KenVfYO_HzMRgzSPfm-:bzbkknq)*

**Comment by AleksueiR** [comment]
All legend entries are not tabbable, so it's possible to get to the tolltips on errored or lacking data entries.

Hiding and showing tooltips turned out to be not as trivial as expected. Tooltip is a AM directive and since it's removed from the dom, it's not possible to disabled/enable it through the direct binding. This should probably be turned into a separate issue as well.

---

Review status: 11 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KeoXOPBg0ZOBTZzcw0z:b7cssxz)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KeoYq26YQoTOHdU_8pY:bnfp4nl)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1740#-:-KeoZnj_28b48c8dcVTd:bnfp4nl)*

**Comment by AleksueiR** [comment]
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1759

**Pull request merged**
