### PR TITLE
feat(overview): Add customization to overview component

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Add customization to overview map component. Set expandFactor, disable/enable and set the layer to use. For the expand factor and layer to use work will have to be done inside geoApi

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [] ~release notes have been updated~ no release page created
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2206)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 129 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206#-KpR9xQlm0sWTYqiyVfM:-KpR9xQlm0sWTYqiyVfN:b9u4evs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce2dddfcca9bcda4ffe420a30a7fbf5cbd1d9fde/schema.json#L129)):*
> ```JSON
>                 "extentSetId": { "type": "string", "description": "The extent set to be used for this basemap (should reference map.extentSets.id)" },
>                 "lodSetId": { "type": "string", "description": "Optional.  The level of details set to be used for this basemap (should reference map.lod.id)" },
>                 "overviewUrl": { "$ref": "#/definitions/basicLayerNode" }
> ```

So, the basemap layer will depend on the tileschema now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 129 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206#-KpR9xQlm0sWTYqiyVfM:-KpRBabMfqDyBLIloPWR:bgksqpv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce2dddfcca9bcda4ffe420a30a7fbf5cbd1d9fde/schema.json#L129)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

So, the basemap layer will depend on the tileschema now?
</blockquote></details>

Only if user wants to define a specific url for overview map (not use the active basemap). One url needs to be define by tileschema if user switch projection. If it is empty, viewer will take the active basemap. It is not a mandatory field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[schema.json, line 129 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206#-KpR9xQlm0sWTYqiyVfM:-KpUba5MEcvSXA8UVu8b:b3yhqf4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce2dddfcca9bcda4ffe420a30a7fbf5cbd1d9fde/schema.json#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Only if user wants to define a specific url for overview map (not use the active basemap). One url needs to be define by tileschema if user switch projection. If it is empty, viewer will take the active basemap. It is not a mandatory field.
</blockquote></details>

Nice! Can you add this comment to the schema as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r2, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 129 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206#-KpR9xQlm0sWTYqiyVfM:-KpVRRtaCS_enQ6cZ_5M:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce2dddfcca9bcda4ffe420a30a7fbf5cbd1d9fde/schema.json#L129)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Nice! Can you add this comment to the schema as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2206)*

**Pull request merged**
