### PR TITLE
feat(ui): disable 'Zoom To Feature' for any map points in a hidden or…

### LINKED ISSUE #712: "Zoom To Feature" for any map points in a hidden layer
Tested on http://fgpv.cloudapp.net/demo/v0.16.0/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Hillshade,Airports,Barley,FeatureServer,ZoomScale
Consider the scenario when certain layer is hidden, what should be the expected behavior when using "Zoom to Feature" for map points?
1. Hide one layer - all map point for this layer hidden
2. open data table for this layer
3. "Zoom to feature" for any point of the layer
The map still zoomed to somewhere, but because all feature point not shown, not sure if the map zoom to the right point or not. Below screenshot is an example when zooming to Obj ID 49
image

### PR DESCRIPTION
**Pull request by jolevesq**
… not visible at map scale layer

Closes #712

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1134)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 231 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQaHYkuEC7PJX3f6onP:-KQaHYkuEC7PJX3f6onQ:b88ztrl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/filters/filters-default.directive.js#L231)):*
> ```JavaScript
>                         // set the disabled argument value
>                         button.disabledArg = (button.name === 'rv-zoom-marker') ?
>                             '!self.enabled || !self.visibility.value || self.offscale.value' : '';
> ```

Maybe it's better to not disable zoom-to controls if the layer itself is out of scale? Event if the layer maybe out of scale, datatable can open, and the user might want to zoom to a specific point (which is visible at some level). Disabling zoom to controls when the layer is invisible is warranted as the point can't be viewed at any zoom level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 231 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQaHYkuEC7PJX3f6onP:-KQaKJt6VhcZAfxLonib:b8o9pdr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/filters/filters-default.directive.js#L231)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Maybe it's better to not disable zoom-to controls if the layer itself is out of scale? Event if the layer maybe out of scale, datatable can open, and the user might want to zoom to a specific point (which is visible at some level). Disabling zoom to controls when the layer is invisible is warranted as the point can't be viewed at any zoom level.
</details>
Agree, didn't about that. When user zoom to feature it will be visible is visibility is on. btw, is the zoom to feature function make sure to zoom inside min/max scale for a layer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 231 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQaHYkuEC7PJX3f6onP:-KQaMgbuU7-E1vNrf_Ss:b-a3ds04) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/filters/filters-default.directive.js#L231)):*
`zoomWithOffset` function's description says:
> ... then zooms to the maximum level such that the geometry is still visible.

It's located here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/map.service.js#L478

Can you confirm that it does what it claims to do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 231 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQaHYkuEC7PJX3f6onP:-KQal01tFZ8PFTEq3GZu:b-gia4of) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/filters/filters-default.directive.js#L231)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `zoomWithOffset` function's description says:
> > ... then zooms to the maximum level such that the geometry is still visible.
> 
> It's located here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/map.service.js#L478
> 
> Can you confirm that it does what it claims to do?
</details>
Yes it zoom to the maximum level geometry is still visible. It is a little but weird behaviour because the first time I click on zoom to feature it only zoom to the maximum level then the second time it zoom like if the layer was at a visible scale. It should go at that scale the first time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/details/details-record-esrifeature.html, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQamrqmfapFBDcwgsVY:-KQamrqmfapFBDcwgsVZ:b-3wazo1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/details/details-record-esrifeature.html#L18)):*
> ```HTML
> 
>     <md-button class="md-icon-button rv-icon-20" ng-click="self.zoomToFeature()"
>         ng-disabled="!(self.requester.layerRec.visible && self.requester.layerRec.visibleAtMapScale)">
> ```

We probably don't want to disable this zoom-to button is the layer is out of scale as well.

---

*[src/app/ui/filters/filters-default.directive.js, line 231 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQaHYkuEC7PJX3f6onP:-KQaml3ucr_4Z_DEc9m9:b39ttej) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/filters/filters-default.directive.js#L231)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Yes it zoom to the maximum level geometry is still visible. It is a little but weird behaviour because the first time I click on zoom to feature it only zoom to the maximum level then the second time it zoom like if the layer was at a visible scale. It should go at that scale the first time.
</details>
Yeap, I get that too. Can you log this as a bug? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 231 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQaHYkuEC7PJX3f6onP:-KQaoi4-HOtsKmgzorsa:b-t4i5cs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/filters/filters-default.directive.js#L231)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Yeap, I get that too. Can you log this as a bug? 
</details>
I will do!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by jolevesq** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 231 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQaHYkuEC7PJX3f6onP:-KQb2KxvvMZpzx_0wRLe:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/filters/filters-default.directive.js#L231)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I will do!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by jolevesq** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-record-esrifeature.html, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-KQamrqmfapFBDcwgsVY:-KQb4GwdQaRbavNH98-O:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b2f54683c490b7ef98b8766c0559bfb6e2719bf/src/app/ui/details/details-record-esrifeature.html#L18)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> We probably don't want to disable this zoom-to button is the layer is out of scale as well.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1134#-:-KQb4OW18vc6Fo3zhKYM:bnfp4nl)*

**Pull request merged**
