### PR TITLE
fix(ui): add icon indicating tile layer in wrong projection

### LINKED ISSUE #1186: Visibility of user-added ESRI Tile Layer cannot be changed
I added [this layer](http://ec.gc.ca/arcgis/rest/services/Basemaps/OilSandsBasemap/MapServer/) and the visibility control is disabled in its legend entry (visibility is initially off as well).

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1186

## Testing
:eye: 

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1758)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Any sample layer urls to test this?

---

Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1758#-:-KeshbbHB11UB5z1GMhB:b-dh9k8o)*

**Comment by AleksueiR** [comment]
Found it in the original issue: http://ec.gc.ca/arcgis/rest/services/Basemaps/OilSandsBasemap/MapServer/
Nice and clean :lgtm:  :+1: 

---

Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1758#-:-Kesi8cdSpVSXOkUxPIJ:b-2yjd92)*

**Comment by milesap** [comment]
Pushing again, travis failed to report status

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1758)*

**Pull request merged**
