### PR TITLE
fix(ui): update docs and focus manager update

### LINKED ISSUE #2021: Focus manager displays empty pop up
On `index-mobile.html` when the page is loaded and you tab to focus the viewer, an empty pop up box appears. 

This page should not display a pop up since it is a full page app. Though the pop up should be addressed  for the pages that do use it.

fm

### PR DESCRIPTION
**Pull request by milesap**
## Description
- set fullscreen config property so that focus pop up does not occur for `index-mobile.html`
- added ui -> fullscreen config entry
- corrected focus manager pop up translations issue
- updated PR template

Closes #2021, #1920, #1953

## Testing
womm

## Documentation
:+1: 

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2025)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm: Demo works - no nasty boxes :+1: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/config.class.js, line 1953 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025#-KnGCAzs2xgMdOiFyPQe:-KnGCAzs2xgMdOiFyPQf:budwb5f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4453c195cd07f314c11d20a880bc4d8950a9562f/src/app/core/config.class.js#L1953)):*
> ```JavaScript
>             this._legend = new UILegend(uiSource.legend);
>             this._help = new Help(uiSource.help);
>             this._fullscreen = uiSource.fullscreen;
> ```

Needs a corresponding schema change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025#-:-KnGCebNh2U7-zBAGmJc:bf91gf8)*

**Comment by jolevesq** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/locales/help/default/fr-CA.md, line 68 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025#-KnGDOWj2SErbTdbvyHp:-KnGDOWk4NLuPm0Xask5:bbhnqsn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4453c195cd07f314c11d20a880bc4d8950a9562f/src/locales/help/default/fr-CA.md#L68)):*
> ```Markdown
> # Partager
> 
> L'option partager est utilisé pour générer une URL partageable de la carte dans son état actuel avec les jeux de données sélectionnés. Elle est accessible dans le menu principal. Si une clé Google API est configurée pour la carte, vous aurez également la possibilité de générer un lien court. Une fois que vous mettez en surbrillance le lien, copiez-le comme vous copiez normalement du texte (clic droit -> copier ou Ctrl+C)
> ```

Put  Google API inside double quotes. The user will understand it is not translated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025)*

**Comment by milesap** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.class.js, line 1953 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025#-KnGCAzs2xgMdOiFyPQe:-KnJXToS81ib2YP0El35:b-8b11j9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4453c195cd07f314c11d20a880bc4d8950a9562f/src/app/core/config.class.js#L1953)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Needs a corresponding schema change.
</blockquote></details>

Added

---

*[src/locales/help/default/fr-CA.md, line 68 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025#-KnGDOWj2SErbTdbvyHp:-KnJXpMiW7tCoP6SY0ZN:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4453c195cd07f314c11d20a880bc4d8950a9562f/src/locales/help/default/fr-CA.md#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put  Google API inside double quotes. The user will understand it is not translated.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2025#-:-KnJkg7ODgEvhuOIAbW9:bnfp4nl)*

**Pull request merged**
