### PR TITLE
feat(ui): add opt description to legend blocks

### LINKED ISSUE #2260: [#TM9] A map layer entry can have a description defined which will appear beneath the layer title and above the layer symbology when expanded.
One item from [thematic maps](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/405) got lost along the way.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Allows to add an optional description to legend entry blocks and legend info blocks (unbound layers only).

Config schema is updated to 2.1.

Closes #2260

## Testing

layer_description

## Documentation
Inline comments.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2281)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281)*

**Comment by JahidAhmed** [comment]
Reviewed 7 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/geo/legend-block.class.js, line 306 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281#-Kq8pq4igvQ-tttuUK0z:-Kq8pq4igvQ-tttuUK1-:b-ulu81x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6824ebc932ab330ec2497e2d22ef2bf1c8aa7451/src/app/geo/legend-block.class.js#L306)):*
> ```JavaScript
> 
>         get layerName () {              return this.blockConfig.layerName; }
>         get description () {            return this._blockConfig.description; }
> ```

Should this be `this.blockConfig`?

---

*[src/app/geo/legend-block.class.js, line 605 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281#-Kq8psTi9t0S0e5rIvvX:-Kq8psTi9t0S0e5rIvvY:b-kshff2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6824ebc932ab330ec2497e2d22ef2bf1c8aa7451/src/app/geo/legend-block.class.js#L605)):*
> ```JavaScript
>         fetchGraphic(oid) {         return this._mainProxyWrapper.fetchGraphic(oid); }
> 
>         get description () {    return this._blockConfig.description; }
> ```

Similarly here, `this.blockConfig`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281)*

**Comment by AleksueiR** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend-block.class.js, line 306 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281#-Kq8pq4igvQ-tttuUK0z:-Kq8s9SmvXCZVUJYjIJb:boj1qgt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6824ebc932ab330ec2497e2d22ef2bf1c8aa7451/src/app/geo/legend-block.class.js#L306)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Should this be `this.blockConfig`?
</blockquote></details>

Good catch. Done.

---

*[src/app/geo/legend-block.class.js, line 605 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281#-Kq8psTi9t0S0e5rIvvX:-Kq8sBiTmPDFvynWEZUS:boj1qgt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6824ebc932ab330ec2497e2d22ef2bf1c8aa7451/src/app/geo/legend-block.class.js#L605)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Similarly here, `this.blockConfig`
</blockquote></details>

Good catch. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281#-:-Kq8tdfNCc9-aldlJA3q:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2281)*

**Pull request merged**
