### PR TITLE
bugs galore

### LINKED ISSUE #2619: Map image has to be re-generated automatically  when Custom image size set and selected
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=ZoomScale,Airports,JOSM,Barley,NPRI_CO,CESI_Other,EcoAction,mb_colour,Railways

Steps to reproduce:
1.Select Export 
2. Set any custom  size  . ( 520 x 320 ) and click generate .Do not proceed with export .
3. Select any other size .Image regenerated automatically and ready for download .
4. Select again custom  size . Same image as before and "generate " button not available

### LINKED ISSUE #2620: User added single entry Dynamic service layer not refreshing after set up refresh interval
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-04/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/21

• Add the above test data as ESRI Dynamic Layer
• In step 3 select Average ambient ozone concentrations... (the default one) sub-layer to add
• Set Refresh Interval to some value, for example 0.2 minute and Reload
After reloading, this layer doesn't refresh.
image

### LINKED ISSUE #2633: Unexpected highlight oulitne on legend items
An unexpected outline is shown around legend items and their symbology stack elements when clicked with a mouse. It doesn't seem to show up when tabbing to interactive elements inside the legend.

This highlight is not needed, and just gets in the way.

### LINKED ISSUE #2636: Only the layer of the first RCS key is loaded
Tested Build: http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways

When loading layers with RCS keys in the URL, the viewer only loads the layer of the first RCS key.  For example, only JOSM is loaded in the tested build above.

### LINKED ISSUE #2639: OnHover ToolTips not working for User-added ESRI Feature Layers
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale
Test data: ne_10m_ports.zip

- Add ESRI Feature Layers from above test data
- Place cursor on any of map points for the imported layer
Tooltip didn't display the default field for the feature as expected. However, OnHover ToolTips work well for JOSM layer.
image

### LINKED ISSUE #2643: Table filter date picker stays in English
The date picker in the date-range filters stay in English when the page is in French. Most obvious is the days of the week letters.

Can see it by using this [service](http://section917.cloudapp.net/arcgis/rest/services/TestData/TimeParty/MapServer/0) and opening the data table, then selecting the date picker on the time based columns

### LINKED ISSUE #2645: COORDS INFO cannot open coordinates info window
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

-  From left-side menu click COORDS INFO
-  Place the + sign on any point on the map
It didn't pop a window like before to tell user the detail Coordinates info, instead it opened up Feature details panel as below screenshot.

image

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2619 - generate option enabled again on switch
Closes #2620 - refresh intervals fixed for dynamic single entry collapsed
Closes #2633 - removed outline
Closes #2636 - rcs keys loading correctly
Closes #2639 - tooltips for file-based layers
Closes #2643 - translate datepicker options
Closes #2645 - coords info pop-up window appears

## Testing
:eyes: 

## Documentation
In-line

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/geo/legend.service.js, line 450 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646#-LA-IQzEEBArv7boLBzB:-LA-IQzEEBArv7boLBzC:b-t77y59) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c3e92556e93114777e427f420a8d9ab0d231408/src/app/geo/legend.service.js#L450)):*
> ```JavaScript
>             } else {
>                 layerConfig.layerEntries.forEach(entry => (entry.cachedRefreshInterval = entry.refreshInterval));
>             }
> ```

a lot of code to just disappear. can you either comment or tell me why its going? donethx.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 450 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646#-LA-IQzEEBArv7boLBzB:-LA-LTF30B9WTB3p7lwT:b-fc4t9b) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c3e92556e93114777e427f420a8d9ab0d231408/src/app/geo/legend.service.js#L450)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

a lot of code to just disappear. can you either comment or tell me why its going? donethx.
</blockquote></details>

there was an inconsistency with where the refresh interval was being set for dynamics. at first, it was being set on the parent node and then copied over to all the child nodes here.

i made changes inside `legend-element-factory` so that its consistent through and its only set on the parent now to avoid any of the problems where the child has a refresh interval, but a hidden parent (collapsed) is still set as 0 with no way to change it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 11 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646)*

**Pull request merged**
