### PR TITLE
fix(bug): Legend panel gets stuck above app-bar if rapidly opened and…

### PR DESCRIPTION
**Pull request by jolevesq**
Debounce function to solve problem when user click rapidly on legend button.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1130)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQ_mRoxQzAXM1kIpYSp:bt94735) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
> ```JavaScript
>         // article: http://unscriptable.com/2009/03/20/debouncing-javascript-methods/
>         // source: http://jsfiddle.net/Warspawn/6K7Kd/ (adapted from angular's $timeout code)
>         .factory('debounceService', ['$rootScope', '$browser', '$q', '$exceptionHandler',
> ```

Thanks for the debounce article, we certainly can use it in a few places.
However, I think this implementation is overly complex, uses deferreds, and relies on some of Angular's private functions (like $browser.defer). 

Here's my take on this:
```js
/**
 * Registers a function for debouncing. If the returned function is executed more than once at intervals less that the detection period, only the first call will go through.
 * @function registerDebounce
 * @param {Function} fn a function to debounced
 * @param {Number} delay detection period for debouncing
 * @param {Boolean} skipApply optional; skips triggering a digest cycle
 * @private
 * @return {Function} a debounced function; execute at will
 */
function registerDebounce(fn, delay, skipApply = false) {
	let timeoutHandle;
	let bouncing = false; // bouncing is true when the function is called during the detection period after the first call
	
	return (...args) => {
		if (!bouncing) {
		   fn(...args); // pass any arguments to the registered function
		   if (!skipApply) {
		       $rootScope.$applyAsync(); // applyAsync during the next digest cycle
		   }
		   bouncing = true;
		}
			
		$timeout.cancel(timeoutHandle);
		timeoutHandle = $timeout(bouncing = false, delay); // stop bouncing
	};
}
```
Here's a codepen with an example: http://codepen.io/AleksueiR/pen/YGzway

It can be used like this:
```js
const debounceToggleToc = debounceService.registerDebounce(debounceToggleToc, 175);

 function toggleToc() {
     debounceToggleToc();
}
```

What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQa4zgLCEP2K3esL94R:bytnsgj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Thanks for the debounce article, we certainly can use it in a few places.
> However, I think this implementation is overly complex, uses deferreds, and relies on some of Angular's private functions (like $browser.defer). 
> 
> Here's my take on this:
> ```js
> /**
>  * Registers a function for debouncing. If the returned function is executed more than once at intervals less that the detection period, only the first call will go through.
>  * @function registerDebounce
>  * @param {Function} fn a function to debounced
>  * @param {Number} delay detection period for debouncing
>  * @param {Boolean} skipApply optional; skips triggering a digest cycle
>  * @private
>  * @return {Function} a debounced function; execute at will
>  */
> function registerDebounce(fn, delay, skipApply = false) {
> 	let timeoutHandle;
> 	let bouncing = false; // bouncing is true when the function is called during the detection period after the first call
> 	
> 	return (...args) => {
> 		if (!bouncing) {
> 		   fn(...args); // pass any arguments to the registered function
> 		   if (!skipApply) {
> 		       $rootScope.$applyAsync(); // applyAsync during the next digest cycle
> 		   }
> 		   bouncing = true;
> 		}
> 			
> 		$timeout.cancel(timeoutHandle);
> 		timeoutHandle = $timeout(bouncing = false, delay); // stop bouncing
> 	};
> }
> ```
> Here's a codepen with an example: http://codepen.io/AleksueiR/pen/YGzway
> 
> It can be used like this:
> ```js
> const debounceToggleToc = debounceService.registerDebounce(debounceToggleToc, 175);
> 
>  function toggleToc() {
>      debounceToggleToc();
> }
> ```
> 
> What do you think?
</details>
You are right, the implementation is a little bit complex, more then the function I had in GCViz. Your implementation is really clean I think we should use yours.  Should we let this inside a service? If not, where should I put this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQa68xMQtH1gZhLESQw:b-rcpjpl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> You are right, the implementation is a little bit complex, more then the function I had in GCViz. Your implementation is really clean I think we should use yours.  Should we let this inside a service? If not, where should I put this function.
</details>
Keeping it in a service is a good idea - we can reuse it elsewhere in the app then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQaVaFF7Q7vXGePfX0T:bjex3up) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Keeping it in a service is a good idea - we can reuse it elsewhere in the app then.
</details>
I made a small modification. In your code the function is trigger the first time the button is press then if we press on the button nothing happen. I made it the other way, the function is trigger only when the user finish to push the button. I find it more user friendly. This way the function is triggered when the user finish to press the button. What do you think?

```return (...args) => {
                if (!bouncing) {
                    //fn(...args); // pass any arguments to the registered function
                    if (!skipApply) {
                        $rootScope.$applyAsync(); // applyAsync during the next digest cycle
                    }
                    bouncing = true;
                }

                $timeout.cancel(timeoutHandle);
                timeoutHandle = $timeout(() => {
                    // fire function when debounce is finish
                    fn(...args); // pass any arguments to the registered function
                    bouncing = false;
                }, delay); // stop bouncing
            };```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*
<!-- Sent from Reviewable.io -->

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQaW_iAy6s8v_brkkWe:b5um432) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I made a small modification. In your code the function is trigger the first time the button is press then if we press on the button nothing happen. I made it the other way, the function is trigger only when the user finish to push the button. I find it more user friendly. This way the function is triggered when the user finish to press the button. What do you think?
> 
> ```return (...args) => {
>                 if (!bouncing) {
>                     //fn(...args); // pass any arguments to the registered function
>                     if (!skipApply) {
>                         $rootScope.$applyAsync(); // applyAsync during the next digest cycle
>                     }
>                     bouncing = true;
>                 }
> 
>                 $timeout.cancel(timeoutHandle);
>                 timeoutHandle = $timeout(() => {
>                     // fire function when debounce is finish
>                     fn(...args); // pass any arguments to the registered function
>                     bouncing = false;
>                 }, delay); // stop bouncing
>             };```
</details>
Ha-ha :) I was thinking the opposite. I guess it depends on your situation: if we are talking about mouse hover (jquery intent plugin comes to mind), then yes, it would be more useful to fire on the last call; however, for opening legend, I think it should fire on the first call (if the user unintentionally clicks twice and debounce is triggered, it might appear that the application is not responsive as nothing happened during the first click). That's my thoughts anyway.

Can you add a flag to the registerDebounce function that let's you pick the behaviour - execute on first or last call? This might be useful later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQaY3QFmG3Nv-9Eh0bP:btt1ne8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Ha-ha :) I was thinking the opposite. I guess it depends on your situation: if we are talking about mouse hover (jquery intent plugin comes to mind), then yes, it would be more useful to fire on the last call; however, for opening legend, I think it should fire on the first call (if the user unintentionally clicks twice and debounce is triggered, it might appear that the application is not responsive as nothing happened during the first click). That's my thoughts anyway.
> 
> Can you add a flag to the registerDebounce function that let's you pick the behaviour - execute on first or last call? This might be useful later.
</details>
Good idea for the flag. I understand your not responsive feeling. This is quite true if the delay is long. For a 175 millisecond delay is not too bad. I will put it at the end in my next push you will be able to see how it respond.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQaemjZGV3iNfkWLUqQ:bpkafhp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Good idea for the flag. I understand your not responsive feeling. This is quite true if the delay is long. For a 175 millisecond delay is not too bad. I will put it at the end in my next push you will be able to see how it respond.
</details>
I see what you mean, but even with a single click a 175 ms delay is still noticeable (to me at least). I would prefer not to introduce additional delays if we can avoid it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQai3nP4ppe2rLBLWQy:b-rtrhk6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I see what you mean, but even with a single click a 175 ms delay is still noticeable (to me at least). I would prefer not to introduce additional delays if we can avoid it.
</details>
I made the modification

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/debounce.service.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-KQ_mRow_Ok5GYj_ytm8:-KQalyfnTC9Iab5KHNkQ:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/773b67d72f52db30cfa5645a21b48b00200232fd/src/app/core/debounce.service.js#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I made the modification
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1130#-:-KQam0Gv5_hwteIhDlrA:bnfp4nl)*

**Pull request merged**
