### PR TITLE
refactor(map): don't change cursor to hand when identify mode is silent

### LINKED ISSUE #2599: Disable identify hints for `Silent` and `None` Identify modes on Feature layers
## Current Behaviour

A hint is provided to the user by changing the mouse cursor to the `hand` when hovering over features from a Feature layer indicating the availability of identify results.

## Suggested Changes
After https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2595 is implemented, the `hard` cursor hint should not be provided for `Silent` and `None` identify modes for the user will not see any changes to the map or details panel.

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #2599

With the changes mentioned in #2599 this was pretty much already done in #2740. Just updated to use the `IdentifyMode` constant.
## Testing

:eyes:
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm, @ShrutiVellanki, and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783#-:-LEzazSk5ZgNj4bKfgce:bnfp4nl)*

**Comment by ShrutiVellanki** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm, @ShrutiVellanki, and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783#-:-LEzdnmbDhTmzCeLoUEx:bnfp4nl)*

**Comment by barryytm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShrutiVellanki and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783#-:-LFI1BH_9i8mpIO6Jl1A:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShrutiVellanki)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShrutiVellanki)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783#-:-LFXVI2EB2Po7Jj--23W:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783)*

**Pull request merged**
