### PR TITLE
feat(ui): add a parameter to setting panel to disable layer(s) in the…

### LINKED ISSUE #409: Disable Layer Queries
Allow each map service to have Identify/GetFeatureInfo queries be disabled.  This is helpful when a user is experiencing long response times from a particular layer or just wish to add a layer for background context but are not interested in the data contained in the layer itself.  This setting should be available in the settings menu and result in an indicator being displayed in the Legend which shows that the layer is not responding to queries.

### PR DESCRIPTION
**Pull request by jolevesq**
… identify windows

Closes #409

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/654)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/settings/settings.html, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIdbY3yQmu2G_1yfjr3:-KIdbY3yQmu2G_1yfjr4:-1484789697) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/ui/settings/settings.html#L56)):*
> ```HTML
>                         </md-button>
>                     </div>
>                 </div>
> ```

For this setting, please, use a`switch` control:
```js
<div class="rv-setting-option" ng-if="self.tocEntry.options.query">
	<md-switch translate-attr-aria-label="settings.aria.query" class="md-primary rv-switch"
			   ng-model="self.tocEntry.options.query.value"
			   ng-change="self.toggleQuery()">
		{{'settings.label.query' | translate}}
	</md-switch>
</div>
```

We used `button` for enabling snapshot mode because it's a one-way operation and you can't switch back to the `on-demand` mode (switching back doesn't make sense since all the data is already downloaded to the client). The `query` setting is togglable and using a`switch` control is more appropriate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 163 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgpBkv0W4OZq9yygST:-KIgpBkv0W4OZq9yygSU:-1656522947) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L163)):*
> ```JavaScript
> 
>                 // ignore invisible layers and those where query option is false by returning empty object
>                 if (!layer.visibleAtMapScale || !layer.visible || !state.options.query.value) {
> ```

@james-rae @jolevesq , Does the `visibleAtMapScale` value indicate that __all child layers__ are out of scale? If not, we are dropping valid identify targets here.

---

*[src/app/geo/identify.service.js, line 176 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgqfP0jEEePPBdfqLm:-KIgqfP0jEEePPBdfqLn:-1235682390) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L176)):*
> ```JavaScript
> 
>                     // ignore invisible sublayers and those where query option is false by returning empty object
>                     if (!legendEntry.getVisibility() || !legendEntry.options.query.value || !parentQuery) {
> ```

Checking if a parent's query is `false` will exclude a valid identify target (`sublayer A`), as in this example:
```
- subgroup 1 [query: false]
    - sublayer A [query: true]
    - sublayer B [query: false]
```
Only checking `legendEntry`'s `query` value is necessary here, parents' values can be ignored.

---

*[src/app/ui/settings/settings.directive.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgnWzkLptI2h2ymQNZ:-KIgnWzkLptI2h2ymQN_:-826178659) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/ui/settings/settings.directive.js#L99)):*
> ```JavaScript
>             const tocEntry = self.tocEntry;
>             tocEntry.options.query.value = value;
>             setTocEntryChildrenQuery(value, tocEntry.items);
> ```

There is a handy helper function you can use to walk down the legend hierarchy:
```js
if (tocEntry.type === 'group') {
    tocEntry.walkItems(item => item.options.query.value = value);
}
```
`walkItems` function takes a function and applies it to all non-group children.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 163 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgpBkv0W4OZq9yygST:-KIhH3sH3VCYg2kIL4gv:1848973328) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L163)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> @james-rae @jolevesq , Does the `visibleAtMapScale` value indicate that __all child layers__ are out of scale? If not, we are dropping valid identify targets here.
</details>
it does not.  may want to utilize the stuff I added for the scale flags.  see the latest commits on [this branch](https://github.com/james-rae/fgpv-vpgf/commits/feature/scaleFlag).  Easist approach would be to grab the `flags.scale.visible` from the legend, though might not be best architecture to reference the legend from the identify service.  Alternate approach is to re-calculate the scales using function `makeScaleSet` in layer-registry  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 176 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgqfP0jEEePPBdfqLm:-KIhJ46MXo6XNbDl96t7:2127613396) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L176)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Checking if a parent's query is `false` will exclude a valid identify target (`sublayer A`), as in this example:
> ```
> - subgroup 1 [query: false]
>     - sublayer A [query: true]
>     - sublayer B [query: false]
> ```
> Only checking `legendEntry`'s `query` value is necessary here, parents' values can be ignored.
</details>
Yes, it will exclude sublayerA but it will behave the same way as visibility. In the above, if subgroup1 visibility is false user will not see sublayerA even if value is true.

By default,  because of this line who check the first entry, in your case even if sublayerA is true, if subgroup is true it will not show. It is why i added the parent check because with 2 levels it behave differently.

```
// ignore invisible layers and those where query option is false by returning empty object
                if (!layer.visibleAtMapScale || !layer.visible || !state.options.query.value) {
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 163 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgpBkv0W4OZq9yygST:-KIhx5djXBNuMz0PdgOd:2011818464) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L163)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> it does not.  may want to utilize the stuff I added for the scale flags.  see the latest commits on [this branch](https://github.com/james-rae/fgpv-vpgf/commits/feature/scaleFlag).  Easist approach would be to grab the `flags.scale.visible` from the legend, though might not be best architecture to reference the legend from the identify service.  Alternate approach is to re-calculate the scales using function `makeScaleSet` in layer-registry  
</details>
To be fixed later: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/664 

---

*[src/app/geo/identify.service.js, line 176 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgqfP0jEEePPBdfqLm:-KIhuT9CB5dT5ZvrdIIp:-2111272807) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L176)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Yes, it will exclude sublayerA but it will behave the same way as visibility. In the above, if subgroup1 visibility is false user will not see sublayerA even if value is true.
> 
> By default,  because of this line who check the first entry, in your case even if sublayerA is true, if subgroup is true it will not show. It is why i added the parent check because with 2 levels it behave differently.
> 
> ```
> // ignore invisible layers and those where query option is false by returning empty object
>                 if (!layer.visibleAtMapScale || !layer.visible || !state.options.query.value) {
> ```
> 
</details>
There is a bug in how we handle the visibility of the layer object itself:
- if the top legend entry of a dynamic layer is turned off, the layer itself is made invisible (to save on server requests)
- if then its child it turned on, this doesn't turn on the parent layer object as it should
Bug is logged here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/663


Please, remove the `parentQuery` check on line 176 and `query` option check on line 163, and we will address #663 separately. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654)*

**Comment by jolevesq** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 163 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgpBkv0W4OZq9yygST:-KIiUuqIAqE7HEt9Bmel:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L163)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> To be fixed later: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/664 
</details>
Done.

---

*[src/app/geo/identify.service.js, line 176 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgqfP0jEEePPBdfqLm:-KIiUvzI0v1lnqGXYOfH:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/geo/identify.service.js#L176)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> There is a bug in how we handle the visibility of the layer object itself:
> - if the top legend entry of a dynamic layer is turned off, the layer itself is made invisible (to save on server requests)
> - if then its child it turned on, this doesn't turn on the parent layer object as it should
> Bug is logged here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/663
> 
> 
> Please, remove the `parentQuery` check on line 176 and `query` option check on line 163, and we will address #663 separately. 
</details>
Done.

---

*[src/app/ui/settings/settings.directive.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIgnWzkLptI2h2ymQNZ:-KIiUzSG2yMW3K_nGlQ-:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/ui/settings/settings.directive.js#L99)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> There is a handy helper function you can use to walk down the legend hierarchy:
> ```js
> if (tocEntry.type === 'group') {
>     tocEntry.walkItems(item => item.options.query.value = value);
> }
> ```
> `walkItems` function takes a function and applies it to all non-group children.
</details>
Done.

---

*[src/app/ui/settings/settings.html, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-KIdbY3yQmu2G_1yfjr3:-KIiV7U0WMcCrgeyyNTj:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6c5e6e19b792f6c2985fa88af22f32b2465407a/src/app/ui/settings/settings.html#L56)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> For this setting, please, use a`switch` control:
> ```js
> <div class="rv-setting-option" ng-if="self.tocEntry.options.query">
> 	<md-switch translate-attr-aria-label="settings.aria.query" class="md-primary rv-switch"
> 			   ng-model="self.tocEntry.options.query.value"
> 			   ng-change="self.toggleQuery()">
> 		{{'settings.label.query' | translate}}
> 	</md-switch>
> </div>
> ```
> 
> We used `button` for enabling snapshot mode because it's a one-way operation and you can't switch back to the `on-demand` mode (switching back doesn't make sense since all the data is already downloaded to the client). The `query` setting is togglable and using a`switch` control is more appropriate.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654)*

**Comment by AleksueiR** [comment]
:lgtm:

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> #### feat\(ui\): add a parameter to setting panel to disable layer\(s\) in the…
> 
> … identify windows
> 
> 
> 
> Closes #409
> 
> 
> 
</details>


---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654#-:-KIlwJZ-S4fLKtZNkUIj:1417088721)*

**Comment by james-rae** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/654)*

**Pull request merged**
