### PR TITLE
Symbology

### PR DESCRIPTION
**Pull request by cynngah**
#477

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/504)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 71 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504#-KFfYtfZfCA275orJd9z:-KFfYtfZfCA275orJdA-:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6a3bd85dd57e8f82e5a029c6d0ace63549af2e8/src/app/ui/filters/filters-default.directive.js#L71)):*
const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504)*

**Comment by AleksueiR** [comment]
When I build the branch, icons show up in the "JOSM" datagrid, but the "rcs.cesi" datagrid fails to open altogether
. 

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504#-:-KFiHVtFeDVUrQp8eapi:-773868218)*

**Comment by cynngah** [comment]
apparently featureIndex is being hard coded to 0 right now. I could put in a hacky fix to make it work until featureIndex gets fixed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504#-:-KFi_Wzo5UULGe78XYnt:1641132707)*

**Comment by AleksueiR** [comment]
Sure, just add some notes about it and create an issue to fix it later.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504#-:-KFiarS2pQU8_GEHUbVV:-178392414)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 73 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504#-KFij7Mmv6_A65k1TLET:-KFij7Mmv6_A65k1TLEU:637139078) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/931dc91ce206ca74f6924fa080d59236a92f7f9b/src/app/ui/filters/filters-default.directive.js#L73)):*
add a TODO or FIXME to this line, so we remember to come back to it.  Otherwise, nice hack :elephant: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 73 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504#-KFij7Mmv6_A65k1TLET:-KFik9ZABcJ6ydPshSkC:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/931dc91ce206ca74f6924fa080d59236a92f7f9b/src/app/ui/filters/filters-default.directive.js#L73)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/504)*

**Pull request merged**
