### PR TITLE
fix(ui): automatic URL selection in share dialog input field

### LINKED ISSUE #1284: Share Link not working in IE11 for both Short Link and Long Link
Tested build URL: http://fgpv.cloudapp.net/demo/release-v1.4.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

In IE11, although the dialog is shown up and "Click to copy" will display "Link copied to clipboard", but actually the URL is not copied. When pasting to a new tab in IE11, it is not the Link generated by Share Link in IE11, instead it just picks up whatever the previous copied item on clipboard.

image

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
Share Link not working in IE11 for both Short Link and Long Link #1284

## Testing
Test with IE11, Fox and Chrome
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [ ] PR targets the correct release version

Closes #1284

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1607)

### CODE REVIEW

**Comment by alyec** [comment]
:lgtm: (Firefox)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-:-KbAXLM3TqgNEfBIPLrh:b53czl5)*

**Comment by jolevesq** [comment]
:lgtm: (Chrome and Safari)

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-:-KbGNHx83wQGHhzwjUpf:barfu37)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/share-dialog.html, line 9 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLzMjKTk7FeEykZBSm:-KbLzMjKTk7FeEykZBSn:bv73gr3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/share-dialog.html#L9)):*
> ```HTML
> 
>             <md-input-container class="md-block" flex-gt-xs>
>                 <input id="rv-shareLink" type="text" ng-model="self.url" readonly md-select-on-focus/>
> ```

Kudos for finding `select-on-focus` directive.

---

*[src/app/ui/sidenav/sidenav.service.js, line 107 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLyXW4BwapK6DOmouj:-KbLyXW4BwapK6DOmouk:b-7xpt7t) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L107)):*
> ```JavaScript
>                         clickOutsideToClose: true,
>                         fullscreen: false
>                     }).then(function () {
> ```

Does this promise resolve when the dialog is rendered on the page?
There is a `onShowing ` callback function (https://material.angularjs.org/latest/api/service/$mdDialog) you can use for this purpose. 

---

*[src/app/ui/sidenav/sidenav.service.js, line 196 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLxrGUNaO99-LLgKZz:-KbLxrGUNaO99-LLgK_-:b-8cfthm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L196)):*
> ```JavaScript
>             // watch for changing URL value to set actual value
>             $scope.$watch('self.url', () => {
>                 $timeout(selectURL());
> ```

Does it work without `timeout`?

Also, the url can only be updated inside this directive, so we know when it's being updated. No need to watch for changes. Just call `selectURL` from `getLongLink` and `getShortLink` functions.

---

*[src/app/ui/sidenav/sidenav.service.js, line 244 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLyi_052IAMXFmLo7d:-KbLyi_052IAMXFmLo7e:b-v1czm8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L244)):*
> ```JavaScript
>             */
>             function selectURL() {
>                 $(document.getElementById(SHARE_LINK_ID)).select();
> ```

This searches the whole document. You can store the reference to the dialog node in the `onShowing` callback to avoid doing that. See here for an example: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/export/export.service.js#L57

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/sidenav/sidenav.service.js, line 107 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLyXW4BwapK6DOmouj:-KbLzdrDWDLSRVadWzQO:bqkvist) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L107)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Does this promise resolve when the dialog is rendered on the page?
There is a `onShowing ` callback function (https://material.angularjs.org/latest/api/service/$mdDialog) you can use for this purpose. 
</blockquote></details>

onShowing execute too soon. I also tried onComplete whitout better results. Maybe I did it the wrong way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/sidenav/sidenav.service.js, line 196 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLxrGUNaO99-LLgKZz:-KbM-kGtANu99DMNloqo:bfy8fsk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L196)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Does it work without `timeout`?

Also, the url can only be updated inside this directive, so we know when it's being updated. No need to watch for changes. Just call `selectURL` from `getLongLink` and `getShortLink` functions.
</blockquote></details>

I didn't try that one.  I'll check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/sidenav.service.js, line 107 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLyXW4BwapK6DOmouj:-KbM03xPuizXzY4RtXbW:b-xo8wh0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L107)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

onShowing execute too soon. I also tried onComplete whitout better results. Maybe I did it the wrong way.
</blockquote></details>

Executes before the url is available? It should be late enough to get the reference to the element node, so you don't have to `$(document)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/sidenav/sidenav.service.js, line 244 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLyi_052IAMXFmLo7d:-KbM-ytqB2HUVXPymmyP:b-uqmqy4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L244)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This searches the whole document. You can store the reference to the dialog node in the `onShowing` callback to avoid doing that. See here for an example: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/export/export.service.js#L57
</blockquote></details>

You already gave me that info in the issue. Maybe, I didn't apply it correctly. Thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607)*

**Comment by ChrisLatRNCan** [comment]
I'll try on another branch without throwing that one into the garbage.

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/ui/sidenav/share-dialog.html, line 9 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbM2yiOI8hEZ8Bfbe47:-KbM2yiOI8hEZ8Bfbe48:b-a0cixh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/share-dialog.html#L9)):*
> ```HTML
> 
>             <md-input-container class="md-block" flex-gt-xs>
>                 <input id="rv-shareLink" type="text" ng-model="self.url" readonly md-select-on-focus/>
> ```

It's better to use a class, instead of an id. Ids should not repeat, and this one will in case there are several maps on the page.

---

*[src/app/ui/sidenav/sidenav.service.js, line 244 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607#-KbLyi_052IAMXFmLo7d:-KbM2olL67m4O_uyHh3S:br7wzs2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63d9966779bd332abf566552fcee288d7cc49ad8/src/app/ui/sidenav/sidenav.service.js#L244)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

You already gave me that info in the issue. Maybe, I didn't apply it correctly. Thx
</blockquote></details>

Quite close. Here's what I thinking of:

```js
$mdDialog.show({
     ....
    fullscreen: false,
    onShowing: (scope, element) => 
        (scope.element = element.find('.side-nav-summary'))
});

....

function selectURL() {
    self.scope.element.find('.rv-shareLink').select();
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1607)*

**Pull request closed without merging**
