### PR TITLE
jsdoc build

### PR DESCRIPTION
**Pull request by alyec**
Part one of #767

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/797)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 69 of 69 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797)*

**Comment by AleksueiR** [comment]
Reviewed 69 of 69 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/core/config.service.js, line 63 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797#-KKnRh7GYt627aJgJohx:-KKnRh7GYt627aJgJohy:448817789) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b0f9f971885f2ef58da8dd36f29be375dd6e8680/src/app/core/config.service.js#L63)):*
> ```JavaScript
>         /**
>          * Initializes `configService` by fetching and parsing `config` object.
>          * @function initialize
> ```

Do we need to add function names to the jsdoc block now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 63 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797#-KKnRh7GYt627aJgJohx:-KKnRx676ppKM51HPGdP:256733216) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b0f9f971885f2ef58da8dd36f29be375dd6e8680/src/app/core/config.service.js#L63)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Do we need to add function names to the jsdoc block now?
</details>
In most cases yes.  I'm planning on writing up a few metadocs on the wiki.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 63 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797#-KKnRh7GYt627aJgJohx:-KKnTZaSm1YPIao6aT00:-1834867264) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b0f9f971885f2ef58da8dd36f29be375dd6e8680/src/app/core/config.service.js#L63)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> In most cases yes.  I'm planning on writing up a few metadocs on the wiki.
</details>
Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797)*

**Comment by cynngah** [comment]
Reviewed 66 of 69 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/797)*

**Pull request merged**
