### PR TITLE
feat(geosearch): enhance geosearch

### LINKED ISSUE #1805: More geosearch enhancements
Some geosearch suggestions from previous PRs; some of them might not be relevant anymore.

- If I set a filter with the drop down there is no way to remove it. You can click the clear filter button but it will remove all the filters. May be we should have the first item in the list an item to reset the filter.

- When I close geosearch and get back to it later, my previous search is cleared. Would it be good to keep it as long as the user doesn't clear it himself? The filters works that way. For small screen when you select an element, you can't see it is the right thing until you close the panel and you lose your search.

- Would be great to see the overflow when hovering or tabbing to the element (like in our filter panel). Or when selected, there is a popup like the hovering to show the complete text selection.

- Focus is not trap inside geosearch when tabbing. At the end it goes to zoom control but it should go the search text.

- In FF and Safari, when I select a filter value with the keyboard FF completely lost focus and Safari bring it url bar then goes back to the filter.

### PR DESCRIPTION
**Pull request by jolevesq**
Close #1805

## Description

Enhancement for geosearch. The tooltip only shows for FF and Chrome. Need to see for IE and not working for Safari. For now there is only on focus woth the keyboard. If we like the tooltip idea, I can work on the hover as well.

## Testing

Chrome, FF and Safari

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1850)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Mouse clicking on the search results does not trigger zoom; tabbing to a result and pressing Enter does work.

---

Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/geo-search.service.js, line 149 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KiUjhCxo85GW4hONNbb:-KiUjhCxo85GW4hONNbc:b-1eyucg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/geo/geo-search.service.js#L149)):*
> ```JavaScript
> 
>                         // add ... to the list to reset filter from the selection bbox
>                         provinceList.push({ code: undefined, abbr: '...', name: '...' });
> ```

Can we use a more explicit code, something like `-1` instead of the `undefined`.

---

*[src/app/ui/geosearch/geosearch.directive.js, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KiUtiwqpKTn6pii3QXy:-KiUtiwqpKTn6pii3QXz:bwi7ck4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/ui/geosearch/geosearch.directive.js#L75)):*
> ```JavaScript
>          */
>         function onItemFocus(evt) {
>             const target = evt.target;
> ```

Instead of replacing the original elements, you can wrap `rv-results-item-main` and `rv-results-item-type` in another div, remove `overflow:hidden` and animate that. This way you can preserve the styling which is lost when the original items are concatenated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-:-KiUuAKNGaPi5_cBz3yV:b-e3ux9s)*

**Comment by milesap** [comment]
All issues in #1805 are addressed, works well! I am having the same issue as @aleksueir however where mouse clicking on results does not trigger a zoom. 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/geosearch/geosearch.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjHxWry8iOEBy5F7o20:-KjHxWrzabNEwmTqmnOA:b-o14vps) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/ui/geosearch/geosearch.service.js#L48)):*
> ```JavaScript
> 
>                 // force focus on open geosearch because sometimes it is lost
>                 $rootElement.find('.rv-geosearch-open').rvFocus();
> ```

We should avoid UI stuff in services, ideally a service should not know/care about elements. Please see if there is a better place for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-:-KjHzQqraJTDTji8kpil:b-zc54vu)*

**Comment by jolevesq** [comment]
Good catch! I made it work with the mouse as well.

---

Review status: 4 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/geo/geo-search.service.js, line 149 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KiUjhCxo85GW4hONNbb:-KjIEebpl5I82ysViizB:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/geo/geo-search.service.js#L149)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can we use a more explicit code, something like `-1` instead of the `undefined`.
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch.directive.js, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KiUtiwqpKTn6pii3QXy:-KjIa3DkHReuXHjh2yZ8:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/ui/geosearch/geosearch.directive.js#L75)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Instead of replacing the original elements, you can wrap `rv-results-item-main` and `rv-results-item-type` in another div, remove `overflow:hidden` and animate that. This way you can preserve the styling which is lost when the original items are concatenated.
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjHxWry8iOEBy5F7o20:-KjJ1TxuneV2Ph7jNYuI:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/ui/geosearch/geosearch.service.js#L48)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

We should avoid UI stuff in services, ideally a service should not know/care about elements. Please see if there is a better place for this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-:-KjJ1OSTNaFXvQAlkQJ0:bkf3go4)*

**Comment by milesap** [comment]
Reviewed 4 of 7 files at r2.
Review status: 8 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/ui/geosearch/geosearch.directive.js, line 47 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjJFGZCx9_vOVs20r7S:-KjJFGZCx9_vOVs20r7T:b-uzk64z) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/407e2d356c5b2c5e9d58597dcfa7e47826c1fbd0/src/app/ui/geosearch/geosearch.directive.js#L47)):*
> ```JavaScript
>                 }
> 
>                 $rootScope.$watch(() => stateManager.state.mainGeosearch.active, newValue => {
> ```

Please use `$rootScope.$on` instead of `$rootScope.$watch` for performance reasons. The service can emit an event that on will listen to.

---

*[src/app/ui/geosearch/geosearch.html, line 22 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjJFceALio-MQaF3bDb:-KjJFceTNUITYW-M4Ktl:bblmg8s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/407e2d356c5b2c5e9d58597dcfa7e47826c1fbd0/src/app/ui/geosearch/geosearch.html#L22)):*
> ```HTML
>                 ng-mouseleave="self.onItemBlur($event)"
>                 ng-mousedown="self.service.zoomTo(result)">
>                 
> ```

typo ot to to

---

*[src/app/ui/geosearch/geosearch.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjHxWry8iOEBy5F7o20:-KjJFjG-6zJLqpR-0qMH:b-6i7273) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/ui/geosearch/geosearch.service.js#L48)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Use `$rootScope.$emit` to compliment the `$on` in the directive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850)*

**Comment by jolevesq** [comment]
Review status: 4 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/geosearch/geosearch.directive.js, line 47 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjJFGZCx9_vOVs20r7S:-KjJtXcyO2HxpwCHVMmS:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/407e2d356c5b2c5e9d58597dcfa7e47826c1fbd0/src/app/ui/geosearch/geosearch.directive.js#L47)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Please use `$rootScope.$on` instead of `$rootScope.$watch` for performance reasons. The service can emit an event that on will listen to.
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch.html, line 22 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjJFceALio-MQaF3bDb:-KjJu4lyrQ5noVLXK2gR:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/407e2d356c5b2c5e9d58597dcfa7e47826c1fbd0/src/app/ui/geosearch/geosearch.html#L22)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

typo ot to to
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjHxWry8iOEBy5F7o20:-KjJu8wRw1r9HSD3oBlk:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78fae462272add18869a776c8f46ea5dd6ec3b87/src/app/ui/geosearch/geosearch.service.js#L48)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Use `$rootScope.$emit` to compliment the `$on` in the directive
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850)*

**Comment by milesap** [comment]
Reviewed 8 of 9 files at r3.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/geosearch/geosearch.directive.js, line 47 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850#-KjJFGZCx9_vOVs20r7S:-KjNMjVLATfkteySqdHf:btojbfd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/407e2d356c5b2c5e9d58597dcfa7e47826c1fbd0/src/app/ui/geosearch/geosearch.directive.js#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850)*

**Comment by milesap** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1850)*

**Pull request merged**
