### PR TITLE
fix(symbol): Safari doesn't render svg

### LINKED ISSUE #1671: Safari- Missing Symbology and wrong placement of right side menu
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-en.html?keys=EcoAction

image

Device Info

image

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1671, #1642

## Testing

Chrome and Safari

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1780)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/svg.directive.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780#-KffoK_o3Zvmu2CQrMVS:-KffoK_o3Zvmu2CQrMVT:bl4foc8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b8217cd379e1172b26d2edef209342d6a86a3d3/src/app/ui/common/svg.directive.js#L46)):*
> ```JavaScript
>             const stopWatch = scope.$watch('src', newValue => {
>                 if (newValue) {
>                     const node = angular.element(scope.src);
> ```

`rv-svg` directive is used in a bunch of places and for more than just svg content - it's a generic include directive. Please, check that it's actually svg code that is passed into it before modifying. Also, can you try updating broken `href` attribute using string replacement, since svg code is passed as a string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/svg.directive.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780#-KffoK_o3Zvmu2CQrMVS:-Kfg-tgq-kqV0f3nFpgn:bz7zk1n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b8217cd379e1172b26d2edef209342d6a86a3d3/src/app/ui/common/svg.directive.js#L46)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`rv-svg` directive is used in a bunch of places and for more than just svg content - it's a generic include directive. Please, check that it's actually svg code that is passed into it before modifying. Also, can you try updating broken `href` attribute using string replacement, since svg code is passed as a string?
</blockquote></details>

Try to replace the string but it didn't work. It is why I change the node instead. Will check for svg content

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/svg.directive.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780#-KffoK_o3Zvmu2CQrMVS:-KfkWw1PYe4i6SJm7k7W:b-slmih0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b8217cd379e1172b26d2edef209342d6a86a3d3/src/app/ui/common/svg.directive.js#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Try to replace the string but it didn't work. It is why I change the node instead. Will check for svg content
</blockquote></details>

Replacing the string didn't work? That's weird. When the svgcode is directly inserted into the page in dev tools, it works just fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/svg.directive.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780#-KffoK_o3Zvmu2CQrMVS:-KfkspJwqlKNKAXezY7E:bfpqld9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b8217cd379e1172b26d2edef209342d6a86a3d3/src/app/ui/common/svg.directive.js#L46)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Replacing the string didn't work? That's weird. When the svgcode is directly inserted into the page in dev tools, it works just fine.
</blockquote></details>

Maybe I did something wrong, I will try it again...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/svg.directive.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780#-KffoK_o3Zvmu2CQrMVS:-KfkvbRMDz0sOHxhzhA5:bynf7jp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b8217cd379e1172b26d2edef209342d6a86a3d3/src/app/ui/common/svg.directive.js#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Maybe I did something wrong, I will try it again...
</blockquote></details>

Don't know why didn't work before... but now it work with the string replacement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/svg.directive.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780#-KffoK_o3Zvmu2CQrMVS:-KflJRQlK0qJV6rN57qr:b-ikqyly) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b8217cd379e1172b26d2edef209342d6a86a3d3/src/app/ui/common/svg.directive.js#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Don't know why didn't work before... but now it work with the string replacement
</blockquote></details>

:sparkles:  nice :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1780#-:-Kg-Remr475lUu1J2FlL:bnfp4nl)*

**Pull request merged**
