### PR TITLE
Side panels: metadata and settings

### PR DESCRIPTION
**Pull request by AleksueiR**
Added metadata and settings side panels;
Fixed overlapping panel shadows;

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/13)

### CODE REVIEW

**Comment by alyec** [comment]
For SCSS I just blindly mark everything as reviewed.  I don't understand any of it :)

---

Reviewed 25 of 25 files at r1, 30 of 30 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/app/ui/metadata/metadata.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13#-K-3eUQbwGIC0EITHCGO)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27fd2bba04d835175e3b818b0904b91d4adab85f/src/app/ui/metadata/metadata.html#L1)):</sup>
There should be one line in here that's different from the rest.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13)

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13)

**Comment by alyec** [comment]
I think we should merge this, but after that I think we should take a pass through every file and at least add module level comments as @james-rae suggested.  We already have a lot of files and we're starting to add non-trivial code so it would be good to have guidelines as to what goes where.  We should also think about when we want to start enforcing some unit test coverage.


---

Reviewed 12 of 12 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/layout/side-panel-plug.controller.js, line 14 \[r8\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13#-K-JJSog1MR-Nd8-c01H)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/98aa97ac4545068c4329b61c0e7724f5d2426c64/src/app/layout/side-panel-plug.controller.js#L14)):</sup>
impressive hardcoding


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13)

**Comment by AleksueiR** [comment]
Review status: 34 of 37 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/layout/side-panel-plug.controller.js, line 14 \[r8\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13#-K-JJSog1MR-Nd8-c01H)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/98aa97ac4545068c4329b61c0e7724f5d2426c64/src/app/layout/side-panel-plug.controller.js#L14)):</sup>
I laughed so hard :joy: :joy: :joy: 
This a controller I copied directly from github. Turned out ng-class works fine with variables as well, so, no more CZ hardcoding.  :joy:

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13)

**Comment by AleksueiR** [comment]
@alyec, I agree. We should start writing proper comments and unit tets.
@ec-dev, Jack, since you know more about dgeni and how it parses comments, can you add some empty comment blocks to the code? I looked at angular comments and they use `@ngdoc` tag. Should we use it as well? Are there any other specific tags we should be using?


---

Review status: 34 of 37 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13)

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/layout/side-panel-plug.controller.js, line 14 \[r8\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13#-K-JJSog1MR-Nd8-c01H)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/98aa97ac4545068c4329b61c0e7724f5d2426c64/src/app/layout/side-panel-plug.controller.js#L14)):</sup>
@james-rae will be proud ... if he ever reads this stuff


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13)

**Comment by alyec** [comment]
Reviewed 33 of 33 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/13)

**Pull request merged**
