### PR TITLE
fix(ui): focus dialog improvement

### LINKED ISSUE #1377: Focus dialog something skipped
I noticed that skipping the focus dialog and then pressing Shift + Tab sometimes sets focus on the viewer directly without triggering the dialog. I think it might be related to that 200 ms delay - if `Shift + Tab` is pressed in that time window.

- tab to the viewer
- see the focus dialog popup
- press `Shift + Tab`
- press `Tab` again quickly
- the viewer gets focus without the focus dialog

### PR DESCRIPTION
**Pull request by milesap**
## Description
Dialog will now correctly display when tabbing quickly

Closes #1377

## Testing
:eye: 

## Documentation
jsdoc, inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1714)

### CODE REVIEW

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/focus-manager.js, line 64 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714#-KdX1x_5r2aMDkwCbv4w:-KdX1x_5r2aMDkwCbv4x:b-ia7ru5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/057a31ca11131bfc6d6d9d2601d22c92373773cd/src/app/focus-manager.js#L64)):*
> ```JavaScript
>          * the callbacks so that the are fired in order when $mdDialog is ready.
>          *
>          * Note that dlgCB must return a promise that resolves when $mdDialg is in a ready state
> ```

Typo $mdDialog?

---

*[src/app/focus-manager.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714#-KdX25LhoIilaLHIo6zi:-KdX25LhoIilaLHIo6zj:b-ia7ru5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/057a31ca11131bfc6d6d9d2601d22c92373773cd/src/app/focus-manager.js#L66)):*
> ```JavaScript
>          * Note that dlgCB must return a promise that resolves when $mdDialg is in a ready state
>          *
>          * @param   {Function}  dlgCB       a function to be invoked when $mdDialg is ready (must return a promise)
> ```

Typo $mdDialog?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/focus-manager.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714#-KdX25LhoIilaLHIo6zi:-Kd_ny4FqUxA2fxS6kRu:b-yo9heh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/057a31ca11131bfc6d6d9d2601d22c92373773cd/src/app/focus-manager.js#L66)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo $mdDialog?
</blockquote></details>

For readability, can you rename `dlgCB` to `dialogCallback` or something like that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/focus-manager.js, line 64 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714#-KdX1x_5r2aMDkwCbv4w:-Kda5fsJyuNzbFUviHEs:b-886gsx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/057a31ca11131bfc6d6d9d2601d22c92373773cd/src/app/focus-manager.js#L64)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo $mdDialog?
</blockquote></details>

Fixed

---

*[src/app/focus-manager.js, line 66 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714#-KdX25LhoIilaLHIo6zi:-Kda5hbhuiQR3fJKj1G9:b499q7j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/057a31ca11131bfc6d6d9d2601d22c92373773cd/src/app/focus-manager.js#L66)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

For readability, can you rename `dlgCB` to `dialogCallback` or something like that?
</blockquote></details>

Changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714)*

**Comment by jolevesq** [comment]
:lgtm: in Chrome

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714#-:-Kda75ZFqGGViYPxjAca:b-vu7zbu)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1714)*

**Pull request merged**
