### PR TITLE
feat(ui): first part of the layer import ui component

### PR DESCRIPTION
**Pull request by AleksueiR**
stub test file included

:warning: sass

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/341)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Will add comments later.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-:-KApp0ELBGsYaA6zjhO8:2071276070)*

**Comment by ec-dev** [comment]
Reviewed 5 of 19 files at r1.
Review status: 5 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by spencerwahl** [comment]
Reviewed 18 of 19 files at r1.
Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 169 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KApoviRA32k3R2mY9US:-KApoviSgCyLasMg66Jc:165649747) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1619863b95022486d8b2f5cc5fa2ed1e744d5c1b/CONTRIBUTING.md#L169)):*
:+1: good work

---

*[src/app/ui/layer-loader, line 0 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KAppmFy4RLWibrgfyot:-KAppmFzbUc1ZlOqAwwo:1149883757) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1619863b95022486d8b2f5cc5fa2ed1e744d5c1b/src/app/ui/layer-loader#L0)):*
Is this supposed to be here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by alyec** [comment]
Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/statemanager.constant.service.js, line 64 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KApsAX8eUEVgcqefvvC:-KApsAX8eUEVgcqefvvD:-68012350) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/common/router/statemanager.constant.service.js#L64)):*
This reads a bit like a typo, is there a better name for this?

---

*[src/app/layout/shell.controller.js, line 33 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KApsOl21iTvVmu8Osov:-KApsOl21iTvVmu8Osow:1908049787) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/layout/shell.controller.js#L33)):*
Same as above, can we avoid the `ll`?

---

*[src/app/ui/lloader/lloader-file.html, line 42 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KAptXCcrYKaQhnPpM5k:-KAptXCcrYKaQhnPpM5l:2038416497) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/ui/lloader/lloader-file.html#L42)):*
What is this sneaky directive doing?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/layout/shell.controller.js, line 33 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KApsOl21iTvVmu8Osov:-KApuMf-m4hg800-Wwj-:1011651183) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/layout/shell.controller.js#L33)):*
Sure. Would `layerLoader` be better? Or maybe just `loader`.

---

*[src/app/ui/lloader/lloader-file.html, line 42 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KAptXCcrYKaQhnPpM5k:-KApu7GdomJyi3zlgol0:833760450) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/ui/lloader/lloader-file.html#L42)):*
I was adding fake directives to see if they look right and work correctly.

---

*[src/app/ui/layer-loader, line  \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KAppmFy4RLWibrgfyot:-KApu-lyyndzhAZ5QNK4:-621372694) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1619863b95022486d8b2f5cc5fa2ed1e744d5c1b/src/app/ui/layer-loader#L)):*
Nope. Atom didn't delete this file for some reason.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/layout/shell.controller.js, line 33 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KApsOl21iTvVmu8Osov:-KAq2eVZ6enk1XLBdGXK:-1021275507) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/layout/shell.controller.js#L33)):*
I think loader works well enough.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by ec-dev** [comment]
Reviewed 8 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by AleksueiR** [comment]
Review status: 7 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/layout/shell.controller.js, line 33 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KApsOl21iTvVmu8Osov:-KAtVL4xPbGikknLe69f:1706342937) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/layout/shell.controller.js#L33)):*
Done. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by alyec** [comment]
Reviewed 15 of 15 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by spencerwahl** [comment]
Reviewed 15 of 15 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/common/router/statemanager.constant.service.js, line 64 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341#-KApsAX8eUEVgcqefvvC:-KAuOKnZJOtrTS4Xpsmh:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b4c23209fe6a3623b7fb0603af3e057a78342e5/src/app/common/router/statemanager.constant.service.js#L64)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/341)*

**Pull request merged**
