### PR TITLE
fix(ui): truncate overflowing details values

### LINKED ISSUE #1635: "SiteOnline Resource" url for some JOSM points cuts off in the feature details Pane
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html

This issue applies to only JOSM layers so far where if a map point has longer url for siteOnlineresourceText_en/siteOnlineResource_fr, the content seems to cut off as below. Mainly seen when there is xls link. Please fix the issue

image

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Truncate overflowing details values that cannot be wrapped.
Closes #1635

http://fgpv.cloudapp.net/demo/users/AleksueiR/1635-truncate-autolinks/prod/samples/index-fgp-en.html?keys=JOSM

## Testing
Eyeballing.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ not needed
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1645)

### CODE REVIEW

**Comment by milesap** [comment]
In IE there are no ellipses, and clicking on a link shifts the link left. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645#-:-KbWDQM_QEIOgqtv5Tvc:bgfople)*

**Comment by milesap** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645)*

**Comment by AleksueiR** [comment]
WOMM in IE:


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645#-:-KbjMpMT83Xjz7FemUN0:bxwv82)*

**Comment by milesap** [comment]
:lgtm: WOMM is the golden standard

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645#-:-KbjXM1YBBPIT9H5U0kl:b-hsyjmg)*

**Comment by AleksueiR** [comment]
All links are forced into a single line and truncated with an ellipsis (even in IE):


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645#-:-Kbju-drvU02zz59PvOx:buo35kv)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645#-:-Kbk0yJopCx1Ly-67maq:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1645)*

**Pull request merged**
