### PR TITLE
Fix when filter got truncated in IE

### LINKED ISSUE #2098: Data table Search text field is truncated in IE
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily11/prod/samples/index-samples.html

image

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes #2098 
Fix when filter got truncated in IE

## Testing

Manually
## Documentation

None
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2147)

### CODE REVIEW

**Comment by AleksueiR** [comment]
The fix bring back https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1973.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2147#-:-KomYx8RZMKZ7CfnlQea:b-9thr2l)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/modules/_filters.scss, line 177 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2147#-KoqZxf3avIj1AZ3pVrQ:-KoqZxf3avIj1AZ3pVrR:ba87t34) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/102d035eb3925eacf737042dd8a18350de28b8d7/src/content/styles/modules/_filters.scss#L177)):*
> ```SCSS
>             @include include-size(rv-gt-sm) {
>                 width: 220px;
>                 -ms-flex-preferred-size: 220px;
> ```

Try not to use browser-specific prefixes. `flex-basis: 220px;` should work equally well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2147)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2147)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2147)*

**Pull request merged**
