### PR TITLE
fix not init collapse mini map

### LINKED ISSUE #1943: The collapse button for mini map does not appear when initializing
The mini map collapse button does not show up when init.  However it does show up when the base map was changed.

capture3

### PR DESCRIPTION
**Pull request by barryytm**
## Description

fixes #1943, the collapse button should appear when first loaded now.

## Testing

No, it was a UI bug.

## Documentation

NA
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1946)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/overview-toggle.directive.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1946#-Km7mwvdEcYo7C6xYutH:-Km7mwvdEcYo7C6xYutI:bbhqtmn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5cfd87fd361c8acf13890f2758c5fc6d02e0ea97/src/app/geo/overview-toggle.directive.js#L53)):*
> ```JavaScript
>         // TODO: instead of relying on esri event here, listen on it in map service and re-emit as rv-basemapchange event
>         events.$on(events.rvApiReady, () =>
>             configService.getSync.map.instance.basemapGallery.on('selection-change', init));
> ```

To simplify a bit, you can move the `init` call to the event listener you already have here:

```js
events.$on(events.rvApiReady, () => {
            init();
            configService.getSync.map.instance.basemapGallery.on('selection-change', init));
});
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1946)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1946)*

**Comment by barryytm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/overview-toggle.directive.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1946#-Km7mwvdEcYo7C6xYutH:-Km7q1t3iUMU2EXEp9Fr:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b2bac49c2821246f709ea144abfd7b05cae482f/src/app/geo/overview-toggle.directive.js#L53)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

To simplify a bit, you can move the `init` call to the event listener you already have here:

```js
events.$on(events.rvApiReady, () => {
            init();
            configService.getSync.map.instance.basemapGallery.on('selection-change', init));
});
```
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1946)*

**Comment by AleksueiR** [comment]
:lgtm: :+1: Works nicely!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1946#-:-Km7qEPFHxg9XmPCXECB:bcr4k6a)*

**Pull request merged**
