### PR TITLE
Bug roundup

### LINKED ISSUE #2232: Cancel when importing a service
When importing a service, closing the panel when the service is taking long to respond for example and reopening it shows progress for the `Continue` button but has a blank field for the service URL and eventually throws an error that the service did not respond.

saving

issue

Should be possible to cleanly cancel out of this step.

### PR DESCRIPTION
**Pull request by milesap**
## Description
fix(import): cancel when importing service issue resolved
fix(ui): space in datagrid title + geosearch option rename

Closes #2232, #2215, #1745

## Testing
eagle eyes

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2244)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/common/stepper/stepper.class.js, line 131 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp6zIN9h9MemWHzVZI:-Kpp6zIN9h9MemWHzVZJ:b30vb9z) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/app/ui/common/stepper/stepper.class.js#L131)):*
> ```JavaScript
>             const cancelPromise = $q(resolve =>
>                 (this._resolveCancelPromise = resolve)).then(() =>
>                     (isMoveCanceled = true));
> ```

Change this to `isMoveCanceled = true; this._think(currentStep, false);`. This will simple remove `isThinking` animation after canceling the move.

---

*[src/app/ui/common/stepper/stepper.class.js, line 198 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp6jm0Ce0dGseSf48R:-Kpp6jm0Ce0dGseSf48S:bm9xsex) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/app/ui/common/stepper/stepper.class.js#L198)):*
> ```JavaScript
>          * @return {Object}            itself for chaining
>          */
>         _reset(step) {
> ```

Add `this.cancelMove();` here, so the current move will be canceled when the panel is closed.

---

*[src/app/ui/loader/loader-service.directive.js, line 198 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp3IMRmjMRIcenq_xF:-Kpp3IMRmjMRIcenq_xG:b-5on8y3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/app/ui/loader/loader-service.directive.js#L198)):*
> ```JavaScript
> 
>         connect.serviceUrl = '';
>         connect.step.isThinking = false;
> ```

`isThinking` is a private var, should not be changed outside of the Stepper class.

---

*[src/locales/translations.csv, line 76 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp1WqXgWeeHdmgn2R_:-Kpp1WqXgWeeHdmgn2Ra:baohzen) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/locales/translations.csv#L76)):*
> ```CSV
> Details pane tooltip for expand button,details.tooltip.expand,Expand,1,Agrandir,1
> Details pane label for no result,details.label.noresult,Nothing found,1,Aucun résultat,1
> Details pane label for searching,details.label.searching,Searching ...,1,[fr] Searching ...,0
> ```

While you are at it, can you update missing translations? Just search for `,0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244)*

**Comment by milesap** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/common/stepper/stepper.class.js, line 131 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp6zIN9h9MemWHzVZI:-KppQIm-rPviIzmR2KBd:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/app/ui/common/stepper/stepper.class.js#L131)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Change this to `isMoveCanceled = true; this._think(currentStep, false);`. This will simple remove `isThinking` animation after canceling the move.
</blockquote></details>

:+1: 

---

*[src/app/ui/common/stepper/stepper.class.js, line 198 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp6jm0Ce0dGseSf48R:-KppQKl7cHpYLeHbNJqX:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/app/ui/common/stepper/stepper.class.js#L198)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Add `this.cancelMove();` here, so the current move will be canceled when the panel is closed.
</blockquote></details>

:+1: 

---

*[src/app/ui/loader/loader-service.directive.js, line 198 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp3IMRmjMRIcenq_xF:-KppQMLOwVrCsl7wyYmM:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/app/ui/loader/loader-service.directive.js#L198)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`isThinking` is a private var, should not be changed outside of the Stepper class.
</blockquote></details>

:+1: 

---

*[src/locales/translations.csv, line 76 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp1WqXgWeeHdmgn2R_:-KppQNml1ny7Hmrzj39z:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/locales/translations.csv#L76)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

While you are at it, can you update missing translations? Just search for `,0`.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/common/stepper/stepper.class.js, line 141 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-KppQgLO0COMZpwCIgN4:-KppQgLO0COMZpwCIgN5:b2fyn7k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41c33365c9e43a948aa27a072e226728b869ec09/src/app/ui/common/stepper/stepper.class.js#L141)):*
> ```JavaScript
>                 // when isCanceled is true we know the user canceled the step move sometime between the promise being created and it being resolved.
>                 // in any case, do not move forward when the user canceled
>                 if (!isMoveCanceled && isCanceled !== true) {
> ```

I don't think you need this anymore.

---

*[src/app/ui/loader/loader-service.directive.js, line 162 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-KppQiXeuaCcN0frxb6j:-KppQiXeuaCcN0frxb6k:bw2tdye) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41c33365c9e43a948aa27a072e226728b869ec09/src/app/ui/loader/loader-service.directive.js#L162)):*
> ```JavaScript
>                 self.layerSource = layerSourceOptions[preselectedIndex];
>                 // when isThinking is false we know the user canceled
>                 return !connect.step.isThinking;
> ```

And this as well.

---

*[src/locales/translations.csv, line 76 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp1WqXgWeeHdmgn2R_:-KppQ_ShxJB9y2PDlRPH:b-ucfknh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/locales/translations.csv#L76)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244)*

**Comment by milesap** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/stepper/stepper.class.js, line 141 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-KppQgLO0COMZpwCIgN4:-KppRN-2jlpZEXgt95c7:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41c33365c9e43a948aa27a072e226728b869ec09/src/app/ui/common/stepper/stepper.class.js#L141)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I don't think you need this anymore.
</blockquote></details>

:+1: 

---

*[src/locales/translations.csv, line 76 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-Kpp1WqXgWeeHdmgn2R_:-KppRP7qyM0dxEg1ZZCI:bfikg6n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d3eea06b9c6c2b5a4855c04eed2cb0a43dcdfce/src/locales/translations.csv#L76)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

:ballot_box_with_check: 

---

*[src/app/ui/loader/loader-service.directive.js, line 162 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-KppQiXeuaCcN0frxb6j:-KppRbuKAQyG2JU_iuhx:bevsic7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41c33365c9e43a948aa27a072e226728b869ec09/src/app/ui/loader/loader-service.directive.js#L162)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

And this as well.
</blockquote></details>

:heavy_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244)*

**Comment by AleksueiR** [comment]
:lgtm: demo works

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2244#-:-KppTU6teBAZfviGwPUX:b-1i7rd8)*

**Pull request merged**
