### PR TITLE
fix(legend): datatable icon appearing for basemaps

### LINKED ISSUE #2076: Data control flag appears for a basemap layer in the Legend Panel
Tested build :http://fgpv.cloudapp.net/demo/v2.0.0-daily10/prod/samples/index-fgp-en.html

Test data:http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBME_CBCE_HS_RO_3978/MapServer

Please turn off the data control for this layer as there is no data behind a basemap layer.

image

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2076, #2077.

## Testing
Visually tested.

## Documentation
None.

## Checklist

- [ ] commits messages follow the guidelines
- [ ] code passes unit tests
- [ ] release notes have been updated
- [ ] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2080)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Demo works :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/toc/legend-element-factory.class.js, line 240 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2080#-KnpCh9emSs_c25ZKQE6:-KnpCh9emSs_c25ZKQE7:b-j26nsj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e1ff357440509a5c83607d78a3b127a98107d739/src/app/ui/toc/legend-element-factory.class.js#L240)):*
> ```JavaScript
> 
>         get isVisible () {
>             return super.isVisible && this.block.featureCount !== -1;
> ```

Maybe add some comments what these overrides do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2080#-:-KnpCg1Na5e-dfjroG9N:b-da8nlq)*

**Comment by JahidAhmed** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/legend-element-factory.class.js, line 240 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2080#-KnpCh9emSs_c25ZKQE6:-KnpHLUhOhFd3TmVz6qw:b-7smv2g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e1ff357440509a5c83607d78a3b127a98107d739/src/app/ui/toc/legend-element-factory.class.js#L240)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Maybe add some comments what these overrides do.
</blockquote></details>

Added, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2080)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2080)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2080)*

**Pull request merged**
