### PR TITLE
fix(ui): remove hovertip on highlight

### LINKED ISSUE #1604: Hovertips fight with Highlighter
Our feature highlighter masks the map.  Currently, two things happen when a highlight appears and the map has hovertip layers

* If a hovertip was active when the highlight is applied, the `mouse-out` event on the hovertip graphic does not trigger.  This results in the hovertip never disappearing until the user changes the scale level.
* When highlight is active, no features can trigger a hovertip. This is because the haze polygon is on top of everything and blocks any mouse events to the stuff under it.

## Short Term Solutions

* Change default config setting for hovertips to `false`. This means tips are available to custom implementers, but the catalog site / RCS sources will have them off (and this might be a good thing; else we will have catalog maps where only some layers have hover tips, or we need to modify RCS to explicitly set the tips to OFF for all registrations)
* Add code to clear any hovertips whenever a highlight is requested. This will solve the hovertip that never leaves.

## Long Term Solutions

* Implement the Alex highlighting approach.  It gets rid of the haze polygon. See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/820
* Implement hover events on highlight layer as well to enable hover on highlights (RAMP1 did a similar approach...need to link graphics in highlight layer to their source graphic)

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1604

## Testing
:eye: 

## Documentation
jsdoc

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1713)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/tooltip/tooltip.service.js, line 438 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1713#-KdWVSjm23mLAXdsFYVN:-KdWVSjm23mLAXdsFYVO:bjti2tn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b09a82568789e33942f4057d6b3159b435aca620/src/app/ui/tooltip/tooltip.service.js#L438)):*
> ```JavaScript
> 
>         /**
>          * Removes an existing hover tooltip if one exitis, otherwise does nothing.
> ```

typo: exists

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1713)*

**Comment by milesap** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/tooltip/tooltip.service.js, line 438 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1713#-KdWVSjm23mLAXdsFYVN:-KdWcKS4dbqn6h-wASv1:b-ybs2wb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b09a82568789e33942f4057d6b3159b435aca620/src/app/ui/tooltip/tooltip.service.js#L438)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: exists
</blockquote></details>

Fixed typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1713)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1713)*

**Comment by jolevesq** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1713)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1713#-:-Kd_jCS4D-dbtMcs8GgX:bnfp4nl)*

**Pull request merged**
