### PR TITLE
fix(ui): Datagrid breaks if rapidly opened and closed

### LINKED ISSUE #896: Datagrid breaks if rapidly opened and closed
image

image

### PR DESCRIPTION
**Pull request by jolevesq**
Use a debounce function like in #895

Closes #896

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1154)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1154)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/toc/toc.service.js, line 191 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1154#-KR8Xm77J4BI9OWMPOTZ:-KR8Xm78beEr8Qozjw-G:b-u6vmfr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/215c271d687227316029325ebc9f12e235cd8490/src/app/ui/toc/toc.service.js#L191)):*
> ```JavaScript
> 
>         // debounce toggle filter function
>         const debToggleFilter = debounceService.registerDebounce(debToggleLayerFiltersPanel, 175);
> ```

Tiny improvement - feel free to ignore: make 175 a default value in the `registerDebounce` function, so we don't need to specify it all the time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1154#-:-KR8Y66g8SmluKGP_PZX:bnfp4nl)*

**Comment by jolevesq** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 191 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1154#-KR8Xm77J4BI9OWMPOTZ:-KR8hSkqGoC2gdbubHzW:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/215c271d687227316029325ebc9f12e235cd8490/src/app/ui/toc/toc.service.js#L191)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Tiny improvement - feel free to ignore: make 175 a default value in the `registerDebounce` function, so we don't need to specify it all the time.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1154)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1154)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1154)*

**Pull request merged**
