### PR TITLE
fix(core): fix null/undefined errors in picture formatter

### LINKED ISSUE #2239: Error hovering over symbols for Air Ozone layer
Possibly related to #2225.

After clicking on one of the symbols (the ones identified in the legend, not the `Nature` symbols) on the map for the `Air Ozone` layer, the `Feature Details` panel opens.

While the panel is open, hovering onto or out of any of these symbols described above or any clickable item (for example any of the buttons) results in the following error:

capture

Note: Only happens for this layer, none of the others result in this error.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Adds a more robust checking to picture formatter.

Closes #2239

## Testing
Eyeballs.

## Documentation
Nope.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2290)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2290)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/core/formatters.filter.js, line 114 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2290#-KqU3FfakXVtiKSlpsdz:-KqU3FfakXVtiKSlpse-:b-7ikw43) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/51e11c29346227a00d7e59cf59022fd742bae645/src/app/core/formatters.filter.js#L114)):*
> ```JavaScript
>          */
>         function stringify(str) {
>             if (typeof str === 'undefined' || str === null) {
> ```

Wouldn't `!str` be better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2290)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/formatters.filter.js, line 114 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2290#-KqU3FfakXVtiKSlpsdz:-KqU3qFxqfmXrtuIYQRq:brl4meh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/51e11c29346227a00d7e59cf59022fd742bae645/src/app/core/formatters.filter.js#L114)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Wouldn't `!str` be better?
</blockquote></details>

I wish it would. Unfortunately, this will give you wrong results for the number `0` and boolean`false`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2290)*

**Comment by barryytm** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2290)*

**Pull request merged**
