### PR TITLE
CESI: Ability to remove layers for indicator selector

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
For CESI: Remove layers after map has been instantiated 

## Testing
Visually tested

## Documentation
JSDoc, Comments

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2513)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 259 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513#-L-leRkRw4eTQHf5cVug:-L-leRkRw4eTQHf5cVuh:bl1fvn7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/231437670cb819534bb15e95d95a947e3adf5ab3/src/app/core/config.service.js#L259)):*
> ```JavaScript
>                     });
> 
>                     layerRecords = [];
> ```

why are we setting local vars after they are done?  does this do pointer smashing and really updates the `map.xxx` property?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513)*

**Comment by JahidAhmed** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 259 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513#-L-leRkRw4eTQHf5cVug:-L-loz4coxyVem92Co9t:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/231437670cb819534bb15e95d95a947e3adf5ab3/src/app/core/config.service.js#L259)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

why are we setting local vars after they are done?  does this do pointer smashing and really updates the `map.xxx` property?
</blockquote></details>

done thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513)*

**Comment by james-rae** [comment]
Worth noting, this approach is a temporary measure for CESI.  Once the new API is completed, that will be the preferred approach for manipulating map layers from outside the viewer, and this code will be nuked.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513#-:-L-lr2-AacV21-F18oJg:brd13vg)*

**Comment by barryytm** [comment]
Perhaps we can create a separate branch for this commit if this will be nuked after the API is finished?

**Comment by dan-bowerman** [comment]
Perfectly fine by me. I don't intend for CESI to go past version 2.1 anytime in the near-to-medium term, and already have the hacky stuff to prevent objectID and Symbol fields to be omitted to add back in once Dev is updated with this PR.

**Comment by AleksueiR** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/config.service.js, line 241 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513#-L-rO29zmk9RyR6xCiNR:-L-rO29zmk9RyR6xCiNS:b4yqysq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0a107bd7969457ac7a12ab24a35066b2aa45d574/src/app/core/config.service.js#L241)):*
> ```JavaScript
>          * @function resetMap
>          */
>         resetMap() {
> ```

Can you reuse this reset function: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/core/config.class.js#L1879 ? It's missing removing bounding boxes, but that can be added easily.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/config.service.js, line 241 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513#-L-rO29zmk9RyR6xCiNR:-L-rOeZCmzxfwyrMUusy:bj0x04a) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0a107bd7969457ac7a12ab24a35066b2aa45d574/src/app/core/config.service.js#L241)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you reuse this reset function: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/core/config.class.js#L1879 ? It's missing removing bounding boxes, but that can be added easily.
</blockquote></details>

I initially tried to use the already existing reset function however that threw multiple errors and resulted in no layers being added afterwards (I think because the map instance and legend blocks were set to null)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/config.service.js, line 241 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513#-L-rO29zmk9RyR6xCiNR:-L-rQ0Hf09leSxTPYil9:b-ksy7tv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0a107bd7969457ac7a12ab24a35066b2aa45d574/src/app/core/config.service.js#L241)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

I initially tried to use the already existing reset function however that threw multiple errors and resulted in no layers being added afterwards (I think because the map instance and legend blocks were set to null)
</blockquote></details>

Hm, okay. I don't really like the idea of two almost identical functions though...

Maybe this one can be moved to the config.class.js file, so you can avoid adding setters to the layer records and others. Also, add a comment somewhere that this is temporary until API is complete. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2513)*

**Comment by JahidAhmed** [comment]
Going to close this as CESI dev site was already updated and this temp code will not be going in `develop`. Will make changes mentioned above (if necessary) and see whether we need to open a new PR pointing to a different branch (again; if necessary).

**Pull request closed without merging**
