### PR TITLE
fix(bookmark): not able to reopen group after removing a sublayer and…

### LINKED ISSUE #1611: Expand layers not working after removed one sub-layer and then applied "Back To Cart"
Tested build http://fgpv.cloudapp.net/demo/v1.5.0-14/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

-  Removed one sub-layer for any layers with multiple sub-layers, for example Mercury emissions sub-layer under CESI: Other Air Indicators
-  Click "Back to Cart"
-  Click Expand Groups to expand all layers

No sub-layer displayed under CESI: Other Air Indicators, even the chevron is in expand status.

image

### PR DESCRIPTION
**Pull request by jolevesq**
… did Back to Cart

Closes #1611

## Description

#1611 

## Testing

Chrome, FF and Safari

tested with those layers index-fgp-en.html?keys=EcoNest,EcoAction

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1627)

### CODE REVIEW

**Comment by james-rae** [comment]
*[src/app/core/bookmark.service.js, line 732 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627#-KbL6aY-tb4tgG8KRy1Z:-KbL6aY-tb4tgG8KRy1_:biuiyi0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/01a4b41b65aa140ee6eed03659d224982ced7695/src/app/core/bookmark.service.js#L732)):*
> ```JavaScript
>                             if (!angular.equals(cfg.layerEntries, rcsBookmarks[cfg.id].layerEntries) &&
>                                 merge.layerType === 'esriDynamic') {
>                                 merge.layerEntries = rcsBookmarks[cfg.id].layerEntries;
> ```

You might also need to handle the `childOptions` array property too.  You can trigger this property by having dynamic layers with nested children.  This service can provide a simple example - `http://section917.cloudapp.net/arcgis/rest/services/TestData/Nest/MapServer`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/bookmark.service.js, line 732 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627#-KbL6aY-tb4tgG8KRy1Z:-KbL91a73lNm7bAE-Txo:berkdrd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/01a4b41b65aa140ee6eed03659d224982ced7695/src/app/core/bookmark.service.js#L732)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

You might also need to handle the `childOptions` array property too.  You can trigger this property by having dynamic layers with nested children.  This service can provide a simple example - `http://section917.cloudapp.net/arcgis/rest/services/TestData/Nest/MapServer`
</blockquote></details>

Will take a look. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/core/bookmark.service.js, line 731 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627#-KbLDcqvyixLgYwT7FoZ:-KbLDcqwcWx65wDC9Lts:b-uctxm1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/01a4b41b65aa140ee6eed03659d224982ced7695/src/app/core/bookmark.service.js#L731)):*
> ```JavaScript
>                             // https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1611
>                             if (!angular.equals(cfg.layerEntries, rcsBookmarks[cfg.id].layerEntries) &&
>                                 merge.layerType === 'esriDynamic') {
> ```

I will push a new version with Geo.Layer.Types.ESRI_DYNAMIC

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by james-rae** [comment]
*[src/app/core/bookmark.service.js, line 732 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627#-KbL6aY-tb4tgG8KRy1Z:-KbLHFXVY9vkW2HRXwvB:bfo8hw8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/01a4b41b65aa140ee6eed03659d224982ced7695/src/app/core/bookmark.service.js#L732)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Will take a look. Thanks
</blockquote></details>

Better sample: RCS key `EcoNest` has index `5` in `layerEntries`, and when bookmarked will have the four subchildren (`6, 7, 8, 9`) in `childOptions`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/core/bookmark.service.js, line 732 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627#-KbL6aY-tb4tgG8KRy1Z:-KbRId5rmhfAIC8owhDK:b8xbbqw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/01a4b41b65aa140ee6eed03659d224982ced7695/src/app/core/bookmark.service.js#L732)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Better sample: RCS key `EcoNest` has index `5` in `layerEntries`, and when bookmarked will have the four subchildren (`6, 7, 8, 9`) in `childOptions`
</blockquote></details>

Child option does nothing. The difference is in the result. For nested elements they are not removed. Only the first level in the group his (first group Climate change is still there after back to cart even if it was remove)



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by james-rae** [comment]
*[src/app/core/bookmark.service.js, line 732 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627#-KbL6aY-tb4tgG8KRy1Z:-KbRbkuGc_PIQGR0ZYhj:b-38vzs2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/01a4b41b65aa140ee6eed03659d224982ced7695/src/app/core/bookmark.service.js#L732)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Child option does nothing. The difference is in the result. For nested elements they are not removed. Only the first level in the group his (first group Climate change is still there after back to cart even if it was remove)



</blockquote></details>

As discussed -- Currently, the bookmark was made to track information changed about nested children (e.g. someone turns off visibility, changes opacity). As the legend builds itself, it checks if each child has extra config data and updates itself. What the legend builder doesn't do is use the config to determine if children are erased or not. We still use the logic of "things in `layerEntries` determine what is in the legend, and we include all children under them". The ability to have children pre-deleted is not considered in the legend generator. Suggest not implementing that until after the refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by james-rae** [comment]
*[src/app/core/bookmark.service.js, line 731 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627#-KbLDcqvyixLgYwT7FoZ:-KbRcBZFo2PyqMLSaqOv:b-vs1pr4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/01a4b41b65aa140ee6eed03659d224982ced7695/src/app/core/bookmark.service.js#L731)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I will push a new version with Geo.Layer.Types.ESRI_DYNAMIC
</blockquote></details>

Looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1627)*

**Pull request merged**
