### PR TITLE
fix(legend): safari svg symbol doesn't render

### LINKED ISSUE #1671: Safari- Missing Symbology and wrong placement of right side menu
Tested build :http://fgpv.cloudapp.net/demo/v1.5.0-rc2/prod/samples/index-fgp-en.html?keys=EcoAction

image

Device Info

image

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1671

## Description

The problem append again because now safari use NS1:href not just href

## Testing

Safari and Chrome

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1854)

### CODE REVIEW

**Comment by AleksueiR** [comment]
In browser stack, legend symbology renders only in the layer selector, not in the datatable (Sierra with Safari 10):


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-:-KiALdcQ79O1SzbT0n4x:b-mli0di)*

**Comment by jolevesq** [comment]
It is because of the same thing. Symbology is added with ns1:href. I will chck why it doesn't go trough the svg directive.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-:-KiAUFtpJdeKf5xZY2WB:b72dmmg)*

**Comment by jolevesq** [comment]
The symbol is added tot he table in ```toc.service.js``

```
row.rvSymbol = geoService.retrieveSymbol(row, attributes.renderer);
```
It never goes trough svg.directive.js. I will try to make it go inside

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-:-KiAWHDPepc39mNAxuMe:b-onw0t6)*

**Comment by AleksueiR** [comment]
Yes, they are injected directly to improve performance.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-:-KiBG88g59oCzT5On3o0:bte0ds3)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 387 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-KiGehPt9BPMIu2b45B5:-KiGehPuB7v15Z4brnH-:b-fcf1hp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaaabe2465ca0551e8503ee945682b17220c1539/src/app/ui/toc/toc.service.js#L387)):*
> ```JavaScript
>                     if (!attributes.columns.find(({ data }) => data === rvSymbolColumnName)) {
> 
>                         const scope = $rootScope.$new();
> ```

This is going to slow the datatable down; it's already somewhat slow because we are adding to button directives there. Adding a third directive for the icon will be slower still. 

`geoService.retrieveSymbol(row, attributes.renderer)` returns simple string, right? So you can do a straight replacement on it without compiling it. 
Maybe it makes sense to move the logic replacing 'NS1:href' with 'xlink:href' into a helper function. You can add it to the `graphics.service.js` file which already has some graphics helper functions and reference it from here and from the `rvSvg` directive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 387 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-KiGehPt9BPMIu2b45B5:-Ki_E-5O5L0hme5F-kZ6:be95ouy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaaabe2465ca0551e8503ee945682b17220c1539/src/app/ui/toc/toc.service.js#L387)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This is going to slow the datatable down; it's already somewhat slow because we are adding to button directives there. Adding a third directive for the icon will be slower still. 

`geoService.retrieveSymbol(row, attributes.renderer)` returns simple string, right? So you can do a straight replacement on it without compiling it. 
Maybe it makes sense to move the logic replacing 'NS1:href' with 'xlink:href' into a helper function. You can add it to the `graphics.service.js` file which already has some graphics helper functions and reference it from here and from the `rvSvg` directive.
</blockquote></details>

Yes it is a string replacement. I agree with you compile will slow down. I wanted to have all the svg modification at the same place. I will create the replacement function that will be call by the directive and the toc loading so we have the fix only at one place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854)*

**Comment by jolevesq** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 387 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-KiGehPt9BPMIu2b45B5:-Ki_QOnm6iBh3xMi4z4D:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aaaabe2465ca0551e8503ee945682b17220c1539/src/app/ui/toc/toc.service.js#L387)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes it is a string replacement. I agree with you compile will slow down. I wanted to have all the svg modification at the same place. I will create the replacement function that will be call by the directive and the toc loading so we have the fix only at one place.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854)*

**Comment by AleksueiR** [comment]
:lgtm: Works in IE 14, Firefox, and Safari on browserstack.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854#-:-KikWyMstYcqAm2lOdVt:b-csoud8)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3, 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1854)*

**Pull request merged**
