### PR TITLE
fix(api): identify buffer size and layer queryable

### LINKED ISSUE #2600: API: add option to change the identify buffer size at runtime
The identify buffer size is set by geoApi, and cannot be changed. An API option is needed to set the buffer size at runtime.

## Use Case
CIP needs to highlight a CMIP5 grid cell (grid layer is loaded as Dynamic) on a click, and the identify results can include multiple cells (based on the buffer size) if the click was made directly on a cell's border. Reducing the buffer size to the minimum helps to limit the number of cases where the identify results must be discarded by the host page as described in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2595.

### LINKED ISSUE #2684: Identify Results - Fields vs Aliases
Our identify functions return individual results in "Details" form. This is an array of key-value pairs, where the key is the Alias of the field (field name if there was no alias).
This made sense in the original RAMP where the identify result was only used to populate the Details pane.

Now that the identify results are also available through the API, we have noticed it can be useful to know the field name instead of the alias name.

Example of current result 

```text
{
  data: [
    {
      name: "Kittyland",
      oid: 1,
      symbology: [<graphic>],
      data: [
        {
          key: "Place Name",
          value: "Kittyland",
          type: "esriString"
        },
        {
          key: "oid",
          value: 1,
          type: "esriOIDField"
        },
        {
          key: "Place Rating",
          value: "Fantastic",
          type: "esriString"
        }
      ]
    }
  ],
  <other properties>
}
```

### Idea 1 - Add Fieldname Field to Details Element

We add the field names to the individual results.  Makes the information very easy to access when working with it. Will duplicate field names for each hit on a layer, making object larger (meh?).

```text
{
  data: [
    {
      name: "Kittyland",
      oid: 1,
      symbology: [<graphic>],
      data: [
        {
          key: "Place Name",
          value: "Kittyland",
          field: "place_name",
          type: "esriString"
        },
        {
          key: "oid",
          value: 1,
          field: "oid",
          type: "esriOIDField"
        },
        {
          key: "Place Rating",
          value: "Fantastic",
          field: "rating",
          type: "esriString"
        }
      ]
    }
  ],
  <other properties>
}
```

### Idea 2 - Add Alias to Fieldname Lookup in Result

We add a lookup object at the top level of the result to provide a means for looking up a field name given an alias.

```text
{
  data: [
    {
      name: "Kittyland",
      oid: 1,
      symbology: [<graphic>],
      data: [
        {
          key: "Place Name",
          value: "Kittyland",
          type: "esriString"
        },
        {
          key: "oid",
          value: 1,
          type: "esriOIDField"
        },
        {
          key: "Place Rating",
          value: "Fantastic",
          type: "esriString"
        }
      ]
    }
  ],
  fieldLookup: {
    oid: "oid",
    "Place Name": "place_name",
    "Place Rating": "rating"
  },
  <other properties>
}
```

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2600 - buffer size can be set for each layer individually
Closes #2684 - idea 1 implemented
Starts on #2603 - moved `identifyMode` to from `Map` to `LayerGroup` and added `queryable` option to `ConfigLayer` which is linked with the UI query option in settings panel

## Testing
:eyes: 

To test identify mode: 
```js
`RZ.mapInstances[0].layers.identifyMode = 'none'` // turns off identify 
`RZ.mapInstances[0].layers.identifyMode = 'details'` // turns on identify 
```

To test field name in identify result (open the logged features array and check the contained data array):
```js
RZ.mapInstances[0].layers.identify.subscribe(event => {
    event.requests.forEach((request, index) =>
        request.features.then(features =>
            console.log(features)
        )
    );
});
```

To test layer `ConfigLayer` queryable:
```js
RZ.mapInstances[0].layers.getLayersById('powerplant100mw-liquids')[0].queryable = false // turns off query option
RZ.mapInstances[0].layers.getLayersById('powerplant100mw-liquids')[0].queryable = true // turns on option to query
// updates throughout the viewer
```

To test layer buffer size:
```js
RZ.mapInstances[0].layers.getLayersById('powerplant100mw-liquids')[0].identifyBuffer = 500 // why not
// click on map near a feature
```

## Documentation
In-line comments, JSDoc

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740)

### CODE REVIEW

**Comment by james-rae** [comment]
I get the impression this changes how one sets the Identify mode in API code.
CIP is currently using this, so when we merge this we'll need to let them know how to update their code.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[api/src/layers.ts, line 221 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-LDhMGK3DZfC2Qoq6ovQ:-LDhMGK44_K1Dv3lrGBY:b8fdob2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f389d76c8c6f506f0bd4129f7f88f514f2f27765/api/src/layers.ts#L221)):*
> ```XML
>         // if the tolerance value is defined and is less than 1, set it to 1 (smallest possible value)
>         const toleranceToSet: number | undefined = tolerance && tolerance < 1 ? 1 : tolerance;
>         this._identifyBuffer = toleranceToSet;
> ```

can we add the following comment?  it's tricky to find where all the event-linked logic is. when you see this code its not obvious

`// if dynamic layer, value is spread to other children in layer-registry.service, _createApiLayer()`

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-:-LDhN_w34IVoC1gcdrCB:b-7buqav)*

**Comment by JahidAhmed** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[api/src/layers.ts, line 221 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-LDhMGK3DZfC2Qoq6ovQ:-LDks5Yb6cSj04uEXvLA:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f389d76c8c6f506f0bd4129f7f88f514f2f27765/api/src/layers.ts#L221)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can we add the following comment?  it's tricky to find where all the event-linked logic is. when you see this code its not obvious

`// if dynamic layer, value is spread to other children in layer-registry.service, _createApiLayer()`
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740)*

**Comment by dane-thomas** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740)*

**Comment by AleksueiR** [comment]
Is it possible to set the buffer size on all layers at once? If not, can we have a shortcut, so you don't have to always iterate over them?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-:-LDl8q-z5SH-NUxXE79m:b-vo5rme)*

**Comment by ShrutiVellanki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-:-LDlA87V-V19Xy6aCccc:bs8xbab)*

**Comment by JahidAhmed** [comment]
Added an option on `LayerGroup` to set buffer size for all layers together. example: `RZ.mapinstances[0].layers.setBuffer(5)`

---

Review status: 8 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-:-LDlHQxQ21L6PgLC8zBO:bauzo70)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740)*

**Comment by james-rae** [comment]
*[api/src/layers.ts, line 1025 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-LDlJA2F3VhfOCbvXxB7:-LDlJA2G1tTLiYaIyFwZ:bmab3cz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c6632480e5034703813b670379b1e153a9dd4be/api/src/layers.ts#L1025)):*
> ```XML
> 
>     /** Sets the buffer size of all layers to be used when identifying. */
>     setBuffer(tolerance: number | undefined): void {
> ```

can we rename to `setAllBuffers` or something similar?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740)*

**Comment by JahidAhmed** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[api/src/layers.ts, line 1025 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740#-LDlJA2F3VhfOCbvXxB7:-LDlKgEM7rROPum-Aobz:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c6632480e5034703813b670379b1e153a9dd4be/api/src/layers.ts#L1025)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can we rename to `setAllBuffers` or something similar?
</blockquote></details>

donethanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2740)*

**Pull request merged**
