### PR TITLE
Feature/lod

### PR DESCRIPTION
**Pull request by james-rae**
Apply level of details to map on creation.
Wait for map load (triggered by basemap) prior to adding other layers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/473)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 129 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/473#-KEppgQUAWVoajk7syni:-KEppgQUAWVoajk7synj:-1584889153) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e2e633c5eb7b1d011caa4b3d925ad07e0f212fa9/src/app/geo/map.service.js#L129)):*
It might be a bit cleaner to return a promise here, which resolves with `service` when `premMapLoad` is resolved:
```js
return preloadMap.then(() => service);
```

With this, there is no need to add another `then` in `geo.service`, keeping it nice and clean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/473)*

**Comment by james-rae** [comment]
*[src/app/geo/map.service.js, line 129 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/473#-KEppgQUAWVoajk7syni:-KEprNV-rWbO2ke86_O7:-619869148) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e2e633c5eb7b1d011caa4b3d925ad07e0f212fa9/src/app/geo/map.service.js#L129)):*
Nice, I was hoping there was a better way to structure the chain in geo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/473)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/473)*

**Comment by ec-dev** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/473)*

**Comment by cynngah** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/473)*

**Pull request merged**
