### PR TITLE
fix(filter): replace Keytable by our own keyboard navigation

### LINKED ISSUE #1896: Replace Keytable extension by our on keyboard navigation
Keytable extension has trouble with focus manager and scroller extension. It also has trouble when we reorder columns and change visibility. For all those reasons we should create our own way to navigate the table without Keytable extention.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1896

## Description

There is a lot of bugs between Keytable and Scroller extention and Focus manager.  Build our own keyboard navigation will solve this.
 
## Testing

Chrome, FF and Safari

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1898)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898)*

**Comment by AleksueiR** [comment]
Demo works :lgtm:; the PR seems to be out of sync with develop;

---

Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 424 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898#-KlTF3hPB4rFl7h5H0gV:-KlTF3hQO7Iz3eIL1k4J:blepjon) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81fa73111df43e5db5c7fb17c19f63dc6e5a2ba6/src/app/ui/filters/filters-default.directive.js#L424)):*
> ```JavaScript
> 
>                 // set current cell index when user click a cell
>                 $rootElement.find('.dataTables_scrollBody td').on('click', event => {
> ```

Two comments:
- maybe it makes sense to store a reference to `$rootElement.find('.dataTables_scrollBody')` as `self.tableBody` right after the table is made since it's being call somewhat often;
- setting events on `$rootElement.find('.dataTables_scrollBody td').on('click', callback)` will create a gazillion of handlers - one per cell; it's better to use event delegation `$rootElement.find('.dataTables_scrollBody').on('click', 'td', callback)` which creates just one event handler on the parent that is listening to events bubbling up from the cells; 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898#-:-KlTGV0bT2G0p1OgyXIA:b-mg27x9)*

**Comment by milesap** [comment]
:+1: 

---

Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898#-:-KlU-U3J4F5Q_b4MYeUj:bmeyrwp)*

**Comment by jolevesq** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 424 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898#-KlTF3hPB4rFl7h5H0gV:-KlYVrwyoWLBulju8gNf:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81fa73111df43e5db5c7fb17c19f63dc6e5a2ba6/src/app/ui/filters/filters-default.directive.js#L424)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Two comments:
- maybe it makes sense to store a reference to `$rootElement.find('.dataTables_scrollBody')` as `self.tableBody` right after the table is made since it's being call somewhat often;
- setting events on `$rootElement.find('.dataTables_scrollBody td').on('click', callback)` will create a gazillion of handlers - one per cell; it's better to use event delegation `$rootElement.find('.dataTables_scrollBody').on('click', 'td', callback)` which creates just one event handler on the parent that is listening to events bubbling up from the cells; 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898#-:-KlYWOnNfHy4P31h_Tfq:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1898)*

**Pull request merged**
