### PR TITLE
Reordering Utilities

### PR DESCRIPTION
**Pull request by alyec**
Not a complete implementation, for discussion at the moment.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/547)

### CODE REVIEW

**Comment by james-rae** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547#-KGXj9koRJs0uwAzTP9p:-KGXj9koRJs0uwAzTP9q:1859321482) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41545005994dbaf128a9f904ab18c17286ba673a/src/app/geo/layer-registry.service.js#L66)):*
comment explaining the two map stacks might be helpful to non-esri-api folk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547#-KGXj9koRJs0uwAzTP9p:-KGlGO0TWOq_q1slU78n:-1369644486) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41545005994dbaf128a9f904ab18c17286ba673a/src/app/geo/layer-registry.service.js#L66)):*
Also adding that the esri map stack is reversed compared to the legend stack, that's why `nextEntry` is actually the layer above the given legend position.

---

*[src/app/geo/layer-registry.service.js, line 62 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547#-KGlGlWjx_lSFMesDPsj:-KGlGlWjx_lSFMesDPsk:1677627908) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/069fe8c9a7fbb63050fd5d89b5ea0073d68530c6/src/app/geo/layer-registry.service.js#L62)):*
Maybe also add that only top level items in the legend are considered.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547)*

**Comment by alyec** [comment]
Assuming discussions are resolved this should be treated as a proper PR now.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547#-KGXj9koRJs0uwAzTP9p:-KGliB1fRYnwQsx_-cFn:-1118381096) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/41545005994dbaf128a9f904ab18c17286ba673a/src/app/geo/layer-registry.service.js#L66)):*
Added to top level comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547#-:-KGliEiCWpvWafXxViuL:1613580975)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/547)*

**Pull request merged**
