### PR TITLE
fix(ui): evil snowman is neutralized

### LINKED ISSUE #2105: IE 11 - All buttons within viewer frozen after zooming out to scale 1000km/1000mi
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily12/prod/samples/index-samples.html

This issue is for Lambert projection only. All buttons in tool bar are not responding after zooming out to 1000km/1000mi, including all buttons on top of the viewer (menu, Geo Search, legend, bookmark, etc.)

image

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
@JahidAhmed had found that IE was chocking on drawing the snowman svg icon (zoom out too far, and the north poll comes into view). The icon is fixed; snowman, defanged.

Closes #2105

## Testing
Beholder 

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[] release notes have been updated~~ unreleased bug
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2174)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
:lgtm: Nice fix

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2174#-:-Kowy8jRkefhC4o5VJCf:b-g69qxr)*

**Comment by barryytm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2174#-:-KowzAJpH3csrzQn8jyW:bnfp4nl)*

**Comment by barryytm** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2174)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2174)*

**Pull request merged**
