### PR TITLE
Default behaviour when no config is provided 

### LINKED ISSUE #754: Behaviour when no config file is present
@ChrisLatRNCan brought up a very good point that, right now, we require a config file for the viewer to load at all.

We should probably allow the viewer to start when there is no config attribute; choosing a default basemap, default starting language, only rcs and user added layers.

Questions:
- Is there a good case for not having a default state?
- What to do for default basemaps? Supply a list or just use the blank basemap
- Anything else we have to worry about a default for?

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #754

## Testing

:eyes:
Config `67. Map with no config provided` in index-samples

## Documentation

in-line commenting

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743)

### CODE REVIEW

**Comment by james-rae** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/app/core/config.service.js, line 149 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDljLVQAP4tJyroTXZ1:-LDljLVQAP4tJyroTXZ2:bqzr3wc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44b0362dd619d12cf310228d24569ec21f1eaa9f/src/app/core/config.service.js#L149)):*
> ```JavaScript
>             {
>               "id": "baseNrCan",
>               "name": "Canada Base Map - Transportation (CBMT)",
> ```

shorten to `Canada Base Map` then add a ` / ` and add the french name after it?

---

*[src/app/core/config.service.js, line 150 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDljRcQ8f7A7rwEt5KM:-LDljRcQ8f7A7rwEt5KN:b-byjvm3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44b0362dd619d12cf310228d24569ec21f1eaa9f/src/app/core/config.service.js#L150)):*
> ```JavaScript
>               "id": "baseNrCan",
>               "name": "Canada Base Map - Transportation (CBMT)",
>               "description": "The Canada Base Map - Transportation (CBMT) web mapping services of the Earth Sciences Sector at Natural Resources Canada, are intended primarily for online mapping application users and developers.",
> ```

Shorten and combine with french?

---

*[src/app/core/config.service.js, line 151 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDljErp7zhcfGsW-MuY:-LDljErp7zhcfGsW-MuZ:bmrdp71) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44b0362dd619d12cf310228d24569ec21f1eaa9f/src/app/core/config.service.js#L151)):*
> ```JavaScript
>               "name": "Canada Base Map - Transportation (CBMT)",
>               "description": "The Canada Base Map - Transportation (CBMT) web mapping services of the Earth Sciences Sector at Natural Resources Canada, are intended primarily for online mapping application users and developers.",
>               "altText": "altText - The Canada Base Map - Transportation (CBMT)",
> ```

remove `altText - `.  no idea why that is in our other configs as well.

---

*[src/app/core/config.service.js, line 479 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDlj6ZzCGa72nefuxq0:-LDlj6ZzCGa72nefuxq1:bbljtl3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44b0362dd619d12cf310228d24569ec21f1eaa9f/src/app/core/config.service.js#L479)):*
> ```JavaScript
>             // convert DEFAULT_CONFIG to string so config parsing logic can stay the same
>             configAttr = JSON.stringify(DEFAULT_CONFIG);
>             languages = ['en-CA'];
> ```

can we make copies of `DEFAULT_CONFIG` and then just adjust the language property?  combined with comments above for basemap langague

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743)*

**Comment by dane-thomas** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/core/config.service.js, line 149 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDljLVQAP4tJyroTXZ1:-LDmMsSEBvEmAYcmRKQm:bn3r4b) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ef68a8dc7624830656d2e7c94c0b47258eb427aa/src/app/core/config.service.js#L149)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

shorten to `Canada Base Map` then add a ` / ` and add the french name after it?
</blockquote></details>

Not done; See below

---

*[src/app/core/config.service.js, line 150 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDljRcQ8f7A7rwEt5KM:-LDmMvDo19YcyT16l8Ky:bn3r4b) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ef68a8dc7624830656d2e7c94c0b47258eb427aa/src/app/core/config.service.js#L150)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Shorten and combine with french?
</blockquote></details>

Not done; See below

---

*[src/app/core/config.service.js, line 151 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDljErp7zhcfGsW-MuY:-LDmMqYe0sUDS6Fm8YRc:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ef68a8dc7624830656d2e7c94c0b47258eb427aa/src/app/core/config.service.js#L151)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

remove `altText - `.  no idea why that is in our other configs as well.
</blockquote></details>

done thanks

---

*[src/app/core/config.service.js, line 479 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDlj6ZzCGa72nefuxq0:-LDmMwMj-a0v9VSHr723:brlexfp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ef68a8dc7624830656d2e7c94c0b47258eb427aa/src/app/core/config.service.js#L479)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can we make copies of `DEFAULT_CONFIG` and then just adjust the language property?  combined with comments above for basemap langague
</blockquote></details>

Should now generate 2 default configs; One for English and one for French

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743)*

**Comment by james-rae** [comment]
*[src/app/core/config.service.js, line 150 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-LDljRcQ8f7A7rwEt5KM:-LDmp8tw9AvFB25S07zE:b-qxd5xf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ef68a8dc7624830656d2e7c94c0b47258eb427aa/src/app/core/config.service.js#L150)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

Not done; See below
</blockquote></details>

fancy!

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743#-:-LDqfuux0605lekDu2PZ:bnfp4nl)*

**Pull request merged**
