### PR TITLE
feat(ui): add option to open metadata in a dialog box

### PR DESCRIPTION
**Pull request by milesap**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/577)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/metadata/metadata-expand.directive.js, line 48 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577#-KH5vvq9zqa26DZX6mng:-KH5vvq9zqa26DZX6mnh:925820305) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/73a127cc40070af04471c39dd43736b3efd8fb38/src/app/ui/metadata/metadata-expand.directive.js#L48)):*
Instead of storing things on `scope` itself, we use `scope.self`. I think it should look something like this:

```js
controller: (display, cancel) => {
	const self = this;
		
	self.display = display;
	self.cancel = cancel;
},
locals: {
	display: stateManager.display.metadata,
	cancel: $mdDialog.cancel
},
templateUrl: 'app/ui/metadata/metadata-modal.html',
clickOutsideToClose: true,
escapeToClose: true,
controllerAs: 'self',
bindToController: true

```

And the `metadata-modal.html` template will than use `self.cancel()` and `{{ self.display.requester.name }}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Comment by alyec** [comment]
Reviewed 12 of 13 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/metadata/metadata-modal.html, line 2 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577#-KHFxtA53G_xn5Mwt8iw:-KHFxtA6EmGvp4Hogm8e:-1503436525) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490ebfa13d39a53fac5cb65767880ce8629b1edd/src/app/ui/metadata/metadata-modal.html#L2)):*
Add a TODO for translation of Metadata.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Comment by spencerwahl** [comment]
Reviewed 10 of 13 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/metadata/metadata-expand.directive.js, line 48 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577#-KH5vvq9zqa26DZX6mng:-KHPHfi15o0byzmC4zoW:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/73a127cc40070af04471c39dd43736b3efd8fb38/src/app/ui/metadata/metadata-expand.directive.js#L48)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of storing things on `scope` itself, we use `scope.self`. I think it should look something like this:
> 
> ```js
> controller: (display, cancel) => {
> 	const self = this;
> 		
> 	self.display = display;
> 	self.cancel = cancel;
> },
> locals: {
> 	display: stateManager.display.metadata,
> 	cancel: $mdDialog.cancel
> },
> templateUrl: 'app/ui/metadata/metadata-modal.html',
> clickOutsideToClose: true,
> escapeToClose: true,
> controllerAs: 'self',
> bindToController: true
> 
> ```
> 
> And the `metadata-modal.html` template will than use `self.cancel()` and `{{ self.display.requester.name }}`.</details>
complete

---

*[src/app/ui/metadata/metadata-modal.html, line 2 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577#-KHFxtA53G_xn5Mwt8iw:-KHPHjScwIDeneqsETZ5:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490ebfa13d39a53fac5cb65767880ce8629b1edd/src/app/ui/metadata/metadata-modal.html#L2)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Add a TODO for translation of Metadata.</details>
complete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/577)*

**Pull request merged**
