### PR TITLE
rebinds query legend control and flag ui components

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Rebinds query toggle and query legend flag.

## Testing
Eyeballs.

## Documentation
Inline comments;

## Checklist

- ~[ ] commits messages follow the guidelines~ nope
- [x] code passes unit tests
- ~[ ] release notes have been updated~ not needed
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1885)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885#-KkGXCQJmzfCRW-orKam:-KkGXCQJmzfCRW-orKan:b-b44lrk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d25f1e5f7c11df75cbe327ea95298b38288e1d78/src/app/geo/geo.service.js#L61)):*
> ```JavaScript
>             setFullExtent() {
>                 // TODO: check if this is true:
>                 // basemap extent should have the same projection as the map, so there is no need to reproject it and pass through `enhanceConfigExtent`
> ```

I believe `enhanceConfigExtent` not only reprojects but also converts the JSON config data into a full ESRI Extent object which is needed for `setExtent`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885#-KkGXCQJmzfCRW-orKam:-KkGYG9sFLEvzKwOIuA3:bgukr44) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d25f1e5f7c11df75cbe327ea95298b38288e1d78/src/app/geo/geo.service.js#L61)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

I believe `enhanceConfigExtent` not only reprojects but also converts the JSON config data into a full ESRI Extent object which is needed for `setExtent`.
</blockquote></details>

`configService.getSync.map.selectedBasemap.full` is already a full ESRI Extent object. It's converted by the typed config on initial parsing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885#-KkGXCQJmzfCRW-orKam:-KkGYhxLbhPd-Sl122yk:bgm0mzt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d25f1e5f7c11df75cbe327ea95298b38288e1d78/src/app/geo/geo.service.js#L61)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`configService.getSync.map.selectedBasemap.full` is already a full ESRI Extent object. It's converted by the typed config on initial parsing.
</blockquote></details>

Here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/geo4/src/app/core/config.class.js#L692

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 61 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885#-KkGXCQJmzfCRW-orKam:-KkH9TIbOWJ6R49vIbTo:bm0h2gf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d25f1e5f7c11df75cbe327ea95298b38288e1d78/src/app/geo/geo.service.js#L61)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/geo4/src/app/core/config.class.js#L692
</blockquote></details>

First, an update to geoApi is needed - the map wrapper expects the extent to be an esri object at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1885)*

**Pull request merged**
