### PR TITLE
feat(ui): toggle layers/groups (basic)

### PR DESCRIPTION
**Pull request by AleksueiR**
Will need more work to toggle dynamic layers and their children, but good enough for now (I hope).

No tests yet.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/298)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/vendor/_esri.scss, line 240 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298#-KA160r-_Ski2IxaVA8n:-KA160r-_Ski2IxaVA8o:-12448698) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e01efea814f76ae133a56fa56987f219b66f63b6/src/content/styles/vendor/_esri.scss#L240)):*
if we are commenting out all of this do we still need it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/vendor/_esri.scss, line 240 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298#-KA160r-_Ski2IxaVA8n:-KA16YRXtHUUwuq2sFp_:-554418062) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e01efea814f76ae133a56fa56987f219b66f63b6/src/content/styles/vendor/_esri.scss#L240)):*
Probably now, I left it as a reference for now; will remove when I'm satisfied with how overview map is displayed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/298)*

**Pull request merged**
