### PR TITLE
Integrate on demand attribute loading: Part I

### PR DESCRIPTION
**Pull request by AleksueiR**
Integrating geoApi changes from fgpv-vpgb/geo#105 originating in #522.

Relates to #537.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/567)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 192 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGs2_GFmizDD1V_TT5D:-KGs2_GFmizDD1V_TT5E:-1262693389) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d00c94bc0fcfe5b0fc21c51469ecd9c3f9fc358/src/app/geo/identify.service.js#L192)):*
We have this line repeated in all three `identify*` functions.  Wouldn't it make sense to refactor this a bit?  Error handling is also fairly similar across the board.  We could probably have a generic `identify` pulled either into its own function or have a structure more like:
```js
layerRegistry.getAllQueryableLayerTypes().map(layer =>
  return genericStuff(layer).then(typeSpecificHandler[layer.type]);
```

---

*[src/app/geo/identify.service.js, line 261 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGs2AMWzKrOdN7MWxTm:-KGs2AMWzKrOdN7MWxTn:-1824940400) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d00c94bc0fcfe5b0fc21c51469ecd9c3f9fc358/src/app/geo/identify.service.js#L261)):*
Styling: can we make this so the promise is set above the return and the return statement becomes a single line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by spencerwahl** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by james-rae** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by AleksueiR** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 192 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGs2_GFmizDD1V_TT5D:-KGweeI6IJAxfUNmS1xi:1245977388) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d00c94bc0fcfe5b0fc21c51469ecd9c3f9fc358/src/app/geo/identify.service.js#L192)):*
Done, although I couldn't get rid of that particular line.

---

*[src/app/geo/identify.service.js, line 261 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGs2AMWzKrOdN7MWxTm:-KGwet-0QsdkO2dC_ztF:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8d00c94bc0fcfe5b0fc21c51469ecd9c3f9fc358/src/app/geo/identify.service.js#L261)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 105 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGwhBtUINEzs8e6BzP3:-KGwhBtVBXIAip3bCG2D:-936037365) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b16f7cf6112c1acbdd7606670890bbeaddc6186f/src/app/geo/layer-registry.service.js#L105)):*
typo: recrods -> records

on the line below as well

---

*[src/app/geo/layer-registry.service.js, line 115 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGwhJcz8s7Q8UZu-va0:-KGwhJcz8s7Q8UZu-va1:-1035544618) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b16f7cf6112c1acbdd7606670890bbeaddc6186f/src/app/geo/layer-registry.service.js#L115)):*
more recrods

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by AleksueiR** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 105 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGwhBtUINEzs8e6BzP3:-KGwje_ip3iiTNvUwvla:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b16f7cf6112c1acbdd7606670890bbeaddc6186f/src/app/geo/layer-registry.service.js#L105)):*
Done.

---

*[src/app/geo/layer-registry.service.js, line 115 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGwhJcz8s7Q8UZu-va0:-KGwjeQY-xrY1o5Ast99:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b16f7cf6112c1acbdd7606670890bbeaddc6186f/src/app/geo/layer-registry.service.js#L115)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 32 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGwshny0SG1wVzbLI_E:-KGwshny0SG1wVzbLI_F:-1790437386) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/259a96e160efa467e5d4f1f11944affd216da227/src/app/geo/identify.service.js#L32)):*
Based on our discussion: use a constructor function to avoid the extra init call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 32 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567#-KGwshny0SG1wVzbLI_E:-KGwukFESGE6rGCuUP5t:-1960621882) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/259a96e160efa467e5d4f1f11944affd216da227/src/app/geo/identify.service.js#L32)):*
Can we postpone this until we start using es6 classes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/567)*

**Pull request merged**
