### PR TITLE
fix(bootstrap): loading in correct order

### PR DESCRIPTION
**Pull request by milesap**
## Description
- fixes import ordering issue between `bootstrap` and `app-seed`
- adds warning to all new API files - only use core devs should be using it now
- Implements webpack tooling to help identify code and dependencies we can remove/change to decrease overall bundle size. See the readme for instructions.

## Testing
WOMM

## Documentation
Yes

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2564)

### CODE REVIEW

**Comment by milesap** [comment]
Init map through API working, link: http://fgpv.cloudapp.net/demo/users/milesap/fix-bootstrap-api/dev/samples/api.html

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2564#-:-L3nca8nCZC1j1OKj6kj:b9p0pdi)*

**Comment by spencerwahl** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2564)*

**Comment by james-rae** [comment]
Excellent ASCII art

---

Reviewed 14 of 14 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2564#-:-L3nhwMUDZlNZKFgxai7:b-b82ke3)*

**Comment by AleksueiR** [comment]
:lgtm: 

Do we want to handle IE polyfills (the SVG one) in a separate issue? 

---

Reviewed 14 of 14 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2564#-:-L3nmViZYp7xzLtYE4mj:bktz39g)*

**Comment by milesap** [comment]
Good to merge, SVG can be separate PR

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2564#-:-L3nqAsnVBzZVgxOB78Y:b-14ynyl)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2564#-:-L40xXvKt4DG0-3ibtee:bnfp4nl)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2564)*

**Pull request merged**
