### PR TITLE
Correctly update datatable header and size

### LINKED ISSUE #1974: Datatable header does not update properly
The header of the data panel seems to get stuck after switching the data source several times and will not update properly.

datatable_name_stuck

Notice how after changing to `my custom title` the header doesn't change even after closing the panel and opening it again. Closing the panel should have cleared all data from the display manager.

Affects latest develop: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #1974.
Also stores layers previous datatable size and reloads to that size instead of default size.

## Testing
Visually tested.

## Documentation
None.

## Checklist

- [ ] commits messages follow the guidelines
- [ ] code passes unit tests
- [ ] release notes have been updated
- [ ] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2006)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/core/config.class.js, line 445 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9NgQED_XY3BSU1yaX:-Kn9NgQED_XY3BSU1yaY:b-wgd9du) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/587afbb7191ef5f558bf1218d636bffbdc722423/src/app/core/config.class.js#L445)):*
> ```JavaScript
>             this._source = source;
> 
>             this._title = source.title;
> ```

Hm, in the schema `title` defaults to `null`. It should probably default to an empty string since it's a String :) 
@alyec @james-rae @jolevesq  Is it okay to update the schema's default value in this PR, or do we want to put all schema changes in a separate PR?

---

*[src/app/core/config.class.js, line 450 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9OS6a7gJA9EBlHzPP:-Kn9OS6a7gJA9EBlHzPQ:brk76qa) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/587afbb7191ef5f558bf1218d636bffbdc722423/src/app/core/config.class.js#L450)):*
> ```JavaScript
>             this._search = source.search;
>             this._applyMap = source.applyMap || false;
>             if (source.columns) {
> ```

`columns` should default to empty array, I think.

---

*[src/app/core/config.class.js, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9N_Sv1GO5sR_ILZWf:-Kn9N_Sv1GO5sR_ILZWg:bjm95d0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/587afbb7191ef5f558bf1218d636bffbdc722423/src/app/core/config.class.js#L453)):*
> ```JavaScript
>                 this._columns = source.columns.map(columnsSource =>
>                     (new ColumnNode(columnsSource)));
>             }        
> ```

White space.

---

*[src/app/core/config.class.js, line 602 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9OcSjW8YEbxogWssN:-Kn9OcSjW8YEbxogWssO:b-im46dt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/587afbb7191ef5f558bf1218d636bffbdc722423/src/app/core/config.class.js#L602)):*
> ```JavaScript
>                 nameField: this.nameField,
>                 tolerance: this.tolerance,
>                 filters: this.filters
> ```

`filters: this.filters.JSON`

---

*[src/app/core/config.class.js, line 788 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9OjwlqZ1Db5uaiUdJ:-Kn9OjwlqZ1Db5uaiUdK:b69ug8r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/587afbb7191ef5f558bf1218d636bffbdc722423/src/app/core/config.class.js#L788)):*
> ```JavaScript
>                     layerEntry.JSON),
>                 tolerance: this.tolerance,
>                 filters: this.filters,
> ```

`filters: this.filters.JSON`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by JahidAhmed** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/core/config.class.js, line 445 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9NgQED_XY3BSU1yaX:-KnA3_TYIuWUSWg8MXRC:b8risqr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b751064a522b40758ea5315b794f3ec32e1ced88/src/app/core/config.class.js#L445)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Hm, in the schema `title` defaults to `null`. It should probably default to an empty string since it's a String :) 
@alyec @james-rae @jolevesq  Is it okay to update the schema's default value in this PR, or do we want to put all schema changes in a separate PR?
</blockquote></details>

Fixed the title, thanks!. Waiting for confirmation on changes to schema.

---

*[src/app/core/config.class.js, line 450 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9OS6a7gJA9EBlHzPP:-KnA3bldBJUhr0DHc4X3:b-896fja) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b751064a522b40758ea5315b794f3ec32e1ced88/src/app/core/config.class.js#L450)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`columns` should default to empty array, I think.
</blockquote></details>

Done!

---

*[src/app/core/config.class.js, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9N_Sv1GO5sR_ILZWf:-KnA3cNlaNPQNptPfuPd:b-896fja) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b751064a522b40758ea5315b794f3ec32e1ced88/src/app/core/config.class.js#L453)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

White space.
</blockquote></details>

Done!

---

*[src/app/core/config.class.js, line 602 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9OcSjW8YEbxogWssN:-KnA3dQout9OJ6YfC0EY:b-896fja) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b751064a522b40758ea5315b794f3ec32e1ced88/src/app/core/config.class.js#L602)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`filters: this.filters.JSON`
</blockquote></details>

Done!

---

*[src/app/core/config.class.js, line 788 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9OjwlqZ1Db5uaiUdJ:-KnA3e5kmDTnjIQn_Y3S:b-896fja) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b751064a522b40758ea5315b794f3ec32e1ced88/src/app/core/config.class.js#L788)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`filters: this.filters.JSON`
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by AleksueiR** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 454 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-KnA4M6Ti_5DCGX39Z5R:-KnA4M6Ti_5DCGX39Z5S:b-qey5ii) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3c995bd301fce44ef14a6a33ef5e4a41327b6634/src/app/ui/filters/filters-default.directive.js#L454)):*
> ```JavaScript
>                 // check if colums configuration exist. If so use it to set columns
>                 const order = [];
>                 if (config.columns.length) {
> ```

Shouldn't this be `config.columns.length > 0` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by JahidAhmed** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 454 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-KnA4M6Ti_5DCGX39Z5R:-KnA6xUIFrdEErGpSYPM:b-896fja) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3c995bd301fce44ef14a6a33ef5e4a41327b6634/src/app/ui/filters/filters-default.directive.js#L454)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Shouldn't this be `config.columns.length > 0` ?
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/config.class.js, line 445 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9NgQED_XY3BSU1yaX:-KnAiYH64hCwJVQQ4Jpl:b-o5eqqq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b751064a522b40758ea5315b794f3ec32e1ced88/src/app/core/config.class.js#L445)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Fixed the title, thanks!. Waiting for confirmation on changes to schema.
</blockquote></details>

Since no one replied, can you make an issue about this, so we can merge this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by JahidAhmed** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.class.js, line 445 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-Kn9NgQED_XY3BSU1yaX:-KnEy9K_JJhjDzgmgaEZ:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b751064a522b40758ea5315b794f3ec32e1ced88/src/app/core/config.class.js#L445)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Since no one replied, can you make an issue about this, so we can merge this PR?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2006#-:-KnFNHhw5vmxkhaYKnmP:bnfp4nl)*

**Pull request merged**
