### PR TITLE
Reorder layers with Dragula (it's so easy it's painfull™)

### LINKED ISSUE #272: Layer re-ordering
Allow the user to reorder the layers within their major groups (i.e. Feature vs Image Layers).  

Relates to:
#126

Traceability Matrix ID#043

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #272, #592.

I do apologize for sections of ugly code (especially related to legend entry, layer object and other "state" related checks). These should be cleared up after the refactor proposed by Aly.

Unit test for `layerRegistry` are turned off as well until the refactor is complete.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/600)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by alyec** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[src/app/geo/geo.constant.service.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHelCP7OFyi7OObt-Ay:-KHelCP8-4CZ1KHcejcu:606739374) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/geo.constant.service.js#L13)):*
> ```JavaScript
> 
>     // jscs doesn't like enhanced object notation
>     // jscs:disable requireSpacesInAnonymousFunctionExpression
> ```

To be removed now that this is a set of arrays.

---

*[src/app/geo/layer-registry.service.js, line 157 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfAM_I96889ccacFBH:-KHfAM_I96889ccacFBI:1204686673) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/layer-registry.service.js#L157)):*
> ```JavaScript
> 
>             /**
>              * Finds a position at whcich to insert the soruce layer so it's positioned directly about target layer (if one specified).
> ```

typos: which, source, about -> above

---

*[src/app/geo/layer-registry.service.js, line 347 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfCQPZncgrgEHC4cKm:-KHfCQPZncgrgEHC4cKn:1598294691) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/layer-registry.service.js#L347)):*
> ```JavaScript
>                             console.error('## layer error', layer.id, data);
> 
>                             // TODO: if layer errors on initial loading, swith it to the error state
> ```

typo: switch

---

*[src/app/geo/layer-registry.service.js, line 348 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfCMIqf980tcUConE4:-KHfCMIqf980tcUConE5:-930687647) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/layer-registry.service.js#L348)):*
> ```JavaScript
> 
>                             // TODO: if layer errors on initial loading, swith it to the error state
>                             // since this seems to happen sporadically, maybe don't change the template to errored placeholder on the fisrt error and wait for some time or for the next error or something like that
> ```

typo: first

---

*[src/app/ui/common/rvDragula.directive.js, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfDlgJWdwYaExl-O3o:-KHfDlgJWdwYaExl-O3p:-1748696789) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/common/rvDragula.directive.js#L49)):*
> ```JavaScript
>             dragulaService.options(dragulaScope, attr.rvDragula, dragulaOptions);
> 
>             // compile original dragula directive in some html with actually insering it into the page
> ```

typo: inserting; with -> without?

---

*[src/app/ui/toc/toc.directive.js, line 48 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfE4ipl-o6pXZou_4c:-KHfE4ipl-o6pXZou_4d:-930687647) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/toc/toc.directive.js#L48)):*
> ```JavaScript
> 
>                     // get item above the drop position
>                     const aboveItem = sibling.prev(); // can be [] if it's the fisrt item in the list
> ```

typo: first

---

*[src/app/ui/toc/toc.directive.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfFG05aO9y-2pLJLTV:-KHfFG05aO9y-2pLJLTW:1309516390) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/toc/toc.directive.js#L52)):*
> ```JavaScript
> 
>                     // docs says sibling can be null when trying to drop on the last place in the list
>                     // it doesn't seem to happen this way; if the sibling is the draggable item iself (has `gu-mirror` class), assume it's the end of the list
> ```

typo: itself

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by AleksueiR** [comment]
Thanks @alyec Aly for finding all the tyops. :D

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> #### Reorder layers with Dragula \(it&#39;s so easy it&#39;s painfull™\)
> 
> Closes #272, #592.
> 
> 
> 
> I do apologize for sections of ugly code (especially related to legend entry, layer object and other "state" related checks). These should be cleared up after the refactor proposed by Aly.
> 
> 
> 
> Unit test for `layerRegistry` are turned off as well until the refactor is complete.
> 
> 
> </details>


---

Review status: 11 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/geo/geo.constant.service.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHelCP7OFyi7OObt-Ay:-KHfHUlGGr4e9ESvHAk6:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/geo.constant.service.js#L13)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> To be removed now that this is a set of arrays.</details>
Done.

---

*[src/app/geo/layer-registry.service.js, line 157 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfAM_I96889ccacFBH:-KHfHVdsXQzfxvbhH3WR:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/layer-registry.service.js#L157)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typos: which, source, about -> above</details>
Done.

---

*[src/app/geo/layer-registry.service.js, line 347 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfCQPZncgrgEHC4cKm:-KHfHW7BIjqihjm4Yc2f:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/layer-registry.service.js#L347)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: switch</details>
Done.

---

*[src/app/geo/layer-registry.service.js, line 348 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfCMIqf980tcUConE4:-KHfHWcYGV72-skHFaoN:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/geo/layer-registry.service.js#L348)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: first</details>
Done.

---

*[src/app/ui/common/dragula.directive.js, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfDlgJWdwYaExl-O3o:-KHfHXGx7j2EPgaTLutJ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/common/dragula.directive.js#L49)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: inserting; with -> without?</details>
Done.

---

*[src/app/ui/toc/toc.directive.js, line 48 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfE4ipl-o6pXZou_4c:-KHfHYnd-xL4SiUqN_6v:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/toc/toc.directive.js#L48)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: first</details>
Done.

---

*[src/app/ui/toc/toc.directive.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfFG05aO9y-2pLJLTV:-KHfHZaDy3DRBNL03jIa:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/toc/toc.directive.js#L52)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: itself</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-:-KHfH_Mk738cRydMKSgW:417509753)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/dragula.directive.js, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfDlgJWdwYaExl-O3o:-KHfT8kMCrbDPMzGkr_t:-1462838711) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/common/dragula.directive.js#L49)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Done.</details>
missed inserting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by AleksueiR** [comment]
Review status: 10 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/dragula.directive.js, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600#-KHfDlgJWdwYaExl-O3o:-KHtOeiMxJwIPZUtK0To:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6708490028b5e7afa74062e85f645292f7a936f4/src/app/ui/common/dragula.directive.js#L49)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> missed inserting</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by alyec** [comment]
Reviewed 1 of 5 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 5 files at r2, 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/600)*

**Pull request merged**
