### PR TITLE
Colourpicker

### PR DESCRIPTION
**Pull request by AleksueiR**
Adds a colour picker to file-based imports. Needs geoApi patch which would actually apply the supplied colour.

In support of #770.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/865)

### CODE REVIEW

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/865#-:-KMQUjJtp1DogKs7ZG4O:1417088721)*

**Comment by alyec** [comment]
@spencerwahl reviewed this at my machine since his is out of commission.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/865#-:-KMQUsdO3NevBv20m0FR:616083314)*

**Comment by AleksueiR** [comment]
Needs [geoApi#133](https://reviewable.io/reviews/fgpv-vpgf/geoApi/133#-) to be merged first.

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/865#-:-KMTyjT0ar85awi6qV7x:1613720409)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/865)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/865)*

**Pull request merged**
