### PR TITLE
Enhance configService

### PR DESCRIPTION
**Pull request by spencerwahl**
- Removed most hacky parts of configService
- applies layer defaults to all layers in the config

---
This change is [Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/386)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 130 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386#-KCasFIkbmJlKFmcjZvw:-KCasFIkbmJlKFmcjZvx:682812125) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f697083cadd31a506a389ba2a09eeab3fcb71409/src/app/core/config.service.js#L130)):*
typo: Applies

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 108 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386#-KCatfOjt1UsYMp5CFI7:-KCatfOkB-41Zc1lNqB9:-1093232091) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f697083cadd31a506a389ba2a09eeab3fcb71409/src/app/core/config.service.js#L108)):*
Not for this PR, but if partial promises fail, the app doesn't load at all. We should at least try to start it with the file config (if any).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386)*

**Comment by spencerwahl** [comment]
*[src/app/core/config.service.js, line 130 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386#-KCasFIkbmJlKFmcjZvw:-KCaucSgIspJvIWNUmwK:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f697083cadd31a506a389ba2a09eeab3fcb71409/src/app/core/config.service.js#L130)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/386)*

**Pull request merged**
