### PR TITLE
Add more samples and modify some config files

### LINKED ISSUE #2024: Unable to test Metadata for structured Legends
Tested build: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html

Metadata option for structured legends are non responsive. Please investigate as this feature cannot be tested in the current build.

image

### PR DESCRIPTION
**Pull request by barryytm**
## Description

#1786 and fixes #2024.  Add more samples and fix the metadata not loading problem.
## Testing

Manually 
## Documentation

`index-samples` and more config files
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2091)

### CODE REVIEW

**Comment by milesap** [comment]
Looks good, works well :+1: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2091#-:-KoCGufB8y90IXzaWKMM:b2rsoyc)*

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/content/samples/config-sample-17.json, line 318 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2091#-KoCHJOOPE0BFS4-jZHu:-KoCHJOOPE0BFS4-jZHv:b-a3gg6s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e944c4c3fb9ad7ec135dd37f281b285529b9d2cf/src/content/samples/config-sample-17.json#L318)):*
> ```JSON
>           {
>             "name": "Layer with only Information section",
>             "expanded": true,
> ```

I believe `expanded` only applies to groups.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2091)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2091#-:-KoCom4-wFhzi8_B1xoN:bnfp4nl)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/samples/config-sample-17.json, line 318 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2091#-KoCHJOOPE0BFS4-jZHu:-KoColWgdHcQvC09JTKT:b-8hlgqu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e944c4c3fb9ad7ec135dd37f281b285529b9d2cf/src/content/samples/config-sample-17.json#L318)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I believe `expanded` only applies to groups.
</blockquote></details>

Deleted it, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2091)*

**Comment by james-rae** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2091)*

**Pull request merged**
