### PR TITLE
fix(ui): opacity slider percent display

### LINKED ISSUE #429: UI problems for opacity slider
- Opacity label missing
- second % label
- first % label is bound to the wrong variable (and only shows up as "%")

### PR DESCRIPTION
**Pull request by cynngah**
closes #429

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/439)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/settings/settings.html, line 12 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439#-KEHWeIDN-TAq-gxbw26:-KEHWeIEBXJD1QHVfIfl:-1713228664) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a778145ad24e1fc19faf5e900bb70161b28b3519/src/app/ui/settings/settings.html#L12)):*
The label saying "Opacity" is still missing

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439)*

**Comment by cynngah** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/settings/settings.html, line 12 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439#-KEHWeIDN-TAq-gxbw26:-KEHz4DA3TmVL042p2W5:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a778145ad24e1fc19faf5e900bb70161b28b3519/src/app/ui/settings/settings.html#L12)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/439)*

**Pull request merged**
