### PR TITLE
part 2 of config update, please review geoApi first. Require new geoApi build.

### PR DESCRIPTION
**Pull request by ec-dev**
need geoApi review first, once the geoApi pull request is complete, will generate a new build and bump the bower.json.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/318)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/configDemo.json, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKS5TPwaApvx_Xvezm:-KAKS5TPwaApvx_Xvezn:-2073339452) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L3)):*
I think we decided to not specify language in the config file. Not sure. @alyec ?

---

*[src/configDemo.json, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKSDuS3OG7H2uBNqY4:-KAKSDuS3OG7H2uBNqY5:-1430850212) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L7)):*
Please update config schema to match the config file.

---

*[src/configDemo.json, line 72 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKRzstoWBk_Vypy0q0:-KAKRzstoWBk_Vypy0q1:1502648106) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L72)):*
Could you add real basemap names?

---

*[src/configDemo.json, line 240 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKOgeZSBnTHBZZ_KsO:-KAKOgeZSBnTHBZZ_KsP:53734443) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L240)):*
Previously, there was a bit of a discussion about changing how the navigation is configured: :point_up: [January 19, 2016 8:33 AM](https://gitter.im/fgpv-vpgf/ArchDocDiscussion?at=569e3b3659e3d04215bc9e20)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 390 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KALGlJHcoY2zAmK0jxb:-KALGlJHcoY2zAmK0jxc:-1869111934) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/app/geo/geo.service.js#L390)):*
We should start using promises if we're getting into dependency chains.

---

*[src/configDemo.json, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKS5TPwaApvx_Xvezm:-KAK_cjmj0_hmlnkcXGf:704544436) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L3)):*
I think it's present as a way to verify (so if a developer accidentally reverses their configs it becomes pretty obvious).  I'm okay with dropping this as well.

---

*[src/configDemo.json, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKSDuS3OG7H2uBNqY4:-KALEnPdi8iuRc5Qkj7C:353541818) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L7)):*
How about please update the config to match the schema? :)

---

*[src/configDemo.json, line 240 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKOgeZSBnTHBZZ_KsO:-KALFHdZLLP6CN3ndhJL:1698445788) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L240)):*
Extended this discussion further: https://gitter.im/fgpv-vpgf/ArchDocDiscussion?at=56bddd944dfe1fa71ffc5a00 and I think we can leave it as is until that part gets resolved (i.e. let this part merge and then revise it after we get consensus).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 390 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KALGlJHcoY2zAmK0jxb:-KALHjj3380tiMrZMInQ:-1667502251) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/app/geo/geo.service.js#L390)):*
See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/310

---

*[src/configDemo.json, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKSDuS3OG7H2uBNqY4:-KALHqRhVgm3MjmkUVMH:-1272706100) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L7)):*
How about "please first update schema if you are planning to add new stuff to config and then update config"? :D

---

*[src/configDemo.json, line 240 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKOgeZSBnTHBZZ_KsO:-KALI20ll4flSs_7B4wp:1062185556) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L240)):*
I'm okay with that as long as the consensus matches my version :dancers: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/configDemo.json, line 240 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKOgeZSBnTHBZZ_KsO:-KALIXj2ZbHgw6ZJB6X1:-1488834322) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L240)):*
`overviewMapWidget` :white_check_mark: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by ec-dev** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 390 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KALGlJHcoY2zAmK0jxb:-KApbn7jdQgJrdw4uj9R:700044289) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/app/geo/geo.service.js#L390)):*
Agreed, but will do this on a separate task.

---

*[src/configDemo.json, line 72 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAKRzstoWBk_Vypy0q0:-KApl3W-YFqIJchkx6Qg:-469593337) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/configDemo.json#L72)):*
done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/config-demo.json, line 250 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApmBi_sXr4h0Yji-pZ:-KApmBiaUp_iTv4xpVZv:-1384011383) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5aa374caa3122484d723530d637da0a297fdf313/src/config-demo.json#L250)):*
What's `extendId`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 390 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KALGlJHcoY2zAmK0jxb:-KApmN20B28qxtOJKJ3H:5173697) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/957a3a7a9d6522e131b300fedcfc7b79ab750440/src/app/geo/geo.service.js#L390)):*
Ok

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/config-demo.json, line 250 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApmBi_sXr4h0Yji-pZ:-KApn1ne4RQxwZno2lAD:-786644750) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5aa374caa3122484d723530d637da0a297fdf313/src/config-demo.json#L250)):*
in a basemap node, it has extendId refer to the specific extentSet in the map config. This extentSet may have "full", "default", or "maximum".  The value of extendId should reference map.extentSets.id

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 460 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApqrk_OuKUrSbyrbLj:-KApqrk_OuKUrSbyrbLk:56848096) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/app/geo/geo.service.js#L460)):*
const
`extentSet =>` (no brackets)

---

*[src/app/geo/geo.service.js, line 469 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApr8lWMlx0p6aZGwm8:-KApr8lWMlx0p6aZGwm9:912605642) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/app/geo/geo.service.js#L469)):*
I think this is an error and it should throw an exception.

---

*[src/app/geo/geo.service.js, line 473 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAprHJPTGxDPnoxe7DX:-KAprHJPTGxDPnoxe7DY:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/app/geo/geo.service.js#L473)):*
const

---

*[src/schema.json, line 403 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApo0rpI4Jgx4hg1ooq:-KApo0rpI4Jgx4hg1oor:914939647) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L403)):*
"default": "buttons"

---

*[src/schema.json, line 404 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoAvKheXIkfrGOuRz:-KApoAvKheXIkfrGOuS-:504152774) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L404)):*
"default": []

---

*[src/schema.json, line 406 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoEWyTCLN1BqZgsXe:-KApoEWyTCLN1BqZgsXf:2070253650) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L406)):*
"additionalProperties": false

---

*[src/schema.json, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoyefdIeSuKhauAXg:-KApoyegJmH_iQL7K2Kh:-881702828) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L416)):*
For these properties you can use `option` as a base (essentially adding enabled: boolean defaulted to true.  Or remove the enabled property from everything, don't make any of these required and then use their presence to determine which widgets should be displayed.

---

*[src/schema.json, line 421 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAppF2E_B6zPRgs2cAU:-KAppF2E_B6zPRgs2cAV:332964210) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L421)):*
Maybe change northArrow and scaleBar to { enabled: boolean } just to make it consistent with the other components

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/config-demo.json, line 250 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApmBi_sXr4h0Yji-pZ:-KAprzfcUimuBXiP5yEN:2065937316) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5aa374caa3122484d723530d637da0a297fdf313/src/config-demo.json#L250)):*
typo: `extendId` -> `extentId`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by ec-dev** [comment]
*[src/config-demo.json, line 250 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApmBi_sXr4h0Yji-pZ:-KApsOH7SMgeat1xB0_G:-1681934626) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5aa374caa3122484d723530d637da0a297fdf313/src/config-demo.json#L250)):*
Thanks, didn't even see it when you brought it up first. Arrghhh.. :dizzy_face: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r6.
Review status: 4 of 5 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 460 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApqrk_OuKUrSbyrbLj:-KAqISNOZhiGZeqeeLYL:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/app/geo/geo.service.js#L460)):*
Done.

---

*[src/app/geo/geo.service.js, line 469 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApr8lWMlx0p6aZGwm8:-KAvDgcEdqepRIJwekgO:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/app/geo/geo.service.js#L469)):*
Done.

---

*[src/app/geo/geo.service.js, line 473 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAprHJPTGxDPnoxe7DX:-KAvDh1-V-J5Lmi6yn58:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/app/geo/geo.service.js#L473)):*
Done.

---

*[src/config-demo.json, line 250 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApmBi_sXr4h0Yji-pZ:-KAvDhcCarXjFgSazMem:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5aa374caa3122484d723530d637da0a297fdf313/src/config-demo.json#L250)):*
Done.

---

*[src/schema.json, line 403 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApo0rpI4Jgx4hg1ooq:-KAvDinwkxjRC2kU3uOZ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L403)):*
Done.

---

*[src/schema.json, line 404 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoAvKheXIkfrGOuRz:-KAvDj6DsUTtZ0NveoWt:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L404)):*
Done.

---

*[src/schema.json, line 406 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoEWyTCLN1BqZgsXe:-KAvDjV7VxmBgAuqWKbV:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L406)):*
Done.

---

*[src/schema.json, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoyefdIeSuKhauAXg:-KAvDnyAe3RPHR5D1hhJ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L416)):*
Done.

---

*[src/schema.json, line 421 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KAppF2E_B6zPRgs2cAU:-KAvDjtRHu_fxdcyi1to:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L421)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/schema.json, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoyefdIeSuKhauAXg:-KAvGdE5-c5fkP6uzjpk:-1884262130) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L416)):*
`enabled` still has no default, if you plan to use the element's presence as an indicator of them being enabled then `enabled` should be removed and it should be added to the description

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r4, 2 of 3 files at r5, 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/schema.json, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoyefdIeSuKhauAXg:-KB8-HaIfhQhkypHGFku:-558355780) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L416)):*
As @alyec said, it makes sense to use either the `option` definition as the base for `mapComponentsNode` properties or just list them similar to `navBarButtons`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by ec-dev** [comment]
*[src/schema.json, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoyefdIeSuKhauAXg:-KB8DdTnenzGodoQIbK2:-1953644709) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L416)):*
we have mixed type of values, therefore AFAIK  we cannot follow the navBarButtons pattern. geoSearch, mouseInfo, overviewMap nodes have more properties. 

As with the option definition, the only two that can use it is the scalebar and northArrow. I can replace both with 
{ "$ref": "#/definitions/option"};

[Respectfully saying the following...] But, I am new to this schema validation thing, so If I missed how to combine ref node with new properties, let me know. I will update it. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoyefdIeSuKhauAXg:-KB8pyWsjxJ6XJkt4Vhk:-798715035) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L416)):*
I see. You an use `allOf` to combine definitions: http://spacetelescope.github.io/understanding-json-schema/reference/combining.html#allof

Here's adding `value` property to the visibility toggle:
```json
"visibility": {
                            "allOf": [
                                { "$ref": "#/definitions/option" },
                                {
                                    "properties": {
                                        "value": {
                                            "type": "boolean",
                                            "default": true,
                                            "description": "True: the layer group and all its children are visible unless children have overrides; False: the layer group and all its children are hidden unless the overrides are specified."
                                        }
                                    }
                                }
                            ],
```

I'm not sure if combining defs in this case will be better (it looks like it will be more code). I would say 'do as Aly says' :), but he :space_invader: ed. Maybe merge this and fix later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 416 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318#-KApoyefdIeSuKhauAXg:-KB8syP1moxYUz2ZvrTF:-2030574924) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3bd535a0ed9f00b9b0ab8417e501b45c5cb07af7/src/schema.json#L416)):*
Yeah, feel free to merge this for now and we can sort out improvements later (I think making all of these optional and having their presence imply `enabled` looks like the cleanest option to me).  We can continue the discussion once it's in develop.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/318)*

**Pull request merged**
