### PR TITLE
webpack phase 1

### PR DESCRIPTION
**Pull request by milesap**
- clear npm cache and node_modules folder
- run `npm install`
- run `npm run serve` for browser and `npm run start` for just build files
- minor bugs, please squash some if you can
- phase 2 will roll out dist build and any other functionality missing from gulp and bug squashing
- phase 3 will optimize build, remove unused packages, and update ones we do use

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1887)

### CODE REVIEW

**Comment by AleksueiR** [comment]
`npm run serve` fails (running with Vagrant). 
Here are logs: https://gist.github.com/AleksueiR/b9765e8a3c0d4f346e77afd06e38c083

---

Review status: 0 of 190 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-:-KkL95GtmxxWCFLVwnBT:b-bakr92)*

**Comment by AleksueiR** [comment]
`npm run start` fails with the same errors.

---

Review status: 0 of 190 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-:-KkL9e5nL4FhqphiY-1h:braw2y2)*

**Comment by AleksueiR** [comment]
Things so far:

- angular scoping seems to be working
- label "DATATABLE" still visible on layer selector items
- datatable menu is messed up a little: https://i.imgur.com/tFKVqQi.png
- can't save export image

---

Review status: 0 of 213 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-:-KkqCKdZoL3UN7inQZ-o:bu1lvj9)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 107 files at r2, 4 of 15 files at r3.
Review status: 8 of 213 files reviewed at latest revision, 1 unresolved discussion.

---

*[.eslintrc.yml, line 8 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-KkubfMo6Cq4VAh_8z-9:-KkubfMo6Cq4VAh_8z-A:b-a3rrpe) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/.eslintrc.yml#L8)):*
> ```YAML
>   RColor: true
>   marked: true
>   Ease: true
> ```

Why are these no longer global?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by milesap** [comment]
> label "DATATABLE" still visible on layer selector items
> datatable menu is messed up a little: https://i.imgur.com/tFKVqQi.png

Still looking into these two but they are related to md-button.

---

Review status: 8 of 214 files reviewed at latest revision, 1 unresolved discussion.

---

*[.eslintrc.yml, line 8 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-KkubfMo6Cq4VAh_8z-9:-KkvdedLMMCdIX9IaGNl:by7esp9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/.eslintrc.yml#L8)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Why are these no longer global?
</blockquote></details>

`Ease` and `BezierEasing` were not module exportable, using `Power1` from `gsap` as a replacement (they have many more, just chose `Power1` for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-:-Kkve0XoEp2NZ0PLqpnO:b-3b3rjg)*

**Comment by AleksueiR** [comment]
Review status: 8 of 215 files reviewed at latest revision, 1 unresolved discussion.

---

*[.eslintrc.yml, line 8 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-KkubfMo6Cq4VAh_8z-9:-KkzxYR4NGVXQ1_rRDVD:b-8g4vd6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/.eslintrc.yml#L8)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

`Ease` and `BezierEasing` were not module exportable, using `Power1` from `gsap` as a replacement (they have many more, just chose `Power1` for now.
</blockquote></details>

`power1` is not the same as `BezierEasing`. Also, our css transitions use bezier easing.
There is no way to include them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by AleksueiR** [comment]
Reviewed 141 of 227 files at r1, 89 of 107 files at r2, 4 of 15 files at r3, 7 of 9 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[.eslintrc.yml, line 8 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-KkubfMo6Cq4VAh_8z-9:-Kl-MsB4Md_Qs0u8UFar:b-9zy36b) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/.eslintrc.yml#L8)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`power1` is not the same as `BezierEasing`. Also, our css transitions use bezier easing.
There is no way to include them?
</blockquote></details>

Can you make an issue to restore `BezierEasing` at some later date?

---

*[src/app/app-seed.js, line 27 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-No54hhS0_S4zuNc4:-Kl-No54hhS0_S4zuNc5:bb76mu4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/app-seed.js#L27)):*
> ```JavaScript
>             // this checks for any failures; to fix a problem add 'ngInject'; to the function preamble
>             angular.bootstrap(node, ['app'], {
>                 strictDi: false
> ```

Why?

---

*[src/app/core/config.class.js, line 1497 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aAcFtIcYlYaRsSYN:-Kl-aAcFtIcYlYaRsSYO:b8by07) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/config.class.js#L1497)):*
> ```JavaScript
>         }
> 
>         static get AVAILABLE_ITEMS () { return [
> ```

Any reason for this change?

---

*[src/app/core/translation.service.js, line 14 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aYBIHOpcsyexs5JL:-Kl-aYBJ9eMLN_fA7YHY:b32vhw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/translation.service.js#L14)):*
> ```JavaScript
> 
> function translationService($q, translations, $translate) {
>     console.log(translations);
> ```

:)

---

*[src/app/core/version.service.js, line 16 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aeX6ztDmK7Fp2Igh:-Kl-aeX6ztDmK7Fp2Igi:b-3rqrv7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/version.service.js#L16)):*
> ```JavaScript
>         patch: RVersion.patch,
>         hash: RVersion.gitHash.substring(0, 9),
>         timestamp: + new Date()
> ```

The time stamp should reflect the time the build was made, not the current time.

---

*[src/app/geo/legend-block.class.js, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-eb4-bW3P-5htJxVi:-Kl-eb49i_HP8WqDqtvA:bohnv5k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/geo/legend-block.class.js#L176)):*
> ```JavaScript
>             this.isControlUserDisabled = ref.isControlUserDisabled.bind(this);
>             this._isSelected = false;
>             this._layerRecordId = null;
> ```

Why move default properties inside the constructor?
There are several places in the PR with such changes.

---

*[src/app/layout/shell.html, line 46 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-evjkCxtI8u3S3KsO:-Kl-evjkCxtI8u3S3KsP:b-eydapm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/layout/shell.html#L46)):*
> ```HTML
> <rv-panel type="filters" rv-state="filters" rv-morph="filters" class="rv-plug-slide-down-grand"></rv-panel>
> 
> <div class="rv-basemap">
> ```

Please move the basemap selector template in its own file. Maybe turn this into a template of the basemap directive itself, similar to how `rv-mapnav` is done, or just keep it as include for now. This can be done later.

---

*[src/app/ui/geosearch/geosearch.service.js, line 31 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-fqQm6G6Puo0hEjne:-Kl-fqQm6G6Puo0hEjnf:bb76mu4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/ui/geosearch/geosearch.service.js#L31)):*
> ```JavaScript
> 
>     const ref = {
>         mainPanel: storageService.panels.shell ? storageService.panels.shell.find('[rv-state=main]') : $(),
> ```

Why?

---

*[src/app/ui/toc/legend-element-factory.class.js, line 393 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-hGu-POxPtbzGlPNQ:-Kl-hGu-POxPtbzGlPNR:bb76mu4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/ui/toc/legend-element-factory.class.js#L393)):*
> ```JavaScript
>         get label () {   return 'toc.label.flag.query'; }
> 
>         get isVisible () { return true; }
> ```

Why?

---

*[src/app/ui/tooltip/tooltip.directive.js, line 27 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-hq4suW9g2NfB9DCw:-Kl-hq4suW9g2NfB9DCx:bqd5jir) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/src/app/ui/tooltip/tooltip.directive.js#L27)):*
> ```JavaScript
>             // scope: {}, // here, the tooltip directive requests an isolated scope, while the transcluded content of the tooltip has non-isolated scope with access to the scope the directive was compiled under
>             templateUrl: (elm, attr) =>
>                 (`app/ui/tooltip/tooltip-${attr.template}.html`),
> ```

You can't specify the template name anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by milesap** [comment]
Will re-open new PR on correct target branch

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[.eslintrc.yml, line 8 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-KkubfMo6Cq4VAh_8z-9:-Kl3OiRjG-6mCXs-6G8F:b-7iu3bs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/.eslintrc.yml#L8)):*
> BezierEasing
Opened issue #1902

---

*[src/app/app-seed.js, line 27 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-No54hhS0_S4zuNc4:-Kl3PHsc_z-yYvRj-QhP:b-9xsjd3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/app-seed.js#L27)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

We don't explicitly annotate our functions in the code, it's only done automatically on prod builds due to minification. Unless it does other stuff in the background the check itself is not useful (and injecting dev builds increases its file size without added benefit).

---

*[src/app/core/config.class.js, line 1497 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aAcFtIcYlYaRsSYN:-Kl3QeNQRUAiHKSGUyon:b-5qyp4c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/config.class.js#L1497)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Any reason for this change?
</blockquote></details>

Webpack would fail to compile code with errors. Was the original code valid syntax or some newer ES2017 format?

---

*[src/app/core/translation.service.js, line 14 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aYBIHOpcsyexs5JL:-Kl3RYYCxyMKqkKV_yFc:by62x24) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/translation.service.js#L14)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

:)
</blockquote></details>

Missed it! :+1: 

---

*[src/app/core/version.service.js, line 16 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aeX6ztDmK7Fp2Igh:-Kl3S2IjN87s76K3N8t0:b499q7j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/version.service.js#L16)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

The time stamp should reflect the time the build was made, not the current time.
</blockquote></details>

Changed

---

*[src/app/geo/legend-block.class.js, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-eb4-bW3P-5htJxVi:-Kl3S9DTVqXwE-F9Qgas:b-5qyp4c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/geo/legend-block.class.js#L176)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Why move default properties inside the constructor?
There are several places in the PR with such changes.
</blockquote></details>

Webpack would fail to compile code with errors. Was the original code valid syntax or some newer ES2017 format?

---

*[src/app/layout/shell.html, line 46 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-evjkCxtI8u3S3KsO:-Kl3S_9Bajb3uUAHZIYS:b-uli7wj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/layout/shell.html#L46)):*
> Please move the basemap selector template in its own file. Maybe turn this into a template of the basemap directive itself, similar to how rv-mapnav is done, or just keep it as include for now. This can be done later.
Opened #1903

---

*[src/app/ui/geosearch/geosearch.service.js, line 31 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-fqQm6G6Puo0hEjne:-Kl3TPmNDVCKna--bh7E:bm8qah4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/ui/geosearch/geosearch.service.js#L31)):*
> storageService.panels.shell.find('[rv-state=main]')
Corrected on rebase

---

*[src/app/ui/toc/legend-element-factory.class.js, line 393 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-hGu-POxPtbzGlPNQ:-Kl3SxEeambBdst2T916:batd03t) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/ui/toc/legend-element-factory.class.js#L393)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Corrected on rebase

---

*[src/app/ui/tooltip/tooltip.directive.js, line 27 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-hq4suW9g2NfB9DCw:-Kl3T6uApckt9H3bPvnp:bl5xxvo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/src/app/ui/tooltip/tooltip.directive.js#L27)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can't specify the template name anymore.
</blockquote></details>

I believe there is only one template. It others are added later they need to be required at the top of the file (a few places in the code do this already for reference)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/core/config.class.js, line 1497 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aAcFtIcYlYaRsSYN:-Kl3U8y57J4lDd4_Anni:bxao2yc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/config.class.js#L1497)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Webpack would fail to compile code with errors. Was the original code valid syntax or some newer ES2017 format?
</blockquote></details>

Yeap, it's valid under babels' stage 2 proposal. You need to add `"babel-preset-stage-2": "^6.22.0",` to the npm packages.

---

*[src/app/geo/legend-block.class.js, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-eb4-bW3P-5htJxVi:-Kl3Uary8bajrMsH0hfS:bk0wha5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/geo/legend-block.class.js#L176)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Webpack would fail to compile code with errors. Was the original code valid syntax or some newer ES2017 format?
</blockquote></details>

stage 2, see above.

---

*[src/app/layout/shell.html, line 46 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-evjkCxtI8u3S3KsO:-Kl3Udmv8dcjDIBVHsKF:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/layout/shell.html#L46)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

> Please move the basemap selector template in its own file. Maybe turn this into a template of the basemap directive itself, similar to how rv-mapnav is done, or just keep it as include for now. This can be done later.
Opened #1903
</blockquote></details>

:+1: 

---

*[src/app/ui/tooltip/tooltip.directive.js, line 27 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-hq4suW9g2NfB9DCw:-Kl3UkRUaPj2GzM_tKNv:bcmyq12) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28b0307ad0e1893a2ff603be1d90466e81e2b9c4/src/app/ui/tooltip/tooltip.directive.js#L27)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I believe there is only one template. It others are added later they need to be required at the top of the file (a few places in the code do this already for reference)
</blockquote></details>

Makes sense. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/core/config.class.js, line 1497 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aAcFtIcYlYaRsSYN:-Kl3Ym7emQEVw6rkhSnf:b-4snzlm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/config.class.js#L1497)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Yeap, it's valid under babels' stage 2 proposal. You need to add `"babel-preset-stage-2": "^6.22.0",` to the npm packages.
</blockquote></details>

Added stage 2 to babel-loader and reverted changes on file

---

*[src/app/geo/legend-block.class.js, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-eb4-bW3P-5htJxVi:-Kl3YfYsJY_55Fu-SuJ8:b-4snzlm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/geo/legend-block.class.js#L176)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

stage 2, see above.
</blockquote></details>

Added stage 2 to babel-loader and reverted changes on file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/core/config.class.js, line 1497 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-aAcFtIcYlYaRsSYN:-Kl3ZZPK4Y44WMGVbw2_:b-75h0bq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/core/config.class.js#L1497)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Added stage 2 to babel-loader and reverted changes on file
</blockquote></details>

:+1:  THanks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/app-seed.js, line 27 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-No54hhS0_S4zuNc4:-Kl3aA7v2EJHn6_g7gQr:bt4slqa) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/app-seed.js#L27)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

We don't explicitly annotate our functions in the code, it's only done automatically on prod builds due to minification. Unless it does other stuff in the background the check itself is not useful (and injecting dev builds increases its file size without added benefit).
</blockquote></details>

There is a `ng-annotate` module that auto-annotates functions as long as `"ngInject";` is specified at the beginning of the function needed to be annotated. I think it's still useful since you get a nice error when you screw up with your angular dependencies. 

Why does the size increase with `strictDi` and by how much?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/app-seed.js, line 27 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887#-Kl-No54hhS0_S4zuNc4:-Kl3eDs9QsvVS97BQRmK:bpb95ma) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5de4cca321e5634f9472e2901e33f20925df85c2/src/app/app-seed.js#L27)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

There is a `ng-annotate` module that auto-annotates functions as long as `"ngInject";` is specified at the beginning of the function needed to be annotated. I think it's still useful since you get a nice error when you screw up with your angular dependencies. 

Why does the size increase with `strictDi` and by how much?
</blockquote></details>

Let's crunch some numbers:
without annotations: rv-main.js is 7,820kb (dev)
with annotations: rv-main.js is 7,831kb (dev)
an increase of **0.14%** :warning: 

Annotations are text strings that are added to the build file via a plugin. I can enable strictDi if you'd like (`ngInject`) would no long be needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1887)*

**Pull request closed without merging**
