### PR TITLE
fix(api): change event timing

### LINKED ISSUE #2577: API bug in map.setCenter
`XY.projectToPoint()` has the spatial reference parameters [reversed](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-semi-weekly01/api/src/geometry.ts#L27) , needs to be source then target.

Also, we have the lambert projection hardcoded into [setCenter](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-semi-weekly01/api/src/map.ts#L168).  The code should be getting the spatial reference from the map.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Change timing of api event calling.

Closes #2577, #2575, #2561

## Testing
`samples/api.html`

## Documentation
None

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2576)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Which sample page is the `self-loader` extension is being loaded on?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576#-:-L4lh-ImAAVaMc1AM_CR:bael11h)*

**Comment by JahidAhmed** [comment]
http://fgpv.cloudapp.net/demo/users/milesap/2575-api-timing/dev/samples/api.html I believe

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576#-:-L4lhpsnrn4u-qg0WmGT:b-qqgumb)*

**Comment by AleksueiR** [comment]
Thanks :+1:  Everything seems to work find. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576#-:-L4ltDRbQQwKCLKVw02F:b-rxpn3d)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576)*

**Comment by milesap** [comment]
Should be good to merge, test link changed to http://fgpv.cloudapp.net/demo/users/milesap/2575-api-timing/dev/samples/api/self-loading/api.html

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576#-:-L5FCnkLTCTnw310XYWl:b-b0va0a)*

**Comment by JahidAhmed** [comment]
Reviewed 2 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2576)*

**Pull request merged**
