### PR TITLE
fix(ui) Set map whit configuration file when language switch

### LINKED ISSUE #1278: Side menu ignores config changes
Items are added to the side menu during the viewer initialization. When changing the language, a new config file is loaded but the side menu items are not updated.

Say `English` config enabled `shareable` and `French` config does not.
- Open the map (`English` is default)
- Check `Share` option is available in the side menu
- Switch language to French
- Check that `Share` option is still available

### PR DESCRIPTION
**Pull request by jolevesq**
Throw rvLangSwitch event for items to listen and react at a language switch

Closes #1278

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1328)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/layout/shell.directive.js, line 59 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328#-KVz0kIqprwZ5CoB03x8:-KVz0kIqprwZ5CoB03x9:b-rbu3lr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8cfe0b8bf27fb8f57d99386b654c0f286db2f91f/src/app/layout/shell.directive.js#L59)):*
> ```JavaScript
>     }
> 
>     // ignore jshint maxparams options
> ```

I think the maxparams issue is because shell directive is doing too much.  Can you add a FIXME for refactoring out shell directive into more manageable pieces?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328)*

**Comment by jolevesq** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.directive.js, line 59 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328#-KVz0kIqprwZ5CoB03x8:-KW3EO3EyEuWj0q9UlFE:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8cfe0b8bf27fb8f57d99386b654c0f286db2f91f/src/app/layout/shell.directive.js#L59)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think the maxparams issue is because shell directive is doing too much.  Can you add a FIXME for refactoring out shell directive into more manageable pieces?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328)*

**Comment by jolevesq** [comment]
Yes!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1328#-:-KW3GbLS9AsP0m20Lds4:bb77uf3)*

**Pull request merged**
