### PR TITLE
Moving hovertip template

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
- move hovertip template to tootlip service as the default template
- prevent controlled layers from being queried (even if specified in the config)
- prevent controlled layers from having enabled bounding boxes (even if specified in the config)
- prevent controlled layers from having hovertips

## Testing
Nope.

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ not needed
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1895)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 86 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVhT0GgUhswagI8HeP:-KkVhT0GgUhswagI8HeQ:bj1tt6h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend.service.js#L86)):*
> ```JavaScript
>             const blockConfig = new ConfigObject.legend.Entry(entryConfigObject);
> 
>             // FIXME: this seems to alwyas insert a new layer at the bottom of the legend regardless of it's sorting group; needs fixing
> ```

Typo on always

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/legend-block.class.js, line 37 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVyHDumInl1zqFnOBw:-KkVyHDumInl1zqFnOBx:bytl4mo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L37)):*
> ```JavaScript
>         };
> 
>         /**
> ```

jsdoc is happening again :trophy: 

---

*[src/app/geo/legend-block.class.js, line 129 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVzDrEnevgyMUgM8QO:-KkVzDrEnevgyMUgM8QP:b2ry1wx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L129)):*
> ```JavaScript
>             /**
>              * Layer config object persists through layer reload (corresponding layer record and legend blocks are destroyed),
>              * the changed snapshot value will be processed in geoApi on the subsequent generation of layer records.             *
> ```

style: clean up the extra `*` on the right

---

*[src/app/geo/legend-block.class.js, line 752 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVzb5vh6chmDj1npwq:-KkVzb5vh6chmDj1npwr:btj8hjx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L752)):*
> ```JavaScript
> 
>         /**
>          * Checks if the specified control is locked to modification by the system and user.
> ```

`locked to` -> `locked from` might be more clear

---

*[src/app/geo/legend-block.class.js, line 764 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVzkFmxSpRdkZkucr6:-KkVzkFmxSpRdkZkucr7:btj8hjx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L764)):*
> ```JavaScript
> 
>         /**
>          * Checks if the specified control is locked to modification by the user.
> ```

`locked to` -> `locked from` might be more clear

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895)*

**Comment by AleksueiR** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/legend-block.class.js, line 37 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVyHDumInl1zqFnOBw:-KkW-TEJ1lhpW8xoTIHM:biyfe3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L37)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

jsdoc is happening again :trophy: 
</blockquote></details>

Done, thanks :)

---

*[src/app/geo/legend-block.class.js, line 129 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVzDrEnevgyMUgM8QO:-KkW-cRAif5Qy3YeBr3o:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L129)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

style: clean up the extra `*` on the right
</blockquote></details>

Done.

---

*[src/app/geo/legend-block.class.js, line 752 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVzb5vh6chmDj1npwq:-KkW-d8MIA6l-Of7QNfP:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L752)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

`locked to` -> `locked from` might be more clear
</blockquote></details>

Done.

---

*[src/app/geo/legend-block.class.js, line 764 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVzkFmxSpRdkZkucr6:-KkW-dSq9DYCa5ZAx8-R:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend-block.class.js#L764)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

`locked to` -> `locked from` might be more clear
</blockquote></details>

Done.

---

*[src/app/geo/legend.service.js, line 86 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895#-KkVhT0GgUhswagI8HeP:-KkW-i8S-SVPZd2qqRlB:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8df88aaf5d9b0ad50b82d35db638091482b009f7/src/app/geo/legend.service.js#L86)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo on always
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1895)*

**Pull request merged**
