### PR TITLE
Bookmark enhancements

### PR DESCRIPTION
**Pull request by spencerwahl**
Bookmarking is now tied to the API, extent is kept on projection switch, API is paused while map is reloading

issues #799 , #833

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/904)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Comment by alyec** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[src/app/bootstrap.js, line 110 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiVTWknyaqsM1MRjud:-KMiVTWknyaqsM1MRjue:1960590724) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/bootstrap.js#L110)):*
> ```JavaScript
>     const mapProxy = {
>         _appPromise: null,
>         _initAppPromise: null,
> ```

comments please; when there was only one of them I kind of had an idea what they were doing now I have absolutely none

---

*[src/app/bootstrap.js, line 157 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiVP3fzW_TCJr_fC6D:-KMiVP3fzW_TCJr_fC6E:-408585108) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/bootstrap.js#L157)):*
> ```JavaScript
>             );
> 
>             this._initAppPromise = new Promise((resolve) =>
> ```

duplicated code :sparkles: 

---

*[src/app/core/bookmark.service.js, line 134 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiVnEuKyHUvIZPVH0l:-KMiVnEuKyHUvIZPVH0m:-463942294) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/bookmark.service.js#L134)):*
> ```JavaScript
>         }
> 
>         function addRcsConfigs(rcsBookmarks, config) {
> ```

jsdoc

---

*[src/app/core/bookmark.service.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiW8krsame1Mdk4yyj:-KMiW8krsame1Mdk4yyk:1273612598) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/bookmark.service.js#L138)):*
> ```JavaScript
>                 return configService.rcsAddKeys(Object.keys(rcsBookmarks).map(id => id.split('.')[1]))
>                     .then(rcsConfigs => {
>                         const configSnippets = [];
> ```

`configSnippets = rcsConfigs.map(cfg => angular.merge(cfg, rcsBookmars[cfg.id]))` ?

---

*[src/app/core/config.service.js, line 196 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiWpWI9OY0r0hn6e9A:-KMiWpWI9OY0r0hn6e9B:-514060151) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/config.service.js#L196)):*
> ```JavaScript
>          * Stores configPromise to be returned using getCurrent.
>          *
>          * @param {Promise} configPromise   A promise resolving with a config (usually modified by a bookmark)
> ```

needs `@function setCurrent`

---

*[src/app/core/constant.service.js, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiX2hAkIcpqyAtoeMJ:-KMiX2hAkIcpqyAtoeMK:-1107143306) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/constant.service.js#L28)):*
> ```JavaScript
>         .constant('events', {
>             rvReady: 'rvReady',
>             rvApiHalt: 'rvApiHalt',
> ```

These need descriptions.  Either here or in a new docs page describing our events.

---

*[src/app/core/core.run.js, line 45 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXEW6Oh1JHFhnSzRH:-KMiXEW6Oh1JHFhnSzRI:2049132950) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/core.run.js#L45)):*
> ```JavaScript
>         /**
>          * Waits on bookmark to modify the config if needed
>          *
> ```

needs `@function readyDelay` probably `@private` as well

---

*[src/app/core/core.run.js, line 64 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXVcbMp7YlZrrZhZY:-KMiXVccDJg64LowkvXf:-221644550) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/core.run.js#L64)):*
> ```JavaScript
>         /**
>          * Allows API calls to be exposed before map creation
>          *
> ```

needs `@function preloadApiBlock` probably `@private` as well

---

*[src/app/core/core.run.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXbJAjKOS8cLwXNqr:-KMiXbJAjKOS8cLwXNqs:2146968611) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/core.run.js#L158)):*
> ```JavaScript
>          * Updates the map using bookmark. If initial is set, will only be used if its the first call to be received.
>          *
>          * @param {String} bookmark     The bookmark containing the desired state of the viewer
> ```

needs `@function useBookmark`

---

*[src/app/core/reload.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiY89nUokxWNb5jZsE:-KMiY89nUokxWNb5jZsF:1522974903) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L30)):*
> ```JavaScript
>          * Maintains state over projection switch. Updates the config to the current state,
>          * sets the new basemap, and then reloads the map.
>          *
> ```

needs `@function loadNewProjection`

---

*[src/app/core/reload.service.js, line 35 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiYDeRhMCznuO4ZlMv:-KMiYDeRhMCznuO4ZlMw:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L35)):*
> ```JavaScript
>         function loadNewProjection(basemapId) {
>             $rootScope.$broadcast(events.rvApiHalt);
>             let bookmark = bookmarkService.getBookmark();
> ```

const

---

*[src/app/core/reload.service.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiY4ZcAaeUbQMEfmS8:-KMiY4ZcAaeUbQMEfmS9:1690007928) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L52)):*
> ```JavaScript
>          * Maintains state over language switch. Gets the current state, switches to the new lang and its config,
>          * and then reloads the map.
>          *
> ```

needs `@function loadNewLang`

---

*[src/app/core/reload.service.js, line 67 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXv0MxniwcYYS7l4p:-KMiXv0MxniwcYYS7l4q:1304854654) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L67)):*
> ```JavaScript
>         /**
>          * Applies 'bookmark' to the config and then broadcasts the bookmarkReady event or reloads the map
>          *
> ```

needs `@function loadWithBookmark`

---

*[src/app/core/reload.service.js, line 72 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiYYX8xt2_f_NmbdjL:-KMiYYX8xt2_f_NmbdjM:-494564642) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L72)):*
> ```JavaScript
>          */
>         function loadWithBookmark(bookmark, initial) {
>             // only let the call through if its first and the initial call, or its not the initial call
> ```

grammar: it's (both cases)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Comment by spencerwahl** [comment]
Review status: 2 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/app/bootstrap.js, line 110 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiVTWknyaqsM1MRjud:-KMiygchtc_uLIRPngZt:1702014766) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/bootstrap.js#L110)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> comments please; when there was only one of them I kind of had an idea what they were doing now I have absolutely none
</details>
Note: After a short discussion between Aly and I we concluded the API has to change internally. Its becoming too difficult to add new behaviour, and when we are able it becomes much more confusing to use.

---

*[src/app/bootstrap.js, line 157 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiVP3fzW_TCJr_fC6D:-KMj11Q3Rkdcdg72CCQ6:2101406251) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/bootstrap.js#L157)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> duplicated code :sparkles: 
</details>
see above

---

*[src/app/core/bookmark.service.js, line 134 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiVnEuKyHUvIZPVH0l:-KMj0ZFUWcOMuxlDK9_n:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/bookmark.service.js#L134)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---

*[src/app/core/bookmark.service.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiW8krsame1Mdk4yyj:-KMj0YEyl_w-6WlC5Pcs:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/bookmark.service.js#L138)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `configSnippets = rcsConfigs.map(cfg => angular.merge(cfg, rcsBookmars[cfg.id]))` ?
</details>
Done.

---

*[src/app/core/config.service.js, line 196 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiWpWI9OY0r0hn6e9A:-KMj00ctV1JN81jb9ao8:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/config.service.js#L196)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs `@function setCurrent`
</details>
Done.

---

*[src/app/core/constant.service.js, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiX2hAkIcpqyAtoeMJ:-KMj1n5yXxQejus7aBK0:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/constant.service.js#L28)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> These need descriptions.  Either here or in a new docs page describing our events.
</details>
Done.

---

*[src/app/core/core.run.js, line 45 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXEW6Oh1JHFhnSzRH:-KMj0-uIRGiCa_JuVgGq:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/core.run.js#L45)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs `@function readyDelay` probably `@private` as well
</details>
Done.

---

*[src/app/core/core.run.js, line 64 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXVcbMp7YlZrrZhZY:-KMj-zKJe3gA731N3IRU:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/core.run.js#L64)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs `@function preloadApiBlock` probably `@private` as well
</details>
Done.

---

*[src/app/core/core.run.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXbJAjKOS8cLwXNqr:-KMj-zdngX1bb8hgX8qH:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/core.run.js#L158)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs `@function useBookmark`
</details>
Done.

---

*[src/app/core/reload.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiY89nUokxWNb5jZsE:-KMj0s7HzF3l6chHUm6L:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L30)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs `@function loadNewProjection`
</details>
Done.

---

*[src/app/core/reload.service.js, line 35 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiYDeRhMCznuO4ZlMv:-KMj0rt2lIj-BbeJj1qD:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L35)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> const
</details>
Done.

---

*[src/app/core/reload.service.js, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiY4ZcAaeUbQMEfmS8:-KMj0sVMpa93iHu7DjEi:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L52)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs `@function loadNewLang`
</details>
Done.

---

*[src/app/core/reload.service.js, line 67 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiXv0MxniwcYYS7l4p:-KMj0szdkpRx9vylrS9V:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L67)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs `@function loadWithBookmark`
</details>
Done.

---

*[src/app/core/reload.service.js, line 72 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMiYYX8xt2_f_NmbdjL:-KMj0w3q5HUq1U4YHVB1:649739453) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72bcf58c4bf52a795c3d960b8a8b2bb41c3ca34a/src/app/core/reload.service.js#L72)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> grammar: it's (both cases)
</details>
bad habit :speak_no_evil: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-:-KMj9xqd5BvKIB_F66OO:1417088721)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 133 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMjlRCA5YxSq3s3yvOZ:-KMjlRCA5YxSq3s3yvO_:-778629168) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f58330b6aba467807eded89f96d137bea8a45c4/src/app/geo/map.service.js#L133)):*
> ```JavaScript
>                 service.mapManager.BasemapControl.setBasemap(geoState.selectedBaseMapId);
> 
>                 if (config.map.initialBasemapId && config.map.initialBasemapId.startsWith('blank_basemap_')) {
> ```

hardcoded prefix check on an id: :trophy: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Comment by spencerwahl** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 133 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMjlRCA5YxSq3s3yvOZ:-KMjmiV505s7PeVmyS7e:-881900584) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f58330b6aba467807eded89f96d137bea8a45c4/src/app/geo/map.service.js#L133)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> hardcoded prefix check on an id: :trophy: 
</details>
Done-ish

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 133 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904#-KMjlRCA5YxSq3s3yvOZ:-KMjmqj5WVtGspDKlAea:1914656886) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f58330b6aba467807eded89f96d137bea8a45c4/src/app/geo/map.service.js#L133)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> Done-ish
</details>
:trophy: / 2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Comment by james-rae** [comment]
Reviewed 7 of 7 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Comment by cynngah** [comment]
Reviewed 1 of 9 files at r1, 7 of 7 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/904)*

**Pull request merged**
