### PR TITLE
feat(export): allow markdown in generated legend

### LINKED ISSUE #2392: Render markdown of info sections in the export image
#2389 adds export support to legend info sections, but markdown content can only be represented as plain text so far:

There are some options to implement that:
- find or build a markdown-to-svg/canvas converter :) maybe use something like [spongedown](https://ivanceras.github.io/spongedown/)
- [draw rendered markdown html to a canvas by wrapping it in an svg element](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas)
- ~~use [html2canvas](https://github.com/niklasvh/html2canvas) library or something similar to create canvas representations of rendered info sections~~
  - bad solution - if we turn info sections straight into images and then add them to the legend, the legend might further scale the images to fit in the export legend column. This will distort the text, potentially making it illegible. 

The last one seems the most promising - at least it should fast to check if this approach works or not.

Highcharts seems to use a server call to export their graphs as images. Moreover, their graphs are rendered as svg from the start, so all the labels and their styling are svg-based, and are relatively easy to draw on a canvas as is.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2392

## Testing
Many :eyes: 's on chrome

## Documentation
Inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2402)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-:-KuzBKO9C8-nb4EnnNCY:bnfp4nl)*

**Comment by AleksueiR** [comment]
Doesn't work in IE :( 


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/export/export-legend.service.js, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-Kv25WRaozC0FDht_lrK:-Kv25WRaozC0FDht_lrL:b-v1innm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/14641760bf7ce6be80935a4aed7db0c012dcdc40/src/app/ui/export/export-legend.service.js#L453)):*
> ```JavaScript
>                     let correctedWidth = Math.min(300, actualWidth);
>                     // estimate the rendered height
>                     let approxHeight = Math.ceil(actualWidth / correctedWidth) * 25 + 25;
> ```

Line height for this kind of text is 20px. This will obviously not work if there are any headers or tables or images in the markdown.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-:-Kv25rxk1poNtEJMNNZE:bgb8n6b)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 447 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-Kv3mq8bhCq9WwC6adza:-Kv3mq8bhCq9WwC6adzb:bk2o8b8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/14641760bf7ce6be80935a4aed7db0c012dcdc40/src/app/ui/export/export-legend.service.js#L447)):*
> ```JavaScript
>                     const canvas = service.canvas || (service.canvas = document.createElement('canvas'));
>                     const ctx = canvas.getContext('2d');
>                 
> ```

Evil Spaces

---

*[src/app/ui/export/export-legend.service.js, line 473 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-Kv3myd5OdG13b2jGalB:-Kv3myd6X--1qtjwxrJ7:bb7dhz5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/14641760bf7ce6be80935a4aed7db0c012dcdc40/src/app/ui/export/export-legend.service.js#L473)):*
> ```JavaScript
>                       DOMURL.revokeObjectURL(url);
>                     }
>                     
> ```

bad!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402)*

**Comment by milesap** [comment]
Linux PC at home so can't debug IE bug, will do when back at office

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 447 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-Kv3mq8bhCq9WwC6adza:-KvShJYYFL3nZgNLsTV6:b-yy0tub) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7ab28f6fc5e03c15ccd4d0cd27bb62778d1fc67c/src/app/ui/export/export-legend.service.js#L447)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Evil Spaces
</blockquote></details>

Evil spaces destroyed

---

*[src/app/ui/export/export-legend.service.js, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-Kv25WRaozC0FDht_lrK:-KvShNn_hDElJzQOe6zb:bqwjt35) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7ab28f6fc5e03c15ccd4d0cd27bb62778d1fc67c/src/app/ui/export/export-legend.service.js#L453)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Line height for this kind of text is 20px. This will obviously not work if there are any headers or tables or images in the markdown.
</blockquote></details>

Changed 25 -> 20

---

*[src/app/ui/export/export-legend.service.js, line 473 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-Kv3myd5OdG13b2jGalB:-KvShMuyxd5h6qKLSyOT:b-yy0tub) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7ab28f6fc5e03c15ccd4d0cd27bb62778d1fc67c/src/app/ui/export/export-legend.service.js#L473)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

bad!
</blockquote></details>

Evil spaces destroyed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-:-KvSh3OV-ZHvLkVOEWIP:bybavhj)*

**Comment by milesap** [comment]
ie silently fails, not surprised since there is some fancy canvas work being done. I'm now stripping markdown for IE. Also, the 25 size height estimation is needed, going lower produces cut off text.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402#-:-KvbET6I1mLStD1yVriO:bdhfngj)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402)*

**Comment by barryytm** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2402)*

**Pull request merged**
