### PR TITLE
feat(ui): Layer symbology stack improvements

### LINKED ISSUE #1425: Layer Symbology stack can be opened from Layer Menu
- [x] Add menu option (Show legend) to the layers drop down menu (this will add another way of opening the symbology stack)
- [x] Fan out icons when hovering over a legend record

**Usability Issue:**
V4. Unable to find and open the symbology (Type: Design)

Inside the legend most testers were not aware that the symbology icons (including animations) were clickable.  After assistance some testers were able to open it and asked that an expandable arrow be used to indicate that this part is expandable.

### PR DESCRIPTION
**Pull request by milesap**
## Description
When hovering over a layer, the symbology stack is fanned out. Also added
an option in the layer menu to 'Show Legend'.

Closes #1425

## Testing
:eye: 

## Documentation
None needed

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1489)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn1eoQ_bUkKxoqFaBJ:-KYn1eoQ_bUkKxoqFaBK:b5htuzk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/entry-symbology.directive.js#L54)):*
> ```JavaScript
> 
>             self.expanded = false; // holds the state of symbology section
>             self.entry.toggleSymbology = self.toggleSymbology = toggleSymbology;
> ```

I would attach `wiggleSymbology` and `toggleSymbology` functions to the `symbology` object, not the `entry` as it's not directly related to it. Then it can be called as `self.entry.symbology.wiggleSymbology(false)` in the layer template.

---

*[src/app/ui/toc/toc.service.js, line 115 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn48eMkmgudZ3lB_h7:-KYn48eMkmgudZ3lB_h8:bqucyvv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/toc.service.js#L115)):*
> ```JavaScript
>                     action: entry => {
>                         entry.toggleSymbology();
>                         entry.wiggleSymbology();
> ```

`toggleSymbology` should be enough on its own.

---

*[src/app/ui/toc/templates/layer-entry.html, line 16 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn3m0oEsiM4BoWWEGi:-KYn3m0oEsiM4BoWWEGj:bhf9q5y) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/templates/layer-entry.html#L16)):*
> ```HTML
>     ng-mouseover="self.entry.wiggleSymbology(true)"
>     ng-mouseleave="self.entry.wiggleSymbology(false)"
>     ng-if="!self.entry.options.data">
> ```

If you remove `ng-if` here, mouseover and mouseleave listeners in the button above can also be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-:-KYn4FEtKzpp9WTWigVv:bnfp4nl)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn1eoQ_bUkKxoqFaBJ:-KYnPUKLNyFKwu9VThq7:b84oph9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/entry-symbology.directive.js#L54)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I would attach `wiggleSymbology` and `toggleSymbology` functions to the `symbology` object, not the `entry` as it's not directly related to it. Then it can be called as `self.entry.symbology.wiggleSymbology(false)` in the layer template.
</blockquote></details>

`entry.symbology` is an array, not sure if converting it to an object would start breaking other things

---

*[src/app/ui/toc/toc.service.js, line 115 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn48eMkmgudZ3lB_h7:-KYnPmNuIE2cBhvR46fS:bhrmuoz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/toc.service.js#L115)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`toggleSymbology` should be enough on its own.
</blockquote></details>

If I remove `wiggleSymbology` then when I collapse symbology from the menu they remain fanned out. This seems to fix that.

---

*[src/app/ui/toc/templates/layer-entry.html, line 16 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn3m0oEsiM4BoWWEGi:-KYnQKAI570NNz6XmJB-:b-xv107x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/templates/layer-entry.html#L16)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

If you remove `ng-if` here, mouseover and mouseleave listeners in the button above can also be removed.
</blockquote></details>

If I remove `ng-if` then clicking on the layers will not open the datatable (since this div blocks the button above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn1eoQ_bUkKxoqFaBJ:-KYn_6gO_Mr8Wz9orqBL:bltc9yw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/entry-symbology.directive.js#L54)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

`entry.symbology` is an array, not sure if converting it to an object would start breaking other things
</blockquote></details>

Alex and I think leave it as is for now, revisit during the big geo module refactor.  Please leave a FIXME around so it's easy to find later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn1eoQ_bUkKxoqFaBJ:-KYnROv8ztMUvjlXZUk9:brkmnca) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/entry-symbology.directive.js#L54)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Alex and I think leave it as is for now, revisit during the big geo module refactor.  Please leave a FIXME around so it's easy to find later.
</blockquote></details>

Fair enough; it's good for now then.

---

*[src/app/ui/toc/toc.service.js, line 115 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn48eMkmgudZ3lB_h7:-KYnRfSOKz3-EiG-ZAov:b-xaf1sg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/toc.service.js#L115)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

If I remove `wiggleSymbology` then when I collapse symbology from the menu they remain fanned out. This seems to fix that.
</blockquote></details>

Ah, makes sense now. The original toggle function assumes you are clicking on the symbology toggle button directly, so the icons should stay fanned out when it collapses.

---

*[src/app/ui/toc/templates/layer-entry.html, line 16 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn3m0oEsiM4BoWWEGi:-KYnSIGnEa7maZ2FnPck:b-1jsrq2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/templates/layer-entry.html#L16)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

If I remove `ng-if` then clicking on the layers will not open the datatable (since this div blocks the button above)
</blockquote></details>

Yeah... good enough for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489)*

**Comment by milesap** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489#-KYn1eoQ_bUkKxoqFaBJ:-KYnzmybvRO4OzjjWipz:b-q7zapf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4185608df05ea4318d25a54e96340e07178de02e/src/app/ui/toc/entry-symbology.directive.js#L54)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Fair enough; it's good for now then.
</blockquote></details>

Left a `TODO`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1489)*

**Pull request merged**
