### PR TITLE
fix(datatable): truncate long column headings

### LINKED ISSUE #2151: Long Column headings will need to be truncated in  datatable
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html

Test data http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_census_of_agriculture_2011_ccs/MapServer
Select "**Characteristics of farm operators**

Long column names will need to be truncated or column should be resized to fit the header text. 

image
image

### PR DESCRIPTION
**Pull request by milesap**
## Description
No longer overflows its container. Test on config 37

Closes #2151

## Testing
:eyes: on chrome

## Documentation
none

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2173)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2173#-:-Kowwyqhx8MV69KXI_gU:bnfp4nl)*

**Comment by JahidAhmed** [comment]
Is there any way to still view the entire column name, like on hover or something similar?

**Comment by AleksueiR** [comment]
Agree, need a hover tooltip for truncated names. There is no sense in truncating them if we don't provide a way to see the full text.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2173#-:-Kp06CQBII8wsEoOa3t4:bw7imx6)*

**Comment by milesap** [comment]
:+1: Added `title` attribute so the full text of truncated headings can still be read on hover

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2173#-:-KpG4NM3ciUi4Ub8i4pQ:b-ksre38)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2173#-:-KpKPCAw5NySngw4NGaz:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2173)*

**Pull request merged**
