### PR TITLE
fix(ui): adjust icon opacity to obtain 3:1 contrast with background

### LINKED ISSUE #3915: WCAG: Interactive controls don't have a border or any identifier that passes the minimum contrast requirements of 3:1 with the background
Spawned from #3892.

"Make the buttons and icons darker. Make it at least #929292"

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #3915 

Crazy changes in this PR: I've changed the opacity of icons (when not hovered) within the app from `0.62` to `0.72` in order to ensure that the colour remains below `#929292`. I've also darkened the `$primary-color` value from `#607d8b` to `#536c77`.

Here are before and after pictures:

😠 **Before** 😠 

✨ **After** ✨ 

The colour picker tool in paint.net says that the icon colour is now `#919191` when not hovered, which should satisfy the requirement.

You can find a demo of this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3915/samples/index-samples.html).

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3944)

### CODE REVIEW

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3944)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by sharvenp — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3944)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by elsa-huang — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3944)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by milespetrov — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3944)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3944)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by james-rae — APPROVED** [review]
You madlad.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3944#-:-McjGDJYCF1w3DAK_uoU:bopn72h)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
