### PR TITLE
Apply filter to layers on the map on load

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2120, as title
## Testing

Manually, try No. 46 in `index-samples`
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2354)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
I get errors trying to load `index-mobile`



---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-:-Ksiex9f1zqmT7EWz2Z-:bj5r8mn)*

**Comment by AleksueiR** [comment]
I feel the legend service is not the best place for this code. The legend service should not ideally mess directly with proxy object or their wrappers. A better place would be in toc: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/toc/toc.directive.js#L260

There is already listener for layers being loaded, and some datatable logic that opens the panel if specified in the config. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-:-KsjFBKoBV7KTM6ouEls:bip6u70)*

**Comment by barryytm** [comment]
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/toc/toc.directive.js#L260 was not triggered in anyways.  The initial apply for filter should also work for the children of dynamic layers, therefore requiring a work through to the layer structure.  Is there another place for that?

**Comment by AleksueiR** [comment]
This is odd. Let me check.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-:-KsmrYbFF38MvhWLWZMd:b3xntt)*

**Comment by AleksueiR** [comment]
Ah, right, this only happens if the table needs to be opened initially. Nonetheless, you can add another listener to the toc service for example and apply filters there.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-:-KsmsH_LZi8z-SoZXBUD:b-z2x5k5)*

**Comment by JahidAhmed** [comment]
When you make your changes, can you also display the filter flag on the layers where there are filters applied to the map

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-:-KsnNWLLfPijye_GGFs5:b-t68aka)*

**Comment by JahidAhmed** [comment]
A few things:

1. `index-mobile` is throwing errors again; not loading.
2. Can you change the sample so dynamic layer group so that only one of them has filters initially.
3. Can you also change it so that any one layer has multiple columns displayed but not all columns have filters initially applied. (So like `3 column filters` for example, remove the filter from `OBJECTID`, leave the other two columns with filters)

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-:-Kst7tOtm4jQEFrjFEz6:bsvnlnu)*

**Comment by JahidAhmed** [comment]
If you open the datatable for a layer and then reload it (before or after closing the datatable, doesn't matter) the filter flag will disappear and then when you re-open the table, the `Apply To Map` button is visible but the filters are already applied

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-:-KstMr-9MYxmT4QBF4qT:b-lrric3)*

**Comment by james-rae** [comment]
Reviewed 4 of 7 files at r5, 2 of 3 files at r7, 1 of 1 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 137 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KstsFYezDnVaXi2-a67:-KstsFYezDnVaXi2-a68:b-8fhwmb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L137)):*
> ```JavaScript
>          * @return {string} the Assembled query definition of the layer
>          */
>         _getassembledDefintion(columns) {
> ```

captial A.  `_getAssembledDefintion`

---

*[src/app/geo/layer-blueprint.class.js, line 146 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-Kstt7P7_Gia_QTdImnS:-Kstt7P7_Gia_QTdImnT:b-juy5uw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L146)):*
> ```JavaScript
>             });
> 
>             defs = defs.join(' AND ');
> ```

just return the `join` result. 
`return defs.join(' AND ');`

---

*[src/app/geo/layer-blueprint.class.js, line 161 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KstshzIvyyCBe0ngUVF:-KstshzIvyyCBe0ngUVG:bv0o26o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L161)):*
> ```JavaScript
>          * @return {Array} defs definition queries array
>          */
>         _getFilterDefintion(defs, column) {
> ```

rather than passing in an empty array that gets modified and returned, drop the param and just do `const defs = [];` at start of function.

---

*[src/app/geo/layer-blueprint.class.js, line 209 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KsttQIMLWYcH3eNP4WC:-KsttQIMLWYcH3eNP4WD:b-qi2w2o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L209)):*
> ```JavaScript
>          */
>         generateLayer() {
>             if (this.config.layerType === layerTypes.ESRI_DYNAMIC) {
> ```

can we have a comment explaining that `filterQuery` is a temporary property, used only at startup?

---

*[src/app/ui/toc/toc.directive.js, line 267 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-Kstu5CMImJ7rP4vlMk3:-Kstu5CMImJ7rP4vlMk4:b1kkwew) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/ui/toc/toc.directive.js#L267)):*
> ```JavaScript
>         ref.initialDynamicLayerFilter();
>         ref.initialDynamicLayerFilter = events.$on(events.rvLayerRecordLoaded, (_, layerRecordId) => {
>             let layerRecord = layerRegistry.getLayerRecord(layerRecordId);
> ```

`const`

---

*[src/app/ui/toc/toc.directive.js, line 270 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KstuLmda_ZI7HDgiCsG:-KstuLmda_ZI7HDgiCsH:b-so74tp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/ui/toc/toc.directive.js#L270)):*
> ```JavaScript
> 
>             if (layerRecord.layerType === 'esriDynamic') {
>                 for (let i = 0; i < layerRecord.config.layerEntries.length; i ++) {
> ```

use `forEach`
```
layerRecord.config.layerEntries.forEach(currentSubLayer => {
   <your if block logic here>
});
```

---

*[src/app/ui/toc/toc.directive.js, line 273 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-Kstugi32laeTtCdUrdi:-Kstugi32laeTtCdUrdj:b1kkwew) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/ui/toc/toc.directive.js#L273)):*
> ```JavaScript
>                     let currentSubLayer = layerRecord.config.layerEntries[i];
>                     if (currentSubLayer.table && currentSubLayer.table.applyMap) {
>                         let proxy = layerRecord.getChildProxy(currentSubLayer.index);
> ```

`const`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by james-rae** [comment]
*[src/app/geo/layer-blueprint.class.js, line 161 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KstshzIvyyCBe0ngUVF:-Ksu1sVmohPsBSxPE_ko:b8t0l7e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L161)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

rather than passing in an empty array that gets modified and returned, drop the param and just do `const defs = [];` at start of function.
</blockquote></details>

Ignore. I missed that it was being called inside a column loop in the function above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by barryytm** [comment]
Review status: 6 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 137 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KstsFYezDnVaXi2-a67:-KsxbkRFGKErrGI9Qlru:b-c5ec4x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L137)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

captial A.  `_getAssembledDefintion`
</blockquote></details>

done, thank

---

*[src/app/geo/layer-blueprint.class.js, line 146 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-Kstt7P7_Gia_QTdImnS:-KsxbmTPRF6USkuiwJgV:b-r18wje) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L146)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

just return the `join` result. 
`return defs.join(' AND ');`
</blockquote></details>

done, thanks

---

*[src/app/geo/layer-blueprint.class.js, line 161 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KstshzIvyyCBe0ngUVF:-KsxbpAe7YbNGvmUQAKB:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L161)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Ignore. I missed that it was being called inside a column loop in the function above.
</blockquote></details>

done, thanks

---

*[src/app/geo/layer-blueprint.class.js, line 209 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KsttQIMLWYcH3eNP4WC:-KsxbpgauFccd7IRUEGl:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/geo/layer-blueprint.class.js#L209)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can we have a comment explaining that `filterQuery` is a temporary property, used only at startup?
</blockquote></details>

done, thanks

---

*[src/app/ui/toc/toc.directive.js, line 267 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-Kstu5CMImJ7rP4vlMk3:-KsxbqFvsaxhZq14Basx:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/ui/toc/toc.directive.js#L267)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`const`
</blockquote></details>

done, thanks

---

*[src/app/ui/toc/toc.directive.js, line 270 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KstuLmda_ZI7HDgiCsG:-KsxbqfHfqBC0QGVHvs4:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/ui/toc/toc.directive.js#L270)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

use `forEach`
```
layerRecord.config.layerEntries.forEach(currentSubLayer => {
   <your if block logic here>
});
```
</blockquote></details>

done, thanks

---

*[src/app/ui/toc/toc.directive.js, line 273 at r10](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-Kstugi32laeTtCdUrdi:-Ksxbr1qb5t--hTGodkk:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e342f4ccab61ead43ae26d145a931d40b313bc/src/app/ui/toc/toc.directive.js#L273)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`const`
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 7 files at r5, 1 of 3 files at r7, 2 of 2 files at r10, 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-blueprint.class.js, line 160 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtGrdZiooHLexozkrbY:-KtGrdZiooHLexozkrbZ:b-6ed4xl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/110e4cf976f0982f847cca326facb416de01887b/src/app/geo/layer-blueprint.class.js#L160)):*
> ```JavaScript
>          */
>         _getColumnFitlerDefintion(defs, column) {
>             /*jshint maxcomplexity:11 */
> ```

We don't use `jshint` anymore.

---

*[src/app/geo/layer-blueprint.class.js, line 203 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtGpROu3hh-TbH4ylXh:-KtGpROu3hh-TbH4ylXi:b-qlpdqe) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/110e4cf976f0982f847cca326facb416de01887b/src/app/geo/layer-blueprint.class.js#L203)):*
> ```JavaScript
>          * Generates a layer from an online service based on the layer type.
>          * Takes a layer in the config format and generates an appropriate layer object.
>          * Create a temporary property filteredQuery to store the computed results for dynamic layers
> ```

Even if this property is temporary, I suggest adding it to the class definitions. Name it `initialFilteredQuery` to highlight it's only used at the beginning, and you don't even need to delete it in `toc`.

---

*[src/app/ui/toc/toc.directive.js, line 269 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtGs1uXAjp6S7e8s4yT:-KtGs1uXAjp6S7e8s4yU:bd1195s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/110e4cf976f0982f847cca326facb416de01887b/src/app/ui/toc/toc.directive.js#L269)):*
> ```JavaScript
>             const layerRecord = layerRegistry.getLayerRecord(layerRecordId);
> 
>             if (layerRecord.layerType === 'esriDynamic') {
> ```

Use `Geo.Layer.Types.ESRI_DYNAMIC` instead of the hardcoded name. You might need to import `Geo`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/ui/table/table-default.directive.js, line 468 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtHQRCsgUagOhxdjB4H:-KtHQRCsgUagOhxdjB4I:bn8t4rg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cac9bae24acc484d293386f865bb7de9f270cbd9/src/app/ui/table/table-default.directive.js#L468)):*
> ```JavaScript
>                     // set applyMap to false so when table reopen, filter are not reapply to map.
>                     // they need to be apply only when table opens the first time
>                     config.applyMap = false;
> ```

So we shouldn't actually be removing this line. Removing this results in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2203 occurring again. (Check other comment)

---

*[src/app/ui/toc/toc.service.js, line 66 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtHQrXVaLXNgWo6xn28:-KtHQrXVaLXNgWo6xn29:b-ftuqup) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/110e4cf976f0982f847cca326facb416de01887b/src/app/ui/toc/toc.service.js#L66)):*
> ```JavaScript
> 
>         // reset filter flag
>         legendBlock.filter = config.applyMap;
> ```

I think we can add another property somewhere else and set it to the initial value of `config.applyMap` and here use that property instead so that the filter flag stays consistent but `config.applyMap` is also set to false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by barryytm** [comment]
Review status: 4 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 160 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtGrdZiooHLexozkrbY:-KtHqUQpODdJVlMCXtnh:b-5iwing) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6381ce371f76b917fd97b3edb4402cdc7aa5312/src/app/geo/layer-blueprint.class.js#L160)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

We don't use `jshint` anymore.
</blockquote></details>

deleted it, thanks

---

*[src/app/geo/layer-blueprint.class.js, line 203 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtGpROu3hh-TbH4ylXh:-KtHqW-znfbEI3tdaoSb:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6381ce371f76b917fd97b3edb4402cdc7aa5312/src/app/geo/layer-blueprint.class.js#L203)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Even if this property is temporary, I suggest adding it to the class definitions. Name it `initialFilteredQuery` to highlight it's only used at the beginning, and you don't even need to delete it in `toc`.
</blockquote></details>

done, thanks

---

*[src/app/ui/table/table-default.directive.js, line 468 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtHQRCsgUagOhxdjB4H:-KtHqZEZMBjx0bE41ViS:bqx43ss) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/72df7357f82a558cda343ad5b3b4b70b9dd2ade7/src/app/ui/table/table-default.directive.js#L468)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

So we shouldn't actually be removing this line. Removing this results in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2203 occurring again. (Check other comment)
</blockquote></details>

put it back in, thanks

---

*[src/app/ui/toc/toc.directive.js, line 269 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtGs1uXAjp6S7e8s4yT:-KtHqc3mC7wuFgEsMe_0:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6381ce371f76b917fd97b3edb4402cdc7aa5312/src/app/ui/toc/toc.directive.js#L269)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Use `Geo.Layer.Types.ESRI_DYNAMIC` instead of the hardcoded name. You might need to import `Geo`.
</blockquote></details>

done, thanks

---

*[src/app/ui/toc/toc.service.js, line 66 at r11](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354#-KtHQrXVaLXNgWo6xn28:-KtHqdIRF2uJXUyNcpSj:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6381ce371f76b917fd97b3edb4402cdc7aa5312/src/app/ui/toc/toc.service.js#L66)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

I think we can add another property somewhere else and set it to the initial value of `config.applyMap` and here use that property instead so that the filter flag stays consistent but `config.applyMap` is also set to false
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 6 files at r12.
Review status: 6 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r12.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by james-rae** [comment]
Reviewed 1 of 6 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Comment by JahidAhmed** [comment]
Reviewed 2 of 7 files at r5, 1 of 3 files at r7, 1 of 3 files at r11, 6 of 6 files at r12.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2354)*

**Pull request merged**
