### PR TITLE
fix(table): styling enhancements

### LINKED ISSUE #2235: Table Settings Revamp
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-rc3/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction

image

### PR DESCRIPTION
**Pull request by milesap**
## Description
Table settings is now its own panel. Flex style improvements.

Closes #2235

## Testing
Chrome and IE
eagle eyes

## Documentation
None

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2275)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
I'm not sure if `Reset` is working as expected. Adding a filter and applying it to the map does not allow for it to be reset.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq3IOFHFVgwSpxp1Siy:bypap6x)*

**Comment by JahidAhmed** [comment]
Also disabling `Show Filters` and opening the settings panel hides all the filters.


---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq3JZpdGe3_rJgfo1tI:bgtwanx)*

**Comment by milesap** [comment]
#1: I haven't changed the logic behind the reset functionality, but we can either:
- reset is always active and clears all filters
- reset is only active when `Apply` is clicked and some value changes - it restores values to when the last "Apply" was clicked 
- insert third idea here

#2: You have a fix for this in `v2.0.1` not yet on `v2.1.0` 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq3QjhwpQqxYXw7Qdop:brvarbg)*

**Comment by JahidAhmed** [comment]
I think we can keep it as it currently is with it always being active, unless others prefer a different option.

Also, attempting to reorder a column above or below the columns that currently fit inside the panel does not automatically scroll the panel anymore. Is this expected behaviour?

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq3V-Nq0WbV21stJiOc:b-t9jj9t)*

**Comment by milesap** [comment]
:+1:  scroll is now working again. Also changed the reset button so it is always active.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq3uAdLTika7GVb2msd:bifsdz0)*

**Comment by JahidAhmed** [comment]
Thanks :lgtm: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq3wxDZ6GaPoCBZcD3J:b5euyw2)*

**Comment by AleksueiR** [comment]
- close button needs to be offset some more on the right similar to the close button on the datatable itself



- filter headers look too big, should probably use `md-subhead` for them


- reset and close buttons should use default button font sizes



- apply button needs to be vertically centered in the button row


and since we revamping this, can you please change `clear filter` icon and make the button disabled when no filters applied?


and to update drag target styles so it doesn't look like a whitish row with a checkbox, but as a regular row (it already has a drop shadow):


please, also, rename `Display` filter column to `Show` to make it less confusing what it is.

----

Looks way better than before :+1: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq3wqRPftD8kxZx4lZS:bgen9h6)*

**Comment by JahidAhmed** [comment]
Can we also add in an option to switch the morph value between split view and maximize in the settings panel, similar to how it is in the datatable itself

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq4IzGQ1qnKszvFko6b:bt8jbtq)*

**Comment by milesap** [comment]
:+1: didn't add morph yet as it would be a pain to do unless really needed

---

Review status: 4 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq8BjNiCxdjF3PPBxHK:bv33lxa)*

**Comment by JahidAhmed** [comment]
If the clear filters button is disabled in the table panel with no filters applied, should we change the settings panel to have the same functionality, for consistency?

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq8OS8tfaQqOdP30R4k:bra2ayy)*

**Comment by milesap** [comment]
You'd run into the same issue on settings that you posted before:

> I'm not sure if Reset is working as expected. Adding a filter and applying it to the map does not allow for it to be reset.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq8PNXjX96MubOgzUd3:b-rkv0ny)*

**Comment by JahidAhmed** [comment]
Oh yeah, that's fine then. :lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq8Q7lyvq4zvIdjcMNw:b-crwhod)*

**Comment by AleksueiR** [comment]
Some more minor change requests:
- change padding on the bottom control bar to `padding: 9px 16px;`, so the buttons are a bit offset on the right and there is some more vertical white space. Should end up looking like this:


- use solid background colour for the drag target - it's transparent right now:


---

Reviewed 4 of 7 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq9AK2Hk8J4QJNJ86UW:bif8m4l)*

**Comment by milesap** [comment]
done and done :+1: 

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275#-:-Kq9JRlrwCQEt0XX57Cs:brdjbd6)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2275)*

**Pull request merged**
