### PR TITLE
fix(ui): ESRI date field now includes time

### LINKED ISSUE #1330: Include time in ESRI date field formatting
Our formatting code for ESRI date fields is currently dropping the time portion.  Add some logic to include the time if the time is present (i.e. if time is `0:00:00`, keep formatting as-is).

Decision:  How to format the time?

* Time zones? UTC time? Convert to user local time?
* Formatting?  ISO looks bad: `2016-11-04T14:36:45.466Z`

Code location to change:
`layer-record.class.js`
```
// convert each date cell to ISO format
fieldNameArray.forEach(fieldName => {
	rows.forEach(row => {
		const date = new Date(row[fieldName]);
		row[fieldName] = date.toISOString().substring(0, 10);
	});
});
```

### PR DESCRIPTION
**Pull request by milesap**
## Description
Testing layer:
http://section917.cloudapp.net/arcgis/rest/services/TestData/TimeParty/MapServer/0

Closes #1330

## Testing
:eye: 

## Documentation
None needed

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1591)

### CODE REVIEW

**Comment by james-rae** [comment]
Some date values only have the date, not time.  Do we want to add conditional formatting to drop the time?  Currently it treats the date as if it was at midnight, then adjusts to our time zone.

Sample service: http://services.aadnc-aandc.gc.ca/geomatics/rest/services/Donnees_Ouvertes-Open_Data/Bail_minier_NU_Mining_Lease/MapServer/0/

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-KaNykRGAIk1h28eH5U6:be4txpd)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 271 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KaO-YWxrA2aH8XgMXnz:-KaO-YWxrA2aH8XgMXo-:blur5i0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/873031353718ed94029ca9b4674ca14c30c3dcff/src/app/geo/layer-record.class.js#L271)):*
> ```JavaScript
>                 fieldNameArray.forEach(f =>
>                     rows.forEach(r =>
>                         r[f] = moment.tz(r[f], moment.tz.guess()).format('YYYY-MM-D H:MM:SSA z')
> ```

I think we should not change underlying data and to format data directly ar - or as close to - the template level.
Also, `LayerRecord` will eventually be moved to the geoApi and it shouldn't rely on the `moment` library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by james-rae** [comment]
More on this: a date value of `1514332800000` is in reality `27-Dec-2017`. When pushed to our timezone, it becomes `26-Dec-2017 7:00 pm`, which is true, but may also fool the user because the date is different.  On top of that, the `moment` library is super precise, and appears to add leap minutes, so in the grid we see `26-Dec-2017 7:12 pm`, making it appear as an exact time instead of just a date.

Currently trying to find a way to detect when an epoch time value is considered "Date Only"

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-KaO0ciSMlJOfBqJJFHJ:b2vbikm)*

**Comment by milesap** [comment]
:thinking: and that's why I never use epoch time

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 271 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KaO-YWxrA2aH8XgMXnz:-KaO4yrHbcrMwWUN4bgY:b4g14bs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/873031353718ed94029ca9b4674ca14c30c3dcff/src/app/geo/layer-record.class.js#L271)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think we should not change underlying data and to format data directly ar - or as close to - the template level.
Also, `LayerRecord` will eventually be moved to the geoApi and it shouldn't rely on the `moment` library.
</blockquote></details>

Ok, moved into `filters-default.directive.js` as the closest place to it being rendered (passed into DataTable instance).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-KaO5GfigMNbUC2TqZjz:b-ju6tl3)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 201 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KaO66qX3Vaj9JpFXPkT:-KaO66qX3Vaj9JpFXPkU:b-nzwoc9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fe3792a36a202d20e9016edbbe5adac6be332c9a/src/app/ui/filters/filters-default.directive.js#L201)):*
> ```JavaScript
>                             // convert each date cell to a better format
>                             displayData.rows.forEach(r =>
>                                 r[field.name] = moment.tz(r[field.name], userTimeZone).format('YYYY-MM-D H:MM:SSA z')
> ```

Nice, can you also turn this into an Angular filter and add it to the `app/common/formatters.filter.js` along with the `autolink` filter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by milesap** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 201 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KaOE_sRQEDjffzOyoBs:-KaOE_sRQEDjffzOyoBt:bklzo7f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fe3792a36a202d20e9016edbbe5adac6be332c9a/src/app/ui/filters/filters-default.directive.js#L201)):*
> ```JavaScript
>                             // convert each date cell to a better format
>                             displayData.rows.forEach(r =>
>                                 r[field.name] = moment.tz(r[field.name], userTimeZone).format('YYYY-MM-D H:MM:SSA z')
> ```

Ok moved into a filter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by milesap** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 201 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KaO66qX3Vaj9JpFXPkT:-KaOH91xFiuImEqav7nK:b12ohq2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fe3792a36a202d20e9016edbbe5adac6be332c9a/src/app/ui/filters/filters-default.directive.js#L201)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Nice, can you also turn this into an Angular filter and add it to the `app/common/formatters.filter.js` along with the `autolink` filter?
</blockquote></details>

Ok moved into `formatters.filter.js`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 201 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KaO66qX3Vaj9JpFXPkT:-KaOIUex2QcxF5ncKIuN:b-83sjoh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fe3792a36a202d20e9016edbbe5adac6be332c9a/src/app/ui/filters/filters-default.directive.js#L201)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Ok moved into `formatters.filter.js`
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by AleksueiR** [comment]
Cannot open details for any of the sample layer features. 

Get the following console error:
>RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at http://fgpv.cloudapp.net/demo/users/milesap/1330-esri-time/prod/lib/core.js:45:29759

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-KaOKKSssTGgmcse1ajx:b-bi9d6k)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by milesap** [comment]
:+1:  fixed

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-KabQrq8aBR22Is7NOLZ:bhw7gfp)*

**Comment by AleksueiR** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/identify.service.js, line 117 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabYTQ9UCMBgD_yoqOX:-KabYTQ9UCMBgD_yoqOY:bwe9kj8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/geo/identify.service.js#L117)):*
> ```JavaScript
> 
>                         if (layerRegistry.checkDateType(key, fields) && val.length > 10) {
>                             val = $filter('dateTimeZone')(val);
> ```

Value formatting should be done on the template, instead of the identify service.
You can put it here, along with the `autolink` filter: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/details/details-record-esrifeature.directive.js#L77
This way there is also no need to check if the date passed to the filter is already formatted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by milesap** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/identify.service.js, line 117 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabYTQ9UCMBgD_yoqOX:-Kab_04S4daAK6WsUvDF:b-nvzaey) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/geo/identify.service.js#L117)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Value formatting should be done on the template, instead of the identify service.
You can put it here, along with the `autolink` filter: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/details/details-record-esrifeature.directive.js#L77
This way there is also no need to check if the date passed to the filter is already formatted.
</blockquote></details>

It seems `$filter('autolink')` is called for every item, but `$filter('dateTimeZone')` is only for date fields

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by alyec** [comment]
Getting a bunch of
```plain
Error: Error performing query operation
    at Object.h.load (init.js:896)
    at init.js:181
    at c (init.js:66)
    at d (init.js:66)
    at b.Deferred.resolve.callback (init.js:67)
    at c (init.js:66)
    at d (init.js:66)
    at b.Deferred.resolve.callback (init.js:67)
    at init.js:185
    at k (init.js:189)
```
in my console.  Don't know if this is a viewer issue or a service issue.

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/common/formatters.filter.js, line 28 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabZ1mOwoVQ3YVgbLxh:-KabZ1mOwoVQ3YVgbLxi:bwg8iqm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/common/formatters.filter.js#L28)):*
> ```JavaScript
>          * @function dateTimeZone
>          * @param {Number} esriDate epoch time to convert
>          * @param {String} format moment format string for output date/time
> ```

Please add the optional status and the default in the jsdoc string
http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-Kab_cXpS42h0GbL4y0O:be3vg14)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/identify.service.js, line 117 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabYTQ9UCMBgD_yoqOX:-Kab_xI6MGyUWZa0ccyo:b3nrzz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/geo/identify.service.js#L117)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

It seems `$filter('autolink')` is called for every item, but `$filter('dateTimeZone')` is only for date fields
</blockquote></details>

Right, that would be a problem. Maybe we should start passing field type to the details panel as well.
@alyec , what do you think? Should we apply formatting here or in the details panel?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/identify.service.js, line 117 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabYTQ9UCMBgD_yoqOX:-KabaH-yzkGlTN-JP6NE:b-c4s4sv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/geo/identify.service.js#L117)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Right, that would be a problem. Maybe we should start passing field type to the details panel as well.
@alyec , what do you think? Should we apply formatting here or in the details panel?
</blockquote></details>

Generally I'd go with put the formatting as close to the presentation code as possible (i.e. template) but I'm not sure I follow the tradeoff in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/identify.service.js, line 117 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabYTQ9UCMBgD_yoqOX:-Kabb8C1ahwxDLOytJ-q:b-u5n2l5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/geo/identify.service.js#L117)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Generally I'd go with put the formatting as close to the presentation code as possible (i.e. template) but I'm not sure I follow the tradeoff in this case.
</blockquote></details>

We only want to format date fields, and to distinguish them from other fields in the template we need a fieldtype passed to the template's directive. That's the tradeoff - pass another parameter to the details panel or format inside the identify service.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by milesap** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/formatters.filter.js, line 28 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabZ1mOwoVQ3YVgbLxh:-KabbXKgF00uZUISviZ5:b-k1hz2j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/common/formatters.filter.js#L28)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Please add the optional status and the default in the jsdoc string
http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values
</blockquote></details>

ok changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by AleksueiR** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 117 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabYTQ9UCMBgD_yoqOX:-Kabgqo6ZFjlVSGfMr3c:bf2fc3v) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/geo/identify.service.js#L117)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

We only want to format date fields, and to distinguish them from other fields in the template we need a fieldtype passed to the template's directive. That's the tradeoff - pass another parameter to the details panel or format inside the identify service.
</blockquote></details>

Yeap, pass the field type along with the `key/value` to the details panel and apply the appropriate formatter in `details-record-esrifeature.directive.js`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by milesap** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 117 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-KabYTQ9UCMBgD_yoqOX:-Kabv8Jq-qyIzLIWNJ-V:bcxcw9h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dcb3da295764db25925377c59cb4fa8d650ca260/src/app/geo/identify.service.js#L117)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Yeap, pass the field type along with the `key/value` to the details panel and apply the appropriate formatter in `details-record-esrifeature.directive.js`.
</blockquote></details>

Ok changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591)*

**Comment by AleksueiR** [comment]
:+1: Changes look good. Can't test the demo because services fail.

---

Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-KabwpAjrDjleTOvXuN7:bf6lqd9)*

**Comment by milesap** [comment]
Try on `index-fgp-en.html` with layer http://section917.cloudapp.net/arcgis/rest/services/TestData/TimeParty/MapServer/0

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-Kabx2Jztzmq8zbvZN9m:b-8iylru)*

**Comment by AleksueiR** [comment]
Get loads of errors:
> init.js:182 Error: Error performing query operation
    at Object.h.load (init.js:896)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-Kabxa2z0r29djvSM-9_:b-bbd81v)*

**Comment by milesap** [comment]
Strange I don't get any errors

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1591#-:-KabxpzcFM-Hj0m6bzH_:b-r3topz)*

**Pull request merged**
