### PR TITLE
feat(ui): enhance loading indicators

### LINKED ISSUE #2794: Improve service loading feedback
### Problem

The data architecture for this project is expected to use Geomet WFS and WMS services.  Earlier non-prod query times are on an order of 9-10 seconds.  Although a speed increase for production can be expected, it is still expected to have a greater load time than desired for smooth interaction with the user.  In order to provide more obvious feedback in cases where delays are expected, we need to determine options for increasing feedback to the user on loading delays. 

### Solution

A new service called `ShellService` is created to track various loading processes and their effects on the global loading status (the global loading status is displayed by a progress bar along the bottom edge of the map).

Any module can register a process that takes time to complete (not necessarily a layer load/update) by supplying a following signature:

```ts
{
    {id} [string] - id of the loading process; used to clear the loading process when it's completed
    {initDelay} [number] [optional=0] - initial delay before the loading process is marked as `active`; this is a convenience so the caller code can avoid using timeouts; useful to avoid setting indicator for a small amounts of time
    {messageDelay} [number] [optional=4000] - delay before the notification is displayed
    {messageDuration} [number=0] - specifies how long the notifcation will be shown
    {message} [string] [optional=''] - the text of the message to be displayed when the process is going on for longer than the `messageDelay` value
    {action} [string] [optional=''] - the text of the toast action button; clicking on the action button closes the notification and resolves the returned promise; the caller code can wait on that promise to perform some action
}
```

A process is marked as active only after the `initDelay` time has elapsed; the global loading status is `true` if at least one of the registered processes is active. 

When added, individual processes have an option to display a notification message after the specified period of time and also allow for a user action via the notification action button. Notifications are automatically removed when their corresponding processes clear.

Notification do not stack, but they queue. If the first one is dismissed, the next one is shown. 

At the moment, only three types of processes are being registered: `map-init`, `map-update` and `layer-load`.

- `map-init` - refers to the initial loading of the map; used only once and will not display any notifications;
- `map-update` - a catch-all process to track any map updates; will trigger on layer loads/updates, but will not show any notifications;
- `layer-load` - will be registered when a layer record is generated from a layer blueprint and cleared when a `rv-loaded` event is fired by that record; will display a "taking-longer-than-expected" notification after 4000 ms (or other time delay if overridden by the config) with an option to dismiss the notifications;

A new option is added to the layer schema definitions:

**expectedResponseTime** - The time span after which a 'slow-to-respond' notification is shown for any loading or refreshing layer. Defaults to 4000 ms.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Enhanced the service loading feedback. See #2794 for details.

Closes #2794

## Testing
- open `config-01` in `index-samples`
- a notifications that "Liquid pipelines" (response time for this layer is set to 100) are slow should pop up - a similar notifications for the "WMS Layer" should be displayed next
- enable "crops" layer (response time is default 4000)
- a notification for "crops" will display
- zoom or pan the map
- notifications for "crops" is display every time the layer redraws

If you don't get notifications for "crops", [throttle your network in dev tools](https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions).

## Documentation
Lots of inline comments

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 21 of 21 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @AleksueiR, @james-rae, and @JahidAhmed)

---

*[src/app/geo/map.service.js, line 393 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-LFXRdCL0EG6bjSGpVhL:-LFXRdCME57C5N9XORiX:bcbtrd8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75ca93f30c88005cd0a7b1f3a5dd5b8f66f6ff0/src/app/geo/map.service.js#L393)):*
> ```JavaScript
>             'mouse-move': data => events.$broadcast(events.rvMouseMove, data.mapPoint),
>             'update-start': () => {
>                 shellService.setLoadingFlag({ id: 'map-update', initDealy: 100 });
> ```

initDealy -> initDelay

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)*

**Comment by AleksueiR** [comment]
Review status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @spencerwahl, @james-rae, and @JahidAhmed)

---

*[src/app/geo/map.service.js, line 393 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-LFXRdCL0EG6bjSGpVhL:-LFXTrrj2Wp9o_FkEJoY:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d75ca93f30c88005cd0a7b1f3a5dd5b8f66f6ff0/src/app/geo/map.service.js#L393)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

initDealy -> initDelay
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)*

**Comment by JahidAhmed** [comment]
When I initially load `index-samples`, I come across one, sometimes two, toasts for `Liquids Pipeline`. Not sure if this is expected behaviour. 

Same behaviour when I pan or zoom the map and also when toggling visibility for `Liquids Pipeline` from false to true

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-:-LFXdSsS0MfCRvK9n-SM:bv0sn3i)*

**Comment by JahidAhmed** [comment]
Should there also be a `Hide` option for layers that failed to load?


---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-:-LFXeOeR6G5Du1BnuSC_:b-tdcn5i)*

**Comment by AleksueiR** [comment]
The response time for the `Liquids Pipeline` layer is set to 100ms through the config to show how to override the default value of 4000 ms. So it's expected to see notifications for `Liquids Pipeline` all the time.

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-:-LFXeEv3CUtnqDfrfPFF:b-i6rvnj)*

**Comment by AleksueiR** [comment]
> Should there also be a Hide option for layers that failed to load?

The `failed` toast should disappear after 3sec. We can add a `reload` button to it, so the user can try and reload the layer right away.

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-:-LFXehyt-GuNSae1SAu4:bdfqc7k)*

**Comment by JahidAhmed** [comment]
Sounds good, we can add in a `reload` option in a later PR. :lgtm: 

---

Reviewed 18 of 21 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-:-LFXfn5g0YGCmzWAAnrk:bqtbq79)*

**Comment by james-rae** [comment]
Reviewed 18 of 21 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @AleksueiR)

---

*[src/locales/translations.csv, line 246 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-LFd0aKC1LZexefukqlL:-LFd0aKC1LZexefukqlM:b-jkxi4k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab9a629670e366b601e659e2b32622f85f27c797/src/locales/translations.csv#L246)):*
> ```CSV
> Table of Content open datatable label,toc.label.dataTable,Datatable,1,Tableau de données,1
> Table of Content zoom to boundary tooltip,toc.tooltip.boundaryZoom,Zoom to Layer Boundary,1,Zoomer à la limite,1
> ,toc.layer.longload.message,{{name}} is taking longer than expected,1,[fr] {{name}},0
> ```

`{{name}} prend plus de temps que prévu` , keep flag at `0`

---

*[src/locales/translations.csv, line 248 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-LFd0mkH3GRvAAzFAA1I:-LFd0mkI-MDvT3kXwgBu:b-pisz4r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab9a629670e366b601e659e2b32622f85f27c797/src/locales/translations.csv#L248)):*
> ```CSV
> ,toc.layer.longload.message,{{name}} is taking longer than expected,1,[fr] {{name}},0
> ,toc.layer.longload.hide,Hide,1,Masquer,1
> ,toc.layer.longload.failed,{{name}} failed to load,1,[fr] {{name}},0
> ```

`{{name}} omis de charge` , keep flag at `0`

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)*

**Comment by AleksueiR** [comment]
Review status: 15 of 22 files reviewed, 2 unresolved discussions (waiting on @JahidAhmed, @james-rae, and @spencerwahl)

---

*[src/locales/translations.csv, line 246 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-LFd0aKC1LZexefukqlL:-LFiYhK712tAPZl9_gmw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab9a629670e366b601e659e2b32622f85f27c797/src/locales/translations.csv#L246)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`{{name}} prend plus de temps que prévu` , keep flag at `0`
</blockquote></details>

Done.

---

*[src/locales/translations.csv, line 248 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799#-LFd0mkH3GRvAAzFAA1I:-LFiYh7O9SOL02LZ8NXu:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ab9a629670e366b601e659e2b32622f85f27c797/src/locales/translations.csv#L248)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`{{name}} omis de charge` , keep flag at `0`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)*

**Comment by james-rae** [comment]
Reviewed 7 of 7 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2799)*

**Pull request merged**
