### PR TITLE
LayerRecord integration

### LINKED ISSUE #606: State Transition Tracking
This is a refactoring task for state tracking with the geo module.  Currently states are determine by checking a variety of boolean variables which introduces a lot of complexity in state checking.  This should be replaced by a single location for state tracking (boolean properties reflecting those we currently have can be added as read only for the ui module to consume).  ES6 classes should be used for exposing read only properties.

Suggested tasks:
- [x] convert layer record to an ES6 class
- [x] add a state tracking property
- [x] hook layer events to trigger state transitions using the new property
- [x] expose read only boolean properties for `isLoading`, `isError` and `isPlaceHolder`
- [ ] consolidate discussion on this issue into a wiki page and include a state transition diagram

state-transition

### PR DESCRIPTION
**Pull request by alyec**
Closes #606 when complete.  Still missing some doc updates, but want to get the code sections merged up front.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/723)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Comment by james-rae** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[bower.json, line 40 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723#-KJf_maDARSzzgCImNb0:-KJf_maDARSzzgCImNb1:1169702890) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42e74ee7a21373a97168cbddf92ad43c54f61992/bower.json#L40)):*
> ```JSON
>     },
>     "angular-dragula": {
>       "main": "dist/angular-dragula.min.js"
> ```

Do you want to include the workaround into the source?

---

*[src/app/geo/layer-registry.service.js, line 554 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723#-KJfcAFibYZvueXYkviE:-KJfcAFibYZvueXYkviF:-1089101882) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/40e41e25da7c9e0f62c5b0eeb8d8e6e3f541bdac/src/app/geo/layer-registry.service.js#L554)):*
> ```JavaScript
>              * @return {Object}               formatted attribute data { data: Array, columns: Array, fields: Array, oidField: String, oidIndex: Object}
>              */
>             function formatAttributes(attributes, layerData) {
> ```

Where did `formatAttributes` go? It's removed here, but I can't find it on the right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 40 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723#-KJf_maDARSzzgCImNb0:-KJfoLYMhujrk-q8bJeJ:-369748429) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42e74ee7a21373a97168cbddf92ad43c54f61992/bower.json#L40)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Do you want to include the workaround into the source?
</details>
Noted here https://github.com/fgpv-vpgf/fgpv-vpgf/issues/293  Hopefully we get some time to fix it properly later.

---

*[src/app/geo/layer-registry.service.js, line 554 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723#-KJfcAFibYZvueXYkviE:-KJfoQuguVjOARtnDzld:343400351) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/40e41e25da7c9e0f62c5b0eeb8d8e6e3f541bdac/src/app/geo/layer-registry.service.js#L554)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Where did `formatAttributes` go? It's removed here, but I can't find it on the right.
</details>
`formatAttributes` is now in `AttrRecord`: https://github.com/alyec/fgpv-vpgf/blob/lrintegrate/src/app/geo/layer-record.class.js#L132

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 149 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723#-KJjmFw-M88yS13WmYSR:-KJjmFw-M88yS13WmYSS:1513327034) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/705a9686e6be0f05be62bed7b79e3a1b04d12ed3/src/app/geo/identify.service.js#L149)):*
> ```JavaScript
>             */
>             function identifyEsriDynamicLayer(layerRecord, opts) {
>                 const legendEntry = layerRecord.legendEntry;
> ```

So nice, no more state :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/723)*

**Pull request merged**
