### PR TITLE
feat(ui): third part of the layer import ui component

### PR DESCRIPTION
**Pull request by AleksueiR**
File loader ui somewhat done;
added array.find polyfill;
no tests yet; some descriptions missing; both will be added later.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/365)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 8 of 24 files at r1.
Review status: 8 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by ec-dev** [comment]
Reviewed 4 of 24 files at r1.
Review status: 12 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by ec-dev** [comment]
Reviewed 12 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by alyec** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/ui/common/stepper.service.js, line 65 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBnoe-KPDpo57e3wZd3:-KBnoe-KPDpo57e3wZd4:-1501186109) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16d77f150a8bcc166764d1204b61337802caf848/src/app/ui/common/stepper.service.js#L65)):*
Can you link / identify what a step is.  Also, I was initially confused by the object option, I thought the object would imply a tree structure but it really means single or multiple.  I'm not sure if I'm the only one to read it that way but could you update the comment to reflect that?

---

*[src/app/ui/loader/loader-file.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBnqes4cnndPQGBn9LU:-KBnqes5DxVWIgks52yX:164036818) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16d77f150a8bcc166764d1204b61337802caf848/src/app/ui/loader/loader-file.html#L1)):*
Maybe leave a comment somewhere to translate the labels?  Unless there's a fancy tool that extracts all hardcoded strings automatically.

---

*[src/app/ui/loader/loader-menu.directive.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBnqyjoFZbJp_bVQzIX:-KBnqyjpM0rfYpjRsjFk:455174540) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16d77f150a8bcc166764d1204b61337802caf848/src/app/ui/loader/loader-menu.directive.js#L19)):*
Do we need the empty link and activate functions?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by AleksueiR** [comment]
Review status: 19 of 24 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/common/stepper.service.js, line 65 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBnoe-KPDpo57e3wZd3:-KBrOJjh8Vnebo1bFgWn:-901633260) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16d77f150a8bcc166764d1204b61337802caf848/src/app/ui/common/stepper.service.js#L65)):*
Is this helpful?

---

*[src/app/ui/loader/loader-file.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBnqes4cnndPQGBn9LU:-KBrIcLVeFCX3b-GJGpH:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16d77f150a8bcc166764d1204b61337802caf848/src/app/ui/loader/loader-file.html#L1)):*
Done.

---

*[src/app/ui/loader/loader-menu.directive.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBnqyjoFZbJp_bVQzIX:-KBrKrMYclbKCBhvBQOw:-1177509397) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16d77f150a8bcc166764d1204b61337802caf848/src/app/ui/loader/loader-menu.directive.js#L19)):*
No, not really. I'll try to remove them in the future.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/stepper.service.js, line 65 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBnoe-KPDpo57e3wZd3:-KBrbyAhBwW2GtRy66ME:-1219453649) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16d77f150a8bcc166764d1204b61337802caf848/src/app/ui/common/stepper.service.js#L65)):*
Yes, thanks.

---

*[src/app/ui/common/stepper.service.js, line 10 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBrboG1XVmgrCkfbh9a:-KBrboG2_XPnvomKBEzd:971249858) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d2225728e4fffeaf85790d4199a3dac681038bbb/src/app/ui/common/stepper.service.js#L10)):*
Desing -> Design

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/stepper.service.js, line 10 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBrboG1XVmgrCkfbh9a:-KBrcm-DqXYuL9UZTD80:-1461567895) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d2225728e4fffeaf85790d4199a3dac681038bbb/src/app/ui/common/stepper.service.js#L10)):*
Will be fixed in the next PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/common/stepper.service.js, line 10 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365#-KBrboG1XVmgrCkfbh9a:-KBrdeGgxXopyCdt2yDu:583163564) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d2225728e4fffeaf85790d4199a3dac681038bbb/src/app/ui/common/stepper.service.js#L10)):*
np, sorry I missed it on the first pass

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Comment by ec-dev** [comment]
Reviewed 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/365)*

**Pull request merged**
