### PR TITLE
Deploy to fgpv.cloudapp on every build

### LINKED ISSUE #632: chore(build): have Travis publish builds for submitted PRs
:point_up: [May 19, 2016 9:09 AM](https://gitter.im/fgpv-vpgf?at=573dbaed40f0f34870b389c6)

### PR DESCRIPTION
**Pull request by AleksueiR**
Now all builds will be deployed to fgpv.cloudadpp. This is useful when people need to look a PRs but don't have time to build them.

Builds running on the main repo are still deployed as before.
Builds running on forks will be deployed to `http://fgpv.cloudapp.net/demo/users/{user}/{branch}/` with subsequent pushes to a branch overriding previous builds.

Closes #632

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/639)

### CODE REVIEW

**Comment by AleksueiR** [comment]
This PR, for example, is deployed to http://fgpv.cloudapp.net/demo/users/AleksueiR/travis_test/ .

**Comment by spencerwahl** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/639)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/639)*

**Comment by cynngah** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/639)*

**Pull request merged**
