### PR TITLE
enable support, sample page, and documentation for hosting https

### LINKED ISSUE #2764: Ensure viewer can operate in https environment
In the past we had issues because scripts being called within the viewer were not https.

### PR DESCRIPTION
**Pull request by milesap**
## Description

Sample page added w/ config `index-https.html` (localhost only).

Closes #2764

## Testing
You can locally test RAMP using https by running the `npm run serve -- --env.https`. Navigate to https://localhost:6001/samples/index-https.html. You'll receive a "Your connection is not private" message in chrome since the SSL certificate generated by `webpack-dev-server` is self-signed. For testing purposes this is fine - click on "Advanced" then "Proceed to localhost (unsafe)". 

## Documentation
Docs updated

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)

### CODE REVIEW

**Comment by james-rae** [comment]
Can you check that the projection lookup works correctly?  We have an http url hardcoded in `intention\epsg\epsg.intention.ts`

---







*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786#-:-LFTd3ngAEtaB6cw3uAO:b-z543cd)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShrutiVellanki, @james-rae, and @dane-thomas)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Comment by milesap** [comment]
Updated the epsg intention - confirmed working over http and https

---

Review status: 5 of 6 files reviewed, all discussions resolved (waiting on @ShrutiVellanki, @james-rae, and @dane-thomas)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786#-:-LG6XcCSDoSCMzpTyAnR:b5ntxsn)*

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @milesap, @ShrutiVellanki, and @dane-thomas)

---

*[docs/README.md, line 1 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786#-LG6_Fe_4obbvMd5Ahzf:-LG6_FeaBsTgu4WCgcnX:bmda6o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9423e07eb6b3154d0bea107802b540fbb0679b7f/docs/README.md#L1)):*
> ```Markdown
> # RAMP2 FGP Visualiser
> ```

Curious what this file is?  Seems to be focused on https but it's just `docs\readme`.

Though can't argue that the old version of this file was better :1st_place_medal: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Comment by ShrutiVellanki** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @milesap and @dane-thomas)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Comment by dane-thomas** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @milesap)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Comment by milesap** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @milesap)

---

*[docs/README.md, line 1 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786#-LG6_Fe_4obbvMd5Ahzf:-LG6lQzr9n31LGxdo184:bt9g64b) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9423e07eb6b3154d0bea107802b540fbb0679b7f/docs/README.md#L1)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Curious what this file is?  Seems to be focused on https but it's just `docs\readme`.

Though can't argue that the old version of this file was better :1st_place_medal: 
</blockquote></details>

Its the main landing page for the docs. Eventually it should resemble our repos readme. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @milesap)

---

*[docs/README.md, line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786#-LGUoOAj7F07OcQIs428:-LGUoOAj7F07OcQIs429:b-2lsn6t) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9423e07eb6b3154d0bea107802b540fbb0679b7f/docs/README.md#L5)):*
> ```
> setup your configuration file for https
> ```

Shouldn't this be `http`, not `https`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Comment by milesap** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @milesap)

---

*[docs/README.md, line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786#-LGUoOAj7F07OcQIs428:-LGUpg2HBv1gGHy6kAD_:bk42fba) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9423e07eb6b3154d0bea107802b540fbb0679b7f/docs/README.md#L5)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

> ```
> setup your configuration file for https
> ```

Shouldn't this be `http`, not `https`?
</blockquote></details>

Should be `https` since serving that page as `https` would fail. Served as `http` is fine as well since there is no mixed content errors over `http` if some links are to `https` resources. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Comment by AleksueiR** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[docs/README.md, line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786#-LGUoOAj7F07OcQIs428:-LGUqm6N3CGMXO81oG9k:bd5l6n4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9423e07eb6b3154d0bea107802b540fbb0679b7f/docs/README.md#L5)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Should be `https` since serving that page as `https` would fail. Served as `http` is fine as well since there is no mixed content errors over `http` if some links are to `https` resources. 
</blockquote></details>

thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2786)*

**Pull request merged**
