### PR TITLE
fix(table): header scrolling with body

### LINKED ISSUE #2222: Prevent table header scrolling without removing `autoWidth: false`
Find a solution that allows `autoWidth: false` but also does not reintroduce table header scrolling issues.

`autoWidth: false` was removed since it fixes an issue where table headers do not scroll horizontally with the table body. 

See #2141 and #2081

The side effect of removing `autoWidth: false` is Datatable columns now extend to the full length of the data being displayed instead of breaking the column data and adding '...'

capture

For tables with few columns or not enough content to fill the table horizontally it looks sad and empty:

empty

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2222.

## Testing
Visually tested on Chrome, FF, IE.

## Documentation
In-line comment.

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2269)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm: Demo seems to work surprisingly well considering this is a datatable bug. Fox, IE, and Chrome tested.

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2269#-:-Kpzse3LXEJ27Re87Ry-:bwpekvr)*

**Comment by AleksueiR** [comment]
Likely not directly related to this PR.
Hm, tested with Safari on BrowserStack, and it has these hiding scrollbars that are supposed to show up only when you are hovering over them. Well, they don't. How do you scroll in Safari without a scroll wheel?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2269#-:-KpztlMzzltD1X4208FX:b-o75la4)*

**Comment by JahidAhmed** [comment]
That's weird, does the same happen on the develop branch?

**Comment by AleksueiR** [comment]
Yeap, that's why I said it's not directly related.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2269#-:-Kpzvq-NCckxWCc9hlTD:byrno2u)*

**Comment by AleksueiR** [comment]
Made a separate issue for that: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2274

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2269#-:-Kq2qF8crDLERzBwLSM_:b91gwi3)*

**Pull request merged**
