### PR TITLE
fix(filters): option data not read from config file

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

config file option.data was not properly read from the config file.

## Testing

index-one.html
With feature layer Land Pub Standard Zone Details ("data": { "enabled": false })
With dynamic layer Eco Geo first layer ({"index": 6, "data": {"enabled": false}})

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1652)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Found what was wrong. Submitted a PR to your PR :smile: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652#-:-KbtzwaC3S5KFA3lzrOk:b-24z8yp)*

**Comment by AleksueiR** [comment]
:lgtm: :+1: 

---

Reviewed 2 of 3 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652#-:-Kbui7OMgFR5z3DzwQSR:b-8sos09)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/legend-entry.service.js, line 207 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652#-Kbv2Yct92eoK5YfVDFH:-Kbv2Yct92eoK5YfVDFI:b-imyyrn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1d20bb73bad3f59a7e88fd50e1b680af0285375/src/app/geo/legend-entry.service.js#L207)):*
> ```JavaScript
>                 // solves https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1628
>                 if (this.options.data) {
>                     this.flags.data.visible = this.options.data.value;
> ```

I didn't read the schema correctly. This line should be with __enabled__, not _value_:
```js
this.flags.data.visible = this.options.data.enabled;
```

@jolevesq Can you change this quickly please? 

EcoGeo layer on index-one has it's first sublayer's data disabled only, so it should look like this:


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652)*

**Comment by jolevesq** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend-entry.service.js, line 207 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652#-Kbv2Yct92eoK5YfVDFH:-Kbv6sdcyY_mexws0Xq7:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1d20bb73bad3f59a7e88fd50e1b680af0285375/src/app/geo/legend-entry.service.js#L207)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I didn't read the schema correctly. This line should be with __enabled__, not _value_:
```js
this.flags.data.visible = this.options.data.enabled;
```

@jolevesq Can you change this quickly please? 

EcoGeo layer on index-one has it's first sublayer's data disabled only, so it should look like this:

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652#-:-KbvHGO3Jp91qeb8TQh_:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1652)*

**Pull request merged**
