### PR TITLE
feat(filters): rename filters panel to table panel

### LINKED ISSUE #2051: Rename filter to be a grid-specific term
Up until now we have been using the word `filter` to describe the grid in code. Now that we have actual filters in the grid, the terminology is becoming awkward. We should do a rename across the whole app (config schema, file names, object names, documentation) to something like `grid`, `table`, `datagrid`

- [x] Determine what the new name / term should be.
- [x] Update the config schema
- [x] Update code references to schema / object names
- [x] Update file names in the application
- [x] Update technical documentation / help
- [x] Update any tests

This should be done after https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2050 , and ideally at a time where there is no other major development happening on the impacted areas of the code.

### PR DESCRIPTION
**Pull request by milesap**
## Description
- Reviewed all 500 uses of the word `filter` in the viewer and changed to
`table` where appropriate
- config schema changes
    - FilterNode -> TableNode
    - Layer filters -> Layer table
- I don't ever want to hear the word filter again

Closes #2051

## Testing
:eyes: on chrome

## Documentation
updated inline and dev docs

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2167)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 64 of 64 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167)*

**Comment by barryytm** [comment]
Reviewed 36 of 64 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/table/search.html, line 5 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167#-Kox4mCT6WKgF05ZcbV5:-Kox4mCT6WKgF05ZcbV6:b-k4sjyq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/900a6ecfc934725787b2f47d401a489c73a71249/src/app/ui/table/search.html#L5)):*
> ```HTML
>     ng-if="self.service.isGlobalSearch">
>     <input
>         aria-label={{ filter.aria.table.search | translate }}"
> ```

I think the`translations.csv` need to be updated too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167)*

**Comment by AleksueiR** [comment]
Reviewed 64 of 64 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167)*

**Comment by AleksueiR** [comment]
Review status: 48 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/table/search.html, line 13 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167#-Kp-u15MVMfqHUrkFQ-K:-Kp-u15MVMfqHUrkFQ-L:b-bwjvwc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a9cd1b57c5e43cd96e42a6ddeb3ec5b9165b06ff/src/app/ui/table/search.html#L13)):*
> ```HTML
>     </md-button>
>     <md-icon ng-show="self.searchText.length <= 2" md-svg-src="action:search">
>         <md-tooltip>{{ 'filter.aria.table.search' | translate }}</md-tooltip>
> ```

To be fair, this on should read `table.aria.search`, but I'm not going to bother changing it right now.

---

*[src/app/ui/toc/toc.directive.js, line 248 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167#-Kp-tqg0RW7ABcpizwEs:-Kp-tqg0RW7ABcpizwEt:b-mse72q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a9cd1b57c5e43cd96e42a6ddeb3ec5b9165b06ff/src/app/ui/toc/toc.directive.js#L248)):*
> filter.search.placeholder

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167)*

**Comment by AleksueiR** [comment]
Review status: 48 of 51 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/table/search.html, line 5 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167#-Kox4mCT6WKgF05ZcbV5:-Kp03oevWjZ4jENaWW8U:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/900a6ecfc934725787b2f47d401a489c73a71249/src/app/ui/table/search.html#L5)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

I think the`translations.csv` need to be updated too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167)*

**Comment by james-rae** [comment]
Reviewed 1 of 64 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2167)*

**Pull request merged**
