### PR TITLE
refactor(core): de-defer core config service

### PR DESCRIPTION
**Pull request by AleksueiR**
I tried to get rid of deferred (Rookie mistake #4 in http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html).
Am I doing it correctly?

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/20)

### CODE REVIEW

**Comment by alyec** [comment]
Looks okay to me.  I'm also coming from a background of using deferred objects.


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/config.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20#-K-cyjbmwBR_Wr3ZLl26)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/806ce23d104051afce1a29da59b05da63b56fbfc/src/app/core/config.service.js#L46)):</sup>
 :+1: helpful comments, but maybe for a big default initialization we should use and `if` instead of `||` ?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by spencerwahl** [comment]
Looks good to me, though I'm no expert on deferreds or promises


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/config.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20#-K-cyjbmwBR_Wr3ZLl26)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/806ce23d104051afce1a29da59b05da63b56fbfc/src/app/core/config.service.js#L46)):</sup>
I wanted just one `return` statement in the `initialize` function.

Since we are likely to have many `initialize`-type of functions (in services mainly I think; big and and small), maybe we should decide on a convention: always use `if` or always use `||` to return the init promise. What do you think guys?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/config.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20#-K-cyjbmwBR_Wr3ZLl26)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/806ce23d104051afce1a29da59b05da63b56fbfc/src/app/core/config.service.js#L46)):</sup>
I prefer `||` over `if`, but not by much. I agree with deciding on a convention for consistency :+1:


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/config.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20#-K-cyjbmwBR_Wr3ZLl26)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/806ce23d104051afce1a29da59b05da63b56fbfc/src/app/core/config.service.js#L46)):</sup>
Maybe I'm missing something, why do you need a second return for something like

```
if (! promise) {
  promise = $q({
     long_multiline_thing
  }
}
return promise;
```

@spencerwahl I'd say `||` for single line defaults (ex `let extent = defaultExtent || maxExtent;` ) but `if` when complex functions or objects are being created as the default


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/config.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20#-K-cyjbmwBR_Wr3ZLl26)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/806ce23d104051afce1a29da59b05da63b56fbfc/src/app/core/config.service.js#L46)):</sup>
I wanted to avoid another indentation level, hence the second `return`.

I agree about complex functions/object though; `if` it is then, I guess, unless someone suggests something else in the next two days.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/20)

**Pull request merged**
