### PR TITLE
fix(ui): prioritize layers with data in slider

### LINKED ISSUE #984: Grouping Layers in Slider Portion of Identify Results Panel
Currently the viewer maintains the order of the layers in the slider portion of the Details panel.  As a result, on the first Identify click, it is possible for there to appear to be "No Results" as indicated in the screenshot from JOSM below.  Also, when many layers exist in the viewer, results will be greatly spread out and it is possible they will overflow beyond the viewing area of the slider while showing a long list of layers with no results.

Once a layer is selected, subsequent Identify clicks will be sticky as per #645.  However, this does not address the poor initial feedback provided or deal with results being buried at the bottom of the slider.

In order to address these shortcomings:
- Add three "groups" of layers to the slider area, "Results", "Waiting for Response", "No results"
- All layers will initially appear in "Waiting for response"
- As results are received, the layer is moved to the appropriate group
- Identify results should still stick to previous layer selection (forward planning FTW  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/645#issuecomment-223328636)

### PR DESCRIPTION
**Pull request by milesap**
Closes #984

## Description
Present layers with data above those without while maintaining ordering within these groups.

## Testing
:eye: 

## Documentation
None yet as 1.6 branch is missing jsDocs tutorial implementation.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1696)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/layer-list-slider.html, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696#-Kd1wNc9vCNa1K7iLwhw:-Kd1wNc9vCNa1K7iLwhx:b-38mnnq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fdefaccc64b8bf7433ae767519b5e2e3598c26af/src/app/ui/details/layer-list-slider.html#L2)):*
> ```HTML
> 
> <div class="rv-list">
> ```

Keep this as a list please, for accessibility sake :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696)*

**Comment by milesap** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/layer-list-slider.html, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696#-Kd1wNc9vCNa1K7iLwhw:-Kd1xvRsjFeJnnQHMzI-:bdszexs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fdefaccc64b8bf7433ae767519b5e2e3598c26af/src/app/ui/details/layer-list-slider.html#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Keep this as a list please, for accessibility sake :D
</blockquote></details>

Yeah and I noticed `rv-list` is used in other places, changed back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/layer-list-slider.html, line 4 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696#-Kd2CZqEXJGuirbet8ZL:-Kd2CZqEXJGuirbet8ZM:bgwe7qr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9f9d51a44c65dbf9bb7fac85d5586893a0c68e7e/src/app/ui/details/layer-list-slider.html#L4)):*
> ```HTML
> <ul class="rv-list rv-flex-column">
>     <li
>         ng-repeat="item in self.display.data"
> ```

Somehow missed that you are using the `order` property. Probably more straightforward is to just order using `orderBy` on `ng-repeat`:

```js
 ng-repeat="item in self.display.data | orderBy:['data.length == 0','-isLoading']"
```
🐱‍👤

And no need for `flex`ing the list, as `ng-repeat` will change the actual order of dom nodes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/layer-list-slider.html, line 4 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696#-Kd2CZqEXJGuirbet8ZL:-Kd2EYMtS6Ii5MvkDMwa:b-blkhx8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9f9d51a44c65dbf9bb7fac85d5586893a0c68e7e/src/app/ui/details/layer-list-slider.html#L4)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Somehow missed that you are using the `order` property. Probably more straightforward is to just order using `orderBy` on `ng-repeat`:

```js
 ng-repeat="item in self.display.data | orderBy:['data.length == 0','-isLoading']"
```
🐱‍👤

And no need for `flex`ing the list, as `ng-repeat` will change the actual order of dom nodes.

</blockquote></details>

Awesome :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696)*

**Comment by AleksueiR** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696#-:-Kd2FgLNzGNMw5hKz9He:bg7igkv)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1696)*

**Pull request merged**
