### PR TITLE
feat(ui): stop buffering queries for polygon layers

### LINKED ISSUE #538: Do not buffer queries for polygon layers
When querying feature layers a buffered intersection is applied to all layer types.  This can be dropped from polygon layers since a point in polygon intersection will probably yield better results for the user.  https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v0.13.0/src/app/geo/identify.service.js#L228

### PR DESCRIPTION
**Pull request by cynngah**
Closes #538

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/659)

### CODE REVIEW

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659#-KIhJDCx6k3k-ucxpyoz:-KIhJDCyzgSdn03Bs8md:1448495678) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d55bff2ff70bb54d2254e2c89fd94e12c88ca06f/src/app/geo/identify.service.js#L269)):*
> ```JavaScript
> 
>                 // more accurate results without making the buffer if we're dealing with extents
>                 if (opts.mapExtent.type !== 'extent') {
> ```

`opts.mapExtent` is the current view of the map on screen.  you probably want to use `layer.geometryType === 'esriGeometryPolygon'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659#-KIhJDCx6k3k-ucxpyoz:-KIhJ_LsQ1QbZ8YydiiR:-229633114) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d55bff2ff70bb54d2254e2c89fd94e12c88ca06f/src/app/geo/identify.service.js#L269)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> `opts.mapExtent` is the current view of the map on screen.  you probably want to use `layer.geometryType === 'esriGeometryPolygon'`
</details>
err, make that `!==`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659)*

**Comment by cynngah** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 269 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659#-KIhJDCx6k3k-ucxpyoz:-KIhSrGGRX7evfPFDM2J:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d55bff2ff70bb54d2254e2c89fd94e12c88ca06f/src/app/geo/identify.service.js#L269)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> err, make that `!==`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/659)*

**Pull request merged**
