### PR TITLE
feat(ui): change north arrow icon

### LINKED ISSUE #1835: Change north arrow image on main map
Current image can make it seem the user should pan up to an important point and that it isn't a north arrow. 

Example:

It should probably be a bit smaller though :smiley:

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1835

## Testing
:eyes:

## Documentation
None

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1838)

### CODE REVIEW

**Comment by jolevesq** [comment]
The arrow is pointing north and south. Can we just keep the pointing north section?


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh22Ph1lNpfJdUPSBKN:b-zc2m75)*

**Comment by AleksueiR** [comment]
Some nice vector arrows here: http://jrgraphix.net/CAD/downloads/North_Arrow/
I also like this one : 
 

[ [svg](https://files.gitter.im/AleksueiR/bicz/NorthArrow_02.svg) ]

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh2NtxnsXWd_fZdgwT_:beajm91)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838)*

**Comment by milesap** [comment]
Looks good, changed the icon

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh2aOrl36mOmxvc-9aG:bltz31y)*

**Comment by AleksueiR** [comment]
Something is wrong ....


---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh2fj5iWE5wPnvvpvrW:bt14xyj)*

**Comment by milesap** [comment]
WOMM - though it's a tad large here, I'll make it smaller

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh2iDPdGBDen-6kJ1li:bws5jdm)*

**Comment by AleksueiR** [comment]
Same as before. Main CSS file is not found:
> Request URL:http://fgpv.cloudapp.net/demo/users/milesap/1835/prod/lib/main.css
Request Method:GET
Status Code:404 Not Found

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh2m40vzixHpesB_k04:bwz6iyt)*

**Comment by AleksueiR** [comment]
Any luck in fixing the demo?

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh3OpluHJaAjgPqSFaY:b-ujfazl)*

**Comment by milesap** [comment]
Think I found the problem, an extra `}` in a scss file

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh7AY22F3LEmwZD4MFK:b-msqykq)*

**Comment by AleksueiR** [comment]
Same, `main.css` is still missing. Maybe try to clean the demo folder and run the build again.

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh7CnCtxfRaxdbO3-YS:bm15tp3)*

**Comment by milesap** [comment]
check now, travis was slow on my build

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh7CznNCc6yicC1ZUyp:b-f5fan3)*

**Comment by AleksueiR** [comment]
Works now, cool.
Do you think we can drop the white circle underneath the arrow and change its size from 40 to 32? It's quite visible as it is.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh7E5FdvSVEiMQ4aein:b-9mznt6)*

**Comment by milesap** [comment]
I can change the size to 32, but the 'N' letter is not visible on darker basemaps. If that's ok then I can remove it

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh7EOUbnJeMi4KwpidE:b-h28pm8)*

**Comment by AleksueiR** [comment]
I would love to remove that "N" :) Solves the problem. @jolevesq Do we need the "N" letter on the arrow? Can we remove it? IMO it looks much better without the white circle, but we need it to keep the "N" visible. Maybe just put the circle under "N"?

Yes, please make it 32. Thanks.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Kh7GWD2WSPPWe7P713r:bfoyrru)*

**Comment by milesap** [comment]
Changed to 32 and moved circle so that it is only behind the "N" letter.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-KhMrPoNvDtwZ4dC7F0p:b-1npkx2)*

**Comment by milesap** [comment]
I noticed an issue with `index-fgp-en/fr.html` where the logger would cause an error (called before initialized) so the map wouldn't load. Put a small fix until library can be loaded in proper order.

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-KhMw-YfKD8ca2YBe7hG:b9h901b)*

**Comment by milesap** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/bootstrap.js, line 17 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-KhMx7iDNkEscDlcsjXe:-KhMx7iDNkEscDlcsjXf:b-q2p5dz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3499ddafd843680ec1b0d69822bf6905261c9bb4/src/app/bootstrap.js#L17)):*
> ```JavaScript
>     // TODO: load logger lib before app starts
>     RV.logger = {};
>     ['debug', 'log', 'info', 'warn', 'error'].forEach(t => RV.logger[t] = console[t]);
> ```

RV.logger = console would work too... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838)*

**Comment by milesap** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/bootstrap.js, line 17 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-KhMx7iDNkEscDlcsjXe:-KhMxhvvsILeDUCE8-7H:b499q7j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3499ddafd843680ec1b0d69822bf6905261c9bb4/src/app/bootstrap.js#L17)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

RV.logger = console would work too... 
</blockquote></details>

Changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838)*

**Comment by jolevesq** [comment]
@aleksueir I agree to remove the N. Some old fashion user will maybe complain but they will complain with the new way of showing the north anyway :smile:. i like this new icon but I would remove the N and put the tip of the arrow upper so when you are in Newfounland and the arrow is behind the menu bar you can still guess where the north is.

---

Reviewed 2 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-KhRnRvNb2uzGikUtQ-i:b49p11f)*

**Comment by milesap** [comment]
I'll see if I have time for removing the "N", most likely won't happen this week.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-KhTKfx4yfChe_iSr88i:b-ndujok)*

**Comment by AleksueiR** [comment]
Is your PR open to external contributions? I can update the arrow image if you don't have time.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-KhXBtMkTG5X5cJKFVUU:blteoua)*

**Comment by milesap** [comment]
Enabled external contributions, in case it's not done by tmrw then this is a good idea.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-KhXJf2fJSPZcn1o0KPn:b-ltbjyq)*

**Comment by AleksueiR** [comment]
Simplified the arrow a bit, added some animation and moved the rotation point to `top center`.


---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838#-:-Ki6QKXOtKOkOUjjV8tu:b-ft7htg)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838)*

**Comment by james-rae** [comment]
Reviewed 1 of 5 files at r1, 1 of 3 files at r3, 4 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1838)*

**Pull request merged**
