### PR TITLE
feat(ui): Adds filters panel

### PR DESCRIPTION
**Pull request by AleksueiR**
Also swaps main CSS transitions for JS ones;
adds "loads" of comments;

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/38)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 11 files at r1, 40 of 41 files at r2, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 27 unresolved discussions, all commit checks successful.

---

<sup>**[bower.json, line 36 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0hdrF2SInSX1JA1BWT)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/febca91ff5b50c25b5330a79f3e78ddeab4755c1/bower.json#L36)):</sup>
Can we agree on online style for single element object literals?


---

<sup>**[src/app/core/config.service.js, line 57 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kjWUiDna6-h9pdPNe)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/core/config.service.js#L57)):</sup>
partins? :)


---

<sup>**[src/app/core/config.service.js, line 127 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kjrivU5il6smpemoO)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/core/config.service.js#L127)):</sup>
Let's fill this in before we merge, otherwise I think it will get forgotten and left the way it is.


---

<sup>**[src/app/core/core.config.js, line 37 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gclTzcWFPUWDm3aEn)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/core/core.config.js#L37)):</sup>
Is this supposed to be a dgeni comment?  If not // probably makes more sense, and if it is don't we need more parameters?

Based on what we talked about I guess we'll merge Jack's PR and see how this gets picked up.


---

<sup>**[src/app/layout/filters-panel-plug.controller.js, line 21 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gdylqk0jXznKX6ZTV)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/filters-panel-plug.controller.js#L21)):</sup>
You mention `rvMorph` here but I'm not sure what it's referencing.  If `rvMorph` isn't used directly then it may be good to expand on how it interacts with the controller.


---

<sup>**[src/app/layout/filters-panel-plug.controller.js, line 26 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gdkA2Nu-fEKPmIozS)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/filters-panel-plug.controller.js#L26)):</sup>
const self = this


---

<sup>**[src/app/layout/filters-panel-plug.controller.js, line 34 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gdu-uKuDyJDOXRnpd)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/filters-panel-plug.controller.js#L34)):</sup>
const


---

<sup>**[src/app/layout/layout.route.js, line 24 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0geaMYoKm_fmE_FusN)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/layout.route.js#L24)):</sup>
References to the structure being defined would be helpful (either here or inline).  I think there should be enough inline docs to make it clear how to add a new route, including all the other pieces this needs to interact with.


---

<sup>**[src/app/layout/layout.service.js, line 18 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gfFvNAc4AgGKShHqB)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/layout.service.js#L18)):</sup>
+ "As the UI-Manager it combines services (and directives?) from the `app.ui` module in a single interface." ?


---

<sup>**[src/app/layout/main-panel-plug.controller.js, line 22 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0ggl1mNpP24yfSQ65x)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/main-panel-plug.controller.js#L22)):</sup>
If we haven't released yet shouldn't we just remove deprecated settings right away?


---

<sup>**[src/app/layout/shell.controller.js, line 29 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0klNiha7EGUNX-cAM-)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/layout/shell.controller.js#L29)):</sup>
const


---

<sup>**[src/app/layout/side-panel-plug.controller.js, line 25 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kmf90MeIHGDA3saD5)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/layout/side-panel-plug.controller.js#L25)):</sup>
Can we create a plug controller class?  I think we're seeing that everything needs an active property (and I'm guessing there will be more common code that we could hoist).


---

<sup>**[src/app/ui/appbar/appbar.controller.js, line 19 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0knH8NUW6d_w6BpwBs)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/appbar/appbar.controller.js#L19)):</sup>
I'm going to pretty much ignore this controller since we're going to be replacing most of it.


---

<sup>**[src/app/ui/common/common.module.js, line 9 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0knfIpT2awKgGCN7b1)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/common.module.js#L9)):</sup>
A little bit more detail would be nice as to what directives belong in this module -- avoiding having someone to be familiar with `rv-morph` or maybe just providing more examples so that someone can get a better feel of what is appropriate.


---

<sup>**[src/app/ui/common/morph.directive.js, line 13 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0koR-WBWnqAM-bWoPr)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/morph.directive.js#L13)):</sup>
sp: immediately

This is probably a good class to use a a reference for how to use ngdoc.


---

<sup>**[src/app/ui/common/plug-slide.transition.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0krTzqQ8xo19kt7eOh)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/plug-slide.transition.js#L22)):</sup>
What makes a node valid -- we don't have a specific Plug type so what makes a node compatible?

typo: rvPlugSLide


---

<sup>**[src/app/ui/common/plug-slide.transition.js, line 34 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0krAFcATVu2rrtEEIR)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/plug-slide.transition.js#L34)):</sup>
I'm not seeing why all these bindings are necessary (and it may be that I'm just confused).


---

<sup>**[src/app/ui/filters/filters-default.directive.js, line 24 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kskABqe4GX-Xm-E3F)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/filters/filters-default.directive.js#L24)):</sup>
const


---

<sup>**[src/app/ui/mapnav/mapnav.controller.js, line 23 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kuyT92vQOdChGPxe3)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/mapnav/mapnav.controller.js#L23)):</sup>
const


---

<sup>**[src/app/ui/panels/content-pane.directive.js, line 24 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kvYus36dE1U3y3gh7)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/content-pane.directive.js#L24)):</sup>
const


---

<sup>**[src/app/ui/panels/content-pane.html, line 2 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kwrbztMOCZJrcDc39)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/content-pane.html#L2)):</sup>
sp: headline


---

<sup>**[src/app/ui/panels/filters-panel.directive.js, line 10 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kwvurRxG1Rvpot-4y)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/filters-panel.directive.js#L10)):</sup>
sp: outer


---

<sup>**[src/app/ui/panels/filters-panel.directive.js, line 23 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxG2CMwWPhzz0BelX)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/filters-panel.directive.js#L23)):</sup>
const


---

<sup>**[src/app/ui/panels/main-panel.directive.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxRtikOZ4UyKQdgmJ)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/main-panel.directive.js#L22)):</sup>
const


---

<sup>**[src/app/ui/panels/side-panel.directive.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxX1civjs76D191xp)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/side-panel.directive.js#L22)):</sup>
const


---

<sup>**[src/app/ui/sidenav/menulink.directive.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxeATHLr99lDvA7LD)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/sidenav/menulink.directive.js#L22)):</sup>
const


---

<sup>**[src/index-many.html, line 39 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kkGaUEMqGEhQR8w3E)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/index-many.html#L39)):</sup>
Did we just add trailing whitespace?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38)

**Comment by james-rae** [comment]
Reviewed 4 of 11 files at r1, 37 of 41 files at r2, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 25 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38)

**Comment by AleksueiR** [comment]
Review status: 27 of 46 files reviewed at latest revision, 25 unresolved discussions, some commit checks pending.

---

<sup>**[bower.json, line 36 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0hdrF2SInSX1JA1BWT)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/febca91ff5b50c25b5330a79f3e78ddeab4755c1/bower.json#L36)):</sup>
Atom's beautify plugin expands single-element objects, so I suggest we always expand them :D


---

<sup>**[src/app/core/config.service.js, line 57 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kjWUiDna6-h9pdPNe)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/core/config.service.js#L57)):</sup>
Done.


---

<sup>**[src/app/core/config.service.js, line 127 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kjrivU5il6smpemoO)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/core/config.service.js#L127)):</sup>
Done.


---

<sup>**[src/app/core/core.config.js, line 37 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gclTzcWFPUWDm3aEn)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/core/core.config.js#L37)):</sup>
It's a valid jsdoc comment. Since the function doesn't take parameters and is not returning anything it looks like a regular block comment.


---

<sup>**[src/app/layout/filters-panel-plug.controller.js, line 21 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gdylqk0jXznKX6ZTV)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/filters-panel-plug.controller.js#L21)):</sup>
Done.


---

<sup>**[src/app/layout/filters-panel-plug.controller.js, line 26 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gdkA2Nu-fEKPmIozS)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/filters-panel-plug.controller.js#L26)):</sup>
Done.


---

<sup>**[src/app/layout/filters-panel-plug.controller.js, line 34 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gdu-uKuDyJDOXRnpd)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/filters-panel-plug.controller.js#L34)):</sup>
Done.


---

<sup>**[src/app/layout/layout.route.js, line 24 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0geaMYoKm_fmE_FusN)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/layout.route.js#L24)):</sup>
Agree, but I'm still not entirely clear. Routes should be broken between corresponding components and there should be some service to resolve state changes. Not much comments I can add right now I'm afraid :(


---

<sup>**[src/app/layout/main-panel-plug.controller.js, line 22 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0ggl1mNpP24yfSQ65x)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/main-panel-plug.controller.js#L22)):</sup>
Done.


---

<sup>**[src/app/layout/shell.controller.js, line 29 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0klNiha7EGUNX-cAM-)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/layout/shell.controller.js#L29)):</sup>
Done.


---

<sup>**[src/app/layout/side-panel-plug.controller.js, line 25 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kmf90MeIHGDA3saD5)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/layout/side-panel-plug.controller.js#L25)):</sup>
Good idea. Maybe not in this PR, but it should be done.


---

<sup>**[src/app/ui/appbar/appbar.controller.js, line 19 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0knH8NUW6d_w6BpwBs)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/appbar/appbar.controller.js#L19)):</sup>
Done.


---

<sup>**[src/app/ui/common/common.module.js, line 9 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0knfIpT2awKgGCN7b1)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/common.module.js#L9)):</sup>
Better?


---

<sup>**[src/app/ui/common/morph.directive.js, line 13 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0koR-WBWnqAM-bWoPr)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/morph.directive.js#L13)):</sup>
:+1: 


---

<sup>**[src/app/ui/common/plug-slide.transition.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0krTzqQ8xo19kt7eOh)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/plug-slide.transition.js#L22)):</sup>
Good point. Maybe we should make plugs into their own directive.


---

<sup>**[src/app/ui/common/plug-slide.transition.js, line 34 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0krAFcATVu2rrtEEIR)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/plug-slide.transition.js#L34)):</sup>
Fixed!


---

<sup>**[src/app/ui/filters/filters-default.directive.js, line 24 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kskABqe4GX-Xm-E3F)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/filters/filters-default.directive.js#L24)):</sup>
Done.


---

<sup>**[src/app/ui/mapnav/mapnav.controller.js, line 23 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kuyT92vQOdChGPxe3)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/mapnav/mapnav.controller.js#L23)):</sup>
Done.


---

<sup>**[src/app/ui/panels/content-pane.directive.js, line 24 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kvYus36dE1U3y3gh7)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/content-pane.directive.js#L24)):</sup>
Done.


---

<sup>**[src/app/ui/panels/content-pane.html, line 2 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kwrbztMOCZJrcDc39)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/content-pane.html#L2)):</sup>
Done.


---

<sup>**[src/app/ui/panels/filters-panel.directive.js, line 10 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kwvurRxG1Rvpot-4y)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/filters-panel.directive.js#L10)):</sup>
Done.


---

<sup>**[src/app/ui/panels/filters-panel.directive.js, line 23 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxG2CMwWPhzz0BelX)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/filters-panel.directive.js#L23)):</sup>
Done.


---

<sup>**[src/app/ui/panels/main-panel.directive.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxRtikOZ4UyKQdgmJ)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/main-panel.directive.js#L22)):</sup>
Done.


---

<sup>**[src/app/ui/panels/side-panel.directive.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxX1civjs76D191xp)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/panels/side-panel.directive.js#L22)):</sup>
Done.


---

<sup>**[src/app/ui/sidenav/menulink.directive.js, line 22 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kxeATHLr99lDvA7LD)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/sidenav/menulink.directive.js#L22)):</sup>
Done.


---

<sup>**[src/app/layout/layout.service.js, line 18 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gfFvNAc4AgGKShHqB)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/layout/layout.service.js#L18)):</sup>
Removed. Proper comments in the header.


---

<sup>**[src/index-many.html, line 39 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0kkGaUEMqGEhQR8w3E)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/index-many.html#L39)):</sup>
It wasn't me :cat: 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38)

**Comment by alyec** [comment]
Reviewed 19 of 21 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[bower.json, line 36 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0hdrF2SInSX1JA1BWT)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/febca91ff5b50c25b5330a79f3e78ddeab4755c1/bower.json#L36)):</sup>
I vote -0


---

<sup>**[src/app/core/core.config.js, line 37 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gclTzcWFPUWDm3aEn)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/core/core.config.js#L37)):</sup>
Does it need stuff like `@ngdoc` or `@name` identify it?  Or does it auto parse now?


---

<sup>**[src/app/ui/common/common.module.js, line 9 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0knfIpT2awKgGCN7b1)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6ae2aa164a497bea21280394d4bc13017fb94c6/src/app/ui/common/common.module.js#L9)):</sup>
:+1: 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/core.config.js, line 37 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38#-K0gclTzcWFPUWDm3aEn)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/97dae6554b6834b675d9e539cd6c1a1b948278ac/src/app/core/core.config.js#L37)):</sup>
This's an inner function of the `configBlock`, so it doesn't need any of that, I think. Again, I want to see works with #34 first.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/38)

**Pull request merged**
