### PR TITLE
fix(ui): identify appbar title not being truncated

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes: #2467

## Testing

:eyes:

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barryytm, @ShrutiVellanki, and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)*

**Comment by dane-thomas** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @AleksueiR, @JahidAhmed, @dane-thomas, @barryytm, @ShrutiVellanki, and @james-rae)

---

*[src/content/styles/modules/_appbar.scss, line 37 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811#-LG1GWzu2loPl-TARGk7:-LG1GzVM1iB7w2kAeNpm:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da189bf6f8ae68e419b238c58bf489f78cdeae38/src/content/styles/modules/_appbar.scss#L37)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Better to use `overflow: hidden;` instead of specifying the `width`.
</blockquote></details>

donethanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)*

**Comment by barryytm** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @AleksueiR, @ShrutiVellanki, and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShrutiVellanki and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)*

**Comment by JahidAhmed** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ShrutiVellanki and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)*

**Comment by ShrutiVellanki** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)*

**Pull request merged**
