### PR TITLE
Attrib reloading

### PR DESCRIPTION
**Pull request by cynngah**
#685 

Toast disappears when successfully loaded
Can reload datagrid if errored the first time.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/810)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 245 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KKsYYDPqK23FdEGEixh:-KKsYYDQM_6BmDNK6Pys:-1700699752) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a1eedc7e7e478cb4e577ae017f6e7c614aa16e9e/src/app/geo/layer-record.class.js#L245)):*
> ```JavaScript
> 
>                 if (formAtt.hasOwnProperty(featureIdx) && formAtt[featureIdx].$$state.status === 1) {
>                     return this._formattedAttributes[featureIdx];
> ```

`return formAtt[featureIdx];` :dancers: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by cynngah** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 245 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KKsYYDPqK23FdEGEixh:-KKsZtP3Qt_ua8SBeOZi:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a1eedc7e7e478cb4e577ae017f6e7c614aa16e9e/src/app/geo/layer-record.class.js#L245)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> `return formAtt[featureIdx];` :dancers: 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-:-KKxaSu1vvRgs3GZYeCm:1417088721)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/layer-record.class.js, line 244 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KKxbMdJJiM-P95aMpwm:-KKxbMdJJiM-P95aMpwn:1951112335) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e35de62160ad7099dd8c8673ad5e915e092b3a/src/app/geo/layer-record.class.js#L244)):*
> ```JavaScript
>                 const formAtt = this._formattedAttributes;
> 
>                 if (formAtt.hasOwnProperty(featureIdx) && formAtt[featureIdx].$$state.status === 1) {
> ```

What is `$$state.status` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by cynngah** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 244 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KKxbMdJJiM-P95aMpwm:-KKxeFSwP5qQ_YD_ouAL:-167701488) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e35de62160ad7099dd8c8673ad5e915e092b3a/src/app/geo/layer-record.class.js#L244)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> What is `$$state.status` ?
</details>
variable in the promise that tells you if it's resolved or not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 244 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KKxbMdJJiM-P95aMpwm:-KKxga9qOyuisPnucITJ:1186451672) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e35de62160ad7099dd8c8673ad5e915e092b3a/src/app/geo/layer-record.class.js#L244)):*
<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> variable in the promise that tells you if it's resolved or not
</details>
I see. If the promise takes some time to resolve (lots of attributes to download) and `getAttributes` is called several times (by opening and closing data panel), multiple parallel calls to `getAttribs` will be made.

Maybe instead of checking some private variable to see if the promise is resolved, add a catch statement to the `attributePromise` itself:
```js
const attributePromise = $q.all([layerPackage.getAttribs(), layerPackage.layerData])
    .then(([attributes, layerData]) => this.formatAttributes(attributes, layerData));
    
attributePromise.catch(error => 
    delete this._formattedAttributes[featureIdx]); // delete cached promise when the geoApi `getAttribs` call fails, so it will be requested again next time `getAttributes` is called;

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by cynngah** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 244 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KKxbMdJJiM-P95aMpwm:-KLr3GpxUqIx9z7GfPcI:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e3e35de62160ad7099dd8c8673ad5e915e092b3a/src/app/geo/layer-record.class.js#L244)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I see. If the promise takes some time to resolve (lots of attributes to download) and `getAttributes` is called several times (by opening and closing data panel), multiple parallel calls to `getAttribs` will be made.
> 
> Maybe instead of checking some private variable to see if the promise is resolved, add a catch statement to the `attributePromise` itself:
> ```js
> const attributePromise = $q.all([layerPackage.getAttribs(), layerPackage.layerData])
>     .then(([attributes, layerData]) => this.formatAttributes(attributes, layerData));
>     
> attributePromise.catch(error => 
>     delete this._formattedAttributes[featureIdx]); // delete cached promise when the geoApi `getAttribs` call fails, so it will be requested again next time `getAttributes` is called;
> 
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/geo/layer-record.class.js, line 253 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KLr7yRlur-ckb8hbi10:-KLr7yRlur-ckb8hbi11:-278161748) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9d8917a8f3e282ec51ebdfb3f938a8ccd1d5d2cf/src/app/geo/layer-record.class.js#L253)):*
> ```JavaScript
>                     .catch(() => {
>                         delete this._formattedAttributes[featureIdx]; // delete cached promise when the geoApi `getAttribs` call fails, so it will be requested again next time `getAttributes` is called;
>                         throw 'Attrib loading failed';
> ```

`throw new Error('Attrib loading failed');`

---

*[src/app/ui/toc/toc.service.js, line 280 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KLr7b-seG1rtoIN16_S:-KLr7b-t46bM8RvkedQ9:423310725) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9d8917a8f3e282ec51ebdfb3f938a8ccd1d5d2cf/src/app/ui/toc/toc.service.js#L280)):*
> ```JavaScript
> 
>             const layerRecord = geoService.layers[requester.layerId];
>             let dataPromise = layerRecord.getAttributes(entry.featureIdx)
> ```

Why was this changed to `let`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by cynngah** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-record.class.js, line 253 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KLr7yRlur-ckb8hbi10:-KM5itk9CwEA3kyCUfaE:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9d8917a8f3e282ec51ebdfb3f938a8ccd1d5d2cf/src/app/geo/layer-record.class.js#L253)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `throw new Error('Attrib loading failed');`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by cynngah** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/toc.service.js, line 280 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810#-KLr7b-seG1rtoIN16_S:-KM5ivSsw9xVRLUVjgcC:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9d8917a8f3e282ec51ebdfb3f938a8ccd1d5d2cf/src/app/ui/toc/toc.service.js#L280)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Why was this changed to `let`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/810)*

**Pull request merged**
