### PR TITLE
WMS Layer Styling

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Related to #332 

Allows users to choose styles for layers while importing (Step 3)
Also allows changing styles to be disabled (legendEntryControls).

## Testing
Visually tested.

Sample 1 can be used to test disabled styles control

This service can be used to test configuring styles when importing: http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities.

## Documentation
Comments, JSDoc

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2429)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
WMS 1.1 legends can be tested in this PR (http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities)

**Comment by alyec** [comment]
Reviewed 4 of 8 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 273 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2429#-KwuWcrSkWbAYrNKm6ul:-KwuWcrTjTqlR3KBLOAI:btmivn9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ad3a30425113ec43aadaf6bcdf7826b22f0a9c9/schema.json#L273)):*
> ```JSON
>                 "id": { "type": "string", "description": "The id of the layer entry in the WMS" },
>                 "name": { "type": "string", "description": "A descriptive name for the layer.  To be used in the legend." },
>                 "allStyles": { "type": "array", "description": "All the styles for the layer entry in the WMS" },
> ```

add `"items": { "type": "string" }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2429)*

**Comment by JahidAhmed** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 273 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2429#-KwuWcrSkWbAYrNKm6ul:-KwuZ3n-iT8PS-w8FxC8:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3ad3a30425113ec43aadaf6bcdf7826b22f0a9c9/schema.json#L273)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

add `"items": { "type": "string" }`
</blockquote></details>

Done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2429)*

**Comment by james-rae** [comment]
Reviewed 4 of 8 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2429)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2429)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2429)*

**Pull request merged**
