### PR TITLE
Handle RCS keys on language change

### PR DESCRIPTION
**Pull request by james-rae**
## Description
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1657 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1658

## Testing
Tested a medley of language change, bookmark, and back to cart with RCS and file-config based layers

## Documentation
JSDocs. WIki update pending for loading flow

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1667)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 474 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-KcK7qYTenNCCejQA7o7:-KcK7qYUgWoF7jXYs3nN:b-eid6dv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/46db3560bfa82271ad09b1f8fcc638e22bdf4a18/src/app/core/bookmark.service.js#L474)):*
> ```JavaScript
>             if (newLang) {
>                 (() => {
>                     console.debug(newLang, config);
> ```

Sorry, one more change: can we remove the debugs before this gets merged?

---

*[src/app/core/bookmark.service.js, line 488 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-KcK892gAi7QpP_mYw9e:-KcK892gAi7QpP_mYw9f:b-27ej45) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/46db3560bfa82271ad09b1f8fcc638e22bdf4a18/src/app/core/bookmark.service.js#L488)):*
> ```JavaScript
>                     console.debug(bookmarkLayers);
>                     // only keep layers that are not coming from the bookmark
>                     config.layers = config.layers.filter(l => bookmarkedKeys.indexOf(l.id.split('.')[1]) === -1);
> ```

This line was part of my first fix attempt.  I'm pretty sure it does nothing useful now, it can be removed as can `const bookmarkedKeys` and `bookmarkedKeys.push`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667)*

**Comment by james-rae** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 474 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-KcK7qYTenNCCejQA7o7:-KcKCdk4AyXeXbGeMyy3:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/46db3560bfa82271ad09b1f8fcc638e22bdf4a18/src/app/core/bookmark.service.js#L474)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Sorry, one more change: can we remove the debugs before this gets merged?
</blockquote></details>

done thanks

---

*[src/app/core/bookmark.service.js, line 488 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-KcK892gAi7QpP_mYw9e:-KcKCfW7h7K5skoV3yXj:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/46db3560bfa82271ad09b1f8fcc638e22bdf4a18/src/app/core/bookmark.service.js#L488)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

This line was part of my first fix attempt.  I'm pretty sure it does nothing useful now, it can be removed as can `const bookmarkedKeys` and `bookmarkedKeys.push`.
</blockquote></details>

done thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667)*

**Comment by AleksueiR** [comment]
Language switching works correctly. :lgtm: 

Is [#1658](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1658) supposed to be fixed as well? 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/core/bookmark.service.js, line 473 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-KcNOwE-159tENMD6tLV:-KcNOwE-159tENMD6tLW:b-d2td3r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b31f7b459f15f43c82931630103cac460d3dd1c/src/app/core/bookmark.service.js#L473)):*
> ```JavaScript
> 
>             if (newLang) {
>                 (() => {
> ```

Non-blocking comment: 

Why this block is a IIFE?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-:-KcNQEF_Rhrwm_XTtMQt:b-eadipx)*

**Comment by james-rae** [comment]
*[src/app/core/bookmark.service.js, line 473 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-KcNOwE-159tENMD6tLV:-KcNuz2Fahfd5vIduuPM:b44gg9x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b31f7b459f15f43c82931630103cac460d3dd1c/src/app/core/bookmark.service.js#L473)):*
From Aly:

> It solved the too many statements restrictions and since I really didn't want to do major refactors on `parseBookmark` it seemed the best option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/core/bookmark.service.js, line 473 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-KcNOwE-159tENMD6tLV:-KcNvfbUKX_UgEgEiBu1:b9jt3g9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0b31f7b459f15f43c82931630103cac460d3dd1c/src/app/core/bookmark.service.js#L473)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

From Aly:

> It solved the too many statements restrictions and since I really didn't want to do major refactors on `parseBookmark` it seemed the best option.
</blockquote></details>

Smart. I would have never thought of that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667)*

**Comment by james-rae** [comment]
It does appear to have fixed the major problem of that issue (layers now show after back to cart), but I notice that the Airport layer re-appears so might want to keep it open.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-:-KcNw25mtLQMpYIKoAXW:bds95rz)*

**Comment by AleksueiR** [comment]
Airport and JOSM layers re-appear for me as well.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-:-KcNwPLpkaatyUTxfy_c:buu79hu)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-:-KcOgYvr1II_03899Qj7:bnfp4nl)*

**Comment by AleksueiR** [comment]
#1658 looks solved to me. :lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1667#-:-KcOgysj0LMLuXpROH1G:b1nva8q)*

**Pull request merged**
