### PR TITLE
2078 remove user layers

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
- [bug #2078] allows removing user-added layers even in the structured legend
- [undocumented bug] hidden layers are no longer queried
- [undocumented bug] when importing a feature layer as dynamic, the `display as group` option is pre-deselected
- [chores] removing leftover dead code

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ unreleased bugs
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2086)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086)*

**Comment by milesap** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086)*

**Comment by alyec** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/legend.service.js, line 394 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086#-KoDbjbGHMm4u-ZFufjO:-KoDbjbGHMm4u-ZFufjP:b-f0bksf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8ce58e4fe23c948f0b3ee54b467f008773431645/src/app/geo/legend.service.js#L394)):*
> ```JavaScript
>          * @param {LayerRecord} layerRecord the loaded dynamic layer record to travers
>          * @param {LayerNode} layerConfig the typed and defaults config of the supplied dynamic layer record
>          * @return {Object} a tree structure of dynamic children cast to proper legend block classes and with defautls applied
> ```

typo: defaults

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086)*

**Comment by AleksueiR** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 394 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086#-KoDbjbGHMm4u-ZFufjO:-KoDkjSHXZOx0KOYvEY_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8ce58e4fe23c948f0b3ee54b467f008773431645/src/app/geo/legend.service.js#L394)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: defaults
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2086)*

**Pull request merged**
