### PR TITLE
fix(ui): open initial datatable specified in the config

### LINKED ISSUE #2088: Opening data table on load when specified needs to be implemented
When given the option `filterIsOpen` under `ui` in a config file, the data table of the specified layer should be opened on load.  The implementation regarding to it is missing in `toc.directive.js`.  There could be difficulties when implementing due to the asynchronous nature when requesting layer files and the data in the layer files that is required to achieve such action.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description

Properly opens the datatable by default is specified in the config.

Close #2088

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ unreleased bug
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2090)

### CODE REVIEW

**Comment by barryytm** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.class.js, line 2010 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090#-KoCjHXG6YLCR3qt6RT0:-KoCjHXG6YLCR3qt6RT1:b-vg1onm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e980b0c4ab66e0b72e63bf11ff5315cb0d96b25d/src/app/core/config.class.js#L2010)):*
> ```JavaScript
>             this._help = new Help(uiSource.help);
>             this._fullscreen = uiSource.fullscreen;
>             this._filterIsOpen = new FilterIsOpen(uiSource.filterIsOpen);
> ```

Would it be possible to rename `filter` to something like `dataTable`?  It is a bit confusing when I first read it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.class.js, line 2010 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090#-KoCjHXG6YLCR3qt6RT0:-KoCk_pMOoiGB86jwL9u:b-9dkmkw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e980b0c4ab66e0b72e63bf11ff5315cb0d96b25d/src/app/core/config.class.js#L2010)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Would it be possible to rename `filter` to something like `dataTable`?  It is a bit confusing when I first read it.
</blockquote></details>

It's in the plans: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2051
Don't want to start renaming things before 2.0 ships.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090)*

**Comment by barryytm** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090#-:-KoClXIe--S-FDhS2drp:bnfp4nl)*

**Comment by barryytm** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090)*

**Comment by barryytm** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090#-:-KoClwGtqzAW9ANusDu8:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2090)*

**Pull request merged**
