### PR TITLE
Temporary Fix for Sync config

### PR DESCRIPTION
**Pull request by barryytm**
## Description

A temporary fix for problem with loading synchronous config.

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2442 
## Testing

Try switching to a different config in `index-samples`
http://fgpv.cloudapp.net/demo/users/barryytm/2.1.0-2442/dev/samples/index-samples.html
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2457)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 203 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457#-KxmGh_0Vp3hrXh2007c:-KxmGh_0Vp3hrXh2007d:buauml) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7346872d7b3d0340151f89728150bb9d232176cd/src/app/core/config.service.js#L203)):*
> ```JavaScript
>         get loadingState() { return _loadingState; }
>         get getSync() {
>             // TODO: Get rid of this getter and use getAsync instead
> ```

I would like @alyec to weigh in on this one...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457)*

**Comment by alyec** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 203 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457#-KxmGh_0Vp3hrXh2007c:-Kxn6Cb_fq75LYZ8avM9:b-ga6mvn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7346872d7b3d0340151f89728150bb9d232176cd/src/app/core/config.service.js#L203)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I would like @alyec to weigh in on this one...
</blockquote></details>

I'd be willing to let this in if I could be convinced that this was both: temporary, and does not cause other problems (particularly if we are saying the code already makes assumptions about when the config is loaded, giving it the ability to silently ignore errors sounds like we're setting ourselves up for some extra fun bug hunting down the road).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 203 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457#-KxmGh_0Vp3hrXh2007c:-KxrG7XlBh99b7-mbha3:b954o5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7346872d7b3d0340151f89728150bb9d232176cd/src/app/core/config.service.js#L203)):*
> "There's nothing more permanent than a temporary hack." - Kyle Simpson

---

*[src/app/core/config.service.js, line 304 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457#-KxmiT2YtMpEmcTDci7w:-KxmiT2YtMpEmcTDci7x:baqe2ss) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7346872d7b3d0340151f89728150bb9d232176cd/src/app/core/config.service.js#L304)):*
> configList = [];    // empty previous configs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457)*

**Comment by milesap** [comment]
Regarding [my comment](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2442#issuecomment-339972230) on this issue, I'd much rather we go that route (if its possible) since it can be more or less a permanent fix, and "doesn't sound all that difficult"

1. Intercept config reload request
2. Ask `config.service.js` or w/e to get/download the config and when it signals its ready
3. Execute #1

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457#-:-KxrGUz8iQ_52cS_YNpF:b-da20d6)*

**Comment by AleksueiR** [comment]
Has this bug been released with the 2.1 release?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2457#-:-KxrkFgKb48LkxyOXzJC:b-wlxcbq)*

**Comment by milesap** [comment]
Closing for now, please re-open with suggested solution or similar.

**Pull request closed without merging**
