### PR TITLE
feat(ui): solo records in details panel expanded by default

### LINKED ISSUE #819: feat(ui): expand solo record in details panel
When details panel is opened from the datagrid, the solo record should be expanded and locked (cannot be collapsed).

### PR DESCRIPTION
**Pull request by milesap**
Closes #819

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/871)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm: Thanks for adding one-time bindings!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/871#-:-KMV7LCt-8wPettE-8bV:-897451193)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/details/details-record-esrifeature.directive.js, line 100 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/871#-KMV7xHyniMNcNiY83lu:-KMV7xHyniMNcNiY83lv:-1967172934) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/18ffcacba9b29aec50bf82a42f9bc68d87a278f1/src/app/ui/details/details-record-esrifeature.directive.js#L100)):*
> ```JavaScript
> 
>         /**
>          * Expand/collapse identify record section. Disable functionality for solo records.
> ```

Not sure I follow this part, there's a change in the comment but no change in the function implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/871)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/871)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/871)*

**Pull request merged**
