### PR TITLE
fix(details): fix zoom to goes to bad zoom level for layer with scale…

### LINKED ISSUE #1454: User added Scale Dependency layer - All zoom levels were out of scale after zooming from Detail panel
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-8/prod/samples/index-fgp-en.html?keys=JOSM,Airports,NPRI_CO,Railways,mb_colour
User added scale dependency layer:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

This issue happened with Mercator basemaps only.
-  Add scale dependency layer by selecting zoom level 1 to zoom level 4
-  Click any map point for the added layer to display Point Info panel
-  Click Zoom To Feature button highlighted in below screenshot
image
-  Click Legend to open up layers - all zoom levels are out of scale, see below
image

### PR DESCRIPTION
**Pull request by jolevesq**
… dependency

Closes #1454

## Description

#1454 

## Testing

Chrome, FF and Safari

## Documentation

inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1626)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Travis didn't publish a demo again for some reason.
Code looks good.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-record-esrifeature.directive.js, line 52 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1626#-KbKa-tDpeRGJ1ci-6ev:-KbKa-tDpeRGJ1ci-6ew:bhsygbd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b2cc792f71f6404532b747a5554c73080ed19858/src/app/ui/details/details-record-esrifeature.directive.js#L52)):*
> ```JavaScript
>                 // we need this espcially for scale dependant layer for the zoom to go to the proper zoom level for the
>                 // selected layer
>                 if (entry.layerType === 'esriDynamic') {
> ```

Layer types are stored in the `Geo` constant service. Add `Geo` as a dependency and use `Geo.Layer.Types.ESRI_DYNAMIC` instead of the hardcoded string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1626#-:-KbK_y2Z5Fs-n00LGDcR:bddxty8)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1626)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-record-esrifeature.directive.js, line 52 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1626#-KbKa-tDpeRGJ1ci-6ev:-KbL8pTpWKAt7PoHUYdq:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b2cc792f71f6404532b747a5554c73080ed19858/src/app/ui/details/details-record-esrifeature.directive.js#L52)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Layer types are stored in the `Geo` constant service. Add `Geo` as a dependency and use `Geo.Layer.Types.ESRI_DYNAMIC` instead of the hardcoded string.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1626)*

**Comment by AleksueiR** [comment]
:lgtm: Works in Chrome and IE.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details-record-esrifeature.directive.js, line 52 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1626#-KbKa-tDpeRGJ1ci-6ev:-KbLA6w5E-5KjC47DDwT:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b2cc792f71f6404532b747a5554c73080ed19858/src/app/ui/details/details-record-esrifeature.directive.js#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1626#-:-KbLA8WIUaqhnrC_AqKO:b-pjqo6n)*

**Pull request merged**
