### PR TITLE
Use WMS layer title in legend

### PR DESCRIPTION
**Pull request by james-rae**
## Description
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1453

## Testing
Tested against local WMSes. Will add unit tests after code is migrated to geoAPI

## Documentation
Function headers

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1543)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 197 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-K_5Mh1Fezv6IyiFnAJC:-K_5Mh1GgfkJV7jvrTdX:baro3sn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78567388d9aab7d2aeb0db901a30d038de082f20/src/app/geo/legend.service.js#L197)):*
> ```JavaScript
>              * @return {String}              layer title as defined on the service, '' if no title defined
>              */
>             function getWMSLayerTitle(wmsLayer, wmsLayerId) {
> ```

Shouldn't this be in geoApi? There is already a wms crawl function there: https://github.com/fgpv-vpgf/geoApi/blob/39ce4a266be7e450eb51d2c97617a400560b84cb/src/layer/ogc.js#L140. Maybe this can be piggy-backed on that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543)*

**Comment by james-rae** [comment]
*[src/app/geo/legend.service.js, line 197 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-K_5Mh1Fezv6IyiFnAJC:-K_6N8Vcv5DipUYYXBgV:bei0xj8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78567388d9aab7d2aeb0db901a30d038de082f20/src/app/geo/legend.service.js#L197)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Shouldn't this be in geoApi? There is already a wms crawl function there: https://github.com/fgpv-vpgf/geoApi/blob/39ce4a266be7e450eb51d2c97617a400560b84cb/src/layer/ogc.js#L140. Maybe this can be piggy-backed on that?
</blockquote></details>

I have a todo below to move it after the refactor. But maybe I'll move it now. Lazy vs proactive :'D . The function you linked, while similar in that it also crawls `layerInfos`, it does a full crawl wheras mine is searching for a target then exiting (and updating a value outside the loop). They should certainly be in the same `ogc.js` file, but I don't think I can effectively share the looping code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 197 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-K_5Mh1Fezv6IyiFnAJC:-K_9Ohkp-6up7y6ng1Eu:b-k5mvra) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78567388d9aab7d2aeb0db901a30d038de082f20/src/app/geo/legend.service.js#L197)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I have a todo below to move it after the refactor. But maybe I'll move it now. Lazy vs proactive :'D . The function you linked, while similar in that it also crawls `layerInfos`, it does a full crawl wheras mine is searching for a target then exiting (and updating a value outside the loop). They should certainly be in the same `ogc.js` file, but I don't think I can effectively share the looping code
</blockquote></details>

ha-ha, missed the todo comment. 

Sure, let me know if you are not going to move it to geoapi right now and I'll merge this.

Also, can you post some wms layers the demo can be tested with? Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543)*

**Comment by james-rae** [comment]
Url for testing: `http://section917.cloudapp.net/arcgis/services/NPRI_FGP_All_Layers/MapServer/WMSServer?request=GetCapabilities&service=WMS`
However, the wizard will not accept WMS (I believe this is a known issue, the URL checker fails when it gets xms when it expects json or something like that).  To test, need to add the WMS to the config file and specify one of the layers.  Specifying a title in the config will override the new logic.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 197 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-K_5Mh1Fezv6IyiFnAJC:-K_A45lE7yYSR0u7-M8Q:bw39bj8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/78567388d9aab7d2aeb0db901a30d038de082f20/src/app/geo/legend.service.js#L197)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

ha-ha, missed the todo comment. 

Sure, let me know if you are not going to move it to geoapi right now and I'll merge this.

Also, can you post some wms layers the demo can be tested with? Thanks.

</blockquote></details>

Will be lazy, as it is lazy week.  Testing URL posted on main comment thread at top, its not simple to test directly off the build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-:-K_A3XuDnG9arUWKr8vV:b-kohid4)*

**Comment by james-rae** [comment]
I'm wrong.  Using this URL works `http://section917.cloudapp.net/arcgis/services/NPRI_FGP_All_Layers/MapServer/WMSServer`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-:-K_A4O_Lp9a5Qy9bS7DW:blwwmje)*

**Comment by AleksueiR** [comment]
On hold until Aly can take a look at it. Seems there is a possibility of reusing some geoApi code.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-:-K_AH-7C7BtjmLGq50JK:butmjd1)*

**Comment by AleksueiR** [comment]
Please, rebase this, when you have a chance. We are going to merge as it is, and fix duplication later.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543#-:-K_idbL40V1NpogAq8xs:b-337wyx)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1543)*

**Pull request merged**
