### PR TITLE
Legend Service and some schema refactoring

### PR DESCRIPTION
**Pull request by AleksueiR**
Added `legendService` for legend generation and direct binding from `toc`. It's "somewhat" incomplete although config layers are now bound directly to toc. There is some dead code in `toc`: to be removed later.

Will be adding layer symbology scrapers to it next.

Will add comments later and tests.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/391)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/core/config.service.js, line 162 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuXH9nUJxUTYnJb7Th:-KCuXH9nUJxUTYnJb7Ti:-379329482) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/core/config.service.js#L162)):*
I'd prefer to avoid using angular built-ins when similar functionality exists in the spec: `Object.entries`.  Needs a polyfill but will prevent people from having to lookup the semantics of `angular.forEach`.

---

*[src/app/geo/layer-registry.service.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuQO19MEescVIOlsUp:-KCuQO1A4IhhdyoXWp9M:2030390453) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/layer-registry.service.js#L143)):*
No, I think this should stay an error as it is enforced by the schema I believe.

---

*[src/app/geo/legend.service.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuUDI9EGBtB_fiGfeQ:-KCuUDI9EGBtB_fiGfeR:-1372780552) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/legend.service.js#L13)):*
Is this ever going to be used by an HTML ID?  It may only be application unique (you could add some additional prefix).

---

*[src/app/geo/legend.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuU-GsdNbYwGyX7FE0:-KCuU-GsdNbYwGyX7FE1:-1452553285) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/legend.service.js#L30)):*
The default expression reads pretty well IMO, but since it's new syntax maybe add a note that the default is always re-evaluated.

---

*[src/app/geo/legend.service.js, line 85 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuUzUEjkHHOV7Sp1A-:-KCuUzUF3wV_VnZ9FSpu:1935262311) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/legend.service.js#L85)):*
Is there a reason we can't pull them out of translate?  IIRC we still recreate the map and dependent services when we language switch.

---

*[src/app/geo/map.service.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuVaofLmh5njR9dqb1:-KCuVaognuu8RQU15dPB:1363293502) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/map.service.js#L19)):*
Since mapService has a fixed number of args I don't think we should be using `...args`.

---

*[src/app/ui/toc/toc.service.js, line 1139 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuWQBPb-gbgR8t-OIC:-KCuWQBPb-gbgR8t-OID:2129089061) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/ui/toc/toc.service.js#L1139)):*
I'd prefer to avoid using angular built-ins when similar functionality exists in the spec: `Object.entries`.  Same comment in config service.

---

*[src/app/ui/toc/toc.service.js, line 1147 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuXh6zlC4WdahgcY0y:-KCuXh6zlC4WdahgcY0z:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/ui/toc/toc.service.js#L1147)):*
const

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuQO19MEescVIOlsUp:-KCu_FdgNZX5H6S4hIlk:160384653) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/layer-registry.service.js#L143)):*
Ok.

---

*[src/app/geo/legend.service.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuUDI9EGBtB_fiGfeQ:-KCu_ItHM2iqSB9zuHYg:-1066537791) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/legend.service.js#L13)):*
Unlikely, but I'll add `rv` prefix just in case.

---

*[src/app/geo/legend.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuU-GsdNbYwGyX7FE0:-KCu_NfSP4NIQ58RKNYc:1085483994) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/legend.service.js#L30)):*
Will do.

---

*[src/app/geo/legend.service.js, line 85 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuUzUEjkHHOV7Sp1A-:-KCu_RwWkWqCn0LHB6pt:1522000390) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/legend.service.js#L85)):*
Yes, I forgot that we recreate everything when switching languages.

---

*[src/app/geo/map.service.js, line 19 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuVaofLmh5njR9dqb1:-KCu__Vxb6NDwLO6a8cg:1724388019) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/geo/map.service.js#L19)):*
This is just to avoid duplicating argument names. Otherwise, it will be written three times.

---

*[src/app/ui/toc/toc.service.js, line 1147 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuXh6zlC4WdahgcY0y:-KCu_zilmImftmFPCm28:-709678398) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/ui/toc/toc.service.js#L1147)):*
Will fix.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391)*

**Comment by AleksueiR** [comment]
Review status: 9 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/config.service.js, line 162 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuXH9nUJxUTYnJb7Th:-KCurRdMhH7OuuJZ0aXd:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/core/config.service.js#L162)):*
Done.

---

*[src/app/ui/toc/toc.service.js, line 1139 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-KCuWQBPb-gbgR8t-OIC:-KCurSg1oN6Y4Hy8jO46:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2e69d0c81ca3ce816806acea560e502d47f1ad7b/src/app/ui/toc/toc.service.js#L1139)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391#-:-KCut6BgRKpatrbNGajc:1417088721)*

**Comment by spencerwahl** [comment]
Reviewed 9 of 14 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/391)*

**Pull request merged**
