### PR TITLE
Add fade animation, overhaul panel animation file

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/74)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2T0u3us7vRar2EhIoc)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f656c28f27aae1930fd3a6e5840ff124105ed019/src/app/ui/common/plug-slide.animation.js#L39)):</sup>
Get-out-of muffin points: use es6 template strings: https://babeljs.io/docs/learn-es2015/#template-strings
```js
.animation(`.rv-plug-fade-${element}-grand`, plugFadeGrandBuilder(index));
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2T0u3us7vRar2EhIoc)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f656c28f27aae1930fd3a6e5840ff124105ed019/src/app/ui/common/plug-slide.animation.js#L39)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2T0u3us7vRar2EhIoc)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f656c28f27aae1930fd3a6e5840ff124105ed019/src/app/ui/common/plug-slide.animation.js#L39)):</sup>
+10 get-out-of muffin points :+1: 
Thanks, @spencerwahl 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 32 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2gf7_F2cnVkdg8T4Jh)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L32)):</sup>
Should it be const instead of let?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 32 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2gf7_F2cnVkdg8T4Jh)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L32)):</sup>
Good catch, fixed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 239 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2h8MFLfK1ZXjQBoJdX)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L239)):</sup>
type of shift doesn't really help unless there's something that provides more context that I've missed


---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 262 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2h79K0Fi2o0x8Hxcvi)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L262)):</sup>
we shouldn't have different types assigned to delta (we should probably explicitly convert the output of deltaHelper to a string)


---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 36 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2iQS1kQ2sDRwkeLQ-c)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9356ca3dabdff75c024df591cbae10fa5ad07a9f/src/app/ui/common/plug-slide.animation.js#L36)):</sup>
We seem to have a lot of code that returns very similar {enter,leave} services.  Can we unify them:

```js
animationBuilder({ mode: 'fade', direction: index, grand: true })

function animationBuilder(opts) {
  return $rootElement => {
    const func = mode === 'fade' ? makeFadeAnim : makeSlideAnim;
    return {
      enter: func($rootElement, opts.direction, false, opts.grand),
      leave: func($rootElement, opts.direction, true, opts.grand)
    }
  }
}
```


---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 288 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2iNvMS0Hvi8n4FclM7)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9356ca3dabdff75c024df591cbae10fa5ad07a9f/src/app/ui/common/plug-slide.animation.js#L288)):</sup>
units -- for those of us who barely work on this?


---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 306 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2iOZ5No0uCV2QnT4dU)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9356ca3dabdff75c024df591cbae10fa5ad07a9f/src/app/ui/common/plug-slide.animation.js#L306)):</sup>
how about `reverse ? end : start` (dropping the `!` for readability)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 288 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2iNvMS0Hvi8n4FclM7)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9356ca3dabdff75c024df591cbae10fa5ad07a9f/src/app/ui/common/plug-slide.animation.js#L288)):</sup>
gsap uses seconds.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 239 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2h8MFLfK1ZXjQBoJdX)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L239)):</sup>
Done.


---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 36 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2iQS1kQ2sDRwkeLQ-c)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9356ca3dabdff75c024df591cbae10fa5ad07a9f/src/app/ui/common/plug-slide.animation.js#L36)):</sup>
Done.


---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 288 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2iNvMS0Hvi8n4FclM7)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9356ca3dabdff75c024df591cbae10fa5ad07a9f/src/app/ui/common/plug-slide.animation.js#L288)):</sup>
Done.


---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 306 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2iOZ5No0uCV2QnT4dU)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9356ca3dabdff75c024df591cbae10fa5ad07a9f/src/app/ui/common/plug-slide.animation.js#L306)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 262 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2h79K0Fi2o0x8Hxcvi)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L262)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 262 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2h79K0Fi2o0x8Hxcvi)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L262)):</sup>
Forgot to update the doc to say the return type is now string.  Might also consider having the toString here in case the method is ever needed for feeding into some other numeric formula.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 262 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2h79K0Fi2o0x8Hxcvi)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/92869f060343f7228d4e738af59e991fe09176c9/src/app/ui/common/plug-slide.animation.js#L262)):</sup>
Done again :smile:


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 36 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2m6hQD8lMkMJrOJO-u)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/36ebb0e299adb1c653e13921e1aba2d69bfdf732/src/app/ui/common/plug-slide.animation.js#L36)):</sup>
style: no brackets around type


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 36 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2m6hQD8lMkMJrOJO-u)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/36ebb0e299adb1c653e13921e1aba2d69bfdf732/src/app/ui/common/plug-slide.animation.js#L36)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 36 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2m6hQD8lMkMJrOJO-u)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/36ebb0e299adb1c653e13921e1aba2d69bfdf732/src/app/ui/common/plug-slide.animation.js#L36)):</sup>
You can also drop curly brackets on the first arrow function since you are return a chained function call. :smile: 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 36 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74#-K2m6hQD8lMkMJrOJO-u)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/36ebb0e299adb1c653e13921e1aba2d69bfdf732/src/app/ui/common/plug-slide.animation.js#L36)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/74)

**Pull request merged**
