### PR TITLE
chore(docs): correct existing docs for v2.0

### PR DESCRIPTION
**Pull request by milesap**
## Description
correct existing docs for v2.0, update README, and add north arrow to help file.

## Testing
None

## Documentation
Yes it is

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1993)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/developer/modules/core.md, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993#-Kml_Bv-K-LAkS73YFRo:-Kml_Bv-K-LAkS73YFRp:b-qfmgd4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/103390c3d42959be2466e297bce5c221b2e86af0/docs/developer/modules/core.md#L48)):*
> ```Markdown
> # formatters.filter.js
> 
> Custom angular filters can be added here. Currently this file includes date formatting and url detection in strings.
> ```

You can also add the picture filter added lately

---

*[src/locales/help/default/fr-CA.md, line 195 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993#-Kmlyiz88QH1drgnvJM9:-Kmlyiz88QH1drgnvJMA:b-emzzuo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/103390c3d42959be2466e297bce5c221b2e86af0/src/locales/help/default/fr-CA.md#L195)):*
> ```Markdown
> # Flèche Nord
> 
> La carte principale contient une flèche nord. On le trouve en haut de la carte. Il se déplacera horizontalement sur l'écran de sorte qu'il traverse toujours une ligne droite imaginaire qui dépasse le centre de la carte et le pôle nord.
> ```

La carte principale contient une flèche **du** nord. On ~~le~~ **la** trouve en haut de la carte. ~~Il~~ **Elle** se ~~déplacera~~ **déplace** horizontalement sur l'écran de sorte qu'~~il~~ **elle** traverse toujours une ligne droite imaginaire qui ~~dé~~passe **par** le centre de la carte et le pôle nord.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993)*

**Comment by AleksueiR** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/developer/app_startup.md, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993#-Kn-2BlI9UZ4RofaaG9s:-Kn-2BlI9UZ4RofaaG9t:b-fvbxnl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/103390c3d42959be2466e297bce5c221b2e86af0/docs/developer/app_startup.md#L4)):*
> ```Markdown
> 
> To load the viewer on a webpage, a few things are required on the host page:
> - A script tag which loads `rv-main.js`. This should be placed in the `body` section of the host page near the end.
> ```

It should also be place before any of the host page scripts that interact with the external API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/developer/app_startup.md, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993#-Kn-2BlI9UZ4RofaaG9s:-Kn5Nz2v9I7AIYx8Gwiq:b-8b11j9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/103390c3d42959be2466e297bce5c221b2e86af0/docs/developer/app_startup.md#L4)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

It should also be place before any of the host page scripts that interact with the external API.
</blockquote></details>

Added

---

*[docs/developer/modules/core.md, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993#-Kml_Bv-K-LAkS73YFRo:-Kn5NvVV44knLQn7CjRn:bqmjwcl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/103390c3d42959be2466e297bce5c221b2e86af0/docs/developer/modules/core.md#L48)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can also add the picture filter added lately
</blockquote></details>

Added 

---

*[src/locales/help/default/fr-CA.md, line 195 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993#-Kmlyiz88QH1drgnvJM9:-Kn5N8MpD9H0aApb8m70:bpxi63) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/103390c3d42959be2466e297bce5c221b2e86af0/src/locales/help/default/fr-CA.md#L195)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

La carte principale contient une flèche **du** nord. On ~~le~~ **la** trouve en haut de la carte. ~~Il~~ **Elle** se ~~déplacera~~ **déplace** horizontalement sur l'écran de sorte qu'~~il~~ **elle** traverse toujours une ligne droite imaginaire qui ~~dé~~passe **par** le centre de la carte et le pôle nord.
</blockquote></details>

Thank you! Sometimes I wonder why in an age where we can land rockets on pads floating in the ocean, or soon to be self-driving cars (watch out!) we can't get translations right. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/help/default/fr-CA.md, line 195 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993#-Kmlyiz88QH1drgnvJM9:-Kn5nk31DzuPWXg8v9R8:bo48ckk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/103390c3d42959be2466e297bce5c221b2e86af0/src/locales/help/default/fr-CA.md#L195)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Thank you! Sometimes I wonder why in an age where we can land rockets on pads floating in the ocean, or soon to be self-driving cars (watch out!) we can't get translations right. 
</blockquote></details>

:smile: you are right but translation can be very hard sometimes especially when you go to French (my girlfriend, she is a translator so I heard about it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1993)*

**Pull request merged**
