### PR TITLE
Support for WMS additional styles

### LINKED ISSUE #332: Support for WMS additional styles
Consult GeoMet Team (@alexandreleroux and @tomkralidis for more information about this potential requirement. WMS layers can be styled in many different ways and expose several of these options in their Capabilities -- how can we best ingest and handle multiple style configurations for the same layers?

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #332 

## Testing
:eyes: 

To test, add any WMS layer and open the settings panel to change styles (Styles are only shown if there is more than 1 style available, otherwise the subheading is not shown)

This can be used: http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities

## Documentation
Comments, JSDoc

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2416)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2416)*

**Comment by james-rae** [comment]
Any changes to the config schema?
Do we need to handle any defaulting if a WMS config is provided with no styles defined?
(not sure, maybe this is already handled)

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2416#-:-Kw5voel5opZvp1jotIA:b-wwn2mr)*

**Comment by JahidAhmed** [comment]
@james-rae I don't think we need to handle it since if there is no style, it will just be blank which happens by default I believe

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2416#-:-KwfI3d1yDChZKOzLIds:btxsvof)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2416)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r2, 1 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2416#-:-KwfYly6MmYbITgb6aVT:bnfp4nl)*

**Comment by milesap** [comment]
:eyes: approved 

---

Reviewed 3 of 6 files at r1, 1 of 3 files at r3, 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2416#-:-KwjNASX2yuN7Lmnz-Bc:bekbn4c)*

**Pull request merged**
