### PR TITLE
fix(loader): keyboard user issues in add layer

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Relate to #1595.

Solves keyboard navigation problems for add layer.

## Testing

Chrome, FF and Safari

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1662)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/common/_all.scss, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc39sXrsB1nEhBJ5OPd:-Kc39sXrsB1nEhBJ5OPe:bwwiqxy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/content/styles/common/_all.scss#L87)):*
> ```SCSS
> // when we set name attribute, a select element is created and it becomes a hidden tab
> .md-visually-hidden {
>     display: none;
> ```

This might be dangerous, as this will `display: none` all visually hidden elements. I don't think we should do that, they are just visually hidden for a reason.

I suggest we target on that extra field generated in the file/service loader because we know it's harmful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-:-Kc3lY6XgMfPXn1IgyQt:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/loader/loader-file.directive.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc3m9q8pmqxV1OAMAGl:-Kc3m9q9078DJqaprwko:bgc5aam) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/app/ui/loader/loader-file.directive.js#L53)):*
> ```JavaScript
>                 onContinue: uploadOnContinue,
>                 onCancel: () => onCancel(self.upload.step),
>                 onKeypress: checkContinue,
> ```

If these functions are only being called from one place I think it's better that we inline them.  Same for `checkContinue` in `loader-service.directive`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/loader/loader-file.directive.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc3m9q8pmqxV1OAMAGl:-Kc43OwA4uZGsOmn8aQA:b-y5ugi7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/app/ui/loader/loader-file.directive.js#L53)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

If these functions are only being called from one place I think it's better that we inline them.  Same for `checkContinue` in `loader-service.directive`
</blockquote></details>

When you say inline them you mean do the same thing as onCancel on the row above?

---

*[src/content/styles/common/_all.scss, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc39sXrsB1nEhBJ5OPd:-Kc426V8vhA1Gso7a0sU:bosjp05) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/content/styles/common/_all.scss#L87)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This might be dangerous, as this will `display: none` all visually hidden elements. I don't think we should do that, they are just visually hidden for a reason.

I suggest we target on that extra field generated in the file/service loader because we know it's harmful.
</blockquote></details>

So on open, you would like to delete select tag inside md-input-container? We can restrict the visually-hidden display none to only select tag inside md-input-container. I check fews samples on the web where they use md-select and none of them get the hidden select tag generated tag. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/loader/loader-file.directive.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc3m9q8pmqxV1OAMAGl:-Kc4ACZpYLF306u7kIX4:b-v08nfj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/app/ui/loader/loader-file.directive.js#L53)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

When you say inline them you mean do the same thing as onCancel on the row above?
</blockquote></details>

Yes, in this case I think since the function body is really small it is pretty readable on one line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/content/styles/common/_all.scss, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc39sXrsB1nEhBJ5OPd:-KcISU2YOzU1bAL_q0su:b-pmqxn5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/content/styles/common/_all.scss#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

So on open, you would like to delete select tag inside md-input-container? We can restrict the visually-hidden display none to only select tag inside md-input-container. I check fews samples on the web where they use md-select and none of them get the hidden select tag generated tag. 
</blockquote></details>

No, not delete it, but to write a more specific css rule - put it under `rv-stepper-item` in `modules/_loader.scss`. This should be specific enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/loader/loader-file.directive.js, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc3m9q8pmqxV1OAMAGl:-KcIyypdJQpv9mlpIE_B:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/app/ui/loader/loader-file.directive.js#L53)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Yes, in this case I think since the function body is really small it is pretty readable on one line.
</blockquote></details>

Done.

---

*[src/content/styles/common/_all.scss, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662#-Kc39sXrsB1nEhBJ5OPd:-KcIxSS2Y-u1ttqwWPpj:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f071a0cba46a73e35452a2da9dfd5c6e1fca1782/src/content/styles/common/_all.scss#L87)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

No, not delete it, but to write a more specific css rule - put it under `rv-stepper-item` in `modules/_loader.scss`. This should be specific enough.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1662)*

**Pull request merged**
