### PR TITLE
feat(datagrid): add ui panel to set filters and global search capabil…

### LINKED ISSUE #1416: UI for datagrid filters setting panel
Develop the filters UI following the mockups and comments from #1240. Items from #155 should also be taken into consideration.

- [x] Global Search
- [x] Button Cluster
     - [x] Apply to Map Button (show when filters changed)
     - [x] Clear Filters
     - [x] Toggle Filters Settings
- [x] Grey Out Map when Filters Changed and Map not Updated
- [x] Filters Settings Panel
     - [x] Reorder Fields
     - [x] Hide/Display Fields
     - [ ] Set Filters Type (string, number range, date range, selection)
     - [x] Set Filters Value
     - [x] Set Sorting Fields

### PR DESCRIPTION
**Pull request by jolevesq**
## Description
Contains requirement from #1416 and #1417.
* Filters on datatables are only there for large layouts. filters are always present on setting panel
* When you type a value in a filter, it writes the info on the console
* When you execute an action (sort, display) it writes to the console. For sort, it updates the icon
* Values persists when you close, open a new table and reopen the first one.
* Global search filters the table as you type
* Other filters are ui only, not code behind
* When you modify a filter, Apply map button appears. It disappears if you remove the filter or click clear all filters button

## Testing
Visual and function tested (function writes to the console)

## Documentation
Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

…ities.

Setting panel will be use to set filters value, hide/show columns, reorder columns. Global serach will search trought the whole datagrid. When filters are modify map will be gray out and apply map button willbe visible.

Closes #1416

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1527)

### CODE REVIEW

**Comment by mweech** [comment]
thinking of the amount of real estate it takes up, should we only have the filtering fields, etc. visible when in a maximized data grid? split view would be a reduced set of features..?

**Comment by AleksueiR** [comment]
Top filters are only available on the large layout anyway, so it should be fine, I think.

---

Reviewed 1 of 20 files at r1.
Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527#-:-KZSjofrUHhUBCDAOpkn:b1y5mx0)*

**Comment by mweech** [comment]
my laptop in "large layout" is only 1366x768.. its a pretty common laptop resolution outside of dev machines.

capture

**Comment by AleksueiR** [comment]
Good point. @jolevesq What do you think of showing top filters only when the table is maximized? Users will lose the ability to see the map and filter the table right away (can be done through the filters panel anyway).

---

Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527#-:-KZSlW75Jq7R2LwwKvLz:b9je1rw)*

**Comment by jolevesq** [comment]
Hummm.... Not sure about this. The filters takes only one line of data. Filters can be use to filter the map as well so seeing the map at the same time is good. I think having the filters only for maximized view will confuse the user.

---

Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527#-:-KZWTe23EA3fG-6UT0Uf:bkus4tv)*

**Comment by mweech** [comment]
I have to favor the feedback that has come from the Web Presence team.  It is very important to maintain a good viewing experience of the data within the table first, and the features of the viewer to filter that data table must come second.  In this case, data > features.

**Comment by james-rae** [comment]
I think things will be ok, but may want to do a quick re-test after https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1552 gets merged.  Small possibility that the escaped column names in the datatable may invalidate some equality checks

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527#-:-K__1uRNQk3VFncmm8wy:b-if0i5y)*

**Comment by AleksueiR** [comment]
Reviewed 19 of 20 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 99 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527#-K_d_gV1mw456R_Rpcx2:-K_d_gV2WwpH7wwQEY7P:b-uw9i3k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/351760ce23c895aa0c132f68fb1fac1e13c5a092/src/app/ui/filters/filters-default.directive.js#L99)):*
> ```JavaScript
>             const columnTypes = {
>                 esriFieldTypeString: {
>                     init: () => { return { value: '' }; }
> ```

Non-blocking.

There is a neat trick to have an arrow function return an object without the `return` keyword:
```js

init: () => ( { value: '' } )

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 99 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527#-K_d_gV1mw456R_Rpcx2:-K_jNVIngGfn8TUnuM0Q:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/351760ce23c895aa0c132f68fb1fac1e13c5a092/src/app/ui/filters/filters-default.directive.js#L99)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Non-blocking.

There is a neat trick to have an arrow function return an object without the `return` keyword:
```js

init: () => ( { value: '' } )

```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1527)*

**Pull request merged**
