### PR TITLE
Add `undo` option when removing layers

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/351)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.directive.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351#-KBJPI3bMJpBEGRoWW_j:-KBJPI3bMJpBEGRoWW_k:1206769619) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b355b6f19d03faa7f240dfb6bc42c7c1aab5422f/src/app/layout/shell.directive.js#L2)):*
It stopped working when positioned directly above function declaration.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Comment by ec-dev** [comment]
Reviewed 10 of 22 files at r1, 1 of 3 files at r2.
Review status: 10 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Comment by alyec** [comment]
Reviewed 18 of 22 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 8 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351#-KBOYJXjRcEk4etDuQQ7:-KBOYJXjRcEk4etDuQQ8:796512398) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1b9be9cd99f5f1d5d415117bb6381bbe44d90/.travis.yml#L8)):*
Why do we need this (i.e. are there cases where pushing to test/branchName doesn't work)?

---

*[src/app/layout/shell.directive.js, line 15 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351#-KBOWlvCIu1L0_cabgDx:-KBOWlvCIu1L0_cabgDy:1887857923) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1b9be9cd99f5f1d5d415117bb6381bbe44d90/src/app/layout/shell.directive.js#L15)):*
Needs updating now that this a directive.

---

*[src/app/ui/basemap/basemap.directive.js, line 88 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351#-KBOXExI9CXYRjtDOKP3:-KBOXExI9CXYRjtDOKP4:1652598207) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1b9be9cd99f5f1d5d415117bb6381bbe44d90/src/app/ui/basemap/basemap.directive.js#L88)):*
Can you fix up the `var`s or leave a comment so we don't forget to clean this up later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Comment by alyec** [comment]
Reviewed 1 of 22 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Comment by AleksueiR** [comment]
Review status: 23 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 8 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351#-KBOYJXjRcEk4etDuQQ7:-KBOZHjs0TWlUYJTaaVN:505592016) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1b9be9cd99f5f1d5d415117bb6381bbe44d90/.travis.yml#L8)):*
My PR failed two times yesterday because I didn't run protractor tests. It's a pain to run the locally, so it would make sense to run them on Travis, especially if you are submitting a PR from a different branch (not `develop` or `master`).

---

*[src/app/layout/shell.directive.js, line 15 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351#-KBOWlvCIu1L0_cabgDx:-KBOZnhdkTZKgD8ZYQ36:332919901) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1b9be9cd99f5f1d5d415117bb6381bbe44d90/src/app/layout/shell.directive.js#L15)):*
Will do in the next PR.

---

*[src/app/ui/basemap/basemap.directive.js, line 88 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351#-KBOXExI9CXYRjtDOKP3:-KBOZxxe3MiORdDvJZsT:-1535998633) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1b9be9cd99f5f1d5d415117bb6381bbe44d90/src/app/ui/basemap/basemap.directive.js#L88)):*
Will add comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Comment by alyec** [comment]
Reviewed 1 of 22 files at r1, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Comment by spencerwahl** [comment]
Reviewed 19 of 22 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Comment by ec-dev** [comment]
Reviewed 5 of 22 files at r1, 1 of 3 files at r4, 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/351)*

**Pull request merged**
