### PR TITLE
Feature/i18n

### PR DESCRIPTION
**Pull request by james-rae**
Re-submission of past commits with working tests.
Nav widget also converted.
Lots of strings pre-added ahead of conversion

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/314)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by alyec** [comment]
Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by AleksueiR** [comment]
Reviewed 9 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/mapnav/mapnav.service.js, line 97 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314#-KAFY-PS42GpvrCOk5bo:-KAFY-PS42GpvrCOk5bp:-1064356123) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6b1b5cc2d2c0e79bd718f213ad53c335921c1b6d/src/app/ui/mapnav/mapnav.service.js#L97)):*
Does `onReady` fire when you switch to a different language?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/mapnav/mapnav.service.js, line 97 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314#-KAFY-PS42GpvrCOk5bo:-KAFdP4sy-uIpMIPzZuJ:926331324) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6b1b5cc2d2c0e79bd718f213ad53c335921c1b6d/src/app/ui/mapnav/mapnav.service.js#L97)):*
I think there is a better way to do this:

In `mapnav.service` you have
```js
service.controls = {
            zoomIn: {
                label: 'nav.label.zoomIn',
                ....
                tooltip: 'nav.tooltip.zoomIn',
                .....
            },
```

and in `mapnav-button.html` you have

```html
<md-button
    aria-label="{{ self.control.label | translate }}"
    ...>

    <md-tooltip md-direction="left">{{ self.control.tooltip | translate }}</md-tooltip>
    ...

</md-button>

```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by james-rae** [comment]
*[src/app/ui/mapnav/mapnav.service.js, line 97 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314#-KAFY-PS42GpvrCOk5bo:-KAFfbkw_2QYCX3TT8wf:-1438818973) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6b1b5cc2d2c0e79bd718f213ad53c335921c1b6d/src/app/ui/mapnav/mapnav.service.js#L97)):*
onReady fires after the languages are loaded (including initial).  If you do not wait for it, the `$translate` object always returns undefined when attempting lookups. 
I will try your second suggestion to ensure it works (it should); though are you concerned about all the filters you are adding?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/mapnav/mapnav.service.js, line 97 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314#-KAFY-PS42GpvrCOk5bo:-KAFu1Q2Og4g0MX-1SZc:1715719997) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6b1b5cc2d2c0e79bd718f213ad53c335921c1b6d/src/app/ui/mapnav/mapnav.service.js#L97)):*
I'm not sure. It would be nice to do a performance test with filters vs direct assignments. Good enough for now I guess.
Maybe leave a comment about potential performance issues. Thanks.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/314)*

**Pull request merged**
