### PR TITLE
Fix layer positioning error when switching projection or language 

### LINKED ISSUE #2777: Layer positioning error when switching to a different projection
@YaroRoodzit has discovered this issue and please see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2679 for more details.

When switching to a projection different than the initial one.  The layer positioning will be incorrect and the layer re-ordering will also be malfunction.  It seems the information of layer ranking is lost in the transition and it somehow disabled the re-ordering function.

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes #2777 

Fix layer positioning error when switching projection or language by recreating and recompiling the dragular instance.

## Testing

Tested Sample 59
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782)

### CODE REVIEW

**Comment by james-rae** [comment]
*[src/app/geo/layer-registry.service.js, line 370 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782#-LEzQfYp8gu3S1PmCOVs:-LEzQfYq0oye7_DxqdkJ:b-t9qrmo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/630b8f7a68d9667488a0a78b845f64314d775af3/src/app/geo/layer-registry.service.js#L370)):*
> ```JavaScript
> 
>         configService.getSync.map.legendBlocks.entries.forEach(entry => {
>             layerRecordIDsInLegend.push(entry.layerRecordId);
> ```

just looking at all the code that got deleted...are we still considering duplicate and blank entries?  are these no longer a factor?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782)*

**Comment by barryytm** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @barryytm, @AleksueiR, and @james-rae)

---

*[src/app/geo/layer-registry.service.js, line 370 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782#-LEzQfYp8gu3S1PmCOVs:-LEzaRMn1bFghph9nho2:b134ns7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/630b8f7a68d9667488a0a78b845f64314d775af3/src/app/geo/layer-registry.service.js#L370)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

just looking at all the code that got deleted...are we still considering duplicate and blank entries?  are these no longer a factor?
</blockquote></details>

A mistake.  Reverted back.  Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782)*

**Comment by ShrutiVellanki** [comment]
Tested random samples with random projections/languages in Chrome, IE, Firefox :lgtm: 

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AleksueiR)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782#-:-LF2dwLM7VFlC-QOkc2f:b-ajy5xr)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AleksueiR)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782)*

**Comment by dane-thomas** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AleksueiR)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782#-:-LF2mnJ70G5dzVH4DL0t:bnfp4nl)*

**Comment by YaroRoodzit** [comment]
Problem resolved. Tested with index-fgp-en.html AND  index-samples.html

**Pull request merged**
