### PR TITLE
Make north arrow configurable

### LINKED ISSUE #2541: Change North Pole Snowman symbol
Unfortunately, the client services group have been receiving emails about people complaining about the snowman symbol for the north pole. Apparently, some people are offended by it.

Can we change the symbol or make it configurable?

Thanks,

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes #2541 

Make north arrow configurable and support both url and base64 data.
## Testing

sample 55
http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2541/dev/samples/index-samples.html
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2570)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[schema.json, line 744 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4HyX0sXt44JqfYZdot:-L4HyX0tgh6ijirNws9D:bzc4vi2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f75efaaf3ac6e9fc05c9b77a50ade1ddc09b35e6/schema.json#L744)):*
> ```JSON
>                 "northArrow": {
>                     "type": "object",
>                     "arrowIcon": { "object": "string", "description": "The graphical icon url of the north arrow" },
> ```

should be `"type": "string"`

---

*[schema.json, line 746 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4HyoImJP2dACGP0qIA:-L4HyoImJP2dACGP0qIB:byxfncd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f75efaaf3ac6e9fc05c9b77a50ade1ddc09b35e6/schema.json#L746)):*
> ```JSON
>                     "arrowIcon": { "object": "string", "description": "The graphical icon url of the north arrow" },
>                     "poleIcon": { "object": "string", "description": "The graphical icon url of the north pole that replaces north arrow when it's on north pole" },
>                     "enabled":  { "type": "boolean" }
> ```

default true?

---

*[src/app/ui/common/north-arrow.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4Hz4QkHIy0649fCCcZ:-L4Hz4QkHIy0649fCCc_:b7s6lfu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f75efaaf3ac6e9fc05c9b77a50ade1ddc09b35e6/src/app/ui/common/north-arrow.directive.js#L54)):*
> ```JavaScript
> 
>                     if (north.screenY > 0) { // change icon for north pole
>                         if (poleSource) {
> ```

two very similar blocks of code.  can we make a subfunction like `makeTemplate(source, svg, default)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570)*

**Comment by barryytm** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[schema.json, line 744 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4HyX0sXt44JqfYZdot:-L4I9UGJmPfE96ucJOJU:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f75efaaf3ac6e9fc05c9b77a50ade1ddc09b35e6/schema.json#L744)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

should be `"type": "string"`
</blockquote></details>

done, thanks

---

*[schema.json, line 746 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4HyoImJP2dACGP0qIA:-L4I9YYgC_-msTHPpZkC:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f75efaaf3ac6e9fc05c9b77a50ade1ddc09b35e6/schema.json#L746)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

default true?
</blockquote></details>

done, thanks

---

*[src/app/ui/common/north-arrow.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4Hz4QkHIy0649fCCcZ:-L4I9dZ6Jt7rcfedyGnf:b807bau) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f75efaaf3ac6e9fc05c9b77a50ade1ddc09b35e6/src/app/ui/common/north-arrow.directive.js#L54)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

two very similar blocks of code.  can we make a subfunction like `makeTemplate(source, svg, default)`?
</blockquote></details>

done, thanks.  I named it  `_getTemplate(source, isSVG)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570)*

**Comment by milesap** [comment]
:lgtm: ok in ie, chrome. 

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-:-L4ezRGRTuFj3yPj6pR2:bfb8uki)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/common/north-arrow.directive.js, line 39 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4f-1urjn7pghEFd5h2:-L4f-1urjn7pghEFd5h3:b-ke9wh3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4cd61a8293a34b4c0fcb646937ba98892b33d2ba/src/app/ui/common/north-arrow.directive.js#L39)):*
> ```JavaScript
>                 const poleSource = mapConfig.northArrow.poleIcon || 'snowman';
> 
>                 // flags to indicate of the supplied urls are svg or not.  Defaults to true if not provided// flags to indicate of the supplied urls are svg or not.  Defaults to true if not provided
> ```

Double comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-:-L4f-YooB8QRGcLTyZhr:bnfp4nl)*

**Comment by barryytm** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/north-arrow.directive.js, line 39 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570#-L4f-1urjn7pghEFd5h2:-L4fjd-MPfzBF0gfkoj5:brpdd2r) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4cd61a8293a34b4c0fcb646937ba98892b33d2ba/src/app/ui/common/north-arrow.directive.js#L39)):*
> 
deleted, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2570)*

**Pull request merged**
