### PR TITLE
feat(map): Add watermark to the map. The value can be taken from the …

### LINKED ISSUE #832: Add watermark icon/logo to the map
Similar to how esri adds it's own logo into the lower right corner of the map, add logo specified in the config (we can have two options in the config: one image to be displayed in the side menu; another, to be added as a watermark) to the map.

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Add watermak for basemap (#832)

## Testing

Tested in Chrome, FF and Safari. Use the index-fgp-one to test because config file is updated

## Documentation

None

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

…server (default) or it can be set by the configuration file. If set by the configuration file, text content and logo can be set.

Closes #832

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1421)

### CODE REVIEW

**Comment by AleksueiR** [comment]
`index-fgp-en.html`

When switching languages, the esri logo briefly appears and then is hidden. Can we prevent it from flickering like that?


---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/map.service.js, line 325 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-KXfMTy1vlkHpR2-Pa82:-KXfMTy1vlkHpR2-Pa83:bafy2kn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b4cc447a8fcf69ac636b9f9b26009752af60bbbb/src/app/geo/map.service.js#L325)):*
> ```JavaScript
>                     // for not esri basemap, logo should be disable if no custom logo are provided
>                     // because esri logo and liks are the default values
>                     attNode.removeClass('rv-attribution-hide');
> ```

Does this work? `attNode.hide()`  if not, you can use `ng-hide` class, instead of creating a new one.

---

*[src/app/geo/map.service.js, line 328 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-KXfMHftCQ-fjZr8EAEW:-KXfMHftCQ-fjZr8EAEX:bs0jem0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b4cc447a8fcf69ac636b9f9b26009752af60bbbb/src/app/geo/map.service.js#L328)):*
> ```JavaScript
>                     logoNode.removeClass('rv-attribution-hide');
> 
>                     if (cfgAtt !== undefined) {
> ```

Please use the following check for undefined:`typeof cfgAtt === 'undefined'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-:-KXfMzFH0tVl_nE9iOZe:bbw7rat)*

**Comment by jolevesq** [comment]
Yes we can do something... maybe not pretty

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/map.service.js, line 325 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-KXfMTy1vlkHpR2-Pa82:-KXgn3KnlRqYfE4A4szw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b4cc447a8fcf69ac636b9f9b26009752af60bbbb/src/app/geo/map.service.js#L325)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Does this work? `attNode.hide()`  if not, you can use `ng-hide` class, instead of creating a new one.
</blockquote></details>

Done.

---

*[src/app/geo/map.service.js, line 328 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-KXfMHftCQ-fjZr8EAEW:-KXgn3goxZ96Yj2-uuvB:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b4cc447a8fcf69ac636b9f9b26009752af60bbbb/src/app/geo/map.service.js#L328)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please use the following check for undefined:`typeof cfgAtt === 'undefined'`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-:-KXgmyS7WU21UeMXM4bF:b-rbmdwq)*

**Comment by AleksueiR** [comment]
:lgtm: Thanks!

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/map.service.js, line 350 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-KXkrGsz_C_tyNqUwK4O:-KXkrGsz_C_tyNqUwK4P:bcn8d17) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/46ce7ecac2c42aa306bc8269a865c59daf013f87/src/app/geo/map.service.js#L350)):*
> ```JavaScript
>                         } else {
>                             // jscs:disable maximumLineLength
>                             logoNode.css('background-image', 'url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEEAAAAkCAYAAADWzlesAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAADO9JREFUeNq0Wgl0jlca/pfvzyo6qNBSmhLLKE1kKEUtB9NTat+OYnBacwwJY19DZRC7sR41th60lWaizFSqRTOEw0lsrQSJGFIESSxJ/uRfv3nef+7Vt9f3p2E695z3fMt97/3ufe+7PO+9n9n0UzELsjKyiHdUdMZnVHTl2VyFe9nO7Kc/Io+4epUxmpWxeVkbr3hvUebgFf15GL9XUwZHndtAAYI09jGvIghOuoEwLOLeYiBoXrwGfZjYYOWAvWyMGlsk2YebXeV3NUEW1qcT5BBX4jUbCYEmHwwKEfdW1gEXgoWtiIlNRFeezcrkrQaTNSuraRYDdImrR1ylAALZBPnkXIJ0wRskeG2Cj3jsoFI2HhcfDDFWA9UBNdZZyc/PP4Z3HZYsWTLGbrffond0Xb9+/Qy6P3jw4F+HDx8+mu7XrVs3c+7cuX+i+3nz5o3n/Rw4cGAdf/7hhx9SZ8yYEcffHT9+/G/8uaSkJGvDhg3D8P3moNdXrlw5UtYVFxfnXL9+/V8PHz68grr2N2/eTC4tLb2E+9+Cotq1a/dOenr6njt37nxPdOrUqd0dO3bsjromoHBQKBPkEyFUB71MH6SPbNy4cRqfkMvlenzixImtqO/x3XffbXc6nSW5ubnpOTk5J1NTU/cQH91//fXXu3/88ccLy5cvj6d34B8gaBA9JyQk/OWjjz5aIu8Fz2DiWbZs2QLx/A4m0Qf9f/n48eNsPEeDfrdly5Y/U31UVNT7dJ04ceIsGseNGzfS6DkuLq4v8YE6Y/G+93g8XKZ6QUHBRVHfAPQC0xJfCRAv65EkeUP6gFx11JEkfw/qTc8ff/zxKofDUXrv3r08rOIBeU9CWbx48SLej5y4LGlpaf9YuHDhUv5OtqH+6Vty0riPAbWjheH8n3322VYpuG+//Xa5mGB7CGM8hKN7vV5dLfHx8WNI20E1aN4WP97YZyc7d+6MM5vNHRs2bDg3NjY23e12l5w8eZJWzIUJ9IdmlI4bNy4tICAgtHbt2hGdOnXaSe3oftu2bWmBgYFOn3MwmwcQLViwIJOeYVYJGGAZVuW2zWZzCZ6hoIGapnmknUMTQnr16vUeTOKydHqyHrx9t27dunro0KEfzJw5M4Pe3bp166Z0pHXr1g0Fj2EYCw8PD+N+SjNwUuSAKnxexOkswOWxZN63b9/MAQMGzIUwx5WXl99eunTpFLx+hJU/K9o/yM7OPhgZGdk5KSkpp0WLFv+Vrq7/na5nz57dR1dM6t7hw4e3DRkyJG7WrFlxgudzukIw58TzV3SF3Z+ByUzFbTk5O9j8fVH/JV3PnTv3uRijSdSR5/empKRkT5kypQxCC+UTxMKVQXuyWBT5WbiS4VFjIZLHWQsLN1ZFgFbm0U1KSNWUUMlDp9kAh0iNdCkRwiva2FjUsjJeJ5sYRYQwCGIYNGk8tC1UCuDQoUOb+vbtuxuPRUJ4FVwIFhZ7pUD45OXEbUpo9DIz8hgAFk0BORblWypm8BiQzkKnpoRnM+PxsEWhiYfFxMTUHTx4cDOYhg7tzM7IyLhNCiYEUEbCMxsAGYuCGjl4ClKE4GY+xCnIw95zBKqxvmyCOJqT7dws5ntZzLcoaJEjQiPUahMaESzudWEqhBEeiSuZvUvzA1+lxIMEhbD7QGYKUl0rBAgxC9vlq6IzNZZ9BYt+rMw8pBDLmSZZFBPQmBC8imaofo1roa5oKH82aQaaIH0CDTZM0sCBAxvBKbZ+7bXXGr3yyisN4ZjMDx48uAeAkofQdHbt2rUXhIpJKevMJwSLfqq3bt365enTp3eFh365SZMmBGpMFRUVZcAV1wFmzs2ZMyddtCkXk9ESExOjq1Wr9iLCbwAilA9xwrnlwimS4G2ffvppj1atWrWoWbNmbWCKAtj9V5MnT84cMWJEvTfeeKM+wqSFzCEoKMgJ3HEVgO6SkTlKMwgUgImwArn2DpMmTYrDALP0XyjEA9sbjTZtQZGij7qghqBWoK4AWPswkbLK+qHIsWPHjoXgfwvUhsZAAEflg+dfg0kuBlosUuvoO2jXl65qXWZm5g7UNRPIOIQLQqpcmECMJIAuRp1UVmiCACmTxAReFx+LhnPqV1hY+O9n6evIkSObSXCEHI0WASDtMMJ0uVHb7du3E6p9HxpxQK0DjN4r0Gc9kSZYeZiSNkuaUOv06dPTO3fuPNj0DAWgKWTFihVL+vfvT0J8kfohAsobV6tWrYbP0hf460pnLE2AF2jB21DvIKO2gO6FNB+ERJtaB+xjY37NN3+LogmkHi9s2rTp3bZt277LG8NuK5AopXbv3n0O7Gtsjx49ZmNye6GOD1RBwD9MFUKoSQSc30UdzJUrV26uWrVqP7D/lt27d+9/9OhRMas7gjYbhROzkv9R2wcHBwdWshjkYL1G7SBQTXGwTwQQLLIqWsGeGFAhVyFSO6C7Naj7ADRUJENDQGMjIiLmQl0LVLUbNWrUItSPhBNcodYhFyFklwAiYf0RNKZZs2YfFhUVXYcAvhFm0FFc++fl5eX4Mxto7JnRo0cvID4yHWSz70dHRw+khAxZ6yGVH8ndftS9DWokciWNx15fTN2zZ0+f6tWr1+LS279/fwYgcz4LPzJvdyGVLUFidFiVOIRAqx8KlQysZCdKboJUXL58uRAmMLFp06aLRbh1cGhrVEiD3nzzzTXIcU5R6gC6vXfv3kuIGgSIyq1Wq6cqpmdhiNAXFtu0adNeZVq9enUWA0xywyVECC4AicwttQ2SrvpkYnfv3i1X6xo0aPAiJv2H+fPnt27UqFEN4YsCDBCk33Lt2rW8kSNHJuP2LqUc4kq+4KFAgg6LxeKtSl+a4hMC6tSp85QD27VrVy9I1U2SJaKYS/ZG8Rf5uhVXq91ud4aEhATINo0bN46glUQMv4aQV46MMpj3iRVvsGjRohFEENQtygCRmZ5B6DsqNNPFANJT5cyZM5RoPRBE/qREaJYEYm4aZ1WFwDG9ppoClebNm9czPV/xYXOo6J4xY8Z84I8Jgq9HBCDVfsKECR+mpqZ+gSQnRVQHGTm4CxcuXBP9l4qrneUNPtheVSFYKtkF/jUKqWbx2LFjUxBJViA82asSZvv06TPq+PHjE/D4GzI70jiVT+xDyBzDo8DhZyoWNXsD4Cn/FYVQLKgIofCfMIkhgKyr4bhO8pBoVGgvsEuXLq+SEIw0Qayyl5H+vIPUmJf2ZYOwz5twXE05U/369TfBZu+wvMBpkH7L3dwyYZ+l4uoRPL50FzCcQuAJstvIyMjacG5Rw4YN64b7V9XBxcbGdgJq/cZIE4TT0/2ceTyzJsiMj0JSxfnz50+rTECBUUq2aGd2WC7Izib+WFwdLJs0sczT1w+Q3d34+PhTSKQ2w4GeVL9LTtefY1Q2YEz/qxC8LIe3f/LJJ2kqU79+/WIGDRpUj+0L8N0lG7B6N+QGiS1btgxR9ha8gi949uzZ0UiENgBSR4iQyFNiL0zkrh+V/78XfjJDq1aWnJx85dixY8kqRE1KSopNSUkZ0K1btwjhsGpMmzatbVZW1nTy/JQbQHUXA26HMRul/gOQHkcBUK1BBGiJFHgtcMV7YqeXeEM7dOhQB4lXh6dCS1kZaZbDSBjinV6ZhsBkdAMz0o00SO4hhIrUl7K/7vfv37+hP0eBw8tBftFRpNNNExMThyMqlKp8SEXsADy5t1GM+qF6CHwe+hifm5t7Ta1PSEiYj7rWIhsMZaCPEkDyL+2PHj36hdqO3lGd4KkuYbN0jC5h22TPRT179pwCZ5j9rKqF0FWtd+/eL0kBA9Y2kRudvBB4og2al1CM+iFsgQFfJTCkaZrboL2DhUfd4NjAadROvHPyvUsLayxNghxaMWw0D1EhFiguqSrxXWZ/EN7IyZMnX5QHn127dk0Gxo+nnd6q9EHf2rx58zJgC1oxSrQKgR1cKl9YWJhdOFg329TlC1oBM3YYZJ8OubcozVZTJPjkzEEwOBGr1yIr+xz23xX23i48PPxVjiqRQV6GRuetXLkSbiPpCsPuTulzEAYPAh+cnzp1ao+YmJi31D5gevkwo3sZGRmn0M+RzMzMAhFtaGG0ixcvfpmfn39WbpNBC1zILK8KHqdykCsXszQ7O/sE8WMBNKGlbrxLF1HsSeQyV5JQBSrJUghLdDQmKB46ywTJFTKzfqqxftScwM1OjGXY/Vl0UU7IHcq3XMrutkz0QsX3bOwEWo5TfsNj9hMxjP5VCFR2fPl/AS4xMH7u71X6CWR92JQjer5t72AHLrpyKGRRhKbCZrNybhJg8HvBU+385Qv8DMKi/BjBEaKuHJK42YDU/x789cFhu1s5cFH/hTAp3/UqhzMm5cTM6G8br/qnyi8lTWYDoZiUP1TUEyc1Ble1D5OSA+gG7U0GR3b+fhUy+kVIN0Kb/xFgANrk0XIqRaL0AAAAAElFTkSuQmCC)');
> ```

These two images seem to be the same. If so, can we move them into a variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-:-KXksZhsmVM4GWvXlQ-W:b-g2a5fb)*

**Comment by james-rae** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421)*

**Comment by jolevesq** [comment]
Done and did the rebase, thanks for the comments

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 350 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-KXkrGsz_C_tyNqUwK4O:-KXm4D34J4Q8r6VCqV9n:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/46ce7ecac2c42aa306bc8269a865c59daf013f87/src/app/geo/map.service.js#L350)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

These two images seem to be the same. If so, can we move them into a variable?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-:-KXm4DlWHRgH0ovVYbsq:by47a93)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1421#-:-KXp_mdjGkyfNmYVxvtK:bnfp4nl)*

**Pull request merged**
