### PR TITLE
Improve docs for WFS 3

### PR DESCRIPTION
**Pull request by elsa-huang**
For #3837: update config schema and wizard select-format text

The schema update was slightly blind. Let me know if its totally wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)

### CODE REVIEW

**Review by milespetrov — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsa-huang)

**Review by james-rae — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: all files reviewed, 1 unresolved discussion (waiting on @elsa-huang)

___
*[packages/ramp-core/schema.json, line 1275 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923#-MbCx7gZA1h-Vune-BJ8:-MbCx7gZA1h-Vune-BJ9:b-a745el) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f78015fbca6f2fd849793e88cee334285b8f4d5/packages/ramp-core/schema.json#L1275)):*
> ```JSON
>                 "url": {
>                     "type": "string",
>                     "description": "The service endpoint of the layer.  It should match the type provided in layerType."
> ```

Lets buff this description too. The `layerType` (as a string value) doesn't indicate version, so can add something like "WFS v3 support only".

**Review by elsa-huang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @james-rae and @milespetrov)

___
*[packages/ramp-core/schema.json, line 1275 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923#-MbCx7gZA1h-Vune-BJ8:-MbD1k8R2vEStKnybhd6:bah2568) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f78015fbca6f2fd849793e88cee334285b8f4d5/packages/ramp-core/schema.json#L1275)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Lets buff this description too. The `layerType` (as a string value) doesn't indicate version, so can add something like "WFS v3 support only".
</blockquote></details>

Donethanks

**Review by james-rae — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsa-huang)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsa-huang)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsa-huang)

**Review by sharvenp — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsa-huang)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsa-huang)

**Pull request merged**
