### PR TITLE
fix(ui): remove split/max options in datatable for sm/md layouts

### LINKED ISSUE #1678: Remove Split/maximised options in datatable for small/medium layouts
Tested version: http://fgpv.cloudapp.net/demo/v1.5.0-rc3/prod/samples/index-fgp-fr.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,on_crop,Barley

Split/Maximised options for a datatable does not add any value when the Viewer is used in a mobile platform. Since the screens are small, users cannot differentiate between these 2 views. The datatable in this case should always be maximised.

### PR DESCRIPTION
**Pull request by milesap**
## Description
remove split/max options in datatable for sm/md layouts

Closes #1678 

## Testing
:eye: 

## Documentation
none

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1705)

### CODE REVIEW

**Comment by AleksueiR** [comment]
If the layout changes after initialization, the binding is not updated and the options are still visible (or hidden, depending on the initial viewer size).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1705#-:-KdC8FGku04B9QcPBose:bpvlttd)*

**Comment by milesap** [comment]
Changed so resizing at any time works

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1705#-:-KdC9pkjhZ6MmqHFH0jW:b-48p08c)*

**Comment by AleksueiR** [comment]
Yeap, thank should work :+1: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1705#-:-KdCA8aRmmKpmPSdXVMm:ba239tm)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1705#-:-KdCDY02V5W9VdUCepFP:bnfp4nl)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1705)*

**Comment by jolevesq** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1705#-:-KdCLux_PB5-w5OF7rVO:bg7igkv)*

**Pull request merged**
