### PR TITLE
Extent Restriction

### PR DESCRIPTION
**Pull request by james-rae**
## Description
Option to have map extent restricted to maximum extent (as defined by the config).
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1320

## Testing
There are unit tests in the geoApi part.

## Documentation
jsdoc, config schema

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1391)

### CODE REVIEW

**Comment by alyec** [comment]
I don't think any of the configs have this option set.  Doesn't seem to break regular panning.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 67 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-KWnoDi03RuU6siCM_qP:-KWnoDi03RuU6siCM_qQ:b-yek1zo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4eeddf93c81a5328d70515b44687fc8f6bcd563/src/app/geo/layer-registry.service.js#L67)):*
> ```JavaScript
> 
>             // set event handler for extent changes
>             // TODO consider listning to the $rootScope.$broadcast 'extentChange' event instead
> ```

typo: listening

---

*[src/app/geo/layer-registry.service.js, line 156 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-KWnoNDo_OaRhrE2m7oV:-KWnoNDo_OaRhrE2m7oW:bfju801) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4eeddf93c81a5328d70515b44687fc8f6bcd563/src/app/geo/layer-registry.service.js#L156)):*
> ```JavaScript
>                     const extentTest = gapiService.gapi.mapManager.enforceBoundary(params.extent, geoState.maxExtent);
>                     if (extentTest.adjusted) {
>                         // NOTE: the map wil not do a smooth pan because we have pan duration
> ```

typo: will

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-:-KWnrY3x2rs3mKP7uVAC:bon5p8z)*

**Comment by james-rae** [comment]
What would be standard procedure here? Make a new config/html pair for person testing?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-:-KWns7bMVHh_86XaTd7k:b-h65e4w)*

**Comment by alyec** [comment]
With something this small I'm okay with a WOMM from you.  You could also change the existing configs and publish to a custom (i.e. not versioned) tag like `jamesExtentTest`.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-:-KWnsKD0LOL1nPFUIVW2:bmwcxoi)*

**Comment by james-rae** [comment]
I've made a testable sample on my own repo. It is restricting at the regular full extent.  You can try it [here](http://fgpv.cloudapp.net/demo/users/james-rae/test/restrictExtent/dev/samples/index-fgp-en.html)

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 67 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-KWnoDi03RuU6siCM_qP:-KWnyNqgI7KGMCqhLb6Y:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4eeddf93c81a5328d70515b44687fc8f6bcd563/src/app/geo/layer-registry.service.js#L67)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: listening
</details>
donethanks

---

*[src/app/geo/layer-registry.service.js, line 156 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-KWnoNDo_OaRhrE2m7oV:-KWnyPmurqKKGHxc0Xzl:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4eeddf93c81a5328d70515b44687fc8f6bcd563/src/app/geo/layer-registry.service.js#L156)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: will
</details>
donethanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-:-KWnySVWmPEidX5xPX1V:b94ynro)*

**Comment by alyec** [comment]
There's a bit of odd behaviour: if you zoom out completely and the scroll off the map it changes the zoom level when it snaps you back

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-:-KWoRNpktod83r5sG4z2:brkh9mu)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/layer-registry.service.js, line 67 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-KWnoDi03RuU6siCM_qP:-KWrMH9bgB50Th7IRR7h:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4eeddf93c81a5328d70515b44687fc8f6bcd563/src/app/geo/layer-registry.service.js#L67)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> donethanks
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391)*

**Comment by james-rae** [comment]
Hmmm let me try doing a `centerAt` instead of a `setExtent`.  Hold off merging for a bit

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-:-KWrtcfx-mIbxo0RMst0:b4f202i)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391)*

**Comment by alyec** [comment]
:lgtm: (only testing for not breaking existing demos)

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1391#-:-KWs57Fkk6616XMAe66S:b-isium8)*

**Pull request merged**
