### PR TITLE
fix(ui): point info from ogcwms display in main panel

### LINKED ISSUE #1236: Point Information is populated in Expanded panel and not in Point Info Panel for most of the Railway map Points
Tested using bookmark:http://fgpv.cloudapp.net/demo/v1.3.0/samples/index-fgp-en.html?rv=A,YmFzZU5yQ2Fu,MTY1OTg3NS41NDU0NjYwOTQz,LTExMjcxOC4xNTc1MjI2NTYyOQ,MTc1MDA,MDByY3MuSk9TTS5lbjEwMDAwMDE,MDByY3MuQWlycG9ydHMuZW4xMDAwMDAx,MDByY3MuWm9vbVNjYWxlLmVuMTAwMDAwMQ,MDNyY3MuRWNvQWN0aW9uLmVuMTAwMDAx,MDNyY3MuQ0VTSV9PdGhlci5lbjEwMDAwMQ,MDNyY3MuTlBSSV9DTy5lbjEwMDAwMQ,MDFyY3MuUmFpbHdheXMuZW4xMDAxMDE,MDRyY3MubWJfY29sb3VyLmVuMTAwMDA,MDNyY3MuQmFybGV5LmVuMTAwMDAx

Layer used - Canadian Railway Network

Point information Panel is not populated at all times when querying this layer. However, all info is present in the expanded panel. Issue was found in "Railway Crossings" , Railway Stations and Tracks

screenhunter_2483 sep 27 11 40

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
Point Information is populated in Expanded panel and not in Point Info Panel for most of the Railway map Points #1236

## Testing
Manual tests with index-wet.html and index-fgp-en.html on IE11, Chrome and Firefox

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [ ] PR targets the correct release version

Closes #1236

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1403)

### CODE REVIEW

**Comment by milesap** [comment]
Works for me in chrome and IE :+1: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403#-:-KXHMSse1QA5AId58T6a:b-go79uk)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 480 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403#-KXHaBRkOglE3Zfso09R:-KXHaBRkOglE3Zfso09S:bpr6cxd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db397005a05b301703cbe67401c29a8442394f0b/src/app/geo/identify.service.js#L480)):*
> ```JavaScript
>                         loadingPromises.push(infallibleLoadingPromise);
>                     });
> ```

I can't check the demo as they are all broken for me :(, but this looks like it will delay the opening of the details panel until all the queries resolve. We want the details panel to open as soon as the user clicks on the map and display identify results as soon as they come in. If we wait until we have all the results, the user might start to wonder why nothing happens after clicking the map. We want to keep this behaviour.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/geo/identify.service.js, line 480 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403#-KXHaBRkOglE3Zfso09R:-KXI3OeGVgSGXOR1TPNJ:b-8zsmwl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db397005a05b301703cbe67401c29a8442394f0b/src/app/geo/identify.service.js#L480)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I can't check the demo as they are all broken for me :(, but this looks like it will delay the opening of the details panel until all the queries resolve. We want the details panel to open as soon as the user clicks on the map and display identify results as soon as they come in. If we wait until we have all the results, the user might start to wonder why nothing happens after clicking the map. We want to keep this behaviour.
</details>
I did't experience notable lag time. However, when you'll be able to check the demo just let me know if it is acceptable are not.
I'll go back to the blackboard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 480 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403#-KXHaBRkOglE3Zfso09R:-KXLI8vApDXgTGLGyyiG:b-n0nv50) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db397005a05b301703cbe67401c29a8442394f0b/src/app/geo/identify.service.js#L480)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary>
> I did't experience notable lag time. However, when you'll be able to check the demo just let me know if it is acceptable are not.
> I'll go back to the blackboard.
</details>
Checked the demo - it does wait for all identify queries to be resolved as I thought. We should not make the user wait more than necessary. Need a different fix for this bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/geo/identify.service.js, line 480 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403#-KXHaBRkOglE3Zfso09R:-KXLRmouEXxufbtCSCUg:b32w0x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db397005a05b301703cbe67401c29a8442394f0b/src/app/geo/identify.service.js#L480)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Checked the demo - it does wait for all identify queries to be resolved as I thought. We should not make the user wait more than necessary. Need a different fix for this bug.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403)*

**Comment by AleksueiR** [comment]
Demo works! :lgtm: 

---

Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403#-:-KXM_kD4CB4O1Z2CWh20:b-5d8yd)*

**Comment by milesap** [comment]
Works for me in IE

---

Reviewed 2 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403#-:-KXMaocOhhXinoxL36fv:bnshhux)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1403)*

**Pull request merged**
