### PR TITLE
fix(grid): moved filters to children for dynamic layers

### LINKED ISSUE #2050: Move filtersNode to Dynamic Child Structure
On the config schema, we have `filtersNode`, which describes a datagrid (title, columns, size, any filters, etc). It is implemented as a property of `dynamicLayerNode`. A dynamic layer doesn't have a grid; each of it's leaf children have a grid.

Move the `filters` property from `dynamicLayerNode` to `dynamicLayerEntryNode`, so a grid can be defined for each leaf.

Be sure to test a sample against the code that applies defaults to config structures for dynamic layers.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2050

## Testing
`index-samples.html` with config #6 - Power Plants, nuclear has a custom title

## Documentation
none

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2158)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Need to update the `config-mobile-2` config file since it uses 'fitlers' for the Date Layer.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158#-:-Kox0vCISLhuSndUAz3d:bj89h1l)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158)*

**Comment by AleksueiR** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/schema.json, line 254 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158#-KpGZMM5Eejfy6ZOpsjT:-KpGZMM5Eejfy6ZOpsjU:b-jbvmkj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/24a8c5acdeae4c0d90cd9cdd785d640a97ec0391/src/content/samples/schema.json#L254)):*
> ```JSON
>                 "state": { "$ref": "#/definitions/initialLayerSettings" },
>                 "stateOnly": { "type": "boolean", "default": false, "description": "A flag indicating this entry is only for state tracking (i.e. it should not be displayed on the UI and all of the controls will be ignored, but the layer itself will be displayed on the map with the given state settings)." },
>                 "filters": { "$ref": "#/definitions/filtersNode", "description": "Settings for filters inside data panel"}
> ```

Need to update the config-mobile-2 config file since it uses 'filters' for the Date Layer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158)*

**Comment by AleksueiR** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/config/config-sample-06-structured-legend-dynamic-children-split-layers.json, line 334 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158#-KpGa7ClnEyQpa_KYjM3:-KpGa7ClnEyQpa_KYjM4:bsk4njy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/24a8c5acdeae4c0d90cd9cdd785d640a97ec0391/src/content/samples/config/config-sample-06-structured-legend-dynamic-children-split-layers.json#L334)):*
> ```JSON
>           {
>             "index": 22,
>             "filters": {
> ```

Shouldn't this be `table` though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158)*

**Comment by milesap** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/config/config-sample-06-structured-legend-dynamic-children-split-layers.json, line 334 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158#-KpGa7ClnEyQpa_KYjM3:-KpGb_iHCGhryXYcqzox:b68bht7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/24a8c5acdeae4c0d90cd9cdd785d640a97ec0391/src/content/samples/config/config-sample-06-structured-legend-dynamic-children-split-layers.json#L334)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Shouldn't this be `table` though?
</blockquote></details>

yeah, also corrected another schema reference to filtersNode

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2158#-:-KpKOmYppY5iR9MbTBmg:bnfp4nl)*

**Pull request merged**
