### PR TITLE
Add aria-label and tool-tips for legend stacks 

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2517

Add the missing aria-labels and tool-tips for legend stacks (i.e. legends of a legend)
## Testing

http://fgpv.cloudapp.net/demo/users/barryytm/2.1.1-2517/dev/samples/index-samples.html sample 2

## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2520)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm:

Can you also add the `aria-pressed="false | true"` attribute to these buttons? Not in the original issue, but these are toggle buttons, so this might be useful as well.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role

Thanks.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2520#-:-L0KfWCqwz_K2nyyPIZk:bqf9zyp)*

**Comment by barryytm** [comment]
@AleksueiR Done, thanks

**Comment by AleksueiR** [comment]
:lgtm_strong:  Works nicely.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2520#-:-L0KjrdN5H8xe4K6mheJ:bq895ll)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2520)*

**Pull request merged**
