### PR TITLE
feat(geo): configurable identify tolerance

### PR DESCRIPTION
**Pull request by james-rae**
Supports configurable tolerance value to be used when clicking on features

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/337)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by cynngah** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 77 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337#-KAlNy_CNJ4iy8E2rQ1x:-KAlNy_DGN5BAlzVqpL6:1400827100) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8d60e7869620c18eaf59bd0d9bc731e0d86529a/src/app/geo/identify.service.js#L77)):*
tolerance is already defaults to 5 in `getTolerance`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 77 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337#-KAlNy_CNJ4iy8E2rQ1x:-KAokZDCMOA8G1J98cP1:-1622963403) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0bf180a1c29bb78c0468bc963be7e4dbe6fa5381/src/app/geo/identify.service.js#L77)):*
redundancy, as no one can force you to call this function from `getTolerance`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 77 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337#-KAlNy_CNJ4iy8E2rQ1x:-KAoksJHK0WUQvRMGQFZ:2089325711) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0bf180a1c29bb78c0468bc963be7e4dbe6fa5381/src/app/geo/identify.service.js#L77)):*
in this case, use es6 function default
```js
function makeClickBuffer(point, geoApi, map, tolerance = 5) {
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Comment by ec-dev** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/337)*

**Pull request merged**
