### PR TITLE
fix(ui): endless loop when closing layer loader after details panel

### LINKED ISSUE #366: bug(ui): endless loop when closing layer loader after details panel
Steps:
1. Open layer loader (by clicking on the `Layer Loader File` in the middle of the map)
2. Open details panel by clicking anywhere on the map
3. Try to close details panel by clicking on `X` button in its upper right corner - it closes and the layer loader pane pop us.
4. Try to close layer loader pane by clicking on `X` button in the upper right corner - it closes and the details panel pops up.
5. Goto 3.

Here's gif:

Bug introduced in PR #365.

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #366

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/369)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/369)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/common/router/statemanager.service.js, line 266 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/369#-KC0swAUYSF0sges_pOF:-KC0swAUYSF0sges_pOG:-1477917469) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2105ba79092b4c3e8beeaeac277a8008f11e6fbb/src/app/common/router/statemanager.service.js#L266)):*
rename to currentPaneName ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/369)*

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/369)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/369)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/common/router/statemanager.service.js, line 266 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/369#-KC0swAUYSF0sges_pOF:-KC0u79Tuolhjafohrv4:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2105ba79092b4c3e8beeaeac277a8008f11e6fbb/src/app/common/router/statemanager.service.js#L266)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/369)*

**Pull request merged**
