### PR TITLE
fix(ui): menu placement in IE

### LINKED ISSUE #2052: Full screen IE menu placement
When in full screen mode and one of the menu options is clicked from the legend panel, the placement of the menu appears to the left and not beside the button itself.

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2052.

## Testing
Visually tested.

## Documentation
None.

## Checklist

- [ ] commits messages follow the guidelines
- [ ] code passes unit tests
- [ ] release notes have been updated
- [ ] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2134)

### CODE REVIEW

**Comment by milesap** [comment]
Menu placement seems fixed, but I'm getting a scrollbar on the right side of the screen now. Can this be hidden or prevented by some other means?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2134#-:-Kogn7t7mm69C8GmcM76:bxnckvb)*

**Comment by AleksueiR** [comment]
Hm, we can't expect that styles to the sample pages will end up in the production pages, so this can't really be a fix for IE menu placement. As to the scrollbar, the margin is causing it. The content is now exactly 2px wider and taller than the box, so scrollbars are drawn.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2134#-:-Kolg03wcAyX6b7onQVV:b-udp7uc)*

**Comment by milesap** [comment]
Good point. Perhaps a CSS fix should be selectively applied to IE users by the viewer instead. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2134#-:-KomZJmoxTRlBi-T-N6K:b-7c4j9x)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2134)*

**Comment by AleksueiR** [comment]
Closing for now. Needs to investigate more.

**Pull request closed without merging**
