### PR TITLE
Resize Info section images on export 

### PR DESCRIPTION
**Pull request by barryytm**
## Description

As title
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2393
## Testing

http://fgpv.cloudapp.net/demo/users/barryytm/2.1.x-2393/dev/samples/index-mobile.html
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2495)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495)*

**Comment by AleksueiR** [comment]
Demo works :+1: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/ui/export/export-legend.service.js, line 246 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495#-L-BoqVm0lu0SLughgA7:-L-BoqVm0lu0SLughgA8:bgnma27) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53306dd767db60c11cf875acd9fc985f06bd37e5/src/app/ui/export/export-legend.service.js#L246)):*
> ```JavaScript
>         const lineSet = container.set();
> 
>         items.forEach(item => makeLayer(item, sectionWidth));
> ```

`makeLegendElement`, 'makeGroup', 'makeItem' and other functions are scoped to the `makeLegend`, so they should already have access to `sectionWidth`, and since this value can't change while the legend is made, there is no real need in passing it through all these functions.

---

*[src/app/ui/export/export-legend.service.js, line 340 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495#-L-BnNnnpVbjbp0YywM5:-L-BnNnnpVbjbp0YywM6:bq56qr0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53306dd767db60c11cf875acd9fc985f06bd37e5/src/app/ui/export/export-legend.service.js#L340)):*
> ```JavaScript
> 
>             /// use the width that is greater
>             if (imageItemViewbox.width > facotredSectionWidth){
> ```

I think there is a typo - should be `factored`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495#-:-L-BpCQlr9QsStiZCRKP:b-gm168)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 340 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495#-L-BnNnnpVbjbp0YywM5:-L-Brhq51GFS20V8ZUwh:bxpe1hz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53306dd767db60c11cf875acd9fc985f06bd37e5/src/app/ui/export/export-legend.service.js#L340)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think there is a typo - should be `factored`.
</blockquote></details>

I think you need to change `imageItemViewbox.height`accordingly; otherwise, width / height ratio will change compared to the original image.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495)*

**Comment by barryytm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 246 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495#-L-BoqVm0lu0SLughgA7:-L-CuRW1ZxPZq99J3IZu:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/502baf482b3bf20685c45656a570cdeb2f7ae9f6/src/app/ui/export/export-legend.service.js#L246)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`makeLegendElement`, 'makeGroup', 'makeItem' and other functions are scoped to the `makeLegend`, so they should already have access to `sectionWidth`, and since this value can't change while the legend is made, there is no real need in passing it through all these functions.
</blockquote></details>

done, thanks

---

*[src/app/ui/export/export-legend.service.js, line 340 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495#-L-BnNnnpVbjbp0YywM5:-L-CuTa_JvwF78VF6fIJ:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/502baf482b3bf20685c45656a570cdeb2f7ae9f6/src/app/ui/export/export-legend.service.js#L340)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think you need to change `imageItemViewbox.height`accordingly; otherwise, width / height ratio will change compared to the original image.
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495)*

**Comment by AleksueiR** [comment]
Perfect, works very nice, even in IE :+1: :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495#-:-L-DBbGL-d5zTDyBmN5y:b59lmcc)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2495)*

**Pull request merged**
