### PR TITLE
fix(ui): update basemaps on map reload

### LINKED ISSUE #1062: Update basemap selector on language switch
A call to basemapService.reload() should be made when the map is reloaded.

### PR DESCRIPTION
**Pull request by milesap**
Closes #1062

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1117)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117#-KQ6dMpdBvxDzGLKG_uQ:-KQ6dMpePqEGk9Ig4b6g:b-xk07vd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f364088601dc7cd2445fcbbc9104d3a59579e08/src/app/geo/geo.service.js#L99)):*
> ```JavaScript
>             // update basemaps with new config
>             if (typeof mapNode === 'undefined') {
>                 basemapService.reload();
> ```

This will execute every time `assembleMap` is called except the first one (the very first time `reload` is called from inside the basemap service itself), correct? 

If so, how about adding it to the second `then` below ...
```js
.then(ms => {
	// expose mapService on geoService
	angular.extend(service, ms);
 	
	basemapService.reload();

	return layerRegistry(state, config);
})
```

... and removing `$rootScope.$on(events.rvReady, reload);` from [basemap.service.js#L36](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/basemap/basemap.service.js#L36)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117)*

**Comment by milesap** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117#-KQ6dMpdBvxDzGLKG_uQ:-KQLarMnvVAEx4kG63yy:b-az813s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f364088601dc7cd2445fcbbc9104d3a59579e08/src/app/geo/geo.service.js#L99)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This will execute every time `assembleMap` is called except the first one (the very first time `reload` is called from inside the basemap service itself), correct? 
> 
> If so, how about adding it to the second `then` below ...
> ```js
> .then(ms => {
> 	// expose mapService on geoService
> 	angular.extend(service, ms);
>  	
> 	basemapService.reload();
> 
> 	return layerRegistry(state, config);
> })
> ```
> 
> ... and removing `$rootScope.$on(events.rvReady, reload);` from [basemap.service.js#L36](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/basemap/basemap.service.js#L36)?
> 
> 
</details>
Looks good, made the change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117)*

**Comment by AleksueiR** [comment]
Nice! :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117#-:-KQLejsITb0i9Hj1Wi-e:be8rotp)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117)*

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1117)*

**Pull request merged**
