### PR TITLE
feat(ui): write panel switching logic

### PR DESCRIPTION
**Pull request by AleksueiR**
Includes panel switching between settings, metadata and filters.

Some tests included.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/138)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 13 of 14 files at r1.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by spencerwahl** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by AleksueiR** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/metadata/metadata.html, line 19 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138#-K6FJLPphaHFtUdsktWT:-K6FJLPqlaTCRjubUXD1:-712597875) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5a2a78fe7c7aa8a9788c0e1fbe9e53a191f61b7f/src/app/ui/metadata/metadata.html#L19)):*
I love how it picked out `content` from a paragraph and matched it to `rv-subcontent` class name . :smile: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by james-rae** [comment]
Reviewed 1 of 14 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by AleksueiR** [comment]
@james-rae, Don't merge this one yet please, want to make some more enhancements.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138#-:-K6i20JPGbXWpV-Wl3Ot:-890153185)*

**Comment by AleksueiR** [comment]
Review status: 12 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.html, line 7 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138#-K6iQGw8mUTe0mvmIedu:-K6iQGw8mUTe0mvmIedv:-1634460927) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da71f7757393d65977280062c341921cde30f724/src/app/ui/toc/toc.html#L7)):*
Turned out css classes have a minimum length of 2: http://stackoverflow.com/a/449000

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by alyec** [comment]
Reviewed 1 of 3 files at r3.
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[.jscsrc, line 92 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138#-K6iTqdIJz62jIjPKC3_:-K6iTqdIJz62jIjPKC3a:-2091058796) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da71f7757393d65977280062c341921cde30f724/.jscsrc#L92)):*
I don't believe this is reflects our style guide :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by AleksueiR** [comment]
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[.jscsrc, line 92 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138#-K6iTqdIJz62jIjPKC3_:-K6iUAotM95wCXKupYKL:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da71f7757393d65977280062c341921cde30f724/.jscsrc#L92)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/138)*

**Pull request merged**
