### PR TITLE
2736 Enhance keyboard-based identify

### LINKED ISSUE #2736: Enhance keyboard-based identify
Mockups:
- https://invis.io/WZJ7OWFEF6U#/298577715_10a-Ds-06-L_03
- https://invis.io/8YJ7OXQV73C#/298577717_10a-Ds-06-L_04

Behaviour:
- blue highlight around the map is displayed around the map when it's keyboard focused
- arrow keys pan the map; holding Shift pans the map faster
- `+/-` keys zoom the map in/out
- pressing "Enter" triggers an identify call
- crossharis are centered relative to the rv-shell; if the inner shell is not center aligned, crosshairs can appear off-center
- a hover tooltip is displayed above or beneath the crosshairs when the crosshairs pass over a feature
- the tooltip is fixed relative to the map container;

Related issues:
- [bug] #2730 - breaks keyboard-based zoom when trying to pan during zoom animation

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
- add the crosshairs image to the map when using keyboard to navigate
- shows tooltips when the crosshairs moves over a feature, same as when using a mouse cursor
- show a keyboard navigation description at the bottom of the map

Closes #2736, #2665

## Testing
:eyes: 

## Documentation
Inline comments.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
If we use the keyboard to hover over a feature with a hovertip and then move the mouse, the hovertip will stay on screen following the mouse. Not sure if there is a good way around this



---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-:-LDbGw6R0B7fOrv3_CKI:b-1q15ce)*

**Comment by AleksueiR** [comment]
Yes, this does happen. I added a comment about that at the bottom of the `crosshairs.directive.js`. Here it is:

> // TODO: if the tooltip is opened by crosshairs and the user moves the mouse cursor over the map, the tooltip will move and stay with the mouse cursor until the extent changes or the user hovers over a different feature somehow detect such tooltip's desertion and hide it

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-:-LDbRhzB53r4dkaxa5kO:b-y5wbd4)*

**Comment by AleksueiR** [comment]
Not sure how this can be detected easily without modifying the tooltip service.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-:-LDbS77s3qlyPcrby0fQ:bxdwess)*

**Comment by JahidAhmed** [comment]
Ah yes, missed that. Is there anything we can do using the API map `mouseMove` observable to handle the hovertips?

If not, tested in Chrome and IE and demo works. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/layout/shell.directive.js, line 71 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-LDbUQNL-UrkF5x64Rno:-LDbUQNL-UrkF5x64Rnp:b-k10qpq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1d6263fd68844b4792556a2631159e17dd040ab8/src/app/layout/shell.directive.js#L71)):*
> ```JavaScript
>             const mdSidePanelOpen = $('md-sidenav').toArray().find(el => !$(el).hasClass('md-closed'));
>             const navigationKeys = [keyNames.TAB, keyNames.ENTER, keyNames.LEFT_ARROW, keyNames.UP_ARROW, keyNames.RIGHT_ARROW,keyNames.DOWN_ARROW,keyNames.EQUAL_SIGN,keyNames.DASH];
>             
> ```

extra spaces

---

*[src/locales/help/default/en-CA.md, line 253 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-LDbU6Qr-0ljJOFvGLA4:-LDbU6Qr-0ljJOFvGLA5:bi1irdd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1d6263fd68844b4792556a2631159e17dd040ab8/src/locales/help/default/en-CA.md#L253)):*
> ```Markdown
> Keyboard functionality is provided as an alternative for users who are unable to use a mouse. Use the Tab key to navigate forward to links and controls on the page. Press Shift+Tab to go back one step. Use the Enter or Spacebar keys to activate links and controls.
> 
> When the map gains focus, a crosshairs marker is displayed in the center of the map. Use the __arrow__ keys to move the map and __+__ / __-__ keys to zoom in and out. Press __Enter__ to select a feature under the crosshairs and displaye associated data in the Details panel.
> ```

small spelling change: "..and display associated.."

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-:-LDbT-j26eGckG81kf1Y:bl2jjqe)*

**Comment by AleksueiR** [comment]
Review status: 20 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/layout/shell.directive.js, line 71 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-LDbUQNL-UrkF5x64Rno:-LDbjM3O0qTGG4Te4NZD:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1d6263fd68844b4792556a2631159e17dd040ab8/src/app/layout/shell.directive.js#L71)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

Done.

---

*[src/locales/help/default/en-CA.md, line 253 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-LDbU6Qr-0ljJOFvGLA4:-LDbjKrM9T7p4LNyPY7w:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1d6263fd68844b4792556a2631159e17dd040ab8/src/locales/help/default/en-CA.md#L253)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

small spelling change: "..and display associated.."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737)*

**Comment by milesap** [comment]
:lgtm:

Focus manager approves these changes

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/app/focus-manager.js, line 396 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-LDbrB5z5a5riy7UHnsQ:-LDbrB5z5a5riy7UHnsR:bnv4ybr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2836c0e813938fd466caa7947586c23265b12dfc/src/app/focus-manager.js#L396)):*
> ```
> // check if the viewer was clicked
> ```

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-:-LDbrVxk1Mlvb73gT-X3:b-tjaa08)*

**Comment by AleksueiR** [comment]
Dismissed @milesap from a discussion.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/focus-manager.js, line 396 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737#-LDbrB5z5a5riy7UHnsQ:-LDbtPhq2tgeH_NXZkf_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2836c0e813938fd466caa7947586c23265b12dfc/src/app/focus-manager.js#L396)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

> ```
> // check if the viewer was clicked
> ```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2737)*

**Pull request merged**
