### PR TITLE
fix(ui): basemap updates on bookmark use

### LINKED ISSUE #913: Basemap selector doesn't update on reload
When a bookmark is used to reload the map the basemap selector does not update if the basemap changes.

Need to refactor to allow outside control of the basemap list the selector displays.

- create new basemap registry/list/thing service
- expose basemap list and updater functions (select basemap by id?)
- tie list into basemap directive

### PR DESCRIPTION
**Pull request by milesap**
Closes #913

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1056)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/basemap/basemap.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPEIbch3YzKVMslDCLf:-KPEIbci8Ux6Y1r4wmTs:b-1d54om) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.html#L7)):*
> ```HTML
>         <div class="rv-subheader">
>             <h3 class="md-title">{{projection.name}} {{'basemap.title' | translate}}</h3>
>             <div class="rv-icon-16" ng-show='self.selectedWkid != projection.wkid'>
> ```

Currently being shown for both projections at all times. It seems like we don't keep track of 'selectedWkid' anymore.

---

*[src/app/ui/basemap/basemap.service.js, line 17 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPEUoapXDzJRF_2PpMx:-KPEUoapXDzJRF_2PpMy:b-o07hpm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L17)):*
> ```JavaScript
>         .factory('basemapService', basemapService);
> 
>     function basemapService($rootScope, events, configService, $translate, geoService, $injector, $q) {
> ```

we'll probably want to expose something to re-populate the basemap list using a new config. Then we can replace the items when we reload with a new language.

---

*[src/app/ui/basemap/basemap.service.js, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPESTGoAbjmb0fXTrqC:-KPESTGoAbjmb0fXTrqD:b-smp568) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L53)):*
> ```JavaScript
>             } else {
>                 // avoiding circular dependency on bookmarkService
>                 $injector.get('reloadService').loadNewProjection(basemap.id);
> ```

Might be able to avoid this, will report back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/ui/basemap/basemap.service.js, line 6 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPN_P7NSSh4nSMqleGB:-KPN_P7NSSh4nSMqleGC:bywzfwh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L6)):*
> ```JavaScript
>     /**
>      * @module basemapService
>      * @memberof app.ui.basemap
> ```

We are going to flatten the ui namespace.  Can you changes this to `app.ui`?

---

*[src/app/ui/basemap/basemap.service.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPNkNsYHAI4FLoXYl4s:-KPNkNsZPgjD-s7a7Hot:bdccu2q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L106)):*
> ```JavaScript
>             bmSelected = bmSelected.selected ? bmSelected.selected : basemap;
>             projection.basemaps.unshift(basemap);
>             _addBaseMaps(basemapList); // recursive - keep going until no basemaps remain
> ```

Mostly curious: why recursive instead of straight iteration?

---

*[src/app/ui/basemap/basemap.service.js, line 118 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPN_ySCOcNC8HKGVFQi:-KPN_ySD55txXnukNQi7:b-qa2qk5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L118)):*
> ```JavaScript
>      */
>     function _wkidToProjectionName(wkid) {
>         return (wkid === 3978) ? 'Lambert' : (wkid === 102100) ? 'Mercator' : 'Other';
> ```

Can you set this up so it's easy to add more projections later on (maybe move this to constants)?  Also, are these displayed to the user?  If so they need translations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by milesap** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/ui/basemap/basemap.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPEIbch3YzKVMslDCLf:-KPSfCEGl1-iHaCJ1Wjn:bbe1blr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.html#L7)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> Currently being shown for both projections at all times. It seems like we don't keep track of 'selectedWkid' anymore.
</details>
Fixed so it displays correctly. Now we can just query the selected basemap for its wkid instead of having it stored separately.

---

*[src/app/ui/basemap/basemap.service.js, line 6 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPN_P7NSSh4nSMqleGB:-KPSflHBTjbE51YFohWg:bud9rrf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L6)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> We are going to flatten the ui namespace.  Can you changes this to `app.ui`?
</details>
Ok made the change

---

*[src/app/ui/basemap/basemap.service.js, line 17 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPEUoapXDzJRF_2PpMx:-KPSo2t0t22fboX5pcNL:bkq9u26) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L17)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> we'll probably want to expose something to re-populate the basemap list using a new config. Then we can replace the items when we reload with a new language.
</details>
I've exposed a function named `reload` which will re-populate projections based on the current config.

---

*[src/app/ui/basemap/basemap.service.js, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPESTGoAbjmb0fXTrqC:-KPSq4wHY2A-trZ6v5qD:bddphfw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L53)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> Might be able to avoid this, will report back
</details>
Any luck on this? Let me know if any change is still needed here.

---

*[src/app/ui/basemap/basemap.service.js, line 106 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPNkNsYHAI4FLoXYl4s:-KPSoRBoRuCnXWDuTfNE:b17slhw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L106)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Mostly curious: why recursive instead of straight iteration?
</details>
Not enough coffee :expressionless:  changed to iteration since it makes more sense here.

---

*[src/app/ui/basemap/basemap.service.js, line 118 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPN_ySCOcNC8HKGVFQi:-KPSplKgH62R4QC98JiG:bcj8mm7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L118)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you set this up so it's easy to add more projections later on (maybe move this to constants)?  Also, are these displayed to the user?  If so they need translations.
</details>
Made into a constant at the top of the page. The translations occur in `basemap.html`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/basemap/basemap.service.js, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPESTGoAbjmb0fXTrqC:-KPT4NXCOCDFTJudCQ4n:bpyyh9n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d4384148ce1b086f1f96e600db2671fd03eef441/src/app/ui/basemap/basemap.service.js#L53)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Any luck on this? Let me know if any change is still needed here.
</details>
No luck

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/basemap/basemap.service.js, line 3 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPTBAWOzbHoHjGCcRtb:-KPTBAWOzbHoHjGCcRtc:bu798yl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/df189a70a309000c210af1b6ef6ec25992e38535/src/app/ui/basemap/basemap.service.js#L3)):*
> ```JavaScript
> (() => {
>     'use strict';
>     const wkidNames = wkid => (wkid === 3978) ? 'Lambert' : (wkid === 102100) ? 'Mercator' : 'Other';
> ```

```js
const wkidMap = new Map();
wkidMap.set(3978, 'Lambert');
wkidMap.set(102100, 'Mercator');
const wkidNames = wkid => wkidMap.get(wkid) || 'Other';
```

With `Map` it becomes a lot easier to extend instead of stacking on further conditionals.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by milesap** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 3 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPTBAWOzbHoHjGCcRtb:-KPTc80OsFaJ5NX5KENW:bjwqmb9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/df189a70a309000c210af1b6ef6ec25992e38535/src/app/ui/basemap/basemap.service.js#L3)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> ```js
> const wkidMap = new Map();
> wkidMap.set(3978, 'Lambert');
> wkidMap.set(102100, 'Mercator');
> const wkidNames = wkid => wkidMap.get(wkid) || 'Other';
> ```
> 
> With `Map` it becomes a lot easier to extend instead of stacking on further conditionals.
</details>
Didn't know about this, made the change :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by milesap** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 3 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPTBAWOzbHoHjGCcRtb:-KPTqr92Evj52Nrz87W5:b-5wk89g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/df189a70a309000c210af1b6ef6ec25992e38535/src/app/ui/basemap/basemap.service.js#L3)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Didn't know about this, made the change :+1: 
</details>
Could not get the Map polyfill to work - jshint would check the file despite it being told not to. To keep my sanity I'll omit the use of `Map` for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by alyec** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 3 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPTBAWOzbHoHjGCcRtb:-KPU0M4YEnlN10sUYirW:bjec1ez) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/df189a70a309000c210af1b6ef6ec25992e38535/src/app/ui/basemap/basemap.service.js#L3)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Could not get the Map polyfill to work - jshint would check the file despite it being told not to. To keep my sanity I'll omit the use of `Map` for now.
</details>
Can you find some other way to keep the mappings better organized than conditionals?  Maybe use a standard JS object and make the WKIDs strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by milesap** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 3 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056#-KPTBAWOzbHoHjGCcRtb:-KPXZZNmGvPa-yQEY_23:bo0eic2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/df189a70a309000c210af1b6ef6ec25992e38535/src/app/ui/basemap/basemap.service.js#L3)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you find some other way to keep the mappings better organized than conditionals?  Maybe use a standard JS object and make the WKIDs strings.
</details>
Ok made the change using a standard object

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by cynngah** [comment]
Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1056)*

**Pull request merged**
