### PR TITLE
chore(build): automated weekly build script

### PR DESCRIPTION
**Pull request by milesap**
## Description
Automates the weekly build for all release branches. Written in python using the [PyGithub library](https://github.com/PyGithub/PyGithub/) .

## Testing
Manual testing completed - do not run until release branch 1.5 has correct version in package.json

## Documentation
Python documentation

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1393)

### CODE REVIEW

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/weekly_build/run.py, line 122 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KWrUV18DFJros5yQaMg:-KWrUV18DFJros5yQaMh:b-vnruf9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d422ac5e1d1597fc5122d2a17d62484f1d7c093e/scripts/weekly_build/run.py#L122)):*
> ```Python
>             title = 'Weekly RAMP2 Build - FGP Viewer v' + self.next_version
>             body = """### Weekly Build Release %s
> - [Production Builds](http://fgpv.cloudapp.net/demo/users/milesap/build/weekly-1.4.0-7/prod/samples/)
> ```

TODO: Update links and/or add more content 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[scripts/weekly_build/run.py, line 25 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBp8LBXJMRXi0LrM1Z:-KXBp8LBXJMRXi0LrM1_:b-c3wh3d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L25)):*
> ```Python
>             A list of string branch names
>         """
>         pattern = re.compile("^upstream/(develop|v)+")
> ```

why is the `+` needed?

---

*[scripts/weekly_build/run.py, line 27 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBpOUEKzNukcAC95NH:-KXBpOUEKzNukcAC95NI:b-q7pus2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L27)):*
> ```Python
>         pattern = re.compile("^upstream/(develop|v)+")
>         list_remote_branches = subprocess.run(['git', 'branch', '-r'], shell=True, stdout=subprocess.PIPE, universal_newlines=True)
>         only_upstream_branches = list(map(str.strip, list_remote_branches.stdout.splitlines()))
> ```

why not use a list comprehension here as well `[strip(line) for line in list_remote_branches.stdout.splitlines()]` should work (I think)

---

*[scripts/weekly_build/run.py, line 63 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBpyKROOA5knYzx5rw:-KXBpyKROOA5knYzx5rx:bedqe1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L63)):*
> ```Python
>         version = self.readJsonFile('package.json')['version'].split('-')
>         build_num = 1
>         if len(version) > 1:
> ```

is there somewhere else in the code that handles the case where the last build was a full version?

---

*[scripts/weekly_build/run.py, line 84 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBqLEBeaJFwnV9kHvD:-KXBqLEBeaJFwnV9kHvE:b-p46axw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L84)):*
> ```Python
>         self.writeJsonFile(filename, json)
> 
>     def mergePull(self, pull):
> ```

can you add a max_tries or something like that?

---

*[scripts/weekly_build/run.py, line 127 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBnj-JnVxXYLXp6vCP:-KXBnj-JnVxXYLXp6vCQ:b-e2ezbk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L127)):*
> ```Python
> 
> if __name__ == '__main__':
>     build = WeeklyBuilder('github token')
> ```

Can you set this to pull from an environment variable or sys.argv?  Order should be command line first then environment variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393)*

**Comment by milesap** [comment]
Having issues with `GitPython` as discussed, unable to clone repo into a temp directory (even with admin priv.). 

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[scripts/weekly_build/run.py, line 25 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBp8LBXJMRXi0LrM1Z:-KXBuNlkQwO2-BrAE9lf:b-kub8pb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L25)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> why is the `+` needed?
</details>
Removed, not needed

---

*[scripts/weekly_build/run.py, line 27 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBpOUEKzNukcAC95NH:-KXBufjMsYxymp6lRIyS:b-u06tab) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L27)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> why not use a list comprehension here as well `[strip(line) for line in list_remote_branches.stdout.splitlines()]` should work (I think)
</details>
Changed to your suggestion

---

*[scripts/weekly_build/run.py, line 63 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBpyKROOA5knYzx5rw:-KXBuoYljOSlVxZv2QQj:b-rugtdd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L63)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> is there somewhere else in the code that handles the case where the last build was a full version?
</details>
`build_num = 1` handles full versions since `v1.4.0` would become `v1.4.0-1`. Should this be `v1.5.0-1` as you suggested? The only issue I would have here is that there should be a `v.1.5.0` release branch, so in this case maybe don't make a weekly build?

---

*[scripts/weekly_build/run.py, line 84 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBqLEBeaJFwnV9kHvD:-KXBw87eEKwdeDmNRlSU:bjk2oz4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L84)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> can you add a max_tries or something like that?
</details>
Ok added `self.maxMergeTries` (tries up to three times)

---

*[scripts/weekly_build/run.py, line 127 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBnj-JnVxXYLXp6vCP:-KXC7Pc-mrufZDj4ZQss:b12els0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L127)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you set this to pull from an environment variable or sys.argv?  Order should be command line first then environment variable.
</details>
Github token can be provided via the first command line argument, or as an environment variable `GITHUB_TOKEN`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-:-KXC7dljzwHub0Qg2bk3:bwj0vwz)*

**Comment by milesap** [comment]
It seems that for the following code, the "access is denied" error is from the tempfile cleanup:

```
with tempfile.TemporaryDirectory() as tmpdirname:
    self.repo = Repo.clone_from(self.repoAPI.clone_url, os.path.join(tmpdirname, 'reponame'))
    print('test') # this prints 'test' as expected then fails
```

I'll continue to investigate tomorrow - if you have any insights in the meantime just let me know

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-:-KXCYQ622XD_NsKuDMzV:bb6f6c3)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scripts/weekly_build/run.py, line 63 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBpyKROOA5knYzx5rw:-KXCdd8iX2G8_RK9vztu:b-bp29r3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L63)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> `build_num = 1` handles full versions since `v1.4.0` would become `v1.4.0-1`. Should this be `v1.5.0-1` as you suggested? The only issue I would have here is that there should be a `v.1.5.0` release branch, so in this case maybe don't make a weekly build?
</details>
`1.4.0-1` comes before `1.4.0` so it shouldn't be tagged after.  I'm fine with stopping the autobuild with a warning so some human can come along and either update to `1.5.0-0` or merge `v1.5` branch on top of `develop`.

---

*[scripts/weekly_build/run.py, line 84 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBqLEBeaJFwnV9kHvD:-KXCeHy1TYCQsPGnulj3:bs051h6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L84)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Ok added `self.maxMergeTries` (tries up to three times)
</details>
I think this should be added to the function args instead `mergeTries = 3`, and pass `mergeTries-1` to each subsequent call.  Less state hopefully leads to fewer bugs.

---

*[scripts/weekly_build/run.py, line 125 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXCeXsWnJcygKI5aaAw:-KXCeXsWnJcygKI5aaAx:b-y8so5t) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a4b413acb24ae15c859b7b1aa5e3f5785d495562/scripts/weekly_build/run.py#L125)):*
> ```Python
>             body = """### Weekly Build Release {0}
> - [Production Builds](http://fgpv.cloudapp.net/demo/users/{1}/build/{2}/prod/samples/)
> - [Developer Builds](http://fgpv.cloudapp.net/demo/users/{1}/build/{2}/dev/samples/)""".format(self.next_version, self.user.login, 'weekly-' + self.next_version)
> ```

Look who's adopting the new string formatting :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393)*

**Comment by milesap** [comment]
@alyec take a look at the code and see if you can run it without error. Changed to `GitPython` instead of `subprocess`.  

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scripts/weekly_build/run.py, line 63 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBpyKROOA5knYzx5rw:-KXGKBGmDoh695u70bss:b7gr332) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L63)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `1.4.0-1` comes before `1.4.0` so it shouldn't be tagged after.  I'm fine with stopping the autobuild with a warning so some human can come along and either update to `1.5.0-0` or merge `v1.5` branch on top of `develop`.
</details>
Ok, added a check so that a weekly build is avoided for final releases

---

*[scripts/weekly_build/run.py, line 84 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXBqLEBeaJFwnV9kHvD:-KXGKKtMz_OHBMkAj03e:b-1ctm1u) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28bd1aed4ec960f51363a68f492d68ffea891d16/scripts/weekly_build/run.py#L84)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think this should be added to the function args instead `mergeTries = 3`, and pass `mergeTries-1` to each subsequent call.  Less state hopefully leads to fewer bugs.
</details>
Much better

---

*[scripts/weekly_build/run.py, line 125 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-KXCeXsWnJcygKI5aaAw:-KXGKPc42gWI0pi6w3wB:bjwa7hh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a4b413acb24ae15c859b7b1aa5e3f5785d495562/scripts/weekly_build/run.py#L125)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Look who's adopting the new string formatting :+1: 
</details>
:tada: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1393#-:-KXGKTw8OKARgQlIf9pE:bnp5u0)*

**Comment by milesap** [comment]
Currently with @alyec for testing and change suggestions

**Comment by milesap** [comment]
Will reopen if one is finalized - for now manual dailies are made.

**Pull request closed without merging**
