### PR TITLE
External language switch

### PR DESCRIPTION
**Pull request by spencerwahl**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/433)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433)*

**Comment by cynngah** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/core/api.service.js, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433#-KE6F4aL80ZMHYj5GDfq:-KE6F4aM4OirfHvJWxqp:1858290956) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19bdb4f644c6354964ef5d0d49219bb5d94d5619/src/app/core/api.service.js#L29)):*
Function level comments?

---

*[src/app/core/api.service.js, line 35 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433#-KE6FBhpUfv8QMxkeemF:-KE6FBhpUfv8QMxkeemG:-2026703398) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19bdb4f644c6354964ef5d0d49219bb5d94d5619/src/app/core/api.service.js#L35)):*
Can omit brackets around `resolve`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433)*

**Comment by spencerwahl** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/api.service.js, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433#-KE6F4aL80ZMHYj5GDfq:-KE7uPI4FH_REy_4qTrQ:1496800417) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19bdb4f644c6354964ef5d0d49219bb5d94d5619/src/app/core/api.service.js#L29)):*
Done (in core.run)

---

*[src/app/core/api.service.js, line 35 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433#-KE6FBhpUfv8QMxkeemF:-KE7uRj_-5hde1n4MfJ-:1872549340) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/19bdb4f644c6354964ef5d0d49219bb5d94d5619/src/app/core/api.service.js#L35)):*
Done (also in core.run)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/433)*

**Pull request merged**
