### PR TITLE
fix(ui): automatic URL selection in share dialog input field

### LINKED ISSUE #1284: Share Link not working in IE11 for both Short Link and Long Link
Tested build URL: http://fgpv.cloudapp.net/demo/release-v1.4.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

In IE11, although the dialog is shown up and "Click to copy" will display "Link copied to clipboard", but actually the URL is not copied. When pasting to a new tab in IE11, it is not the Link generated by Share Link in IE11, instead it just picks up whatever the previous copied item on clipboard.

image

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
Share Link not working in IE11 for both Short Link and Long Link #1284

## Testing
Test with IE11, Fox and Chrome

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [ ] PR targets the correct release version

Closes #1284

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1653)

### CODE REVIEW

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1653#-:-Kbpr06ZGjoOna1ImJio:bnfp4nl)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/sidenav/sidenav.service.js, line 106 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1653#-Kbq-pwZkTMCpfvjKbgh:-Kbq-pwZkTMCpfvjKbgi:b-nkw7ep) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2d0b695f78aa22e7e543a241d0dae9a06c4e99e8/src/app/ui/sidenav/sidenav.service.js#L106)):*
> ```JavaScript
>                         onShowing: (scope, element) => (scope.element = element.find('.side-nav-summary'))
>                     }).then(function () {
>                         $rootElement.find('.rv-shareLink').select();
> ```

Can use arrow function here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1653#-:-Kbq-zQMPum6asSQW-Is:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
Absolutely... I'll do

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1653#-:-Kbq2FyABcr1Bch5bmJr:b-4531ce)*

**Comment by AleksueiR** [comment]
Thanks. Is it okay to close https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1607#- ?

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1653#-:-Kbq4RgQ655pe4mXuVLl:bpofsrp)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1653)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1653)*

**Pull request merged**
