### PR TITLE
North arrow top offset and flag to geometry api

### LINKED ISSUE #2678: Add top offset to north pole icon and make flag use new api geometry point
1. Ability to specify a top offset in screen pixels for the north arrow compass. This offset will need to be included in the compass trigonometry math.

untitled

2. The north pole icon should now use the api geometry point object.

### PR DESCRIPTION
**Pull request by Dane-Thomas**
## Description

Closes #2678 

Change flag to use geometry api.
Add ability to specify top offset for the north arrow. 

## Testing

Tested manually.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/ui/common/north-arrow.directive.js, line 40 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCV1Kjg7aRveXXkxGg5:-LCV1Kjg7aRveXXkxGg6:b7n3x90) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3a1c92817a021e6cd9c4a08539a702174fee0c3/src/app/ui/common/north-arrow.directive.js#L40)):*
> ```JavaScript
>                         mapI.addLayer(mapI.northPoleLayer);
>                         mapI.northPoleLayer.addGeometry(northPole); 
>                     });              
> ```

evil spaces

---

*[src/app/ui/common/north-arrow.directive.js, line 85 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCV1juw60eV5b3UsO5X:-LCV1juw60eV5b3UsO5Y:b7n3x90) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3a1c92817a021e6cd9c4a08539a702174fee0c3/src/app/ui/common/north-arrow.directive.js#L85)):*
> ```JavaScript
>                             .css('transform-origin', 'top center')
>                             .css('transform', `rotate(${north.rotationAngle}deg)`);
>                     }                   
> ```

evil spaces

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 30 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYPAal0GAKSfpxcQow:-LCYPAal0GAKSfpxcQox:b-9iwbat) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3a1c92817a021e6cd9c4a08539a702174fee0c3/src/app/ui/common/north-arrow.directive.js#L30)):*
> ```JavaScript
>                 events.$on(events.rvApiMapAdded, (_, mApi) => {
>                     // create new layer for north pole
>                     mApi.layers.addLayer('northPoleLayer').then(layer => {
> ```

Any specific reason you're creating a `simpleLayer` for the north pole geometry point? Is this better than just using `mApi.simpleLayer`?

---

*[src/app/ui/common/north-arrow.directive.js, line 39 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYPzbQAFsaplYDZ2t6:-LCYPzbQAFsaplYDZ2t7:b-rxx6rr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3a1c92817a021e6cd9c4a08539a702174fee0c3/src/app/ui/common/north-arrow.directive.js#L39)):*
> ```JavaScript
>                         mapI.northPoleLayer = layer[0]; 
>                         mapI.addLayer(mapI.northPoleLayer);
>                         mapI.northPoleLayer.addGeometry(northPole); 
> ```

Would the following work?

```js
events.$on(events.rvApiMapAdded, (_, mApi) => {
  const poleSource = mapConfig.northArrow.poleIcon || 'M14.4 6L14 4H5v17h2v-7h5.6l.4 2h7V6z';
  const northPole = new Point('northPole', poleSource, new XY(-96, 90));
  mApi.simpleLayer.addGeometry(northPole);
});
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by AleksueiR** [comment]
Travis still doesn't build you PRs :/
It doesn't even see commits to the repo: https://travis-ci.org/Dane-Thomas/fgpv-vpgf/builds

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCY_deLDF1QwFZcxOo_:bcfz7c2)*

**Comment by AleksueiR** [comment]
Demo works :+1: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 27 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYfZtl-zOzumfE417y:-LCYfZtl-zOzumfE417z:byy9fy4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e5da13f29f68291551bbe8baff71dc970583724d/src/app/ui/common/north-arrow.directive.js#L27)):*
> ```JavaScript
>             if (mapConfig.northArrow && mapConfig.northArrow.enabled) {
>                 // required so that arrow moves behind overview map instead of in front 
>                 $rootElement.find('.rv-esri-map > .rv-inner-shell').first().after(element);
> ```

Do we still need this line? The arrow is inside the `rv-inner-shell` already.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCYfuKo4Ce9aUazMwwx:b-gm168)*

**Comment by barryytm** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 37 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYuoVTCnRlK4-6dtAA:-LCYuoVTCnRlK4-6dtAB:b4ogtcj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28203dbb955b41226a9836f9e0cac55405f74f26/src/app/ui/common/north-arrow.directive.js#L37)):*
> ```JavaScript
>             function updateNorthArrow() {
>                 const arrowSource = mapConfig.northArrow.arrowIcon || 'northarrow';
>                 const poleSource = mapConfig.northArrow.poleIcon || 'flag';
> ```

The north pole icon needs to be configurable and it doesn't seem to be able to do that.  You probably need this line back.  Please take a look at sample 55 in index.samples.  Let me know if you have any questions.

---

*[src/app/ui/common/north-arrow.directive.js, line 79 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYsddf9beo8yizUyAH:-LCYsddf9beo8yizUyAI:b72z04j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5993b7371d7ca1ddfe0abf7bf9a1bf80a22be6a5/src/app/ui/common/north-arrow.directive.js#L79)):*
> ```JavaScript
>                             .css('left', north.screenX)
>                             .css('top', 1)
>                             .css('transform-origin', 'top center')
> ```

Can you make the flag pole pointing toward the north pole?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by Dane-Thomas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/ui/common/north-arrow.directive.js, line 39 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYPzbQAFsaplYDZ2t6:-LCZGOOh3utn9dS54SwQ:bu8ox7e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3a1c92817a021e6cd9c4a08539a702174fee0c3/src/app/ui/common/north-arrow.directive.js#L39)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Would the following work?

```js
events.$on(events.rvApiMapAdded, (_, mApi) => {
  const poleSource = mapConfig.northArrow.poleIcon || 'M14.4 6L14 4H5v17h2v-7h5.6l.4 2h7V6z';
  const northPole = new Point('northPole', poleSource, new XY(-96, 90));
  mApi.simpleLayer.addGeometry(northPole);
});
```
</blockquote></details>

Changed thanks

---

*[src/app/ui/common/north-arrow.directive.js, line 35 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYjVxI20NAD6XNIR0L:-LCZGMId5C9JbVhSzk8y:bu8ox7e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5993b7371d7ca1ddfe0abf7bf9a1bf80a22be6a5/src/app/ui/common/north-arrow.directive.js#L35)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

> ```
>                         mapI.northPoleLayer = layer[0];
>                         mapI.addLayer(mapI.northPoleLayer);
>                         mapI.northPoleLayer.addGeometry(northPole);
> ```

Does layer[0].addGeometry(northPole); work?
</blockquote></details>

Changed thanks

---

*[src/app/ui/common/north-arrow.directive.js, line 37 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYuoVTCnRlK4-6dtAA:-LCZGRuW25DF0FbBIiJC:b-udxwti) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/28203dbb955b41226a9836f9e0cac55405f74f26/src/app/ui/common/north-arrow.directive.js#L37)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

The north pole icon needs to be configurable and it doesn't seem to be able to do that.  You probably need this line back.  Please take a look at sample 55 in index.samples.  Let me know if you have any questions.
</blockquote></details>

Fixed thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by milesap** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/ui/common/north-arrow.directive.js, line 24 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZII_p5N6xIkurFqrn:-LCZII_p5N6xIkurFqro:bn1jutp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L24)):*
> ```JavaScript
>         $rootScope.$on(events.rvApiReady, () => {
>             const mapConfig = configService.getSync.map.components;
>             const mapI = configService.getSync.map.instance;
> ```

still needed?

---

*[src/app/ui/common/north-arrow.directive.js, line 28 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIG-yDcIw9EKfhyX6:-LCZIG-yDcIw9EKfhyX7:b-l6mwxj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L28)):*
> ```JavaScript
>                 let deregisterMapAddedListener = events.$on(events.rvApiMapAdded, (_, mApi) => {
>                     deregisterMapAddedListener();
>                     console.log(mApi.layers.allLayers);
> ```

remove

---

*[src/app/ui/common/north-arrow.directive.js, line 35 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIPDL5n7Msrhi3K9j:-LCZIPDL5n7Msrhi3K9k:b-6j8bj7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L35)):*
> ```
> splice(0, 1);
> ```
Why is the layer removed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by james-rae** [comment]
North arrow positioning logic seems a bit off.  It's hiding behind the search bar and not certain it's pointing north. 
( http://fgpv.cloudapp.net/demo/users/Dane-Thomas/flag-offset/dev/samples/index-fgp-en.html )


---







*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCZJcTq59kmETeWCfjZ:b59p5sx)*

**Comment by Dane-Thomas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 24 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZII_p5N6xIkurFqrn:-LCZMGut2hc5J97KJQEQ:bp5ywni) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L24)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

still needed?
</blockquote></details>

removed thanks

---

*[src/app/ui/common/north-arrow.directive.js, line 28 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIG-yDcIw9EKfhyX6:-LCZMJBQ-l0R0-DZxMSH:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L28)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

remove
</blockquote></details>

done thanks

---

*[src/app/ui/common/north-arrow.directive.js, line 35 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIPDL5n7Msrhi3K9j:-LCZJkah6Jwte-fBRduI:bcpvcgs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L35)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

> ```
> splice(0, 1);
> ```
Why is the layer removed?
</blockquote></details>

Layer removed to prevent host from accessing it 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by JahidAhmed** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 35 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIPDL5n7Msrhi3K9j:-LCZOTsx1_FUBQqAbpf-:bpdmtzt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L35)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I would keep the layer, if a rogue plugin wants to change the flag to a snowman it'll find a way regardless. 
</blockquote></details>

I was thinking that this should follow the same structure as the default `simpleLayer` and `highlightLayer` for example. So the layers will be included on the map instance, but they won't be part of the API layers list; that would be reserved for `ConfigLayers` and manually added `SimpleLayers`.

So in this case, if someone really wanted to change our north pole icon after, they would do it through the variable locating on the map instance as opposed to in the layers list

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by Dane-Thomas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 79 at r4](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCYsddf9beo8yizUyAH:-LCZT6aP4suScYLG3Nfq:b-q75uju) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5993b7371d7ca1ddfe0abf7bf9a1bf80a22be6a5/src/app/ui/common/north-arrow.directive.js#L79)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Can you make the flag pole pointing toward the north pole?
</blockquote></details>

No options for styling the point icons

---

*[src/app/ui/common/north-arrow.directive.js, line 30 at r6](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZNeMq-KiOSNirJkPP:-LCZSV3RDGd7pKau6UR0:b-a6ixmz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fab6546f26af5127ecfbfbf5ad25d86c0c2227c/src/app/ui/common/north-arrow.directive.js#L30)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Is there a reason why it's not using svg cache as default?
</blockquote></details>

I believe svg cache isn't supported by the point api

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by Dane-Thomas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 30 at r6](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZNeMq-KiOSNirJkPP:-LCZa8dKAqVRC_y47t41:b9wu27l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5fab6546f26af5127ecfbfbf5ad25d86c0c2227c/src/app/ui/common/north-arrow.directive.js#L30)):*
<details><summary><i>Previously, Dane-Thomas (Dane Thomas) wrote…</i></summary><blockquote>

I believe svg cache isn't supported by the point api
</blockquote></details>

Confirmed. Not directly supported and will most likely more work than worthwhile.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by Dane-Thomas** [comment]
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 35 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIPDL5n7Msrhi3K9j:-LCZOTH4Al0t9ACF-FUn:b-e8mex6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L35)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I'm ok with discussing the idea of hiding/reserving layers so other people don't modify/see them by accident (for example). We need to plan this out a bit more first - as is, this operation is not detectable and doesn't trigger the proper events. It's also easily confused with the idea that doing this removes the layer from the map altogether. For now keep the layer on the map and if you have time write up an API proposal for this feature. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

or 

subclass the Array class and remove splice, pop, push, ... etc. 

or

find and ES6 way of defining a custom get/set iterator 
</blockquote></details>

alright done

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by JahidAhmed** [comment]
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/common/north-arrow.directive.js, line 35 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIPDL5n7Msrhi3K9j:-LCZgyjv8omCUXr8XeHU:b-wxbqzu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L35)):*
<details><summary><i>Previously, Dane-Thomas (Dane Thomas) wrote…</i></summary><blockquote>

alright done
</blockquote></details>

Alternatively, we could also create the `SimpleLayer` manually by first creating a `LayerRecord` using the appropriate `geoApi` function manually, similar to how the `SimpleLayer` is done: 
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/layer-registry.service.js#L55

This would ensure we don't add / remove it from any layers list and it also won't be async.

This can be done in a future PR though if we want to handle it this way

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by milesap** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/north-arrow.directive.js, line 35 at r5](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-LCZIPDL5n7Msrhi3K9j:-LCd9epO6cTH1LPlOD9u:bgjrtrv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/380de5d2e2d622d2b7f30c58a7ee3c0517e50dc7/src/app/ui/common/north-arrow.directive.js#L35)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Alternatively, we could also create the `SimpleLayer` manually by first creating a `LayerRecord` using the appropriate `geoApi` function manually, similar to how the `SimpleLayer` is done: 
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/layer-registry.service.js#L55

This would ensure we don't add / remove it from any layers list and it also won't be async.

This can be done in a future PR though if we want to handle it this way
</blockquote></details>

Sounds good, bring this up in the next api meeting or open a quick issue to track this - I'll likely forget

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by AleksueiR** [comment]
Demo works :+1: 

The arrow is correctly positioned now; however, I noticed that it can move too far to the right/left in some cases (the blue box is `inner-shell`):



Ideally, the arrow should stop at the border. If this is seems non-trivial to implement, it can be done in a separate PR.

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCdDvS7DlRuUFIuRI9z:b-594m1t)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by barryytm** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by Dane-Thomas** [comment]
Alright should stop at the border now

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCdRoLF091mG69zn3K2:b7myfvd)*

**Comment by milesap** [comment]
The north arrow still seems to pass over the mini map but under the legend bar. It's position or rotation seems off:



---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCda_Kd3prLhiDJtynn:b8s6ze7)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)*

**Comment by milesap** [comment]
On `index-samples.html` the rotation appears to be off (it's position looks correct). Or do my :eyes: deceive me?

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCoJIDH5oqsaGcR9qpg:b-6uqlke)*

**Comment by james-rae** [comment]
Miles, agree, but the old logic also did that.  Likely a problem in the original algorithm to calculate the angle.  Would suggest opening a new issue to investigate the trigonometry.

---







*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCoXWJrEDmnQX8W-Oag:bptuuxr)*

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 3 of 4 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714#-:-LCoczhe0-gOy67-FLHr:bg7igkv)*

**Pull request merged**
