### PR TITLE
Scales

### PR DESCRIPTION
**Pull request by cynngah**
#154 ; #401

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/690)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/690)*

**Comment by AleksueiR** [comment]
The [demo page](http://fgpv.cloudapp.net/demo/users/cynngah/scales/index-one.html) never asks me for geo permissions, it just zooms to Montreal. Does this work properly for everyone?

<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> #### Scales
> 
> #154 ; #401
> 
> 
> 
</details>


---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/690#-:-KJ6QX-sLfCBxpnF8wrW:794204668)*

**Comment by james-rae** [comment]
It asked me (Chrome).  Maybe you have a blocker?

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> The [demo page](http://fgpv.cloudapp.net/demo/users/cynngah/scales/index-one.html) never asks me for geo permissions, it just zooms to Montreal. Does this work properly for everyone?
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/690#-:-KJ6Qyx6D4clLEZeVevp:-1585973332)*

**Comment by alyec** [comment]
Chrome did not ask, but Firefox did

<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> It asked me (Chrome).  Maybe you have a blocker?
</details>


---

Reviewed 2 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/690#-:-KJ6RCko812yylHqUcv1:1013556859)*

**Comment by AleksueiR** [comment]
Ah, yes, this is it. Thanks. :lgtm: 

<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Chrome did not ask, but Firefox did
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/690#-:-KJ6RKuCPbSEOk8TiuaB:1643099757)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/690)*

**Comment by alyec** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/690)*

**Pull request merged**
