### PR TITLE
Toc update

### PR DESCRIPTION
**Pull request by AleksueiR**
- a bit of refactor on toc (threw out a lot of duplicate code); 
- any toc entry can be removed now, even sub-layers/groups of a dynamic layer (except for root groups for now) #410 
- metadata for dynamic sublayers is displayed properly
- options missing from toc entries (metadata, settings, etc.) are no longer created
- updated tests

Relates to #434

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/476)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 4 of 42 files at r1.
Review status: 4 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476)*

**Comment by ec-dev** [comment]
Reviewed 8 of 42 files at r1.
Review status: 9 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476)*

**Comment by spencerwahl** [comment]
Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/entry.directive.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476#-KEqcRUq8c6mCvkeb8K1:-KEqcRUq8c6mCvkeb8K2:-1528646148) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b92329af8a7d978761d3561e93006d28c4c45651/src/app/ui/toc/entry.directive.js#L8)):*
@restrict E

---

*[src/app/ui/toc/entry.directive.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476#-KEqcOZwtw-t7ENJIoxC:-KEqcOZx4m3A7KaIxumW:-1031499326) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b92329af8a7d978761d3561e93006d28c4c45651/src/app/ui/toc/entry.directive.js#L11)):*
compoenent -> component, gropu -> group

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/entry.directive.js, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476#-KEqcRUq8c6mCvkeb8K1:-KEqhNuWWT0YPYt_7gYs:631509455) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b92329af8a7d978761d3561e93006d28c4c45651/src/app/ui/toc/entry.directive.js#L8)):*
:+1:  Will be fixed in the next PR.

---

*[src/app/ui/toc/entry.directive.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476#-KEqcOZwtw-t7ENJIoxC:-KEqhSfua50Cx8FoUw4U:631509455) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b92329af8a7d978761d3561e93006d28c4c45651/src/app/ui/toc/entry.directive.js#L11)):*
:+1:  Will be fixed in the next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476)*

**Comment by ec-dev** [comment]
Reviewed 30 of 42 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/476)*

**Pull request merged**
