### PR TITLE
feat(config): add support for fullpage viewers

### LINKED ISSUE #834: Full page app support
Put a flag in the config that lets the viewer know its in control of the page. Control meaning either:
- the viewer is the only content on the page (as in `index-one.html`)
- or it is in full-screen mode within the host page

Update `focus.service.js` so that it uses this config value, currently we have a `rv-fullpage-app` attribute in `index-one.html` as a temporary solution.

Should turn on things like the share button.

### PR DESCRIPTION
**Pull request by milesap**
## Description
removes the rv-fullpage-app attribute on rootElement

Closes #834

## Testing
Yes

## Documentation
some inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1768)

### CODE REVIEW

**Comment by jolevesq** [comment]
:lgtm:

Full screen button on top of zoom in/zoom out is not there. Is it something only 1.6?

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768#-:-KfHyJ_PiOzJyY-YWYUi:b2b1t07)*

**Comment by milesap** [comment]
It should show - will investigate and update PR

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768#-:-KfHznXCl49L4i6qlsjj:b3yjqai)*

**Comment by milesap** [comment]
Corrected

---

Review status: 12 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768#-:-KfI3yfsobiaRoHDeMyy:b-1dcph8)*

**Comment by alyec** [comment]
Suggested change for consistency: `isFullscreen` -> `fullscreen` (for the config sections only I think it's fine as `isFullscreen in the code)

---

Reviewed 12 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768#-:-KfIBWzTt1sPgctJCHrq:b-gm0ckx)*

**Comment by milesap** [comment]
np, changed config property to `fullscreen` 

---

Review status: 6 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768#-:-KfIDP5UIj6bnIeaCpRg:b9yudii)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768)*

**Comment by alyec** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768#-:-KfIGa2l8Clgr0Eo85en:bnfp4nl)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 8 of 8 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768#-:-KfIRAXo085-PunFF-mf:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 12 files at r1, 2 of 2 files at r2, 8 of 8 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1768)*

**Pull request merged**
