### PR TITLE
chore(build): remove hardcoded dependencies from sample html files

### PR DESCRIPTION
**Pull request by AleksueiR**
also fixes iso 8601 bug

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/248)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[gulpfile.js, line 347 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93cmLL11eLOCVDqqLw:-K93cmLL11eLOCVDqqLx:2142593597) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/gulpfile.js#L347)):*
is there a reason we're keeping dead code?

---

*[src/app/injector.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93eeKQYL0aDL5Jg87G:-K93eeKQYL0aDL5Jg87H:-1260701377) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L1)):*
top level comments?

---

*[src/app/injector.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93erj-Rc-MRyL542Vg:-K93erj-Rc-MRyL542Vh:-1192526762) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L4)):*
are you sure this is guaranteed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by AleksueiR** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[gulpfile.js, line 347 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93cmLL11eLOCVDqqLw:-K9CTdmprzRHmD2V1RKw:-867268508) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/gulpfile.js#L347)):*
Nope, I just forgot to delete it.

---

*[src/app/injector.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93eeKQYL0aDL5Jg87G:-K9CabABSWkeSTBmiNjf:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L1)):*
Done.

---

*[src/app/injector.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93erj-Rc-MRyL542Vg:-K9CUMXf0BLTyqFVLlz8:87473662) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L4)):*
The rendering of the page is blocked while a script is downloaded and executed (if no `async` or `defer` attributes are specified), so the last script tag on the page belongs to the script currently being executed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/injector.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93erj-Rc-MRyL542Vg:-K9D6SMnX5G1H1aZykNb:1436107478) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L4)):*
don't people use `async` pretty heavily these days?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/injector.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93erj-Rc-MRyL542Vg:-K9DXPxe-xX5c_nf7pxS:-101438310) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L4)):*
Setting `asyn` in script tags in html doesn't not block the page, but it also doesn't preserve the order in which scripts are executed.
Do you think people might want to add `asyn` to our script?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by AleksueiR** [comment]
Added a wet sample page. It's working right now even though there are two version of jquery loaded on the page.

---

Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-:-K9DYo4jgc26sbPV8Lwo:-583245727)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/injector.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93erj-Rc-MRyL542Vg:-K9DlW7j0U5J4DE2o0A4:-897368332) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L4)):*
yes, at least I think we should expect to have to deal with that possiblity

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/injector.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248#-K93erj-Rc-MRyL542Vg:-K9DnsYsp_VWwudx808z:-1466441477) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d74f7cbef0ce39bbefaa1a41f0b07cb93ba9250/src/app/injector.js#L4)):*
I'll add a todo to fix it. Good enough for now?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by alyec** [comment]
Reviewed 1 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/248)*

**Pull request merged**
