### PR TITLE
State transistions for invisible layers

### PR DESCRIPTION
**Pull request by james-rae**
Change to state transition flow to accommodate invisible and out-of-scale layers.

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/980

Will probably want to wait for @alyec to review before pulling

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1011)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 176 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011#-KNn5KcDm_JrVieFksDE:-KNn5KcEohBFhjvQlr6Q:1976260034) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/984243fe5a33233e766149b9a401111eae559ffa/src/app/geo/layer-record.class.js#L176)):*
> ```JavaScript
>                 } else {
>                     this.constructLayer(config);
>                     this.state = Geo.Layer.States.LOADING;
> ```

I think you can safely remove `NEW` from geo.constant.service.js (should be line 30)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011)*

**Comment by james-rae** [comment]
*[src/app/geo/layer-record.class.js, line 176 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011#-KNn5KcDm_JrVieFksDE:-KNn6M4jEM4P7ADinBny:-482871991) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/984243fe5a33233e766149b9a401111eae559ffa/src/app/geo/layer-record.class.js#L176)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> I think you can safely remove `NEW` from geo.constant.service.js (should be line 30)
</details>
Agreed -- also pretty sure i can combine `LOADING` and `REFRESH`, but will wait for Aly's review in case he wants larger changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-record.class.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011#-KNqQGHoSRUwexLPcrV0:-KNqQGHpAnTNvsrsLtuy:1627167257) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/984243fe5a33233e766149b9a401111eae559ffa/src/app/geo/layer-record.class.js#L96)):*
> ```JavaScript
>                     }
>                 }
>                 lookupPromise.then(() => this._stateChange(Geo.Layer.States.LOADED));
> ```

If I remember correctly, the `load` event indicates the initial handshake, not that layer has rendered. We waited for the first `update-end` to mark a layer as `LOADED`. Wouldn't this show layers as loaded in the layer selector before their data is actually visible?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011)*

**Comment by james-rae** [comment]
*[src/app/geo/layer-record.class.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011#-KNqQGHoSRUwexLPcrV0:-KNqywCOtAixN2vSGVIS:1606365613) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/984243fe5a33233e766149b9a401111eae559ffa/src/app/geo/layer-record.class.js#L96)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> If I remember correctly, the `load` event indicates the initial handshake, not that layer has rendered. We waited for the first `update-end` to mark a layer as `LOADED`. Wouldn't this show layers as loaded in the layer selector before their data is actually visible?
</details>
Correct about the effect of `load`.  However, waiting for `update-end` is the cause of our problems...a layer can be perfectly fine without requesting data when it is invisible.  It is in fact loaded, and its current map state is a no-features state.  

In the normal case (data is visible at start), which I think is where your concern lies, the following would happen with this new state system:
* Layer Record created with `LOADING` state. Constructor generates an ESRI Layer object.
* Legend shows an entry with the loading animation
* `load` event happens. `LOADED` state applied. Legend animation stops.
* __Immediately__, `update-start` event happens.  `REFRESH` state applied.  Legend animates again.
* Wait for data to finish downloading
* `update-end` event happens.  `LOADED` state applied. Legend animation stops.
* :chicken: :dash: 

The only possible minor issue is the user may notice a reset of the legend animation when it goes from `LOADING` :arrow_right: `LOADED` :arrow_right: `REFRESH`.  But I think this is far better than an invisible or off-scale layer constantly showing the animation when it is not actually loading anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011)*

**Comment by james-rae** [comment]
Second commit closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1012
(piggybacking PRs for release day)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011#-:-KNr8dfzIXf5nWzgOfVR:-780568891)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011#-KNqQGHoSRUwexLPcrV0:-KNrCGIjwskDu2rvxRhO:699314560) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/984243fe5a33233e766149b9a401111eae559ffa/src/app/geo/layer-record.class.js#L96)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Correct about the effect of `load`.  However, waiting for `update-end` is the cause of our problems...a layer can be perfectly fine without requesting data when it is invisible.  It is in fact loaded, and its current map state is a no-features state.  
> 
> In the normal case (data is visible at start), which I think is where your concern lies, the following would happen with this new state system:
> * Layer Record created with `LOADING` state. Constructor generates an ESRI Layer object.
> * Legend shows an entry with the loading animation
> * `load` event happens. `LOADED` state applied. Legend animation stops.
> * __Immediately__, `update-start` event happens.  `REFRESH` state applied.  Legend animates again.
> * Wait for data to finish downloading
> * `update-end` event happens.  `LOADED` state applied. Legend animation stops.
> * :chicken: :dash: 
> 
> The only possible minor issue is the user may notice a reset of the legend animation when it goes from `LOADING` :arrow_right: `LOADED` :arrow_right: `REFRESH`.  But I think this is far better than an invisible or off-scale layer constantly showing the animation when it is not actually loading anything.
</details>
Sounds good. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1011#-:-KNrCuRNlpcnc3kx9MPQ:1417088721)*

**Pull request merged**
