### PR TITLE
Use scale in bookmark

### PR DESCRIPTION
**Pull request by james-rae**
Use scale instead of scale level in bookmarks. 
Add version key to bookmark. 

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1068

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1127)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127#-KQWDJ3ohF5vKIYmb10W:-KQWDJ3pcGLclem_7Flv:b-eok742) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13e80a951d317643f9bbe0588dfb871123f86423/src/app/core/bookmark.service.js#L39)):*
> ```JavaScript
>             const mapExtent = geoService.mapObject.extent.getCenter();
> 
>             // get scale level
> ```

zoom scale instead of scale level?

---

*[src/app/core/bookmark.service.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127#-KQWDlv63R45cjFm2H90:-KQWDlv63R45cjFm2H91:b-57dsua) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13e80a951d317643f9bbe0588dfb871123f86423/src/app/core/bookmark.service.js#L96)):*
> ```JavaScript
> 
>             // mark initial basemap
>             config.map.initialBasemapId = basemap;
> ```

`config.map.initialBasemapId = newBaseMap || basemap`

---

*[src/app/core/reload.service.js, line 41 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127#-KQWDxC9E7WEdGJgTlQ2:-KQWDxC9E7WEdGJgTlQ3:bhftkph) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13e80a951d317643f9bbe0588dfb871123f86423/src/app/core/reload.service.js#L41)):*
> ```JavaScript
>             // get original config and add bookmark to it
>             configService.getOriginal().then(config => {
>                 bookmarkService.parseBookmark(bookmark, config, undefined, basemapId);
> ```

With the above change to bookmark you should be able to simplify this:

```
bookmarkService.parseBookmark(bookmark, config, undefined, basemapId);
geoService.assembleMap();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127)*

**Comment by james-rae** [comment]
*[src/app/core/bookmark.service.js, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127#-KQWDJ3ohF5vKIYmb10W:-KQWhgRs_ZqA9RzKGWXS:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13e80a951d317643f9bbe0588dfb871123f86423/src/app/core/bookmark.service.js#L39)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> zoom scale instead of scale level?
</details>
done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127)*

**Comment by james-rae** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127#-KQWDlv63R45cjFm2H90:-KQWhlNOVZdd0fgsFX3d:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13e80a951d317643f9bbe0588dfb871123f86423/src/app/core/bookmark.service.js#L96)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> `config.map.initialBasemapId = newBaseMap || basemap`
</details>
done, thanks

---

*[src/app/core/reload.service.js, line 41 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127#-KQWDxC9E7WEdGJgTlQ2:-KQWhn_zP3oIUZyeUTTl:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/13e80a951d317643f9bbe0588dfb871123f86423/src/app/core/reload.service.js#L41)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> With the above change to bookmark you should be able to simplify this:
> 
> ```
> bookmarkService.parseBookmark(bookmark, config, undefined, basemapId);
> geoService.assembleMap();
> ```
</details>
done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127#-:-KQ_ZM22fj8hagolPDyl:bnfp4nl)*

**Comment by milesap** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1127)*

**Pull request merged**
