### PR TITLE
fix(datatable): parsing column names and filters

### LINKED ISSUE #2019: Error parsing French accents
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

Opening a datatable for any layer which has columns with French accents in them throws an error: 
`Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 8-8 [é] in expression [self.Catégorie.value].`

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2019 and any related parsing problems that may occur.

## Testing
Visually tested.

## Documentation
None

## Checklist

- [ ] commits messages follow the guidelines
- [ ] code passes unit tests
- [ ] release notes have been updated
- [ ] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2166)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-definition.directive.js, line 273 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166#-Kp1EmNN_dZznh6gJ40K:-Kp1EmNN_dZznh6gJ40L:b-htkx2s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e1260944d92b128974c4aecb9f1918a8864c9f8e/src/app/ui/filters/filters-definition.directive.js#L273)):*
> ```JavaScript
>             filter.scope = filterScope;
> 
>             if (!column.simpleColumnName) {
> ```

Can you add a bit more detailed comment here why we need simplified names?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166)*

**Comment by JahidAhmed** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-definition.directive.js, line 273 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166#-Kp1EmNN_dZznh6gJ40K:-KpFjzVuneUJQEL2AwfX:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e1260944d92b128974c4aecb9f1918a8864c9f8e/src/app/ui/filters/filters-definition.directive.js#L273)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you add a bit more detailed comment here why we need simplified names?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-definition.directive.js, line 273 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166#-Kp1EmNN_dZznh6gJ40K:-KpFtdBceXnfxIorEuZI:b-etrs3f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e1260944d92b128974c4aecb9f1918a8864c9f8e/src/app/ui/filters/filters-definition.directive.js#L273)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think you remove the whole file :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2166)*

**Pull request merged**
