### PR TITLE
Get the viewer to load in ie11

### PR DESCRIPTION
**Pull request by spencerwahl**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/487)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 239 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/487#-KFPaXcHICvp7xP76OG5:-KFPaXcHICvp7xP76OG6:1474610059) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b30a288e900273027910b3f54f2db4a8ece07ec3/gulpfile.js#L239)):*
I'm guess there's a reason for us not to use to use babel on the polyfills?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/487)*

**Comment by spencerwahl** [comment]
*[gulpfile.js, line 239 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/487#-KFPaXcHICvp7xP76OG5:-KFPb0B3b5b-4EE7IFCo:-120108599) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b30a288e900273027910b3f54f2db4a8ece07ec3/gulpfile.js#L239)):*
Ill add a note.

We aren't using babel on them since it was not allowing access that some of the polyfills needed. (e.g. when `this` referred to `window` it would be rewritten as `undefined`).

I changed all the polyfills to be es5 so there are no problems there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/487)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/487)*

**Comment by ec-dev** [comment]
Reviewed 7 of 9 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/487)*

**Comment by AleksueiR** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/487)*

**Pull request merged**
