### PR TITLE
feat(ui): tab and hoverIntent support for layer list panel

### LINKED ISSUE #147: feat(ui): point information panel - open layer list on hover intent or after a slight delay
Right now it's just opening on hover which might be annoying.

Also, open the list on focus for keyboard support. When triggered from the keyboard, set focus to the pane's close button.

### PR DESCRIPTION
**Pull request by milesap**
Closes #147

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/681)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details.html, line 118 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ122fqlDwXmFVEg79a:-KJ122fr-7l7NfpGecf3:1786879964) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.html#L118)):*
> ```HTML
>                         class="rv-button-square rv-details-layer-button" 
>                         ng-click="self.selectItem(item)">
>                     
> ```

trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681)*

**Comment by AleksueiR** [comment]
Getting this error in the console:

```js
service.js:115Error: [$parse:isecdom] Referencing DOM nodes in Angular expressions is disallowed! Expression: self.linkHoverIntent()
http://errors.angularjs.org/1.4.11/$parse/isecdom?p0=self.linkHoverIntent()
    at http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:1227:12
    at ensureSafeObject (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:14051:13)
    at fn (eval at compile (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:14802:15), <anonymous>:4:228)
    at Scope.$eval (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:17533:28)
    at pre (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:26165:15)
    at invokeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:10248:9)
    at nodeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9714:11)
    at compositeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9134:13)
    at compositeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9137:13)
    at publicLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9014:30) <rv-slider tabindex="-1" ng-init="self.linkHoverIntent()" class="rv-details-layer-list" ng-show="self.display.data.length >
```

<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### feat\(ui\): tab and hoverIntent support for layer list panel
> 
> Closes #147
> 
> 
> 
</details>


---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/ui/details/details.directive.js, line 55 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1Ju67SLY-A3gUr4q4:-KJ1Ju67SLY-A3gUr4q5:349716976) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/68fe4fd143d0a776da6afed8df76457bec81cde8/src/app/ui/details/details.directive.js#L55)):*
> ```JavaScript
> 
>             function onEnter($event) {
>                 if (!layerListNode || layerListNode[0] !== $event.currentTarget) {
> ```

This check was needed to create the animation only once when panel's content changes. Without it the animation will be recreated every time `onHover` is called.

---

*[src/app/ui/details/details.directive.js, line 57 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1MEtHEELxwpQG0NHy:-KJ1MEtIt78u4q_1H7ZA:-599569683) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.directive.js#L57)):*
> ```JavaScript
> 
>             self.focusOnClose = evt => {
>                 if (evt.which === 13) {
> ```

Please add 33 and `Space`.

---

*[src/app/ui/details/details.directive.js, line 58 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1EsFmUvZpc4F_87te:-KJ1EsFmUvZpc4F_87tf:-2021062631) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.directive.js#L58)):*
> ```JavaScript
>             self.focusOnClose = evt => {
>                 if (evt.which === 13) {
>                     element.find('button')[1].focus();
> ```

Does `[1]` refer to the close button? Is so, this is very brittle as the structure of the content pane can change.

I think the better way would be to let the panel (or panel-content) directive decide where the focus should go as details directive generally shouldn't know how to get to the close button.

---

*[src/app/ui/details/details.directive.js, line 64 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1I0WOjU9Yb1bR2FUc:-KJ1I0WPff9cqf7Mnsye:-1731446331) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.directive.js#L64)):*
> ```JavaScript
>             let isOpenState = false; // track if side panel is open/closed
>             function onEnter() {
>                 if (!isOpenState) {
> ```

No need to check for state, `play` always moves animation forwards; `reverse`, backwards.

---

*[src/app/ui/details/details.directive.js, line 87 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1GigxMAdbPH3pwBAs:-KJ1GigxMAdbPH3pwBAt:-1319006240) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.directive.js#L87)):*
> ```JavaScript
> 
>                     isOpenState = true;
>                     tl.play(0, false);
> ```

Forcing the timeline to play from 0 can cause jerky animation when `play` is called in the middle of `reverse` for example.

---

*[src/app/ui/details/details.html, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1CVr6gLzSPB-G3QTg:-KJ1CVr6gLzSPB-G3QTh:771002527) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.html#L101)):*
> ```HTML
> 
>         
>         <rv-slider tabindex="-1"
> ```

Any reason for changing `div` to `rv-slider`? As far as I can tell it's not a directive.

---

*[src/app/ui/details/details.html, line 112 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1DP8uQMFZqGWV8iNy:-KJ1DP8uQMFZqGWV8iNz:-1972718773) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.html#L112)):*
> ```HTML
> 
>                     <md-button
>                         ng-blur="$last ? self.onLeave() : false"
> ```

This will also trigger blur when you `shitf+tab` on the last button which doesn't take you out of the selector.

Also, the selector should close when you tab out at either end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-:-KJ1DHqh5vWNaIzws65h:-1254500943)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/ui/details/details.directive.js, line 57 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-KJ1MEtHEELxwpQG0NHy:-KJ1_erIJJDVYRymSXyL:-1032033734) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e51b9b90c79e27054c6c97746db107bc0f515d65/src/app/ui/details/details.directive.js#L57)):*
> Please add 32 which is `Space`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681)*

**Comment by AleksueiR** [comment]
The last couple of commits seem to be a separate PR. They modify the code in the previous commits though, offsetting comments and making everything quite hard to read and understand which comments have been addressed.

Please, can you PR the second set of commits separately?

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Getting this error in the console:
> 
> ```js
> service.js:115Error: [$parse:isecdom] Referencing DOM nodes in Angular expressions is disallowed! Expression: self.linkHoverIntent()
> http://errors.angularjs.org/1.4.11/$parse/isecdom?p0=self.linkHoverIntent()
>     at http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:1227:12
>     at ensureSafeObject (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:14051:13)
>     at fn (eval at compile (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:14802:15), <anonymous>:4:228)
>     at Scope.$eval (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:17533:28)
>     at pre (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:26165:15)
>     at invokeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:10248:9)
>     at nodeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9714:11)
>     at compositeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9134:13)
>     at compositeLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9137:13)
>     at publicLinkFn (http://fgpv.cloudapp.net/demo/users/milesap/feat/point-info-hover/core.js:9014:30) <rv-slider tabindex="-1" ng-init="self.linkHoverIntent()" class="rv-details-layer-list" ng-show="self.display.data.length >
> ```
</details>


---

Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-:-KJMZfOWX6sPauLakZF2:-916397626)*

**Comment by AleksueiR** [comment]
I do think bundling PRs is a good idea. However, in my opinion, PRs should be reasonably small (in scope, amount of changes, and the number of files affected) and submitted at the same time, not days apart. More importantly, bundled PRs should not modify the same code. Overlapping changes make it harder to read the code, understand if the comments were properly addressed and check if PRs are actually doing what they are supposed to do.

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> The last couple of commits seem to be a separate PR. They modify the code in the previous commits though, offsetting comments and making everything quite hard to read and understand which comments have been addressed.
> 
> Please, can you PR the second set of commits separately?
</details>


---

Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-:-KJYVas8EjB4fWDcme3w:774747955)*

**Comment by milesap** [comment]
Latest commit combines issues #665, #622, and #147.

Firefox and IE continue to have isolated issues with the statemanager tracking and setting focus.
- Firefox has an open issue https://bugzilla.mozilla.org/show_bug.cgi?id=962251 with a target milestone of 48 where it returns null for the relatedTarget in both blur and focus events. Once implemented these issues will resolve.
- IE is strict about which elements can have focus and routinely throws errors when setting focus even though support for focus in IE 11 is there. IE crashes when trying to view index-one.html, and is non-responsive with dev. tools open.

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I do think bundling PRs is a good idea. However, in my opinion, PRs should be reasonably small (in scope, amount of changes, and the number of files affected) and submitted at the same time, not days apart. More importantly, bundled PRs should not modify the same code. Overlapping changes make it harder to read the code, understand if the comments were properly addressed and check if PRs are actually doing what they are supposed to do.
</details>


---

Review status: 0 of 18 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/681#-:-KJ_lS0GQsXy1Qkw-HOP:2102932239)*

**Pull request closed without merging**
