### PR TITLE
fix(translation): Fix bad French translation

### LINKED ISSUE #2703: Inappropriate French translation for standby message "Building Table..."
Unless the standby message is to convey "**Table of the building...**",  "**Tableau de l'immeuble...**" is inappropriate.

In translations.csv:
`,table.splash.buildingtable,Building Table ...,1,Tableau de l’immeuble ...,0`

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2703

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/locales/translations.csv, line 36 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731#-LDHdb2O-BfK7KKkrCy5:-LDHdb2O-BfK7KKkrCy6:bp16wvl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7abf96c6cc22d720d6567ec3b43be28e8330b101/src/locales/translations.csv#L36)):*
> ```CSV
> Tooltip text for No Zoom Projection,filter.tooltip.nozoom,Data in custom projection. Cannot zoom to feature.,1,La donnée utilise une projection personnalisée. Le zoom à l'élément n'est pas supporté.,1
> DataTable text for Processing,filter.default.label.processing,Processing...,1,Traitement en cours...,1
> Datatable contents out of date,filter.default.label.outOfDate,Table may be out of date with layer,1,Le tableau peut être périmée avec la couche,1
> ```

Remove 'e' from périmé~~e~~

---

*[src/locales/translations.csv, line 115 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731#-LDHdrbT4pWi9eKvk-81:-LDHdrbU-Y0Oj8c1Vd3b:bwqgp47) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7abf96c6cc22d720d6567ec3b43be28e8330b101/src/locales/translations.csv#L115)):*
> ```CSV
> ,basemap.showdescription,Show basemap description,1,Montrer la description de la carte de base,1
> ,basemap.hidedescription,Hide basemap description,1,Masquer la description de la carte de base,1
> Basemap broken,basemap.broken,Basemap load failed,1,Le chargement du fond de carte à échoué,0
> ```

'a' with no accent

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/locales/translations.csv, line 36 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731#-LDHdb2O-BfK7KKkrCy5:-LDHewxD223crDePNNM_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7abf96c6cc22d720d6567ec3b43be28e8330b101/src/locales/translations.csv#L36)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Remove 'e' from périmé~~e~~
</blockquote></details>

Done.

---

*[src/locales/translations.csv, line 115 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731#-LDHdrbT4pWi9eKvk-81:-LDHexQS8RbdK3w2o5V6:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7abf96c6cc22d720d6567ec3b43be28e8330b101/src/locales/translations.csv#L115)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

'a' with no accent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731#-:-LDHgqjI4G6Xq2z25B34:bnfp4nl)*

**Pull request merged**
