### PR TITLE
feat(ui): add toast for bad boundary zooms

### LINKED ISSUE #2273: Zoom To Layer Boundary Behavior
Need to determine best logic for where map ends up when user clicks `Zoom To Layer Boundary`

## Layer with Well-Defined Extent

Want to zoom to it.  In particular, useful if area is small, or outside the normal map view (e.g. user adds dataset in China. Zooming to it lets them know why they don't see it in Canada).

## Layer with Massive Extent

Often the case of poor server defaulting (e.g. WMS really likes to do the entire world in Lat/Long).  Sometimes data covers entire world, sometimes not; this makes zooming to the extent randomly useful.

Is a bigger problem with Lambert basemap; it's focused on Canada and distorts the rest of the world severly. Zooming to the world means Canada is panned northward off the screen.

Mercator is not bad because our tile set covers the world and what you see on the screen makes sense.

User can always click the "Canada Extent" button to return from a nonsense view.

## Options

This is most problematic with RCS layers and user-added layers. A config-file based layer can override the layer extent to be something intelligent.

Each basemap category (i.e. projection schema) can have various extents set for them, such as `full` and `maximum` extents; however these are not required. `default` is required and will be used if the other extents are not provided.  We could add logic that limits the `Zoom To Layer Boundary` to reside inside one of those extents. But we lose some utility in doing so (e.g. if data is in Europe, where do you zoom to? Canada view? Not helpful).

Since user can always recover from a silly/confusing view, we could just accept that some zooms will be bad (e.g. full world in Lambert) and blame the service creators.

Related issues:
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1650
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2259

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Detect zoom to boundary events that move the extent center outside the full extent of the basemap and display a toast to the user with an option to adjust the new extent.

Closes #2273

## Documentation
Inline comments.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2304)

### CODE REVIEW

**Comment by barryytm** [comment]
I tried importing https://services.arcgis.com/HuLaMAzbcrbWfOM8/ArcGIS/rest/services/Outline_of_world_countries/FeatureServer/0 but it failed.

**Comment by james-rae** [comment]
Looks like you found a different bug, Barry.  Code appears to be thinking that layer is geoJson and then fails. Possibly related to that fix that handles any file name?  I'll trace

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2304#-:-Kr7EmIsBeZcDODpeglb:bj3y9ka)*

**Comment by barryytm** [comment]
WOMM

---

Reviewed 8 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2304#-:-Kr7FFRqxB-6NE1XiSq0:bb76399)*

**Comment by AleksueiR** [comment]
It works on current develop, but fails in 2.1.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2304#-:-Kr7FQW9SvBsg7cZbxHO:bvikklv)*

**Comment by james-rae** [comment]
I think that recent fix conflicts with our old prediction code.  First glance looks like our Service Wizard still executes file check on path (later on we moved server-based-files to file part of the wizard).  Since we now default to geoJson, it concludes geoJson before even checking if it's a map server

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2304#-:-Kr7FULN8RL8C2D6YVdK:b-trpbnl)*

**Comment by james-rae** [comment]
Since unrelated, and is on 2.1.0 branch, commit this and then fix as separate PR?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2304#-:-Kr7FrgSD4F7qfF9vIoz:bcoo396)*

**Comment by AleksueiR** [comment]
Works for me. Can you make a new issue for this bug?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2304#-:-Kr7HAq4_lqufj1lGxZz:b-8lrunh)*

**Pull request merged**
