### PR TITLE
feat(ui): error toast shown when metadata or datatable fails to load

### LINKED ISSUE #564: Add error message to datatable if attribute fail to load
There is no message or any visible indication that attribute loading failed.

If a user opens a datatable and loading fails, he can wait a long time not realizing nothing is happening anymore.

Maybe we can also retrying to load attributes on fail.

### PR DESCRIPTION
**Pull request by milesap**
Toast appears on bottom of panel.

Closes #564, #591

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/601)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/displaymanager.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf77RjKh4BS-nAreaJ:-KHf77RkU4Xf5Qw9aQ5i:135398296) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/common/router/displaymanager.service.js#L66)):*
> ```JavaScript
>          * @param  {Object} requester        an optional object requesting display change; must have `id` attribute if you want the panel to toggle off on the same requester; requester object can be used to immediately pass content to the panel - for example passing layer name to the filters panel to be displayed in the panel header while the datatable is being constructed;
>          * @param  {Number} delay            an optional time to wait (in milliseconds) before setting loading indicator
>          * @return {Object} return promise
> ```

Please include what the promise will resolve to.

---

*[src/app/ui/common/error.service.js, line 25 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf9ybmGMp9iEBO_R1c:-KHf9ybmGMp9iEBO_R1d:-794356123) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/common/error.service.js#L25)):*
> ```JavaScript
>         return service;
> 
>         function display(errorMsg, parentElem) {
> ```

Needs a jsdoc header

---

*[src/app/ui/toc/toc.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf9MdgknvzvpHBXm8q:-KHf9MdhQiieeZ7k4Bxd:-1136501975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/toc/toc.service.js#L288)):*
> ```JavaScript
>                     stateManager.toggleDisplayPanel('filtersFulldata', dataPromise, requester, 0)
>                         .catch(() => {
>                             errorService.display('There was an error retrieving this resource, try again later.',
> ```

Needs translation

---

*[src/app/ui/toc/toc.service.js, line 340 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf9aej2B6FRETHfiw3:-KHf9aej2B6FRETHfiw4:-2115382839) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/toc/toc.service.js#L340)):*
> ```JavaScript
>                 .then(() => stateManager.toggleDisplayPanel('sideMetadata', dataPromise, requester, 0)
>                         .catch(() => {
>                             errorService.display('There was an error retrieving this resource, try again later.',
> ```

Translate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601)*

**Comment by milesap** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/displaymanager.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf77RjKh4BS-nAreaJ:-KHtc59BMRUiTYR5hZlK:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/common/router/displaymanager.service.js#L66)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Please include what the promise will resolve to.</details>
complete

---

*[src/app/ui/common/error.service.js, line 25 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf9ybmGMp9iEBO_R1c:-KHtbz1WB_-V8_y6qKhH:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/common/error.service.js#L25)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Needs a jsdoc header</details>
complete

---

*[src/app/ui/toc/toc.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf9MdgknvzvpHBXm8q:-KHtc0jIpbWjsWV3cqBf:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/toc/toc.service.js#L288)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Needs translation</details>
complete

---

*[src/app/ui/toc/toc.service.js, line 340 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf9aej2B6FRETHfiw3:-KHtc2_gXjUkWRoi1BKN:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/toc/toc.service.js#L340)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Translate</details>
complete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/common/router/displaymanager.service.js, line 121 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHtfWgbn1DpG33z30wE:-KHtfWgbn1DpG33z30wF:-1035940761) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/common/router/displaymanager.service.js#L121)):*
> ```JavaScript
>                     .catch(() => {
>                         display.isLoading = false;
>                         return $q.reject();
> ```

I don't think you need to return a rejected promise in the `catch`. Any `catch` after this one will be triggered anyway.
@alyec Aly, is it correct?

---

*[src/app/ui/common/error.service.js, line 38 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHt_MfEsJD9gfanXORu:-KHt_MfEsJD9gfanXORv:425536498) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/common/error.service.js#L38)):*
> ```JavaScript
>             }
> 
>             return $mdToast.hide().then(() => { // hide any pre-existing toast
> ```

Seems `$mdToast` can support only one toast at a time: no need to explicitly close existing ones.

---

*[src/app/ui/panels/panel.directive.js, line 41 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHtfwFBwTKQz0_6GXVx:-KHtfwFBwTKQz0_6GXVy:-2077384771) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/ui/panels/panel.directive.js#L41)):*
> ```JavaScript
> 
>         function link(scope, elem) {
>             layoutService.panes.filter = elem[0].previousSibling;
> ```

`rvPanel` is a container directive for all the panels; it will be created several times and `layoutService.panes.filter` value will hold the element reference for the last panel element.

Add `layoutService.panes.filters = el;` to the `link` function in the `filters-defaults.directive.js` instead, similar to the `metadata-panel.directive.js` above.

---

*[src/app/ui/toc/toc.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHf9MdgknvzvpHBXm8q:-KHtiETXMtzhQVjR8FWf:-883234729) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/toc/toc.service.js#L288)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> complete</details>
Array functions by default return the result of a single statement (which is a promise in this case). You can attach `catch` directly on top of `then` and avoid the pyramid of doom.

```js
    .then(() => stateManager.toggleDisplayPanel('filtersFulldata', dataPromise, requester, 0)
    .catch(() => {
        errorService.display('There was an error retrieving this resource, try again later.',
            layoutService.panes.filter);
    });
```

---

*[src/app/ui/toc/toc.service.js, line 338 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHtiTkRUzhhFSS9bGDx:-KHtiTkRUzhhFSS9bGDy:-1742265148) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/ui/toc/toc.service.js#L338)):*
> ```JavaScript
>             stateManager
>                 .setActive(panelToClose)
>                 .then(() => stateManager.toggleDisplayPanel('sideMetadata', dataPromise, requester, 0)
> ```

Don't set the delay to 0, it makes the metatada panel flicker when switching to after it cached the text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/common/router/displaymanager.service.js, line 121 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHtfWgbn1DpG33z30wE:-KHtjdjmwKMiSeMvycM7:168725298) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/common/router/displaymanager.service.js#L121)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I don't think you need to return a rejected promise in the `catch`. Any `catch` after this one will be triggered anyway.
> @alyec Aly, is it correct?</details>
In the then section above I think `return;` instead of `return $q.resolve();` works.  In this case instead of rejecting a new promise it probably makes more sense to rethrow the existing error.  Maybe:
```js
.catch(err => {
  display.isLoading = false;
  throw err;
});
```
which allows `dataPromise` to pass error information through this handler into the next one if it makes sense to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/displaymanager.service.js, line 121 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHtfWgbn1DpG33z30wE:-KHuXUaG3iRRBqT8VVr4:2014820002) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/common/router/displaymanager.service.js#L121)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> In the then section above I think `return;` instead of `return $q.resolve();` works.  In this case instead of rejecting a new promise it probably makes more sense to rethrow the existing error.  Maybe:
> ```js
> .catch(err => {
>   display.isLoading = false;
>   throw err;
> });
> ```
> which allows `dataPromise` to pass error information through this handler into the next one if it makes sense to do so.</details>
complete 

---

*[src/app/ui/common/error.service.js, line 38 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHt_MfEsJD9gfanXORu:-KHuX_DPOmaAYER8wsbj:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/common/error.service.js#L38)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Seems `$mdToast` can support only one toast at a time: no need to explicitly close existing ones.</details>
complete

---

*[src/app/ui/toc/toc.service.js, line 338 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHtiTkRUzhhFSS9bGDx:-KHuXa2SeVDwXmeKHja_:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/ui/toc/toc.service.js#L338)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Don't set the delay to 0, it makes the metatada panel flicker when switching to after it cached the text.</details>
complete

---

*[src/app/ui/panels/panel.directive.js, line 41 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHtfwFBwTKQz0_6GXVx:-KHuXb04oXeD8GFW1UEJ:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/ui/panels/panel.directive.js#L41)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `rvPanel` is a container directive for all the panels; it will be created several times and `layoutService.panes.filter` value will hold the element reference for the last panel element.
> 
> Add `layoutService.panes.filters = el;` to the `link` function in the `filters-defaults.directive.js` instead, similar to the `metadata-panel.directive.js` above.</details>
complete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601)*

**Comment by AleksueiR** [comment]
Please, modify toasts so they don't stretch and center them as we discussed: 

<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### feat\(ui\): error toast shown when metadata or datatable fails to load
> 
> Toast appears on bottom of panel.
> 
> 
> 
> Closes #564, #591
> 
> 
> 
</details>


---

Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/error.service.js, line 38 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHt_MfEsJD9gfanXORu:-KHujRWakgGFJW6AV9Nl:-1819095686) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7fbe61eeb7d632be97d6d97b43df77337607a585/src/app/ui/common/error.service.js#L38)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> complete
</details>
You might still want to return the toast in case whoever calls it, wants to act on user input (or the lack of).

---

*[src/app/ui/toc/toc.service.js, line 286 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-KHukSPdw3nG-7nthmnG:-KHukSPdw3nG-7nthmnH:-1224184736) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/aba614f1608f088f69b13865e17bf8dba47186f8/src/app/ui/toc/toc.service.js#L286)):*
> ```JavaScript
>                 })
>                 .then(() => {
>                     stateManager.toggleDisplayPanel('filtersFulldata', dataPromise, requester, 0)
> ```

:) 0 delay is set here on purpose. Even if we have data cached it takes time to render the datatable, so we want the loading indicator to be turned on immediately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/601#-:-KI3hOJI77VTUHEcChWn:-1521006844)*

**Pull request closed without merging**
