### PR TITLE
Basic feature layer support

### PR DESCRIPTION
**Pull request by alyec**
- unit tests to follow in a separate PR

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/203)

### CODE REVIEW

**Comment by james-rae** [comment]
Do we want to use filename `configFeatures.json` when it can contain layers that are not feature layers?  I'm indifferent, but raising it now while file is new 

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-:-K7rA7SbLmCwH8X5nmOQ:-1006039321)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/geo/geo.service.js, line 49 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r7hd7T2Bfbz9DEn4Y:-K7r7hd7T2Bfbz9DEn4Z:1108332419) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L49)):*
Nitpicking: wouldn't it be clearer to rename `order` to `position`?

---

*[src/app/geo/geo.service.js, line 122 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r862ihXmdGPe4qNTL:-K7r862ihXmdGPe4qNTM:983767901) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L122)):*
Can we use another basemap, not the grey one? :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Comment by alyec** [comment]
I was going to keep it as `configFeatures` and add separate configs for other cases.  I'm good with any of the options.

---

Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 49 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r7hd7T2Bfbz9DEn4Y:-K7rBBkBfyqkoaeosd7M:678041242) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L49)):*
sure

---

*[src/app/geo/geo.service.js, line 122 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r862ihXmdGPe4qNTL:-K7rB8VxLhHqExO2vLGR:5174662) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L122)):*
no

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-:-K7rAynfWsE5_kD6OqhV:1303434125)*

**Comment by AleksueiR** [comment]
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---

*[src/app/geo/geo.service.js, line 122 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r862ihXmdGPe4qNTL:-K7rCDCK3UhK5PEWEuCz:502306121) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L122)):*
Why not?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Comment by alyec** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 122 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r862ihXmdGPe4qNTL:-K7rCZ_frI6UtkBu69Iu:-274979654) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L122)):*
I'm too lazy to lookup the other options.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Comment by james-rae** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 122 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r862ihXmdGPe4qNTL:-K7rD2LUSToFsewUQ0TA:1736664581) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L122)):*
"streets" , "satellite" , "hybrid", "topo", "gray", "dark-gray", "oceans", "national-geographic", "terrain" and "osm"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Comment by alyec** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 122 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r862ihXmdGPe4qNTL:-K7rD6KF1LtCjK9Yikc_:-1856380076) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L122)):*
dark-gray it is

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Comment by AleksueiR** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 122 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203#-K7r862ihXmdGPe4qNTL:-K7rDLvrJ40c6CncFShp:816197015) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da831e0202b901b5fcabc3eb1379fc1dfc3de6ca/src/app/geo/geo.service.js#L122)):*
http://www.nooooooooooooooo.com/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/203)*

**Pull request merged**
