### PR TITLE
fix(ui): fix broken layer selector

### PR DESCRIPTION
**Pull request by spencerwahl**
issue #598

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/615)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615)*

**Comment by AleksueiR** [comment]
Add `Closes #598` to the commit message please.

<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> #### fix\(ui\): fix broken layer selector
> 
> issue #598
> 
> 
> </details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/ui/details/details.directive.js, line 55 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615#-KHyah7dHlwxZy2U5zqV:-KHyah7dHlwxZy2U5zqW:1490076152) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a263ef13e8309ebadcc2ef46186807ce7ee79186/src/app/ui/details/details.directive.js#L55)):*
> ```JavaScript
> 
>             function onEnter($event) {
>                 if (!layerList || layerList[0] !== $event.currentTarget) {
> ```

I suggest renaming `layerList` to `layerListNode` (and `section` to `sectionNode`) because `layerList[0]` looks like it is accessing the first item of some layer list.

---

*[src/app/ui/details/details.directive.js, line 60 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615#-KHya0xGrZTr6_OA_MCx:-KHya0xGrZTr6_OA_MCy:-1587115861) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a263ef13e8309ebadcc2ef46186807ce7ee79186/src/app/ui/details/details.directive.js#L60)):*
> ```JavaScript
>                     section = element.find(RV_DETAILS_SECTION);
> 
>                     tl.clear();
> ```

You can chain `tl.clear().to(...)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615#-:-KHyaaC0BxxT0LsBhig3:-285558404)*

**Comment by spencerwahl** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/details/details.directive.js, line 55 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615#-KHyah7dHlwxZy2U5zqV:-KHzKDvhV_l6ePExJnWF:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a263ef13e8309ebadcc2ef46186807ce7ee79186/src/app/ui/details/details.directive.js#L55)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I suggest renaming `layerList` to `layerListNode` (and `section` to `sectionNode`) because `layerList[0]` looks like it is accessing the first item of some layer list.</details>
Done.

---

*[src/app/ui/details/details.directive.js, line 60 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615#-KHya0xGrZTr6_OA_MCx:-KHzKEDndK7a1O6B1iXO:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a263ef13e8309ebadcc2ef46186807ce7ee79186/src/app/ui/details/details.directive.js#L60)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> You can chain `tl.clear().to(...)`.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/615)*

**Pull request merged**
