### PR TITLE
fix(help): search terms no longer target element types or attributes

### LINKED ISSUE #1797: Fix help search functionality to avoid selecting element attributes
Bug was noticed with inclusion of markdown support where image names are included in seach results (and therefore display the html element is plain text.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Regex cannot be used to determine html elements/attributes. Instead, a
dom tree is created, textNodes extracted and searched.

Closes #1797

## Testing
Yes, in browser

## Documentation
inline, jsdocs

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1811)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/help/help.service.js, line 50 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1811#-KgKFiEuoD00O5aeaX_H:-KgKFiEvBlW_71b8QSPJ:byekgdw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74430d34bbb837078d713d88da149edd950c68c1/src/app/ui/help/help.service.js#L50)):*
> ```JavaScript
>             htmlFragment.appendChild(searchElement);
>             // place fragment into DOM
>             $('#searchtree').append(htmlFragment);
> ```

Does it have to be added to the DOM? Can be detached? If not, don't make it global, it can target nodes outside the viewer and nodes in other viewer instances.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1811)*

**Comment by milesap** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/help/help.service.js, line 50 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1811#-KgKFiEuoD00O5aeaX_H:-KgKKRC-WC0T40mHS0Hi:b2xdz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/74430d34bbb837078d713d88da149edd950c68c1/src/app/ui/help/help.service.js#L50)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Does it have to be added to the DOM? Can be detached? If not, don't make it global, it can target nodes outside the viewer and nodes in other viewer instances.
</blockquote></details>

It can be detached - I like that better. Changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1811)*

**Comment by AleksueiR** [comment]
Nicely done! :lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1811#-:-KgKLXPjM8jF4wvAmH-Y:b8ggozm)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1811)*

**Pull request merged**
