### PR TITLE
fix(ui): (metadata) expand button needs a tooltip

### LINKED ISSUE #590: bug(ui): (metadata) expand button needs a tooltip
There is no tooltip on the expand button in the metadata panel.

### PR DESCRIPTION
**Pull request by cynngah**
Closes #590

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/637)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/637)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/637)*

**Comment by AleksueiR** [comment]
:lgtm: 

<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> #### bug\(ui\): \(metadata\) expand button needs a tooltip
> 
> Closes #590
> 
> 
> 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/637#-:-KI9D-B7ZBVLmT4RNdsF:980077423)*

**Comment by AleksueiR** [comment]
Just noticed - the commit scope should be `fix`, not `bug` :bug:  :)

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> :lgtm: 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/637#-:-KI9JzePSpN-X4H--XK1:481526799)*

**Comment by cynngah** [comment]
whoops I just copy pasted issue title LOL

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Just noticed - the commit scope should be `fix`, not `bug` :bug:  :)
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/637#-:-KI9KnC9DVjWwcUkZ-J4:-1958846528)*

**Pull request merged**
