### PR TITLE
fix(ui): fix basemap translation

### PR DESCRIPTION
**Pull request by jolevesq**
Translate information in the config file and modify the directives behaviour to act differently when French is detected

Closes 1151

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1168)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/ui/basemap/basemap-item.html, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRTFAQ8KO829H9nFV8c:-KRTFAQ8KO829H9nFV8d:b5eoi3a) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eeceedc2a98797943ae7c5f40496de86f2ecb3c4/src/app/ui/basemap/basemap-item.html#L18)):*
> ```HTML
>         <div class="rv-basemap-footer">
>             <span>
>                 <span class="md-body-2" ng-class="{ 'rv-basemap-name': self.basemap.currentLang !== 'fr-CA' }">{{ self.basemap.name }}</span>
> ```

Since capitalization can be an issue in different languages, I suggest we remove this CSS class altogether. Let the config author be responsible for the proper capitalization.

---

*[src/app/ui/basemap/basemap.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRTCEUQL66r_5sh3kuH:-KRTCEUQL66r_5sh3kuI:b-tjfckw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eeceedc2a98797943ae7c5f40496de86f2ecb3c4/src/app/ui/basemap/basemap.html#L5)):*
> ```HTML
>     <div class="rv-subsection" ng-repeat="projection in self.projections">
> 
>         <div class="rv-subheader">
> ```

This approach will make it harder to support additional languages. It's better to use variable replacement: https://angular-translate.github.io/docs/#/guide/06_variable-replacement

Add a new string to the translations where position of the projection name varies based on language:
`Projection title,basemap.projection.title,{{title}} Maps, Cartes {{title}}`

Use it in the template:
`<h3 class="md-title" >{{ basemap.projection.name | translate:projection }}</h3>`

`projection` object has a 'title' property which will be used as a substitution for the translation string.

---

*[src/content/styles/modules/_basemap.scss, line 72 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRTE7Uc9hkPYxf6LRid:-KRTE7Uc9hkPYxf6LRie:b-micfxe) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eeceedc2a98797943ae7c5f40496de86f2ecb3c4/src/content/styles/modules/_basemap.scss#L72)):*
> ```SCSS
>                 display: none;
>                 font-size: 12px;
>                 overflow: scroll;
> ```

I agree that descriptions are cut off and not completely visible, but I think adding scrollbars to that tiny container is not a good solution. We need to come up with something better.

Can you reverse this change and make an issue to address this separately?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/basemap/basemap-item.html, line 18 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRTFAQ8KO829H9nFV8c:-KRYz1FZaJYw71U2Hgy1:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8f0518ed446a71ee9cfee7dc6574270413f20c74/src/app/ui/basemap/basemap-item.html#L18)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Since capitalization can be an issue in different languages, I suggest we remove this CSS class altogether. Let the config author be responsible for the proper capitalization.
</details>
Done.

---

*[src/app/ui/basemap/basemap.html, line 5 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRTCEUQL66r_5sh3kuH:-KRYtvOiztQmBc3RyRyO:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8f0518ed446a71ee9cfee7dc6574270413f20c74/src/app/ui/basemap/basemap.html#L5)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This approach will make it harder to support additional languages. It's better to use variable replacement: https://angular-translate.github.io/docs/#/guide/06_variable-replacement
> 
> Add a new string to the translations where position of the projection name varies based on language:
> `Projection title,basemap.projection.title,{{title}} Maps, Cartes {{title}}`
> 
> Use it in the template:
> `<h3 class="md-title" >{{ basemap.projection.name | translate:projection }}</h3>`
> 
> `projection` object has a 'title' property which will be used as a substitution for the translation string.
</details>
Done.

---

*[src/content/styles/modules/_basemap.scss, line 72 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRTE7Uc9hkPYxf6LRid:-KRYlTWnM9xyUdUwlTZ_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8f0518ed446a71ee9cfee7dc6574270413f20c74/src/content/styles/modules/_basemap.scss#L72)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I agree that descriptions are cut off and not completely visible, but I think adding scrollbars to that tiny container is not a good solution. We need to come up with something better.
> 
> Can you reverse this change and make an issue to address this separately?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.service.js, line 129 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRZ173reVZoe_0-33fa:-KRZ173s2b846LK7B50i:b-h8owsc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/135c4ff38540ff474a61f9ff1871a7ca8a00c940/src/app/ui/basemap/basemap.service.js#L129)):*
> ```JavaScript
>                 wkid: p.basemaps[0].wkid,
>                 selected: false,
>                 currentLang: configService.currentLang() // no capitalize in French
> ```

I don't think we need this anymore - it's not used anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-:-KRZ1DecKHpQqyTmcxX7:bnfp4nl)*

**Comment by jolevesq** [comment]
Review status: 9 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/basemap/basemap.service.js, line 129 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-KRZ173reVZoe_0-33fa:-KRZ6YzpaNftGekHhi6j:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/135c4ff38540ff474a61f9ff1871a7ca8a00c940/src/app/ui/basemap/basemap.service.js#L129)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I don't think we need this anymore - it's not used anywhere.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168)*

**Comment by AleksueiR** [comment]
I think part of your next PR got mixed in here.

---

Reviewed 1 of 4 files at r3.
Review status: 9 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-:-KRZ6tmI-6HxVSxoahTx:b-y0syj0)*

**Comment by jolevesq** [comment]
It happend when I create a new file in my other branch. I don't know why the new file have been transferred to this branch?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-:-KRZ9-8-Vhh0MDlboLeE:b-u6ehf6)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168#-:-KRZCwFRf9-awc-v7E5D:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1168)*

**Pull request merged**
