### PR TITLE
bug(ui): expand basemap description under title 

### PR DESCRIPTION
**Pull request by milesap**
Replaces tooltip with a div element that appears over basemap on mouse hover.

Closes #583

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/584)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/basemap/basemap-item.html, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHPzjAL6_5eW8Yf0bSb:-KHPzjAL6_5eW8Yf0bSc:-970105966) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6fe8dada56d037f0e69553e0bd1e0e18f80e6a81/src/app/ui/basemap/basemap-item.html#L24)):*
> ```HTML
>             <md-icon class="rv-basemap-check" md-svg-src="navigation:check" ng-if="self.basemap.selected"></md-icon>
>         </div>
>         
> ```

extra whitespace

---

*[src/content/styles/modules/_basemap.scss, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHPzuRPM1TNDRx_HdZk:-KHPzuRPM1TNDRx_HdZl:-1146967742) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6fe8dada56d037f0e69553e0bd1e0e18f80e6a81/src/content/styles/modules/_basemap.scss#L47)):*
> ```SCSS
>                     margin-top: $list-item-gap;
>                 }
>                 
> ```

whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584)*

**Comment by milesap** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/basemap/basemap-item.html, line 24 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHPzjAL6_5eW8Yf0bSb:-KHUP2mONt4HCSuDaFlI:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6fe8dada56d037f0e69553e0bd1e0e18f80e6a81/src/app/ui/basemap/basemap-item.html#L24)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> extra whitespace</details>
complete

---

*[src/content/styles/modules/_basemap.scss, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHPzuRPM1TNDRx_HdZk:-KHUP4ltz51bZycVM--F:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6fe8dada56d037f0e69553e0bd1e0e18f80e6a81/src/content/styles/modules/_basemap.scss#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> whitespace</details>
complete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/content/styles/modules/_basemap.scss, line 6 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHUcJE9WkaWTKTPg3HD:-KHUcJE9WkaWTKTPg3HE:-1507112527) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8d9ad28b853338f80683426a304f244f04c6376/src/content/styles/modules/_basemap.scss#L6)):*
> ```SCSS
>     ul.rv-basemap-list {
>         > li {
>             margin-bottom: 22px;
> ```

Please, use `rem` function for sizes instead of pixels. `rem` multiplies a base size (defaults to 10px) by its argument. `rem(2.2) -> 22px`.
This is handy if we want to scale the whole application up or down.

---

*[src/content/styles/modules/_basemap.scss, line 69 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHUjlcU5b-4q3_D4DLV:-KHUjlcU5b-4q3_D4DLW:-1317977548) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8d9ad28b853338f80683426a304f244f04c6376/src/content/styles/modules/_basemap.scss#L69)):*
> ```SCSS
>                 height: 78px;
>                 white-space: normal;
>                 line-height: 14px;
> ```

I would change some stuff here although it will only allow for four-line descriptions:
```css
                text-transform: none; // keeps text from being uppercase
                padding: rem(0.5) rem(1); // nice padding around description
                text-align: left; 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584)*

**Comment by milesap** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_basemap.scss, line 6 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHUcJE9WkaWTKTPg3HD:-KHVKPEHxc9zY2SMtTNF:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8d9ad28b853338f80683426a304f244f04c6376/src/content/styles/modules/_basemap.scss#L6)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Please, use `rem` function for sizes instead of pixels. `rem` multiplies a base size (defaults to 10px) by its argument. `rem(2.2) -> 22px`.
> This is handy if we want to scale the whole application up or down.</details>
complete

---

*[src/content/styles/modules/_basemap.scss, line 69 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584#-KHUjlcU5b-4q3_D4DLV:-KHVKQdCUoMpXYaNKDRm:-472701157) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e8d9ad28b853338f80683426a304f244f04c6376/src/content/styles/modules/_basemap.scss#L69)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I would change some stuff here although it will only allow for four-line descriptions:
> ```css
>                 text-transform: none; // keeps text from being uppercase
>                 padding: rem(0.5) rem(1); // nice padding around description
>                 text-align: left; 
> ```</details>
added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584)*

**Comment by cynngah** [comment]
Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/584)*

**Pull request merged**
