### PR TITLE
Remove hardcoded metadata

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Also rejects datapromise on error to stop metadata progress bar animation.

## Testing
Nope.

## Documentation
Nope.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ not needed
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1890)

### CODE REVIEW

**Comment by alyec** [comment]
:lgtm: but haven't checked thoroughly as there's still clean up from geo refactor

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/metadata.service.js, line 103 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1893#-KkVx7kiQKGjwQIpphqv:-KkVx7kiQKGjwQIpphqw:b-kaa9be) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c323c87a76fe95f27a4d5dbe0417b48c17f1458c/src/app/geo/metadata.service.js#L103)):*
> ```JavaScript
>                 .then(response => response.data)
>                 .catch(error => {
>                     console.error('Metadata XHR request failed.');
> ```

Should we start migrating to the new logger or leave that to a separate PR for now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1893#-:-KkVxOqDnYsP2L0B3d5u:b31aa3y)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/metadata.service.js, line 103 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1893#-KkVx7kiQKGjwQIpphqv:-KkVxjYXQHEvyNRgP-qj:bbatgpo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c323c87a76fe95f27a4d5dbe0417b48c17f1458c/src/app/geo/metadata.service.js#L103)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Should we start migrating to the new logger or leave that to a separate PR for now?
</blockquote></details>

Yes, but I still don't know how the new logger works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1893)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1893)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1893)*

**Pull request merged**
