### PR TITLE
State Manager Switch

### PR DESCRIPTION
**Pull request by spencerwahl**
Switches the whole UI over to the new state manager. Affects a lot of files but almost all of the changes are small.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/93)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/layer-group-toggle.directive.js, line 21 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93#-K5CUhxOW44LaVSnX3eK:-K5CUhxOW44LaVSnX3eL:2058900056) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53611931a0fcaec6ded214d7ad83943855974a01/src/app/ui/toc/layer-group-toggle.directive.js#L21)):*
Why do we need tocController here? I don't see it's being used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93)*

**Comment by james-rae** [comment]
Reviewed 19 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/layer-group-toggle.directive.js, line 21 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93#-K5CUhxOW44LaVSnX3eK:-K5CYGc4IWEPjVrEe5JH:-2125938140) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53611931a0fcaec6ded214d7ad83943855974a01/src/app/ui/toc/layer-group-toggle.directive.js#L21)):*
This used to be `require: '^ngController'`, I must have changed it without actually checking if it was still needed... whoops

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93)*

**Comment by cynngah** [comment]
Reviewed 19 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93)*

**Comment by AleksueiR** [comment]
Reviewed 19 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/toc/layer-group-toggle.directive.spec.js, line 8 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93#-K5G-SAgvWJ8TXoZ8hI5:-K5G-SAgvWJ8TXoZ8hI6:715296297) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dba400b8aa8f33944244c27225cd741c371f93aa/src/app/ui/toc/layer-group-toggle.directive.spec.js#L8)):*
Then you don't need to mock `rvToc` here as it's no longer required by the directive.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93)*

**Comment by spencerwahl** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/layer-group-toggle.directive.spec.js, line 8 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93#-K5G-SAgvWJ8TXoZ8hI5:-K5GXq_yVDQL85EuP5nU:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/dba400b8aa8f33944244c27225cd741c371f93aa/src/app/ui/toc/layer-group-toggle.directive.spec.js#L8)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/93)*

**Pull request merged**
