### PR TITLE
feat(PR checklist): add additional check and muffin threat

### LINKED ISSUE #1804: Update PR template with a new check item
Add the following line to the PR checklist:

- [x] original issue is updated with the final solution, expected behaviour, and any additional notes for testers

This is needed to let people who mostly read Github issues of any important changes/decisions arrived at in PR/Reviewable comments.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1804

## Testing
No

## Documentation
No

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~ internal change
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1812)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1812#-:-KgKh6ycsC0CXE_Ead51:bnfp4nl)*

**Comment by alyec** [comment]
Maybe we should change the way we handle checklists since the icons don't show in reviewable?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1812#-:-KgKhJTVzr1A2ZBuhRyn:b-7rcpkb)*

**Comment by milesap** [comment]
I always merge directly in Github, but if you merge on reviewable you may just have to quickly verify the checklist there before you merge.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1812#-:-KgKlDA7Gzs0uAe95MU9:bntmh6q)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1812)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1812#-:-KgZz1gBfQUznmCJpreI:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1812)*

**Pull request merged**
