### PR TITLE
Scale Zoom Flags not working for Dynamics with Children

### PR DESCRIPTION
**Pull request by cynngah**
#783

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/872)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend-entry.service.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872#-KMVDtKjgzRUUVNg2euG:-KMVDtKjgzRUUVNg2euH:1163057563) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4fee7166a2ed68042980e03ad3ec41464e352150/src/app/geo/legend-entry.service.js#L96)):*
> ```JavaScript
>             obj.setLayerScaleFlag = (scaleSet) => {
> 
>                 if (obj.layerType !== 'esriDynamic') {
> ```

Please use a constant from Geo instead of 'esriDynamic'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872)*

**Comment by cynngah** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend-entry.service.js, line 96 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872#-KMVDtKjgzRUUVNg2euG:-KMVJchTit1Vk-AO7FAi:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4fee7166a2ed68042980e03ad3ec41464e352150/src/app/geo/legend-entry.service.js#L96)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Please use a constant from Geo instead of 'esriDynamic'
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872#-:-KMVKVr-MuAFw0H1tq8R:1417088721)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/872)*

**Pull request merged**
