### PR TITLE
ESRI CSS Fix

### PR DESCRIPTION
**Pull request by alyec**
## Description

Addresses #1940 and also the webpack stuff.  The fixes are small so I pushed them together in one PR.

## Testing

Polyfill and CSS related, lots of testing directly on IE

## Documentation

Updated a CSS comment.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- release notes have been updated (fixes unreleased bug)
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1957)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm: Loads in IE! :+1: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 80 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmD8kql5_evsD5PXs9Z:-KmD8kql5_evsD5PXs9_:b-e9r8p5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/package.json#L80)):*
> ```JSON
>   "scripts": {
>     "build": "webpack",
>     "serve": "webpack-dev-server --progress --hot --inline",
> ```

What does `progress` do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-:-KmD9AMxFwuR_F6_hLBj:b-obpdvy)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 80 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmD8kql5_evsD5PXs9Z:-KmD9MM_26nivY4ci0Uy:b-75k64) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/package.json#L80)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

What does `progress` do?
</blockquote></details>

Shows the build progress on the console.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 80 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmD8kql5_evsD5PXs9Z:-KmD9i0EJVLMqgqHJOAi:bzgz7hr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/package.json#L80)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Shows the build progress on the console.
</blockquote></details>

Ok, I thought it was already outputting stuff to the console.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 80 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmD8kql5_evsD5PXs9Z:-KmDA6JqvorEZCgwcJtM:bp8srr2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/package.json#L80)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Ok, I thought it was already outputting stuff to the console.
</blockquote></details>

Seems to only do that once it's done.  At least for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by james-rae** [comment]
Not sure if this means we can't use any ESRI API less than 3.15, but if so we should document that, or do a warning check

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-:-KmDAH7tv_oBFcWtudwZ:b-bk67pg)*

**Comment by alyec** [comment]
Alex and I were discussing this a bit.  It's possible to have both selectors active so the old style container names are supported.  I would say we do that instead of a warning if we want to keep support for < 3.15 JSAPI.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-:-KmDAmbZ2GPU3I_jDpcv:b-ab9u2u)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 80 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmD8kql5_evsD5PXs9Z:-KmDBTlQ3wSJONVA2lic:b-aorbub) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/package.json#L80)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Seems to only do that once it's done.  At least for me.
</blockquote></details>

Doesn't hurt anyway. :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[webpack.common.js, line 119 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmQrETdVlZhPtc_OjhA:-KmQrETdVlZhPtc_OjhB:bywng5f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/webpack.common.js#L119)):*
> ```JavaScript
>             host: '0.0.0.0',
>             publicPath: '/',
>             historyApiFallback: {
> ```

So are directory listings shown with `historyApiFallback` defined? Everything else looks good :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[webpack.common.js, line 119 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmQrETdVlZhPtc_OjhA:-KmROALCk1qFMUNR9l4I:b-wf9v2o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/webpack.common.js#L119)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

So are directory listings shown with `historyApiFallback` defined? Everything else looks good :+1: 
</blockquote></details>

Yes, plenty of hacks involved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[webpack.common.js, line 119 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957#-KmQrETdVlZhPtc_OjhA:-KmRgZEgceniyly8F3dc:b-s8f4kp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/459f9d5f2da11c5db484496d1384f344390e2cc3/webpack.common.js#L119)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Yes, plenty of hacks involved.
</blockquote></details>

@milesap good to merge?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1957)*

**Pull request merged**
