### PR TITLE
fix(ui): fix keyboard identify tooltip position

### LINKED ISSUE #2809: Keyboard identify crosshairs tooltip is sometimes misaligned
### Problem
The tooltips is not properly positioned. So far this was noticed only in the CCCS build.
This happens because the size of the crosshairs image is taken into account when positioning the tooltip and sometimes the image doesn't load fast enough return the default icon size of 24x24.

### Solution
Deffer getting the dimensions of the crossharis image until the first extent change cause by the keyboard navigation.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
The crosshairs image does not load quick enough and its size is returned as 24x24 pixels. Deffer getting the dimensions until the first keyboard-caused extent change.

Closes #2809

## Testing
:eye: 

## Documentation
Inline comments.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Inline comments are added
~~- [ ] Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae and @JahidAhmed)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @AleksueiR)

---

*[src/app/ui/common/crosshairs.directive.js, line 27 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810#-LFwKr-I0bxlmuhquUv9:-LFwKr-I0bxlmuhquUvA:b7n3x90) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ea55ae4851b7b365bda4723f05d83918c620f0/src/app/ui/common/crosshairs.directive.js#L27)):*
> ```JavaScript
> 
>         const targetElement = element.find('.rv-target');
>         
> ```

evil spaces

---

*[src/app/ui/common/crosshairs.directive.js, line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810#-LFwLC_c5a4uGj3VHkR5:-LFwLC_c5a4uGj3VHkR6:b-vg34ny) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ea55ae4851b7b365bda4723f05d83918c620f0/src/app/ui/common/crosshairs.directive.js#L30)):*
> ```JavaScript
>         // the size of the crosshairs element will be 24x24 until its svg image is rendered
>         // deffer getting the crosshairs dimensions
>         let targetElmWidth, targetElmHeight;
> ```

i believe our style guide is one var per declaration?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @james-rae)

---

*[src/app/ui/common/crosshairs.directive.js, line 27 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810#-LFwKr-I0bxlmuhquUv9:-LFwLmhQ6q9uFADzRAQ2:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ea55ae4851b7b365bda4723f05d83918c620f0/src/app/ui/common/crosshairs.directive.js#L27)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

evil spaces
</blockquote></details>

Done.

---

*[src/app/ui/common/crosshairs.directive.js, line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810#-LFwLC_c5a4uGj3VHkR5:-LFwLmx9-v5o4NfQJTFx:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08ea55ae4851b7b365bda4723f05d83918c620f0/src/app/ui/common/crosshairs.directive.js#L30)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

i believe our style guide is one var per declaration?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)*

**Pull request merged**
