### PR TITLE
Remove error message when closing the data table from its own layer entry

### PR DESCRIPTION
**Pull request by barryytm**
## Description

As title
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2292
## Testing

Manually 
## Documentation

NA
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2310)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
:lgtm: you can remove the comment also for the line you changed, I don't think it applies now

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310#-:-KrBkgcnaqsC3R-GMMTW:b-zed3ww)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/displaymanager.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310#-KrC-YNUHDtc77b5dzEU:-KrC-YNUHDtc77b5dzEV:b-7vn7fy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a298747206c285d59f75d68d29aa94963c42c93c/src/app/core/displaymanager.service.js#L87)):*
> ```JavaScript
>             stateManager.setActive(panelName); // just close the panel
> 
>             return $q.resolve(); // display for this panel is not defined, exit
> ```

Even though this likely works, it should remain as `reject` for completeness since the panel did not open successfully (it was already opened by the same requester so this request is ignored). You should instead catch the rejected promise where applicable and/or `try/catch` it if that fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/core/displaymanager.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310#-KrC-YNUHDtc77b5dzEU:-KrC1Q5vUXGwU_Tuh_OB:blm7v6i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a298747206c285d59f75d68d29aa94963c42c93c/src/app/core/displaymanager.service.js#L87)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Even though this likely works, it should remain as `reject` for completeness since the panel did not open successfully (it was already opened by the same requester so this request is ignored). You should instead catch the rejected promise where applicable and/or `try/catch` it if that fails.
</blockquote></details>

Sorry, scratch the last part... try this instead:

`return stateManager.setActive(panelName);`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/displaymanager.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310#-KrC-YNUHDtc77b5dzEU:-KrCC7iS9QeppIekfL6m:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e03df5503c0f9bb5a06393462cfd46e67b310d3e/src/app/core/displaymanager.service.js#L87)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Sorry, scratch the last part... try this instead:

`return stateManager.setActive(panelName);`
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310)*

**Comment by milesap** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310#-:-KrCDeciWOTdL7zRpx-Y:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2310)*

**Pull request merged**
