### PR TITLE
fix(ui): re-enable custom key bindings

### LINKED ISSUE #2022: Custom map key bindings broken/missing
Some time ago we disabled ESRI map bindings with our own implementation since ESRI requires a mouse to hover over the map in order to pan. It seems ESRI key bindings are being used again.

Also, when using arrows to pan, error is thrown:
> Uncaught TypeError: Cannot read property 'extent' of undefined

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2022, #2072

## Testing
:eyes: and :keyboard: 

## Documentation
None

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2079)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2079)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/init-map.directive.js, line 49 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2079#-Knp7PlPhpFb8GL5irDR:-Knp7PlPhpFb8GL5irDS:bkx9opi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f7d520458892b28b69a395943096c4e618004481/src/app/geo/init-map.directive.js#L49)):*
> ```JavaScript
>             mapInstance.mapDefault('panRate', 0);
> 
>             el.on('keydown', keyDownHandler);
> ```

I think you need to remove these listeners every time the map is destroyed, or just remove them before setting new ones, otherwise they will pile up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2079)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2079)*

**Comment by milesap** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/init-map.directive.js, line 49 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2079#-Knp7PlPhpFb8GL5irDR:-KnseIQaqGXU8A5qmvyd:bmeyrxb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f7d520458892b28b69a395943096c4e618004481/src/app/geo/init-map.directive.js#L49)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think you need to remove these listeners every time the map is destroyed, or just remove them before setting new ones, otherwise they will pile up.
</blockquote></details>

:+1:  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2079)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2079)*

**Pull request merged**
