### PR TITLE
State Manager cleanup

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/94)

### CODE REVIEW

**Comment by AleksueiR** [comment]
The best PR ever! Can be merged right away, I think :lgtm_strong: 

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/94#-:-K5GkbTwsh9e48rX0Mup:-242126317)*

**Comment by james-rae** [comment]
Reviewed 17 of 17 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/94)*

**Comment by AleksueiR** [comment]
:+1: 

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/94#-:-K5GvVx08c-2nLtTwE8C:-510466975)*

**Comment by cynngah** [comment]
Reviewed 15 of 17 files at r1, 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/94)*

**Pull request merged**
