### PR TITLE
fix(geo): throw error so faulty import dont silently fail

### PR DESCRIPTION
**Pull request by cynngah**
#933

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1007)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Comment by AleksueiR** [comment]
[Demo](http://fgpv.cloudapp.net/demo/users/cynngah/useraddedfails/samples/index-one.html)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-record.class.js, line 103 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007#-KOFl9fVHBLHJv02UDZT:-KOFl9fVHBLHJv02UDZU:599672863) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6962d53f333af11dced2e0134967cc4b83b53ac4/src/app/geo/layer-record.class.js#L103)):*
> ```JavaScript
>                 console.warn(e);
>                 this._stateChange(Geo.Layer.States.ERROR);
>                 throw new Error(`Layer error: ${e}`);
> ```

I don't think this is the right place to throw an error.  A layer being in an error state is valid as part of our state diagram.  It's probably better for the calling code to attach a listener for the `ERROR` state and display a message / handle the error accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/loader/loader-file.directive.js, line 350 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007#-KOFrVXtgqT3jM00woIi:-KOFrVXtgqT3jM00woIj:591325113) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6962d53f333af11dced2e0134967cc4b83b53ac4/src/app/ui/loader/loader-file.directive.js#L350)):*
> ```JavaScript
>         function configureOnContinue() {
>             // this check is performed because file validation happens for other file types in the select step
>             if (self.layerBlueprint.fileType === 'csv') {
> ```

I think this condition can be dropped to check if `generateLayer` throws an error for all file types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Comment by cynngah** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/loader/loader-file.directive.js, line 350 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007#-KOFrVXtgqT3jM00woIi:-KOL5lfHX09Ap15PXX-5:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6962d53f333af11dced2e0134967cc4b83b53ac4/src/app/ui/loader/loader-file.directive.js#L350)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I think this condition can be dropped to check if `generateLayer` throws an error for all file types.
</details>
Done.

---

*[src/app/geo/layer-record.class.js, line 103 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007#-KOFl9fVHBLHJv02UDZT:-KOL5ndmhp2LbfTyVg2r:-964234114) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6962d53f333af11dced2e0134967cc4b83b53ac4/src/app/geo/layer-record.class.js#L103)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I don't think this is the right place to throw an error.  A layer being in an error state is valid as part of our state diagram.  It's probably better for the calling code to attach a listener for the `ERROR` state and display a message / handle the error accordingly.
</details>
Seems like I don't even need the throw anymore ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007#-:-KOL64R4mxbJPeHqMyPf:1417088721)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 4 files at r3, 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1007)*

**Pull request merged**
