### PR TITLE
Style change: indenting first ten levels in layer selector

### PR DESCRIPTION
**Pull request by AleksueiR**
adds "null" as a return value to shut up jshint;
adds crazy nested layer group sample;

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/247)

### CODE REVIEW

**Comment by cynngah** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/geo/geo.service.js, line 201 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247#-K92gWJ8ZA-8onHXi09x:-K92gWJ8ZA-8onHXi09y:1895679991) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e674463058c6cbb487a089e770dac6a674283afb/src/app/geo/geo.service.js#L201)):*
Doesn't Promise.catch(() => { return null; }) return a Promise which resolves to null?  If not that would make .then and .catch inconsistent which would be pretty odd.

---

*[src/app/ui/toc/toc.service.js, line 23 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247#-K92h0quVxogzOZifeV1:-K92h0quVxogzOZifeV2:572034356) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e674463058c6cbb487a089e770dac6a674283afb/src/app/ui/toc/toc.service.js#L23)):*
enable this after the sample config is declared?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 201 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247#-K92gWJ8ZA-8onHXi09x:-K92iqnoU5KoKDWl_MXt:686405997) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e674463058c6cbb487a089e770dac6a674283afb/src/app/geo/geo.service.js#L201)):*
It does, but my style checker keeps complaining the return value is wrong. Is it better to add an jscs/jshint exception to this function?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/toc.service.js, line 23 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247#-K92h0quVxogzOZifeV1:-K92lL7dsVtLacj5Vm2E:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e674463058c6cbb487a089e770dac6a674283afb/src/app/ui/toc/toc.service.js#L23)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 201 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247#-K92gWJ8ZA-8onHXi09x:-K92l_cif6F9Tkneb21N:1605499159) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e674463058c6cbb487a089e770dac6a674283afb/src/app/geo/geo.service.js#L201)):*
Yes.  Exceptions in the checker are better than misleading docs IMO.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 201 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247#-K92gWJ8ZA-8onHXi09x:-K92lpouWEDMUMPWsHkZ:-1777103967) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e674463058c6cbb487a089e770dac6a674283afb/src/app/geo/geo.service.js#L201)):*
If removing the arrow function helps that's also an option.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 201 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247#-K92gWJ8ZA-8onHXi09x:-K92p6BNCc5QcNO8Kbfx:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e674463058c6cbb487a089e770dac6a674283afb/src/app/geo/geo.service.js#L201)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/247)*

**Pull request merged**
