### PR TITLE
fix(table): repair filter (searchable and default value for selector …

### LINKED ISSUE #2685: Table fields/filters problems
The searchable option to restrict remove filter from a field doesn't work. We can't set a value by default for a filter of type selector.

### PR DESCRIPTION
**Pull request by jolevesq**
…filter type)

Closes #2685

## Description

Repair searchable properties for columns so if it is false, filter will not be created. Repair the default selector filter type value.
  
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/ui/table/table-default.directive.js, line 554 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686#-LBN2AYrEp2KsrGwr_4P:-LBN2AYrEp2KsrGwr_4Q:bbt12rr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/61a54da659415cb85a1041c8d26a86465a3d64e6/src/app/ui/table/table-default.directive.js#L554)):*
> ```JavaScript
>                         // set searchable (if false, data is there but not part of the filtering)
>                         column.searchable = (typeof configCol.searchable === 'undefined') || configCol.searchable ?
>                             true : false;
> ```

i think you can get rid of the whole `?` operator part.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/table/table-default.directive.js, line 554 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686#-LBN2AYrEp2KsrGwr_4P:-LBQgl0PAb8hAVHO5HI1:boavpo0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/61a54da659415cb85a1041c8d26a86465a3d64e6/src/app/ui/table/table-default.directive.js#L554)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

i think you can get rid of the whole `?` operator part.
</blockquote></details>

If it is undefined, will it set it to false by default?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686)*

**Comment by james-rae** [comment]
*[src/app/ui/table/table-default.directive.js, line 554 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686#-LBN2AYrEp2KsrGwr_4P:-LBROXmY2hJmiIOYZIov:b-dnvta6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/61a54da659415cb85a1041c8d26a86465a3d64e6/src/app/ui/table/table-default.directive.js#L554)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If it is undefined, will it set it to false by default?
</blockquote></details>

it looks like you're already handling the undefined case with the `typeof` check.
If I'm reading it right, `(typeof configCol.searchable === 'undefined') || configCol.searchable` evaluates to `true` or `false`.  So no need to use `? true : false` 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686)*

**Comment by jolevesq** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/table/table-default.directive.js, line 554 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686#-LBN2AYrEp2KsrGwr_4P:-LBVkbX57GqaE3sdA8gN:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/61a54da659415cb85a1041c8d26a86465a3d64e6/src/app/ui/table/table-default.directive.js#L554)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

it looks like you're already handling the undefined case with the `typeof` check.
If I'm reading it right, `(typeof configCol.searchable === 'undefined') || configCol.searchable` evaluates to `true` or `false`.  So no need to use `? true : false` 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2686)*

**Pull request merged**
