### PR TITLE
Fixes and enhancements for legend entry symbology stack

### LINKED ISSUE #760: Fixes and enhancements for legend entry symbology stack
##### 1. Notice the missing gap between the last symbology icon and the next legend entry:

| Expected (as in v0.14)  | Right now  |
|---|---|
|   |   |

##### 2. Only wms symbology items need to be enlarged when expanding the stack (notice how the default symbology image on the right):

| Expected (as in v0.14)  | Right now  |
|---|---|
|   |   |

##### 3. Animation expanding wms symbology items starts too soon, and expanding images overlap the name of the layer and the name of its own symbology item. 
expanding_wms
This expanding animation should start later, after items moved down sufficiently to not overlap the legend entry.

##### 5. Change how wms symbology labels are displayed.

Display label underneath the image but insde the floating image container:

If the label is too long, expand the floating container to accomodate it:

Let the label wrap:

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #760 and #745.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/844)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 137 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSN1wSRSF2__D-Cnpf:-KLSN1wSRSF2__D-Cnpg:-915001225) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L137)):*
> ```JavaScript
>                     trigger = element.find(RV_SYMBOLOGY_ITEM_TRIGGER);
> 
>                     // calculate maximum with of a symbology item based on image, label size and the main panel width
> ```

typo: width

---

*[src/app/ui/toc/entry-symbology.directive.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSN6DRAJaJuaaJJLrv:-KLSN6DRAJaJuaaJJLrw:-2089971788) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L138)):*
> ```JavaScript
> 
>                     // calculate maximum with of a symbology item based on image, label size and the main panel width
>                     // symbology item cannot be wider than the panel
> ```

scroll bars for everyone

---

*[src/app/ui/toc/entry-symbology.directive.js, line 193 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLRRb7Gb_vWzS2hFEAq:-KLRRb7Gb_vWzS2hFEAr:1406458141) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L193)):*
> ```JavaScript
>                             index === symbologyItems.length - 1));
> 
>                     totalHeight += symbologyListMargin; // add marging at the bottom of the list
> ```

typo: margin

---

*[src/app/ui/toc/entry-symbology.directive.js, line 242 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSNRJbz_cHO9WAHzit:-KLSNRJbz_cHO9WAHziu:1453403832) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L242)):*
> ```JavaScript
>                  * @param  {Number}  totalHeight   height of the legend stack so far
>                  * @param  {Boolean} isLast        flag indicating this is the last item in the stack
>                  * @return {Nimber}                height of this symbology item plus its bottom margin is applicable
> ```

typo: number

---

*[src/app/ui/toc/entry-symbology.directive.js, line 302 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSNhxPJ14f0hgBTMBr:-KLSNhxPJ14f0hgBTMBs:1368616389) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L302)):*
> ```JavaScript
>                  * @param  {Number}  totalHeight   height of the legend stack so far
>                  * @param  {Boolean} isLast        flag indicating this is the last item in the stack
>                  * @return {Nimber}                height of this symbology item plus its bottom margin is applicable
> ```

Nimber returns

---

*[src/app/ui/toc/entry-symbology.directive.js, line 354 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSNr4YoFmAH54I8f01:-KLSNr4YoFmAH54I8f02:1376586168) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L354)):*
> ```JavaScript
>                  * @param  {Object} canvas cached canvas node
>                  * @param  {String} text   string of text to measure
>                  * @param  {String} font   text font and size
> ```

Since this is structured text can you explain or link to how it should be structured?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844)*

**Comment by AleksueiR** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 137 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSN1wSRSF2__D-Cnpf:-KLW9uPT5w1s6XgmtrFy:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L137)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: width
</details>
Done.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSN6DRAJaJuaaJJLrv:-KLW9jKzq1pAAChdZ9J8:-1401698157) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L138)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> scroll bars for everyone
</details>
I object.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 193 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLRRb7Gb_vWzS2hFEAq:-KLW9xbD6NKTbHt4mdzC:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L193)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: margin
</details>
Done.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 242 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSNRJbz_cHO9WAHzit:-KLWA-OsZPlxSPINmqtG:-881942749) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L242)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: number
</details>
Done. :D

---

*[src/app/ui/toc/entry-symbology.directive.js, line 302 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSNhxPJ14f0hgBTMBr:-KLWA0KBaHZkyIbDc4qx:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L302)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Nimber returns
</details>
Done.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 354 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSNr4YoFmAH54I8f01:-KLWH-QKbPGvi7UgxO5Q:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L354)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Since this is structured text can you explain or link to how it should be structured?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844)*

**Comment by AleksueiR** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 354 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844#-KLSNr4YoFmAH54I8f01:-KLWLXP_HThvS7ECvLBW:1097248490) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bb90e82ce70f3ed1dfbeced6274b52259ff96107/src/app/ui/toc/entry-symbology.directive.js#L354)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Done.
</details>
Check out this pen: https://codepen.io/anon/pen/BzRzzW

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/844)*

**Pull request merged**
