### PR TITLE
WCAG: display lat/long coordinates on keyboard movement

### LINKED ISSUE #3921: WCAG: There is a long/lat coordinates provided on the screen to provide the location of the mouse, but this is not provided to the keyboard user
Spawned from #3892.

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #3921

Adds a new event to update map coordinates on map panning using arrow keys (when map is focused). 

[Demo link](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3921-WCAG-keyboard-coords/samples/index-samples.html)

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)

### CODE REVIEW

**Review by milespetrov — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by JahidAhmed — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @JahidAhmed, @james-rae, @milespetrov, @RyanCoulsonCA, and @sharvenp)

___
*[packages/ramp-core/src/app/core/constant.service.js, line 22 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934#-Mbqx6sIDGgrd2GKcN6Q:-MbqzxB06NqpnKW-xhqX:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ce0de7641e3be98e5c906f560ba43ee2c3aaaefa/packages/ramp-core/src/app/core/constant.service.js#L22)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lets remove this dead link and replace with `, see bookmark_formats.md`
</blockquote></details>

Done.

**Review by spencerwahl — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

**Review by james-rae — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
