### PR TITLE
fix(ie): update polyfills to babel standard

### LINKED ISSUE #1516: ReferenceError: 'Symbol' is undefined in IE11
It errors on the line 135388 of the compiled `core.js` which looks like this:
```js

for (var _iterator = Object.entries(service.mapObject.attribution.itemNodes)[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var _step$value = _slicedToArray(_step.value, 1);

    var key = _step$value[0];

    service.mapObject.attribution.itemNodes[key].innerText = cfgAtt.text.value;
}
```

I guess Babel converts [this line here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/map.service.js#L369) into the above and IE [doesn't support](https://camo.githubusercontent.com/9a8ea930b1d871cc949a92a098d0b95e7e1ee958/68747470733a2f2f692e696d6775722e636f6d2f4c704c79556e532e706e67) Symbols.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Removed local and npm polyfills in favor of babel polyfills. This covers
all functionality in ES2015.

Closes #1516

## Testing
In IE, unfortunately 

## Documentation
No

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2033)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Demo loads in IE now.

This will fold all the polyfills into the core file, right? But the whole idea of IE polyfills was to pull them out, reducing the core size  and making the host page load IE polyfills themselves. 

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2033#-:-KnZwybp_-bxcs_BvvPY:b-4r68j2)*

**Comment by milesap** [comment]
babel polyfills continue to reside in `ie-polyfills.js` and are not part of core.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2033#-:-KnZxmiBgbtH5WMzQ7xS:b-nmptiz)*

**Comment by AleksueiR** [comment]
Ah, right missed that one line :+1: :lgtm: 
To bad we can't get rid of the svg polyfill.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2033#-:-KnZyaAi7xFbguh1MWr_:bno2ae7)*

**Comment by milesap** [comment]
Some good news for ie users, polyfills down from 686kb to 170kb :+1: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2033#-:-KnZzqYSR0jyY3ERL3X8:b2lnaob)*

**Pull request merged**
