### PR TITLE
Bug/basemapclosebug

### PR DESCRIPTION
**Pull request by milesap**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/638)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/mapnav/mapnav.service.js, line 27 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/638#-KI9DRKJpAtveBT7f9eB:-KI9DRKJpAtveBT7f9eC:-1905641113) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/069279eaa2e331c90c8664365d4ce567c3bd2352/src/app/ui/mapnav/mapnav.service.js#L27)):*
> ```JavaScript
>         $rootScope.$on('stateChangeStart', (evt, name, prop, value) => {
>             if (name === 'other' && prop === 'active') {
>                 let newMode = value ? 'basemap' : 'default';
> ```

const (this could even be inlined since it isn't used elsewhere)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/638)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/mapnav/mapnav.service.js, line 27 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/638#-KI9DRKJpAtveBT7f9eB:-KICvBEyG8EjowbPmTGQ:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/069279eaa2e331c90c8664365d4ce567c3bd2352/src/app/ui/mapnav/mapnav.service.js#L27)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> const (this could even be inlined since it isn't used elsewhere)
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/638)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/638)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/638)*

**Comment by mweech** [comment]
closed #139

**Pull request merged**
