### PR TITLE
WCAG updates to side panel (hamburger) behavior 

### LINKED ISSUE #3918: WCAG: Hamburger menu stays open if an item is activated with mouse but closes if a keyboard is used
Spawned from #3892.

"Hamburger menu stays open if an item is activated with mouse but closes if a keyboard is used. With mouse, sometimes it stays open sometimes it stays closed.

Leave the side panel open until the user dismisses it with "close" or perhaps an OK button. If a button on the side panel opens a dialog, then the normal behavior is to return the user to the button that launched the dialog when the dialog is closed. An example would be the export button which opens a dialog box and closes the side menu, but doesn't return the user back to the export button when the dialog is closed. A more natural behavior would be to leave the side panel open when launching the dialog (it can be greyed out with the rest of the background.) Then return the user to the export button when the dialog is closed."

### PR DESCRIPTION
**Pull request by milespetrov**
- The side panel now remains open whenever an item is activated (mouse or keyboard navigation)
- Focus returns to the button that activated a popup like export/share and the basemap selector
- Fixed keyboard navigation issue in the basemap side panel where focus could not return to the close button
- Code is linted
- When switching languages, focus moves to the side panel close button. This is caused by those buttons being destroyed and focus manager moving the focus before they are re-created. It _could_ be fixed with some timeOut nonsense if its really bothersome, left it for now.

[Demo](http://ramp4-app.azureedge.net/legacy/users/milespetrov/3918-hamburgers/samples/index-samples.html)
Closes #3918

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926)

### CODE REVIEW

**Review by james-rae — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926)* status: all files reviewed, 1 unresolved discussion (waiting on @milespetrov)

___
*[packages/ramp-plugin-coordinate-info/src/index.ts, line 1 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926#-MbNSlB65vrZfeIYnNtR:-MbNSlB65vrZfeIYnNtS:b-94u7zg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67b6049c08676210e4ef94e7c42fdc5d7a478d03/packages/ramp-plugin-coordinate-info/src/index.ts#L1)):*
> ```XML
> import { template, magSection } from "./html-assets";
> ```

is this file formatted correct? We generally nope `"`, right?

**Review by milespetrov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

___
*[packages/ramp-plugin-coordinate-info/src/index.ts, line 1 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926#-MbNSlB65vrZfeIYnNtR:-MbNTrld7UtBCnRqJIkj:b-qtpkzg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67b6049c08676210e4ef94e7c42fdc5d7a478d03/packages/ramp-plugin-coordinate-info/src/index.ts#L1)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

is this file formatted correct? We generally nope `"`, right?
</blockquote></details>

This package doesn't have linting enabled, the prettier config file is in the `ramp-core` package. I've added issue #3927 to get this done.

**Review by james-rae — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @milespetrov)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @milespetrov)

**Review by yileifeng — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @milespetrov)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @milespetrov)

**Pull request merged**
