### PR TITLE
feat(markdown): improve schema to specify folder name for help and about

### LINKED ISSUE #1884: Set help and about file name from config file
For installation where multiple viewer run from the same dist file, we should be able to specidy the about and help markdown file name from the config file. This way we can a specific help for a viewer where we can add information for the custom plugin only available from this viewer.

By default viewer will look for the default name.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1884

## Description

Use configuration file to specify help or about folder name.

## Testing

index-fgp-en use a configured help and index-one use a configured about

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1889)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 93 of 93 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1889)*

**Comment by jolevesq** [comment]
Review status: 44 of 51 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/schema.json, line 853 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1889#-KkM36WAnWuN_XRliPOf:-KkMd4Bn_rOk0rLQ0Xvt:b-ktkahf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/252579a062c4fc190b80238d80b2da5af9c18182/src/schema.json#L853)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

If my understanding is correct about should only be rendered as a string from the config or as a markdown folder, but not both.  This schema allows for:
```js
about: { config: { value: 'random string' }, markdown: { foldername: 'some/folder' } }
```

I think moving the `oneOf` declaration higher will enforce the restriction correctly and might also simplify the schema.  Ex:
```json
"about": {
  "oneOf": [
    { "type": "object", "properties": { "content": { "type": "string" } }, "required": ["content"], "additionalProperties": false },
    { "type": "object", "properties": { "folderName": { "type": "string" } }, "required": ["folderName"], "additionalProperties": false }
  ]
}
```
</blockquote></details>

Thanks for the comment, Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1889)*

**Comment by AleksueiR** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1889)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1889)*

**Comment by alyec** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1889#-:-KkQsolrcvYXkpGq1Nqk:bnfp4nl)*

**Pull request merged**
