### PR TITLE
chore(docs): added initial tutorial documentation from wiki

### PR DESCRIPTION
**Pull request by milesap**
## Description
Adds initial support for JSDoc tutorials instead of using the wiki
- modified docdash theme so that tutorials appear at the top
- tutorial images are now stored on the repo
- included some tutorials - more to follow

## Testing
Works with `npm run doc`

## Documentation
:+1: 

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [ ] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1664)

### CODE REVIEW

**Comment by milesap** [comment]
Removed docbuildmodules folder created in error

---

Review status: 0 of 86 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-:-KcIzHKbeLyLwXkAoeQD:b-qryv4t)*

**Comment by milesap** [comment]
- docdash template moved into own repo
- split index.json config file into multiple files, ~ one per directory

---

Review status: 0 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-:-KcJU5_5iEWFI6YoJrux:bv9yjh5)*

**Comment by AleksueiR** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/developer/architecture_overview.md, line 20 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcNx85DsXpQTF9EWE6k:-KcNx85DsXpQTF9EWE6l:b-vw6i0n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/architecture_overview.md#L20)):*
> ```Markdown
>   - External contributions are welcome
>   - Easy to report issues and suggestions as well as search existing ones
>   - Ability to fork project and take it in your own direction
> ```

@mweech I remember you saying we don't want segmentation of RAMP codebase. Do we want to keep this line about forking the project then?

---

*[docs/developer/getting_started.md, line 51 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcNxW0I4GLCSLXm2erv:-KcNxW0JJNhP7DcnwAfH:b-bn6eh8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/getting_started.md#L51)):*
> ```Markdown
> |`gulp clean`| Removes all files from build folder |
> |`gulp dist`| Generates tgz and zip files for distribution |
> |`gulp sass`|Compile sass files to CSS, add vendor prefixes, and copy to the temp folder.|
> ```

We can drop `gulp sass` and `gulp clean-sass`; I never use them separately and I doubt anyone else does.

---

*[docs/developer/plugins.md, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcO-23LxqM8puLXFlWM:-KcO-23LxqM8puLXFlWN:bkcpsiw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins.md#L89)):*
> ```Markdown
> ```
> 
> Each property of `translations` is a language key. In this example we will have an english and french translation denoted `en-CA` and `fr-CA` respectively. Within each language object we have keys which we'll use to identify the translation string as the value. Confused? Don't be! Watch and learn:
> ```

:crown: 

---

*[docs/developer/plugins/core_plugins.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcO-i4UyS_8YAtMIDiL:-KcO-i4UyS_8YAtMIDiM:b-nowxkn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins/core_plugins.md#L1)):*
> ```Markdown
> Common functionality that many users need are often made into a core plugin. They are created and maintained by us and come bundled with the viewer code. As a result they are available directly via the `RV.Plugins` object and can be used without importing any additional files. Since these types of plugins increase the overall viewer code size, we restrict the number and size of these plugins. Any plugins that don't make it into `core` become [[External Plugins]].
> ```

[[External Plugins]] link doesn't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docs/developer/architecture_overview.md, line 20 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcNx85DsXpQTF9EWE6k:-KcOHpVG3-fWqh8BMp70:b-4y1fci) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/architecture_overview.md#L20)):*
Mike:
> but yeah anything that supports forking the codebase. no.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by jolevesq** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/developer/plugins.md, line 84 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSl7SqOUWVXwJlPA9o:-KcSl7SqOUWVXwJlPA9p:b-1l3e52) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins.md#L84)):*
> ```Markdown
> 
>     'fr-CA': {
>         helloButtonLabel: 'Boujour Monde'
> ```

Bonjour tout le monde

---

*[docs/developer/plugins.md, line 127 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSlZX-tv7HPRu76UnG:-KcSlZX-tv7HPRu76UnH:b-ve8y59) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins.md#L127)):*
> ```Markdown
> ```
> 
> What about translating the alert text? Unfortunately this is not yet possible :-1: 
> ```

If a user pass 2 values of alert text (en-CA and fr-CA) will it be able to detect language when action button is click and show the right text?

---

*[docs/developer/modules/geo.md, line 18 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnChjVXhybKU8jb1e:-KcSnChjVXhybKU8jb1f:b-p9futu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/geo.md#L18)):*
> ```Markdown
> - Lat/Lng coordinates
> - Place or Name
> - FSA or NTS 
> ```

It will also zoom to a specific scale

---

*[docs/developer/modules/ui.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnlrL3qf_NS6bZIdj:-KcSnlrL3qf_NS6bZIdk:b-xhlpy1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/ui.md#L19)):*
> ```Markdown
> - Left side menu
> - Basemap selector
> - Context aware secondary menu (second line only visible when layer list is open)
> ```

@aleksueir, @alyec It is not there yet but do we plan to have a tools button who will open a panel like toc? In this panel we can add plugins one after the other. It will be useful for complex plugin who will not fit the sidemenu.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/developer/modules/ui.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnlrL3qf_NS6bZIdj:-KcSqrebJkfUb5Zq8Trg:b-2uk1g7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/ui.md#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

@aleksueir, @alyec It is not there yet but do we plan to have a tools button who will open a panel like toc? In this panel we can add plugins one after the other. It will be useful for complex plugin who will not fit the sidemenu.
</blockquote></details>

Yes, there are plans to a have a tools panel (area, population, distance, etc. tools), and it will probably be opened directly from the appbar or from the side menu.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/developer/modules/ui.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnlrL3qf_NS6bZIdj:-KcSrh4hcgEYmjCVPUgz:b-njqt1l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/ui.md#L19)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Yes, there are plans to a have a tools panel (area, population, distance, etc. tools), and it will probably be opened directly from the appbar or from the side menu.
</blockquote></details>

Directly from appbar? If you have let say 4-5 plugins, the appbar will have to be wide to show all buttons. When you click on a button it will open a panel like toc panel to show all the controls?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/developer/modules/ui.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnlrL3qf_NS6bZIdj:-KcSsxBDZ4uzBxA8_Y8X:bdl5dlj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/ui.md#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Directly from appbar? If you have let say 4-5 plugins, the appbar will have to be wide to show all buttons. When you click on a button it will open a panel like toc panel to show all the controls?
</blockquote></details>

One extra button on the appbar to open a panel with extra tools/plugins to do not fit (or if the map author doesn't want them there). This is the idea for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/developer/modules/ui.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnlrL3qf_NS6bZIdj:-KcSxk0qJKlkEorAeU_-:bjm10tf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/ui.md#L19)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

One extra button on the appbar to open a panel with extra tools/plugins to do not fit (or if the map author doesn't want them there). This is the idea for now.
</blockquote></details>

Only one extra button whit a panel is what I had in my mind as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by alyec** [comment]
There are a lot of comments in here, but the docs page works so I'm okay with merging this and addressing the comments in a separate pass.

---

Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[docs/developer/app_startup.md, line 5 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTHOWet9HwuZs9JeOs:-KcTHOWet9HwuZs9JeOt:blsc6cp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L5)):*
> ```Markdown
> To load the viewer on a webpage, two things must be present on the host page:
> - A script tag which loads `bootstrap.js`
> - One or more HTML elements having the class `fgpv`
> ```

This changed after you wrote it, but now the preferred initialization is to put `is="rv-map"` on the element.  `class="fgpv"` will be deprecated in #1672

---

*[docs/developer/app_startup.md, line 12 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTHGt1Z3FMTkWJR2l0:-KcTHGt1Z3FMTkWJR2l1:bj9h2tt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L12)):*
> ```Markdown
> - Initializing the external API as `RV`
> - Proxying the map API until it is loaded
> - Injecting the `jQuery` and `datatables` libraries
> ```

if necessary

---

*[docs/developer/app_startup.md, line 14 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTH-bzIXfUk-8PUW8u:-KcTH-c-H2UN37EwOkKR:b-23qgxm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L14)):*
> ```Markdown
> - Injecting the `jQuery` and `datatables` libraries
> - Injecting our compressed and minified `core.js` script and `main.css` stylesheet
> - Browser detection (for IE polyfills, and touch support for some mobile browsers)
> ```

IE polyfills are not loaded by bootstrap.  Since they are big we split them into a separate file and it's up to the host page to either use them or load their own polyfills.  This must be done before bootstrap is called.

---

*[docs/developer/app_startup.md, line 21 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTHdboc74gxbJVRArV:-KcTHdboc74gxbJVRArW:b-woaj7g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L21)):*
> ```Markdown
> ### global-registry.js
> 
> This file serves two purposes:
> ```

If this is on the developer side you may also want to include a note that this is how interaction with `window.RV` should be managed

---

*[docs/developer/modules/core.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTK4KXPzGuxH0B_BMG:-KcTK4KXPzGuxH0B_BMH:bpgglne) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/core.md#L1)):*
> ```Markdown
> The core module is intended for **viewer specific** reusable functionality, which differs from the common module in that common is for **generic** functionality. 
> ```

I think this is how common was initially envisioned, but it's so small it should probably get merged into core (and would be if we had any serious time for refactoring).

---

*[docs/developer/modules/geo.md, line 9 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTKJ0r7Q8iQtiBgJx1:-KcTKJ0sC9Cqs_MdcvpU:b-vovqzp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/geo.md#L9)):*
> ```Markdown
> Exposes the `geoApi` interface on `geoService.gapi` once it has been loaded (external library)
> 
> ## geo.service.js
> ```

This is also supposed to be the only external interface to the rest of the modules (i.e. if UI needs to do something it should call geo service instead of any specific services).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-:-KcTLdFMqBQVzWeXHmpu:b-idbxs7)*

**Comment by milesap** [comment]
I've noted and made all the needed changes based on comments here in another branch which will follow this one.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[docs/developer/app_startup.md, line 5 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTHOWet9HwuZs9JeOs:-KcTbNu2pombhXRheDNf:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L5)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

This changed after you wrote it, but now the preferred initialization is to put `is="rv-map"` on the element.  `class="fgpv"` will be deprecated in #1672
</blockquote></details>

Made change for next PR

---

*[docs/developer/app_startup.md, line 12 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTHGt1Z3FMTkWJR2l0:-KcTbZRratdowb5SQl_X:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L12)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

if necessary
</blockquote></details>

Made change for next PR

---

*[docs/developer/app_startup.md, line 14 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTH-bzIXfUk-8PUW8u:-KcTbbIaRzsZ1XOON4E6:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L14)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

IE polyfills are not loaded by bootstrap.  Since they are big we split them into a separate file and it's up to the host page to either use them or load their own polyfills.  This must be done before bootstrap is called.
</blockquote></details>

Made change for next PR

---

*[docs/developer/app_startup.md, line 21 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTHdboc74gxbJVRArV:-KcTblR4iXOSnH-s3Jmt:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/app_startup.md#L21)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

If this is on the developer side you may also want to include a note that this is how interaction with `window.RV` should be managed
</blockquote></details>

Made change for next PR

---

*[docs/developer/architecture_overview.md, line 20 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcNx85DsXpQTF9EWE6k:-KcTcNNpZB1Uv3KOQQ3N:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/architecture_overview.md#L20)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Mike:
> but yeah anything that supports forking the codebase. no.
</blockquote></details>

Made change for next PR

---

*[docs/developer/getting_started.md, line 51 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcNxW0I4GLCSLXm2erv:-KcTcSjNGE9tF6WdJo_i:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/getting_started.md#L51)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

We can drop `gulp sass` and `gulp clean-sass`; I never use them separately and I doubt anyone else does.
</blockquote></details>

Made change for next PR

---

*[docs/developer/plugins.md, line 84 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSl7SqOUWVXwJlPA9o:-KcTcgusEn3k0CMdux3s:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins.md#L84)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Bonjour tout le monde
</blockquote></details>

Made change for next PR

---

*[docs/developer/plugins.md, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcO-23LxqM8puLXFlWM:-KcTf-AUOAaBGNtZXIpv:b-txoim5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins.md#L89)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

:crown: 
</blockquote></details>

:1st_place_medal: 

---

*[docs/developer/plugins.md, line 127 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSlZX-tv7HPRu76UnG:-KcTcjmRCnhoUkqnRAxE:b-qomhoz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins.md#L127)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If a user pass 2 values of alert text (en-CA and fr-CA) will it be able to detect language when action button is click and show the right text?
</blockquote></details>

At this time this doesn't work since the viewer needs to explicitly pass values to `$translate`. Since anything can be placed inside the plugins action function its not immediately clear how this would happen. I'm sure we'll expand plugin translations so that this is possible to some degree (I'd imagine something like defining a translatable object in the plugin)

---

*[docs/developer/modules/core.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTK4KXPzGuxH0B_BMG:-KcTe-oy00R-7x1Lhvra:b-4msi98) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/core.md#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

I think this is how common was initially envisioned, but it's so small it should probably get merged into core (and would be if we had any serious time for refactoring).
</blockquote></details>

Will update if this occurs

---

*[docs/developer/modules/geo.md, line 9 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTKJ0r7Q8iQtiBgJx1:-KcTePjLKFq5f62WEvpc:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/geo.md#L9)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

This is also supposed to be the only external interface to the rest of the modules (i.e. if UI needs to do something it should call geo service instead of any specific services).
</blockquote></details>

Made change for next PR

---

*[docs/developer/modules/geo.md, line 18 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnChjVXhybKU8jb1e:-KcTeVO0Jp1ZD7RHqh6-:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/geo.md#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It will also zoom to a specific scale
</blockquote></details>

Made change for next PR

---

*[docs/developer/modules/ui.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcSnlrL3qf_NS6bZIdj:-KcSviuoYM-9F3A2bs6F:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/ui.md#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Only one extra button whit a panel is what I had in my mind as well
</blockquote></details>

:+1: 

---

*[docs/developer/plugins/core_plugins.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcO-i4UyS_8YAtMIDiL:-KcTeiQyxvMf1CxSX675:b-b3bm8i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/plugins/core_plugins.md#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

[[External Plugins]] link doesn't work.
</blockquote></details>

Made change for next PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-:-KcTejjPOzPLfSOmI4xF:b-xvax44)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/modules/core.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTK4KXPzGuxH0B_BMG:-KcTyk2PUexZne_8mhVJ:b-b1havx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/core.md#L1)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Will update if this occurs
</blockquote></details>

It should at least be considered deprecated for now, so if someone wants to add new shared code it goes in core.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/developer/modules/core.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664#-KcTK4KXPzGuxH0B_BMG:-KcU1BSYSeztwzmEgegY:b21cmme) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551ee8e812d4bca6bdf0d0dd1e9c09ea376d17c9/docs/developer/modules/core.md#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

It should at least be considered deprecated for now, so if someone wants to add new shared code it goes in core.
</blockquote></details>

Ok will note that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1664)*

**Pull request merged**
