### PR TITLE
Feature/clickeroo

### PR DESCRIPTION
**Pull request by james-rae**
Harmonized image and feature click events into one.  Uses spatial queries instead of feature-click events on feature layers.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/325)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 28 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe16C0-zMi9EVWk3wG:-KAe16C0-zMi9EVWk3wH:502544502) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L28)):*
You can omit curly braces if the body of the arrow function is a single function call.
```js
addDynamicLayer: (layer, name) => dynamicLayers.push({ layer, name }),
```

---

*[src/app/geo/identify.service.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe2F4yy4IinuW1XqKd:-KAe2F4yy4IinuW1XqKe:1496607694) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L43)):*
with `.filter`, this can be a one-liner:
```js
function getVisibleLayers() { 
    return dynamicLayers.concat(featureLayers).filter(l => l.layer.visibleAtMapScale).length
}
```

---

*[src/app/geo/identify.service.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe3kYys7NEfn1daOWR:-KAe3kYztB1VlQQtV0MV:1936811543) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L158)):*
why not `idPromises.concat(featureLayers.map(({ layer, name }) => {...}));` ?

---

*[src/app/geo/identify.service.js, line 195 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe4c7g9ztcNDWTYIS0:-KAe4c7g9ztcNDWTYIS1:-217114822) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L195)):*
We were talking about a promise which resolves when attributes are downloaded, maybe this could wait on that promise.

---

*[src/app/geo/identify.service.js, line 234 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe5F9fIQgvx5SRKlrd:-KAe5F9fIQgvx5SRKlre:1630243586) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L234)):*
For consistency, we need to decide whether to use `Promise` or Angular `$q` service. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 177 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAeRbXCLl94ZzHjRh3H:-KAeRbXD2Yqa9Se3QpJL:-2016007512) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L177)):*
Consider wrapping the dojo output in a new `Promise` that is compatible.  

---

*[src/app/geo/identify.service.js, line 234 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe5F9fIQgvx5SRKlrd:-KAeR9lp2rsLs4FX0bJ1:-43820676) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L234)):*
I'd vote `Promise` as it's immediately readable by anyone who doesn't know what some random library called `q` does.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 234 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe5F9fIQgvx5SRKlrd:-KAeuxYNXeAJfOhJ5oXl:-455717671) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L234)):*
Unfortunately, it seems like we __have__ to use `$q` as it's tied into the angular digest cycle. Regular Promises will not trigger a new digest cycle by themselves (need to use something like `$scope.$digest`).

@/all please, use '$q' when you need a promise. https://docs.angularjs.org/api/ng/service/$q

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by james-rae** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe3kYys7NEfn1daOWR:-KAeqod_EDJXn23fnJsG:843392689) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L158)):*
concat returns a new array.  it does not add on the end of the existing array.

---

*[src/app/geo/identify.service.js, line 177 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAeRbXCLl94ZzHjRh3H:-KAf-6Mrdl0zvUtXVfTl:-1176250324) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L177)):*
good catch, wasn't considering the "promise returns a promise" thang that would impact the array of promises.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 158 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAg2tPYjHRUe_S1G2j_:-KAg2tPZq9maf2E2KfEt:1317826107) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/60a26a6f0251b04d464d8d9761dca4621241171b/src/app/geo/identify.service.js#L158)):*
You can use `$q.resolve(null)`, same as with Promise.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 158 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAg2tPYjHRUe_S1G2j_:-KAg44Q-Ewwt25rx4Mhd:-743674776) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/60a26a6f0251b04d464d8d9761dca4621241171b/src/app/geo/identify.service.js#L158)):*
thats good :dancers: :dash: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe3kYys7NEfn1daOWR:-KAg9XaX8AGsEQglRQO0:-17976016) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L158)):*
How about `idPromise = idPromises.concat(...)` ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe3kYys7NEfn1daOWR:-KAjcVJksKq5C2DuVrbX:-2131031535) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L158)):*
You would lose your lovely `const`.  IS IT WORTH THE RISK???

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe3kYys7NEfn1daOWR:-KAjdqQOJbCEeYPhEc9n:121267803) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L158)):*
`idPromises.push.apply(idPromises, ...)` this is still nicer than `Array.prototype`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe3kYys7NEfn1daOWR:-KAjduyWESZi1PJquvJm:1959153973) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L158)):*
I'd say so, `concat` is much easier to read than `Array.prototype.push.apply`.  Or call the previous array `dynamicIdPromises`, call this one `featureIdPromises` and concat the two when you need them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 158 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325#-KAe3kYys7NEfn1daOWR:-KAjej1WTmxir8lz37_5:5897627) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9e69310b54ea68fad97317f4d7a0dee4b282a74a/src/app/geo/identify.service.js#L158)):*
some benchmarking: http://jsperf.com/combining-js-arrays
just for fun

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by cynngah** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/325)*

**Pull request merged**
