### PR TITLE
Enable Point Information Display when viewing Datagrid 

### LINKED ISSUE #416: Enable Point Information Display when viewing Datagrid
When selecting a record in the datagrid the point information panel should provide an output similar to that which is provided by Identify.

- [x] reuse map click (in identifyService) to display the proper data and trigger the point click details panel
- [x] make another button in datagrid which triggers the above logic
- [x] make tooltip so people know they're getting details when clicking on said button

### PR DESCRIPTION
**Pull request by cynngah**
Closes #416

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/605)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/content/styles/modules/_filters.scss, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605#-KHtSP-djlDZXBPaY6Gi:-KHtSP-djlDZXBPaY6Gj:-1600125650) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6af0a282f4d10c6c646517fe3c21dbec530cca78/src/content/styles/modules/_filters.scss#L56)):*
> ```SCSS
>                             // FIXME: should be removed when using real button in datatables
>                             .rv-icon {
>                                 cursor: pointer;
> ```

Add a bit of margin `margin: 0 0 0 rem(0.6);` to make it look better.

---

*[src/content/styles/modules/_filters.scss, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605#-KHtSE105_N2wcMvTYrq:-KHtSE105_N2wcMvTYrr:-721252744) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6af0a282f4d10c6c646517fe3c21dbec530cca78/src/content/styles/modules/_filters.scss#L59)):*
> ```SCSS
>                             }
> 
>                             .rv-zoom-to {
> ```

Change this to `.rv-zoom-to, .rv-description {` to reuse existing rules and ...

---

*[src/content/styles/modules/_filters.scss, line 70 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605#-KHtSHI-QzaVuw1eeVIA:-KHtSHI-QzaVuw1eeVIB:803672180) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6af0a282f4d10c6c646517fe3c21dbec530cca78/src/content/styles/modules/_filters.scss#L70)):*
> ```SCSS
>                             }
> 
>                             .rv-description {
> ```

remove this block. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605)*

**Comment by cynngah** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_filters.scss, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605#-KHtSP-djlDZXBPaY6Gi:-KHtcEi2ZtLLA6pMbggp:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6af0a282f4d10c6c646517fe3c21dbec530cca78/src/content/styles/modules/_filters.scss#L56)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Add a bit of margin `margin: 0 0 0 rem(0.6);` to make it look better.</details>
Done.

---

*[src/content/styles/modules/_filters.scss, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605#-KHtSE105_N2wcMvTYrq:-KHtcFAav0CB28VoAAhz:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6af0a282f4d10c6c646517fe3c21dbec530cca78/src/content/styles/modules/_filters.scss#L59)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Change this to `.rv-zoom-to, .rv-description {` to reuse existing rules and ...</details>
Done.

---

*[src/content/styles/modules/_filters.scss, line 70 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605#-KHtSHI-QzaVuw1eeVIA:-KHtcGSHkZcBYNcY2fqX:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6af0a282f4d10c6c646517fe3c21dbec530cca78/src/content/styles/modules/_filters.scss#L70)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> remove this block. </details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/605)*

**Pull request merged**
