### PR TITLE
fix(ui): prevent mapnav controls from overlapping

### LINKED ISSUE #1310: Navcontrols are being overlapped by the datatable when viewer height is small
We should probably be shifting down the nav controls as we run out of vertical space as well:

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #1310.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1319)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319)*

**Comment by milesap** [comment]
In IE while resizing the viewer height, the nav control buttons move a proportional amount outside the viewport. This causes buttons to become unreachable.



---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-:-KVWALh3xsdVevJxBdfR:bpqyxx)*

**Comment by AleksueiR** [comment]
Good catch :+1: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-:-KVWCZbmjcC9z0FLyD3X:bm1iqqr)*

**Comment by alyec** [comment]
I'm not sure if the IE issue is big so I'm flipping it back to you in case it needs a revised estimate.

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-:-KV_1j2v4DnyB232qaJc:bnfp4nl)*

**Comment by AleksueiR** [comment]
IE fix done.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-:-KV_01VKu-oHo1nhZGCX:b-19nhwe)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_mapnav.scss, line 33 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-KV_2EuM2QMWnucMvyHJ:-KV_2EuOaMPyBPeKLONc:bgez1ti) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0d711646e790737364d95554c0e4323bfe934a5d/src/content/styles/modules/_mapnav.scss#L33)):*
> ```SCSS
> 
>         .rv-mapnav-content {
>             // IE expands flex: 1 as flex-grow: 1; flex-shrink: 1; flex-basis: 0px; notice 0px; then it tries to squash the elemnt to 0px; flex-basis needs to be set to 0 then the extra space arond the item's content isn't factored in
> ```

two typos: element and around

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_mapnav.scss, line 33 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-KV_2EuM2QMWnucMvyHJ:-KV_3HwW3Q3TPXmnJ7jr:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0d711646e790737364d95554c0e4323bfe934a5d/src/content/styles/modules/_mapnav.scss#L33)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> two typos: element and around
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319)*

**Comment by AleksueiR** [comment]
Updated [1.4.0 release notes](https://github.com/fgpv-vpgf/fgpv-vpgf/releases/tag/untagged-ea534b601d42929c236e).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-:-KV_69ApUmCkeUy2wWWi:b-m4llqu)*

**Comment by milesap** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1319#-:-KV_Os_502DzZqkCZA8e:bnfp4nl)*

**Pull request merged**
