### PR TITLE
Legend Service cont.

### LINKED ISSUE #303: User Interface modifications for grouped layers
- [x] Define legend schema for group layers (#334)
- [x] Wire TOC to new configuration schema

Traceability Matrix ID#106

### PR DESCRIPTION
**Pull request by AleksueiR**
Added more stuff to legendService:

- generates tile egend layer entries with symbology
- add to the map only dynamic sublayers specified in config's layerEntries
- correctly toggles visibility of the dynamic layer/sublayers

Closes #303

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/428)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/legend.service.js, line 312 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU0s8fIk4N2xvphn0r:-KDU0s8fIk4N2xvphn0s:400794189) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/geo/legend.service.js#L312)):*
I'm having a fair bit of trouble following all the different paths for visibility settings.  Can you add more to the top level comment or to a new wiki page on the site?  It seems like we need to call setVisibility on the UI layer item separately from the actual layer and I don't understand why these are split.

---

*[src/app/geo/legend.service.js, line 368 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU0XbShf5FfZJELIDf:-KDU0XbShf5FfZJELIDg:1540759161) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/geo/legend.service.js#L368)):*
typo: Boolean

---

*[src/app/ui/common/toggle-slide.animation.js, line 48 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU1eUDs8cXzz8ldrMn:-KDU1eUDs8cXzz8ldrMo:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/ui/common/toggle-slide.animation.js#L48)):*
const

---

*[src/app/ui/common/toggle-slide.animation.js, line 50 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU1dIylQJ59ibi2neP:-KDU1dIzciJSW4aOdViu:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/ui/common/toggle-slide.animation.js#L50)):*
const

---

*[src/app/ui/common/toggle-slide.animation.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU1i7d-LlkZomPkyZ8:-KDU1i7d-LlkZomPkyZ9:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/ui/common/toggle-slide.animation.js#L75)):*
const

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by spencerwahl** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 171 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU0aZ6yuZgFLkdlY7R:-KDU0aZ7MKGOCijq34lW:-1530336523) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/geo/layer-registry.service.js#L171)):*
What is this being used for?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by AleksueiR** [comment]
Review status: 9 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 171 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU0aZ6yuZgFLkdlY7R:-KDUEWJBc2HcLUQO_JqI:837695501) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/geo/layer-registry.service.js#L171)):*
So you can access the layer object from the console. For example, you can type this
`RV.layers.aafc_agri_environmental_indicators.layer.setVisibleLayers([1, 2, 3, 5, 6, 7, 8, 9, 10, 11])` into the console and change the visibility of dynamic sublayers. Handy when you are trying to make sure stuff actually works.

---

*[src/app/geo/legend.service.js, line 312 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU0s8fIk4N2xvphn0r:-KDUI1puzKawQiMRi5eb:1910407865) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/geo/legend.service.js#L312)):*
Is this any better or is it more confusing?

---

*[src/app/geo/legend.service.js, line 368 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU0XbShf5FfZJELIDf:-KDU5OcwUnm0kFhVM0rs:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/geo/legend.service.js#L368)):*
Done.

---

*[src/app/ui/common/toggle-slide.animation.js, line 48 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU1eUDs8cXzz8ldrMn:-KDU5MkCKfbdWw2RXbwy:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/ui/common/toggle-slide.animation.js#L48)):*
Done.

---

*[src/app/ui/common/toggle-slide.animation.js, line 50 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU1dIylQJ59ibi2neP:-KDU5N0je5zbfwuGvMTj:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/ui/common/toggle-slide.animation.js#L50)):*
Done.

---

*[src/app/ui/common/toggle-slide.animation.js, line 75 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU1i7d-LlkZomPkyZ8:-KDU5NT69C_U0j66EeFh:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/ui/common/toggle-slide.animation.js#L75)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/legend.service.js, line 312 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428#-KDU0s8fIk4N2xvphn0r:-KDcf4mh0t-5ZfNWT7Kx:1921943882) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f6be14298413ea6c6bce00975ac09078193057b8/src/app/geo/legend.service.js#L312)):*
Makes a lot more sense at a high level.  I'm having a bit of trouble following the decorated functions since I'm used to seeing things like Python's decorator syntax but I'll ask you about that separately.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by ec-dev** [comment]
Reviewed 6 of 12 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by ec-dev** [comment]
Reviewed 2 of 12 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/428)*

**Pull request merged**
