### PR TITLE
fix(help): update help to include new functionality

### LINKED ISSUE #1568: Update Help to include descriptions of new functionality
such as the new `reorder` mode, `expand/collapse layer groups`, and `hide/show all layers`.

### PR DESCRIPTION
**Pull request by milesap**
## Description

Also updated content and added pictures
 
Closes #1568

## Testing
vigorously

## Documentation
Obviously, no

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1801)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/locales/help/en-CA.md, line 21 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrHSnIS-ZoUecGtfPz:-KfrHSnIS-ZoUecGtfQ-:b-lty2bh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L21)):*
> ```Markdown
> 
> 
> # Basemap Selector
> ```

Should you say it is also available in main menu?

---

*[src/locales/help/en-CA.md, line 72 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrIFKaUHF9fVzHXsCW:-KfrIFKaUHF9fVzHXsCX:bh04rel) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L72)):*
> ```Markdown
> Each layer has some symbology associated with it. For simple feature layers a single icon will be present next to the layer name. For complex feature layers (i.e. those with multiple symbols used per layer) the icon will show as a stack that can be toggled open and closed which is expanded beneath the layer name. WMS layers may optionally have a graphical legend defined, if one is present it will be displayed in the same drop down manner.
> 
> Some layers may only be visible at certain zoom levels. If a layer is not visible at a given zoom level the legend will display a notice and have an action available to zoom to the closest zoom level at which the layer will be visible (this may involve either zooming in or zooming out).
> ```

Can you put the icon for out of zoom?

---

*[src/locales/help/en-CA.md, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrIhJpud7OSCvlU95E:-KfrIhJpud7OSCvlU95F:b-v5u6ks) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L98)):*
> ```Markdown
> |----|----|----|
> |  | Metadata | Display relevant metadata in a slideout panel |
> |  | Settings | Opens slideout panel where opacity amount and bounding box visibility can be toggled |
> ```

and queryable

---

*[src/locales/help/en-CA.md, line 142 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrIzdjfPYzwGr8mCy0:-KfrIzdjfPYzwGr8mCy1:byexxjm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L142)):*
> ```Markdown
> You can export an image of the map and its visible layers along with; a legend, title, north arrow with scalebar, custom footnote, and a timestamp.
> 
> Select the 'EXPORT' button from the left side menu to get started. A dialog will appear with an image of the map, and an option to enter a map title if desired.
> ```

Elsewhere you called it main menu.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801)*

**Comment by AleksueiR** [comment]
This looks fantastic! We should release a new patch just to include this help update.

Did you get the icon images from Material design website or just made screenshots of them?

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/content/styles/modules/_help.scss, line 35 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfuqsI4AE0VJQUDefq-:-KfuqsI60QeTq55Z31Uf:bqtekwi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/content/styles/modules/_help.scss#L35)):*
> ```SCSS
> 
>             table {
>                 margin-bottom: 15px;
> ```

Please, use rem instead of px, for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-:-KfurYjeUabLvRNhnHnV:bqov4xo)*

**Comment by milesap** [comment]
ty! Yeah, this PR is in 1.7 which will most likely be released in 2 weeks or less - just need to get the french version ready @jolevesq if you don't mind. I just did screen shots.

---

Review status: 35 of 39 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/content/styles/modules/_help.scss, line 35 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfuqsI4AE0VJQUDefq-:-Kfuzw-Ng3LrCDuG9Yd4:b-n9tkhd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/content/styles/modules/_help.scss#L35)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, use rem instead of px, for consistency.
</blockquote></details>

changed

---

*[src/locales/help/en-CA.md, line 21 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrHSnIS-ZoUecGtfPz:-Kfv-Ii-OXKQrbYkGkgS:b5ywizu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should you say it is also available in main menu?
</blockquote></details>

Yes, added

---

*[src/locales/help/en-CA.md, line 72 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrIFKaUHF9fVzHXsCW:-Kfv1lSnIyjesnUWX7dI:b-c0syn9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put the icon for out of zoom?
</blockquote></details>

Added out of scale and zoom to nearest level icons.

---

*[src/locales/help/en-CA.md, line 98 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrIhJpud7OSCvlU95E:-Kfv23yAXyhPDwcp3XLf:b-7tfmjp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L98)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

and queryable
</blockquote></details>

added

---

*[src/locales/help/en-CA.md, line 142 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-KfrIzdjfPYzwGr8mCy0:-Kfv2FI0gdn6s12_Qzns:b-yigp24) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/84f5ab0e221ee4fbcfa12a1bf5b5c6a3f2661e31/src/locales/help/en-CA.md#L142)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Elsewhere you called it main menu.
</blockquote></details>

corrected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-:-Kfv2JXI7GhlF5fZj75x:bbaqa65)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801)*

**Comment by jolevesq** [comment]
@milesap I can do it for the French version. Do I wait until this is merge or I branch directly from the PR?

With the images help is more useful and looks very nice!

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1801#-:-Kfv6xpBWK-lEjhHeHQ7:bs2ofls)*

**Pull request merged**
