### PR TITLE
Add/modify samples and reorganize config files

### PR DESCRIPTION
**Pull request by barryytm**
## Description

- #1786. Add more samples and modify config files to suit testers' needs. 

- Move all the config files to a fold named `config`.

## Testing

Manually and they still need to be tested by testers.
## Documentation

samples, config files
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2115)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 97 of 97 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115)*

**Comment by james-rae** [comment]
By moving config files related to pages other than `samples` and `mobile`, you've broken the other pages. I'd suggest either moving the other `json` files back, or fixing the other `tpl` files.
And either way, I'll ask you leave the `config.rcs-<lang>.json` files where they are as it will make my RCS merge messy.  If we decide everything gets moved into the subfolder I'll do that on my commit.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115#-:-KoNrW0nwJSlhdp-tuzI:bd2a6ui)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/content/samples/config/config-sample-41.json, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115#-KoNrsylKOT3ta-bODMK:-KoNrsylKOT3ta-bODML:b-8bq2et) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3396e9eb8603233ce7c7438d89d28623a07c5d33/src/content/samples/config/config-sample-41.json#L32)):*
> ```JSON
>     "proxyUrl": "http://167.40.64.74/wmsproxy/ws/wmsproxy/executeFromProxy",
>     "exportMapUrl": "http://webservices-staging.maps.canada.ca/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task",
>     "export": {
> ```

I think you should add exporting sections to more config files; also, please include other export elements (like `title`, `legend`, and `mapElements`) into some of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115)*

**Comment by barryytm** [comment]
Review status: 0 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/config/config-sample-41.json, line 32 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115#-KoNrsylKOT3ta-bODMK:-KoO-R7xtIh4n7ni3ae2:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6143f3495d5beb2ffa344536a20d82eeb9457937/src/content/samples/config/config-sample-41.json#L32)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think you should add exporting sections to more config files; also, please include other export elements (like `title`, `legend`, and `mapElements`) into some of them.
</blockquote></details>

Done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115)*

**Comment by james-rae** [comment]
Reviewed 33 of 97 files at r1, 43 of 64 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115)*

**Comment by james-rae** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115#-:-KoO-e2p2mQ-PmDJEM1k:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 33 of 97 files at r1, 43 of 64 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2115)*

**Pull request merged**
