### PR TITLE
feat(ui): add point/wms details pane to the main panel

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/146)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 19 of 19 files at r1.
Review status: 18 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146#-K6o7414vHOYrxGeWhp5:-K6o7414vHOYrxGeWhp6:1823298196) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/723f8f537e00dea42153bd9e80ae32aafdf78033/src/app/common/router/statemanager.service.js#L30)):*
can you use the ES6 object shorthand to make this simpler?

---

*[src/app/layout/shell.html, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146#-K6o7TXAygYLK1_DmYiS:-K6o7TXAygYLK1_DmYiT:-1635984635) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/723f8f537e00dea42153bd9e80ae32aafdf78033/src/app/layout/shell.html#L47)):*
inline CSS ... we need more of this

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Comment by AleksueiR** [comment]
Review status: 18 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146#-K6o7414vHOYrxGeWhp5:-K6o8uiPOyvbuvYOp8gN:1817204617) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/723f8f537e00dea42153bd9e80ae32aafdf78033/src/app/common/router/statemanager.service.js#L30)):*
Shorthand for `addState: addState` assignments? Sure, I forgot about that.

---

*[src/app/layout/shell.html, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146#-K6o7TXAygYLK1_DmYiS:-K6o8aP7yElxjuGVQLuo:734269606) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/723f8f537e00dea42153bd9e80ae32aafdf78033/src/app/layout/shell.html#L47)):*
This is just for demo: two buttons on the map to open details panel.


---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146#-K6o7414vHOYrxGeWhp5:-K6o9tdhmpbzzCQasM0_:-39177671) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/723f8f537e00dea42153bd9e80ae32aafdf78033/src/app/common/router/statemanager.service.js#L30)):*
Yeah: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Property_definitions

---

*[src/app/layout/shell.html, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146#-K6o7TXAygYLK1_DmYiS:-K6o9weCq65aED06XeFP:523240236) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/723f8f537e00dea42153bd9e80ae32aafdf78033/src/app/layout/shell.html#L47)):*
Wasn't a complaint, it's actually more legible than scss to me :stuck_out_tongue: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Comment by spencerwahl** [comment]
Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Comment by james-rae** [comment]
Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Comment by AleksueiR** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/common/router/statemanager.service.js, line 30 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146#-K6o7414vHOYrxGeWhp5:-K6oC9jQD4l-4QT-fPoQ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/723f8f537e00dea42153bd9e80ae32aafdf78033/src/app/common/router/statemanager.service.js#L30)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/146)*

**Pull request merged**
