### PR TITLE
chore(build): fix xslt file loading for metadata

### LINKED ISSUE #2075: XSL files related to metadata need to be included in webpack
Files in https://github.com/fgpv-vpgf/fgpv-vpgf/tree/develop/src/content/metadata need to be included in the webpack when building.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Removed english/french files (no longer used

Closes #2075

## Testing
None yet

## Documentation
No

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2085)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Looks good to me. :lgtm: 

@barryytm, does this work for you?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085#-:-Knt8fsAhXrjQvnChrPx:b-ugmfai)*

**Comment by barryytm** [comment]
I was not able to test it because none of the metadata urls work.

**Comment by milesap** [comment]
@barryytm ok - added to date layer field

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085#-:-KntLx2lzMKiTNqXMJF8:b-9pceq4)*

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085)*

**Comment by barryytm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085#-:-KntNSHkP4rMUa6mrtep:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085)*

**Comment by barryytm** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2085)*

**Pull request merged**
