### PR TITLE
Panels API

### PR DESCRIPTION
**Pull request by milesap**
## Description
This PR is an overhaul to the panel system which:
- introduces collision management 
- off screen detection
- a more robust API interface with various panel type support + simplified ways to handle complex panel requirements.

1. Read the updated docs here: https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/pr-3312/#/developer/panels
2. Play around with the demo panel builder at: http://fgpv.cloudapp.net/demo/users/milesap/3312-panel-rocket/dev/samples/index-samples.html

Note: This breaks enhancedTables and other plugins until they are migrated when this is merged. @ShrutiVellanki and @dane-thomas please let me know if you think there is something missing or changed drastically which would make migration difficult. 

## Testing
Working on IE11, FF, and Chrome

### Checklist

- [x] works in IE11
- [ ] works in Edge
- [ ] works with projection change
- [ ] works with language change
- [ ] works via config file
- [ ] works via wizard
- [ ] works via API
- [ ] works via RCS
- [ ] works via bookmark load
- [ ] works in auto-legend
- [ ] works in structured legend
- [ ] works on layer reload
- [ ] datagrid works
- [ ] identify works

## Documentation
inline and https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/pr-3312/#/developer/panels

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated
- [x] original issue has been reviewed & updated to reflect the PR content

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3350)

### CODE REVIEW

**Comment by milesap** [comment]
You can also update a panels position in the dev console (either through jQuery or directly in the element inspector) and these changes will trigger collision/offscreen checks.

**Comment by mweech** [comment]
> Note: This breaks enhancedTables and other plugins until they are migrated when this is merged. @ShrutiVellanki and @dane-thomas please let me know if you think there is something missing or changed drastically which would make migration difficult.

Based on the above comment, it seems like we should not merge this change as it would impair QA efforts or other work if bugs arise.  Instead, should we work on the migration of those panels first and merge them all at the same time?

**Comment by milesap** [comment]
Latest changes fix minor issues affecting IE11. FF tested as well. Minor doc tweaks + fixes.

**Comment by james-rae** [comment]
___
*[api/src/panel/index.ts, line 109 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3350#-L_rWfM5AKFFoo2LOaE5:-L_xK_1FAmdSY2kotz2b:b-gw179p) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fe98596666042c3067641bba28c3cbd782c46587/api/src/panel/index.ts#L109)):*
I can't type..

> Is this like the way the panel knows...

**Pull request merged**
