### PR TITLE
Update sample urls

### PR DESCRIPTION
**Pull request by james-rae**
Donethankses #3928 

Mostly adds `https` to servers that require or prefer it.
Updates `section917` domain url.
Updates WMS Proxy url to not use IP Address as domain

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3941)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
Fancy

> Reviewed 152 of 152 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3941#-:-McKS_Ue6qVxFpPONBBu:b-88bs58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

**Review by yileifeng — APPROVED** [review]
> Reviewed 152 of 152 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

**Review by sharvenp — APPROVED** [review]
> Reviewed 152 of 152 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

**Review by JahidAhmed — APPROVED** [review]
> Reviewed 152 of 152 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

**Pull request merged**
