### PR TITLE
chore(readme): add more badges to readme.md

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/267)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 6 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/267#-K9bL3V1PLmWxAh40tqu:-K9bL3V2f_9V58RkyfSf:-831201639) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/404e00b8759f038f52b842f6191ad5dc5de81710/README.md#L6)):*
Shouldn't this one be named PR Stats?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/267)*

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 6 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/267#-K9bL3V1PLmWxAh40tqu:-K9bM4ILI0eUZRR-_W13:-674131257) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/404e00b8759f038f52b842f6191ad5dc5de81710/README.md#L6)):*
True. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/267)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/267)*

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/267)*

**Pull request merged**
