### PR TITLE
fix(table): apply on map for server user added layer

### LINKED ISSUE #2106: "Apply to Map" feature in  datatables not working as expected for certain layers
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily12/prod/samples/index-samples.html

Test data: http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0     
                 http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_SO2/MapServer

Related #884 

"Apply to Map" feature does not filter the points to display the filtered data for layers from config file or user added layers consistently. This feature cannot be seen in the datatable with some dynamic layers. Please investigate

image

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Closes #2106 

## Testing

Chrome

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2179)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/app/ui/table/setting-cluster.html, line 6 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179#-Kp0Yif8M2AMohBk-xiZ:-Kp0Yif8M2AMohBk-xi_:b-iq77dv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/911a2ec55f1d13806dd96c0d16bab89f620e1e75/src/app/ui/table/setting-cluster.html#L6)):*
> ```HTML
>         class="rv-table-apply primary"
>         rv-help="table-apply-button"
>         ng-click="self.tableService.applyFilters()"
> ```

Looks like the old name has snuck back in.  Unless this refers to actual filters :)   Let me know (same with line below)

---

*[src/app/ui/table/table.service.js, line 499 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179#-Kp0ZZUHfwrvsdpl2EOA:-Kp0ZZUHfwrvsdpl2EOB:b888zh4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/911a2ec55f1d13806dd96c0d16bab89f620e1e75/src/app/ui/table/table.service.js#L499)):*
> ```JavaScript
>         const url = layerRegistry.getLayerRecord(stateManager.display.table.requester.legendEntry.layerRecordId).rootUrl;
>         service.isFeatureLayer = (layerType === 'esriFeature' && url !== "") ? true : false;
>         service.isDynamicLayer = (layerType === 'esriDynamicLayerEntry' && url !== "") ? true : false;
> ```

You might be able to simplify this.  It is impossible for Dynamic Layer to be file based, so no need for url check
For Feature, the layerRecord has `isFileLayer()`

```
service.isFeatureLayer = (layerType === 'esriFeature' && !layerRecord.isFileLayer()) ? true : false;
service.isDynamicLayer = (layerType === 'esriDynamicLayerEntry') ? true : false;
```

Will leave it up to you, the current logic is fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179)*

**Comment by james-rae** [comment]
*[src/app/ui/table/table.service.js, line 499 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179#-Kp0ZZUHfwrvsdpl2EOA:-Kp0__zmCG4jrdvOy7ET:bj3cae1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/911a2ec55f1d13806dd96c0d16bab89f620e1e75/src/app/ui/table/table.service.js#L499)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

You might be able to simplify this.  It is impossible for Dynamic Layer to be file based, so no need for url check
For Feature, the layerRecord has `isFileLayer()`

```
service.isFeatureLayer = (layerType === 'esriFeature' && !layerRecord.isFileLayer()) ? true : false;
service.isDynamicLayer = (layerType === 'esriDynamicLayerEntry') ? true : false;
```

Will leave it up to you, the current logic is fine
</blockquote></details>

Actually no need for question marks either

```
service.isFeatureLayer = (layerType === 'esriFeature' && !layerRecord.isFileLayer());
service.isDynamicLayer = (layerType === 'esriDynamicLayerEntry');
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/table/setting-cluster.html, line 6 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179#-Kp0Yif8M2AMohBk-xiZ:-Kp0_KkAZMYWeyG-5eIw:b-4q51n4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/911a2ec55f1d13806dd96c0d16bab89f620e1e75/src/app/ui/table/setting-cluster.html#L6)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Looks like the old name has snuck back in.  Unless this refers to actual filters :)   Let me know (same with line below)
</blockquote></details>

This refers to a function inside table.

---

*[src/app/ui/table/table.service.js, line 499 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179#-Kp0ZZUHfwrvsdpl2EOA:-Kp0_bfmcHmqcISjQX2q:bfv8fh0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/911a2ec55f1d13806dd96c0d16bab89f620e1e75/src/app/ui/table/table.service.js#L499)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

You might be able to simplify this.  It is impossible for Dynamic Layer to be file based, so no need for url check
For Feature, the layerRecord has `isFileLayer()`

```
service.isFeatureLayer = (layerType === 'esriFeature' && !layerRecord.isFileLayer()) ? true : false;
service.isDynamicLayer = (layerType === 'esriDynamicLayerEntry') ? true : false;
```

Will leave it up to you, the current logic is fine
</blockquote></details>

I can do the modification

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2179)*

**Pull request merged**
