### PR TITLE
style(locales): complete French translation of translation.csv file

### LINKED ISSUE #607: Complete Translations of French Text
- [x] Extract and compile a spreadsheet of text that needs to be translated
- [x] Review english strings in the translation file for validity
- [x] Have text translated
- [x] Integrate translated text

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Closes #607

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/691)

### CODE REVIEW

**Comment by alyec** [comment]
:lgtm:

<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary>
> #### style\(locales\): complete French translation of translation\.csv file
> 
> Closes #607
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/691#-:-KJ6D-DxyzCsO6AGKOXv:1417088721)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/locales/translations.csv, line 209 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/691#-KJ6DdtrIELuhZJP0DBk:-KJ6DdtrIELuhZJP0DBl:-1037600138) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f7a64ab366dd2837c3357b11a5ba7e52d90c6ce1/src/locales/translations.csv#L209)):*
> ```CSV
> 'Remove'<br>
> - Remove the layer from the map and legend.","Passez la souris sur un nom de couche et cliquez sur l'icône de ""trois points"" pour accéder à des options supplémentaires pour la couche.<br>
> <br><
> ```

Is this needed? (Extra `<`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/691)*

**Comment by ChrisLatRNCan** [comment]
*[src/locales/translations.csv, line 209 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/691#-KJ6DdtrIELuhZJP0DBk:-KJ6Zwlu6odGpznoVwLP:-575484135) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f7a64ab366dd2837c3357b11a5ba7e52d90c6ce1/src/locales/translations.csv#L209)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> Is this needed? (Extra `<`)
</details>
Correction done, extra < removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/691)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/691)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/691)*

**Pull request merged**
