### PR TITLE
Back to cart

### PR DESCRIPTION
**Pull request by spencerwahl**
Issue #415

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1118)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/index-fgp-en.html, line 450 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6fQA558hggLXKaqqs:-KQ6fQA558hggLXKaqqt:b-3lxa05) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/index-fgp-en.html#L450)):*
> ```HTML
>                         <button onclick="getBookmark()">Get Link</button>
>                         <input type="text" id="bookmarkDisplay" style="width:100%;"></input>
>                         <button onclick="testBackToCart()">backToCart</button>
> ```

Inline Javascript :D

---

*[src/app/core/bookmark.service.js, line 83 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6hVtvBAhfVxnptlXi:-KQ6hVtwvyRf4o77WiVZ:b-agcftc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/bookmark.service.js#L83)):*
> ```JavaScript
>             // pull out non-layer info
>             const [basemap, x, y, zoom] = [1, 2, 3, 4].map(i => decode64(info[i]));
> ```

`const layer = info[5];`

---

*[src/app/core/config.service.js, line 346 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6iEeKKna9joi2cMqa:-KQ6iEeKKna9joi2cMqb:b-7s4sqq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/config.service.js#L346)):*
> ```JavaScript
>                             // if the key is wrong rcs will return null
>                             if (layerEntry) {
>                                 let layer = layerEntry.layers[0];
> ```

const

---

*[src/app/core/core.run.js, line 89 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6l6XmRVxNRq0F4Hme:-KQ6l6XmRVxNRq0F4Hmf:b-5z806j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/core.run.js#L89)):*
> ```JavaScript
>              */
>             function initialBookmark(bookmark) {
>                 const id = $rootElement.attr('id');
> ```

You can use `appInfo.id`

---

*[src/app/core/core.run.js, line 112 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6jcZalTT07YXvJVYa:-KQ6jcZbkEGzSwrJcGgv:b-ak69ja) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/core.run.js#L112)):*
> ```JavaScript
>                     sessionStorage.removeItem(id);
>                 } else {
>                     window.RV.getMap(id).loadRcsLayers(keys);
> ```

You can use `globalRegistry.getMap(id).loadRcsLayers(keys)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118)*

**Comment by spencerwahl** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 83 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6hVtvBAhfVxnptlXi:-KQ6mXbc9yF9T_cBnybW:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/bookmark.service.js#L83)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `const layer = info[5];`
</details>
Done.

---

*[src/app/core/config.service.js, line 346 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6iEeKKna9joi2cMqa:-KQ6m8_C0-UkqcxC-D_6:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/config.service.js#L346)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> const
</details>
Done.

---

*[src/app/core/core.run.js, line 89 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6l6XmRVxNRq0F4Hme:-KQ6mW6czkMlCZ5UBAA2:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/core.run.js#L89)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> You can use `appInfo.id`
</details>
Done.

---

*[src/app/core/core.run.js, line 112 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-KQ6jcZalTT07YXvJVYa:-KQ6mVgobAkOuurZhnfd:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/00be48a880e16eec61c9b16a3f03efa71a3e6b8d/src/app/core/core.run.js#L112)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> You can use `globalRegistry.getMap(id).loadRcsLayers(keys)`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118#-:-KQ6qMyVTI30D3vIzLgM:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1118)*

**Pull request merged**
