### PR TITLE
Api 12 (BasemapGroup, Basemap)

### LINKED ISSUE #2699: API Basemaps
Reference: http://fgpv-vpgf.github.io/fgpv-vpgf/api/classes/_index_d_.rv.ui.basemap.html

Extends off `LayerGroup` and accessible via `mapInstance.basemaps`. Changes should be reflected in the ui basemaps panel.

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2699.

Adds functionality for modifying basemaps (name, description, active) through the API.
Basemaps can also now be added / removed using the API.

## Testing
Some basic examples: (more detail can be found in documentation)
```js
RZ.mapInstances[0].ui.basemaps.allBasemaps // array of all basemaps

RZ.mapInstances[0].ui.basemaps.basemapAdded.subscribe(bm => console.log('basemap Added: ' + bm.id))
RZ.mapInstances[0].ui.basemaps.addBasemap({
    "id": "apiBasemap",
    "name": "API Added Basemap",
    "description": "This basemap was added through the API.",
    "altText": "altText - API Basemap",
    "layers": [
        {
            "id": "CBMT",
             "layerType": "esriFeature",
             "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer"
        }
    ],
    "tileSchemaId": "EXT_NRCAN_Lambert_3978#LOD_NRCAN_Lambert_3978"
}, true);


RZ.mapInstances[0].ui.basemaps.basemapRemoved.subscribe(bm => console.log('basemap Removed: ' + bm.id))
RZ.mapInstances[0].ui.basemaps.removeBasemap('baseSimple')

RZ.mapInstances[0].ui.basemaps.click.subscribe(bm => console.log('basemap clicked: ' + bm.id))

RZ.mapInstances[0].ui.basemaps.getBasemapById('baseNrCan').activeChanged.subscribe(a => console.log('active: ' + a))
RZ.mapInstances[0].ui.basemaps.setActive('baseNrCan')

RZ.mapInstances[0].ui.basemaps.getBasemapById('baseNrCan').name = "new name"
RZ.mapInstances[0].ui.basemaps.getBasemapById('baseNrCan').description = "new description"
```

## Documentation
https://jahidahmed.github.io/docs/api/developer/index.html

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 370 of 371 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/ui/basemap/basemap.directive.js, line 50 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717#-LCdZuHy1bTujJd3CQ67:-LCdZuHy1bTujJd3CQ68:b-7bdgz5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/88fa5333176c1b7568bed59219f237c6a60cf4e4/src/app/ui/basemap/basemap.directive.js#L50)):*
> ```JavaScript
>     events.$on(events.rvMapLoaded, () => {
>         const mapConfig = configService.getSync.map;
>         const allBasemaps = configService.getSync.map.basemaps;
> ```

`const allBasemaps = mapConfig.basemaps;`

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717)*

**Comment by JahidAhmed** [comment]
Review status: 370 of 371 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.directive.js, line 50 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717#-LCdZuHy1bTujJd3CQ67:-LCdbNsFA9l-xF_RT2tN:b-6mv472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/88fa5333176c1b7568bed59219f237c6a60cf4e4/src/app/ui/basemap/basemap.directive.js#L50)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`const allBasemaps = mapConfig.basemaps;`
</blockquote></details>

done thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717)*

**Comment by milesap** [comment]
I'm not sure about the `addBasemap` section, specifically the `tileSchemaId` and `layers`. I'm sure I need a lesson from James/you as to why it needs to be done this way vs. the planned implementation of `layers` taking an array of `configLayer` and possibly `simpleLayer`. Let me know, ty

---

Reviewed 368 of 371 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[package.json, line 30 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717#-LCeASjF8-lMbD34N04u:-LCeASjF8-lMbD34N04v:b4le48x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5a59f9199e74ee34afd3e34aff1df2c497cb620f/package.json#L30)):*
> ```JSON
>     "file-saver": "1.3.8",
>     "geoApi": "github:fgpv-vpgf/geoApi#v2.4.0-3",
>     "gsap": "1.20.4",
> ```

Remove please

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717#-:-LCeBRMSCFat5yxV8sIW:bnfribi)*

**Comment by james-rae** [comment]
I also looked at trying to utilize the basic layer classes for basemaps, but in the words of Mr Rogers, "They're special". Because we're using the ESRI basemap structures (which allow us to use the basemap gallery control to handle the swappage), there are too many differences to make it useful to combine the two.
The `tileSchemaId` allows us to group the basemaps by projection/level of detail, and instructs the map to initialize itself properly so that the tiles will fit on it.
The `layers` part is the structure that allows your basemap to be composed of multiple tile sets, but treated as one singular "unit" of basemap.

---







*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717#-:-LCiQZnZ3W9n747hXx6X:brlws9m)*

**Comment by milesap** [comment]
Sounds/looks good :star2: 

:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2717#-:-LCiyjpE3Sr6wBpjj4E1:b-giqcnd)*

**Pull request merged**
