### PR TITLE
fix(ui): make datatable header scrollable and more

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/237)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/237)*

**Comment by alyec** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/app/ui/filters/filters-default.directive.js, line 55 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/237#-K8e6TYYD8efyLX-t_wx:-K8e6TYYD8efyLX-t_wy:-1023732619) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd932ce7d6ff3ccf9f9238f9188cf218498bad33/src/app/ui/filters/filters-default.directive.js#L55)):*
const and split over two lines for readability (body of fulfill on second line)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/237)*

**Comment by AleksueiR** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 55 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/237#-K8e6TYYD8efyLX-t_wx:-K8e91baOHIFi80rEjKW:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fd932ce7d6ff3ccf9f9238f9188cf218498bad33/src/app/ui/filters/filters-default.directive.js#L55)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/237)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/237)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/237)*

**Pull request merged**
