### PR TITLE
feat(ui): escape key closes from history

### LINKED ISSUE #622: Closing the focused panel on `Esc` key
Right now all panels are closed on the `Esc` key.

The proposed solution is to create a history of focused panels (and anything else that can be closed) and, when `Esc` is pressed, close the currently focused panel setting focus to the previous item in the history.

Some thoughts:
- panel is added to the history as soon as it gets focus
- the same panel cannot be added twice (if it is already in the history, it's hoisted to the "top")
- closing a panel removes it from the history
- after closing a panel, focus is set to the next item in the history
- if history is empty, the focus is set to the map object (or maybe the main toolbar)

### PR DESCRIPTION
**Pull request by milesap**
Previously the escape key closed all panels. Now the escape key only
closes one panel, the most recent one opened. Focus is set on an opening
panel and restored to the previous panel on close.

Closes #622

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/751)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Couple things from testing:
- Opening up filters, clicking on the tiny menu (the one with all the morphs) and selecting anything causes the filters panel to not close on esc
- details panel only minimizes, not sure what the behaviour should be

<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### feat\(ui\): escape key closes from history
> 
> Previously the escape key closed all panels. Now the escape key only
> 
> closes one panel, the most recent one opened. Focus is set on an opening
> 
> panel and restored to the previous panel on close.
> 
> 
> 
> Closes #622
> 
> 
> 
</details>


---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-:-KJuuaB9bG2FAK7TJM21:-1000099836)*

**Comment by spencerwahl** [comment]
One more: opening up legend, then details, then clicking on legend again closes the main panel instead of opening the legend.

<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> Couple things from testing:
> - Opening up filters, clicking on the tiny menu (the one with all the morphs) and selecting anything causes the filters panel to not close on esc
> - details panel only minimizes, not sure what the behaviour should be
</details>


---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-:-KJuvd2LkSrxhgCmohTV:-759412966)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 131 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJuapXWHHHXFcjrVjBC:-KJuapXWHHHXFcjrVjBD:1777898944) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.js#L131)):*
> ```JavaScript
>          * Close the most recently opened panel.
>          *
>          * @return  {Promise}   resolves when a panel has finished its closing animation
> ```

I noticed the `$q.resolve(true)` does the value passed to the promise indicate anything specific?  If not `resolve()` might be better.

---

*[src/app/common/router/statemanager.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJuyZjgV8PDC5B8BRaj:-KJuyZjgV8PDC5B8BRak:2000389212) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.js#L288)):*
> ```JavaScript
>             if (typeof panelToClose.item.parent === 'undefined') {
>                 animationPromise = setItemProperty(panelToClose.name, 'active', false)
>                     .then(() => propagate ? getChildren(panelToClose.name)
> ```

The indentation here makes it hard to read the conditional.

---

*[src/app/common/router/statemanager.service.js, line 295 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJuxIXNAulj3gx-wipa:-KJuxIXNAulj3gx-wipb:-567567740) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.js#L295)):*
> ```JavaScript
>                 if (propagate) {
>                     // replace with sibling from history if exists and keep parent panel open
>                     for (let i = 0; i < panelHistory.length; i++) {
> ```

Style suggestion, use `map` and `find` instead of `for` and `if`.
```js
subPanel = panelHistory
  .map(item => getItem(item))
  .find(subPanel => subPanel.name !== panelToClose.name && subPanel.item.parent === panelToClose.item.parent);
if (subPanel) {
  closePanel(panelToClose, false);
  return setItemProperty(subPanel.name, 'active', true, true);
}
closePanel(getParent(panelToClose.name), false);
```

---

*[src/app/common/router/statemanager.service.spec.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJue2VelSPMWL6wbr0y:-KJue2VfizdD-9rskdeE:-1173662331) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.spec.js#L15)):*
> ```JavaScript
>         // check that controller is created
> 
>         xit('should be created successfully', () => {
> ```

needs comments about why the tests are disabled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by milesap** [comment]
I'll provide a fix for point #1, it occurs whenever focus is moved outside the rootElement (in this case by the context menu) and focus is not restored. 

For points #2,3 I have this as expected behavior. I'm open to suggestions on changing this logic.

<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> One more: opening up legend, then details, then clicking on legend again closes the main panel instead of opening the legend.
</details>


---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-:-KJv-o25k8rmTKu2SO_d:-333758982)*

**Comment by milesap** [comment]
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 131 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJuapXWHHHXFcjrVjBC:-KJvTYXB7bDijA84wfAA:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.js#L131)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I noticed the `$q.resolve(true)` does the value passed to the promise indicate anything specific?  If not `resolve()` might be better.
</details>
:+1: 

---

*[src/app/common/router/statemanager.service.js, line 295 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJuxIXNAulj3gx-wipa:-KJvTb2mKW1UMUu2CztW:1295655087) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.js#L295)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Style suggestion, use `map` and `find` instead of `for` and `if`.
> ```js
> subPanel = panelHistory
>   .map(item => getItem(item))
>   .find(subPanel => subPanel.name !== panelToClose.name && subPanel.item.parent === panelToClose.item.parent);
> if (subPanel) {
>   closePanel(panelToClose, false);
>   return setItemProperty(subPanel.name, 'active', true, true);
> }
> closePanel(getParent(panelToClose.name), false);
> ```
</details>
much better, will use more often going forward

---

*[src/app/common/router/statemanager.service.spec.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJue2VelSPMWL6wbr0y:-KJvTlD6gPZO2G60Z87P:-987217403) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.spec.js#L15)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> needs comments about why the tests are disabled
</details>
Found the issue with the tests, fixed now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/common/router/statemanager.service.spec.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJue2VelSPMWL6wbr0y:-KJvYSmboeSLodFZnaW6:-73704995) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.spec.js#L15)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Found the issue with the tests, fixed now
</details>
Some samples for failing explicitly when the promise chain throws an exception (these will not be exposed in the jasmine test and it looks like a silent failure otherwise): https://github.com/fgpv-vpgf/geoApi/blob/develop/spec/layerSpec.js#L32

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by AleksueiR** [comment]
Please, do not modify existing behaviour. Spencer's points 2 and 3 are valid: details panel should close on Esc and "close" button; main panel should not close when switching between details and layers.

Also, if the settings/metadata panel is opened, closing main panel should first close the metadata/settings panel and then close the main panel, not close both simultaneously.

---

Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-:-KKEcVpcqX_1giAUmNR0:-606932491)*

**Comment by milesap** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/common/router/statemanager.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJuyZjgV8PDC5B8BRaj:-KKIj_DC_8K19LsBuTN0:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.js#L288)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> The indentation here makes it hard to read the conditional.
</details>
:+1: 

---

*[src/app/common/router/statemanager.service.spec.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJue2VelSPMWL6wbr0y:-KKIjVCA2vqL2_UHTT-K:-605279209) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.spec.js#L15)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Some samples for failing explicitly when the promise chain throws an exception (these will not be exposed in the jasmine test and it looks like a silent failure otherwise): https://github.com/fgpv-vpgf/geoApi/blob/develop/spec/layerSpec.js#L32
</details>
Tests are now working

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3, 1 of 3 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 7 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/app/common/router/statemanager.service.js, line 288 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-KJuyZjgV8PDC5B8BRaj:-KKnMuku63JvF9iwX6mK:1475865881) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd37f15e076ec30d4eb250789d72c5972683de67/src/app/common/router/statemanager.service.js#L288)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> :+1: 
</details>
The indentation on the `.then` is off
```js
animationPromise = setItemProperty(panelToClose.name, 'active', false)
    .then(() => 
        propagate ? getChildren(panelToClose.name).forEach(child => closePanel(child, false))
                  : true
    );

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by AleksueiR** [comment]
The details panel is still hidden on `close/Esc`, not closed.

One more:
- open `Setting` for a layer
- open `Metadata` for a different layer
- press `Esc`

This will switch from `Metadata` to previously opened `Settings`. Instead it should close the side panel as if the close button was clicked.

---

Reviewed 1 of 7 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-:-KKnPJdZl-qBVnkBZ618:-1291927042)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r9.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/751#-:-KKsQXcBI4fvRebrYXin:1417088721)*

**Pull request merged**
