### PR TITLE
1258 export size finale

### LINKED ISSUE #1258: User chooses Map Export Image Size
Give the user an option to pick the image size:
- current map size
- 720p (to be shown as "{$width} x 720" where `width` is calculated using viewer's width/height ratio
- 1080p
- custom height entered by the user (
- [optional/for later] let the config author specify custom presets in the config

Do not scale legend text.

There are two main options of doing this:
- asking user to select the size upfront and then start a print task; 
- defaulting to some size and starting a print task right away; if the user changes the size, need to restart the print job;

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Adds export size selector to the export dialog (the size selected is the size of the map image, not the full legend image):

- current map size (default option; it's selected when the export dialog is opened for the first time)
- small size (720p)
- medium size (1080p)
- custom size (user enters either height or width, the other dimension will be calculated based on the width/height ratio of the map object)
  - width min/max - 489/3300 px
  - height min/max - 320/2160 px (support for QVGA through 4K resolutions) (this is somewhat arbitrary restriction) (WMS have problems with images larger than ~2000px in width)
- export dialog remember the last size option selected

Also:

- the settings panel is added where the user can turn off certain parts of the export image at will
- the settings panel is configurable through the config (export components can be locked in)
- the settings panel will only be available there is at least one user-selectable option (not locked)
- north arrow and scalebar share a single toggle in the settings panel
- new export components can be easily added
- because PR is large, will bring muffins if someone comments "muffins" today
- all changes to the settings persist (through projection change as well) (unless a new config is loaded)

There are several know issues I haven't fixed because I really want this PR to get merged already. Will create separate github issue for those today.

## Testing
Lots of eyeballing.

## Documentation
Lots of source comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

Closes #1258

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1445)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445)*

**Comment by milesap** [comment]
Reviewed 17 of 17 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445)*

**Comment by ChrisLatRNCan** [comment]
Do you include the lengend dimensions in the size ?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlFtgq8vUYOjrVVDYM:b-xw8wka)*

**Comment by AleksueiR** [comment]
No, the size is just for the map image.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlH8O_bHOmVVXETnuo:bb3aelt)*

**Comment by ChrisLatRNCan** [comment]
So we are expecting bigger dimensions for the exported image ?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlHOhfSXsb0vXcrHZV:b1ahzlc)*

**Comment by AleksueiR** [comment]
Yes, the end size of the image will depend on the map image size, legend, footnote, title, etc. It's not possible to predict the end size until the image is generated since the legend needs to be redrawn when the width of the image changes.

I think we need to include some sort of explanation what this size is. It might confuse the users.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlHeaWTEEIwV1OkDu5:b-6kkgd6)*

**Comment by ChrisLatRNCan** [comment]
When it works, it works as expected but there some problems:
Chrome
http://fgpv.cloudapp.net/demo/users/AleksueiR/1258-export-size-finale/dev/samples/index-one.html works
http://fgpv.cloudapp.net/demo/users/AleksueiR/1258-export-size-finale/dev/samples/index-fgp-en.html is hanging. 

Firefox
http://fgpv.cloudapp.net/demo/users/AleksueiR/1258-export-size-finale/dev/samples/index-one.html is hanging

IE11
http://fgpv.cloudapp.net/demo/users/AleksueiR/1258-export-size-finale/dev/samples/index-one.html works

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlJQm8s_Zv0bJMZlLn:b-8lfqs2)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445)*

**Comment by AleksueiR** [comment]
Chrome hanging should be resolved now. It was happening because legend graphic generator tried to create a legend image when the legend had no layers.

---

Review status: 16 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlYVesytj3aP-tRzaX:b-8k5nu7)*

**Comment by ChrisLatRNCan** [comment]
Chrome
index-fgp-en.html is now :thumbsup: 
Firefox
index-one.html is hanging same error as previous built

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlahLR8K_Yh7GlSL8y:b-x54q18)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445)*

**Comment by AleksueiR** [comment]
Ok, good. Firefox error will be fixes by a geoApi patch.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1445#-:-KXlcPn8qF5l1U4Yo-1Y:b-rn88ho)*

**Comment by dan-bowerman** [comment]
muffins

**Pull request merged**
