### PR TITLE
chore(build): plugins v3.0.0-3

### PR DESCRIPTION
**Pull request by spencerwahl**
## Description

Re-includes plugin repo fixes. Table should open properly again.

## Testing

any sample

### Checklist

- [ ] works in IE11
- [ ] works in Edge
- [ ] works with projection change
- [ ] works with language change
- [ ] works via config file
- [ ] works via wizard
- [ ] works via API
- [ ] works via RCS
- [ ] works via bookmark load
- [ ] works in auto-legend
- [ ] works in structured legend
- [ ] works on layer reload
- [x] datagrid works
- [ ] identify works

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated
- [ ] original issue has been reviewed & updated to reflect the PR content

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3420)

### CODE REVIEW

**Comment by james-rae** [comment]
Table not doing what it should.  Service based feature doesn't make it past the `###/###` loading screen.  GeoJSON file will hit the max load count, then start increasing upwards (e.g. `20/3`)

**Comment by spencerwahl** [comment]
Do those issues happen in the current develop as well?

**Comment by james-rae** [comment]
Not when i `npm run serve` locally

**Comment by james-rae** [comment]
But `develop` build on cloudapp has issues

**Comment by JahidAhmed** [comment]
@james-rae it's WOMM, were you trying the prod build? The dev build works, but there have been a bunch of issues with the prod one recently

**Comment by james-rae** [comment]
yep all issues are on `prod` build, `dev` seems to be working

**Pull request merged**
