### PR TITLE
feat(build): implement webpack for builds

### PR DESCRIPTION
**Pull request by milesap**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1901)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 246 of 246 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 246 files at r1.
Review status: 212 of 217 files reviewed at latest revision, 1 unresolved discussion.

---

*[webpack.common.js, line 97 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3YS4YgWdPs_pE1M59:-Kl3YS4YgWdPs_pE1M5A:bxtgmle) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d5a971af5cd9a40149b265860ff785a703976d3/webpack.common.js#L97)):*
> ```JavaScript
> 
>         devServer: {
>             historyApiFallback: true,
> ```

Can you add
```js
host: '0.0.0.0',
```
here?

It doesn't work properly inside Vagrant without it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Comment by milesap** [comment]
Review status: 206 of 219 files reviewed at latest revision, 1 unresolved discussion.

---

*[webpack.common.js, line 97 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3YS4YgWdPs_pE1M59:-Kl3_bartIECtYD2nYAe:bo00mth) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d5a971af5cd9a40149b265860ff785a703976d3/webpack.common.js#L97)):*
> host: '0.0.0.0',
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Comment by AleksueiR** [comment]
Reviewed 232 of 246 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[webpack.common.js, line 97 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3YS4YgWdPs_pE1M59:-Kl3dDCKtvjCuaGRG30-:b-bsirlh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d5a971af5cd9a40149b265860ff785a703976d3/webpack.common.js#L97)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

> host: '0.0.0.0',
:+1: 
</blockquote></details>

And also `publicPath: '/build/',` for consistency with how pages are served right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[webpack.common.js, line 56 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3omMjhRNaT84RsPAY:-Kl3omMjhRNaT84RsPAZ:bf756g8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d566a04d37f561de63b23a5d06493499c6eb5c0/webpack.common.js#L56)):*
> ```JavaScript
>                     test: /\.(png|svg)$/,
>                     use: 'url-loader'
>                 },
> ```

Dangling comma.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Comment by AleksueiR** [comment]
hm, help seems to be broken - I get a blank panel.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-:-Kl3q9bES25WFQugaP44:b2fz0tw)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/polyfill/ie-promise.js, line 1 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3qP2uBcbMy551bkMX:-Kl3qP2uBcbMy551bkMY:bcp88oo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/065e1b0d52cf24502968a0087b49cb516ce837b1/src/polyfill/ie-promise.js#L1)):*
> ```JavaScript
> /*!
> ```

What happened to IE-promise?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Comment by milesap** [comment]
This is on `develop` branch, not webpack issue (did you open an issue for it?)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[webpack.common.js, line 97 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3YS4YgWdPs_pE1M59:-Kl41Mu1vWn8X7yAbBSA:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d5a971af5cd9a40149b265860ff785a703976d3/webpack.common.js#L97)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

And also `publicPath: '/build/',` for consistency with how pages are served right now.
</blockquote></details>

:+1: 

---

*[webpack.common.js, line 56 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3omMjhRNaT84RsPAY:-Kl40iLE3h5cFjpfeVsW:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d566a04d37f561de63b23a5d06493499c6eb5c0/webpack.common.js#L56)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Dangling comma.
</blockquote></details>

:+1: 

---

*[src/polyfill/ie-promise.js, line 1 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-Kl3qP2uBcbMy551bkMX:-Kl40wES1mfimCTY5c4w:b-eqrha6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/065e1b0d52cf24502968a0087b49cb516ce837b1/src/polyfill/ie-promise.js#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

What happened to IE-promise?
</blockquote></details>

It is now an npm package `es6-promise` loaded in `src/polyfill/polyfill-loader.js` on output path `ie-polyfills.js`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-:-Kl40SbhPskuei3KF-GX:b-qn1doo)*

**Comment by AleksueiR** [comment]
Yeap, I have the fix ready to go after this merges.
:lgtm: 

---

Reviewed 1 of 4 files at r5.
Review status: 216 of 219 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901#-:-Kl45TIPDbC9zVkl1yZ8:b-jl7kh6)*

**Comment by james-rae** [comment]
Reviewed 1 of 246 files at r1, 5 of 5 files at r2, 4 of 6 files at r3, 4 of 4 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1901)*

**Pull request merged**
