### PR TITLE
Details templates

### PR DESCRIPTION
**Pull request by spencerwahl**
## Description
Adds details panel templating functionality.

Adds 2 config properties to layers; templateUrl and parserUrl to allow config builders to customize identify output.

Templates are angular templates and parsers are plain javascript functions.

## Testing
Config 69 in index-samples

## Documentation
`details_templates` in the docs folder

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- ~[ ] Release notes have been updated~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl and @james-rae)

---

*[src/app/ui/details/details-record-html.directive.js, line 47 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6TJ2v0vzBzymyCFKo:-LG6TJ2v0vzBzymyCFKp:bfota11) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/25ecd2345a227eb591a38e2507da441a558eb083/src/app/ui/details/details-record-html.directive.js#L47)):*
> ```JavaScript
>         // get template to override basic details output, null/undefined => show default
>         self.templateUrl = l.config._source.templateUrl;
>         if (l.config._source.parserUrl) {
> ```

To diminish the pyramid of doom, you can go with `if (!l.config._source.parserUrl) { return; }` and then run the logic parsing the result.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814)*

**Comment by AleksueiR** [comment]
Reviewed 7 of 7 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814)*

**Comment by james-rae** [comment]
Reviewed 9 of 15 files at r1, 7 of 7 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @spencerwahl)

---

*[schema.json, line 556 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6W_sE49jbSok3YywN:-LG6W_sE49jbSok3YywO:b-qrfzrw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50288972af8093561afa831c104c3791d8141e74/schema.json#L556)):*
> ```JSON
>                 "disabledControls": { "$ref": "#/definitions/legendEntryControls", "description": "A list of controls which are blocked from modification either by the user or programmatically. These controls can be visible or not as defined in the `controls` array." },
>                 "state": { "$ref": "#/definitions/initialLayerSettings" },
>                 "templateUrl": { "type": "string"}
> ```

can we add description tags?  should these have a default of empty string?

---

*[docs/user/details_templating.md, line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6Wx-a2ka8IOprBJrl:-LG6Wx-a2ka8IOprBJrm:bon1ana) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50288972af8093561afa831c104c3791d8141e74/docs/user/details_templating.md#L5)):*
> ```Markdown
> There are 2 config attributes that are needed:
> 
> **templateUrl** is needed for any type of layer that wants a template, this is an *absolute* path to your template.
> ```

any way to make these relative?  it's not the end of the world but is an extra step for any type of deployment / copying an example folder.
* edit looking at the sample file, it seems they are relative to the site.  Should we be using the word "relative"? (e.g. going by https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/ )

---

*[src/app/ui/details/details-record-text.directive.js, line 45 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6YxRf7DC9ylfR-tp0:-LG6YxRf7DC9ylfR-tp1:bb7fuop) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50288972af8093561afa831c104c3791d8141e74/src/app/ui/details/details-record-text.directive.js#L45)):*
> ```JavaScript
>         // get template to override basic details output, null/undefined => show default
>         self.templateUrl = l.config._source.templateUrl;
>         
> ```

evil

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814)*

**Comment by spencerwahl** [comment]
Review status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @AleksueiR, @james-rae, and @spencerwahl)

---

*[schema.json, line 556 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6W_sE49jbSok3YywN:-LG6eALn56OGO7iThpyI:bmbjihs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50288972af8093561afa831c104c3791d8141e74/schema.json#L556)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can we add description tags?  should these have a default of empty string?
</blockquote></details>

Description added, default is not needed.

---

*[docs/user/details_templating.md, line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6Wx-a2ka8IOprBJrl:-LG6e4ze1kLthClShz-A:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50288972af8093561afa831c104c3791d8141e74/docs/user/details_templating.md#L5)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

any way to make these relative?  it's not the end of the world but is an extra step for any type of deployment / copying an example folder.
* edit looking at the sample file, it seems they are relative to the site.  Should we be using the word "relative"? (e.g. going by https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/ )
</blockquote></details>

done

---

*[src/app/ui/details/details-record-html.directive.js, line 47 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6TJ2v0vzBzymyCFKo:-LG6aZ-q-Tvgtyt6lT7n:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/25ecd2345a227eb591a38e2507da441a558eb083/src/app/ui/details/details-record-html.directive.js#L47)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

To diminish the pyramid of doom, you can go with `if (!l.config._source.parserUrl) { return; }` and then run the logic parsing the result.
</blockquote></details>

done

---

*[src/app/ui/details/details-record-text.directive.js, line 45 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-LG6YxRf7DC9ylfR-tp0:-LG6e60L0bgKhg4IW_Nw:b8iquyc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/50288972af8093561afa831c104c3791d8141e74/src/app/ui/details/details-record-text.directive.js#L45)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

evil
</blockquote></details>

BEGONE FOUL SPACES

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814#-:-LG6eenb-In2RObECjXh:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2814)*

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. As expected.

**Pull request merged**
