### PR TITLE
Fix up the tool header in index-sample

### PR DESCRIPTION
**Pull request by barryytm**
## Description

As title
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2339
## Testing

Manually in `index-samples.html`
## Documentation

`sample-index.tpl`
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2341)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2341)*

**Comment by AleksueiR** [comment]
Looks cool :+1: 

Can you make the button a bit wider and a bit more visible - say 150px and 0.5 opacity - and have the panel to be opened by default, since that's the main feature of this page? 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2341#-:-KsK9tKGZy0DdpeXmB_4:bteh3dc)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2341)*

**Comment by AleksueiR** [comment]
Nice :medal_sports:  :lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2341#-:-KsKRmMBfP0xgJs9ZLuo:b-dy17h7)*

**Pull request merged**
