### PR TITLE
feat(export): enable export legend optimization

### LINKED ISSUE #1371: Connect geoApi export legend optimization
geoApi provides some additional logic to optimizing export legend wrapping. See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1271 for details.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Enables export legend optimization from https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1271.

## Testing
Eyeballing tests. Unit tests for optimization logic are done in geoApi under https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1271.

## Documentation
Updated comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Closes #1371

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1372)

### CODE REVIEW

**Comment by alyec** [comment]
Test page works

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-KWZRwZAHETJetzWMM-_:-KWZRwZAHETJetzWMM-a:bbl8cz4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc42e3f56f10c0071f0679e2feceddbb849729ef/src/app/ui/export/export-legend.service.js#L48)):*
> ```JavaScript
>          * @param {Number} availableHeight map height, used in legend wraping logic
>          * @param {Number} availableWidth width of the legend graphic, should match width of the exported map image
>          * @param {Number} prefferedSectionWidth width of the individual legend sections inside the legend graphic
> ```

Didn't notice before but change you change to `preferredSectionWidth`?

---

*[src/app/ui/export/export-legend.service.js, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-KWZSNvGBH1o-mP13xF5:-KWZSNvH2eelT7-c6Qna:bbqj186) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc42e3f56f10c0071f0679e2feceddbb849729ef/src/app/ui/export/export-legend.service.js#L75)):*
> ```JavaScript
>             let sectionsUsed = null;
> 
>             // keep optimizing until the number of used sections differs from the number of available sections
> ```

I think you mean keep optimizing *while* ...

---

*[src/app/ui/export/export-legend.service.js, line 114 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-KWZT3LizdTubY3a7vKZ:-KWZT3LizdTubY3a7vK_:b-7o7w5y) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc42e3f56f10c0071f0679e2feceddbb849729ef/src/app/ui/export/export-legend.service.js#L114)):*
> ```JavaScript
>             return generationPromise;
> 
>             function getSectionWidth() {
> ```

jsdoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-:-KWZUSJgaMKliyJv1jdd:bc0xb96)*

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-KWZRwZAHETJetzWMM-_:-KWbxFG_JLiouG0rBW2b:b-dd4ods) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc42e3f56f10c0071f0679e2feceddbb849729ef/src/app/ui/export/export-legend.service.js#L48)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Didn't notice before but change you change to `preferredSectionWidth`?
</details>
ha-ha, done.

---

*[src/app/ui/export/export-legend.service.js, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-KWZSNvGBH1o-mP13xF5:-KWbxJ9CIjbrDAHdLYSd:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc42e3f56f10c0071f0679e2feceddbb849729ef/src/app/ui/export/export-legend.service.js#L75)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think you mean keep optimizing *while* ...
</details>
Done.

---

*[src/app/ui/export/export-legend.service.js, line 114 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-KWZT3LizdTubY3a7vKZ:-KWbx_7qhkTnnpN0Il5U:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc42e3f56f10c0071f0679e2feceddbb849729ef/src/app/ui/export/export-legend.service.js#L114)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372)*

**Comment by milesap** [comment]
Tested in chrome, FF, IE, and on iPhone. Gazed over code :lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-:-KWcrlma9gz6FsC-KGGP:b-at64cg)*

**Comment by alyec** [comment]
^ testing :trophy: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-:-KWcs8SQN4cwabJoqjTI:b-l0v8x3)*

**Comment by AleksueiR** [comment]
:lgtm:  for iphone testing!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-:-KWcsDJm8_61XRnqrMBF:bsz2dgk)*

**Comment by AleksueiR** [comment]
^ I was supposed to be :+1: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-:-KWcss-l9gHl-_yll7JS:b-ecso8o)*

**Comment by alyec** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1372#-:-KWcuZTm4PQiVdpmjqS6:bnfp4nl)*

**Pull request merged**
