### PR TITLE
1267 integrating map export with ui

### LINKED ISSUE #1267: Integrate Print Service and the UI
- [x] Need to get print images from geoApi code;
- [x] position them correctlly in the export dialog (image-based layers, then svg-based layers) so there no jumping to abrup resizing when images load;
- [x] display legend graphic in response to legend switch underneath the map export;
- [x] fuse together print images and legend graphic;
- [x] add [FileSaver](https://github.com/eligrey/FileSaver.js/) library to actually save the generated image on user's computer.
- [x] add title field to the export dialog
- [x] add error handling

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #1267

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1280)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 10 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSEuyRhD5hSTpK0hjs:-KUSEuySjXzICMtVsUjv:b-vb4m6i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export-legend.service.js#L48)):*
> ```JavaScript
>          * @param {Number} availableWidth width of the legend graphic, should match width of the exported map image
>          * @param {Number} prefferedSectionWidth width of the individual legend sections inside the legend graphic
>          * @return {Promise} promise with resovles with a canvas containing the legend
> ```

typo: resolves

---

*[src/app/ui/export/export.service.js, line 110 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSG5-DQeOUuYtcKLTi:-KUSG5-E8vuEUCm4RvD4:b7tcvxy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export.service.js#L110)):*
> ```JavaScript
> 
>                 // store graphic with service layers so it is bound to the ui
>                 $q.resolve(serverPromise).then(canvas =>
> ```

I thought geoApi wraps the promises correctly?

---

*[src/app/ui/export/export.service.js, line 247 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSICe0y5T2-bWeOzyO:-KUSICe0y5T2-bWeOzyP:bc62ash) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export.service.js#L247)):*
> ```JavaScript
>                  * @private
>                  * @function drawMapShell
>                  * @return {Promise} promise resolving with a shell graphic
> ```

The resolve seems to have some additional metadata about offsets as well, can you add that here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Comment by AleksueiR** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/export/export-legend.service.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSEuyRhD5hSTpK0hjs:-KUSMTDxIFWSslFyjQqD:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export-legend.service.js#L48)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: resolves
</details>
Done.

---

*[src/app/ui/export/export.service.js, line 110 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSG5-DQeOUuYtcKLTi:-KUSLw0ExQeckLR3BZ0n:bdg9rxf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export.service.js#L110)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I thought geoApi wraps the promises correctly?
</details>
It does, but we need to trigger another digest cycle to update the bindings. Easiest way here is to use `$q.resolve`, but `$timeout` or `$applyAsync` would also work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Comment by AleksueiR** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/export/export.service.js, line 247 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSICe0y5T2-bWeOzyO:-KUSNFESW6tL0WkApgTR:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export.service.js#L247)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> The resolve seems to have some additional metadata about offsets as well, can you add that here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/export/export.service.js, line 110 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSG5-DQeOUuYtcKLTi:-KUSNi0tqudKerN1PjbY:b845mda) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export.service.js#L110)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> It does, but we need to trigger another digest cycle to update the bindings. Easiest way here is to use `$q.resolve`, but `$timeout` or `$applyAsync` would also work.
</details>
Can you add this to the comment so someone like me doesn't try to refactor this at some point in the future?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Comment by AleksueiR** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/export/export.service.js, line 110 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-KUSG5-DQeOUuYtcKLTi:-KUSOQvlRsFEBN4Us4qf:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f18ab754db3b44646a661bce0855475bbc913ba7/src/app/ui/export/export.service.js#L110)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you add this to the comment so someone like me doesn't try to refactor this at some point in the future?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-:-KUSOfhqbZXQJNkJsUYF:bnfp4nl)*

**Comment by james-rae** [comment]
Do we need to add `exportMapUrl` to the french and the two fgp config files?  The testers will be using the fgp pages.

---

Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-:-KUSOkY4_KuvqMRn3BZl:b-76439u)*

**Comment by AleksueiR** [comment]
Good point. Done.

---

Review status: 10 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280#-:-KUSPNr273unnCvxogvz:b-qu6n94)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1280)*

**Pull request merged**
