### PR TITLE
Add space between heading and slider in the opacity setting block

### LINKED ISSUE #2020: IE Alignment issue under Settings
Tested build :http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html

Browser : IE11

image

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes #2020 as title
## Testing

Manually
## Documentation

NA
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2220)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/content/styles/modules/_setting-controls.scss, line 51 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220#-KpVYV_R9NLJnoFMRNJW:-KpVYV_R9NLJnoFMRNJX:b-tct29z) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27106d2e1af98f7c6a9339c793dbb5ee298a11d8/src/content/styles/modules/_setting-controls.scss#L51)):*
> ```SCSS
> @mixin slider-setting {
>     .rv-slider {
>         display: block;
> ```

This works, but it's usually better to use display flex since it gives you more control. 

---

*[src/content/styles/modules/_setting-controls.scss, line 65 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220#-KpVY0w6jsstiQO_HDsY:-KpVY0w6jsstiQO_HDsZ:b-p7c9dh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/27106d2e1af98f7c6a9339c793dbb5ee298a11d8/src/content/styles/modules/_setting-controls.scss#L65)):*
> ```SCSS
> 
>         .rv-slider-body {
>             flex: 1;
> ```

Better to update `flex` to `flex: 1 1 auto;` here. In IE, `flex: 1` is expanded into `flex: 1 1 0px`. That `0px` what is causing the block to collapse. Setting it to `auto` forces IE to properly calculate the size of the flex block. With this, you don't need to change display to block on the parent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220)*

**Comment by barryytm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_setting-controls.scss, line 51 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220#-KpVYV_R9NLJnoFMRNJW:-KpVbfuerdnkXdZ9G2d2:b-r18wie) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f518e571287ed8510cb6fe832405acaf9f18680d/src/content/styles/modules/_setting-controls.scss#L51)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This works, but it's usually better to use display flex since it gives you more control. 
</blockquote></details>

done, thanks.

---

*[src/content/styles/modules/_setting-controls.scss, line 65 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220#-KpVY0w6jsstiQO_HDsY:-KpVbj0ejVYl_9_Ve1L0:b-r18wie) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f518e571287ed8510cb6fe832405acaf9f18680d/src/content/styles/modules/_setting-controls.scss#L65)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Better to update `flex` to `flex: 1 1 auto;` here. In IE, `flex: 1` is expanded into `flex: 1 1 0px`. That `0px` what is causing the block to collapse. Setting it to `auto` forces IE to properly calculate the size of the flex block. With this, you don't need to change display to block on the parent.
</blockquote></details>

done, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2220#-:-KpVcKpRV1k4DQxEPatI:bnfp4nl)*

**Pull request merged**
