### PR TITLE
chore(build): update webpack from 3 -> 4, rxjs 5 -> 6, and more

### PR DESCRIPTION
**Pull request by milesap**
## Description
- Minor changes to build process for webpack 4 support
- Minor changes to support rxjs 6.1 (from v5)
- Removed out dated protractor scripts
- General version bumps of all deps
- Slight production build size decrease, likely faster builds as well

## Testing
Chrome, IE. Additional 👀 needed to rule out additional side effects of upgrades

## Documentation
None

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Don't we need to add `rxjs-compat` dependencies until we migrate all the 5.x code to 6.x?

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708#-:-LC4NIyX4VbH5C3DQiZW:b-u0igu3)*

**Comment by milesap** [comment]
I did the migration, which was the change from chaining functions to piping. 

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708#-:-LC4OHUV92i8NLrXpmIl:byotiwz)*

**Comment by AleksueiR** [comment]
:+1: 

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708#-:-LC4Pus21wqOye0OlVFz:b-8fx2u7)*

**Comment by AleksueiR** [comment]
`dev` sample pages don't seem to work :/ 


---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708#-:-LC4wXXk8YYNwCYO5XnC:b-inq71t)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708)*

**Comment by milesap** [comment]
Will update geoApi tag version prior to merge, see https://github.com/fgpv-vpgf/geoApi/pull/295

**Comment by JahidAhmed** [comment]
Reviewed 12 of 16 files at r1, 2 of 3 files at r2, 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708)*

**Comment by AleksueiR** [comment]
:lgtm:

Both prod and dev are loading now. :+1: 

---

Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2708#-:-LCA4YQJ0hgQvxMAhJRH:b-2mt5vn)*

**Pull request merged**
