### PR TITLE
Add group layer import

### PR DESCRIPTION
**Pull request by cynngah**
#929

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1044)

### CODE REVIEW

**Comment by james-rae** [comment]
*[src/app/geo/layer-blueprint.class.js, line 192 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044#-KOjmb4tDisu6DXBFiJy:-KOjmb4tDisu6DXBFiJz:bcd5ynu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ae33335388d6fbc140174045e5298de9dcefd0f6/src/app/geo/layer-blueprint.class.js#L192)):*
> ```JavaScript
>                         // some custom processing of Dynamic layers to let the user option to pick sublayers
>                         if (this.serviceType === Geo.Service.Types.DynamicService) {
>                             const lastIndex = this.config.url.substring(this.config.url.lastIndexOf('/') + 1);
> ```

comment on this section explaining what/why we're doing stuff.  E.g. `Check if URL is a group layer (ends with an integer). If so, pre-select any items in the group`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044)*

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044)*

**Comment by james-rae** [comment]
*[src/app/geo/layer-blueprint.class.js, line 192 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044#-KOjmb4tDisu6DXBFiJy:-KOkNazsZIeF8wn_NpQH:b-fycf06) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ae33335388d6fbc140174045e5298de9dcefd0f6/src/app/geo/layer-blueprint.class.js#L192)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> comment on this section explaining what/why we're doing stuff.  E.g. `Check if URL is a group layer (ends with an integer). If so, pre-select any items in the group`
</details>
Also, since your geoApi is now returning the index, you can test for existence of `.groupIdx` and use it rather than stripping the URL again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044)*

**Comment by spencerwahl** [comment]
when loading http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/0 both `Nature` and all children under `Nature` are selected, doubling the entries in the legend

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044#-:-KOp1EPTurw_GJ9QYuRu:b-qeglnv)*

**Comment by alyec** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044)*

**Comment by cynngah** [comment]
True I thought that just imported once. thx :+1: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044#-:-KOp6nzCGM9W5-Aum7fD:b-vur63j)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1044)*

**Pull request merged**
