### PR TITLE
Use the new state manager for morph

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/92)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/common/morph.directive.js, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92#-K5ByaWo-KFl53TvGXKD:-K5ByaWo-KFl53TvGXKE:1345846472) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16f7050ddfb1cfe0b513e98341e7c919ca7ea902/src/app/ui/common/morph.directive.js#L39)):*
No need for `multipleElement` attribute.

From the [Angular docs](https://docs.angularjs.org/api/ng/service/$compile#-multielement-):

 > multiElement

> When this property is set to true, the HTML compiler will collect DOM nodes between nodes with the attributes directive-name-startand directive-name-end, and group them together as the directive elements. It is recomended that this feature be used on directives which are not strictly behavioural (such as ngClick), and which do not manipulate or replace child nodes (such as ngInclude).

---

*[src/app/ui/common/morph.directive.js, line 58 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92#-K5Bz4uvF04G9Me1vTmg:-K5Bz4uvF04G9Me1vTmh:2131704994) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16f7050ddfb1cfe0b513e98341e7c919ca7ea902/src/app/ui/common/morph.directive.js#L58)):*
Can you remove this line and see if it's working? It might not be necessary since the watch expression should pick up the stateManager variable anyway.

---

*[src/app/ui/toc/toc.controller.js, line 18 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92#-K5BzMIjSf6Ev0d2Y1gP:-K5BzMIjSf6Ev0d2Y1gQ:-1227456760) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16f7050ddfb1cfe0b513e98341e7c919ca7ea902/src/app/ui/toc/toc.controller.js#L18)):*
Can get rid of `$state` here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/morph.directive.js, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92#-K5ByaWo-KFl53TvGXKD:-K5CFi0Bt3SDDWZQqbFD:-495976147) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16f7050ddfb1cfe0b513e98341e7c919ca7ea902/src/app/ui/common/morph.directive.js#L39)):*
:+1: Not sure why I put it there in the first place, good catch

---

*[src/app/ui/common/morph.directive.js, line 58 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92#-K5Bz4uvF04G9Me1vTmg:-K5CFfgFXMp0v2JsxmwD:-1664728561) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16f7050ddfb1cfe0b513e98341e7c919ca7ea902/src/app/ui/common/morph.directive.js#L58)):*
Doesn't work without it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92)*

**Comment by cynngah** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/92)*

**Pull request merged**
