### PR TITLE
Node 5.4 upgrade; EPSG code lookup; promise error handling fix

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/245)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 204 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/245#-K8tTpgOE2D41Gx-67EC:-K8tTpgOE2D41Gx-67ED:-1040342288) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0131031736dbf6eacd15d08daa87dc804335d6a6/src/app/geo/geo.service.js#L204)):*
Should this be in geoApi?  We have functions in there that will want to utilize this. Or is the plan to pass an instance of proj4 to geoApi that already has lookups performed and applied?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/245)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 204 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/245#-K8tTpgOE2D41Gx-67EC:-K8tVtEydjsB_PZJaDEi:-1400741561) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0131031736dbf6eacd15d08daa87dc804335d6a6/src/app/geo/geo.service.js#L204)):*
The second option.  I've exposed the option to add projections to the `proj4` instance in the `proj` module: https://github.com/fgpv-vpgf/geoApi/blob/develop/src/proj.js#L137 .  If there's a good case for doing things a different way I'm fine with that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/245)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 204 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/245#-K8tTpgOE2D41Gx-67EC:-K8tZdsunfXQo8U58uQx:671651469) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0131031736dbf6eacd15d08daa87dc804335d6a6/src/app/geo/geo.service.js#L204)):*
Will add a plugin structure to geoApi to allow this function (or other lookup functions) to be accessed in geoApi

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/245)*

**Comment by ec-dev** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/245)*

**Pull request merged**
