### PR TITLE
feat(plugin) add coordinates info plugin

### LINKED ISSUE #1792: Add coordinates info button to sidenav
Add a button in sidenav that wait for user click then show information about the coordinates to give a result like this

screen shot 2017-03-20 at 3 23 21 pm

Check if it need to be in the core or as external plugin

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1792

## Description

Add a plugin to get information about coordinates. In the same time solve a problem with DMS longitude coordinate

## Testing

Chrome, FF and Safari

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1880)

### CODE REVIEW

**Comment by milesap** [comment]
In chrome on `index-fgp-en.html` the dialog is not displaying correctly. When I click on the plugin link in sidenav nothing happens, but when I click anywhere on the map it pops up multiple times.

---

Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/core/core.run.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsUSQCsnMPWZKboVem:-KjsUSQDUaoJeMqwhHkD:bc54sb9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/core/core.run.js#L173)):*
> ```JavaScript
>             toggleSideNav: (val) => { $mdSidenav('left')[val](); },
>             toggleDialogInfo: (title, content) => {
>                 $mdDialog.show({
> ```

All plugin logic should reside in the plugin itself. Only include viewer logic you want exposed to all plugins on the `service` object.  `toggleSideNav` is good.

One idea for moving `$mdDialog` into the plugin is to add an `ngMaterial` object on `api` in `plugin.service.js` which could expose `$mdDialog`. 

---

*[src/app/core/core.run.js, line 195 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsWpoBXSklNJhTZYph:-KjsWpoBXSklNJhTZYpi:bqbj950) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/core/core.run.js#L195)):*
> ```JavaScript
>          * @param {Object}  items    the items to set inside the dialog  (title {string} title for the window, content {string} html content)
>          */
>         function PluginController($mdDialog, items) {
> ```

Move this into the plugin.

---

*[src/app/ui/sidenav/plugin-dialog.html, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsX_ci1kx-thUlORVR:-KjsX_ci1kx-thUlORVS:bnarfwf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/ui/sidenav/plugin-dialog.html#L1)):*
> ```HTML
> <md-dialog aria-label="{{'sidenav.label.about' | translate}}" class="side-nav-plugin">
> ```

Move this template into the plugin. We may want to expose `$rootElement` on the plugin api in case we want plugins to inject the viewer with html if needed (maybe we'll discuss when everyones back)

---

*[src/content/styles/modules/_side-nav.scss, line 34 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsXw7j_aazhu9Wf80z:-KjsXw7j_aazhu9Wf81-:bysvm54) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/content/styles/modules/_side-nav.scss#L34)):*
> ```SCSS
>     }
> 
>     .side-nav-plugin {
> ```

Move into the plugin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KjsSor0WA3MIOC2k02x:bii8mpr)*

**Comment by jolevesq** [comment]
Thanks for your good comments!

weird... works for me. I click the link, then click on the map for the coordinate I want info for then the dialog open once. When I close it and click again on the map there is no more dialog box.

---

Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/core/core.run.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsUSQCsnMPWZKboVem:-KkB3wYpYyOTmcAsezlw:bh3l3pu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/core/core.run.js#L173)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

All plugin logic should reside in the plugin itself. Only include viewer logic you want exposed to all plugins on the `service` object.  `toggleSideNav` is good.

One idea for moving `$mdDialog` into the plugin is to add an `ngMaterial` object on `api` in `plugin.service.js` which could expose `$mdDialog`. 
</blockquote></details>

Ok I can do this. I put it there because I saw it as a universal controller for all plugin who will use $mdDialog. Just send title and content and you are ready to go.

---

*[src/content/styles/modules/_side-nav.scss, line 34 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsXw7j_aazhu9Wf80z:-KkB4fhbUMjAl8TSv5Vq:b-82k3yb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/content/styles/modules/_side-nav.scss#L34)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Move into the plugin
</blockquote></details>

How can I pass my css from the plugin to the application?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KkB3SdZhII2DvYiG5KM:b-nlbxke)*

**Comment by milesap** [comment]
Hmmm, it works for me too. Wonder what that was. Oh well, seems fixed!

---

Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/core/core.run.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsUSQCsnMPWZKboVem:-KkGJaiPvp6CNA4k33tG:b-p875is) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/core/core.run.js#L173)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Ok I can do this. I put it there because I saw it as a universal controller for all plugin who will use $mdDialog. Just send title and content and you are ready to go.
</blockquote></details>

Makes sense - though passing `$mdDialog` to the plugin gives the plugin author more flexibility. We can still control the access to `$mdDialog` in the future by overriding and/or wrapping its methods.

---

*[src/content/styles/modules/_side-nav.scss, line 34 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsXw7j_aazhu9Wf80z:-KkGJB4ExJ7Jjgg0TSAo:b1w5gnp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/content/styles/modules/_side-nav.scss#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

How can I pass my css from the plugin to the application?
</blockquote></details>

you can do something like this:

```js
var style = document.createElement('style')
style.type = 'text/css'
style.innerHTML = 'content'
document.getElementsByTagName('head')[0].appendChild(style)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KkGKJ9InHuW9raZAPuG:bt8ygu2)*

**Comment by jolevesq** [comment]
I put the code more inside plugin.service. I didn't want to put mdDialog in the plugin because I would have to put aother dependencies as well. At the end it would make it harder for user to develop because they will have to understand Angular. The way I did it is I put the template inside the plugin and a custom controller inside plugin.service.

@milesap  Let me know what you think

---

Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KkLQ4wvEfqLe_y-RTk_:b-wwbkrx)*

**Comment by jolevesq** [comment]
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/core/core.run.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsUSQCsnMPWZKboVem:-KkQXa0QYmARN9zhL7-3:bauy5cg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/core/core.run.js#L173)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Makes sense - though passing `$mdDialog` to the plugin gives the plugin author more flexibility. We can still control the access to `$mdDialog` in the future by overriding and/or wrapping its methods.
</blockquote></details>

I moved some stuff inside ```plugin.service``` and some stuff inside ```CoordInfo``` plugin

---

*[src/app/core/core.run.js, line 195 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsWpoBXSklNJhTZYph:-KkQXoVRdoi91vP7wsKc:b-w7lob1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/core/core.run.js#L195)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Move this into the plugin.
</blockquote></details>

Moved inside ```plugin.service```. Tried to put inside plugin but have the $mdDialog inside ```plugin.service``` but it didn't work.

---

*[src/content/styles/modules/_side-nav.scss, line 34 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsXw7j_aazhu9Wf80z:-KkQXVL3Zul45K9UFQBQ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/content/styles/modules/_side-nav.scss#L34)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

you can do something like this:

```js
var style = document.createElement('style')
style.type = 'text/css'
style.innerHTML = 'content'
document.getElementsByTagName('head')[0].appendChild(style)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Comment by jolevesq** [comment]
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/sidenav/plugin-dialog.html, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KjsX_ci1kx-thUlORVR:-KkQY5BjVfRV64I4_Jop:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d3cd689716150f9302b3c820578f503448a6c6da/src/app/ui/sidenav/plugin-dialog.html#L1)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Move this template into the plugin. We may want to expose `$rootElement` on the plugin api in case we want plugins to inject the viewer with html if needed (maybe we'll discuss when everyones back)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Comment by milesap** [comment]
I'm going to take this PR as a reference and expand the plugin API on a separate PR. When that merges you can resubmit a PR with only the plugin. I'll get your input on the other PR before it is merged. 

I need to do a bit of work on the plugin service (and bootstrap is going away with webpack) first as API changes are final once released. You can close this PR.

---

Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-Kl-4LEKpuVAVDtaF629:bwe3g7s)*

**Comment by milesap** [comment]
@jolevesq will open a new PR with the plugin only once the plugin API changes are merged by me

**Comment by milesap** [comment]
fyi there are no api changes with v2.0 so if this plugin is needed for that release we'll need to merge this

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 1 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-Km7V7Oz1NAsdZrurmA3:bg7igkv)*

**Comment by milesap** [comment]
Try removing the `RV.ready` wrapper in the sample page and just execute the code inside.

---

Reviewed 9 of 12 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-Kma8FlIF1B-1Z_At0_o:b-ec1sdb)*

**Comment by james-rae** [comment]
Reviewed 4 of 12 files at r3, 6 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 4 of 8 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KmfLRAB9IVactXzDli4:bg7igkv)*

**Comment by milesap** [comment]
Reviewed 2 of 8 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Comment by AleksueiR** [comment]
Can we suppress identify call, because it seems to fire along with coordinate check as well.
Also, it would be nice to change the mouse cursor to after the user selects "COORDS INFO" from the menu to indicate that the mode has changed.

---

Reviewed 4 of 12 files at r3, 6 of 8 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/core/config.service.js, line 93 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KmfM9Ju2pBYWJRffsns:-KmfM9Ju2pBYWJRffsnt:byn75qz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/185cadf1c13d058afb01508a2ddbf013b18c66f2/src/app/core/config.service.js#L93)):*
> ```JavaScript
>          * @return {String} the current language string
>          */
>         getLang() {
> ```

You can get the current language through `configService.getSync.language`. This will return the language of the currently loaded config and it's already used in some places. 

---

*[src/plugins/core/coord-info.js, line 233 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KmfP_9PkNLKMlPsDmux:-KmfP_9PkNLKMlPsDmuy:b-qzo9xv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/185cadf1c13d058afb01508a2ddbf013b18c66f2/src/plugins/core/coord-info.js#L233)):*
> ```JavaScript
>         style.innerHTML = '.side-nav-plugin { height: 80%; width: 40%; border-radius: 0; }';
>         document.getElementsByTagName('head')[0].appendChild(style);
>         self.openDialogInfo({ items, template });
> ```

This style is being injected multiple times:


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KmfQFWrMo_4PdjtncOO:bxyq45r)*

**Comment by jolevesq** [comment]
The map cursor is done. For the identify is there a way to do it right now or I have to build the function?

---

Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/plugins/core/coord-info.js, line 233 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KmfP_9PkNLKMlPsDmux:-Kmh1-SFEt9o12uHfgkg:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/185cadf1c13d058afb01508a2ddbf013b18c66f2/src/plugins/core/coord-info.js#L233)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This style is being injected multiple times:

</blockquote></details>

Done.

---

*[src/app/core/config.service.js, line 93 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-KmfM9Ju2pBYWJRffsns:-KmgylbxgsPsoCO2UUDc:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/185cadf1c13d058afb01508a2ddbf013b18c66f2/src/app/core/config.service.js#L93)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can get the current language through `configService.getSync.language`. This will return the language of the currently loaded config and it's already used in some places. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KmhKNQATaNIWuyvHGTY:b-90dv04)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880#-:-KmkZr0fxGmTjivu9DU5:bnfp4nl)*

**Comment by milesap** [comment]
Reviewed 2 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Comment by milesap** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1880)*

**Pull request merged**
