### PR TITLE
1345 timed layer refreshing & 2461 table settings alignment 

### LINKED ISSUE #1345: Add support for timed layer refreshing
Would like to support optional use of the `refreshInterval` property of layers.  This is useful for services that update frequently -- the map layer will periodically check for updates and refresh itself.

Things to consider

* Exposing the option via the config schema (defaulted to off)
* Exposing the option in the layer settings panel
* Invalidating any pre-loaded attributes when the layer refreshes
* Deciding how to handle a data grid that is open when a refresh occurs
  * Instant update
  * Notification that data is stale
  * Be content with un-announced staleness, data is refreshed when grid re-opens
  * Other options...

Request comes from Health Canada

### LINKED ISSUE #2461: Datatable settings panel column alignment
The last two columns need to be aligned to the right and some margin added between them to make them look cleaner. Right now it seems the header controls of the columns are not in the same like at the other controls.

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2461 

Closes #1345 - allows for optional use of auto refreshing layers from config or settings panel. However, the datatable must be manually refreshed; a notification is shown when the table is opened for appropriate layers

## Testing
Visually tested. Difficult to test #1345 since I couldn't find a layer that frequently updates.

Sample 53 can be used - Natural Gas Pipeline auto refreshes (can be seen when layer is visible)

## Documentation
In-line comments, JSDoc

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2471)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Can you also add a clear button to the interval field that sets it to 0 and auto-reloads the layer?



The clear button should be disabled if the interval value is 0 or blank.

---

Reviewed 6 of 14 files at r1.
Review status: 6 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[schema.json, line 296 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW-DihuJM4AIDy08zV:-KyW-DihuJM4AIDy08zW:bnvwdif) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/schema.json#L296)):*
> ```JSON
>                 "stateOnly": { "type": "boolean", "default": false, "description": "A flag indicating this entry is only for state tracking (i.e. it should not be displayed on the UI and all of the controls will be ignored, but the layer itself will be displayed on the map with the given state settings)." },
>                 "table": { "$ref": "#/definitions/tableNode", "description": "Settings for table panel"},
>                 "refreshInterval": { "type": "number", "description": "The automatic refresh interval of the layer in minutes." }
> ```

Add a note that maximum interval is 100 minutes.

---

*[src/app/geo/legend-block.class.js, line 641 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW1kUHYQ4qyDE6_I0v:-KyW1kUHYQ4qyDE6_I0w:b-5cpjq8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/src/app/geo/legend-block.class.js#L641)):*
> ```JavaScript
>                         this._mainProxyWrapper.loadedFeatureCount);
> 
>                     if (this._derivedLoadedFeatureCount > this._mainProxyWrapper.featureCount) {
> ```

Some comments please :)

---

*[src/app/ui/settings/settings-content.directive.js, line 85 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW1rzWphErFm9Arqz7:-KyW1rzWphErFm9Arqz8:ba6b9sw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/src/app/ui/settings/settings-content.directive.js#L85)):*
> ```JavaScript
>     self.checkStylesLength = checkStylesLength;
> 
>     self.isNode = () => self.block.blockType === LegendBlock.TYPES.NODE;
> ```

Is it possible to set the refresh interval on the Dynamic layer as a whole and not just on its children?

---

*[src/app/ui/settings/settings-content.html, line 44 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW25NzwldV1y3C0tzI:-KyW25NzwldV1y3C0tzJ:bkmqr00) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/src/app/ui/settings/settings-content.html#L44)):*
> ```HTML
>         <form name="refreshForm">
>             <md-input-container>
>                 <label>{{ 'settings.label.refreshHint' | translate }}</label>
> ```

Please, shorten the label to "Refresh interval in minutes".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-:-KyW5PSBgxEe3PlHm8jG:b-6mfa5i)*

**Comment by AleksueiR** [comment]
Reviewed 8 of 14 files at r1.
Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by JahidAhmed** [comment]
Review status: 3 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[schema.json, line 296 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW-DihuJM4AIDy08zV:-KzPQltMKECqLRCzRXJ6:byv2fai) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/schema.json#L296)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Add a note that maximum interval is 100 minutes.
</blockquote></details>

Added for relevant nodes

---

*[src/app/geo/legend-block.class.js, line 641 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW1kUHYQ4qyDE6_I0v:-KzPQrQcAZ9Xnaw76jOE:b-8b11j9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/src/app/geo/legend-block.class.js#L641)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Some comments please :)
</blockquote></details>

Added

---

*[src/app/ui/settings/settings-content.directive.js, line 85 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW1rzWphErFm9Arqz7:-KzPQsys4lVc4sfTP3sW:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/src/app/ui/settings/settings-content.directive.js#L85)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Is it possible to set the refresh interval on the Dynamic layer as a whole and not just on its children?
</blockquote></details>

Done, thanks

---

*[src/app/ui/settings/settings-content.html, line 44 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KyW25NzwldV1y3C0tzI:-KzPRwUfa31bgMJpMdCc:b-a2ujfz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5749742d1e70cdbaf1df7750fcb5d8689dbf19f2/src/app/ui/settings/settings-content.html#L44)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, shorten the label to "Refresh interval in minutes".
</blockquote></details>

Changed 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by AleksueiR** [comment]
Reviewed 13 of 17 files at r3.
Review status: 16 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by james-rae** [comment]
Reviewed 2 of 14 files at r1, 1 of 4 files at r2, 6 of 17 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 9 of 9 files at r6.
Review status: 20 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[schema.json, line 543 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdaGiQ-wutZCu62kvd:-KzdaGiQ-wutZCu62kve:bmeyb6d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/schema.json#L543)):*
> ```JSON
>                 "name": { "type": "string", "description": "The display name of the layer.  If it is not present the viewer will make an attempt to scrape this information." },
>                 "url": { "type": "string", "description": "The service endpoint of the layer.  It should match the type provided in layerType." },
>                 "refreshInterval": { "type": "number", "description": "The automatic refresh interval of the layer in minutes. Maximum interval is 100 minutes." },
> ```

Does this need a default value (`0`)?

---

*[src/app/geo/layer-registry.service.js, line 90 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdhvAZ6Fe2ac0GaSQw:-KzdhvAZ6Fe2ac0GaSQx:b24c53s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/src/app/geo/layer-registry.service.js#L90)):*
> ```JavaScript
>             if (refreshInterval) {
>                 updateAttributes = common.$interval(() => {
>                     Object.keys(layerRecord._featClasses).forEach(fc => {
> ```

this logic block can be moved to geoApi LayerRecord (as a method). then we are not referencing private variables in geoApi in the client.

---

*[src/content/samples/config/config-sample-01-structured-visibility-sets.json, line 376 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdexFu5EUS8OvKVloc:-KzdexFv1C95MUWd06Ny:bvd6z2n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/src/content/samples/config/config-sample-01-structured-visibility-sets.json#L376)):*
> ```JSON
>         },
>         "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/2",
>         "refreshInterval": 0.1
> ```

We should be making new tests instead of modifying `sample 1`. The testers get unhappy when their existing tests are changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by JahidAhmed** [comment]
Review status: 16 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[schema.json, line 543 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdaGiQ-wutZCu62kvd:-Kzdne8ClldO-LJie-fR:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/schema.json#L543)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Does this need a default value (`0`)?
</blockquote></details>

Done

---

*[src/app/geo/layer-registry.service.js, line 90 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdhvAZ6Fe2ac0GaSQw:-Kzdnf-u-Tj5r0tIWCnM:bky53he) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/src/app/geo/layer-registry.service.js#L90)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this logic block can be moved to geoApi LayerRecord (as a method). then we are not referencing private variables in geoApi in the client.
</blockquote></details>

Done thanks

---

*[src/content/samples/config/config-sample-01-structured-visibility-sets.json, line 376 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdexFu5EUS8OvKVloc:-KzdnfudgT5h7Cp_fkmQ:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/src/content/samples/config/config-sample-01-structured-visibility-sets.json#L376)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

We should be making new tests instead of modifying `sample 1`. The testers get unhappy when their existing tests are changed.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by james-rae** [comment]
Reviewed 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 543 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdaGiQ-wutZCu62kvd:-Kze8x2uYBL8BifyKqfn:benugwx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/schema.json#L543)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Need to do the other 3 definitions 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by JahidAhmed** [comment]
Review status: 21 of 22 files reviewed at latest revision, all discussions resolved.

---

*[schema.json, line 543 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471#-KzdaGiQ-wutZCu62kvd:-KzeAkSw6ghD20TzKzYs:b4g0byb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53c085793c13bd581f0fb54c58d30f48ab1e9c86/schema.json#L543)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Need to do the other 3 definitions 
</blockquote></details>

oops, done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r2, 1 of 1 files at r5, 8 of 9 files at r6, 5 of 7 files at r7, 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2471)*

**Pull request merged**
