### PR TITLE
Geo4 search fix

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Restores geo search after the structured legend refactor.
Also fixes search filter overflow in #1865.

Turns off the "lightbulb" button to rehighlight individual details records as its full expected behaviour is not clear at the moment.

## Testing
Eyeballs.

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated (#1865)
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1899)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 23 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1899#-Kl049SE6uVbuTPOvkMZ:-Kl049SFMU8MUVFgueX9:bexo9og) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1a8c74a5a5ddf74ea92a737d5dc175e66980a927/src/app/geo/map.service.js#L23)):*
> ```JavaScript
>             zoomToLatLong,
> 
>             // TODO: should these functions be proxied through the geoService?
> ```

I might be wrong, but I think everything public in `map.service` gets mashed into `geoService`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1899)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/map.service.js, line 23 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1899#-Kl049SE6uVbuTPOvkMZ:-Kl3NLatYmKu76p2ECyP:b-rhgaaa) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1a8c74a5a5ddf74ea92a737d5dc175e66980a927/src/app/geo/map.service.js#L23)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I might be wrong, but I think everything public in `map.service` gets mashed into `geoService`
</blockquote></details>

Not anymore it's not, everything has changed during the refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1899)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r3.
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1899)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1899)*

**Pull request merged**
