### PR TITLE
feat(ui): appbar i18n support

### PR DESCRIPTION
**Pull request by james-rae**
Pretty simple commit, looking for feedback before I apply similar changes elsewhere

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/289)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by alyec** [comment]
Looks good, quite easy to read

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289#-:-K9hBTZZ7boNOy9zuWG7:1897985513)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/appbar/appbar.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289#-K9hE95NdSregkxKBsG3:-K9hE95OlU48_bxCasIv:141083326) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a67bd3ce375531bc4de1975aee5388e0e30e0844/src/app/ui/appbar/appbar.html#L4)):*
Can you check if this works?
`<md-button translate translate-attr-aria-label="appbar.aria.menu" ...>`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by james-rae** [comment]
*[src/app/ui/appbar/appbar.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289#-K9hE95NdSregkxKBsG3:-K9hVvKR35iID8YL18jP:838305659) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/435f91d69ea49d878252040a53cef0edd94608bd/src/app/ui/appbar/appbar.html#L4)):*
Works.  Much nicer approach, updated commit coming soon.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by james-rae** [comment]
*[src/app/ui/appbar/appbar.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289#-K9hE95NdSregkxKBsG3:-K9hWQVxdEWtwMjkiKB7:205834226) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/435f91d69ea49d878252040a53cef0edd94608bd/src/app/ui/appbar/appbar.html#L4)):*
I was wrong, I checked the wrong thing.  The end result of in final html is `translate-attr-aria-label="appbar.aria.tools"`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/appbar/appbar.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289#-K9hE95NdSregkxKBsG3:-K9hY97T3_rosxonjn7T:740898352) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/435f91d69ea49d878252040a53cef0edd94608bd/src/app/ui/appbar/appbar.html#L4)):*
Strange, it should work. Try bumping `angular-translate` and `angular-translate-loader-static-files` dependencies to 2.9.0.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by james-rae** [comment]
*[src/app/ui/appbar/appbar.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289#-K9hE95NdSregkxKBsG3:-K9h_gGWLiCw6ktb2dEN:885279822) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/435f91d69ea49d878252040a53cef0edd94608bd/src/app/ui/appbar/appbar.html#L4)):*
Same fail condition

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by james-rae** [comment]
*[src/app/ui/appbar/appbar.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289#-K9hE95NdSregkxKBsG3:-K9haW2rearUqmpYmYA-:1890473414) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/435f91d69ea49d878252040a53cef0edd94608bd/src/app/ui/appbar/appbar.html#L4)):*
Breaking news:  it actually worked, and looking at things on two lines is hard :blowfish: :dash: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/289)*

**Pull request merged**
