### PR TITLE
Expand detail

### PR DESCRIPTION
**Pull request by jolevesq**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/697)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Expand button missing a proper tooltip:


<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> #### Expand detail
</details>


---

Reviewed 2 of 12 files at r1, 9 of 10 files at r2.
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_details.scss, line 4 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBMA9GI0i-5f4BgkFy:-KJBMA9GI0i-5f4BgkFz:-84886428) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f6d048a9f3a1ef2ff8fd97f9c573b498933ad66/src/content/styles/modules/_details.scss#L4)):*
> ```SCSS
>     $slide-out-width: rem(28);
> 
>     .rv-details-summary {
> ```

What does this class do? I can't find anything with this name.

---

*[src/content/styles/modules/_details.scss, line 29 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBMEfCvLzP3Z9bDkWv:-KJBMEfCvLzP3Z9bDkWw:1629949667) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f6d048a9f3a1ef2ff8fd97f9c573b498933ad66/src/content/styles/modules/_details.scss#L29)):*
> ```SCSS
>             display: block;
>         }
>         
> ```

Trailing spaces :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-:-KJBMsQuVeqgDdfZLKeY:1107361806)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r3.
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 247 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBOd0zjhRjj4qYvmRw:-KJBOd0zjhRjj4qYvmRx:-1296892237) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/geo/identify.service.js#L247)):*
> ```JavaScript
>                         // TODO: check for French service
>                         // check if a result is returned by the service. If not, do not add to the array of data
>                         if (data.indexOf('Search returned no results') === -1) {
> ```

This needs more attention as services may differ in their `no results` responses.
I think @alyec had a suggestion to create a list of `no results` presets for wms layers and check against them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by jolevesq** [comment]
The rebase change the info inside translation csv to details.expand.tooltip instead of details.tooltip.extend. I will modify.

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Expand button missing a proper tooltip:
> 
</details>


---

Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 247 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBOd0zjhRjj4qYvmRw:-KJBUZvGGAnu3g2bWEJh:586284846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/geo/identify.service.js#L247)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> This needs more attention as services may differ in their `no results` responses.
> I think @alyec had a suggestion to create a list of `no results` presets for wms layers and check against them. 
</details>
I was expecting that. I will wait from @aly suggestion before modifying this

---

*[src/content/styles/modules/_details.scss, line 4 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBMA9GI0i-5f4BgkFy:-KJBTkng2SC_Ycs_oQF8:-1622193814) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f6d048a9f3a1ef2ff8fd97f9c573b498933ad66/src/content/styles/modules/_details.scss#L4)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> What does this class do? I can't find anything with this name.
</details>
It sets the expand details window size (details-modal.html). I copy the code from metatada and it uses rv-help-summary class. I thought using a class with details is more appropriate then linking to a class of something else. If we want the same class to apply to everything it should not be specific to a panel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-:-KJBTJvVX7bSolfK-hRG:1616260793)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r3.
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_details.scss, line 4 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBMA9GI0i-5f4BgkFy:-KJBXqeUkcn_6GjZEiTC:1073308054) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f6d048a9f3a1ef2ff8fd97f9c573b498933ad66/src/content/styles/modules/_details.scss#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> It sets the expand details window size (details-modal.html). I copy the code from metatada and it uses rv-help-summary class. I thought using a class with details is more appropriate then linking to a class of something else. If we want the same class to apply to everything it should not be specific to a panel.
</details>
Ah, okay. I think this can be discussed further: in embedded maps, it would make sense to have modal window take all available space, or even appear on the host page instead (for desktop browsers).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by alyec** [comment]
Reviewed 1 of 12 files at r1, 10 of 10 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 247 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBOd0zjhRjj4qYvmRw:-KJBZMvBppusXANF9w0I:1800452909) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/geo/identify.service.js#L247)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I was expecting that. I will wait from @aly suggestion before modifying this
</details>
It might be worth having a set of phrases that trigger no results to be shown and this could be in a constants file.  However, this should also be communicated to FGP so that WMSes can use this.

---

*[src/app/ui/panels/content-pane.directive.js, line 131 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBdfPLjRQarw-r1m98:-KJBdfPLjRQarw-r1m99:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/ui/panels/content-pane.directive.js#L131)):*
> ```JavaScript
>                     self.headerControls.split(';')
>                         .forEach(controlName => {
>                             let controlElement = $compile(`<${controlName}></${controlName}>`)(scope);
> ```

const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/panels/content-pane.directive.js, line 131 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBdfPLjRQarw-r1m98:-KJBu7VA4Sm9G_oI2KIm:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/ui/panels/content-pane.directive.js#L131)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> const
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 247 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBOd0zjhRjj4qYvmRw:-KJBw_pYqwjrFSktaWrW:-1838833284) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/geo/identify.service.js#L247)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Is it a new issue or this is part of this PR?
</details>
I think a new issue, but if the FGP WMSes are inconsistent then we may want to remove this piece later (if the results detection for WMSes is too random it may be better not to try at all).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by jolevesq** [comment]
Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 247 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBOd0zjhRjj4qYvmRw:-KJCHSywL5SQSfze-ayE:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/geo/identify.service.js#L247)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think a new issue, but if the FGP WMSes are inconsistent then we may want to remove this piece later (if the results detection for WMSes is too random it may be better not to try at all).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by jolevesq** [comment]
Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/panels/content-pane.directive.js, line 131 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBdfPLjRQarw-r1m98:-KJCHWuetzzaoW6bmiB7:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96b674c523fa981dff6a8bb9e10c1a6f6097fd88/src/app/ui/panels/content-pane.directive.js#L131)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Done.
</details>
Done.

---

*[src/content/styles/modules/_details.scss, line 4 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBMA9GI0i-5f4BgkFy:-KJCHXZRKd41tELowla_:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f6d048a9f3a1ef2ff8fd97f9c573b498933ad66/src/content/styles/modules/_details.scss#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Done.
</details>
Done.

---

*[src/content/styles/modules/_details.scss, line 29 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697#-KJBMEfCvLzP3Z9bDkWv:-KJCHYCOMaNSO5bcnAUA:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2f6d048a9f3a1ef2ff8fd97f9c573b498933ad66/src/content/styles/modules/_details.scss#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/697)*

**Pull request merged**
