### PR TITLE
fix(ui): replace keyboard mode dialog with instructions dialog

### LINKED ISSUE #3919: WCAG: Accessibility issues with keyboard mode dialog
Spawned from #3892.

"The mechanism to go into keyboard mode is visually presented as a dialog box, with a greyed out background. But is doesn't act like one and doesn't present the proper roles and states"

"There are a number of fixes
- [ ] Don't have it automatically popup. That is confusing.
- [ ] Provide an invisible button that shows up on focus that says "Open keyboard Instructions"
- [ ] This would open a a true dialog, where the focus is placed inside it
- [ ] Tab focus would remain inside it, and it is dismissed either by hitting then OK button, the X button or pressing escape ESC key.
- [ ] a model for the modal is to the right. It provides the HTML, CSS, JavaScript and ARIA. The instructions could then be more comprehensive to describe how to draw on the map etc. if that is appropriate for the functionality of the map."

68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3536393531373863363338653731386339393630303131352f65613139643165382d363534312d343634332d393662632d333565313637313532623034

https://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #3919 

---
This PR introduces some changes to how tabbing into the viewer works. If you tab into the viewer prior to this PR, you are able to skip focusing on the individual components within the viewer by pressing `tab` again, which takes you to the next focusable element on the page. Issue #3919 requests that this dialogue box no longer pops up automatically, so there's no prompt that shows up when tabbing into the viewer to tell you how to skip the focus. 

We probably still want to have a way to skip the focus on the viewer entirely, but I can't really think of a good way to go about this. Any recommendations would be appreciated.

---

**Changes in this PR:**
Now when you focus on the viewer by pressing TAB, the browser focus is immediately set to a hidden button labelled `Open keyboard controls`. Pressing `enter` while focused on this button opens a dialogue box that contains instructions on how to navigate RAMP using the keyboard. It's possible that I missed some instructions here, let me know if I did.

You can find a demo of this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3919/samples/index-samples.html).

Press TAB until you focus on the viewer (press tab once more after focused on the little up arrow at the bottom of the samples panel), and then press ENTER. If you have the ability to use a screen reader (I used [this one](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn)), you will hear `Open keyboard controls`. 

Preview:

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)

### CODE REVIEW

**Review by spencerwahl — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by sharvenp — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by milespetrov — APPROVED** [review]
Wondering if issue #3919 assumes all keyboard nav. users also use screen readers? Is there any other way to know about this hidden modal/instructions?

Two bad ideas for skipping over map:
1. have another button in the modal called "Skip viewer" or similar that facilitates the skip when enter is pressed. 
2. let the user tab out of the modal and past the map

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950#-:-MczmJd26mzaWmb4Yqgr:bk06hzb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Comment by spencerwahl** [comment]
> Wondering if issue #3919 assumes all keyboard nav. users also use screen readers? Is there any other way to know about this hidden modal/instructions?

This is a good point (I only thought about it in reference to them having to tab an extra time). Can we have the "Open keyboard controls." button show up on focus? That way keyboard users without screen readers can know about the instructions.

**Review by RyanCoulsonCA — COMMENTED** [review]
> Can we have the "Open keyboard controls." button show up on focus?

I was actually just working on doing something like this. Here's a demo of it at the moment, the style and location can be tweaked if necessary:



> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950#-:-Md2CFUJ2uMalZdniI-E:bfeii36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Comment by james-rae** [comment]
Another approach, not sure if it will work (it might be part of the WET page and not RAMP).  If you open the [fgp variant](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3919/samples/index-fgp-en.html) and start pressing TAB, you'll see some "Skip to" things appear at the top of the page. Maybe we can do something similar? Tho I guess that little keyboard icon is essentially the same thing.

**Review by james-rae — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
I believe that the `Skip to` prompt is part of WET. I've been playing around with a couple of options and the easiest one I've come across so far is to keep it similar to how it was pre-PR: tabbing into the viewer will focus on the `Open keyboard controls` button, and pressing TAB again will skip right past it. I could re-name the aria-label on the button to something like `Enable keyboard controls and open instructions`.

This might cause some confusion if you're already focused on the viewer (tabbing through all of the components will focus on this button again at some point). I'm not sure if it's possible, but I might be able to do some JS magic to re-name the button to `Open keyboard controls` again if the viewer is already active.

Here's a quick example of what I'm talking about: *preview isn't working for some reason but you can [click here](https://i.imgur.com/M0HuBrm.gif) to see*.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950#-:-Md2hcr12KB4aNOZt4A-:b-9mdrem)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
Pushed changes to this PR:
* keyboard control button is now visible when it is focused, hidden otherwise
* when tabbing into the viewer, the button is focused. Pressing TAB again will skip past the viewer. The button text will read `Activate Keyboard Controls`
* if you press enter on the button, keyboard mode is activated and the button text will read `View keyboard instructions`

The button text is based on the viewer state (NOT_ACTIVE, WAITING or ACTIVE), so if focus is lost on the viewer the text will revert back to saying `activate keyboard controls`.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950#-:-MdHsPYwEpigJX3h3mH6:b37gam1)* status: 2 of 9 files reviewed, all discussions resolved (waiting on @james-rae, @milespetrov, @sharvenp, @spencerwahl, and @yileifeng)

**Review by spencerwahl — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[packages/ramp-core/src/app/ui/common/keyboard-instructions.html, line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950#-MdHttbe4lCAcWMM8EK_:-MdHttbe4lCAcWMM8EKa:bd96uus) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4b80ed7d028de92b93e3c935c38dec49bc5466dd/packages/ramp-core/src/app/ui/common/keyboard-instructions.html#L5)):*
> ```HTML
>         ng-click="self.open()"
>         class="rv-close md-icon-button primary rv-button-40"
>         aria-label="{{ 'focus.dialog.keyboardInstructions' | translate }}"
> ```

are you able to do a conditional for the label + tooltip like "{{ self.type === 'ACTIVE ? active label : not active label }}"

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[packages/ramp-core/src/app/ui/common/keyboard-instructions.html, line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950#-MdHttbe4lCAcWMM8EK_:-MdHxGet5xjg45FXH-xc:b-6xrxyr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4b80ed7d028de92b93e3c935c38dec49bc5466dd/packages/ramp-core/src/app/ui/common/keyboard-instructions.html#L5)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

are you able to do a conditional for the label + tooltip like "{{ self.type === 'ACTIVE ? active label : not active label }}"
</blockquote></details>

Yep, fixed.

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by james-rae — APPROVED** [review]
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by milespetrov — APPROVED** [review]
> Reviewed 5 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by james-rae — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
