### PR TITLE
feat(core): use config for mannav cluster

### LINKED ISSUE #1481: Update mapnav service to actually use config file
- [x] Allow to remove geo-location button from the mapnav cluster.

Solution:
Config file has a `navBar` section where the map author can specify which button should be available in the map navigation cluster.  Mapnav services doesn't do that right now; the buttons are encoded. The service needs to consume the corresponding section from the config file.

Usability Issue:
V19.  Your location (Type: Functionality)

No tester was able to make the “Your location” button do something.

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Mapnav cluster buttons now configured by the config file (default English config has geoLocation, home and help; default French has geoLocation, home, help, basemap, history, and marquee buttons).

## Testing
Eyeballing.

## Documentation
Source code comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

Closes #1481

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1503)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/mapnav/mapnav.service.js, line 136 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1503#-KYsNVTUBEQGeU5Q7IUK:-KYsP6fCIgiS2nMuWpDo:b6gksb8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2ecc202f5f78a9560385ed9c3271e941fbc68440/src/app/ui/mapnav/mapnav.service.js#L136)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Excellent use of whitespace, bad use of jsdoc :)
</blockquote></details>

No idea how this had happened. Fixed now. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1503)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1503)*

**Comment by alyec** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1503#-:-KYseR0bdkwkYZo-JedC:bnfp4nl)*

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1503#-:-KYsf8rUXQ9S3e9xP8wO:bg7igkv)*

**Pull request merged**
