### PR TITLE
fix(ui): layer symbology graphics enlarged on legend expansion

### LINKED ISSUE #517: WMS Legends inserted as Layer Symbology Graphics
WMS Legend graphics are being inserted into the graphical element for layer symbology.  This should be replaced by a generic symbol for to represent OGC WMS layers and have the legend provided in a similar fashion to how RAMP displays it.

### PR DESCRIPTION
**Pull request by milesap**
Layer name now above graphic, resizing done with GreenSock lib.

Closes #517

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/588)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KHV2X3tMPMpycimK0ai:-KHV2X3tMPMpycimK0aj:-1845836423) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/323baf6c7ae3b5ba23f626a928d14a29a48dd593/src/app/ui/toc/entry-symbology.directive.js#L143)):*
> ```JavaScript
>                     });
> 
>                     // in pixels
> ```

If this changed from pixels to something else please update the comment.  If this was an accidental delete please revert it.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 150 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KHV2su_ORlFzLUL9NQz:-KHV2su_ORlFzLUL9NR-:1671982606) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6ad6536fbd8a0fe977bd4f2867b0a27b7ef6617b/src/app/ui/toc/entry-symbology.directive.js#L150)):*
> ```JavaScript
>                     items.reverse().forEach(img => {
> 
>                         let imageElem = img[0].firstChild;
> ```

const (and the two below as well)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by milesap** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 143 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KHV2X3tMPMpycimK0ai:-KHVLr9pKD1MveGFhgNX:-715221446) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/323baf6c7ae3b5ba23f626a928d14a29a48dd593/src/app/ui/toc/entry-symbology.directive.js#L143)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> If this changed from pixels to something else please update the comment.  If this was an accidental delete please revert it.</details>
Added comment

---

*[src/app/ui/toc/entry-symbology.directive.js, line 150 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KHV2su_ORlFzLUL9NQz:-KHVLtztdhQeQWKP1YT2:257435119) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6ad6536fbd8a0fe977bd4f2867b0a27b7ef6617b/src/app/ui/toc/entry-symbology.directive.js#L150)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> const (and the two below as well)</details>
Changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_symbology.scss, line 29 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KHWVSV2P_8zXJS4qf1y:-KHWVSV2P_8zXJS4qf1z:-1515338504) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3579575b865aab5de97b29b5591fd556be314eb7/src/content/styles/modules/_symbology.scss#L29)):*
> ```SCSS
>             left: 0;
>             top: 0;
>             padding-left: 15px;
> ```

This should be removed; its causing collapsed legends to be off-center

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by milesap** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_symbology.scss, line 29 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KHWVSV2P_8zXJS4qf1y:-KHZeB89JMa8iyp6b-iV:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3579575b865aab5de97b29b5591fd556be314eb7/src/content/styles/modules/_symbology.scss#L29)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> This should be removed; its causing collapsed legends to be off-center</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/toc/entry-symbology.directive.js, line 143 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KHuNF4PW3caIWD8EwoC:-KHuNF4QQH-DonIhqyHj:2006497888) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a3f5119bda80182a03433ca0ce844d99d64e894d/src/app/ui/toc/entry-symbology.directive.js#L143)):*
> ```JavaScript
>                     });
> 
>                     // in pixels
> ```

Keep labels to the right of symbology icons in all layers except WMS. In WMS layers (as they can have differently sized legend items), put the labels on top of the images.

To do this, I suggest adding a different template for wms symbology and choosing between templates based on layer type or some sort of symbology type flag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by AleksueiR** [comment]
The symbology stack for non-wms layers is now spaced much wider than intended: 

|   |    |
|---|---|

Also the first and last icons in the stack are misaligned: first is offset 2px to the left; last, 2px to the right.

<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### fix\(ui\): layer symbology graphics enlarged on legend expansion
> 
> Layer name now above graphic, resizing done with GreenSock lib.
> 
> 
> 
> Closes #517
> 
> 
> 
</details>


---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-:-KI3h-EF5kRUR-xzZldK:-309230008)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/content/styles/modules/_toc.scss, line 141 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KI7zVQ0r4F6NaFWwe5S:-KI7zVQ1ODA53tKQqxmr:1786879964) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4e2e678cd99c291a4a700596af6a861d72f2b8c/src/content/styles/modules/_toc.scss#L141)):*
> ```SCSS
>         .rv-toc-layer-entry {
>             padding-left: $offset * ($index) + rem(1.6) + $toc-padding;
>             
> ```

trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_toc.scss, line 141 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588#-KI7zVQ0r4F6NaFWwe5S:-KI9M3nfD0EGchCuAvkJ:5174689) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f4e2e678cd99c291a4a700596af6a861d72f2b8c/src/content/styles/modules/_toc.scss#L141)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> trailing whitespace
</details>
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/588)*

**Pull request merged**
