### PR TITLE
test(geo): add geo service unit tests

### PR DESCRIPTION
**Pull request by james-rae**
Geo service unit tests

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/205)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/205#-K7sxUt98yKzGfW9WU-P:-K7sxUt98yKzGfW9WU-Q:1868931684) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8929c501217e64ef004b303b03f1fc4e0e6a14ee/src/app/geo/geo.service.spec.js#L11)):*
These functions don't really use Angular scopes so I think `$rootScope` can be dropped.  @AleksueiR ?

---

*[src/app/geo/geo.service.spec.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/205#-K7sxEAYD7dN3Wvxjs1G:-K7sxEAYD7dN3Wvxjs1H:-261737882) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8929c501217e64ef004b303b03f1fc4e0e6a14ee/src/app/geo/geo.service.spec.js#L76)):*
:+1: for noting the unit tests that we haven't written yet

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/205)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/205#-K7sxUt98yKzGfW9WU-P:-K7utsh7hUrugRuZSqDJ:1208990260) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8929c501217e64ef004b303b03f1fc4e0e6a14ee/src/app/geo/geo.service.spec.js#L11)):*
I concur.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/205)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/205)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/205)*

**Pull request merged**
