### PR TITLE
feat(ui): expanded point information consistent between panel and modal

### LINKED ISSUE #818: Point Information-Expanded details for feature does not remain expanded when opened in a separate Panel
Tested on - v18-0-2

All Browsers

Steps to Reproduce

- Select a Feature Point on the Map
-Point Information Panel should load with Feature Information
-Click on the side arrow to open Feature Details
-Click on square icon to Expand the details window in a separate panel
-Feature Details will not visible in the new panel.

screenhunter_2294 jun 23 09 39

### PR DESCRIPTION
**Pull request by milesap**
Closes #818

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/881)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/881)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/details/details-record-esrifeature.directive.js, line 41 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/881#-KMZYrmvWcCVXuTVOy-U:-KMZYrmvWcCVXuTVOy-V:-778810238) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9d8426c8ce971e9b2aa10a74d7b886bbd0756840/src/app/ui/details/details-record-esrifeature.directive.js#L41)):*
> ```JavaScript
> 
>             let isCompiled = false;
>             self.item.isExpanded = !!self.item.isExpanded;
> ```

Maybe use do this, to make it easier to read (although it's a bit verbose):
```js
self.item.isExpanded = typeof self.item.isExpanded === 'undefined' : false ? self.item.isExpanded;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/881)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/881#-:-KMZl8czTwA9XizLiVwY:1417088721)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/881)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/881)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/881)*

**Pull request merged**
