### PR TITLE
Dynamic Layer Click Handler

### PR DESCRIPTION
**Pull request by alyec**
Starting PR for early feedback.  No tests yet.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/300)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/identify.service.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300#-KA1OVxOIGMqiDNGHLEq:-KA1OVxOIGMqiDNGHLEr:216632959) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f74d9ee795065dbd9bf0130061df1e65e2e6e8b4/src/app/geo/identify.service.js#L56)):*
I understand what you are doing in this function, but had to think through a number of the lines.  A few inline "narrative in human readable context" would help a lot.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[package.json, line 64 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300#-KA1PBys0uLgiRSGEq4n:-KA1PBys0uLgiRSGEq4o:677194780) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67749de2a9e1714d025a11462bf5d0d839a56c64/package.json#L64)):*
Why?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/identify.service.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300#-KA1OVxOIGMqiDNGHLEq:-KA1PGgsO56MR17DvsFX:-934119306) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f74d9ee795065dbd9bf0130061df1e65e2e6e8b4/src/app/geo/identify.service.js#L56)):*
Is it the destructuring that is hard to read or the promise chain?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300#-KA1OVxOIGMqiDNGHLEq:-KA1PvV_NILzvdmV45Tg:-1964299175) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f74d9ee795065dbd9bf0130061df1e65e2e6e8b4/src/app/geo/identify.service.js#L56)):*
mostly the map statements.  makes it easier to understand whats going on without having to lookup return values from geoApi. 
E.g. line 68 `//transform attributes of click results into array of grid row data` (or something more appropriate).  Nothing crazy, just a narrative to give context to whats happening.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 64 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300#-KA1PBys0uLgiRSGEq4n:-KA1SmO3M_Nfo1hbQjrY:644546252) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67749de2a9e1714d025a11462bf5d0d839a56c64/package.json#L64)):*
It's not usable in Travis and it also adds to `node-gyp` build issues.  If we are using it anyways there's no point in keeping it around until we do.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[package.json, line 64 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300#-KA1PBys0uLgiRSGEq4n:-KA24f2IlJSxaWxYfSm6:-510466975) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67749de2a9e1714d025a11462bf5d0d839a56c64/package.json#L64)):*
:+1: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/300)*

**Pull request merged**
