### PR TITLE
fix(datatable): column headings position corrected on resize

### LINKED ISSUE #2271: Datatable column positioned incorrectly
Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-mobile.html

Since we have `autoWidth: false` for the table, zooming out in your browser while the datatable is open displaces the positioning of the columns.

capture

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2271

## Testing
eagle eyes

## Documentation
inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2286)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
:lgtm: WOMM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2286#-:-KqOH1liWe_HR7lghaQI:bb6r9ev)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/table/table-default.directive.js, line 610 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2286#-KqOeZlKyZlILnBXRuZL:-KqOvG0KE9WtjJiB9oyI:b-x8msan) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/02f94ea6491dd3b4222396cc635a24fc87ff2396/src/app/ui/table/table-default.directive.js#L610)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Try [`layoutService.onResize`](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/layout/shell.directive.js#L96), it has ~~electrolytes~~ debounce :D
</blockquote></details>

:+1: for electrolytes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2286)*

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2286)*

**Comment by milesap** [comment]
Listener is now removed on table close

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2286#-:-KqYc0Wasys0BRl9CZiI:bwwm066)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2286)*

**Pull request merged**
