### PR TITLE
feat(ui): add north arrow support

### LINKED ISSUE #1793: Add North arrow on the map
Add a north arrow on the map (not only in export)

### PR DESCRIPTION
**Pull request by milesap**
## Description
North arrow moves along top of viewer such that it intersects the line
between the center of the map to where santa lives.

Provides API access to the north arrow data so external plugins can add support for different projections or styles (this may not be entirely complete but it is outside the scope of this PR).

Closes #1793

## Testing
Yes, with basic mobile testing as well (no sim)

## Documentation
Yes, everywhere

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1807)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/layout/shell.directive.js, line 60 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-Kg-umyl1QSVhiegVnFV:-Kg-umymdjiKy0FnK3nf:b-3npulr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551e30bb2a03219b3aea825dc779df308f65ca0e/src/app/layout/shell.directive.js#L60)):*
> ```JavaScript
>                 updateNorthArrow();
>                 // init here since rvExtentChange fires before rvApiReady which will cause gapi issues
>                 $rootScope.$on(events.rvMapPan, updateNorthArrow);
> ```

Wouldn't an `extentchange` event fire with every pan? If so, no need to two listeners.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by jolevesq** [comment]
Very nice! I have only 2 comments. We should have more visible color or a translucide background like mapnav because if we look with mercator web imagery basemap it is hard to see the arrow. The arrow overlap the menu and overview map maybe it should under them.

So  you want me to take my show coords on map and do something like what you did for this PR?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-:-Kg-whMk1fDvB-Cg8XwD:b6yk3z6)*

**Comment by milesap** [comment]
Ok, I'll see if a small semi-transparent circular background would help it be more visible. I personally found the arrow is better if it is over the menu since it is not visible under it. Also, on medium sized viewports like iPad the menu bar takes quite a large chunk of horizontal space. If you or any one has some suggestions for this I can try them out as well.

You can put the appropriate code into `map-tools.service.js` and provide them through `bootstrap.js` and `core.run.js`. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-:-Kg00BP3-8CCCZawX6Rw:b3egrsa)*

**Comment by AleksueiR** [comment]
What about just adding a light border around the arrow? This should make it visible on dark backgrounds.

If you zoom out/pan north far enough so the north pole is in the visible extent, it would be nice for the arrow to stick to the map where the pole is.

Right now it just keeps pointing somewhere.


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-:-Kg03Kuiuvl06NXqw4NP:bj7q681)*

**Comment by milesap** [comment]
Put a light border around the arrow, should be more visible now. I was also able to hardcode the north pole for lambert so that the arrow sticks to it. No luck with mercator, so the arrow will continue to point up at all times.

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.directive.js, line 60 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-Kg-umyl1QSVhiegVnFV:-KgEd4sGxLP7GyYUTJ2k:b52qe1g) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/551e30bb2a03219b3aea825dc779df308f65ca0e/src/app/layout/shell.directive.js#L60)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Wouldn't an `extentchange` event fire with every pan? If so, no need to two listeners.
</blockquote></details>

Removed `rvMapPan` listener

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-:-KgEchWXegFzd-rq-28c:b-fch1pb)*

**Comment by AleksueiR** [comment]
Looks nice!

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/modules/_shell.scss, line 31 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-KgEyVanUUVWLL0fvunH:-KgEyVanUUVWLL0fvunI:b987dei) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c34ca2d84bc5ea171ed31b6937d1d261deb67be/src/content/styles/modules/_shell.scss#L31)):*
> ```SCSS
>             z-index: 10;
>             border-radius: rem(2);
>             background-color: rgb(255, 255, 255);
> ```

Can you set `background-color` to `rgba(white, 0.82);` and remove the `opacity` property, so only the white background is transparent? Without this, opacity affects the arrow as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-:-KgEyUDMgFq3p5p2KcEz:b-vob8el)*

**Comment by milesap** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/styles/modules/_shell.scss, line 31 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-KgEyVanUUVWLL0fvunH:-KgEzGCNosBr74OnXMkW:b499q7j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0c34ca2d84bc5ea171ed31b6937d1d261deb67be/src/content/styles/modules/_shell.scss#L31)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you set `background-color` to `rgba(white, 0.82);` and remove the `opacity` property, so only the white background is transparent? Without this, opacity affects the arrow as well.
</blockquote></details>

Changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-:-KgF1Ut0PcmTZxKEG44o:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/map-tools.service.js, line 48 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-KgFWf6lYEVCuTdFJ_8P:-KgFWf6lYEVCuTdFJ_8Q:bm7hz6j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e2fcb0522bb38ab6f244b182aeafa6a84a2243ef/src/app/geo/map-tools.service.js#L48)):*
> ```JavaScript
>             let rotationAngle = null;
> 
>             if (wkid === 3978) { // lambert
> ```

I don't think we need to restrict this logic to lambert only.  The code in this block should work for any projection. I'd suggest structuring this section to 
```
if mercator then
   2 lines of mercator code
else
   block of code for other projections
end if
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map-tools.service.js, line 48 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807#-KgFWf6lYEVCuTdFJ_8P:-KgFe9j6pA92t4Y9jmCY:b-geb0m6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e2fcb0522bb38ab6f244b182aeafa6a84a2243ef/src/app/geo/map-tools.service.js#L48)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I don't think we need to restrict this logic to lambert only.  The code in this block should work for any projection. I'd suggest structuring this section to 
```
if mercator then
   2 lines of mercator code
else
   block of code for other projections
end if
```

</blockquote></details>

Ok - changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by james-rae** [comment]
Reviewed 1 of 8 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by milesap** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by milesap** [comment]
Reviewed 5 of 8 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1807)*

**Pull request merged**
