### PR TITLE
feat(geo): register layers and attribs

### PR DESCRIPTION
**Pull request by james-rae**
Registration functions for layers and attributes. 
Change API url to ESRI to avoid frequent rebuilds of custom API during development phase

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/201)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/geo/geo.service.js, line 21 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201#-K7n_KbjkwegdX6VzdHK:-K7n_KbklefVqSwLTkvk:1506839908) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f327b1cfbece266ee2eb48242bb64f70cba6a5b5/src/app/geo/geo.service.js#L21)):*
TODO now or later, we might want to add some layering around the registry and the order so that geoService only exposes stuff like `currentLayerOrder()` or `moveLayer(curPos,newPos)`.  Avoids any issues where another module sets something that it shouldn't and also gives us a single point to fire update events to the UI.

---

*[src/app/geo/geo.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201#-K7nXvmvH84scEUXzRb5:-K7nXvmwGJCaFnDF-_ua:-547641599) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f327b1cfbece266ee2eb48242bb64f70cba6a5b5/src/app/geo/geo.service.js#L46)):*
muffin warning: if you need to reference `this` inside a service use `const self = this` at the top level of the service and then reference `self` throughout the rest of the service

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201)*

**Comment by AleksueiR** [comment]
Is there enough functionality in the service, so it makes sense to add some unit tests or should we wait for more guts?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201#-K7nXvmvH84scEUXzRb5:-K7phcjj-0rkspXtOUQw:1143415615) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f327b1cfbece266ee2eb48242bb64f70cba6a5b5/src/app/geo/geo.service.js#L46)):*
James, if you are using `this` to get to the `service` object, you can, as Aly suggested, move `registerLayer` and `registerAttributes` functions inside the `geoService` function and access layers using `service.layers` instead of `this.layers`. No need for other variables. All our Angular services are written this way.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201#-:-K7pjf1cyBFb4gdsbLdR:-227007003)*

**Comment by james-rae** [comment]
We agreed yesterday that unit tests are not a focus for the current sprint

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 21 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201#-K7n_KbjkwegdX6VzdHK:-K7qFojSVHaNx-OUN9r4:-2131635668) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f327b1cfbece266ee2eb48242bb64f70cba6a5b5/src/app/geo/geo.service.js#L21)):*
Comment with future design strategy added

---

*[src/app/geo/geo.service.js, line 46 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201#-K7nXvmvH84scEUXzRb5:-K7qP6sx_RAOwTQ0pTsi:1399683517) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f327b1cfbece266ee2eb48242bb64f70cba6a5b5/src/app/geo/geo.service.js#L46)):*
Done, learning enhanced

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201#-:-K7qFQ5SZmVr-Gq3ut0B:2096649314)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/201)*

**Pull request merged**
