### PR TITLE
Language mismatch in RCS bookmark

### PR DESCRIPTION
**Pull request by james-rae**
## Description
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1674 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1677

## Testing
Medley of bookmark, back to cart, and language change

## Documentation
Comments

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1675)

### CODE REVIEW

**Comment by james-rae** [comment]
^ I put the person under Reviewer instead of Assigned. It's almost as good

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1675#-:-KcPZcFSJxBNr76_HiVy:b5f1vi5)*

**Comment by alyec** [comment]
:lgtm:

I think this is the best we can do until we start encoding language in bookmark.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1675#-:-KcPaIwF_fOUXGhgmBDL:bv8ehxs)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1675)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1675#-:-KcTQRreBwxDCSMAqL14:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1675)*

**Pull request merged**
