### PR TITLE
fix(layerRegistry): workaround fix provided for issue 1637

### LINKED ISSUE #1637: Missing symbology for some user added CESI layer map points
http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
Test Data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

Added Air Emissions sub-layer for CESI from above test data, clicking map points will open Feature Details panel as below screenshot, but the symbology is missing, and the magnifying glass button is not responding.
image

### PR DESCRIPTION
**Pull request by milesap**
## Description

See issue #1637 for details

Closes #1637

## Testing
Works with CESI layer provided, additional tested may be needed

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1721)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 557 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1721#-KdlcXb5NBs9p-YHP4k6:-KdlcXb5NBs9p-YHP4k7:brf3hhh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63768803661c5372499a5e0fc39b2453cadbda3a/src/app/geo/layer-registry.service.js#L557)):*
> ```JavaScript
>                 // Implementation of "Working Lazy" solution provided by James (issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1637)
>                 if (typeof layer === 'undefined') {
>                     const levelDetails = zoomIn ? geoState.lods : [...geoState.lods].reverse();
> ```

I think we might be able to remove this line, as we are always going to zoom in for the edge case. The second parameter below would become `geoState.lods[0]` I believe (test first)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1721)*

**Comment by milesap** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 557 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1721#-KdlcXb5NBs9p-YHP4k6:-Ke-6uNM0r4K_qeQhChA:baru8x5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/63768803661c5372499a5e0fc39b2453cadbda3a/src/app/geo/layer-registry.service.js#L557)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I think we might be able to remove this line, as we are always going to zoom in for the edge case. The second parameter below would become `geoState.lods[0]` I believe (test first)
</blockquote></details>

Good idea, though in testing seems like we need the last array element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1721)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1721)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1721)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1721)*

**Pull request merged**
