### PR TITLE
Turn datatable "details" and "zoom in/out" "buttons" into real buttons

### LINKED ISSUE #766: Turn datatable "details" and "zoom in/out" "buttons" into real buttons
These buttons are right now just icons with a click listeners applied to them (they are also not keyboard accessible and their tooltips are inferior). 

These buttons need to be turned into proper button directives. To avoid making hundreds of these directives for the datatable, I believe we can built one each and reuse them.

### PR DESCRIPTION
**Pull request by AleksueiR**
It's not possible to reuse a single compiled directive for all the zoom and details button in the table. We have to compile a directive for each button with a shared scope.

When table is being rendered, placeholder markers for zoom and details buttons are inserted. On the `draw.dt` event, placeholders are replaced with properly compiled buttons.

Closes #766

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1024)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG2-pCy4HON55DASoZ:-KOG2-pDDq9RYEu5kcU8:76723949) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L2)):*
> ```JavaScript
> (() => {
>     // button blueprints to be added to the table rows
> ```

Add comment about `self` being named as such to be used in the BUTTON_TEMPLATE.

---

*[src/app/ui/filters/filters-default.directive.js, line 199 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG3Zoehr8MpMWjnqmj:-KOG3Zoehr8MpMWjnqmk:-187962118) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L199)):*
> ```JavaScript
>                 /**
>                  * Table initialization callback. This will hide the loading indicator.
>                  */
> ```

missing `@function` and probably `@private`

---

*[src/app/ui/filters/filters-default.directive.js, line 211 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG3dekzm7hVWpQJUDY:-KOG3dekzm7hVWpQJUDZ:-187962118) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L211)):*
> ```JavaScript
>                 /**
>                  * Table draw callback. This will replace row placeholder button with real angular directives.
>                  */
> ```

missing `@function` and probably `@private`

---

*[src/app/ui/filters/filters-default.directive.js, line 233 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG3wDuYe0L-Tfaf952:-KOG3wDuYe0L-Tfaf953:-187962118) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L233)):*
> ```JavaScript
>                 /**
>                  * Row zoom click handler. Will zoom to the feature clicked.
>                  * @param  {Number} rowNumber number of the row clicked
> ```

missing `@function` and probably `@private`

---

*[src/app/ui/filters/filters-default.directive.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG12oW6jxVvJD1r_fK:-KOG12oX57Qc2lIozVu_:-187962118) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L249)):*
> ```JavaScript
>                  * Row details click handler. Will display details for the feature clicked.
>                  * @param  {Number} rowNumber number of the row clicked
>                  */
> ```

missing `@function` and probably `@private`

---

*[src/app/ui/filters/filters-default.directive.js, line 301 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG1VNPYdHkrLhbSvdA:-KOG1VNPYdHkrLhbSvdB:-1942883290) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L301)):*
> ```JavaScript
>                  */
>                 function addColumnInteractivity(column, buttons) {
>                     // use render function to augment button to displayed data when the table is rendered
> ```

Add a comment that we have to do horrible string manipulation for datatables' benefit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG2-pCy4HON55DASoZ:-KOGPNSUZNBah7gTCMJc:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L2)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Add comment about `self` being named as such to be used in the BUTTON_TEMPLATE.
</details>
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 199 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG3Zoehr8MpMWjnqmj:-KOGPTV55fFrM5lBSdha:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L199)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> missing `@function` and probably `@private`
</details>
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 211 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG3dekzm7hVWpQJUDY:-KOGPn_eNpK1ZZ5JWLcu:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L211)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> missing `@function` and probably `@private`
</details>
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 233 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG3wDuYe0L-Tfaf952:-KOGPoL7bUNs7fCUge-k:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L233)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> missing `@function` and probably `@private`
</details>
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG12oW6jxVvJD1r_fK:-KOGPoflRjqNg2YxUIqj:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L249)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> missing `@function` and probably `@private`
</details>
Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 301 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOG1VNPYdHkrLhbSvdA:-KOGQo74dKc5X9OeD-Vy:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b4feb03feab42b8e5f1d648a19f887c603147cd/src/app/ui/filters/filters-default.directive.js#L301)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Add a comment that we have to do horrible string manipulation for datatables' benefit.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 315 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOGSfRNRP8R0HXNJ9B4:-KOGSfRNRP8R0HXNJ9B5:2143625280) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1846d1a67aa98fbe2bffc264936a23a3832bbc85/src/app/ui/filters/filters-default.directive.js#L315)):*
> ```JavaScript
>                     // it's not possble to return a compiled directive from the `render` function since directives compile directly into dom nodes
>                     // first, button placeholder nodes are rendered as part of the cell data
>                     // then, on `draw.dt`, these placeholders are replaced with proper compliled button directives
> ```

typo: compiled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 315 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024#-KOGSfRNRP8R0HXNJ9B4:-KOGTLNW6SxXTuhjNPxO:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/24a85329b994dcb5f3b8655f126c5ec676ef52ae/src/app/ui/filters/filters-default.directive.js#L315)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: compiled
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1024)*

**Pull request merged**
