### PR TITLE
fix(core): update dependencies

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Sinon moved their release files. Bardjs now fetches Sinon by itself.

## Testing
Nope.

## Documentation
What is it?

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1723)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1723)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1723)*

**Comment by milesap** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1723)*

**Comment by AleksueiR** [comment]
Targeted master instead of develop :man_facepalming: .

**Pull request closed without merging**
