### PR TITLE
feat(core): add debugging options to the bootstrap

### PR DESCRIPTION
**Pull request by AleksueiR**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1033)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/bootstrap.js, line 237 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033#-KOLjPq6dIffT8xkhYs5:-KOLjPq7SAdxKyDA9xih:1394140300) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eea74ed229de982a392f6819b2d6438e8107923d/src/app/bootstrap.js#L237)):*
> ```JavaScript
>         /***/
> 
>         function detectBlur(event) {
> ```

jsdoc headers (and on the functions below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/bootstrap.js, line 237 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033#-KOLjPq6dIffT8xkhYs5:-KOLn3ODjknrROcxe285:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eea74ed229de982a392f6819b2d6438e8107923d/src/app/bootstrap.js#L237)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> jsdoc headers (and on the functions below)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/app/bootstrap.js, line 291 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033#-KOLnYQdIXluzWwX3jcn:-KOLnYQdIXluzWwX3jco:1173230312) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e27bfb2b131ae3d0f4e476587db2ee452847666d/src/app/bootstrap.js#L291)):*
> ```JavaScript
>          * @private
>          */
>         function dettachEvents() {
> ```

should be detach

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/bootstrap.js, line 291 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033#-KOLnYQdIXluzWwX3jcn:-KOLoQutKSVRQkSrURa4:-1172476023) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e27bfb2b131ae3d0f4e476587db2ee452847666d/src/app/bootstrap.js#L291)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> should be detach
</details>
very true, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1033)*

**Pull request merged**
