### PR TITLE
fix(filter): set filter menu layout the same as side nav layout

### LINKED ISSUE #1743: Update layout menu to match main menu layout
From user comments

Use the same “Icon > Label > Checkmark” layout order in the datatable menu as the new layout used in the main burger menu. It’s way more user friendly and visually efficient.

screen shot 2017-03-07 at 11 39 26 am

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1743

## Description

Set filters menu the same layout as other menu (icon / text / checkbox)

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1819)

### CODE REVIEW

**Comment by milesap** [comment]
Could you update `angular-material` in `bower.json` to version `1.1.3`. This version will be used in v2.0 and I recall something changing in that version that broke the current way icons displayed in the menu (they were no longer right justified). I fixed it with some css in v2.0 but you may not have any issues if done here.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-:-Kg_4X1eHLQBB1wxhjDV:bzb1nuq)*

**Comment by jolevesq** [comment]
It is already 1.1.3 when I look inside bower.json.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-:-Kg_V-HKyOvZkVzQq5G2:bu83t8m)*

**Comment by milesap** [comment]
Ok perfect - I was looking at v2.0, already updated in 1.7 :+1: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-:-Kg_VIzlcOgdtpINT4f2:b5bz91d)*

**Comment by milesap** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default-menu.html, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-Kgni2Nj5Bq9wUNuzeM6:-Kgni2Nj5Bq9wUNuzeM7:b-5p7ecp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b8b6c06c7aa644ab680627c5c2335c7ecfdb4087/src/app/ui/filters/filters-default-menu.html#L17)):*
> ```HTML
>             </md-menu-item-->
> 
>             <md-menu-item type="radio" ng-model="self.filtersMode" value="default" ng-click="self.setMode(self.filtersMode)" ng-if="self.currentLayout() === 'large'" rv-right-icon="none">
> ```

Any reason for using `rv-right-icon="none"` instead of just `rv-right-icon`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default-menu.html, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-Kgni2Nj5Bq9wUNuzeM6:-KgnuAWulYa2ptSe1qLZ:b4nx7lc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b8b6c06c7aa644ab680627c5c2335c7ecfdb4087/src/app/ui/filters/filters-default-menu.html#L17)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Any reason for using `rv-right-icon="none"` instead of just `rv-right-icon`?
</blockquote></details>

Nope, just didn't thought about it. I can change it to rv-right-icon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/filters/filters-default-menu.html, line 17 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-Kgni2Nj5Bq9wUNuzeM6:-Kgny81nWdFsl3qQPjbo:b-xvo37) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b8b6c06c7aa644ab680627c5c2335c7ecfdb4087/src/app/ui/filters/filters-default-menu.html#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Nope, just didn't thought about it. I can change it to rv-right-icon
</blockquote></details>

If I put just rv-right-icon it doesn't work, check mark is left align instead of right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/common/menuItem.decorator.js, line 50 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-Kh2JFZ1_l9II5Ckqh1F:-Kh2JFZ2T4cCKCGJNtZs:bf17uds) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b8b6c06c7aa644ab680627c5c2335c7ecfdb4087/src/app/ui/common/menuItem.decorator.js#L50)):*
> ```JavaScript
>                     const button = el.find('.md-button');
> 
>                     // specify icon for checkbox and radio in rv-right-icon - done here since angular material actively removes icons to place its own checkmark icon
> ```

I feel this section is a bit redundant, first we prepend the icon, and then we move the icon out of the button, which makes it look a bit weird and now use the full row length:


What do you think about simplifying it something like this:
```js
// specify icon for checkbox and radio in rv-right-icon - done here since angular material actively removes icons to place its own checkmark icon
if (attrs.rvRightIcon) {
	
	if (attrs.type === 'checkbox' || attrs.type === 'radio') {
		// specifying any string that is not an actual icon name will create an empty icon; use `rv-right-icon="none"` for consistency
		button.prepend($compile(
			`<md-icon md-svg-icon="${attrs.rvRightIcon}"></md-icon>`
		)(scope));
		
		// reverse the checkbox icon so it is icon/text and remove the ident class
		el.removeClass('md-indent');
		// need to apped the icon to the button, otherwise the button will shrink
		button.append(icon);
	} else {
		button.prepend(icon);
	}
}

// wrap the button content in div, so we can set flex on that div as Firefox doesn't support display: flex on button nodes yet: https://bugzilla.mozilla.org/show_bug.cgi?id=984869#c24
button.wrapInner(`<div class='rv-button-flex'></div>`);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819)*

**Comment by jolevesq** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/menuItem.decorator.js, line 50 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-Kh2JFZ1_l9II5Ckqh1F:-KhRxVmldwqTw2Qt1Obj:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b8b6c06c7aa644ab680627c5c2335c7ecfdb4087/src/app/ui/common/menuItem.decorator.js#L50)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I feel this section is a bit redundant, first we prepend the icon, and then we move the icon out of the button, which makes it look a bit weird and now use the full row length:


What do you think about simplifying it something like this:
```js
// specify icon for checkbox and radio in rv-right-icon - done here since angular material actively removes icons to place its own checkmark icon
if (attrs.rvRightIcon) {
	
	if (attrs.type === 'checkbox' || attrs.type === 'radio') {
		// specifying any string that is not an actual icon name will create an empty icon; use `rv-right-icon="none"` for consistency
		button.prepend($compile(
			`<md-icon md-svg-icon="${attrs.rvRightIcon}"></md-icon>`
		)(scope));
		
		// reverse the checkbox icon so it is icon/text and remove the ident class
		el.removeClass('md-indent');
		// need to apped the icon to the button, otherwise the button will shrink
		button.append(icon);
	} else {
		button.prepend(icon);
	}
}

// wrap the button content in div, so we can set flex on that div as Firefox doesn't support display: flex on button nodes yet: https://bugzilla.mozilla.org/show_bug.cgi?id=984869#c24
button.wrapInner(`<div class='rv-button-flex'></div>`);
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819)*

**Comment by milesap** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1819#-:-KhXBPZyLSow6pcA9OQj:bnfp4nl)*

**Pull request merged**
