### PR TITLE
Feature/hilight

### PR DESCRIPTION
**Pull request by james-rae**
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/677 https://github.com/fgpv-vpgf/fgpv-vpgf/issues/771 https://github.com/fgpv-vpgf/fgpv-vpgf/issues/557

Adds hilighting and click pin support
Hilight applied on zooms and grid detail.
Group hilight on identify layer button.
Details pane now has feature specific icon and is collapsable.
Efficiency improvements in grid icon generation

NOTE: currently hilighting is broke for layers in WKT projections.  This will be fixed promptly, but wanted to get the PR in so people can point out all the wrong things.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/793)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 5 of 9 files at r1, 7 of 9 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/details/details.directive.js, line 74 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKTojBXQS7XHBOTwSWP:-KKTojBXQS7XHBOTwSWQ:-88845791) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9df9bf4eed7f93f443c2d8a546a79479e6f8344f/src/app/ui/details/details.directive.js#L74)):*
> ```JavaScript
> 
>             // add hilights to all things in the layer.
>             // TODO is this the appropriate place for hilighting code?
> ```

I think so, yes.

---

*[src/app/ui/filters/filters-default.directive.js, line 269 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKTxLphkYg4ZEIB5Vv5:-KKTxLphkYg4ZEIB5Vv6:-1408177802) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9df9bf4eed7f93f443c2d8a546a79479e6f8344f/src/app/ui/filters/filters-default.directive.js#L269)):*
> ```JavaScript
>                 } else {
>                     // destory table is data is set to null
>                     self.destroyTable();
> ```

Anyone knows how `destroyTable` is called when the panel is closed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 167 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKUbjDYwtd2X462c98R:-KKUbjDYwtd2X462c98S:-1242244217) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5249c0e12507149ea2b9b5ef4c24e0d9e55b3aa1/src/app/ui/filters/filters-default.directive.js#L167)):*
> ```JavaScript
>                     // rather than re-calculating the image, hack-extract it from the symbol tag
>                     const imgArr = row.data().rvSymbol.split('"');
>                     const img = imgArr[imgArr.indexOf('> ```

Can you add a comment: `TODO: create a render function for the rvSymbol column to avoid hack-extracting the symbol from data` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by james-rae** [comment]
WKT is now hilighting

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-:-KKUokDt4o3-dKgwAd2o:1650700360)*

**Comment by james-rae** [comment]
*[src/app/ui/filters/filters-default.directive.js, line 167 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKUbjDYwtd2X462c98R:-KKUpSsyoDv6m8IyGXZ0:-1299657660) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5249c0e12507149ea2b9b5ef4c24e0d9e55b3aa1/src/app/ui/filters/filters-default.directive.js#L167)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Can you add a comment: `TODO: create a render function for the rvSymbol column to avoid hack-extracting the symbol from data` ?
</details>
done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by alyec** [comment]
Reviewed 4 of 9 files at r1, 7 of 9 files at r2, 6 of 6 files at r3, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 41 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKTnYeoGeqCmSxbEyib:-KKTnYeoGeqCmSxbEyic:-1481155332) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9df9bf4eed7f93f443c2d8a546a79479e6f8344f/src/app/geo/identify.service.js#L41)):*
> ```JavaScript
>              * @param  {String} caption   optional captions to be displayed along with the name
>              * @return {Object}           identify result object
>              */
> ```

Can we add a TODO to make this an ES6 class?

---

*[src/app/geo/map.service.js, line 303 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKToBkoAIw4ehobtkH-:-KKToBkoAIw4ehobtkH0:-1890897587) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9df9bf4eed7f93f443c2d8a546a79479e6f8344f/src/app/geo/map.service.js#L303)):*
> ```JavaScript
>             /**
>              * Fetches a graphic from the given layer
>              * Will attempt local copy, will it the server if not available.
> ```

typo? "will hit the server"

---

*[src/app/geo/map.service.js, line 314 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcxQon09AI6BtwrsB_:-KKcxQon09AI6BtwrsBa:1921231956) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L314)):*
> ```JavaScript
>                 // FIXME _layer reference
>                 const layerObj = layer._layer;
>                 const result = {
> ```

TODO make this a class

---

*[src/app/geo/map.service.js, line 414 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcw_7tH9zR4-hgJi0M:-KKcw_7tH9zR4-hgJi0N:-1949913644) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L414)):*
> ```JavaScript
>              * Performs the application of a hilight for a graphic
>              *
>              * @ Private
> ```

typo `@private`

---

*[src/app/geo/map.service.js, line 415 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcweYwi7-ofnp4UPx9:-KKcweYwi7-ofnp4UPxA:1401021626) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L415)):*
> ```JavaScript
>              *
>              * @ Private
>              * @param  {Object|Array} graphicBundle a graphic bundle or array of graphic bundles for the item(s) to hilight (see function fetchGraphic)
> ```

`@see` will work with the new jsdoc `@see fetchGraphic`

---

*[src/app/geo/map.service.js, line 417 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcx_tGJvd5s0k0buuR:-KKcx_tH9OTwgl1LTLPZ:938670900) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L417)):*
> ```JavaScript
>              * @param  {Object|Array} graphicBundle a graphic bundle or array of graphic bundles for the item(s) to hilight (see function fetchGraphic)
>              */
>             function applyHilight(graphicBundle) {
> ```

There is a lot of geoApi work in here.  Can we move more of this into geoApi (for example, extract the SR and calls with `(bundles, SR)` and return with an array of highlightPromises)?

---

*[src/app/ui/details/details-content.html, line 8 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKczzpadW83l4DUuTrL:-KKczzpbhmWtEkuzMFtQ:-1600794277) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/ui/details/details-content.html#L8)):*
> ```HTML
>     <div class="rv-subcontent rv-{{self.item.requester.format}}" ng-class="{ 'rv-hide': self.isHidden }" ng-switch on="self.item.requester.format">
> 
>         
> ```

Which translations are missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/ui/details/details-content.html, line 8 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKczzpadW83l4DUuTrL:-KKhpWfa3Io63AmMCZRE:1293049411) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/ui/details/details-content.html#L8)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Which translations are missing?
</details>
All translations are there. I forgot to remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by james-rae** [comment]
Review status: 12 of 18 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/geo/map.service.js, line 303 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKToBkoAIw4ehobtkH-:-KKj8sodYgFPM3wbuN5J:-372963176) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9df9bf4eed7f93f443c2d8a546a79479e6f8344f/src/app/geo/map.service.js#L303)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo? "will hit the server"
</details>
say it in a British accent and its ok.  done, thanks.

---

*[src/app/geo/map.service.js, line 314 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcxQon09AI6BtwrsB_:-KKj8z4AI6DPMpwrCQhO:-1299657660) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L314)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> TODO make this a class
</details>
done, thanks

---

*[src/app/geo/map.service.js, line 414 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcw_7tH9zR4-hgJi0M:-KKj90hIuEpS96cLurfm:-361087922) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L414)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `@private`
</details>
ooops.  done, thanks.

---

*[src/app/geo/map.service.js, line 415 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcweYwi7-ofnp4UPx9:-KKj935ItCKrer6py-5Y:-583291524) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L415)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `@see` will work with the new jsdoc `@see fetchGraphic`
</details>
neat-o.  done, thanks

---

*[src/app/geo/map.service.js, line 417 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKcx_tGJvd5s0k0buuR:-KKj95XFoCmbBfyssFox:-1299657660) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/geo/map.service.js#L417)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> There is a lot of geoApi work in here.  Can we move more of this into geoApi (for example, extract the SR and calls with `(bundles, SR)` and return with an array of highlightPromises)?
</details>
done, thanks

---

*[src/app/ui/details/details-content.html, line 8 \[r6\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKczzpadW83l4DUuTrL:-KKj97orAx9Zg6r7ULt3:-1554113516) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1c63021c69af934bee2c7a53bd970a1db6ecf00/src/app/ui/details/details-content.html#L8)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> All translations are there. I forgot to remove this.
</details>
smited. done, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 41 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793#-KKTnYeoGeqCmSxbEyib:-KKjAa2Uy6psPpJGbkru:-1299657660) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9df9bf4eed7f93f443c2d8a546a79479e6f8344f/src/app/geo/identify.service.js#L41)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can we add a TODO to make this an ES6 class?
</details>
done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 6 of 6 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Comment by cynngah** [comment]
Reviewed 1 of 9 files at r1, 6 of 9 files at r2, 3 of 6 files at r3, 6 of 6 files at r7, 2 of 2 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/793)*

**Pull request merged**
