### PR TITLE
feat(filters): add reorder column fonctionnality, fix some bugs from …

### PR DESCRIPTION
**Pull request by jolevesq**
## Description
Capability to reorder columns in datatables (colReoder extension). Reorder can be done by dragging the field on datatable, by draggin the field (handle) in setting panel or with the keyboard in setting panel.

This PR contains some other small modifications from the rebase.

## Testing
Chrome, FF and Safari

## Documentation
Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1693)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm: Reorder demo works on desktop (checked Chrome, Firefox, and IE). :+1:  Can someone test mobile please?

Column headers overllap in IE. Not sure if it's related to PR or just a new bug:


---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/filters/filters-setting-panel.directive.js, line 83 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd10VeUotmgJavNrs6t:-Kd10VeUotmgJavNrs6u:buw313h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-setting-panel.directive.js#L83)):*
> ```JavaScript
> 
>             // on drag start
>             scope.$on('filters-bag.drag', (evt, dragElement, source) => {
> ```

Can you add a TODO to abstract the scrolling animation, to avoid code duplication? 

---

*[src/app/ui/filters/filters-setting-panel.html, line 14 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd0zlS_uZm2CLhptPpx:-Kd0zlSaE8m54hPLbxLb:bubgj35) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-setting-panel.html#L14)):*
> ```HTML
>         </li>
>          
>          <ul  class="rv-filter-list" dx-start-with="self.columns"
> ```

`dx-start-with` is used to render tree structures. I'm not sure if you need that here, table columns are just a flat list, right? If so, this can be safely removed, I hope :)

---

*[src/content/styles/modules/_filters.scss, line 223 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd1-TCgxLCv5n2Yo_FQ:-Kd1-TCgxLCv5n2Yo_FR:bdqw9l5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/content/styles/modules/_filters.scss#L223)):*
> ```SCSS
>     padding-bottom: 45px;
>     overflow-y: auto;
>     user-select: none; // do select header text to avoid table selection when drag & drop columns
> ```

Typo, maybe. Shouldn't this be `do not select...`? Same a above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-:-Kd10jXDb9znMRmrlQbY:b1cmkqt)*

**Comment by james-rae** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693)*

**Comment by milesap** [comment]
Works on iPhone :+1: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-:-Kd25tzEzDJ0DO0XHur8:bir2ei1)*

**Comment by jolevesq** [comment]
I can't test in IE... Do you want me to create an issue? If it is just some CSS and someone can tell me what to do I cana dd it to this PR

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/filters/filters-setting-panel.directive.js, line 83 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd10VeUotmgJavNrs6t:-Kd5qtk5VhAP8sIj4llC:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-setting-panel.directive.js#L83)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you add a TODO to abstract the scrolling animation, to avoid code duplication? 
</blockquote></details>

Done.

---

*[src/app/ui/filters/filters-setting-panel.html, line 14 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd0zlS_uZm2CLhptPpx:-Kd5rqCCeOmGj9IApzO5:bhl560q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-setting-panel.html#L14)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`dx-start-with` is used to render tree structures. I'm not sure if you need that here, table columns are just a flat list, right? If so, this can be safely removed, I hope :)
</blockquote></details>

You are right, it can be remove. I had so much problem to make it work I just let it there in case :smile:. Finally I found it was because of the ng-if and dragula. When I replaced it by ng-show it is ok.

---

*[src/content/styles/modules/_filters.scss, line 223 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd1-TCgxLCv5n2Yo_FQ:-Kd5qXTtDYaRtbBpq999:b-2mcbst) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/content/styles/modules/_filters.scss#L223)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Typo, maybe. Shouldn't this be `do not select...`? Same a above.
</blockquote></details>

You are right! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-:-Kd5sqiBUFAGTagHiOY1:b9gr99b)*

**Comment by AleksueiR** [comment]
Doesn't seem to be CSS-related. I created an issue for that: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1698

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-setting-panel.html, line 14 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd0zlS_uZm2CLhptPpx:-Kd5vpQw0g_6IDBKwJrK:b-n8s3bp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-setting-panel.html#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You are right, it can be remove. I had so much problem to make it work I just let it there in case :smile:. Finally I found it was because of the ng-if and dragula. When I replaced it by ng-show it is ok.
</blockquote></details>

Great, thanks :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-:-Kd5v_zYq6sSAsa-TiNG:b6p8f0m)*

**Comment by alyec** [comment]
Reviewed 10 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/ui/filters/filters-default.directive.js, line 225 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd1tnoGAuiD7qTvwROe:-Kd1tnoGAuiD7qTvwROf:bmfkzne) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-default.directive.js#L225)):*
> ```JavaScript
> 
>                     if (typeof field !== 'undefined') {
>                         // set position if not define
> ```

typo: defined

---

*[src/app/ui/filters/filters-default.directive.js, line 492 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd1uKFVpjIAa5IFQmDk:-Kd1uKFVpjIAa5IFQmDl:bfjn746) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-default.directive.js#L492)):*
> ```JavaScript
> 
>                 /**
>                  * Initialize the keyTable extenstion who let navigate the datatables lilke Excel spread sheet
> ```

typo: like

---

*[src/app/ui/filters/filters-definition.directive.js, line 275 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd6FLG0GpwemUg-hDzw:-Kd6FLG0GpwemUg-hDzx:b-e8jdrl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/03cccfa5c56f00131494b423582d1c431c98a86f/src/app/ui/filters/filters-definition.directive.js#L275)):*
> ```JavaScript
>              * @private
>              * @param {Object} filter the filter object who contains filter values { min, max }
>              * @return {Interger} index    the column index to retreive the data to filter on
> ```

typo: Integer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693)*

**Comment by jolevesq** [comment]
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 225 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd1tnoGAuiD7qTvwROe:-Kd6I0nUZGKuamP6jEif:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-default.directive.js#L225)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: defined
</blockquote></details>

Done.

---

*[src/app/ui/filters/filters-default.directive.js, line 492 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd1uKFVpjIAa5IFQmDk:-Kd6I0CpgEGNzs9i41cz:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44a75ed8d7b18d3bddc71c659cad7a10d8350bf2/src/app/ui/filters/filters-default.directive.js#L492)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: like
</blockquote></details>

Done.

---

*[src/app/ui/filters/filters-definition.directive.js, line 275 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693#-Kd6FLG0GpwemUg-hDzw:-Kd6I-U7DsD19RJcUWyD:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/03cccfa5c56f00131494b423582d1c431c98a86f/src/app/ui/filters/filters-definition.directive.js#L275)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: Integer
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1693)*

**Pull request merged**
