### PR TITLE
Add panel modes to stateManager

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/90)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 244 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90#-K5ApjeKhz6jjyhlyB3J:-K5ApjeKhz6jjyhlyB3K:1425058371) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd90fefdccb072ccd2143a3df656891547f96e01/src/app/common/router/statemanager.service.js#L244)):*
Please add comments to `getMode` and `setMode` functions.

---

*[src/app/common/router/statemanager.service.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90#-K5Apzk8cfrV469BzdCV:-K5Apzk8cfrV469BzdCW:820006209) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd90fefdccb072ccd2143a3df656891547f96e01/src/app/common/router/statemanager.service.js#L249)):*
Why is this needed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90#-K5Apzk8cfrV469BzdCV:-K5BOL7zfsii_tIkb2td:904373228) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd90fefdccb072ccd2143a3df656891547f96e01/src/app/common/router/statemanager.service.js#L249)):*
jshint was complaining about a "possible strict violation"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90#-K5Apzk8cfrV469BzdCV:-K5BP-l0ONOeUPIfOd9V:-936263989) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd90fefdccb072ccd2143a3df656891547f96e01/src/app/common/router/statemanager.service.js#L249)):*
It shouldn't in this case. Can you test again?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90)*

**Comment by spencerwahl** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 244 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90#-K5ApjeKhz6jjyhlyB3J:-K5BVg-2cWBeVl8gDmTc:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd90fefdccb072ccd2143a3df656891547f96e01/src/app/common/router/statemanager.service.js#L244)):*
Done.

---

*[src/app/common/router/statemanager.service.js, line 249 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90#-K5Apzk8cfrV469BzdCV:-K5BVl53Z9DI_16nBCO2:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bd90fefdccb072ccd2143a3df656891547f96e01/src/app/common/router/statemanager.service.js#L249)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/90)*

**Pull request merged**
