### PR TITLE
Api 09 (LinearRing, MultiLineString)

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2615.

Changes how `LinearRings` are created and also adds functionality for `MultiLineStrings`.

## Testing
```js
MULTILINE
    var pointA = new RZ.GEO.Point(0, 'https://image.flaticon.com/icons/svg/17/17799.svg', [-79, 43]);
    var pointE = new RZ.GEO.Point(4, 'M24.0,2.199C11.9595,2.199,2.199,11.9595,2.199,24.0c0.0,12.0405,9.7605,21.801,21.801,21.801c12.0405,0.0,21.801-9.7605,21.801-21.801C45.801,11.9595,36.0405,2.199,24.0,2.199zM31.0935,11.0625c1.401,0.0,2.532,2.2245,2.532,4.968S32.4915,21.0,31.0935,21.0c-1.398,0.0-2.532-2.2245-2.532-4.968S29.697,11.0625,31.0935,11.0625zM16.656,11.0625c1.398,0.0,2.532,2.2245,2.532,4.968S18.0555,21.0,16.656,21.0s-2.532-2.2245-2.532-4.968S15.258,11.0625,16.656,11.0625zM24.0315,39.0c-4.3095,0.0-8.3445-2.6355-11.8185-7.2165c3.5955,2.346,7.5315,3.654,11.661,3.654c4.3845,0.0,8.5515-1.47,12.3225-4.101C32.649,36.198,28.485,39.0,24.0315,39.0z', [79, 32]);
    var lineB = new RZ.GEO.LineString(12, [pointA, pointE]);
    var hoverB = new RZ.GEO.Hover(1, '<a href="https://www.w3schools.com/html/">Visit our HTML tutorial</a>', { followCursor: true, position: 'bottom' });
    var multiLineA = new RZ.GEO.MultiLineString(5, [lineB, [[-70, 45], [-70, 57], [-55, 57], [-55, 45]], [[-10, 45], [-10, 57], [-20, 57], [-20, 45]]]);
    multiLineA.hover = hoverB;
    RZ.mapInstances[0].simpleLayer.addGeometry([multiLineA]);

POLYGON
    var pointA = new RZ.GEO.Point(0, '', [-79, 43]);
    var pointE = new RZ.GEO.Point(4, '', [-49, 70]);

    // default settings - only the outline ring, no fill for polygon
    var polygonA = new RZ.GEO.Polygon(100, [[pointA, [-79, 70], pointE, [-49, 43]], [[-70, 45], [-70, 57], [-55, 57], [-55, 45]]]);
    // custom settings - just the fill for the polygon, no outline ring
    var polygonB = new RZ.GEO.Polygon(101, [], { outlineWidth: 0, fillColor: '#000000', fillOpacity: 1 });

    var linearRingC = new polygonB.LinearRing([[-10, 45], [-10, 57], [-20, 57], [-20, 45]]);
    polygonB.addLinearRings([linearRingC]);

    var hoverA = new RZ.GEO.Hover(0, 'my annotation');
    var hoverB = new RZ.GEO.Hover(1, '<a href="https://www.w3schools.com/html/">Visit our HTML tutorial</a>', { followCursor: true, position: 'left' });
    polygonA.hover = hoverA;
    polygonB.hover = hoverB;
    RZ.mapInstances[0].simpleLayer.addGeometry([polygonA, polygonB]);
```

## Documentation
https://jahidahmed.github.io/docs/api/developer/index.html

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2621)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 52 of 53 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[api/src/geometry.ts, line 443 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2621#-L9Gq4Za7mQelMf958H0:-L9Gq4Za7mQelMf958H1:b-73u4oi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0a4e2e590c7637e27d6fe663837c51e0aaa569cc/api/src/geometry.ts#L443)):*
secret tech to avoid `let counter` and `counter++`

> `elements.forEach((elem, counter) => {

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2621)*

**Comment by JahidAhmed** [comment]
Review status: 50 of 51 files reviewed at latest revision, 1 unresolved discussion.

---

*[api/src/geometry.ts, line 443 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2621#-L9Gq4Za7mQelMf958H0:-L9Gs6JT1_doAjjdNcxC:b-mhsq5s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0a4e2e590c7637e27d6fe663837c51e0aaa569cc/api/src/geometry.ts#L443)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

secret tech to avoid `let counter` and `counter++`

> `elements.forEach((elem, counter) => {
</blockquote></details>

donethanks

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2621)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2621)*

**Comment by milesap** [comment]
Reviewed 51 of 53 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2621)*

**Pull request merged**
