### PR TITLE
feat(ui): allow datagrid to be filtered by current extent

### LINKED ISSUE #822: Allow Datagrid to be Filtered by Current Extent
The viewer should allow for the user to filter the datagrid by the current viewable extent.  This would be done by providing a Filter by Extent option when viewing the datagrid.

### PR DESCRIPTION
**Pull request by milesap**
Closes #822

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1136)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/filters/filters.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQbLJ0S4F3pbl4ZJy0E:-KQbLJ0S4F3pbl4ZJy0F:bpqe5j1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L1)):*
> ```JavaScript
> /* global esri */
> ```

remove (and see comments below)

---

*[src/app/ui/filters/filters.service.js, line 128 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQbLTp3gybOZVXXb1Tr:-KQbLTp3gybOZVXXb1Ts:b-doxkle) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L128)):*
> ```JavaScript
> 
>             // create and set the esri query parameters
>             const queryTask = new esri.tasks.QueryTask(_queryURL(state.requester.legendEntry));
> ```

this esri query stuff should be moved to geoApi. I'll talk to you tomorrow about the best way to do it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 9 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/app/geo/geo.constant.service.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQeh5TvsYKOshaJ2xo_:-KQeh5TvsYKOshaJ2xoa:b-l00ez9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/geo/geo.constant.service.js#L99)):*
> ```JavaScript
>                     visible: false
>                 },
>                 filterExtent: {
> ```

Can we name this flag just `filter`? I want to use it for regular datatable filters as well.

---

*[src/app/ui/filters/filters-default-menu.directive.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQerKW6vw_DGEDSq96P:-KQerKW6vw_DGEDSq96Q:bt6q7rj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default-menu.directive.js#L47)):*
> ```JavaScript
>         self.setFilter = setFilter;
> 
>         $scope.$watch(() => stateManager.display.filters.requester, req => {
> ```

It would be cleaner to have `filterService` expose the filter flag from the currently viewed layer and bind this menu option directly to it.

---

*[src/app/ui/filters/filters-default-menu.directive.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQerSq5kW2wCQUYIUOm:-KQerSq5kW2wCQUYIUOn:b-1wykds) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default-menu.directive.js#L59)):*
> ```JavaScript
> 
>         function setFilter(state) {
>             stateManager.display.filters.requester.legendEntry.flags.filterExtent.visible = state;
> ```

Instead of setting filter state directly, emit an event, so either the filters directive or filters service can handle that. The menu directive shouldn't know about requesters and legend entry flags.

---

*[src/app/ui/filters/filters-default.directive.js, line 109 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQepBF5JS2VRf59NX8W:-KQepBF6nZOp13ivgKc8:bau8hhf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default.directive.js#L109)):*
> ```JavaScript
> 
>                 // TODO: move hardcoded stuff in consts
>                 containerNode = containerNode || el.find('.rv-filters-data-container');
> ```

Right now `createTable` is called on every extent change even the "filter by extent" option is off. This blocks the interface for a second or two while the table is being redrawn.

---

*[src/app/ui/filters/filters-default.directive.js, line 399 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQehd8z0D3YQWw9jrlG:-KQehd8z0D3YQWw9jrlH:b9zcwz9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default.directive.js#L399)):*
> ```JavaScript
>                     deferredAction = isFullyOpen ?
>                         self.createTable(getDToLang()) :
>                         () => self.createTable(getDToLang());
> ```

Why do you store results of the `createTable` in `deferredAction`? If this is unintended, a regular `if` would be better. Then you also don't need to check if `deferredAction` is a function.

---

*[src/app/ui/filters/filters.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQejgEPTUciprg53twC:-KQejgEPTUciprg53twD:b7fsslg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L66)):*
> ```JavaScript
>             });
> 
>             // triggers when map extent is changing
> ```

Instead of polling current extent, `mapService` can rebroadcast the `update-end` event and you can listen for it here.

---

*[src/app/ui/filters/filters.service.js, line 112 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQeoTCRHlSvN9T06mVA:-KQeoTCSHU_0wroY3gKZ:b-v02r94) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L112)):*
> ```JavaScript
>             });
> 
>             return aPromise;
> ```

I don't see the return value being used anywhere.

---

*[src/app/ui/filters/filters.service.js, line 141 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQeqzY1wS1pK0eItKRU:-KQeqzY1wS1pK0eItKRV:b-i33nhu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L141)):*
> ```JavaScript
>                 const validOIDs = featureSet.features.map(feat => feat.attributes[state.data.oidField]);
>                 // only state rows with an OID in validOIDs is kept
>                 filteredState.data.rows = state.data.rows.filter(row =>
> ```

Instead of manually filtering row here and then recreating the datatable, we can use [Datatable's filter API](https://datatables.net/reference/api/filter()) to filter directly on the datatalbe's rows. Then we don't need to recreate datatable every time the extent changes - should speed things up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by milesap** [comment]
Review status: 0 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/app/geo/geo.constant.service.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQeh5TvsYKOshaJ2xo_:-KQg9G5CbYPBZiqI4GcZ:b-xsr3c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/geo/geo.constant.service.js#L99)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Can we name this flag just `filter`? I want to use it for regular datatable filters as well.
</details>
Changed the name to `filter`

---

*[src/app/ui/filters/filters-default-menu.directive.js, line 47 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQerKW6vw_DGEDSq96P:-KQzYfWOe75llE1D8CBF:b-kpvzh5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default-menu.directive.js#L47)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> It would be cleaner to have `filterService` expose the filter flag from the currently viewed layer and bind this menu option directly to it.
</details>
Exposed a `filter.isActive` boolean property to `filterService`.

---

*[src/app/ui/filters/filters-default-menu.directive.js, line 59 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQerSq5kW2wCQUYIUOm:-KQzZDndQ0hDAZqC6N1o:bquf1gm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default-menu.directive.js#L59)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of setting filter state directly, emit an event, so either the filters directive or filters service can handle that. The menu directive shouldn't know about requesters and legend entry flags.
</details>
Using the `filter.isActive` property here (See above)

---

*[src/app/ui/filters/filters-default.directive.js, line 109 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQepBF5JS2VRf59NX8W:-KQzZY9bWKYJ0H9GFrQm:b-5xs4am) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default.directive.js#L109)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Right now `createTable` is called on every extent change even the "filter by extent" option is off. This blocks the interface for a second or two while the table is being redrawn.
</details>
Changed this so that `createTable` is only called once per layer selection; `draw` is called otherwise. 

---

*[src/app/ui/filters/filters-default.directive.js, line 399 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQehd8z0D3YQWw9jrlG:-KQz_7MNvqnsYDZRwZky:b499q7j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters-default.directive.js#L399)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Why do you store results of the `createTable` in `deferredAction`? If this is unintended, a regular `if` would be better. Then you also don't need to check if `deferredAction` is a function.
</details>
Changed

---

*[src/app/ui/filters/filters.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQbLJ0S4F3pbl4ZJy0E:-KR-Ol0-kqbwXkDWUWoZ:birglq9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L1)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> remove (and see comments below)
</details>
Ok removed

---

*[src/app/ui/filters/filters.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQejgEPTUciprg53twC:-KR-OK53_93l4VsMHJK0:b4fp0ob) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L66)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of polling current extent, `mapService` can rebroadcast the `update-end` event and you can listen for it here.
</details>
Spoke with James, in this case the `extent-change` event is better since `update-end` is not called for user added layers.  

---

*[src/app/ui/filters/filters.service.js, line 112 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQeoTCRHlSvN9T06mVA:-KQeu2N8rnhURlY0qnL0:b-9wuyec) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L112)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I don't see the return value being used anywhere.
</details>
Return value is now being used 

---

*[src/app/ui/filters/filters.service.js, line 128 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQbLTp3gybOZVXXb1Tr:-KR-OmeD0_QwwZmZdN5r:b5quaou) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L128)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> this esri query stuff should be moved to geoApi. I'll talk to you tomorrow about the best way to do it
</details>
Calling from geoAPI

---

*[src/app/ui/filters/filters.service.js, line 141 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQeqzY1wS1pK0eItKRU:-KQza1C7zGeL46PW3S5E:bkx5dpd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L141)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of manually filtering row here and then recreating the datatable, we can use [Datatable's filter API](https://datatables.net/reference/api/filter()) to filter directly on the datatalbe's rows. Then we don't need to recreate datatable every time the extent changes - should speed things up.
</details>
Using`$.fn.dataTable.ext.search` as the row (range) filter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 11 files at r2.
Review status: 6 of 10 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[src/app/ui/filters/filters-default.directive.js, line 114 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR90DO8EQrIjTAXfkqQ:-KR90DO8EQrIjTAXfkqR:btxvooj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters-default.directive.js#L114)):*
> ```JavaScript
>                 const displayData = stateManager.display.filters.data;
> 
>                 // filtering by extent can yield 0 rows, stop here
> ```

Do we still need this?
I think we should let the table draw even if there are no rows in it. Otherwise it's going to look like something broke.

---

*[src/app/ui/filters/filters.service.js, line 66 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KQejgEPTUciprg53twC:-KR8y_zxRthRx6JMXglM:b3c11f8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/490330ad331ae730990863a508a6d8cf701467d7/src/app/ui/filters/filters.service.js#L66)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Spoke with James, in this case the `extent-change` event is better since `update-end` is not called for user added layers.  
</details>
Makes sense :+1: 

---

*[src/app/ui/filters/filters.service.js, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8whZ92kml30-CrOpQ:-KR8whZ92kml30-CrOpR:b-xmg2gu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L27)):*
> ```JavaScript
> 
>         // a list of valid oidField values after filtering is complete
>         let _validOIDs = [];
> ```

Styling: we generally use `_` for "private" variables/functions that get exposed to other code. Here, `_validOIDs` and others cannot be accessed from outside this service. The only thing being exposed is `service` itself - no underscore needed. 

---

*[src/app/ui/filters/filters.service.js, line 72 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8yQ33nUFVbGKLnJTk:-KR8yQ33nUFVbGKLnJTl:bi6dvqy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L72)):*
> ```JavaScript
> 
>             // call _onExtentChange function when the extent has changed
>             geoService.onMapReady.then(() =>
> ```

Instead of adding another `mapReady` indicator, you can reuse the `isMapReady` flag:
```js
scope.$watch(() => geoService.isMapReady, ...);
```

---

*[src/app/ui/filters/filters.service.js, line 139 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR9-6DMdQ_lXDABkZuk:-KR9-6DMdQ_lXDABkZul:b-qgdzz9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L139)):*
> ```JavaScript
> 
>             // if _layerRecord is undefined attempt to get parents
>             if (typeof le._layerRecord === 'undefined') {
> ```

You can use `item.master` to get the top level parent directly.

---

*[src/app/ui/filters/filters.service.js, line 144 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR9-GffTlJKZsqzzjJI:-KR9-GffTlJKZsqzzjJJ:b-xkro6m) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L144)):*
> ```JavaScript
> 
>             // wait until layer has finished updating before filtering
>             const updateWatcher = $rootScope.$watch(() => le._layerRecord._layer.updating, updating => {
> ```

Would be better named `stopUpdateWatcher` since the function de-registers the watch.

---

*[src/app/ui/filters/filters.service.js, line 213 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8w5sC3D4TLx003onr:-KR8w5sDL879iMSpijrw:bd0wvu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L213)):*
> ```JavaScript
>                 if (featureSet.exceededTransferLimit) {
>                     // get the last oidField value to use as a starting point for another query
>                     // TODO: Using the assumption that oidField values are sorted. If this turns out to be not the case,
> ```

What happens if they are not sorted? Is it hard to re-implement this with an assumption that they are not sorted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by milesap** [comment]
Review status: 5 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 114 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR90DO8EQrIjTAXfkqQ:-KRDlWz8SL88vQneyOPv:b-v5tgiu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters-default.directive.js#L114)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Do we still need this?
> I think we should let the table draw even if there are no rows in it. Otherwise it's going to look like something broke.
</details>
No longer needed, removed

---

*[src/app/ui/filters/filters.service.js, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8whZ92kml30-CrOpQ:-KRDl_5_KSYgyzBbcY76:bvjfrss) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L27)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Styling: we generally use `_` for "private" variables/functions that get exposed to other code. Here, `_validOIDs` and others cannot be accessed from outside this service. The only thing being exposed is `service` itself - no underscore needed. 
</details>
Good to know, removed all `_`

---

*[src/app/ui/filters/filters.service.js, line 72 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8yQ33nUFVbGKLnJTk:-KRDldOKP5zPCRegLKqE:b8aa17f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L72)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of adding another `mapReady` indicator, you can reuse the `isMapReady` flag:
> ```js
> scope.$watch(() => geoService.isMapReady, ...);
> ```
</details>
Ok using this instead

---

*[src/app/ui/filters/filters.service.js, line 139 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR9-6DMdQ_lXDABkZuk:-KRDli0YKGJmOI-FWDck:bmjlbc5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L139)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> You can use `item.master` to get the top level parent directly.
</details>
Good to know, changed so `master` is used instead

---

*[src/app/ui/filters/filters.service.js, line 144 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR9-GffTlJKZsqzzjJI:-KRDjDrpVtP8pNjtDW-7:bukbcnd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L144)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Would be better named `stopUpdateWatcher` since the function de-registers the watch.
</details>
Renamed to `stopUpdateWatcher`

---

*[src/app/ui/filters/filters.service.js, line 213 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8w5sC3D4TLx003onr:-KRDjN-G5VSVJYj7YnSZ:b-b89ntl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L213)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> What happens if they are not sorted? Is it hard to re-implement this with an assumption that they are not sorted?
</details>
If they aren't sorted then the last item in the returned list may not have the highest oidField value for this particular result set. I.E. if the returned list was `[1, 5, 2, 0]` and a `exceededTransferLimit` was reached, then we would query again asking for results with an oidField value > 0. This would return  `[1, 5, 2, 0]` again with a `exceededTransferLimit` so an infinite loop is possible. We can't sort client side either since the __first__ result set could include the largest oidField value.

Not hard to fix, `geoAPI` would need to expose the `orderByFields` method so results are sorted before being sent. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by james-rae** [comment]
Reviewed 6 of 11 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 11 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 409 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KRTJ29RxsiWsyzwO0rp:-KRTJ29RxsiWsyzwO0rq:b-ozpg9p) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b28f6fd0a1e259458ae61b59d2ab4e138205258/src/app/ui/filters/filters-default.directive.js#L409)):*
> ```JavaScript
>             $scope.$watch(() => filterService.filterTimeStamps.onChanged, val => {
>                 if (val !== null) {
>                     self.table.draw();
> ```

I find that panning map with a datatable open lags a bit in between when you stop dragging the map, release it, and try to grab it again. The second drag doesn't start immediately, it's delayed for some milliseconds and then the map jumps to the point where it should have been if the drag started normally. I would get this is happening because of the table redraw since it blocks the ui.

Can you try using the debounce service on the `onExtentChange` callback so when the map is panned rapidly, the datatable is not needlessly updated multiple times? I think this would help with the responsiveness of the viewer.

---

*[src/app/ui/filters/filters.service.js, line 213 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8w5sC3D4TLx003onr:-KRTHvrWP-HFe1oFFIgd:bj2krrf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L213)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> If they aren't sorted then the last item in the returned list may not have the highest oidField value for this particular result set. I.E. if the returned list was `[1, 5, 2, 0]` and a `exceededTransferLimit` was reached, then we would query again asking for results with an oidField value > 0. This would return  `[1, 5, 2, 0]` again with a `exceededTransferLimit` so an infinite loop is possible. We can't sort client side either since the __first__ result set could include the largest oidField value.
> 
> Not hard to fix, `geoAPI` would need to expose the `orderByFields` method so results are sorted before being sent. 
</details>
Thanks for the explanation. Can you create an issue for this, so when someone complains, we can remember what is going on? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by milesap** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 409 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KRTJ29RxsiWsyzwO0rp:-KRTWCGA4WNcogIecsg2:brerkmw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b28f6fd0a1e259458ae61b59d2ab4e138205258/src/app/ui/filters/filters-default.directive.js#L409)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I find that panning map with a datatable open lags a bit in between when you stop dragging the map, release it, and try to grab it again. The second drag doesn't start immediately, it's delayed for some milliseconds and then the map jumps to the point where it should have been if the drag started normally. I would get this is happening because of the table redraw since it blocks the ui.
> 
> Can you try using the debounce service on the `onExtentChange` callback so when the map is panned rapidly, the datatable is not needlessly updated multiple times? I think this would help with the responsiveness of the viewer.
</details>
Ok added debounce on extent changing. `500` ms seemed better than `175` default, also tried with `300`, and `400`.

---

*[src/app/ui/filters/filters.service.js, line 213 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8w5sC3D4TLx003onr:-KRTW5p7sOBc97zYmkdw:b-vtfwqm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L213)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Thanks for the explanation. Can you create an issue for this, so when someone complains, we can remember what is going on? :)
</details>
Ok created issue #1174

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/filters/filters-default.directive.js, line 409 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KRTJ29RxsiWsyzwO0rp:-KRTa0OI6W6IYVA0lKnP:b-f1hgzc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b28f6fd0a1e259458ae61b59d2ab4e138205258/src/app/ui/filters/filters-default.directive.js#L409)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Ok added debounce on extent changing. `500` ms seemed better than `175` default, also tried with `300`, and `400`.
</details>
500 is a bit too much, I think; it makes you wait too much for the table to update after the drag is complete. Can you set it at 300 for now? 

---

*[src/app/ui/filters/filters.service.js, line 213 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KR8w5sC3D4TLx003onr:-KRTXOUcSSIapDIZyZKp:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0845ab61cac322eafe208a14ba4ef57d32aff22d/src/app/ui/filters/filters.service.js#L213)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Ok created issue #1174
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by milesap** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 409 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KRTJ29RxsiWsyzwO0rp:-KRTar6OOFK_tjMdbJmn:b8dlbax) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b28f6fd0a1e259458ae61b59d2ab4e138205258/src/app/ui/filters/filters-default.directive.js#L409)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> 500 is a bit too much, I think; it makes you wait too much for the table to update after the drag is complete. Can you set it at 300 for now? 
</details>
Ok changed to 300

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 409 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-KRTJ29RxsiWsyzwO0rp:-KRTb0vgKpGoJbxmq7-5:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7b28f6fd0a1e259458ae61b59d2ab4e138205258/src/app/ui/filters/filters-default.directive.js#L409)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Ok changed to 300
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136#-:-KRTb34Z5z0ku7I4SJrf:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1136)*

**Pull request merged**
