### PR TITLE
feat(ui): add zoom to control four out of scale layers

### LINKED ISSUE #625: feat(ui): add a "zoom to" control for out-of-scale layers
As per latest mockups, `zoom to` control should replace the `visibility` toggle when the layer is out of scale.

Other points:
- identify function should not be executed against out-of-scale layers
- when the layer needs to be zoomed in to its scale level use ; when zoomed out, use 
- invisible layers should keep  icon regardless of their out-of-scale status
- when an invisible layer is set to visible, the icons should change to 
  -  if the layer is in scale;
  -  if the layer is zoomed out of its scale level
  -  if the layer is zoomed in past its scale level

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #625

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/744)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/744)*

**Comment by AleksueiR** [comment]
http://fgpv.cloudapp.net/demo/users/jolevesq/zoom/index-one.html

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> #### feat\(ui\): add zoom to control four out of scale layers
> 
> Closes #625
> 
> 
> 
</details>


---

Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/744#-:-KJqHRTicIVQWetwPt9A:-644701377)*

**Comment by AleksueiR** [comment]
Nicely done! :lgtm: 

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> http://fgpv.cloudapp.net/demo/users/jolevesq/zoom/index-one.html
</details>


---

Reviewed 5 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/744#-:-KJqHcobiO2FOD09BMsB:511382146)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/744)*

**Pull request merged**
