### PR TITLE
chore(build): updated angular material to v1.1.0-rc.5

### PR DESCRIPTION
**Pull request by milesap**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1040)

### CODE REVIEW

**Comment by alyec** [comment]
Looks a bit broken to me:


---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040#-:-KOfA0UW8irZ4fSJDMeb:b-56ukj8)*

**Comment by milesap** [comment]
It sure does - I can't replicate this however, what did you do for this to happen?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040#-:-KOfG6IIctARhMyAZVmG:bidvbp8)*

**Comment by alyec** [comment]
I think this was before the demo site updated with the latest build (so this was r1 where I think _md-icon was missing).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040#-:-KOfHpUkJBS7oWvJS-pa:bcvn4bu)*

**Comment by milesap** [comment]
Ah ok

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040#-:-KOfOLCoew66DEfU-b5E:b-8azvrk)*

**Comment by spencerwahl** [comment]
Legend colour changed, might be a class name change or possibly colliding with fgp styles again.



---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040#-:-KOg91I3vKHrA5Tvhcb_:bs2pj16)*

**Comment by milesap** [comment]
Changed back to white, seems this was changed in angular material itself.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040#-:-KOjCYdN8DNg57Fr75WH:byecpdl)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1040)*

**Pull request merged**
