### PR TITLE
sync symbol alignment with symbol generation

### LINKED ISSUE #2454: Symbology toggles are missaligned
Latest [develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html).

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2454

## Testing
Chrome

## Documentation
inline

## Checklist

- [] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2462)

### CODE REVIEW

**Comment by milesap** [comment]
So the 2px thing was easy, but the image heights are being computed and so far I can't find why they are wrong. I can see  the label container being computed at a wrong height at runtime, but in dev console the label container shows correctly. I'll tackle more on Monday

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2462#-:-Ky2Lf2g_AUDILzrjlmI:b-97xxyg)*

**Comment by milesap** [comment]
Inserted the industrial height calculator I used for export legend.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2462#-:-KyHh_OGFu4AIXyBDeWi:b-4wjw9u)*

**Comment by AleksueiR** [comment]
! don't think it's working:
 :(

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2462#-:-KyHnJe1LrWodcH6u-5l:bvfajgt)*

**Comment by milesap** [comment]
I don't have any more time to spend on this issue, I'm ok to close this PR and revisit in the future.  

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2462#-:-KyHnd1kkVv8bhCCEDXB:bm1esdx)*

**Comment by AleksueiR** [comment]
Sure. Can you remove the calculator code though before we close this?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2462#-:-KyHp1qu6YqWPPyR6LXv:b-dwnne)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2462)*

**Pull request merged**
