### PR TITLE
fix(ui): basemap french language support

### LINKED ISSUE #493: Basemap selector doesn't update on language switch

### PR DESCRIPTION
**Pull request by milesap**
Closes #493

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/641)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/641)*

**Comment by AleksueiR** [comment]
:lgtm: 

<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> #### fix\(ui\): basemap french language support
> 
> Closes #493
> 
> 
> 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/641#-:-KICyjbOj0Vu9XnF7Pl7:980077423)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/641)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/641)*

**Comment by cynngah** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/641)*

**Pull request merged**
