### PR TITLE
fix(legend): show settings options only when settings is available

### LINKED ISSUE #490: Remove settings menu option if no settings available
If there is no settings available for a specific toc entry, remove the setting menu option.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #490

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/617)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend-entry.service.js, line 419 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz0_gfdPBYeY_yvaul:-KHz0_gfdPBYeY_yvaum:-931098966) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L419)):*
> ```JavaScript
>             // if the 'supportsDynamicLayers' flag is false, remove sublayer opacity options
>             if (!this._layerRef.supportsDynamicLayers) {
>                 this.slaves.forEach((slave) => {
> ```

Brackets can be omitted with just one argument.

---

*[src/app/geo/legend-entry.service.js, line 543 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz261u0v4g-qFQXjei:-KHz261u0v4g-qFQXjej:-2129146222) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L543)):*
> ```JavaScript
>         };
> 
>         function checkSettings(options) {
> ```

Needs a jsdoc function comment block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend-entry.service.js, line 419 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz0_gfdPBYeY_yvaul:-KHz5R0mIzXwjt20amcY:1017031852) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L419)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Brackets can be omitted with just one argument.</details>
In the styleguide 8.4, they put brackets when it is multiline arrow function. I dont really care, I can remove them.

---

*[src/app/geo/legend-entry.service.js, line 543 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz261u0v4g-qFQXjei:-KHz4f_0IRp_gjVTaYjW:-1141171194) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L543)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Needs a jsdoc function comment block.</details>
You want the comment block outside the function like  with @param or just /** ... */ inside the function? In geoservice.js there is multiline comment with // is it suppose to be a block comment as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend-entry.service.js, line 419 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz0_gfdPBYeY_yvaul:-KHz6uDiFMzRfLxa2zOY:1625378226) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L419)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> In the styleguide 8.4, they put brackets when it is multiline arrow function. I dont really care, I can remove them.</details>
Haven't realized they do. We generally don't use brackets with a single argument. I would prefer to be consistent though.
@alyec Aly, any thoughts?

---

*[src/app/geo/legend-entry.service.js, line 543 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz261u0v4g-qFQXjei:-KHz6A47idvDZkzlB25T:1909865363) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L543)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> You want the comment block outside the function like  with @param or just /** ... */ inside the function? In geoservice.js there is multiline comment with // is it suppose to be a block comment as well?</details>
Ideally, we want most of the functions to have a proper block comment with @param, @return, etc. to generate documentation from. Extra comments inside the function body won't hurt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend-entry.service.js, line 419 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz0_gfdPBYeY_yvaul:-KHz8aeveJNxocY_0LmR:2055214007) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L419)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Haven't realized they do. We generally don't use brackets with a single argument. I would prefer to be consistent though.
> @alyec Aly, any thoughts?</details>
I think we should add a note that we do not use parens for arrow functions for now (otherwise we'll be doing a lot of style cleanup), but it may be something to look at once we release the beta.  Sounds like a good student task if we decide to change it :)

---

*[src/app/geo/legend-entry.service.js, line 543 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz261u0v4g-qFQXjei:-KHz7yuATUJcHnU7ZpWQ:1360058161) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L543)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Ideally, we want most of the functions to have a proper block comment with @param, @return, etc. to generate documentation from. Extra comments inside the function body won't hurt.</details>
geoService has a bunch of `//` prefixed functions because not everyone knew about the `@private` option.  If you have a function that's not external to the file (like this one) set that and it should be okay for jsdoc.  I believe geoservice has a FIXME or TODO somewhere in the header about cleaning that up at some point (if you don't see it or it's not prominent feel free to add it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by jolevesq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/legend-entry.service.js, line 419 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz0_gfdPBYeY_yvaul:-KHzQ_3oJklsRxaxYjVr:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L419)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think we should add a note that we do not use parens for arrow functions for now (otherwise we'll be doing a lot of style cleanup), but it may be something to look at once we release the beta.  Sounds like a good student task if we decide to change it :)</details>
Done.

---

*[src/app/geo/legend-entry.service.js, line 543 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-KHz261u0v4g-qFQXjei:-KHzQ_mstuP88Q-MwMb7:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c12f23a9b67ec79cc7b42dd11218d00b07be3b32/src/app/geo/legend-entry.service.js#L543)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> geoService has a bunch of `//` prefixed functions because not everyone knew about the `@private` option.  If you have a function that's not external to the file (like this one) set that and it should be okay for jsdoc.  I believe geoservice has a FIXME or TODO somewhere in the header about cleaning that up at some point (if you don't see it or it's not prominent feel free to add it).</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by AleksueiR** [comment]
:lgtm: 

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> #### fix\(legend\): show settings options only when settings is available
> 
> Closes #490
> 
> 
> </details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-:-KHzQo9-83qyBlrMwTJO:980077423)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Comment by jolevesq** [comment]
Do I merge the branch myself or it is the person in charge of the PR?

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> :lgtm: </details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-:-KHzWw_vLhkxAC4wxr_s:272916956)*

**Comment by AleksueiR** [comment]
@cynngah Cynthia is merging PRs this week. Here is the PR rotation page: https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/PR-Rotation

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Do I merge the branch myself or it is the person in charge of the PR?</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-:-KHzXHSSNxusHuWHa0H3:591508559)*

**Comment by cynngah** [comment]
@jolevesq this branch is out of date, can you rebase on top of the current develop branch so I can merge? Thanks :)

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> @cynngah Cynthia is merging PRs this week. Here is the PR rotation page: https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/PR-Rotation</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-:-KHzukGR5P7ePA-Zm9wH:503108226)*

**Comment by jolevesq** [comment]
@cynngah I did a rebase and push again to my origin. Do you need something else? Thanks

<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> @jolevesq this branch is out of date, can you rebase on top of the current develop branch so I can merge? Thanks :)</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617#-:-KI-ABUL1jrLXK3arqfU:51660127)*

**Comment by cynngah** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/617)*

**Pull request merged**
