### PR TITLE
Mercator basemap point click buffer size fix

### PR DESCRIPTION
**Pull request by cynngah**
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1008

Adjust buffer size based on projection and zoom level.

Numbers were obtained through trial and error.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1055)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055#-KPEf5yrCgcquHaFE3Xu:-KPEf5yrCgcquHaFE3Xv:bn4m64k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c8cd1689d9cad817d3568edebe32c089b5c4db47/src/app/geo/identify.service.js#L194)):*
> ```JavaScript
>                 if (map.spatialReference.wkid !== 3978) {
>                     buffSize = buffSize * 8;
>                 }
> ```

All this is working because it is making the buffer size enormous when close to the earth.  Odds are you will get many hits when clicking far away from points on the screen.  Please revert this code back and use the fix below.

---

*[src/app/geo/identify.service.js, line 197 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055#-KPEeZ9_cLLj-8kV5AV6:-KPEeZ9_cLLj-8kV5AV7:brjks4l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c8cd1689d9cad817d3568edebe32c089b5c4db47/src/app/geo/identify.service.js#L197)):*
> ```JavaScript
> 
>                 // Build tolerance envelope of correct size
>                 const cBuff = new gapiService.gapi.mapManager.Extent(1, 1, buffSize, buffSize, point.spatialReference);
> ```

real fix is changing the 1s to 0s.  the failure happens when the size of the buffer is less than 1 map unit (usually meters).  This can occur on the very-close-to earth zoom levels.  The max values in the constructor end up being less than the bad min value of 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by cynngah** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/identify.service.js, line 197 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055#-KPEeZ9_cLLj-8kV5AV6:-KPEr_EOFnRHB42kAvse:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c8cd1689d9cad817d3568edebe32c089b5c4db47/src/app/geo/identify.service.js#L197)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> real fix is changing the 1s to 0s.  the failure happens when the size of the buffer is less than 1 map unit (usually meters).  This can occur on the very-close-to earth zoom levels.  The max values in the constructor end up being less than the bad min value of 1.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by cynngah** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055#-KPEf5yrCgcquHaFE3Xu:-KPIhj1o3zwX9LWDYeLM:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c8cd1689d9cad817d3568edebe32c089b5c4db47/src/app/geo/identify.service.js#L194)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> All this is working because it is making the buffer size enormous when close to the earth.  Odds are you will get many hits when clicking far away from points on the screen.  Please revert this code back and use the fix below.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055#-KPEf5yrCgcquHaFE3Xu:-KPNTs-fi951QXzJ--Jr:b-7o7r0d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c8cd1689d9cad817d3568edebe32c089b5c4db47/src/app/geo/identify.service.js#L194)):*
<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> Done.
</details>
any reason why `const` became `let`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055#-KPEf5yrCgcquHaFE3Xu:-KPNZi3x5DNjC7Fdm3yu:b-hrfa7x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c8cd1689d9cad817d3568edebe32c089b5c4db47/src/app/geo/identify.service.js#L194)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> any reason why `const` became `let`?
</details>
Also, the comment about multiplying by zoom level should be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by cynngah** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055#-KPEf5yrCgcquHaFE3Xu:-KPNfqOajS1OyHPV8F9_:ba6h574) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c8cd1689d9cad817d3568edebe32c089b5c4db47/src/app/geo/identify.service.js#L194)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary>
> Also, the comment about multiplying by zoom level should be removed.
</details>
oh because I was multiplying it by 8 if it was mercator earlier

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1055)*

**Pull request merged**
