### PR TITLE
fix(tooltip): allow only one tooltip to display at a time

### LINKED ISSUE #1760: Some messages hanging after exercising Geolocation Search
Tested build: http://fgpv.cloudapp.net/demo/v1.6.0-1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

This happened when user had a Scale Dependency layer added to FGP Viewer.
- Add above Scale Dependency layer by selecting zoom level 1 to zoom level 4
- Click "Geolocation Search" button
- Enter search text, for example Toronto
- Select any drop down option displayed, for example "Toronto, Peel, ON" (Geographical Area)
- Then click "Close Geolocation Search" button
Put your cursor inside Visualiser on any buttons, including toolbar buttons, or just simply anywhere on the map, you could see some messages hanging on top and on right hand side of the Viewer. Messages will disappear when moving cursor outside of the Viewer.
Below is a screenshot when putting cursor on Geolocation Search button.
image

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1760

## Testing
:eyes: 

## Documentation
inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2145)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/layout/tooltip.decorator.js, line 41 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2145#-Kolq3uthlBuNraWqxHc:-Kolq3uthlBuNraWqxHd:b-4uyrp8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/daf5c44c976c43e71913538a09263c7b2a454201/src/app/layout/tooltip.decorator.js#L41)):*
> ```JavaScript
> 
>                 // this prevents multiple tooltips from displaying at the same time by only showing the most recent (and hiding the others)
>                 scope.$watch('mdVisible', isVisible => {
> ```

Do these watches get removed when the tooltip is destroyed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2145)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/layout/tooltip.decorator.js, line 41 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2145#-Kolq3uthlBuNraWqxHc:-KolqhYWN-fPxr2y2gxh:b-hefxf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/daf5c44c976c43e71913538a09263c7b2a454201/src/app/layout/tooltip.decorator.js#L41)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Do these watches get removed when the tooltip is destroyed?
</blockquote></details>

Yes 
https://stackoverflow.com/questions/25113884/should-angular-watch-be-removed-when-scope-destroyed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2145)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/layout/tooltip.decorator.js, line 41 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2145#-Kolq3uthlBuNraWqxHc:-KolqyV2ctJKA3gHzkkY:bg6yj0x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/daf5c44c976c43e71913538a09263c7b2a454201/src/app/layout/tooltip.decorator.js#L41)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Yes 
https://stackoverflow.com/questions/25113884/should-angular-watch-be-removed-when-scope-destroyed
</blockquote></details>

Sweet :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2145)*

**Comment by AleksueiR** [comment]
Close, but no cigar - there are still four tooltips on the page with one showing up when you hover over the app:


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2145#-:-Koqb1iY6S0QjgmTHsEb:b-egjvo9)*

**Comment by milesap** [comment]
@AleksueiR is looking into this, will open a new PR if a fix is found.

**Pull request closed without merging**
