### PR TITLE
Layer Opacity/Transparency

### PR DESCRIPTION
**Pull request by cynngah**
Second checkbox for #193 
Wires up layer opacity slider to the actual layer.
Also makes preset transparency in configs work.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/389)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 178 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389#-KCpjGORdIULXiSuFVS6:-KCpjGORdIULXiSuFVS7:-740643384) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08b541e2b6cd216ce184a8ffd8ab7bff530d416e/src/app/geo/layer-registry.service.js#L178)):*
If layer defaults are being set properly this should never be the case.  Unless this code is broken I think it would be better to let this throw an exception if it hits an undefined options block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389#-:-KCqNX4he-ISqPR0rf93:1417088721)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 190 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389#-KCqOXNneN-d1HBYth1u:-KCqOXNneN-d1HBYth1v:-1381817659) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/abd40e446e8dd5553fcfebaad9b59150940789b4/src/app/geo/layer-registry.service.js#L190)):*
GGGGGGGGGGGG

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by james-rae** [comment]
Reviewed 1 of 4 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by cynngah** [comment]
*[src/app/geo/layer-registry.service.js, line 178 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389#-KCpjGORdIULXiSuFVS6:-KD-lnqQyac5k0v0BKJk:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/08b541e2b6cd216ce184a8ffd8ab7bff530d416e/src/app/geo/layer-registry.service.js#L178)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/389)*

**Pull request merged**
