### PR TITLE
fix(ui): allow import of raster layer

### LINKED ISSUE #1109: Unable to Import a Raster Layer as the existing Service Types does not identify the layer
Tested on build: http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.htm

Unable to Import a Raster layer. Should this be under supported Service Type?

Tested using the below service url:
http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/0

screenhunter_2404 aug 24 11 42

### PR DESCRIPTION
**Pull request by milesap**
Closes #1109

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1173)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173#-:-KRTYFivBRlZV8L53rPM:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/layer-blueprint.class.js, line 188 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173#-KRhkt1n-DE3Rm7hA1xt:-KRhkt1n-DE3Rm7hA1xu:bjzroml) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/940adef1e10224a41fefca9e5df4a825ec93b20b/src/app/geo/layer-blueprint.class.js#L188)):*
> ```JavaScript
>                                         gapiService.gapi.layer.predictLayerUrl(this.config.url, hint).then(data => {
>                                             info.layers = data.layers;
>                                             flattenDynamicLayerList(info.layers);
> ```

I don't think we need to call `flattenDynamicLayerList` here as we don't give the user option to pick sublayers when it's a raster layer. Sorry, missed it first time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173)*

**Comment by milesap** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-blueprint.class.js, line 188 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173#-KRhkt1n-DE3Rm7hA1xt:-KRi2L0skczbweWtE7fx:bfcyqfx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/940adef1e10224a41fefca9e5df4a825ec93b20b/src/app/geo/layer-blueprint.class.js#L188)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I don't think we need to call `flattenDynamicLayerList` here as we don't give the user option to pick sublayers when it's a raster layer. Sorry, missed it first time.
</details>
Ok removed this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/app/geo/layer-blueprint.class.js, line 188 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173#-KRhkt1n-DE3Rm7hA1xt:-KRi2iUBECyhh2Swr_in:b-ucfkn4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/940adef1e10224a41fefca9e5df4a825ec93b20b/src/app/geo/layer-blueprint.class.js#L188)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Ok removed this
</details>
Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1173)*

**Pull request merged**
