### PR TITLE
fix(ui): basic text output when viewing sample pages in old browser

### LINKED ISSUE #1152: Provide Basic Text Output when Viewing with an old Browser
Browsers that don't support the visualization, like text based browsers such as Links or Lynx.

### PR DESCRIPTION
**Pull request by milesap**
Closes #1152

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1196)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Can you put the `noscript` inside the viewer div?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-:-KS1eQYgjCsRExaQQEwr:bd5en6n)*

**Comment by milesap** [comment]
Yeah, moved into the `.fgpv` element

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-:-KS1gjfI0yX8ewvTqTNl:b-ws637z)*

**Comment by AleksueiR** [comment]
:hatched_chick: 

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-:-KS1hHRyovD2TmTIyHxE:bifvqsd)*

**Comment by jolevesq** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/index-fgp-en.html, line 456 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-KS1i8idm_WtSQ7RIDu3:-KS1i8idm_WtSQ7RIDu4:b7765va) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ba271d950aa111e3e68d6271328cb9371f295b50/src/index-fgp-en.html#L456)):*
> ```HTML
>                             <p>This interactive map requires JavaScript. To view this content please enable JavaScript in your browser or download a browser that supports it.<p>
> 
>                             <p>Cette carte interactive nécessite JavaScript . Pour voir ce contenu s'il vous plaît activer JavaScript dans votre navigateur ou télécharger un navigateur qui prend en charge.</p>
> ```

There is a space after JavaScript and before the .

Pour voir ce contenu**, (add a coma after contenu)** s'il vous plaît**, (add a coma after plait)** activer JavaScript dans votre navigateur ou télécharger un navigateur qui  __le__ prend en charge.

The same modification should be done in every file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196)*

**Comment by milesap** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index-fgp-en.html, line 456 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-KS1i8idm_WtSQ7RIDu3:-KS2MhZa8Z5Np4LbL5LL:b-fl9tfq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ba271d950aa111e3e68d6271328cb9371f295b50/src/index-fgp-en.html#L456)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> There is a space after JavaScript and before the .
> 
> Pour voir ce contenu**, (add a coma after contenu)** s'il vous plaît**, (add a coma after plait)** activer JavaScript dans votre navigateur ou télécharger un navigateur qui  __le__ prend en charge.
> 
> The same modification should be done in every file
</details>
Removed the extra space between the work and period.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196)*

**Comment by AleksueiR** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/index-fgp-en.html, line 456 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-KS1i8idm_WtSQ7RIDu3:-KS6H3hvw-jbp9jRMcjp:bdm0vxf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ba271d950aa111e3e68d6271328cb9371f295b50/src/index-fgp-en.html#L456)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Removed the extra space between the work and period.
</details>
I think you missed adding two commas and __le__.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196)*

**Comment by milesap** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index-fgp-en.html, line 456 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-KS1i8idm_WtSQ7RIDu3:-KS6K37hZ_PFnK6BnPVq:b-886gsx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ba271d950aa111e3e68d6271328cb9371f295b50/src/index-fgp-en.html#L456)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I think you missed adding two commas and __le__.
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196#-:-KS6OYZIm8mwrrgAiogm:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1196)*

**Pull request merged**
