### PR TITLE
fix(ui): north arrow no longer overlaps panels

### LINKED ISSUE #1814: North arrow overlap item when panning up north
This is 2 sample of wierd behaviour when we oan up north. The arrow overlap the toc and the datatable

screen shot 2017-03-29 at 3 28 35 pm
screen shot 2017-03-29 at 3 29 52 pm

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #1814

## Testing
No

## Documentation
No

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1818)

### CODE REVIEW

**Comment by jolevesq** [comment]
It goes under the appbar and filters but not overview map. Should we make this constant so it goes everything or just the filters? If we decide to go under can we put it more on top so we can see the arrow tip when under filter, appbar and overview map?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1818#-:-KgU_pKNQgP9U7_eRzzY:b-iucil3)*

**Comment by AleksueiR** [comment]
Overviewmap is part of the esri map construct, so some trickery is needed to make the north arrow move in between the actual map and overview map.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1818#-:-KgUet8hqc6Bj0Pa5LUR:bchm0bo)*

**Comment by milesap** [comment]
Should I perform this trickery or leave it be?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1818#-:-Kg_3pKi23VeYmxfR6gP:b-94e2pi)*

**Comment by milesap** [comment]
Issue #1826 opened for overview map issue

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1818#-:-Kg_8Jsg0u3P4Vjwxcnn:b-sirtpe)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1818#-:-Kg_8isGd5ARNY6_lNvo:bnfp4nl)*

**Pull request merged**
