### PR TITLE
Update schema

### PR DESCRIPTION
**Pull request by spencerwahl**
## Description
#2526 

May be incomplete, probably better to look (scan) through the whole file and see what I missed, or what descriptions you want enhanced.

## Testing

Hmmmm

## Documentation

Hmmmm

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2542)

### CODE REVIEW

**Comment by milesap** [comment]
Please push a detached tag commit with your updated schema file, then go to https://fgpv-vpgf.github.io/schema-to-docs/?v=the-tag-name-here to see how your updates look/work

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 543 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542#-L26hpkHs8yyWhxsdPrd:-L26hpkHs8yyWhxsdPre:b-s9aedi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76e7b7f9e474e72553b20d80f74f7c9dc2537020/schema.json#L543)):*
> ```JSON
>                 "name": { "type": "string", "description": "The display name of the layer.  If it is not present the viewer will make an attempt to scrape this information." },
>                 "url": { "type": "string", "description": "The service endpoint of the layer.  It should match the type provided in layerType." },
>                 "refreshInterval": { "type": "number", "default": 0, "description": "The automatic refresh interval of the layer in minutes. Maximum interval is 100 minutes." },
> ```

Were all the `refreshInterval` entries supposed to be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542)*

**Comment by spencerwahl** [comment]
https://fgpv-vpgf.github.io/schema-to-docs/?v=schema-update-test2

There are 3 'fixme's under services->properties: geolocation, print and coordInfo
I couldn't tell where they are used (and can't search the whole code base properly) so I'm unsure what extra anything they're supposed to have or if they should even exist.

**Comment by james-rae** [comment]
Yeah, those 3 are poorly defined in the schema.
It looks like `geoLocation` has duplicated down to a child of `search.serviceUrls`
`print` might have morphed into `export` and `exportMapUrl`
`coordInfo` i'm not sure about. Feels more like this is handled by `map.components.mouseInfo` but maybe this is to provide an alternate co-ord lookup service.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542#-:-L26xsiBLO3523fXB8UQ:bpsu60k)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema.json, line 543 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542#-L26hpkHs8yyWhxsdPrd:-L278pzdEHy8DofjqrKu:by1kvgi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76e7b7f9e474e72553b20d80f74f7c9dc2537020/schema.json#L543)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Were all the `refreshInterval` entries supposed to be removed?
</blockquote></details>

No, and I have no idea how they got removed... will add back in, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[schema.json, line 819 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542#-L2KkY34Nbfpbn1AyVTh:-L2KkY34Nbfpbn1AyVTi:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76e7b7f9e474e72553b20d80f74f7c9dc2537020/schema.json#L819)):*
> ```JSON
>                     "required": ["id"]
>                 },
>                 "widgetsWidget": { "type": "object", "additionalProperties": true, "description": "FIXME" }
> ```

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542)*

**Comment by spencerwahl** [comment]
@james-rae remove the first two and leave coordInfo for now then? or scrap them all?

**Comment by milesap** [comment]
Whenever this is good to go, please see https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2542#issuecomment-355570710 so I can verify it's parsing the schema as expected.

**Comment by spencerwahl** [comment]
@milesap https://fgpv-vpgf.github.io/schema-to-docs/?v=schema-update-test3

The 3 fixme's are still in there as I haven't gotten anything definitive about removing/keeping.

**Comment by milesap** [comment]
Great, ty for the link. I'd suggest quickly going through the top level `View Sample` links to see if any samples are missing (empty). For example, `UI.about` and `UI.help` samples are empty, and if you navigate to them they're definitions are vague.  `about` has an array of `oneOf` each having an `allProps` with either content or folder options which isn't clear to the user. Perhaps change this structure, or add more info such as default type and add descriptions to reflect the differences.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542#-:-L2WiD2t059TKv6eBfC6:bbqq71q)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[schema.json, line 925 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542#-L2z-ilOdVgTEZpMScCY:-L2z-ilOdVgTEZpMScCZ:b651tal) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/66a8d14b77491a46f6c338e23753a999bcccdda8/schema.json#L925)):*
> ```JSON
>                     "description": "Layer list in the order which they should be added to the map.  NOTE: ESRI JSAPI v3 cannot draw imagery layers over feature layers."
>                 },
>                 "legend": {
> ```

Here's the trouble maker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542)*

**Comment by milesap** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2542#-:-L33DiFLlHgpat29YupW:bnfp4nl)*

**Pull request merged**
