### PR TITLE
chore(build): webpack will now parse samples of any structure

### PR DESCRIPTION
**Pull request by milesap**
## Description
Added ability in our webpack build to allow for any `sample` folder structure. Moved api related stuff into the `api` folder. Made sub-folders if an api demo has more than one file.
## Testing
WOMM

## Documentation
None

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2574)

### CODE REVIEW

**Comment by barryytm** [comment]
Reviewed 13 of 14 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/samples/bookmark-decode.html, line 0 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574#-L4l-F_DAay_4q75c3VH:-L4l-F_DAay_4q75c3VI:bhplp0f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cc331ab07e9e9e1444f179b5436df9c24ef9068c/src/content/samples/bookmark-decode.html#L0)):*
Is this file supposed to be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574)*

**Comment by milesap** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/samples/bookmark-decode.html, line  at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574#-L4l-F_DAay_4q75c3VH:-L4l0PJSPqWhxgKzQP9p:bnr4ohp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cc331ab07e9e9e1444f179b5436df9c24ef9068c/src/content/samples/bookmark-decode.html#L)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Is this file supposed to be removed?
</blockquote></details>

During build this file would throw an error - removed to see if the file itself was the problem and it was the only one. I can investigate this file further if it is used/useful, let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574)*

**Comment by barryytm** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/samples/bookmark-decode.html, line  at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574#-L4l-F_DAay_4q75c3VH:-L4l1umIIx5vwHJ58lnx:b-64krp7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cc331ab07e9e9e1444f179b5436df9c24ef9068c/src/content/samples/bookmark-decode.html#L)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

During build this file would throw an error - removed to see if the file itself was the problem and it was the only one. I can investigate this file further if it is used/useful, let me know.
</blockquote></details>

Would changing the extension to `tpl`  work?  This file is needed to decode bookmarks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574)*

**Comment by james-rae** [comment]
Reviewed 13 of 14 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/content/samples/bookmark-decode.html, line  at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574#-L4l-F_DAay_4q75c3VH:-L4m7WxgWqDvLkC1TO89:b4e0rh2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cc331ab07e9e9e1444f179b5436df9c24ef9068c/src/content/samples/bookmark-decode.html#L)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Would changing the extension to `tpl`  work?  This file is needed to decode bookmarks.
</blockquote></details>

its very useful. Maybe attempt to try to `tpl` it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574)*

**Comment by milesap** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/samples/bookmark-decode.html, line  at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574#-L4l-F_DAay_4q75c3VH:-L5DxpeV8_r7qx92hdOS:b-evfkda) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/55f1c4c28bbcda01aa826e7731693af70868e791/src/content/samples/bookmark-decode.html#L)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

its very useful. Maybe attempt to try to `tpl` it
</blockquote></details>

Ah, no problem didn't realize it was `.html`. Changing to `.tpl` won't work (those run through a template injector), so I just straight copy (leave as is) any html files from the samples folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574)*

**Comment by barryytm** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2574)*

**Pull request merged**
