### PR TITLE
feat(ui): add map reload message warning (issue#111 for #173)

### PR DESCRIPTION
**Pull request by ec-dev**
add warning to projection header
add warning to hover tip

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/447)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/basemap/basemap.directive.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW8uagyd8C5osRaBS9:-KEW8uagyd8C5osRaBSA:-1969912964) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.directive.js#L194)):*
Wouldn't this `item.needMapRefresh = (basemap.wkid !== item.wkid)` give the same result?

---

*[src/app/ui/basemap/basemap.html, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW9Ka0pSzk7kpd9-so:-KEW9Ka0pSzk7kpd9-sp:-546350561) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.html#L8)):*
Move the style bit to `styles/modules/_basemap.scss` file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/basemap/basemap.html, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW9Ka0pSzk7kpd9-so:-KEWz5Zn3SkRtcrBoSWW:961042614) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.html#L8)):*
Alex, is there a naming standard for the above mentioned item,
right now i have the following setup in _basemap.scss

.rv-basemap-warning-icon-color {
        color: #607D8B;
 }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/basemap/basemap.html, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW9Ka0pSzk7kpd9-so:-KEX0Ye6rhoBU823vicm:-1599804537) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.html#L8)):*
Prefixing with `.rv-` and not using underscores should do it :) You can also use variable for that color, it's in common/_palette.scss.
```css
.rv-basemap-warning {
    color: $primary-color;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by ec-dev** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/basemap/basemap.directive.js, line 194 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW8uagyd8C5osRaBS9:-KEXORtI4vVF-VhBWTJQ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.directive.js#L194)):*
Done.

---

*[src/app/ui/basemap/basemap.html, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW9Ka0pSzk7kpd9-so:-KEXOTrbZgbguGacnHZ4:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.html#L8)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.html, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW9Ka0pSzk7kpd9-so:-KEXThroyRdsY5Ag6NET:1619646444) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.html#L8)):*
Class names are mismatched: `rv-basemap-warning-icon` here, and `rv-basemap-warning` in _basemap.scss.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by ec-dev** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.html, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW9Ka0pSzk7kpd9-so:-KEXeH36dfWkWgoRAKp-:-816148860) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.html#L8)):*
That's a :doughnut: offense. I owe 2 boxes now.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by cynngah** [comment]
Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap.html, line 8 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447#-KEW9Ka0pSzk7kpd9-so:-KEaBQv6p-3j5forQQFZ:703233318) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ad9c4c8c9c8fd3519d412cd733a3b4ff2cdbd83a/src/app/ui/basemap/basemap.html#L8)):*
Nah, that's okay. It's not breaking the build or anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/447)*

**Pull request merged**
