### PR TITLE
Use layer's actual data in the datagrid

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/313)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 936 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/313#-KABnQpQBCNFydJoDW3B:-KABnQpRhACAhj5OR3CL:1861699998) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a0e78f7ec8edb5da19b00eb30eb32c7f5488b001/src/app/ui/toc/toc.service.js#L936)):*
I don't understand the purpose of the slice, or why the position would matter based on `layer.id`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/313)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/313)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 936 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/313#-KABnQpQBCNFydJoDW3B:-KABoxaJS-GAT0supF7E:-598948796) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a02146c6390dd97e42a77cb7c0366a6c885ccd27/src/app/ui/toc/toc.service.js#L936)):*
@AleksueiR was using this for testing, I think he still wanted this in but if he's changed his mind I'll get rid of it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/313)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/toc/toc.service.js, line 936 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/313#-KABnQpQBCNFydJoDW3B:-KAFXE-ZnI6lqHuJJBOI:290773601) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a02146c6390dd97e42a77cb7c0366a6c885ccd27/src/app/ui/toc/toc.service.js#L936)):*
I wanted different amounts of data (number of columns and rows) for different layers to test how the datatable is constructed and how loading times differ.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/313)*

**Pull request merged**
