### PR TITLE
feat(ui): visibility sets remember last selection

### LINKED ISSUE #2224: Keep track of selected radio button when visibility is set to false
radiobutton

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Visibility sets remember last selection when made visible by its parent.

Closes #2224

## Testing

smart_vis_gropu

## Documentation
Inline comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2228)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2228)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2228#-:-Kp_DN6kCE3LNsijXcHC:bnfp4nl)*

**Comment by milesap** [comment]
Any reason for merging this in the patch release?

**Comment by AleksueiR** [comment]
Instead of 2.1.0? This felt more like a bug to me than a feature (although then the PR is named incorrectly).

**Comment by milesap** [comment]
:+1: I was hoping to slap you with a muffin offence, there's been a muffin drought lately...

**Comment by AleksueiR** [comment]
ha-ha, fair enough. We should buy some muffins on Monday, to celebrate though.

**Pull request merged**
