### PR TITLE
Zoom to feature hover tooltip

### LINKED ISSUE #467: Implement Zoom to Feature tooltip for the icon

### PR DESCRIPTION
**Pull request by cynngah**
closes #467 

Added non-angular-magic tooltip to datatable zoom to feature

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/544)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/filters/filters-default.directive.js, line 90 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/544#-KGWtP-dCD8SVKTp0JOC:-KGWtP-dCD8SVKTp0JOD:-411898903) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e65c77e0f3db94905e2bc5e8a1f8cb32f63dceca/src/app/ui/filters/filters-default.directive.js#L90)):*
Have you tried using the `translate` directive here? Does it work? We need to display the tooltip in both languages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/544)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/544)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/544)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/ui/filters/filters-default.directive.js, line 90 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/544#-KGWtP-dCD8SVKTp0JOC:-KGXB7_f1g7X0QJbE6gz:-248250712) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e65c77e0f3db94905e2bc5e8a1f8cb32f63dceca/src/app/ui/filters/filters-default.directive.js#L90)):*
See #546.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/544)*

**Pull request merged**
