### PR TITLE
fix(ui): small medium layouts now based on $rootElement width

### LINKED ISSUE #1599: Small and medium layouts are not applied in all cases
They work correctly when the browser window is resized; however, optimized layout are not applied if the size of the map container itself is small. See screenshot (this is still `large` layout):

These layouts are applied using media queries and they won't fire if the browser window is itself remains unchanged. Need a way to force layout reflows based on the container size.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Media queries have been removed.

Closes #1599

## Testing
:eye: 

## Documentation
inline where needed

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1620)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620)*

**Comment by james-rae** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/layout/shell.directive.js, line 40 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620#-KbLSpy2upisByZkX_3m:-KbLSpy2upisByZkX_3n:b-upoxte) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/23217f8963e52dc0ded951d45e19c0ebd3c1045f/src/app/layout/shell.directive.js#L40)):*
> ```JavaScript
> 
>             // performance optimization - only update dom if the $rootElement width has changed
>             $(window).on('resize', () => $rootElement.width() !== elemWidth ? updateClass() : null);
> ```

This will set several listeners in case of several map instances. Not optimal. Please add a todo to optimize some moar :D

---

*[src/app/layout/shell.directive.js, line 81 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620#-KbLSdZwRSGh8JBajJI2:-KbLSdZwRSGh8JBajJI3:bh3y2ab) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/23217f8963e52dc0ded951d45e19c0ebd3c1045f/src/app/layout/shell.directive.js#L81)):*
> ```JavaScript
>             $rootElement
>                 .removeClass('rv-small rv-medium rv-large')
>                 .addClass('rv-' + layoutService.currentLayout($rootElement));
> ```

`currentLayout` function doesn't take arguments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620#-:-KbLTp9FzRcO17mCgEte:bnfp4nl)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/layout/shell.directive.js, line 40 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620#-KbLSpy2upisByZkX_3m:-KbLWBNyCkYYsWJ67Qf_:bjhlqej) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/23217f8963e52dc0ded951d45e19c0ebd3c1045f/src/app/layout/shell.directive.js#L40)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This will set several listeners in case of several map instances. Not optimal. Please add a todo to optimize some moar :D
</blockquote></details>

Made a note with `TODO`

---

*[src/app/layout/shell.directive.js, line 81 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620#-KbLSdZwRSGh8JBajJI2:-KbLWxmjiZhhLIlZ92uP:b-os95ir) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/23217f8963e52dc0ded951d45e19c0ebd3c1045f/src/app/layout/shell.directive.js#L81)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

`currentLayout` function doesn't take arguments.
</blockquote></details>

Ah good catch - fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.directive.js, line 40 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620#-KbLXQekMYC58sF6BspL:-KbLXQelrLphXJvBRlPR:b-oy4f9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2fc94edd8e3997ef28637ba29f4f4049c4350c0c/src/app/layout/shell.directive.js#L40)):*
> ```JavaScript
> 
>             // performance optimization - only update dom if the $rootElement width has changed
>             // TODO: to further improve performance only have one listener irregardless of the number of viewers on the page
> ```

Typo `irregardless`; should be `regardless`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620)*

**Comment by milesap** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/shell.directive.js, line 40 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620#-KbLXQekMYC58sF6BspL:-KbL_OkopYXhWXZUA1O1:b-t77xc3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2fc94edd8e3997ef28637ba29f4f4049c4350c0c/src/app/layout/shell.directive.js#L40)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Typo `irregardless`; should be `regardless`.
</blockquote></details>

agreed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1620)*

**Pull request merged**
