### PR TITLE
1169 do not include removed layers in bookmar when removal can be still undone

### LINKED ISSUE #1169: Removed layers re-appeared after clicking BackToCart
Tested build URL: http://fgpv.cloudapp.net/demo/v1.2.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

- Remove multiple layers, for example JOSM, Airports, CESI and Barley layers
image
- Click BackToCart, 
- At least one removed layer re-appeared, in below screenshot, Airports layer came back.
image

It seems every time there is different layer coming back after clicking BackToCart. Could try removing different combination of multiple layers, at least one layer will re-appear, and sometimes there might have two layers coming back.

### PR DESCRIPTION
**Pull request by AleksueiR**
Closes #1169 and #1206

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1218)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218)*

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218)*

**Comment by jolevesq** [comment]
When csv layer is huge, it would be great to have a loading indicator

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218#-:-KSHReMXYg5K1h_p4VMb:b-frphc2)*

**Comment by AleksueiR** [comment]
It would. Unfortunately, it's not possible right now as processing all that csv data block the ui thread. Any loading indicator will be frozen until the processing is done. A potential solution would be to use a web worker. Can you create an issue for that, so we don't forget?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218#-:-KSHRrO8YB8u-e1lDYaf:bj0gvlx)*

**Comment by james-rae** [comment]
Issue already exists I believe https://github.com/fgpv-vpgf/fgpv-vpgf/issues/964

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218#-:-KSHSNuqKLX-CS0WriKR:b-zgor3)*

**Comment by AleksueiR** [comment]
Perfect!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218#-:-KSHSbske4hZFT8CTAFk:b-qn5lbb)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/app/core/bookmark.service.js, line 47 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218#-KSHRKS7hBs9NIgUP7wT:-KSHRKS8rey2XEpfA9M9:b-fdyh2a) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3d95a252212c6e6b9dc3e6407c780aa8dff42a29/src/app/core/bookmark.service.js#L47)):*
> ```JavaScript
>             };
> 
>             // loop through layers in legend, remove user added layers and "removed" layer which are in the "undo" time fram
> ```

typo: frame

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/bookmark.service.js, line 47 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218#-KSHRKS7hBs9NIgUP7wT:-KSHVCQwRXjL9-qI4Ih7:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3d95a252212c6e6b9dc3e6407c780aa8dff42a29/src/app/core/bookmark.service.js#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: frame
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1218)*

**Pull request merged**
