### PR TITLE
feat(ui): implement custom map overview toggle functionality

### LINKED ISSUE #679: Update control and behaviour of the "hide/show" toggle overview map
The current esri control is ungainly, not keyboard accessible and [insert third bad thing here].

I would like to change it to something better, something following material design guidelines.

### PR DESCRIPTION
**Pull request by milesap**
Closes #679

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1108)

### CODE REVIEW

**Comment by cynngah** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108)*

**Comment by AleksueiR** [comment]
Please, implement the hide/show animation according to the mockup I posted in the issue.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/geo/overview-toggle.directive.js, line 31 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KPxGs3RRQyp8EP21Hf1:-KPxGs3RRQyp8EP21Hf2:b-f32k86) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/221250155122c8b2a39ddb7cf5ee6a457322effc/src/app/geo/overview-toggle.directive.js#L31)):*
> ```JavaScript
>             restrict: 'A',
>             /* jscs:disable maximumLineLength */
>             template: ` <div class="overview-toggle" style="position:absolute;top:12px;right:12px;">
> ```

No inline css please.

---

*[src/app/geo/overview-toggle.directive.js, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KPx_pYQ9rCW7DmxZpQV:-KPx_pYRZ0tzRtPm1clI:b-bqohlp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/221250155122c8b2a39ddb7cf5ee6a457322effc/src/app/geo/overview-toggle.directive.js#L32)):*
> ```JavaScript
>             /* jscs:disable maximumLineLength */
>             template: ` <div class="overview-toggle" style="position:absolute;top:12px;right:12px;">
>                             <md-button class="md-icon-button rv-button-24 md-button" tabindex="0" ng-click="toggleOverview()">
> ```

Needs `aria-label` with a description.

---

*[src/app/geo/overview-toggle.directive.js, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KPxHqHo1gNhdWi8Esuv:-KPxHqHo1gNhdWi8Esuw:b-94nzo7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/221250155122c8b2a39ddb7cf5ee6a457322effc/src/app/geo/overview-toggle.directive.js#L53)):*
> ```JavaScript
> 
>             // create an observer instance
>             var observer = new MutationObserver(() => {
> ```

Instead of using mutationobserver, replace esri overview toggle in `init-map` directive's link function and inject/compile the custom toggle once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KPxa2TtFvcGRIqTNLWF:b-fv5fk5)*

**Comment by milesap** [comment]
Changed animation/icon to match mockup

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/overview-toggle.directive.js, line 31 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KPxGs3RRQyp8EP21Hf1:-KQ1VhRpoaD6yUTwpOUQ:b-nkdvbw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/221250155122c8b2a39ddb7cf5ee6a457322effc/src/app/geo/overview-toggle.directive.js#L31)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> No inline css please.
</details>
Ok moved to _esri-map.scss

---

*[src/app/geo/overview-toggle.directive.js, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KPx_pYQ9rCW7DmxZpQV:-KQ1Vqa_AHMFIyhQELh4:brus7lh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/221250155122c8b2a39ddb7cf5ee6a457322effc/src/app/geo/overview-toggle.directive.js#L32)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Needs `aria-label` with a description.
</details>
Added aria-label

---

*[src/app/geo/overview-toggle.directive.js, line 53 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KPxHqHo1gNhdWi8Esuv:-KQ1Vwd9lIipGTQC9vni:b-mgydmv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/221250155122c8b2a39ddb7cf5ee6a457322effc/src/app/geo/overview-toggle.directive.js#L53)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of using mutationobserver, replace esri overview toggle in `init-map` directive's link function and inject/compile the custom toggle once.
</details>
As we discussed, moved injection to map.service.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQ1W82_O8ATlISgn3GP:b-v06uva)*

**Comment by AleksueiR** [comment]
Nice, just some tweaking left.

---

Reviewed 4 of 8 files at r2.
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/map.service.js, line 135 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1cfAA3Lt3_5NPtwAG:-KQ1cfAA3Lt3_5NPtwAH:b-a3ihnz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/app/geo/map.service.js#L135)):*
> ```JavaScript
> 
>                 service.mapManager.BasemapControl.basemapGallery.on('selection-change', () => {
>                     $rootElement.find('div.ovwContainer').after('<div rv-overview-toggle></div>');
> ```

Turn the directive into an element directive and put it inside `div.ovwContainer` - this will help with positioning (`right: 0, top: 0`).   Remove the `<div class="overview-toggle">` wrapper - it's not needed.
Set `margin: 0` and `display: block` on the toggle `button` element (also helps with positioning). 

---

*[src/app/geo/overview-toggle.directive.js, line 58 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1d_TNFFRWEqwLEmbN:-KQ1d_TNFFRWEqwLEmbO:bhd0c3w) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/app/geo/overview-toggle.directive.js#L58)):*
> ```JavaScript
> 
>             overviewAnimation
>                 .fromTo(el.prev(), 0.5, // expand/shrink overview map
> ```

Set duration to 0.3 seconds and add `new Ease(BezierEasing(0.35, 0, 0.25, 1));` easing.
Also, I don't think `from` part is needed: the starting size is specified in styles and should be 200px.

---

*[src/app/geo/overview-toggle.directive.js, line 61 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1m-qMMzmcJiM8w9Yy:-KQ1m-qNp3UpreuJUmYW:b-s06mlt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/app/geo/overview-toggle.directive.js#L61)):*
> ```JavaScript
>                     { width: 40, height: 40 },
>                     { width: 200, height: 200 }, 0)
>                 .to(el.find('md-icon').first(), 0.5, { // rotate toggle icon
> ```

Move the toggle button 3 pixel up and to the right in the collapsed state, so it doesn't stick out so much on to of the smaller container.

---

*[src/content/styles/modules/_esri-map.scss, line 43 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1eEAK44hdi0Bpd9nI:-KQ1eEAK44hdi0Bpd9nJ:bnp7e7w) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/content/styles/modules/_esri-map.scss#L43)):*
> ```SCSS
>         }
> 
>         md-icon {
> ```

Adding the `md-icon` rule under `rv-esri-map` is risky since it may affect all other icons added to this container. Better to make the `rv-overview-toggle` selector and put it there.

---

*[src/content/styles/modules/_esri-map.scss, line 45 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1lfuWpMGOwnIXKiin:-KQ1lfuWpMGOwnIXKiio:b-3pjg0c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/content/styles/modules/_esri-map.scss#L45)):*
> ```SCSS
>         md-icon {
>             transform: rotate(225deg);
>         }
> ```

Also cut the top-right corner from the overview map to show the icon more by using something like this:
```css
.ovwContainer:before {
    content: "";
    position: absolute;
    width: 0px;
    height: 0px;
    border-top: 35px solid rgba(250, 250, 250, 0.8);
    border-left: 35px solid transparent;
    z-index: 1;
    right: 0;
    top: 0;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQ1mYLdiQW_6KvHHVRd:b-y8g2id)*

**Comment by AleksueiR** [comment]
The overview map is offset on the initial load:
Now


Before


---

Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQ1wFOKqjfB-U70HHo2:b-rwpyvp)*

**Comment by milesap** [comment]
This issue has been resolved. It seems that in _esri.scss under `.esriOverviewMap .ovwContainer` the `width` and `height` properties had `!important`. Removing this was needed so the inline width/height would work, but this caused the offset issue. Instead I removed the `!important` and set max-width/height.

---

Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/geo/map.service.js, line 135 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1cfAA3Lt3_5NPtwAG:-KQ5_OW4Idy2N-irNDCg:bcxcw9h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/app/geo/map.service.js#L135)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Turn the directive into an element directive and put it inside `div.ovwContainer` - this will help with positioning (`right: 0, top: 0`).   Remove the `<div class="overview-toggle">` wrapper - it's not needed.
> Set `margin: 0` and `display: block` on the toggle `button` element (also helps with positioning). 
</details>
Ok changed

---

*[src/app/geo/overview-toggle.directive.js, line 58 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1d_TNFFRWEqwLEmbN:-KQ5_S44M86XTp3naWFu:bcke3an) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/app/geo/overview-toggle.directive.js#L58)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Set duration to 0.3 seconds and add `new Ease(BezierEasing(0.35, 0, 0.25, 1));` easing.
> Also, I don't think `from` part is needed: the starting size is specified in styles and should be 200px.
</details>
It was needed when `!important` on `.esriOverviewMap .ovwContainer` was removed however this was resolved with max-width/height (see above)

---

*[src/app/geo/overview-toggle.directive.js, line 61 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1m-qMMzmcJiM8w9Yy:-KQ5_lDjaxolnABtnXYH:b-9rj07w) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/app/geo/overview-toggle.directive.js#L61)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Move the toggle button 3 pixel up and to the right in the collapsed state, so it doesn't stick out so much on to of the smaller container.
</details>
Added to animation

---

*[src/content/styles/modules/_esri-map.scss, line 43 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1eEAK44hdi0Bpd9nI:-KQ5_ne0yaW7LtDuth-7:bcxcw9h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/content/styles/modules/_esri-map.scss#L43)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Adding the `md-icon` rule under `rv-esri-map` is risky since it may affect all other icons added to this container. Better to make the `rv-overview-toggle` selector and put it there.
</details>
Ok changed

---

*[src/content/styles/modules/_esri-map.scss, line 45 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1lfuWpMGOwnIXKiin:-KQ5_p4xKvAcnm21OEkO:b-fvt3yt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/content/styles/modules/_esri-map.scss#L45)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Also cut the top-right corner from the overview map to show the icon more by using something like this:
> ```css
> .ovwContainer:before {
>     content: "";
>     position: absolute;
>     width: 0px;
>     height: 0px;
>     border-top: 35px solid rgba(250, 250, 250, 0.8);
>     border-left: 35px solid transparent;
>     z-index: 1;
>     right: 0;
>     top: 0;
> }
> ```
</details>
Added, nice touch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQ5ZN8g8ChxwKp5Mv1s:bcfkir4)*

**Comment by cynngah** [comment]
Reviewed 4 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108)*

**Comment by AleksueiR** [comment]
Just one more tiny change : can you hide the extent box (`.ovwHighlight` selector) inside the overview map when it's collapsed?  

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/overview-toggle.directive.js, line 61 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1m-qMMzmcJiM8w9Yy:-KQ6bIeDJy9yuuqnIlH0:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/app/geo/overview-toggle.directive.js#L61)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Added to animation
</details>
:+1: 

---

*[src/content/styles/modules/_esri-map.scss, line 45 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQ1lfuWpMGOwnIXKiin:-KQ6_ePB3IFjqAAiKxXb:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a57fe50e5d42e8521c9db97c20a1b0c600f5b7d6/src/content/styles/modules/_esri-map.scss#L45)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Added, nice touch
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQ6a_3tLr0jweqC5mal:bii6sji)*

**Comment by milesap** [comment]
This does not seem like an easy fix. While the extent box can be hidden when shrinking the overview map, changing zoom levels will cause esri to display the box again. 

Another issue is that ESRI uses the overview box size to determine how to draw the overview map. So far I have been unable to trigger a redraw when the overview map size changes. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQLDklXoBbr2VlHIeYF:b-yfwehg)*

**Comment by jolevesq** [comment]
Everything works and looks great except one little bug. When the focus is on the arrow, if the overview is collapse and I pan zoom the map. When I reopen the overview map I have this:



The extent on the overview map is very small and does not represent the extent on the map. As soon as I pan or zoom with the overview map open, the extent reload properly and it is okay. If the keyboard focus is not on the overview map button there is no bug.

---

Reviewed 2 of 8 files at r2, 2 of 4 files at r3, 1 of 2 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/locales/translations.csv, line 14 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQMrJcwnrZB7p5HrtNw:-KQMrJcwnrZB7p5HrtNx:b-9aaq6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ca87341b34a260f941445d07a42cfbd5c193c032/src/locales/translations.csv#L14)):*
> ```CSV
> Appbar aria label for point info icon,appbar.aria.pointInfo,Point Information,Information de localisation
> Appbar aria label for menu  icon,appbar.aria.menu,Open Sidenav,Ouvrir menu de navigation
> Map overview aria label for toggle icon,geo.aria.overviewtoggle,Expand/Shrink map overview,Développer / Shrink aperçu de la carte
> ```

Translation can be better but it can be done later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQMsLbLClEUKj1zUQtB:b-ohchfv)*

**Comment by milesap** [comment]
I increased the `$timeout` delay so that the ESRI animation has more time to complete. It's working consistently for me now, however YMMV, let me know if it remains an issue.

---

Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/translations.csv, line 14 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQMrJcwnrZB7p5HrtNw:-KQQGore8-GnzHLIGNl8:b-xj8wmg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ca87341b34a260f941445d07a42cfbd5c193c032/src/locales/translations.csv#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Translation can be better but it can be done later.
</details>
Agreed, used Google Translate for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQQGx5Ay2cApwy0yrYw:bfmn6rq)*

**Comment by jolevesq** [comment]
:lgtm: 

---

Reviewed 3 of 4 files at r5.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQQRvCSvrD6s3-7UVhW:b593w57)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/overview-toggle.directive.js, line 70 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQQR_pSSnEy638sEzFZ:-KQQR_pT4xBCtyi-8z0Z:b-wucyzx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05282a4276c931aba91110a21146ea2c69b4b571/src/app/geo/overview-toggle.directive.js#L70)):*
> ```JavaScript
>             // default overview map to expanded state
>             if (typeof $rootScope.overviewActive === 'undefined') {
>                 $rootScope.overviewActive = true;
> ```

Not critical: `overviewActive` seems to be a local variable and doesn't need to be stored on the `$rootScope`.

---

*[src/app/geo/overview-toggle.directive.js, line 89 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQQS5Et7ttPQgA7zsfj:-KQQS5Eu_dtv2PCP4Lnm:b-k7b5iw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05282a4276c931aba91110a21146ea2c69b4b571/src/app/geo/overview-toggle.directive.js#L89)):*
> ```JavaScript
> 
>                 // $timeout workaround to prevent event collision with ESRI
>                 $timeout(() => overviewMapMap.setExtent(overviewMapMap.extent), 500);
> ```

Not critical: quickly closing and opening the overview map will call `setExtent` twice making the overview jump abruptly. This timeout can be cancelled if `animationCompleted` is called again before it's executed to prevent these jumps.


.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108)*

**Comment by milesap** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/overview-toggle.directive.js, line 70 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQQR_pSSnEy638sEzFZ:-KQQju8Z_UTNMWQYPTXL:bxx37qc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05282a4276c931aba91110a21146ea2c69b4b571/src/app/geo/overview-toggle.directive.js#L70)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Not critical: `overviewActive` seems to be a local variable and doesn't need to be stored on the `$rootScope`.
</details>
I placed it on `$rootScope` so that its state is maintained on projection changes (directive is destroyed and re-created).

---

*[src/app/geo/overview-toggle.directive.js, line 89 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQQS5Et7ttPQgA7zsfj:-KQQkMPOYZYJAmmD-wIM:btyza2z) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05282a4276c931aba91110a21146ea2c69b4b571/src/app/geo/overview-toggle.directive.js#L89)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Not critical: quickly closing and opening the overview map will call `setExtent` twice making the overview jump abruptly. This timeout can be cancelled if `animationCompleted` is called again before it's executed to prevent these jumps.
> 
> 
> .
</details>
Ok good idea, now any existing `$timeout` is canceled before another is started.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108)*

**Comment by AleksueiR** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/overview-toggle.directive.js, line 70 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQQR_pSSnEy638sEzFZ:-KQQkjDQHMo_Zs6H-j6E:b-vu0o2i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05282a4276c931aba91110a21146ea2c69b4b571/src/app/geo/overview-toggle.directive.js#L70)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> I placed it on `$rootScope` so that its state is maintained on projection changes (directive is destroyed and re-created).
</details>
Ok. Can you add this as a comment please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108)*

**Comment by milesap** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/overview-toggle.directive.js, line 70 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-KQQR_pSSnEy638sEzFZ:-KQQljfB1CdfgvBDR-9-:b-3dcmao) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/05282a4276c931aba91110a21146ea2c69b4b571/src/app/geo/overview-toggle.directive.js#L70)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Ok. Can you add this as a comment please?
</details>
Ok added comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1108#-:-KQQlv7P1lEzfXcYLKqp:bnfp4nl)*

**Pull request merged**
