### PR TITLE
feat(ui): Populate Datagrid for Group Layers

### LINKED ISSUE #505: featureIndex being hard coded to '0'
Feature index should reflect the actual index of the layer.

Currently in toc.service.js toggleLayerFiltersPanel function with a FIXME

### PR DESCRIPTION
**Pull request by AleksueiR**
Datatable can now be populated by the group layer attributes; however, it's breaking when trying to match symbology. See #522.

Relates #174 and closes #505.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/523)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 239 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523#-KFtq9MdZMSK1CtwEajn:-KFtq9MdZMSK1CtwEajo:-1206138731) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1e56a9a15f70c627d511a8e0a328f50751172df6/src/app/geo/layer-registry.service.js#L239)):*
typo: datatable

---

*[src/app/geo/legend-entry.service.js, line 133 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523#-KFtqjAGTlrYpwqINKgf:-KFtqjAHD5f-2p55zBWz:-1999255934) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1e56a9a15f70c627d511a8e0a328f50751172df6/src/app/geo/legend-entry.service.js#L133)):*
I think we have more than one of these strip trailing slash and get the feature index in our codebase.  We should move it as a utility into geoApi at some point.

---

*[src/app/geo/legend.service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523#-KFtqxohMCBtjVaeyHI4:-KFtqxohMCBtjVaeyHI5:-996685756) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1e56a9a15f70c627d511a8e0a328f50751172df6/src/app/geo/legend.service.js#L32)):*
typo: instance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523)*

**Comment by AleksueiR** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 239 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523#-KFtq9MdZMSK1CtwEajn:-KFtscd3rBp3bCdAqygs:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1e56a9a15f70c627d511a8e0a328f50751172df6/src/app/geo/layer-registry.service.js#L239)):*
Done.

---

*[src/app/geo/legend-entry.service.js, line 133 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523#-KFtqjAGTlrYpwqINKgf:-KFtsasJTsK9hil0eAOb:-450441212) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1e56a9a15f70c627d511a8e0a328f50751172df6/src/app/geo/legend-entry.service.js#L133)):*
Added a todo.

---

*[src/app/geo/legend.service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523#-KFtqxohMCBtjVaeyHI4:-KFtsd51MeFHank_pBLJ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1e56a9a15f70c627d511a8e0a328f50751172df6/src/app/geo/legend.service.js#L32)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523)*

**Comment by james-rae** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/523)*

**Pull request merged**
