### PR TITLE
fix(ui): "Enter" on waiting focus manager no longer triggers identify

### LINKED ISSUE #1191: Pressing "Enter" on the "keyboard focus" dialog immediately triggers identify and opens a details panel

### PR DESCRIPTION
**Pull request by milesap**
Closes #1191

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1197)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/focus.service.js, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197#-KS2HClTtZMJLRdDQZ0Y:-KS2HClTtZMJLRdDQZ0Z:b-uk1t9l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53737d5267a513417bc7ee62f68b14b04fb42c1c/src/app/layout/focus.service.js#L89)):*
> ```JavaScript
>          * @return {Boolean}    true iff focus manager is in a waiting state
>          */
>         function isWaiting() {
> ```

Maybe just expose focus manager's status and its possible states? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197)*

**Comment by milesap** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/layout/focus.service.js, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197#-KS2HClTtZMJLRdDQZ0Y:-KS2Q9_vd42Mr0eNxGSt:b-tft8z1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/53737d5267a513417bc7ee62f68b14b04fb42c1c/src/app/layout/focus.service.js#L89)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Maybe just expose focus manager's status and its possible states? 
</details>
Sure, makes sense for future use - made the change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197#-:-KS6pXQdOYCAdWP7EYvj:bnfp4nl)*

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1197)*

**Pull request merged**
