### PR TITLE
test(samples): layers sample page

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
## Description
Completes the `index-layers` component of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3472

### Checklist

- [x] works in IE11
- [x] works in Edge
- [ ] works with projection change
- [ ] works with language change
- [x] works via config file
- [ ] works via wizard
- [ ] works via API
- [ ] works via RCS
- [ ] works via bookmark load
- [ ] works in auto-legend
- [ ] works in structured legend
- [ ] works on layer reload
- [ ] datagrid works
- [ ] identify works

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated
- [ ] original issue has been reviewed & updated to reflect the PR content

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3487)

### CODE REVIEW

**Comment by RyanCoulsonCA** [comment]
> _[src/content/samples/new/config/config-sample-layers-01.json, line 92 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3487#-LewhjvO46o5JPJxEjTE:-LewhjvO46o5JPJxEjTF:bx1nygw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6c7eab0527797da74c0124f071c7c09395f64f3e/src/content/samples/new/config/config-sample-layers-01.json#L92)):_
> 
> > ```json
> >         "children": [
> >           {
> >             "layerId": "testLayer1"
> > ```
> 
> These tests are in a slightly different format than every other sample page, should be fine.

@yileifeng Yeah, I had to format this page slightly different due to the fact that structured legends don't allow you to delete layers (as far as I know), and I needed that for test 12. To solve this I had to an autopopulated legend instead, which doesn't allow me to use the same format as the other pages.

All of your other points should be fixed now, though.

**Comment by james-rae** [comment]
For `index-layers`

The word `disabled` appears to be used for invisible/transparent in some cases, and "locked" in others (config 01 mostly).  To me, disabled and locked are the same thing.  Maybe changed disabled to be "invisible" and "0% opacity" (or something else if you think it flows better), and always use disable or locked (choose one) for a control that cant be interacted with.


Config 03. Because the first test is large in the legend, suggest either collapsing it as default, or re-arrange "Test 2" to be "Test 1" if you want a consistent look amongst the configs.
Same with config 04 (maybe push test 5 to test 1)

Config 04, test 3, we are probably good with one mid-opacity test. We can drop two of them (so keep zero, full, and one of the inbetweens)

Config 04, test 4.  maybe just a note to the QA that seeing an image draw on the map means things are working. They won't be inspecting file types on the web traffic.

Config 04, test 2. minor rewording. "controls" makes me think of some kind of controlled layer config. Maybe something like "Test 2: Layers with Children" and change "Power Plants Proper Subset" to "Layer with 3 Children"

Config 04, test 1. minor rewording. "children split" gives me impression they all belong to the same layer (its actually same service loaded 3 times). Maybe "Test 1: Layer Groups" and we can drop one of the layers (two is good).

Config 05, can we default-collapse all the test groups in the legend?

**Comment by RyanCoulsonCA** [comment]
> > Reviewed 10 of 10 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3487)_ status: all files reviewed, 6 unresolved discussions (waiting on @dane-thomas, @RyanCoulsonCA, @ShrutiVellanki, and @yileifeng)
> 
> _[src/content/samples/new/config/config-sample-layers-01-options.json, line 1 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3487#-Lf051t878yunMmWjD0A:-Lf051t878yunMmWjD0B:b-wcumk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/030c7ce0a8f6c379baa7d4f585902504ef8a1961/src/content/samples/new/config/config-sample-layers-01-options.json#L1)):_
> 
> > ```json
> > {
> > ```
> 
> Can you change the config name to match the name in the selector. So `options` -> `controls` maybe
> 
> _[src/content/samples/new/config/config-sample-layers-03.json, line 102 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3487#-Lewm8kG0WIzIqO56Yep:-Lf07Ei_4y8vhCGoJrDN:b-9si0l7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6c7eab0527797da74c0124f071c7c09395f64f3e/src/content/samples/new/config/config-sample-layers-03.json#L102)):_

Done.

> Previously, yileifeng (Yi Lei Feng) wrote…
> Some clarification about what this actually does:
> 
> All 4 legend blocks correspond to the same layer so any change to one of them should apply to the rest. It was primarily used to test removing legend entries through the legend API.
> 
> Could possibly not need to be in this sample at all.

I've removed it entirely from the sample for now.

**Comment by RyanCoulsonCA** [comment]
> For `index-layers`
> 
> The word `disabled` appears to be used for invisible/transparent in some cases, and "locked" in others (config 01 mostly). To me, disabled and locked are the same thing. Maybe changed disabled to be "invisible" and "0% opacity" (or something else if you think it flows better), and always use disable or locked (choose one) for a control that cant be interacted with.
> 
> Config 03. Because the first test is large in the legend, suggest either collapsing it as default, or re-arrange "Test 2" to be "Test 1" if you want a consistent look amongst the configs.
> Same with config 04 (maybe push test 5 to test 1)
> 
> Config 04, test 3, we are probably good with one mid-opacity test. We can drop two of them (so keep zero, full, and one of the inbetweens)
> 
> Config 04, test 4. maybe just a note to the QA that seeing an image draw on the map means things are working. They won't be inspecting file types on the web traffic.
> 
> Config 04, test 2. minor rewording. "controls" makes me think of some kind of controlled layer config. Maybe something like "Test 2: Layers with Children" and change "Power Plants Proper Subset" to "Layer with 3 Children"
> 
> Config 04, test 1. minor rewording. "children split" gives me impression they all belong to the same layer (its actually same service loaded 3 times). Maybe "Test 1: Layer Groups" and we can drop one of the layers (two is good).
> 
> Config 05, can we default-collapse all the test groups in the legend?

These should be fixed.

**Pull request closed without merging**
