### PR TITLE
Squish Reverse Filter Errors

### PR DESCRIPTION
**Pull request by james-rae**
## Description
Bandaid solution to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1397

## Testing
Error no longer happens

## Documentation
None, thanks

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1446)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/reverse.filter.js, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1446#-KXkubg23f1pfHys5yCa:-KXkubg23f1pfHys5yCb:b-w2o14o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9157f3e28ed3a4c305cd62842ebb1d0f652ecbe2/src/app/ui/common/reverse.filter.js#L26)):*
> ```JavaScript
>                 return items.slice().reverse();
>             } else {
>                 return undefined;
> ```

Will returning an empty array be better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1446)*

**Comment by james-rae** [comment]
*[src/app/ui/common/reverse.filter.js, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1446#-KXkubg23f1pfHys5yCa:-KXkvNROKya-bVP6WTaG:banse2e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9157f3e28ed3a4c305cd62842ebb1d0f652ecbe2/src/app/ui/common/reverse.filter.js#L26)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Will returning an empty array be better?
</blockquote></details>

Your icon stack uses the result, so you tell me.  Does `undefined` in , `[]` out make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1446)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/reverse.filter.js, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1446#-KXkubg23f1pfHys5yCa:-KXkwT2eyZbEy4QSOFuq:b-pzkjyj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9157f3e28ed3a4c305cd62842ebb1d0f652ecbe2/src/app/ui/common/reverse.filter.js#L26)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Your icon stack uses the result, so you tell me.  Does `undefined` in , `[]` out make sense?
</blockquote></details>

It's used in a template binding, so it probably doesn't matter as it should implement their own checking. We can change it, if it breaks again. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1446)*

**Comment by AleksueiR** [comment]
:lgtm: Lazy solution approved. :+1: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1446#-:-KXl-8d_4shl0YzDG5bn:btgapar)*

**Pull request merged**
