### PR TITLE
Some UI tweaking

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/335)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/335)*

**Comment by alyec** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/panels/content-pane.directive.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/335#-KAkRULOrDpJi_dl9vFb:-KAkRULOrDpJi_dl9vFc:458308533) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96e236d8cc1a72f9be318eec075be0c96badf608/src/app/ui/panels/content-pane.directive.js#L99)):*
typo: floating

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/335)*

**Comment by AleksueiR** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/panels/content-pane.directive.js, line 99 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/335#-KAkRULOrDpJi_dl9vFb:-KAkS_1YZ6lXGX-X61v4:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/96e236d8cc1a72f9be318eec075be0c96badf608/src/app/ui/panels/content-pane.directive.js#L99)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/335)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/335)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/335)*

**Pull request merged**
