### PR TITLE
feat(ui): add simplistic help

### PR DESCRIPTION
**Pull request by AleksueiR**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/312)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/312)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/312)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/app/layout/shell.controller.js, line 20 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/312#-KAB_1TxhdbJcWVoYu09:-KAB_1TxhdbJcWVoYu0A:171360562) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9533b10ecca7174df6850ae294dc08d395b9845b/src/app/layout/shell.controller.js#L20)):*
This is horrible

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/312)*

**Pull request merged**
