### PR TITLE
feat(ui): close panel on escape

### PR DESCRIPTION
**Pull request by milesap**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/572)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/panels/content-pane.directive.js, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxQNUu7Txl4h32edMI:-KGxQNUu7Txl4h32edMJ:-2082998496) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L100)):*
In case no one has let you in on this yet; we're using Babel (https://babeljs.io/) for transpiling from ES6 -> ES5.
One thing this gives us is arrow functions:
event => {

---

*[src/app/ui/panels/content-pane.directive.js, line 102 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxQm6BR-gD7sVilPAf:-KGxQm6BR-gD7sVilPAg:596877117) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L102)):*
() => {

(different from above as only single parameter functions get to drop the () )

---

*[src/app/ui/panels/content-pane.directive.js, line 105 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxR-Fcf5sioqUQ2v4t:-KGxR-Fcf5sioqUQ2v4u:2090198298) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L105)):*
This can be const: you're not modifying the object directly, only its properties.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/panels/content-pane.directive.js, line 105 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxR-Fcf5sioqUQ2v4t:-KGyFDXvpd_Qi0UHMkrX:1903970882) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L105)):*
Also `Object.keys(state).forEach()` lets you simplify `for (x in state) if (state.hasOwnProperty(x)`.  In this case something like:
```js
Object.keys(stateManager.state).forEach(pName => stateManager.setActive({ [pName]: false }));
```
In the above `{ [pName]: false }` is an ES6 computed property assignment, and as Spencer noted we tend to use ES6 quite a bit (some of us more willingly than others).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/panels/content-pane.directive.js, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KH-gALbxStYqen3kKAT:-KH-gALbxStYqen3kKAU:807865653) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L100)):*
This event listener will fire several times as we have more than one `content-pane` instances. You can move this into the `shell` directive.

Also, adding a listener on `$document` will close all panels in all app instances (if there are more than one on the page). Have you tried listening on `$rootElement` instead? This should limit it to the currently focused app.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Comment by milesap** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/ui/panels/content-pane.directive.js, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxQNUu7Txl4h32edMI:-KH0EZ-3MrsveAIiuqvA:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L100)):*
done

---

*[src/app/ui/panels/content-pane.directive.js, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KH-gALbxStYqen3kKAT:-KH0EbAmuZCe6UxozZNw:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L100)):*
done

---

*[src/app/ui/panels/content-pane.directive.js, line 102 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxQm6BR-gD7sVilPAf:-KH0Ec-89fQWDxTtteEl:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L102)):*
done

---

*[src/app/ui/panels/content-pane.directive.js, line 105 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxR-Fcf5sioqUQ2v4t:-KH0EcsbA5_mLqS99vxN:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L105)):*
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Comment by mweech** [comment]
related to #106 & #119

**Comment by james-rae** [comment]
*[src/app/ui/panels/content-pane.directive.js, line 102 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxQm6BR-gD7sVilPAf:-KH5KhjlTtpixgfwE9sm:-1402076903) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L102)):*
extra comment for short-handed block

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Comment by james-rae** [comment]
*[src/app/ui/panels/content-pane.directive.js, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572#-KGxQNUu7Txl4h32edMI:-KH5KytVzhPVpj3X40TW:-1402076903) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/cbc3053855a3e048437e09de32c05bbac4c514a2/src/app/ui/panels/content-pane.directive.js#L100)):*
extra comment for short-handed block

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/572)*

**Pull request merged**
