### PR TITLE
feat(filters) add filtering capabilities to filters panel

### LINKED ISSUE #1922: Feat(filters): add filters to datatables
Take code from #1416, #1417, #1418, #1513, #1618, #1619 and #1711 (last one not merged yet)

We need to do this because those PR was on a branch that was not merge after the refactor. We need to manually do it.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1922

## Description

PR code from #1416, #1417, #1418, #1513, #1618, #1619 and #1711 (last was not merged). Those PR was on v2.0 but for refactor v2.0.0 was use instead so they get lost.

## Testing

Chrome, FF and Safari

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1944)

### CODE REVIEW

**Comment by james-rae** [comment]
That is a lot of work :trophy: 

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-:-Km7K20gbFA4P8nKM6_i:bvg0b5m)*

**Comment by milesap** [comment]
:lgtm: and WOMM :+1: 

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-:-Km7aucSLp_xDvy0SAEZ:b-yj14y2)*

**Comment by AleksueiR** [comment]
Nice work :1st_place_medal: 
Not sure why the demo wasn't built. I restarted the build.

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/ui/common/dragula.directive.js, line 43 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-KmBaBUqUmkv9Xdq_c24:-KmBaBUqUmkv9Xdq_c25:b-shq48d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1cec10c93b7144db367480e727426365edd7f8b/src/app/ui/common/dragula.directive.js#L43)):*
> ```JavaScript
> 
>         // extend default rvDrag functions so if they are not include in rvDragulaOptions it will not fail
>         const dragOptions = { rvDragCancel: () => { }, rvDragDrop: () => { }, rvDragStart: () => { },
> ```

Are these drag option defaults? If so, you can just add them directly to the `dragulaOptions` above:
```js
const dragulaOptions = {
            containers: [el[0]],
            mirrorContainer: el[0],
            
            rvDragCancel: () => {}, 
            rvDragDrop: () => {},
            ....
        };
```

---

*[src/app/ui/filters/filters-default-menu.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-KmBafW8feMdr66DpphS:-KmBafW8feMdr66DpphT:b-r83et4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1cec10c93b7144db367480e727426365edd7f8b/src/app/ui/filters/filters-default-menu.directive.js#L54)):*
> ```JavaScript
> 
>     function showFilters() {
>         $rootScope.isFiltersVisible = self.filter.isOpen;
> ```

Please, try not to store stuff on `$rootScope` as there is way to properly document what is stored there.
You can store the `isFiltersVisible` variable in the `layoutService`. This looks like a great fit.

---

*[src/app/ui/filters/filters-default.directive.js, line 597 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-KmBbM3D0yaQj-agCOn0:-KmBbM3D0yaQj-agCOn1:b-lutok2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1cec10c93b7144db367480e727426365edd7f8b/src/app/ui/filters/filters-default.directive.js#L597)):*
> ```JavaScript
> 
>                     // fired event to create filters
>                     $rootScope.$broadcast(events.rvTableReady);
> ```

There is a [shortcut for `$rootScope`](https://github.com/AleksueiR/fgpv-vpgf/blob/bookmark-v2/src/app/core/constant.service.js#L32) in `events` service; if you just need the `$rootScope` for broadcasting or listening, you can use 
```js
events.$broadcast(events.rvTableReady);

or

events.$on(events.rvTableReady);
```

Cuts down one extra dependency.

---

*[src/app/ui/toc/templates/legend-control-switch.html, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-KmBcplXWaLGPMl8SI7x:-KmBcplXWaLGPMl8SI7y:bm1iqqr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1cec10c93b7144db367480e727426365edd7f8b/src/app/ui/toc/templates/legend-control-switch.html#L2)):*
> ```HTML
> <md-switch
>     aria-label="{{ self.uiControl.label  | translate }}"
> ```

Good catch :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-:-KmBdv2M1yc9MUnBiAwD:b-rf5blf)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/common/dragula.directive.js, line 43 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-KmBaBUqUmkv9Xdq_c24:-KmCFtZpswFpAysBxAMZ:ba62775) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1cec10c93b7144db367480e727426365edd7f8b/src/app/ui/common/dragula.directive.js#L43)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Are these drag option defaults? If so, you can just add them directly to the `dragulaOptions` above:
```js
const dragulaOptions = {
            containers: [el[0]],
            mirrorContainer: el[0],
            
            rvDragCancel: () => {}, 
            rvDragDrop: () => {},
            ....
        };
```
</blockquote></details>

Oups, haven't seen it was define above

Done!

---

*[src/app/ui/filters/filters-default-menu.directive.js, line 54 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-KmBafW8feMdr66DpphS:-KmCSPIlImlPHU5JjZVc:blqp9e1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1cec10c93b7144db367480e727426365edd7f8b/src/app/ui/filters/filters-default-menu.directive.js#L54)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, try not to store stuff on `$rootScope` as there is way to properly document what is stored there.
You can store the `isFiltersVisible` variable in the `layoutService`. This looks like a great fit.
</blockquote></details>

Did it but the scope for the filter is made in filters-definition-directive from a new scope for each filter. When I put a watch on modification for layoutService.isFilterVisible, it is fired the same amount of time as the number of filters. The other problem is the self from the controller is not the same as the self from the link function. I use to use $root in the template to get access to the value. Now I will put my variable inside the new scope for each filter.

---

*[src/app/ui/filters/filters-default.directive.js, line 597 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-KmBbM3D0yaQj-agCOn0:-KmCGE2Vp2la75lOChb6:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c1cec10c93b7144db367480e727426365edd7f8b/src/app/ui/filters/filters-default.directive.js#L597)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

There is a [shortcut for `$rootScope`](https://github.com/AleksueiR/fgpv-vpgf/blob/bookmark-v2/src/app/core/constant.service.js#L32) in `events` service; if you just need the `$rootScope` for broadcasting or listening, you can use 
```js
events.$broadcast(events.rvTableReady);

or

events.$on(events.rvTableReady);
```

Cuts down one extra dependency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944)*

**Comment by AleksueiR** [comment]
`npm-debug.log` can be removed :D

---

Reviewed 6 of 7 files at r2.
Review status: 32 of 33 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944#-:-KmQycZNv5bKUrcQAmMq:b-vhztit)*

**Comment by james-rae** [comment]
Reviewed 1 of 31 files at r1, 6 of 7 files at r2.
Review status: 32 of 33 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944)*

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r3.
Review status: 31 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r3, 1 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1944)*

**Pull request merged**
