### PR TITLE
Fix map export in IE

### LINKED ISSUE #2060: IE 11 - Map Export never finish loading
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html

- Click Export on left side menu
It couldn't finish loading the exported map, thus map points were not appearing on the map.

image

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Close #2060 fix map export in IE by adding a poly fill module for `outerHtml`.

## Testing

Manually
## Documentation

none
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2165)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/polyfill/ie-outer.HTML.js, line 95 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-Kow5vZDETygiCAgxl4M:-Kow5vZDETygiCAgxl4N:bfukxct) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a830ad554ec3b355983ac0f4024fe158721853e8/src/polyfill/ie-outer.HTML.js#L95)):*
> ```JavaScript
> // defer patching until the SVGjs library is loaded; function in `_deferredPolyfills` will be executed by the bootstrap
> window.RV = window.RV ? window.RV : {};
> window.RV._deferredPolyfills = window.RV._deferredPolyfills ? window.RV._deferredPolyfills : [];
> ```

Looks like `_deferredPolyfills` is no longer used in the bootstrap. I'm not sure how this `SVG.extend(SVG.Element, { svg: newSvg })` is executed now and `serializeSvgContent` is called at all. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by barryytm** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/polyfill/ie-outer.HTML.js, line 95 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-Kow5vZDETygiCAgxl4M:-Kow7odikDXpOwGvcj1f:b59f35l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a830ad554ec3b355983ac0f4024fe158721853e8/src/polyfill/ie-outer.HTML.js#L95)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Looks like `_deferredPolyfills` is no longer used in the bootstrap. I'm not sure how this `SVG.extend(SVG.Element, { svg: newSvg })` is executed now and `serializeSvgContent` is called at all. 
</blockquote></details>

1. So https://github.com/barryytm/fgpv-vpgf/blob/2060-map-export-not-loading-IE/src/app/bootstrap.js#L29 is not being used?  

2. I don't think `newSvg` is being used at all and I tried to delete it, it didn't seem to cause any erros so it is save to delete it I guess? 
 
3. `serializeSvgContent` is being called when https://github.com/barryytm/fgpv-vpgf/blob/2060-map-export-not-loading-IE/src/app/ui/export/export-legend.service.js#L108 and https://github.com/barryytm/fgpv-vpgf/blob/2060-map-export-not-loading-IE/src/polyfill/ie-outer.HTML.js#L55 are called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by AleksueiR** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/polyfill/ie-outer.HTML.js, line 95 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-Kow5vZDETygiCAgxl4M:-KowOC8qbD2mJJO5zEN0:b-eh0yx5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a830ad554ec3b355983ac0f4024fe158721853e8/src/polyfill/ie-outer.HTML.js#L95)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

1. So https://github.com/barryytm/fgpv-vpgf/blob/2060-map-export-not-loading-IE/src/app/bootstrap.js#L29 is not being used?  

2. I don't think `newSvg` is being used at all and I tried to delete it, it didn't seem to cause any erros so it is save to delete it I guess? 
 
3. `serializeSvgContent` is being called when https://github.com/barryytm/fgpv-vpgf/blob/2060-map-export-not-loading-IE/src/app/ui/export/export-legend.service.js#L108 and https://github.com/barryytm/fgpv-vpgf/blob/2060-map-export-not-loading-IE/src/polyfill/ie-outer.HTML.js#L55 are called.
</blockquote></details>

1. Correct. At least I couldn't find a place where `_deferredPolyfills` is called.
2. `newSvg` overrides default CVG constructor here: https://github.com/svgdotjs/svg.js/blob/c482c602500494c8f30357284fd873046296ab65/src/element.js#L210 It's only invoked when a new SVG element is made. This was definitely used, otherwise I wouldn't have bothered overriding it. :) I would preferred to still have it. Can you try just running `SVG.extend(SVG.Element, { svg: newSvg })` here and see if it fails?
3. :heavy_check_mark: It makes sense now why it's called there. Thanks for checking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/polyfill/ie-outer.HTML.js, line 95 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-Kow5vZDETygiCAgxl4M:-KowVfIpOGDJ8H7riUk-:bui31d1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a830ad554ec3b355983ac0f4024fe158721853e8/src/polyfill/ie-outer.HTML.js#L95)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

1. Correct. At least I couldn't find a place where `_deferredPolyfills` is called.
2. `newSvg` overrides default CVG constructor here: https://github.com/svgdotjs/svg.js/blob/c482c602500494c8f30357284fd873046296ab65/src/element.js#L210 It's only invoked when a new SVG element is made. This was definitely used, otherwise I wouldn't have bothered overriding it. :) I would preferred to still have it. Can you try just running `SVG.extend(SVG.Element, { svg: newSvg })` here and see if it fails?
3. :heavy_check_mark: It makes sense now why it's called there. Thanks for checking.
</blockquote></details>

`SVG` should be undefined tho.  I just tried to run `SVG.extend(SVG.Element, { svg: newSvg })` in `ie-outer.HTML.js` and an error popped up saying `SVG` was undefined.  Does it require an import or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/polyfill/ie-outer.HTML.js, line 95 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-Kow5vZDETygiCAgxl4M:-Kowh7zVQLAvhiLKmj6O:b-pz0sus) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a830ad554ec3b355983ac0f4024fe158721853e8/src/polyfill/ie-outer.HTML.js#L95)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

`SVG` should be undefined tho.  I just tried to run `SVG.extend(SVG.Element, { svg: newSvg })` in `ie-outer.HTML.js` and an error popped up saying `SVG` was undefined.  Does it require an import or something?
</blockquote></details>

Ah, SVG is being loaded through geoApi, this code is running to early. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/polyfill/ie-outer.HTML.js, line 95 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-Kow5vZDETygiCAgxl4M:-Kp1SuBgamN2F3RwLBzs:bdq78hw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a830ad554ec3b355983ac0f4024fe158721853e8/src/polyfill/ie-outer.HTML.js#L95)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Ah, SVG is being loaded through geoApi, this code is running to early. :(
</blockquote></details>

Ok, turns out this is simple - need to import geoapi in bootstrap and then you can execute deferred polyfills. Will show you on Monday.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/polyfill/ie-outer.HTML.js, line 95 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-Kow5vZDETygiCAgxl4M:-KpFTInZAp4ZChmm6mIv:b-6w6g8m) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a830ad554ec3b355983ac0f4024fe158721853e8/src/polyfill/ie-outer.HTML.js#L95)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Ok, turns out this is simple - need to import geoapi in bootstrap and then you can execute deferred polyfills. Will show you on Monday.
</blockquote></details>

https://github.com/AleksueiR/fgpv-vpgf/commit/6a23450cfbb5d9cad7f4072891361639a7dc496a

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by james-rae** [comment]
*[src/app/bootstrap.js, line 4 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-KpGBZqrOQErPbovjlEy:-KpGBZqsMJmuMW2y4g5h:b-5ntm03) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/138f1b38982c5bd0d96c5dff4865df03e4cbcee1/src/app/bootstrap.js#L4)):*
> ```JavaScript
> // eslint-disable-next-line max-statements
> 
> import geoapi from 'geoApi';
> ```

Curious why this line?  I don't see it being used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by james-rae** [comment]
*[src/app/bootstrap.js, line 4 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-KpGBZqrOQErPbovjlEy:-KpGBjuT5GFtHZ8Mvu0m:b-7xorhc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/138f1b38982c5bd0d96c5dff4865df03e4cbcee1/src/app/bootstrap.js#L4)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Curious why this line?  I don't see it being used
</blockquote></details>

Does geoApi load SVG?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/bootstrap.js, line 4 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165#-KpGBZqrOQErPbovjlEy:-KpGCDJY0bVV-u-58LsK:bji2yx0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/138f1b38982c5bd0d96c5dff4865df03e4cbcee1/src/app/bootstrap.js#L4)):*
Yeah, it does.

> Ah, SVG is being loaded through geoApi, this code is running to early. :(

by Alex

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2165)*

**Pull request merged**
