### PR TITLE
fix(datatable): change focus link to allow proper tabbing

### LINKED ISSUE #1636: Grid tab order gets stuck with small grid
To reproduce:

* Open `index-fgp-en.html` with no layers
* Load `happy.json`, which has 3 features
* Open the grid
* Get focus into the grid
* Mash tab key
* Eventually the focus will just go back and forth between the Close Button `X` and the Menu Button `Vertical Ellipsis`

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #1636 - focus link is set between legend block button and first focusable element in table
Also cleaned up some console warnings

## Testing
Visually tested

## Documentation
None

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2343)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/full-screen.service.js, line 196 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343#-KsdhQredDjCjj7PhNLY:-KsdhQredDjCjj7PhNLZ:b-3qca21) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fd04fbedda875a308903df687e5ff595f27d715/src/app/ui/common/full-screen.service.js#L196)):*
> ```JavaScript
>         const originalPanDuration = map.mapDefault('panDuration');
>         map.mapDefault('panDuration', 0);
>         // TODO: fix after geoapi allows this through
> ```

Can you remove this comment, since you've done what it says :D

---

*[src/app/ui/toc/toc.html, line 43 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343#-Ksdhmlq055zIrzEWQGo:-Ksdhmlq055zIrzEWQGp:b-nrjtbv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fd04fbedda875a308903df687e5ff595f27d715/src/app/ui/toc/toc.html#L43)):*
> ```HTML
>                 class="rv-toggle-slide"
>                 data-sort-group="{{ ::block.sortGroup }}"
>                 data-legend-id="{{ block.id }}">
> ```

Can you name it `legend-block-id` for consistency please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343)*

**Comment by james-rae** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343)*

**Comment by JahidAhmed** [comment]
Review status: 22 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/common/full-screen.service.js, line 196 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343#-KsdhQredDjCjj7PhNLY:-KsdtnQZZ6Ui93SKolMp:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fd04fbedda875a308903df687e5ff595f27d715/src/app/ui/common/full-screen.service.js#L196)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you remove this comment, since you've done what it says :D
</blockquote></details>

Done, thanks

---

*[src/app/ui/toc/toc.html, line 43 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343#-Ksdhmlq055zIrzEWQGo:-KsdtoWql8lbmtjhVZbI:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8fd04fbedda875a308903df687e5ff595f27d715/src/app/ui/toc/toc.html#L43)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you name it `legend-block-id` for consistency please?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343)*

**Comment by AleksueiR** [comment]
:lgtm: Nice, at least datatable tabbing doesn't :poop: out .

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2343#-:-Kshxhp0f3hjxFboHnDP:b73pnmt)*

**Pull request merged**
