### PR TITLE
Fix warnings from aria-label

### PR DESCRIPTION
**Pull request by barryytm**
## Description

#1700 
Fix the warnings from aria-label

## Testing

No, it is on console

## Documentation

NA
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1912)

### CODE REVIEW

**Comment by milesap** [comment]
Please use translations found in `src/locales` along with the `translate` filter.

Example: `'my.custom.translation' | translate`

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912#-:-KlKGWuDIQZFc8Z5YEDH:b-lvjvsp)*

**Comment by AleksueiR** [comment]
And don't forget the `{{ }}`.
```html
<md-button
        aria-label="{{ appbar.aria.menu | translate }}" >
        ....
        
    </md-button>
```

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912#-:-KlKHVDBIHymhThk_Yv9:bb79zo3)*

**Comment by milesap** [comment]
I still see some warnings on my console:



---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912#-:-KlOiwAhKWxUTzbbbNOl:b-mpr72)*

**Comment by AleksueiR** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/templates/legend-group.html, line 10 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912#-KlOvW8DwywIJ6UFkB7Q:-KlOvW8DwywIJ6UFkB7R:boghovp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6c347c7df2ee500bcce36ecfa8a163eaf81deebb/src/app/ui/toc/templates/legend-group.html#L10)):*
> ```HTML
>         class="rv-body-button rv-button-square"
>         ng-click="self.block.expanded = !self.block.expanded"
>         aria-label="{{ toc.layer.label.symbology | translate }}">
> ```

This is expands the group's content, not legend. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912)*

**Comment by barryytm** [comment]
Should I use toc.menu.expand.title?  Or any other labels?

**Comment by milesap** [comment]
No more warnings :+1: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912#-:-KlTymP_0iR4OygkvalF:bn93hf2)*

**Comment by barryytm** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/templates/legend-group.html, line 10 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912#-KlOvW8DwywIJ6UFkB7Q:-KlUlhOjOBfAIuYbSFc2:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6c347c7df2ee500bcce36ecfa8a163eaf81deebb/src/app/ui/toc/templates/legend-group.html#L10)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This is expands the group's content, not legend. 
</blockquote></details>

Done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912)*

**Comment by AleksueiR** [comment]
:lgtm:

Can you make a new Github issue to add missing quotes to `aria-label` attribute translation strings? There seems to be lots of them.

---

Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1912#-:-KlUmBtO9_Dr30Ymh0Px:bnuxffr)*

**Pull request merged**
