### PR TITLE
Adds file-based layer import (with caveats)

### PR DESCRIPTION
**Pull request by AleksueiR**
In support of #611

Note:
 - errors (like mismatch between detected and user selected file type) are not handled; no error messages (except valid url and required fields)
 - symbology is not displayed in datatable
 - cannot add "conver.json" sample data with the strange error of "_core.js:49391 Uncaught (in promise) Error: Projection: urn:ogc:def:crs:EPSG::3978 could not be found in proj4.defs(…)_" (succeeds when trying to add a second time, what?)
 - does not compute smart defaults
 - no colour picker yet
 - not possible to import non-local files due to proxy issues (cannot test if create layer from non-local files actually works correctly right now)

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/707)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 26 of 39 files at r1.
Review status: 24 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/loader/loader-menu.html, line 10 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJHuJ8wDmuHEB-Nbtsl:-KJHuJ8wDmuHEB-Nbtsm:1263728780) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/loader/loader-menu.html#L10)):*
> ```HTML
>         ng-click="$mdOpenMenu($event)"
>         ng-class="{ selected: self.state.mainLoaderFile.active || self.state.mainLoaderService.active }">
>         <md-tooltip>Import Layers</md-tooltip>
> ```

translation

---

*[src/content/styles/modules/_file-drop.scss, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJHvrA0m8e6OhSQD8FS:-KJHvrA0m8e6OhSQD8FT:160418165) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/content/styles/modules/_file-drop.scss#L29)):*
> ```SCSS
>                 height: rem(5);
>                 width: rem(5);
>                 margin-top: 18px;
> ```

rem

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 39 files at r1.
Review status: 28 of 36 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707)*

**Comment by alyec** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 177 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLDMA2XUZO2BZ99ZMl:-KJLDMA2XUZO2BZ99ZMm:1768194880) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/layer-blueprint.class.js#L177)):*
> ```JavaScript
>         // jscs:disable requireSpacesInAnonymousFunctionExpression
>         /**
>          * Createa a LayerFileBlueprint.
> ```

typo `Create a`
Also, I think this belongs on the constructor, not the class

---

*[src/app/geo/layer-blueprint.class.js, line 183 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLDAfmBdldchU258G5:-KJLDAfmBdldchU258G6:-1091401004) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/layer-blueprint.class.js#L183)):*
> ```JavaScript
>          * @param  {String} path      either file name or file url; if it's a file name, need to provide a HTML5 file object
>          * @param  {File} file      optional: HTML5 file object
>          * @return {String}           service type: 'csv', 'shapefile', 'geojosn'
> ```

typo `'geojson'`

---

*[src/app/geo/layer-blueprint.class.js, line 235 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLEH2Cl4FfuTu6sMrR:-KJLEH2Cl4FfuTu6sMrS:1403215563) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/layer-blueprint.class.js#L235)):*
> ```JavaScript
>                 this._fileType = value;
> 
>                 // create user options object basedo the layer type
> ```

typo `based on`

---

*[src/app/geo/legend-entry.service.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLFKLh2u0oDnA54bGN:-KJLFKLh2u0oDnA54bGO:-936471430) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/legend-entry.service.js#L153)):*
> ```JavaScript
> 
>             // FIXME: this should be done only on feature layers, nothing else!
>             // HACK: to get file based layers working; this will be solved by the layer record ana legend entry hierarchy
> ```

typo: `and`

---

*[src/app/ui/common/stepper/stepper.class.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGDoZOS_ok2XgRZ6k:-KJLGDo_xl3DnKLu0m9E:-685790375) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L15)):*
> ```JavaScript
>          * Start stepper by activating the specified step.
>          * @param  {Number} stepNumber id of the step to activate, defaults to 0
>          * @return {Object}            itthis for chaining
> ```

typo `this`

---

*[src/app/ui/common/stepper/stepper.class.js, line 65 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGFydaQ8QbmkmTwqI:-KJLGFydaQ8QbmkmTwqJ:-685790375) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L65)):*
> ```JavaScript
>          * @param  {Boolean} completeCurrentStep       flag indicating if the current step should be completed
>          * @param  {Boolean} completeIntermediateSteps  flag indicating if the steps in between should be completed
>          * @return {Object}            itthis for chaining
> ```

typo `this`

---

*[src/app/ui/common/stepper/stepper.class.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGc8FOfi_dNLNzczT:-KJLGc8FOfi_dNLNzczU:-685790375) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L101)):*
> ```JavaScript
>          * Moves to the next step.
>          * @param  {Boolean} completeCurrentStep       flag indicating if the current step should be completed
>          * @return {Object}            itthis for chaining
> ```

typo `this`

---

*[src/app/ui/common/stepper/stepper.class.js, line 124 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGlHauX-PoZe-O4Zc:-KJLGlHauX-PoZe-O4Zd:-685790375) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L124)):*
> ```JavaScript
>          * Moves to the previous step.
>          * @param  {Boolean} completeCurrentStep       flag indicating if the current step should be completed
>          * @return {Object}            itthis for chaining
> ```

typo `this`

---

*[src/app/ui/loader/loader-service.directive.js, line 31 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLIyqnRJQj2yoqRMFL:-KJLIyqnRJQj2yoqRMFM:1771287758) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/loader/loader-service.directive.js#L31)):*
> ```JavaScript
>     }
> 
>     function Controller($timeout, stateManager, Stepper) {
> ```

several translations need to be set instead of hardcoded strings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707)*

**Comment by AleksueiR** [comment]
Review status: 29 of 37 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/app/geo/layer-blueprint.class.js, line 177 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLDMA2XUZO2BZ99ZMl:-KJLLdlSsDzOu6IiL2x8:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/layer-blueprint.class.js#L177)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `Create a`
> Also, I think this belongs on the constructor, not the class
</details>
Done.

---

*[src/app/geo/layer-blueprint.class.js, line 183 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLDAfmBdldchU258G5:-KJLLdWl5_Pgjzcp1q-9:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/layer-blueprint.class.js#L183)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `'geojson'`
</details>
Done.

---

*[src/app/geo/layer-blueprint.class.js, line 235 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLEH2Cl4FfuTu6sMrR:-KJLLd4a1bWCZKTu3f7B:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/layer-blueprint.class.js#L235)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `based on`
</details>
Done.

---

*[src/app/geo/legend-entry.service.js, line 153 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLFKLh2u0oDnA54bGN:-KJLLc_YwelowkY3AMxo:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/geo/legend-entry.service.js#L153)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: `and`
</details>
Done.

---

*[src/app/ui/common/stepper/stepper.class.js, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGDoZOS_ok2XgRZ6k:-KJLLc4PE5ffy6JLD4z7:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L15)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `this`
</details>
Done.

---

*[src/app/ui/common/stepper/stepper.class.js, line 65 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGFydaQ8QbmkmTwqI:-KJLLbbRx0WolN_1M-ox:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L65)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `this`
</details>
Done.

---

*[src/app/ui/common/stepper/stepper.class.js, line 101 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGc8FOfi_dNLNzczT:-KJLLbGn4ZmgSBwMCMuw:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L101)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `this`
</details>
Done.

---

*[src/app/ui/common/stepper/stepper.class.js, line 124 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLGlHauX-PoZe-O4Zc:-KJLLaIK8MYYLROiGvad:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/common/stepper/stepper.class.js#L124)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `this`
</details>
Done.

---

*[src/app/ui/loader/loader-menu.html, line 10 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJHuJ8wDmuHEB-Nbtsl:-KJLL_mZhNNIrMoto3k6:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/loader/loader-menu.html#L10)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> translation
</details>
Done.

---

*[src/app/ui/loader/loader-service.directive.js, line 31 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJLIyqnRJQj2yoqRMFL:-KJLLMvAFw5xylc-5fFG:1717558222) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/app/ui/loader/loader-service.directive.js#L31)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> several translations need to be set instead of hardcoded strings
</details>
This will be done in PR for #612.

---

*[src/content/styles/modules/_file-drop.scss, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJHvrA0m8e6OhSQD8FS:-KJLLZerMlOtKkbDUlur:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b3ad884310e538722288a9137c9f86d46129f34c/src/content/styles/modules/_file-drop.scss#L29)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary>
> rem
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/loader/loader-file.directive.js, line 173 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707#-KJMUTX3GINYqCrc6VsJ:-KJMUTX3GINYqCrc6VsK:-1399875053) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d76cdabcea6347cb3b645a8c334f7fea518ffa11/src/app/ui/loader/loader-file.directive.js#L173)):*
> ```JavaScript
>                 self.upload.file = file; // store the first file from the array;
> 
>                 $timeout(() => onLayerBlueprintReady(file.name, file.file), 300);
> ```

`file.file` :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/707)*

**Pull request merged**
