### PR TITLE
Feature/smallkey

### PR DESCRIPTION
**Pull request by james-rae**
Timeout version of smallkey passing in FGP webpages.  To be used as a basis to test the proper fix.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/516)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/index-fgp-en.html, line 180 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516#-KFpkOmStkxZhE_LsRgi:-KFpkOmStkxZhE_LsRgj:1533890362) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/18519a82b715b1c9705890fc71bf60200f807103/src/index-fgp-en.html#L180)):*
IE 11 will throw a fit on arrow functions: https://kangax.github.io/compat-table/es6/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index-fgp-en.html, line 180 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516#-KFpkOmStkxZhE_LsRgi:-KFtE4gQi-VHhBX3idZC:-660267717) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/18519a82b715b1c9705890fc71bf60200f807103/src/index-fgp-en.html#L180)):*
lol, i was so careful with `queryStringToJSON` and then missed this one.  good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/516)*

**Pull request merged**
