### PR TITLE
full extent

### PR DESCRIPTION
**Pull request by ec-dev**
full extent with re-projection; when config settings has different spatial reference than the loaded map

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/299)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.service.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1FE9d5Hspl5OaOHtg:-KA1FE9earcs7i8xCDRl:1799967185) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/app/geo/geo.service.js#L43)):*
VAARRRRRRRRRRRRRR

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 307 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1G-l0HsY7F1e9_246:-KA1G-l1Vtzw_T0aVZ3f:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/app/geo/geo.service.js#L307)):*
const

---

*[src/configDemo.json, line 254 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1GXwQvwEEpfCuoA-s:-KA1GXwQvwEEpfCuoA-t:2134193634) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/configDemo.json#L254)):*
we should start using the proper config format if possible

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/configDemo.json, line 254 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1GXwQvwEEpfCuoA-s:-KA1H-RnNQ3FmMcXA1G2:2065604309) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/configDemo.json#L254)):*
where is the proper config stored? I see the mapSettings is built from config which is read from configDemo.json. Is there an existing config that's already working where I can just adding to it (config.en.json?)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/configDemo.json, line 254 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1GXwQvwEEpfCuoA-s:-KA1ZVGOFU3F54ee819I:1481407231) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/configDemo.json#L254)):*
created a new issue #301 to update configDemo.json and update geo service code that uses old config style

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by ec-dev** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1FE9d5Hspl5OaOHtg:-KA1_G_Px9eziWWup-gL:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/app/geo/geo.service.js#L43)):*
Done.

---

*[src/app/geo/geo.service.js, line 307 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1G-l0HsY7F1e9_246:-KA1_FpskdF03zexH8oX:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/app/geo/geo.service.js#L307)):*
Done.

---

*[src/configDemo.json, line 254 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1GXwQvwEEpfCuoA-s:-KA1_L28wDA7jzynlyE4:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/configDemo.json#L254)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/geo.service.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299#-KA1FE9d5Hspl5OaOHtg:-KA6_2KV9Lub_9i2Ah1g:-1813386401) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7d4df1b619e4e21a403c18bf1826df8259edd11e/src/app/geo/geo.service.js#L43)):*
@james-rae , you need to approve this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/299)*

**Pull request merged**
