### PR TITLE
feat(basemap): Set opacity on layer of array of layers

### LINKED ISSUE #2463: Add opacity value for basemap layers
From the schema, we should be able to set opacity for basemap because they are layers type node. This is especially useful when we want to combine more then 1 layers for a basemap (e.g. CBMT and the Hillshade). Adding: "state": {  "opacity": 0,5 } should do the trick but it doesn't seems to work.

```
{
              "id": "baseCBME_CBCE_HS_RO_3978",
              "name": "Canada Base Map - Elevation (CBME)",
              "description": "The Canada Base Map ...",
              "altText": "altText - Canada Base Map - Elevation (CBME)",
              "layers": [
                     {
                           "id": "CBME_CBCE_HS_RO_3978",
                            "layerType": "esriFeature",
                           "url":"http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/...",
                           "state": {
                                "opacity": 0,5
                          }
                     },
                     {
                           "id": "CBMT_CBCT_GEOM_3978",
                           "layerType": "esriFeature",
                           "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/..."
                     }
              ],
              "tileSchemaId": "EXT_NRCAN_Lambert_3978#LOD_NRCAN_Lambert_3978"
}
```

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2463

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728)

### CODE REVIEW

**Comment by JahidAhmed** [comment]
The blank basemap does not seem to be using opacity 0 anymore when being created, and thus it's showing a basemap there as well

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728#-:-LDHNoDk-eD6EV73XJ8f:b-p05osn)*

**Comment by JahidAhmed** [comment]
For sample 65, clicking on the first basemap in the panel repeatedly also has two different outcomes; one with the CBMT basemap showing and one with the other layer showing

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728#-:-LDHP9ah2NGI2tbIAxcp:bjzwj7w)*

**Comment by JahidAhmed** [comment]
Sorry, you can ignore my 2nd comment about the two different outcomes. That is most likely due to the broken node for the CBMT layer: http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer (layers object sometimes populated and sometimes empty, seen by refreshing)

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728#-:-LDHPmzlCd9at4bou8Qd:bhinfe3)*

**Comment by jolevesq** [comment]
Good catch. I removed the opacity in config class because it was not use anymore but misses the blank basemap

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728#-:-LDcMruTDP7o0dj70NB8:b-91apt1)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728)*

**Comment by james-rae** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728#-:-LDfmZbP9NWYWv-rLcPd:bnfp4nl)*

**Pull request merged**
