### PR TITLE
Sidenav, appbar, main-panel, toc and toolbox

### PR DESCRIPTION
**Pull request by AleksueiR**
fixed broken animation on the sidenav (it was a separate PR);
added the main panel (with animation);
added temporary logo on the sidenav;
added toc and toolbox panels with filler content with primitive routing;
made everything less ugly;
patched code according to latest JSCS config;

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/8)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1, 45 of 45 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/toc/toc.controller.js, line 6 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8#-JzvJrU0R7aDgKG4hG7H)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a419e4c714648b9a72254629047c3fe046d737aa/src/app/ui/toc/toc.controller.js#L6)):</sup>
Do we want to go with a java style TocController instead of TOCController (the former reads better IMO)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/toc/toc.controller.js, line 6 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8#-JzvJrU0R7aDgKG4hG7H)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a419e4c714648b9a72254629047c3fe046d737aa/src/app/ui/toc/toc.controller.js#L6)):</sup>
Agree, not sure why I wrote it like that in the first place.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by AleksueiR** [comment]
Review status: 41 of 42 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/app/ui/toc/toc.controller.js, line 6 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8#-JzvJrU0R7aDgKG4hG7H)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a419e4c714648b9a72254629047c3fe046d737aa/src/app/ui/toc/toc.controller.js#L6)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r1, 30 of 45 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/common/router/router.module.js, line 8 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8#-JzveonS2o0AdlXkUlCP)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/17c77e249c873448bb1c9c7d8af35f7b09ff6054/src/app/common/router/router.module.js#L8)):</sup>
Question: why if this file haven't been modified it is in the file to review in reviewable?

---

<sup>**[src/app/layout/layout.route.js, line 32 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8#-JzvfXZNKWgCO4Pn6RkA)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/17c77e249c873448bb1c9c7d8af35f7b09ff6054/src/app/layout/layout.route.js#L32)):</sup>
Do you still need this panelPlug, it is define in your main.app? Is it the same panel?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/common/router/router.module.js, line 8 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8#-JzveonS2o0AdlXkUlCP)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/17c77e249c873448bb1c9c7d8af35f7b09ff6054/src/app/common/router/router.module.js#L8)):</sup>
There is a whitespace change `function()` -> `function ()` which reviewable is not highlighting

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r1, 3 of 45 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by ec-dev** [comment]
Reviewed 5 of 45 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by ec-dev** [comment]
Reviewed 3 of 45 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/layout/layout.route.js, line 32 \[r5\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8#-JzvfXZNKWgCO4Pn6RkA)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/17c77e249c873448bb1c9c7d8af35f7b09ff6054/src/app/layout/layout.route.js#L32)):</sup>
`panelPlug` is where main panels (like `toc` and `toolbox`) will be inserted depending on the state. At `app` - which is the default state - it's empty, so it's not really needed here. I just didn't want to delete it just yet.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/8)

**Pull request merged**
