### PR TITLE
feat(ui): add support for medium sized viewports

### LINKED ISSUE #1243: Medium Mobile Layout Optimizations
Implement optimizations for a medium sized layout (480-840 pixels):
- [x] update details panel opened from the datatable to open as an "expended" popup
- [x] add back arrows instead of the close buttons in the top-left corner to child panels when overlaying their parent panels.
- [x] remove split view from datatable
- [x] datatable is maximized by default

### PR DESCRIPTION
**Pull request by milesap**
For device widths <= 840

Closes #1243

---

This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1276)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276)*

**Comment by AleksueiR** [comment]
Found a weird case when the datatable panel will open behind the toc:
- click on the map to open identify results
- expand the first result
- switch to the toc
- open datatable (datatable opens behind the toc)

GIF: [table\_mad.gif](https://files.reviewableusercontent.io/images/reviewable/2285779/0a2i7tqky0AcoNypup5nTRGc/table_mad.gif)

Good job otherwise :+1:

---

Reviewed 8 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/content/styles/modules/_details.scss, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWp4WsTqTJiwU0lg4O:-KUWp4WsTqTJiwU0lg4P:bj764ko) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_details.scss#L31)):*
> ```SCSS
>         }
> 
>         @include media($rv-md...) {
> ```

Forcing absolute positioning on a dialog kills opening animation.

---

*[src/content/styles/modules/_mapnav.scss, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWpTTv1eRAYgkNMl0L:-KUWpTTv1eRAYgkNMl0M:borx2gs) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_mapnav.scss#L19)):*
> ```SCSS
>         @include media($rv-md...) {
>             bottom: $viewport-gutter;
>             right: $viewport-gutter;
> ```

`right` value doesn't really change here from default.

---

*[src/content/styles/modules/_toc.scss, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWpntdUND1cFgs-BOD:-KUWpntdUND1cFgs-BOE:bzbe37d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_toc.scss#L26)):*
> ```SCSS
>             overflow: hidden;
> 
>             @include media($rv-lg) {
> ```

What is this for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-:-KUWrM-ZdDhbucuF0P_3:boxuo93)*

**Comment by milesap** [comment]
Fixed the z-index error

---

Review status: 9 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/content/styles/modules/_details.scss, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWp4WsTqTJiwU0lg4O:-KUwsuNui4NL42hz1_x6:b-b7vx5o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_details.scss#L31)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Forcing absolute positioning on a dialog kills opening animation.
</details>
Removed `!important`

---

*[src/content/styles/modules/_mapnav.scss, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWpTTv1eRAYgkNMl0L:-KUwt5k257CP8OrUwuas:b-i7dyq3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_mapnav.scss#L19)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `right` value doesn't really change here from default.
</details>
Good catch - removed duplicate

---

*[src/content/styles/modules/_toc.scss, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWpntdUND1cFgs-BOD:-KUwtCBMoENHfwpRhpp7:b-t3evkb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_toc.scss#L26)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> What is this for?
</details>
This prevents the layer loading indicator lines from poking through to a panel overtop the toc for small and medium sized layouts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-:-KUwtfb5D4cec3vChu4e:b-u9m6wp)*

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276)*

**Comment by AleksueiR** [comment]
Fix confirmed.

---

Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/common/router/statemanager.service.js, line 292 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KV15_Z3fkKdJqheKSkL:-KV15_Z3fkKdJqheKSkM:b-rjk389) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f74712a5cdd4b9c9a7bf81052341ec87319fc674/src/app/common/router/statemanager.service.js#L292)):*
> ```JavaScript
>          */
>         function openPanel(panelToOpen, propagate = true) {
>             /*jshint maxcomplexity:10 */
> ```

Instead of adding an exception, maybe refactor the function to reduce its complexity.

---

*[src/content/styles/modules/_details.scss, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWp4WsTqTJiwU0lg4O:-KV1494_F1plHSx62H3z:b-lu563s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_details.scss#L31)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Removed `!important`
</details>
`#mdDialog`s still don't have opening animation. They just appear on the page. They do have a closing animation though.

---

*[src/content/styles/modules/_toc.scss, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWpntdUND1cFgs-BOD:-KUx7OOVbx7BH8U0T0oG:b-jxcbvf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_toc.scss#L26)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> This prevents the layer loading indicator lines from poking through to a panel overtop the toc for small and medium sized layouts
</details>
Fair enough. Can you add this as a comment for future reference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-:-KV15U0npwBB6vqNx0gd:b-hcpr7l)*

**Comment by mweech** [comment]
We should probably be shifting down the nav controls as we run out of vertical space as well: 
image

**Comment by AleksueiR** [comment]
:point_up_2: moved to [a separate issue](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1310).

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-:-KVBTYa1p_kEL-Cs-l7k:b-ctjkcu)*

**Comment by milesap** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 292 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KV15_Z3fkKdJqheKSkL:-KVP_bpyuNb0B5juFVJs:b-l2o7hr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f74712a5cdd4b9c9a7bf81052341ec87319fc674/src/app/common/router/statemanager.service.js#L292)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Instead of adding an exception, maybe refactor the function to reduce its complexity.
</details>
Ok broke up the opening logic into two parts; one for parent "content" panels, the other for child panels.

---

*[src/content/styles/modules/_details.scss, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWp4WsTqTJiwU0lg4O:-KVPjIxNvAnY0HOe_xV8:bfs238m) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_details.scss#L31)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `#mdDialog`s still don't have opening animation. They just appear on the page. They do have a closing animation though.
</details>
Opened issue #1312, seems they have never been working (at least not at 0.17.0)

---

*[src/content/styles/modules/_toc.scss, line 26 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWpntdUND1cFgs-BOD:-KVPjXkiXW3ZJEqkwwra:b-3dcmao) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_toc.scss#L26)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Fair enough. Can you add this as a comment for future reference?
</details>
Ok added comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 288 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KVPm_RsKfzut71n5Y_l:-KVPm_Rt6IBQi1K71xxU:binyliu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67307f460b0999442a89d17fc3a4e15dcc9380f4/src/app/common/router/statemanager.service.js#L288)):*
> ```JavaScript
>          * @param  {Object}   panelToOpen the parent panel object to be opened
>          * @param  {Boolean}  propagate optional allow sibling panels to be modified
>          * @return {Promise}  resolves when panel animation has completed
> ```

For this and the other two related functions can you add the value the promise resolves with as part of the return comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 12 files at r1, 3 of 4 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/common/router/statemanager.service.js, line 354 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KVPqR6vDXlmF7twShFN:-KVPqR6vDXlmF7twShFO:b9bypkr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67307f460b0999442a89d17fc3a4e15dcc9380f4/src/app/common/router/statemanager.service.js#L354)):*
> ```JavaScript
>             // moved into its own parent panel
>             if (panelToOpen.name === 'mainDetails') {
>                 $('rv-panel[type="main"]').css('z-index', 4);
> ```

Missed the first time: this will search the whole page and apply to all main panels, shouldn't this use `$rootElement` or `shellNode`?

---

*[src/content/styles/modules/_details.scss, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KUWp4WsTqTJiwU0lg4O:-KVPn-nPTaLKEKQACU63:b-oz8tym) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4dc7c96b90b65a470c717fd11dd1565bd7a45b30/src/content/styles/modules/_details.scss#L31)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary>
> Opened issue #1312, seems they have never been working (at least not at 0.17.0)
</details>
Good call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/common/router/statemanager.service.js, line 288 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KVPm_RsKfzut71n5Y_l:-KVeFY7c-S6I_M7kHDYJ:b6my2ds) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67307f460b0999442a89d17fc3a4e15dcc9380f4/src/app/common/router/statemanager.service.js#L288)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> For this and the other two related functions can you add the value the promise resolves with as part of the return comment?
</details>
Ok, noted that they resolve to `undefined` when all animations are complete

---

*[src/app/common/router/statemanager.service.js, line 354 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-KVPqR6vDXlmF7twShFN:-KVeG9RmdZjigfyye3Ot:bku0j92) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/67307f460b0999442a89d17fc3a4e15dcc9380f4/src/app/common/router/statemanager.service.js#L354)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Missed the first time: this will search the whole page and apply to all main panels, shouldn't this use `$rootElement` or `shellNode`?
</details>
Ah yes it would, switched to `$rootElement.find`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1276#-:-KVeHQd7yEZwgmeFGJJb:bnfp4nl)*

**Pull request merged**
