### PR TITLE
feat(ui): legend panel can be opened by default

### LINKED ISSUE #1338: Legend Panel may be Opened by Default
Add the ability to have the viewer legend be expanded by default on initial loading of the map.  User should be able to separately specify the behavior for mobile layouts as an expanded legend would lead to a poor UX.

Requested by JOSM.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Added schema option legendIsOpen where default can be changed from false
to true for the three viewport sizes; small, medium, and large

Closes #1338

## Testing
👀 

## Documentation
inline comment added to `shell.directive.js`

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1496)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1496)*

**Comment by AleksueiR** [comment]
:lgtm: and approved by Aly remotely.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1496#-:-KZWkGEDVO9G84qQsgSh:b4jr4gh)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1496)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1496)*

**Pull request merged**
