### PR TITLE
fix(test): remove some Mercator lods node and adjust extent

### LINKED ISSUE #1230: Mercator maps - Map scale value changed reversely when zooming out after certain scale
Tested build: http://fgpv.cloudapp.net/demo/v1.3.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

After zooming out to a scale of 3000km, the map scale changed reversely to 1000km, and then 60km if continuing to zoom out the map.
image

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
Mercator maps - Map scale value changed reversely when zooming out after certain scale #1230

## Testing
Manual/visual test

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [ ] PR targets the correct release version

Closes #1230

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1598)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598)*

**Comment by AleksueiR** [comment]
There is a slight problem with this - on small layouts you cannot zoom out far enough to see the whole of Canada. 
This is as far out as it goes:


I think users should be able to at least see the whole continent.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-Kahj1AosidMYUNWvwNO:bsrfgzi)*

**Comment by ChrisLatRNCan** [comment]
Salut, how can I replicate what you've done ? Thanks

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-KahkBdkypTSZq0phpio:bbpgkzl)*

**Comment by AleksueiR** [comment]
Updates container styles on the `fgp-en.html` page: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/index-fgp-en.html#L12

with

```css
main div.fgpv {
            width: 500px;
            height: 500px;
            margin: 10px -15px -15px -15px;
        }

```

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-KahkjaoJ3HENaauc1Ub:b-edkzlx)*

**Comment by ChrisLatRNCan** [comment]
Ok, I'll do

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-KahlbuFHApXLRGVPv1r:b-rlb4bs)*

**Comment by ChrisLatRNCan** [comment]
I'll bring back one Lods node to see what's happening

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-KahnUs3DQuKs2VHlS6M:bnqn696)*

**Comment by ChrisLatRNCan** [comment]
Is this better ?


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-Kahq6JORkVYYgO55mCw:b-8quzrs)*

**Comment by ChrisLatRNCan** [comment]
I removed only three nodes. It seems better.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-KahspkdSn8OfO0ojcg2:b-a0rw9h)*

**Comment by james-rae** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598)*

**Comment by AleksueiR** [comment]
Yes. This is manual tweaking though. We need this to happen automagically. Somehow...

The schema supports specifying three different extents in the config: `default` (starting extent), `full` (should give good view of the whole map, not necessarily the maximum extent), and `maximum`. I think, what we want here is to let the user zoom out to the `full` extent no matter the size of the map container. 

Knowing the size of the map container, we can find out how much of the map will be visible for every zoom level/lod, and restrict zooming out beyond the lod which can comfortably fit the `full` extent specified in the config. Or something like that. 

Question: how is this related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1320 ? Can we use extent restriction instead of adding/removing lods?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-Kahs88KBItbpuQJ5Udf:b-tbyu8j)*

**Comment by james-rae** [comment]
LODs are set when the map is created. You cannot add or remove them afterwards. I believe we can set restrictions on the zoom slider (?).  What we may need is some formula to calculate when a zoom level is ridiculous. It would need to be re-evaluated whenever the map size changes. It should also be adjustable via the config (i.e. make more or less tolerant).  Something like 
```
FOR EACH LOD { 
   IF screen size in pixels * LOD.resolution > config tolerance THEN {
       remove LOD from zoom slider
   }
  // test both width and height?
}

```

All very conceptual, not sure if it will work.

#1320 restricts on x and y, not z.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-Kahuu-xLg825dsS9dzH:b8osf97)*

**Comment by AleksueiR** [comment]
Yes, I meant restricting zoom slider, not actually removing LODs. Sorry about that.
Calculating the ridiculousness of the zoom level is what I'm talking about, yes. Can we use the `full` extent from the config as the tolerance? If it's not specified, we can't really tell if it's ridiculous or not. Should be the responsibility of the map author to set it up.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1598#-:-KahwOt0D1cnYkx8RLXz:b-9scpif)*

**Comment by ChrisLatRNCan** [comment]
Humm, first time seeing #1320. They seem related. I would keep the tweaking for the moment and go on with a new issue to define a more complexe strategy.

**Comment by ChrisLatRNCan** [comment]
I had problem in the past with different extent profils. Need to remember the issue.

**Pull request merged**
