### PR TITLE
chore(build): version 1.5.0-rc3

### PR DESCRIPTION
**Pull request by milesap**
## Description
RC3 release

## Testing
nay

## Documentation
nay

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1676)

### CODE REVIEW

**Comment by milesap** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676#-:-KcSkHTkrKIfdAVyKztu:bg7igkv)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676#-:-KcSkPIOALDJofodogxN:bnfp4nl)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bower.json, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676#-KcSkXKvHE00cNrgdcx9:-KcSkXKvHE00cNrgdcxA:bw717dw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/608ccbad842840801ab28fa3a02436bdb67a9667/bower.json#L4)):*
> ```JSON
>   "name": "r2v2",
>   "description": "FGP R2 Viewer",
>   "version": "1.5.0-RC3",
> ```

Shouldn't this be lowercase rc3?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676)*

**Comment by milesap** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bower.json, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676#-KcSkXKvHE00cNrgdcx9:-KcSkqc6ZjFSgVcybgPh:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/608ccbad842840801ab28fa3a02436bdb67a9667/bower.json#L4)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Shouldn't this be lowercase rc3?
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1676)*

**Pull request merged**
