### PR TITLE
2279 datatable toggle columns

### LINKED ISSUE #2279: Datatable toggle sort and display settings
Inside the datatable settings panel, have an option to toggle the `Sort` of all columns to increasing, descending or off instead of having to toggle one by one.

Similarly, toggle the display on or off for all columns.

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes #2279 

Also disables reset button on table when no filters are applied

## Testing
Visually tested

## Documentation
None

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2377)

### CODE REVIEW

**Comment by milesap** [comment]
Prob. by design but changing `sort` and `show` values do not require `Apply` button but `Filter` text does. It least for me this seems odd. 

Everything looks good gg

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-:-Ku4aQl5FcPDl7iouYmg:b-6sr0pk)*

**Comment by JahidAhmed** [comment]
Not too sure about that but I guess the reasoning behind it was that sorting and displaying columns do not directly affect the way layers are displayed on the map, which is the only purpose of the `Apply` button.

I guess the only thing could be to redraw the layer according to sort so that the positioning of each individual feature on the map depends on its sort position. But I don't know whether that's possible or if we'd even want to do that.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-:-Ku4bqsRE5RAwXQ8h7KK:bmjcukx)*

**Comment by AleksueiR** [comment]
I initially suggested by applying filters to the map be done automatically, as soon as the values change (maybe with some debounce), but it seemed to be too taxing, especially for larger datasets.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-:-Ku4dFgzpqD5dISfLOd0:b60snw4)*

**Comment by AleksueiR** [comment]
so many typos :man_facepalming: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-:-Ku4dh5wAycDIGyqFYBE:b-o3jakz)*

**Comment by AleksueiR** [comment]
No typos in the PR, typos in my comment.

:lgtm: Demo works, everything looks good :+1: 

---

Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/ui/table/setting-panel.html, line 42 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-Ku4fMU50lao6BMkJFEw:-Ku4fMU50lao6BMkJFEx:bgbauoa) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db3beedfc7be97d3ff1c152b6c6cba99aa6c40df/src/app/ui/table/setting-panel.html#L42)):*
> ```HTML
>                     <button class="rv-filter-settting-display md-subhead rv-icon-16" ng-click="self.displayAll()">
>                         {{ 'filter.settings.label.show' | translate }}
>                         <md-icon md-svg-src="toggle:check_box" ng-show="self.displayStatus() === true"></md-icon>
> ```

You can dynamically change the icon source and it should update accordingly - no need for several icons. 

```html
<md-icon md-svg-src="toggle:{{ self.displayStatus() ? 'check_box' : (!self.displayStatus() ? 'check_box_outline_blank' : 'indeterminate_check_box') }}" ></md-icon>
```

---

*[src/app/ui/table/table-setting-panel.directive.js, line 288 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-Ku4gR-oFA8HoKQg2Nvr:-Ku4gR-oFA8HoKQg2Nvs:b1e3ojm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db3beedfc7be97d3ff1c152b6c6cba99aa6c40df/src/app/ui/table/table-setting-panel.directive.js#L288)):*
> ```JavaScript
>      */
>     function displayStatus() {
>         const display = self.columns[2].display;
> ```

Please, add a comment why the second column is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-:-Ku4gX9Ce8Xp--y3Ej1F:b-v6erlv)*

**Comment by JahidAhmed** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/table/setting-panel.html, line 42 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-Ku4fMU50lao6BMkJFEw:-Ku4kTDOW7KvUTSOPNg4:b-iry7x8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db3beedfc7be97d3ff1c152b6c6cba99aa6c40df/src/app/ui/table/setting-panel.html#L42)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

You can dynamically change the icon source and it should update accordingly - no need for several icons. 

```html
<md-icon md-svg-src="toggle:{{ self.displayStatus() ? 'check_box' : (!self.displayStatus() ? 'check_box_outline_blank' : 'indeterminate_check_box') }}" ></md-icon>
```
</blockquote></details>

Done, thanks

---

*[src/app/ui/table/table-setting-panel.directive.js, line 288 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-Ku4gR-oFA8HoKQg2Nvr:-Ku4kYbkNUH6srM1jLyx:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/db3beedfc7be97d3ff1c152b6c6cba99aa6c40df/src/app/ui/table/table-setting-panel.directive.js#L288)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, add a comment why the second column is used.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377)*

**Comment by AleksueiR** [comment]
Yes, tabbing in the settings panel needs more work; should be another PR for that.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2377#-:-KuL1KUBKXyIjgxFL3-J:bx37m99)*

**Pull request merged**
