### PR TITLE
Load geoapi

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/42)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/app/layout/shell.html, line 11 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/42#-K14OWLN5uHtq4ldCAL3)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16316f737d46d86fc15e9a6b0e91bf6a44612814/src/app/layout/shell.html#L11)):</sup>
`rv-init-map` directive is missing.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/42)

**Comment by alyec** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/app/layout/shell.html, line 11 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/42#-K14OWLN5uHtq4ldCAL3)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/16316f737d46d86fc15e9a6b0e91bf6a44612814/src/app/layout/shell.html#L11)):</sup>
I haven't built it yet, didn't see any build errors so I figured I could add it later.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/42)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/42)

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/42)

**Pull request merged**
