### PR TITLE
Api 08 (LinearRing, Polygon)

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2610.

Also destroys any open hovertips when a `SimpleLayer` visibility is toggled off.

## Testing
Couple basic examples:

```js
POLYGON
    var pointA = new RZ.GEO.Point(0, '', [-79, 43]);
    var pointE = new RZ.GEO.Point(4, '', [-49, 70]);
    var linearRingA = new RZ.GEO.LinearRing(10, [pointA, [-79, 70], pointE, [-49, 43]]);
	var linearRingB = new RZ.GEO.LinearRing(11, [[-70, 45], [-70, 57], [-55, 57], [-55, 45]]);
    var linearRingC = new RZ.GEO.LinearRing(12, [[-10, 45], [-10, 57], [-20, 57], [-20, 45]]);

    // default settings
    var polygonA = new RZ.GEO.Polygon(100, [linearRingA, linearRingB]);
    // custom settings
    var polygonB = new RZ.GEO.Polygon(101, [linearRingC], { outlineColor: '#000000', outlineWidth: 6, fillColor: '#0000ff', fillOpacity: 0.4 });

    var hoverA = new RZ.GEO.Hover(0, 'my annotation');
    var hoverB = new RZ.GEO.Hover(1, '<a href="https://www.w3schools.com/html/">Visit our HTML tutorial</a>', { followCursor: true, position: 'left' });
    polygonA.hover = hoverA;
    polygonB.hover = hoverB;
    RZ.mapInstances[0].simpleLayer.addGeometry([polygonA, polygonB]);
```

## Documentation
https://jahidahmed.github.io/docs/api/developer/index.html

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2611)

### CODE REVIEW

**Comment by milesap** [comment]
Having some issues during testing - the following code displays a linear ring (or it could be a non-filled polygon)

```js
var linearRingB = new RZ.GEO.LinearRing(11, [[-70, 45], [-70, 57], [-55, 57], [-55, 45]]);
var polygonA = new RZ.GEO.Polygon(100, [linearRingB]);
RZ.mapInstances[0].simpleLayer.addGeometry(polygonA);
```

However the following shows nothing on the map:

```js
var linearRingB = new RZ.GEO.LinearRing(11, [[-70, 45], [-70, 57], [-55, 57], [-55, 45]]);
RZ.mapInstances[0].simpleLayer.addGeometry(linearRingB);
```

Let me know if I'm missing something. Alex advised defaults should be 1px width, black border for linear rings. Fill color on the polygon is nothing, full transparency. The CIP project can use LinearRings or Polygons for their grid squares.

---

Review status: 0 of 52 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2611#-:-L8hcKgy3onELskoAnmq:bwherz8)*

**Comment by milesap** [comment]
Here are some ways we can tackle linear rings and polygons (some based off yesterdays pod discussion):

#### Option 1
Throw an error if an instance of `LinearRing` is added to the map explicitly. The error advises they can only be used with polygons.

#### Option 2
Remove the linear ring class from geometry and only make it accessible from a polygon. You can instantiate a polygon with an:
- `XYLiteral` or `Point`
> This would be your basic polygon with one outer linear ring
- `XYLiteral[]` or `Point[]` 
> This would produce a list of linear rings, with one linear ring per array item.

You would make the `LinearRing` class available as a property on the polygon instance:

```js
const lr = new myPolygon.LinearRing([points...]);
lr.color = '#00000';
lr.add(); // This adds the linear ring to the polygon it came from
// or
myPolygon.addLinearRings([lr, ...]); // alternate form or when adding many at once (to prevent re-draws)
```

#### Option 3
Accept `LineString` instances instead of `LinearRing`. This would remove the `LinearRing` class from geometry entirely. When a `LineString` is given to a polygon it is closed (if open). Everything else remains the same. Not sure if this just pushes the problem onto `LineString`?

#### Option 4
None of the above 🌦

**Comment by james-rae** [comment]
I like both options 1 & 2.  I'd say go with 1 for now (1 line of non-impact code) and we can have a good face to face haggle at our next meeting for how 2 can play out

**Comment by JahidAhmed** [comment]
Decided to move forward with Option 1 for the time being and then we can discuss in an upcoming meeting next steps regarding hovertips and multigeometry / polygons.

Updated console calls to show different CIP required options:
```js
    var pointA = new RZ.GEO.Point(0, '', [-79, 43]);
    var pointE = new RZ.GEO.Point(4, '', [-49, 70]);
    var linearRingA = new RZ.GEO.LinearRing(10, [pointA, [-79, 70], pointE, [-49, 43]]);
	var linearRingB = new RZ.GEO.LinearRing(11, [[-70, 45], [-70, 57], [-55, 57], [-55, 45]]);
    var linearRingC = new RZ.GEO.LinearRing(12, [[-10, 45], [-10, 57], [-20, 57], [-20, 45]]);

    // default settings - only the outline ring, no fill for polygon
    var polygonA = new RZ.GEO.Polygon(100, [linearRingA, linearRingB]);
    // custom settings - just the fill for the polygon, no outline ring
    var polygonB = new RZ.GEO.Polygon(101, [linearRingC], { outlineWidth: 0, fillColor: '#000000', fillOpacity: 1 });

    var hoverA = new RZ.GEO.Hover(0, 'my annotation');
    var hoverB = new RZ.GEO.Hover(1, '<a href="https://www.w3schools.com/html/">Visit our HTML tutorial</a>', { followCursor: true, position: 'left' });
    polygonA.hover = hoverA;
    polygonB.hover = hoverB;
    RZ.mapInstances[0].simpleLayer.addGeometry([polygonA, polygonB]);
```

**Comment by milesap** [comment]
:lgtm: I'll send out a meeting for mid next week

---

Reviewed 53 of 54 files at r1, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2611#-:-L8mjaBG8E11ZMXj5z_W:bqfkl7b)*

**Comment by milesap** [comment]
Reviewed 1 of 54 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2611)*

**Pull request merged**
