### PR TITLE
feat(ui): add zoom to control four out of scale layers

### LINKED ISSUE #625: feat(ui): add a "zoom to" control for out-of-scale layers
As per latest mockups, `zoom to` control should replace the `visibility` toggle when the layer is out of scale.

Other points:
- identify function should not be executed against out-of-scale layers
- when the layer needs to be zoomed in to its scale level use ; when zoomed out, use 
- invisible layers should keep  icon regardless of their out-of-scale status
- when an invisible layer is set to visible, the icons should change to 
  -  if the layer is in scale;
  -  if the layer is zoomed out of its scale level
  -  if the layer is zoomed in past its scale level

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #625

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/730)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 547 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkIjeXTox6c5OdZg8x:-KJkIjeXTox6c5OdZg8y:-1534542362) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/app/geo/layer-registry.service.js#L547)):*
> ```JavaScript
>                 const lods = (direction === 'zoomin') ? geoState.lods : [...geoState.lods].reverse();
> 
>                 lods.some(lod => {
> ```

We have a polyfill for `Array.find`:
```
lod = lods.find(lod => direction === 'zoomin' ? lod.scale < l.minScale : lod.scale > l.maxScale);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 547 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkIjeXTox6c5OdZg8x:-KJkOaGSvFF9WUAfTiNq:-1058975459) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/app/geo/layer-registry.service.js#L547)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> We have a polyfill for `Array.find`:
> ```
> lod = lods.find(lod => direction === 'zoomin' ? lod.scale < l.minScale : lod.scale > l.maxScale);
> ```
</details>
I thought it was just for exact match in string comparison. I will do the modifications

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by AleksueiR** [comment]
Some layers are missing visibility controls: 


<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> #### feat\(ui\): add zoom to control four out of scale layers
> 
> Closes #625
> 
> 
> 
</details>


---

Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/schema.json, line 219 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkO30EnZQa3JV8jxoU:-KJkO30FFjFs7sWBiu-f:-204561642) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/schema.json#L219)):*
> ```JSON
>                 "value": {
>                     "type": "string",
>                     "enum": ["", "zoomin", "zoomout"],
> ```

Would a boolean work? `true` - zoomin, `false` - zoomout, and there is already a scale flag specifying if the layer is in scale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-:-KJkPAD0b5CvMkF1JNaF:-467058029)*

**Comment by jolevesq** [comment]
Just see it, I will correct it before pushing my modifications.

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Some layers are missing visibility controls: 
> 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/schema.json, line 219 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkO30EnZQa3JV8jxoU:-KJkRZayF_xx6fQft604:-565105827) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/schema.json#L219)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Would a boolean work? `true` - zoomin, `false` - zoomout, and there is already a scale flag specifying if the layer is in scale.
</details>
If a put a boolean, i will have to put another value to know if offscale or not. We have to check to value instead of one. It is why I put it inside one value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-:-KJkRni6AWeXMk5UeCdT:-1557526923)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/schema.json, line 219 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkO30EnZQa3JV8jxoU:-KJkTEtodKPZSI8QCw5A:-629151112) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/schema.json#L219)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> If a put a boolean, i will have to put another value to know if offscale or not. We have to check to value instead of one. It is why I put it inside one value.
</details>
It's already available. You can check `legendEntry.flags.scale.visible` to see if the layer is in scale or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/schema.json, line 219 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkO30EnZQa3JV8jxoU:-KJkhwGRpOrUmzil9pJh:-16666723) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/schema.json#L219)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> It's already available. You can check `legendEntry.flags.scale.visible` to see if the layer is in scale or not.
</details>
I have a question for the flag, now we have a visibility icon, is flag still needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by jolevesq** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/schema.json, line 219 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkO30EnZQa3JV8jxoU:-KJlA6kPb65m_MJjVwUL:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/schema.json#L219)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I have a question for the flag, now we have a visibility icon, is flag still needed?
</details>
Done.

---

*[src/app/geo/layer-registry.service.js, line 547 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJkIjeXTox6c5OdZg8x:-KJlA63ru8594Sdb7MKg:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5d0b0bbe88a70bfcd8dba0a6d1a7f5d9d801a52f/src/app/geo/layer-registry.service.js#L547)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I thought it was just for exact match in string comparison. I will do the modifications
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 6 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 73 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJowTst__VTkZP6WfJ_:-KJowTst__VTkZP6WfJa:1961645432) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/ui/toc/toc.service.js#L73)):*
> ```JavaScript
>                     icon: zoom => zoom ? 'action:zoom_in' : 'action:zoom_out',
>                     label: zoom => zoom ? 'toc.label.visibility.zoomIn' : 'toc.label.visibility.zoomOut',
>                     tooltip: zoom => zoom ? 'toc.tooltip.visibility.zoomIn' : 'toc.tooltip.visibility.zoomOut',
> ```

Non-blocking. The above lines are perfectly fine, feel free to ignore this. 
Just out of love for optimization, I thought this can be simplified a little bit :smile: 

```js
zoom => `action:visibility${zoom ? '' : '_off'}`
zoom => `toc.label.visibility.zoom${zoom ? 'in' : 'out'}`
zoom => `toc.tooltip.visibility.zoom${zoom ? 'in' : 'out'}`
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 209 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJp1ZHL8-t4Qr5hNkMv:-KJp1ZHL8-t4Qr5hNkMw:865738501) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/geo/layer-registry.service.js#L209)):*
> ```JavaScript
>                 const scaleSet = {
>                     value: false,
>                     direction: false
> ```

I'm not sure what the scope of change would be for a rename, but if we are using booleans `direction` is going to get confusing.  We can either use constants like `ZOOM_IN: true, ZOOM_OUT: false` or we can rename the variable to `zoomIn` so the direction is implicit in the name and we can have checks like `zoomIn ? lods : [...lods].reverse()`.

---

*[src/app/ui/toc/toc.service.js, line 73 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJowTst__VTkZP6WfJ_:-KJp19xii_08vxr5SzA6:-1592208620) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/ui/toc/toc.service.js#L73)):*
> Just out of love for optimization

Just 20 minutes ago you linked this XKCD https://xkcd.com/1691/ :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/ui/toc/toc.service.js, line 73 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJowTst__VTkZP6WfJ_:-KJp39XacTw81smHe3FH:-1219319281) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/ui/toc/toc.service.js#L73)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> > Just out of love for optimization
> 
> Just 20 minutes ago you linked this XKCD https://xkcd.com/1691/ :)
</details>
That's why I linked it :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 209 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJp1ZHL8-t4Qr5hNkMv:-KJp9gmagi2CDUX-5hbe:-1272646467) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/geo/layer-registry.service.js#L209)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I'm not sure what the scope of change would be for a rename, but if we are using booleans `direction` is going to get confusing.  We can either use constants like `ZOOM_IN: true, ZOOM_OUT: false` or we can rename the variable to `zoomIn` so the direction is implicit in the name and we can have checks like `zoomIn ? lods : [...lods].reverse()`.
</details>
I think you are right. It was one of my concern and it was the reason I haven't used boolean at first. I will do the modification.

---

*[src/app/ui/toc/toc.service.js, line 73 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJowTst__VTkZP6WfJ_:-KJpAB6xocmS_-njjwUQ:1298162690) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/ui/toc/toc.service.js#L73)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> That's why I linked it :D
</details>
I will do something from Aly's comment. Will do this at the same time.  I will do it as well for the visibility icon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by jolevesq** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 209 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJp1ZHL8-t4Qr5hNkMv:-KJpShW-0hlGhYkNxWls:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/geo/layer-registry.service.js#L209)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I think you are right. It was one of my concern and it was the reason I haven't used boolean at first. I will do the modification.
</details>
Done.

---

*[src/app/ui/toc/toc.service.js, line 73 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730#-KJowTst__VTkZP6WfJ_:-KJpSiKdRVam0etbfkLd:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7e130216b8b537138fb819506cd883668bf803ad/src/app/ui/toc/toc.service.js#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I will do something from Aly's comment. Will do this at the same time.  I will do it as well for the visibility icon.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/730)*

**Pull request closed without merging**
