### PR TITLE
fix(core): Stop Pulling Tiles for Blank Basemap Entries

### PR DESCRIPTION
**Pull request by jolevesq**
Closes#595

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/653)

### CODE REVIEW

**Comment by cynngah** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/ui/basemap/basemap-item.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-KIda7PGR-INWmGSpNQK:-KIda7PGR-INWmGSpNQL:555507122) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da68b192afaa6ed26288771606d4746de80807d6/src/app/ui/basemap/basemap-item.html#L7)):*
> ```HTML
> 
>         <div class="rv-wkid rv-3978" ng-switch-when="3978">
>             
> ```

These `ng-if`s are not needed if the blank  datauri is already set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Comment by AleksueiR** [comment]
The original issue mentioned preventing non-existing overview images (caused by blank basemaps) from being pulled, like this one ` http://fgpv.cloudapp.net/demo/users/jolevesq/images/overview.png`.
If it's easy to do, could you update your PR to include this fix as well? If not, please, create another issue to deal with non-existing overview iamge requests.

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> #### fix\(core\): Stop Pulling Tiles for Blank Basemap Entries
> 
> Closes#595
> 
> 
> 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-:-KIglyQ_NX4U1Vaa2ke7:1973536056)*

**Comment by jolevesq** [comment]
You want me to find if the tile image exist and if not, just make sure it do not throw an error?

<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> The original issue mentioned preventing non-existing overview images (caused by blank basemaps) from being pulled, like this one ` http://fgpv.cloudapp.net/demo/users/jolevesq/images/overview.png`.
> If it's easy to do, could you update your PR to include this fix as well? If not, please, create another issue to deal with non-existing overview iamge requests.
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap-item.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-KIda7PGR-INWmGSpNQK:-KIhIVyvfDS6KtA03G3S:2027806846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da68b192afaa6ed26288771606d4746de80807d6/src/app/ui/basemap/basemap-item.html#L7)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> These `ng-if`s are not needed if the blank  datauri is already set.
</details>
If I remove them, the error is shown in the console. I will see what I can do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-:-KIhZKBKO8z-B_RdtuPJ:-1370856591)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap-item.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-KIda7PGR-INWmGSpNQK:-KIhbmGtWpEoECwpF2tw:-696527820) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da68b192afaa6ed26288771606d4746de80807d6/src/app/ui/basemap/basemap-item.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> If I remove them, the error is shown in the console. I will see what I can do.
</details>
Ok, put ng-if before I set url to empty gif. With empty gif the error is not there anymore. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Comment by jolevesq** [comment]
This error http://localhost:6001/images/overview.png 404 (Not Found)  (from your comment in the issue) comes from _esri.scss and are not related to the blank basemap.

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> You want me to find if the tile image exist and if not, just make sure it do not throw an error?
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-:-KIhcEdSfdu28A5yp4Aq:1197939892)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap-item.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-KIda7PGR-INWmGSpNQK:-KIhdBEAT3R0Aqjwn4Tl:-1844859952) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da68b192afaa6ed26288771606d4746de80807d6/src/app/ui/basemap/basemap-item.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Ok, put ng-if before I set url to empty gif. With empty gif the error is not there anymore. 
</details>
What error are you getting with empty gif? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Comment by jolevesq** [comment]
We miss the overview map sprite. It is why we have http://localhost:6001/images/overview.png 404 (Not Found)  error.

<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> This error http://localhost:6001/images/overview.png 404 (Not Found)  (from your comment in the issue) comes from _esri.scss and are not related to the blank basemap.
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap-item.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-KIda7PGR-INWmGSpNQK:-KIhdNCvNzeDXHndU7jv:507367853) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da68b192afaa6ed26288771606d4746de80807d6/src/app/ui/basemap/basemap-item.html#L7)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> What error are you getting with empty gif? 
</details>
No error. My first intervention was the ng-if and it solves the error not able to retrieve tile. Then I add the empty gif url. Didn't notice I do not need the ng-if anymore because the empty url solve the problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-:-KIhdgi5E95YSOb_GBzN:-1590606577)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/basemap/basemap-item.html, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653#-KIda7PGR-INWmGSpNQK:-KIhxfWV3ERtcDZ5sSN0:898459222) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/da68b192afaa6ed26288771606d4746de80807d6/src/app/ui/basemap/basemap-item.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> No error. My first intervention was the ng-if and it solves the error not able to retrieve tile. Then I add the empty gif url. Didn't notice I do not need the ng-if anymore because the empty url solve the problem.
</details>
Perfect, that's what I was expecting :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/653)*

**Pull request merged**
