### PR TITLE
Integrate on demand attribute loading: Part II

### LINKED ISSUE #518: Dynamic Layers pre-load attributes for all children
Sublayers which are never shown on the map don't need their attributes loaded. 
On the demo page, for example, [AAFC AGRI Environmental Indicators](http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_agri_environmental_indicators/MapServer) takes a couple of minutes to load all the attributes and attributes from visible sublayers are not available until then.

### PR DESCRIPTION
**Pull request by AleksueiR**
Re-apply feature count to toc entries.

Close #518 and #537.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/569)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/569)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/layer-registry.service.js, line 301 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/569#-KGx5oCRQM0-NOt_uQT4:-KGx5oCRQM0-NOt_uQT5:-1217658837) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8ee32c8002e22b0edf48dc2d3b3fd535e77ee97f/src/app/geo/layer-registry.service.js#L301)):*
typo: strip
And I agree with the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/569)*

**Comment by AleksueiR** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 301 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/569#-KGx5oCRQM0-NOt_uQT4:-KH0v92WemUgaunCw3e2:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8ee32c8002e22b0edf48dc2d3b3fd535e77ee97f/src/app/geo/layer-registry.service.js#L301)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/569)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/569)*

**Pull request merged**
