### PR TITLE
API-04: Enable/disable identify & add ability to observe map click features

### PR DESCRIPTION
**Pull request by milesap**
#### [Disable identify](http://fgpv-vpgf.github.io/fgpv-vpgf/api-04-docs/api/classes/_map_.map.html)

```js
mapInstance.identify = false;
```

#### [Map clicks](http://fgpv-vpgf.github.io/fgpv-vpgf/api-04-docs/api/classes/_map_.map.html#click) contain a [feature stream](http://fgpv-vpgf.github.io/fgpv-vpgf/api-04-docs/api/classes/_events_.mapclickevent.html)

```js
RZ.mapInstances[0].click.subscribe(a => {
    a.features.subscribe(featureList => {...});
});
```

## Testing
fry

## Documentation
Yes, definitely 

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2550)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by james-rae** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/identify.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-L34rhLnqIB64F5KI6Km:-L34rhLnqIB64F5KI6Kn:b-8ve4n6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecaeb65c906a6d52933428a21ac440e96fea30cb/src/app/geo/identify.service.js#L87)):*
> ```JavaScript
>             data: allIdentifyResults,
>             isLoaded: $q.all(allLoadingPromises).then(() => {
>                 if (allIdentifyResults[0].data.length > 0) {
> ```

if i'm interpreting this correct, this means the API event/stream/next thing won't trigger until **every** source resolves its promise. There are infallible promises to handle failures/errors, but if you have one service with a high timeout that takes minutes to resolve, the entire thing will be waiting on that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-L34rhLnqIB64F5KI6Km:-L380pdyzfembbR1cALw:bdcwseb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecaeb65c906a6d52933428a21ac440e96fea30cb/src/app/geo/identify.service.js#L87)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

if i'm interpreting this correct, this means the API event/stream/next thing won't trigger until **every** source resolves its promise. There are infallible promises to handle failures/errors, but if you have one service with a high timeout that takes minutes to resolve, the entire thing will be waiting on that.
</blockquote></details>

Ok, I'll play around with this so results are returned as they come in. 

I wasn't sure about why `allIdentifyResults` is an array, I haven't tested a scenario where it's length is greater than 1. Is this ok?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-L34rhLnqIB64F5KI6Km:-L38RktG8bnyZFrDs8jm:b-yzckno) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecaeb65c906a6d52933428a21ac440e96fea30cb/src/app/geo/identify.service.js#L87)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Ok, I'll play around with this so results are returned as they come in. 

I wasn't sure about why `allIdentifyResults` is an array, I haven't tested a scenario where it's length is greater than 1. Is this ok?
</blockquote></details>

I might be ok with waiting, the logic in `identify.service` is a bit convoluted and it is not clear to me how I could stream results as they resolve without re-writing this entire section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by james-rae** [comment]
*[src/app/geo/identify.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-L34rhLnqIB64F5KI6Km:-L396qZaYD_oRWNDnxKk:bgp2spj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecaeb65c906a6d52933428a21ac440e96fea30cb/src/app/geo/identify.service.js#L87)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I might be ok with waiting, the logic in `identify.service` is a bit convoluted and it is not clear to me how I could stream results as they resolve without re-writing this entire section.
</blockquote></details>

something like:

```js
const allLoadingPromises = identifyInstances.map(({ identifyPromise, identifyResults }) => {
	// catch error on identify promises and store error messages to be shown in the details panel.
	const loadingPromise = identifyPromise.catch(error => {
		// add common error handling

		RV.logger.warn('identifyService', `Identify query failed with error`, error);

		identifyResults.forEach(identifyResult => {
			// TODO: this outputs raw error message from the service
			// we might want to replace it with more user-understandable messages
			identifyResult.error = error.message;
			identifyResult.isLoading = false;
		});
	});

	const infallibleLoadingPromise = makeInfalliblePromise(loadingPromise);
	
	// new code here!
	infallibleLoadingPromise.then(() => {
		identifyResults.forEach( idResult => {
			mapClickEvent._featureSubject.next(idResult.data);
		});
	});
	// new code ends!
	
	return infallibleLoadingPromise;
});
```

and move your `mapClickEvent` var definition to be above this block.

Could also change this to pass back more than just `data`.  The `error` string might be useful to tell the API consumer if something failed or not.  May also want to consider passing back the entire `identifyResults` array for a layer, so that consumer knows all results belong to same layer. E.g. if you have a Dynamic Layer with four child layers, the above code snippet will trigger four stream hits; if consumer cares about layer ownership, they need to inspect each stream hit and derive ownership.  The alternate is one stream hit, containing an array of four results.  In this alternate, every layer will return an array on the stream, only dynamics will have more than one element in the array.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by milesap** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/identify.service.js, line 87 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-L34rhLnqIB64F5KI6Km:-L39L7kIuU4BvhH85PYq:b-gymnr4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ecaeb65c906a6d52933428a21ac440e96fea30cb/src/app/geo/identify.service.js#L87)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

something like:

```js
const allLoadingPromises = identifyInstances.map(({ identifyPromise, identifyResults }) => {
	// catch error on identify promises and store error messages to be shown in the details panel.
	const loadingPromise = identifyPromise.catch(error => {
		// add common error handling

		RV.logger.warn('identifyService', `Identify query failed with error`, error);

		identifyResults.forEach(identifyResult => {
			// TODO: this outputs raw error message from the service
			// we might want to replace it with more user-understandable messages
			identifyResult.error = error.message;
			identifyResult.isLoading = false;
		});
	});

	const infallibleLoadingPromise = makeInfalliblePromise(loadingPromise);
	
	// new code here!
	infallibleLoadingPromise.then(() => {
		identifyResults.forEach( idResult => {
			mapClickEvent._featureSubject.next(idResult.data);
		});
	});
	// new code ends!
	
	return infallibleLoadingPromise;
});
```

and move your `mapClickEvent` var definition to be above this block.

Could also change this to pass back more than just `data`.  The `error` string might be useful to tell the API consumer if something failed or not.  May also want to consider passing back the entire `identifyResults` array for a layer, so that consumer knows all results belong to same layer. E.g. if you have a Dynamic Layer with four child layers, the above code snippet will trigger four stream hits; if consumer cares about layer ownership, they need to inspect each stream hit and derive ownership.  The alternate is one stream hit, containing an array of four results.  In this alternate, every layer will return an array on the stream, only dynamics will have more than one element in the array.  
</blockquote></details>

Good solution, and code is working well. Each stream now returns an object (correlated with the idea of a layer) that contains a `data` and possible `error` property. In the future we could expand on this to have more info if need be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by milesap** [comment]
Ok, we're good to go now

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-:-L3ElGMkvt6Iql1GYdE7:b-e792nr)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550)*

**Comment by james-rae** [comment]
Donethanks. Will do some fine tuning and aligning when the Layer identify stuff is created

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-:-L3EqT2-FlCRkNkICnS0:b3n12xs)*

**Comment by milesap** [comment]
Perfecto :ok_hand: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2550#-:-L3Eqy6rltpoTthOvHtu:b-pnxbk9)*

**Pull request merged**
