### PR TITLE
refactor(bookmark): fixing v2 bookmark generation

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Fixing bookmark generation.

## Testing
Not yet.

## Documentation
Some comments.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ not needed
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1917)

### CODE REVIEW

**Comment by james-rae** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 42 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917#-KlUCRM0ai3PMFiDsSlQ:-KlUCRM1X3cO_LW97cEN:b-etapvx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffc550c49444aa19cdf729e58efb96188fbff105/src/app/core/bookmark.service.js#L42)):*
> ```JavaScript
> 
>         // we tack a flag at the end to indicate if we were in blank mode or not
>         const basemap = encode64(mapConfig.selectedBasemap.id);
> ```

Trying to find in the code where `mapConfig.selectedBasemap.id` gets generated, in particular, where the `1` or `0` gets appended.

---

*[src/app/core/bookmark.service.js, line 210 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917#-KlUGQyvTtNfSxklv8HH:-KlUGQywFoCDRKS9LSDW:b-a6xk20) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffc550c49444aa19cdf729e58efb96188fbff105/src/app/core/bookmark.service.js#L210)):*
> ```JavaScript
>             // we need to be aware of hierarchy here (at least on the top level).
>             // top-level children of the layer get rootFlag set to true
>             childItems = simpleWalk(layerRecord.getChildTree(), true);
> ```

Appears we were incorrect when we talked about the tree this morning.  It is not a direct representation of the server structure. It is a representation of the structure as it would appear in an autogenerated legend. So is possible to have duplicate children in the tree (was able to prove this in a sample test). Lets discuss (it might be this is still ok).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 42 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917#-KlUCRM0ai3PMFiDsSlQ:-KlUSnPdUoE_xR2R9Csg:b-z7m4s4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffc550c49444aa19cdf729e58efb96188fbff105/src/app/core/bookmark.service.js#L42)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Trying to find in the code where `mapConfig.selectedBasemap.id` gets generated, in particular, where the `1` or `0` gets appended.
</blockquote></details>

New basemap engine uses a specifically named blank basemap.  Will set the bookmark blank flag to `0` always.  Minor issues arise if loading super-old bookmarks, it might not blank the tiles.  Can live with that.

---

*[src/app/core/bookmark.service.js, line 210 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917#-KlUGQyvTtNfSxklv8HH:-KlUSduE1P2Obu0_lPLj:b-1xvngt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffc550c49444aa19cdf729e58efb96188fbff105/src/app/core/bookmark.service.js#L210)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Appears we were incorrect when we talked about the tree this morning.  It is not a direct representation of the server structure. It is a representation of the structure as it would appear in an autogenerated legend. So is possible to have duplicate children in the tree (was able to prove this in a sample test). Lets discuss (it might be this is still ok).
</blockquote></details>

After discussion, determined duplicates OK.  Minor space inefficiency if people make weird maps, but we can live with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917)*

**Comment by AleksueiR** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/bookmark.service.js, line 42 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917#-KlUCRM0ai3PMFiDsSlQ:-KlUTA7OcHg9egB3Ju9G:b-dtkdrq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffc550c49444aa19cdf729e58efb96188fbff105/src/app/core/bookmark.service.js#L42)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

New basemap engine uses a specifically named blank basemap.  Will set the bookmark blank flag to `0` always.  Minor issues arise if loading super-old bookmarks, it might not blank the tiles.  Can live with that.
</blockquote></details>

Done, thanks.

---

*[src/app/core/bookmark.service.js, line 210 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917#-KlUGQyvTtNfSxklv8HH:-KlUTCde9ZWfz4d11pKJ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffc550c49444aa19cdf729e58efb96188fbff105/src/app/core/bookmark.service.js#L210)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

After discussion, determined duplicates OK.  Minor space inefficiency if people make weird maps, but we can live with it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1917)*

**Pull request merged**
