### PR TITLE
Fix animation for hovered geoSearch results

### LINKED ISSUE #1877: Complete text under search panel not visible in IE
Tested build :http://fgpv.cloudapp.net/demo/v1.7.0-rc2/prod/samples/index-fgp-en.htm

Related #1805 (Would be great to see the overflow when hovering or tabbing to the element (like in our filter panel). Or when selected, there is a popup like the hovering to show the complete text selection.)

Longer texts under "GeoSearch" are not  visible when you mouse over in IE.  In Chrome and Firefox, these texts were visible and appear as scrolling text.

image

### PR DESCRIPTION
**Pull request by barryytm**
## Description

As title

Closes #1877, #2247 

## Testing

Manually
## Documentation

NA
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2250)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2250)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2250#-:-KppTrnbTsCCAC8wu8mp:bnfp4nl)*

**Comment by milesap** [comment]
In IE the scroll is not working for me:

#### Chrome



#### IE



---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2250#-:-KppVqBLBjKvnXL0ONV8:b-grxv9y)*

**Comment by milesap** [comment]
Still some issues for me on IE:



---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2250#-:-KppoVPeJ3z8GaUv2CKY:byqz1w3)*

**Pull request closed without merging**
