### PR TITLE
Prepare for v2.4.0 relese

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Bump version tag in and update geoApi in package.json.  As well as update the link for JsDocs.

## Testing

Sanity check
## Documentation

JsDocs link.
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2791)

### CODE REVIEW

**Comment by milesap** [comment]
js/ts docs should not be committed, please remove

**Comment by james-rae** [comment]
Reviewed 1 of 310 files at r1.
Review status: 1 of 310 files reviewed, all discussions resolved (waiting on @milesap and @james-rae)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2791)*

**Comment by james-rae** [comment]
Reviewed 1 of 309 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @milesap)

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2791)*

**Comment by milesap** [comment]
:lgtm:

---

Reviewed 1 of 310 files at r1, 1 of 309 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2791#-:-LFSooc3D9w8q_Y8VkvJ:bnfp4nl)*

**Pull request merged**
