### PR TITLE
Zoom to Layer Bounding Box

### PR DESCRIPTION
**Pull request by cynngah**
#716 

toc.label.boundaryZoom and toc.tooltip.boundaryZoom needs french translation #765

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/916)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 464 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN1rt5pyGlMJp98SQsb:-KN1rt5pyGlMJp98SQsc:-1568478102) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a23e8fa036983a8e26ce52e612f029d38b54a5ba/src/app/geo/layer-registry.service.js#L464)):*
> ```JavaScript
>             }
> 
>             function zoomToBoundary(layerId) {
> ```

Needs block comment.

---

*[src/app/ui/toc/toc.service.js, line 250 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN1t4c44X1BbTayBtjp:-KN1t4c44X1BbTayBtjq:-1568478102) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a23e8fa036983a8e26ce52e612f029d38b54a5ba/src/app/ui/toc/toc.service.js#L250)):*
> ```JavaScript
>         }
> 
>         function zoomToBoundary(layer) {
> ```

Needs block comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by alyec** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 464 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN1rt5pyGlMJp98SQsb:-KN2JZ5wZaRmjIkCyjm5:1851782395) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a23e8fa036983a8e26ce52e612f029d38b54a5ba/src/app/geo/layer-registry.service.js#L464)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Needs block comment.
</details>
Also please include a note to fix the `_layer` reference (we should probably proxy the `fullExtent` property).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by cynngah** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/layer-registry.service.js, line 464 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN1rt5pyGlMJp98SQsb:-KN2RxRX0IQnxk9MH_QB:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a23e8fa036983a8e26ce52e612f029d38b54a5ba/src/app/geo/layer-registry.service.js#L464)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Also please include a note to fix the `_layer` reference (we should probably proxy the `fullExtent` property).
</details>
Done.

---

*[src/app/ui/toc/toc.service.js, line 250 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN1t4c44X1BbTayBtjp:-KN2Ry_pwQg-wyJMb4aZ:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a23e8fa036983a8e26ce52e612f029d38b54a5ba/src/app/ui/toc/toc.service.js#L250)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Needs block comment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 250 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN1t4c44X1BbTayBtjp:-KN2UMxkc7HJGliAXsQe:227549080) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a23e8fa036983a8e26ce52e612f029d38b54a5ba/src/app/ui/toc/toc.service.js#L250)):*
<details><summary><i>Previously, cynngah (Cynthia (Qingwei) Li) wrote…</i></summary>
> Done.
</details>
Can you change the naming to legendEntry instead of layer to be consistent with the terminology part of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/650 (I think everyone is okay with adopting the new terminology).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by AleksueiR** [comment]
Fails spectacularly when trying to zoom to the boundary of a file-based layer: 


---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-:-KN2Xdz9uhisFqRv0qPT:-713705639)*

**Comment by james-rae** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by cynngah** [comment]
Works spectacularly now

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/toc.service.js, line 250 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN1t4c44X1BbTayBtjp:-KN3_5OFAcRyOKhGnyG7:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a23e8fa036983a8e26ce52e612f029d38b54a5ba/src/app/ui/toc/toc.service.js#L250)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Can you change the naming to legendEntry instead of layer to be consistent with the terminology part of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/650 (I think everyone is okay with adopting the new terminology).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-:-KN3ZyDNLoyxaMJ-yomS:553729315)*

**Comment by AleksueiR** [comment]
Works spectacularly now as advertised! :lgtm: 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/geo/layer-registry.service.js, line 475 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN70ek6y-AtX8eIG2Ft:-KN70ek6y-AtX8eIG2Fu:-1100088156) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d504f79f16ec663ae52d8784d4f8f0d8c4614572/src/app/geo/layer-registry.service.js#L475)):*
> ```JavaScript
>                 let gextent;
> 
>                 if (!l.fullExtent.xmin) {
> ```

Please add some comments as to what is going on here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-:-KN70bBr346ve8Z4sUht:-2092057273)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Comment by AleksueiR** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/app/geo/layer-registry.service.js, line 475 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916#-KN70ek6y-AtX8eIG2Ft:-KN7T7qFwo3uESGP5-tI:-1834867277) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d504f79f16ec663ae52d8784d4f8f0d8c4614572/src/app/geo/layer-registry.service.js#L475)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Please add some comments as to what is going on here.
</details>
Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/916)*

**Pull request merged**
