### PR TITLE
Keep RCS from breaking the viewer

### PR DESCRIPTION
**Pull request by spencerwahl**
- file-only config on RCS failure (down-time etc.) plus a notification for users
- handles response from RCS on bad small-key(s)

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/506)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/core/config.service.js, line 122 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWbszHFL5pod54zxc:-KFjWbt-wrJQ_t-6RJPp:1943062304) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L122)):*
can you switch this to warn?

---

*[src/app/core/config.service.js, line 123 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWX6RTkfyAJqnasJm:-KFjWX6S82ijXnr2xkmU:-470516354) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L123)):*
const

---

*[src/app/core/config.service.js, line 310 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWscCtpmSrteLoVPO:-KFjWscDcF2ZoZB5BuoG:-120826363) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L310)):*
Seeing the `[0]` I think the RCS API could be cleaned up a bit to make it easier to work with, and this would probably be a good time to make any RCS changes before v2 goes to final release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/config.service.js, line 310 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWscCtpmSrteLoVPO:-KFjd5BMTUlUamNS6dzY:966895594) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L310)):*
Do we still have time to make changes to the schema? I would like to change visibility config values to boolean instead of "on/off" strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Comment by spencerwahl** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/config.service.js, line 122 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWbszHFL5pod54zxc:-KFjg4RDJEya113aRihM:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L122)):*
Done.

---

*[src/app/core/config.service.js, line 123 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWX6RTkfyAJqnasJm:-KFjg4CF2bKrHID7wzbF:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L123)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 310 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWscCtpmSrteLoVPO:-KFjjIBLlDjIyuJpOJID:-1726135829) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L310)):*
I'm fine with schema breaking changes as long as we're doing it before `1.x` releases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.service.js, line 310 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506#-KFjWscCtpmSrteLoVPO:-KFjsEnex_TzNU-6-pen:-633821629) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7203e291ce255dc01df794f2e3099705a6768112/src/app/core/config.service.js#L310)):*
:+1: Will do it tomorrow then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/506)*

**Pull request merged**
