### PR TITLE
Add dirty bit columns for English and French in the translation file

### PR DESCRIPTION
**Pull request by barryytm**
## Description

#1921 
Add the dirty bit columns in the translation file and ignore it when converting to JSON
## Testing

No, because it was mostly editing data

## Documentation

translations.csv
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1930)

### CODE REVIEW

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kld_6fB3cYyaTK6-38y:-Kld_6fB3cYyaTK6-38z:b-ke648q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
> ```JavaScript
>         csv({
>             noheader: true,
>             ignoreColumns: [0, 3, 5]
> ```

One-line change - nice :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-:-Kld_5UrlVLSHesalWs-:bnfp4nl)*

**Comment by james-rae** [comment]
So I guess the `ignoreColumns` needs to be adjusted depending on the number of languages added.
Do we have any type of manual / how-to documentation for adding languages?  If so, we should update this step.  If not, we should consider making such a page.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-:-KldZzX83p6jwY-0nzPx:b-r7rqzz)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by james-rae** [comment]
*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kld_6fB3cYyaTK6-38y:-Kld_gUWxcWdxjWBNswM:b-i2aexz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

One-line change - nice :+1: 
</blockquote></details>

Actually this might be a problem.  The script would be used in the Spanish version as well, and would need extra numbers.  Ideally, the plugin should adapt to any number of languages, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by james-rae** [comment]
*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kld_6fB3cYyaTK6-38y:-Klda3Wo7y8DLqJtoiPd:bjmr1gc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Actually this might be a problem.  The script would be used in the Spanish version as well, and would need extra numbers.  Ideally, the plugin should adapt to any number of languages, I think.
</blockquote></details>

Or do we just update the plug-in so it's inline with the csv??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kld_6fB3cYyaTK6-38y:-KldaOT44_ynKXupx5Rh:b-g65nct) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Or do we just update the plug-in so it's inline with the csv??
</blockquote></details>

Can the script read csv headers, get indexes of dirty columns, and ignore them? Need to name all dirty columns something simple and consistent though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kld_6fB3cYyaTK6-38y:-KldastE07QGpMQvs-kR:budzx77) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can the script read csv headers, get indexes of dirty columns, and ignore them? Need to name all dirty columns something simple and consistent though.
</blockquote></details>

I think we cold either add more columns to ignore (ie. [0, 3, 5, 7, ...]) or name all the titles to the same word since ignoreColumns works on the same title too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kld_6fB3cYyaTK6-38y:-Kldb07xYhO2V1YbZv2Y:b-t7hjay) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

I think we cold either add more columns to ignore (ie. [0, 3, 5, 7, ...]) or name all the titles to the same word since ignoreColumns works on the same title too.
</blockquote></details>

Same title as in all same column title, something like setting the title`officially reviewed` for the title(ie first row) on all the dirty bit columns.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-Kldk5qfKgpevQ-cHMZy:bgwt807) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
> ```CSV
> Language code (ISO 639-1),lang.code.code,en-CA,English Officially Reviewed,fr-CA,French Officially Reviewed
> ```

Actually, this is not the header column. There seem to be no headers in the translation file. So this should be 
```csv
Language code (ISO 639-1),lang.code.code,en-CA,1,fr-CA,1
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-Kldm1AsKpEv7dDHX9Qb:b-dt10u5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Actually, this is not the header column. There seem to be no headers in the translation file. So this should be 
```csv
Language code (ISO 639-1),lang.code.code,en-CA,1,fr-CA,1
```

</blockquote></details>

But when it converts to JSON in https://github.com/barryytm/fgpv-vpgf/blob/work/scripts/translations_plugin.js#L35.  It actually uses the first row to indicated whether it is French or English.  Should still set it to 1 then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-Kldmob-RbS-u_giQ6ZT:b-1uiyyq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

But when it converts to JSON in https://github.com/barryytm/fgpv-vpgf/blob/work/scripts/translations_plugin.js#L35.  It actually uses the first row to indicated whether it is French or English.  Should still set it to 1 then?
</blockquote></details>

Does it discard the first row? I think this is wrong. We need to add a valid headers row to the file or stop discarding the first one, which ever is lazier :D 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by milesap** [comment]
No docs about this, it should be added with this PR if possible (or open another issue so we dont forget)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldp1UJ7r3rWUm16jyS:-Kldp1UJ7r3rWUm16jyT:bkc9qub) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
> ```JavaScript
>         csv({
>             noheader: true,
>             ignoreColumns: [0, 3, 5]
> ```

Great use of ignoreColumns :+1:  Though since the number of languages can vary, this needs to be dynamic. 

pseudocode > `ignoreColumns: [0].push(...range(3, numOfLanguages, 2));`

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-KldoliNxU2SygZdvaCg:batuyab) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Does it discard the first row? I think this is wrong. We need to add a valid headers row to the file or stop discarding the first one, which ever is lazier :D 
</blockquote></details>

It does not discard the first row, `noheader: true` tells it to use first row as a data row.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-:-Kldq-saxT-xQQIT0bgH:b-k0p1u5)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-KldqMoZqpUxcOEJq06a:btgq4da) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

It does not discard the first row, `noheader: true` tells it to use first row as a data row.
</blockquote></details>

Perfect. That's solved.
Do we want to add headers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by barryytm** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/translations_plugin.js, line 31 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldp1UJ7r3rWUm16jyS:-KleKazeF5NCejqwyHFt:b-r18wje) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/scripts/translations_plugin.js#L31)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Great use of ignoreColumns :+1:  Though since the number of languages can vary, this needs to be dynamic. 

pseudocode > `ignoreColumns: [0].push(...range(3, numOfLanguages, 2));`
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/translations_plugin.js, line 78 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-KlsQZ2t6GzwN8IVA6JE:-KlsQZ2t6GzwN8IVA6JF:b-dnjoci) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc73511ac6252f36a2264cadc9f20a9fe935121f/scripts/translations_plugin.js#L78)):*
> ```JavaScript
>             if (rowNum === 0) {
>                 for (let i = 3; i < row.length; i++) {
>                     if (i % 2 === 1 && this.ignoreCol.indexOf(i) == -1) {
> ```

Please, use `===` instead of `==`.
Can you also add a comment block to this function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/translations_plugin.js, line 78 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-KlsQZ2t6GzwN8IVA6JE:-KlsaFDGb3Xj8cgbzq2E:b-kbp52i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bc73511ac6252f36a2264cadc9f20a9fe935121f/scripts/translations_plugin.js#L78)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, use `===` instead of `==`.
Can you also add a comment block to this function?
</blockquote></details>

:+1:  Perfect, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by milesap** [comment]
Prob. not related to this PR but language switching seems broken (`index-mobile.html` from english to french)

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-KlwunpmM-q7-2bAx3nB:beinq8q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Perfect. That's solved.
Do we want to add headers?
</blockquote></details>

I'd say we don't need them unless someone has a compelling reason for them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-:-KlwvCG1jJBJEtd8xdng:biav85k)*

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-Klxwgif9UqMjlAm6lcg:b-bk5ip0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I'd say we don't need them unless someone has a compelling reason for them.
</blockquote></details>

Works for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/translations.csv, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-Kldk5qfKgpevQ-cHMZx:-KlyIuNF-oypwiAgiq3-:bg7igkv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9b734d7ec2a6bc5637a46e33e6cde1a97d009059/src/locales/translations.csv#L1)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Works for me.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930)*

**Comment by AleksueiR** [comment]
@barryytm Please rebase.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-:-KlyOpFam1D_Ic8dLa7c:b-hncten)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1930#-:-KlyxqJqplJ7pAHrqjl4:bnfp4nl)*

**Pull request merged**
