### PR TITLE
Plug Slide Animation Fix

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/66)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 98 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66#-K27_z9pQWar763DS87v)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a69c7880ee8358fab9322dc30e7af44edd9c4f66/src/app/ui/common/plug-slide.animation.js#L98)):</sup>
Question for my personal knowledge. What is the (...args, null)?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 98 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66#-K27_z9pQWar763DS87v)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a69c7880ee8358fab9322dc30e7af44edd9c4f66/src/app/ui/common/plug-slide.animation.js#L98)):</sup>
It's ES6 spread: https://babeljs.io/docs/learn-es2015/#default-rest-spread
@alyec, is it used correctly here?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 98 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66#-K27_z9pQWar763DS87v)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a69c7880ee8358fab9322dc30e7af44edd9c4f66/src/app/ui/common/plug-slide.animation.js#L98)):</sup>
I believe so, I saw this and figured the args is for passing through the usual link function args and the null is just for setting the delta param but I was more or less skimming the code at that point.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/app/ui/common/plug-slide.animation.js, line 98 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66#-K27_z9pQWar763DS87v)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a69c7880ee8358fab9322dc30e7af44edd9c4f66/src/app/ui/common/plug-slide.animation.js#L98)):</sup>
I'll add some comments, I'm sure others will have the same question.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Comment by ec-dev** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/66)

**Pull request merged**
