### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ec-dev**
Basemap geoAPI & FGPV hookup

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/214)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/init-map.directive.js, line 35 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K809aGKgAi_ou6FPrC0:-K809aGKgAi_ou6FPrC1:-2112676050) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2d344bc57f1a745c484f4c5a43a4a844876a9ae/src/app/geo/init-map.directive.js#L35)):*
Can we move a call to `setupMap` inside the `buildMap` function? I understand these two will always be called together.

---

*[src/app/ui/basemap/basemap-item.directive.js, line 28 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K80BC43-nDbTz0V08rZ:-K80BC43-nDbTz0V08r_:1760064868) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2d344bc57f1a745c484f4c5a43a4a844876a9ae/src/app/ui/basemap/basemap-item.directive.js#L28)):*
We can dumb down this directive and remove `geoService` reference since the basemap-item shouldn't know about it anyway.

1/ Add `select: '&'` to the scope object here. This will bind a function passed from basemap.directive template to the `select` property on `self`.

---

*[src/app/ui/basemap/basemap-item.directive.js, line 45 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K80BsmGtGvpPmxFvvGg:-K80BsmGtGvpPmxFvvGh:-1109662622) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2d344bc57f1a745c484f4c5a43a4a844876a9ae/src/app/ui/basemap/basemap-item.directive.js#L45)):*
2/ cont.
remove `geoService` reference; we don't need it here anymore

---

*[src/app/ui/basemap/basemap-item.directive.js, line 48 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K80Bz3XGLdhNkljofr9:-K80Bz3XGLdhNkljofrA:-220373304) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2d344bc57f1a745c484f4c5a43a4a844876a9ae/src/app/ui/basemap/basemap-item.directive.js#L48)):*
3/ cont.
remove `self.select = select` since the function we pass to this directive is already bound to this property.

---

*[src/app/ui/basemap/basemap-item.directive.js, line 61 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K80C8DBX3wkYaCk9-9f:-K80C8DBX3wkYaCk9-9g:-861775026) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2d344bc57f1a745c484f4c5a43a4a844876a9ae/src/app/ui/basemap/basemap-item.directive.js#L61)):*
4/ cont.
Move `select` function to `basemap.directive.js`;

---

*[src/app/ui/basemap/basemap.directive.js, line 40 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K80CTnK1LPRp7Q67mvF:-K80CTnK1LPRp7Q67mvG:1970433199) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2d344bc57f1a745c484f4c5a43a4a844876a9ae/src/app/ui/basemap/basemap.directive.js#L40)):*
5/ cont
Add a `select` function to self here. This function will get a basemap object as an input. 
In this function: loop through other basemaps and deselect the currently active one; select the one passed in; call `geoService.setBasemap` with its id.

To have the basemap-item.directive call this select function on click, in `src\app\ui\basemap\basemap.html` on line 13 add __`select='select(basemap)'`__ to`rv-basemap-item` node.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 138 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K80QMazncApEUPgnheT:-K80QMazncApEUPgnheU:-1561354935) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/785efad25fe9a8f371548e4204b4e1d2ea5b8c78/src/app/geo/geo.service.js#L138)):*
i think you were typing a bower command with your cursor in your code editor

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by alyec** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/geo/geo.service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K801cgCMLr1EdeTjz9a:-K801cgCMLr1EdeTjz9b:421689184) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1c64d42a6b5bbfacdd1b72d50fccfa0dde785/src/app/geo/geo.service.js#L32)):*
can we rename to something like `selectBasemap` (`setX` generally means you pass in `X` for standard getters and setters)

---

*[src/app/geo/init-map.directive.js, line 40 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K802-44xEoFBTtBiIyk:-K802-44xEoFBTtBiIyl:-590394646) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1c64d42a6b5bbfacdd1b72d50fccfa0dde785/src/app/geo/init-map.directive.js#L40)):*
This can probably move this into geoService (e.g. calling from `buildMap`).

---

*[src/app/ui/basemap/basemap.directive.js, line 88 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K803zamko851zJg6zOS:-K803zamko851zJg6zOT:-631260153) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42b1c64d42a6b5bbfacdd1b72d50fccfa0dde785/src/app/ui/basemap/basemap.directive.js#L88)):*
const (and others below) -- given that all this code might change later based on the new basemaps definition I don't know if it's worth any effort changing it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r3.
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by ec-dev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/basemap/basemap-item.directive.js, line 28 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214#-K80BC43-nDbTz0V08rZ:-K80_VR5Sw1F7_UfLQYh:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2d344bc57f1a745c484f4c5a43a4a844876a9ae/src/app/ui/basemap/basemap-item.directive.js#L28)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by james-rae** [comment]
Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by james-rae** [comment]
Reviewed 2 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by james-rae** [comment]
Reviewed 1 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/214)*

**Pull request merged**
