### PR TITLE
Switch css animations to js

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/129)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/common/plug-slide.animation.js, line 156 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129#-K69k74cUzWdqCnntyaE:-K69k74cUzWdqCnntyaF:2112296041) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2a16ec8ebaeb09e11f650c125605c33939c62ce/src/app/ui/common/plug-slide.animation.js#L156)):*
Maybe add a comment why we switched to the first div and store the selector in a const for reuse - it's referenced three times in the file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129)*

**Comment by AleksueiR** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129#-:-K69odwFXRpFiQyE7EUN:-1868698381)*

**Comment by spencerwahl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/app/ui/common/plug-slide.animation.js, line 156 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129#-K69k74cUzWdqCnntyaE:-K69ofvTaBnLoXNpioGE:-499146009) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a2a16ec8ebaeb09e11f650c125605c33939c62ce/src/app/ui/common/plug-slide.animation.js#L156)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/129)*

**Pull request merged**
