### PR TITLE
Hover tips

### PR DESCRIPTION
**Pull request by alyec**
Rebased version of #1569 with a clean commit list

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1584)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 3 of 7 files at r1, 4 of 7 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1584)*

**Comment by AleksueiR** [comment]
I approve James' half of this PR. :)

---

Reviewed 3 of 7 files at r2, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1584#-:-KaK7iYnwp92Mm7hnHGb:b-jyos05)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1584)*

**Comment by AleksueiR** [comment]
:lgtm: Demo still seems to work.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1584#-:-KaN6O5HOk_nRnZoNTt4:btagg1x)*

**Pull request merged**
