### PR TITLE
feat(ui): enhance layer tree

### PR DESCRIPTION
**Pull request by AleksueiR**
adds layer group toggle directive;
adds animation to layer group toggle;
replaces font icons with svg ones;

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/53)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 9 of 19 files at r1.
Review status: 8 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by jolevesq** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/ui/common/morph.directive.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KyELuCqa7UG8d-1Zb)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/common/morph.directive.js#L2)):</sup>
Arrow function


---

<sup>**[src/app/ui/mapnav/mapnav-button.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzQJY3vffR9-H9piP)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav-button.html#L1)):</sup>
spaces after, before curly brackets


---

<sup>**[src/app/ui/mapnav/mapnav-button.html, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzOcMCo3sHl8B3xUI)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav-button.html#L3)):</sup>
spaces after, before curly brackets


---

<sup>**[src/app/ui/mapnav/mapnav.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzdikMyDCz-w_HPiF)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav.service.js#L1)):</sup>
Arrow function


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by ec-dev** [comment]
Reviewed 3 of 19 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by alyec** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[.gitignore, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1Kuxj60CiZkYtCLWNS)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/.gitignore#L15)):</sup>
Why are we keeping 3rd party packages under `/src` ?  Can we keep them under `/lib` as we have them right now?


---

<sup>**[src/app/ui/common/toggle-slide.animation.js, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KyQZYcl5rvw4AkkuK)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/common/toggle-slide.animation.js#L7)):</sup>
Maybe add a comment to explain what that `.get` is doing and why it's not a normal function call.


---

<sup>**[src/app/ui/common/toggle-slide.animation.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1Kyrd1XzmPhK37JEnm)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/common/toggle-slide.animation.js#L76)):</sup>
Doesn't this also set the height?  If not maybe include a comment about what it's doing.


---

<sup>**[src/app/ui/mapnav/mapnav-button.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzFiB7QNB1PifXy4J)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav-button.html#L4)):</sup>
Need double brace spacing in this file


---

<sup>**[src/app/ui/toc/layer-group-toggle.directive.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1L-AV2UIHpfgK7viGM)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/toc/layer-group-toggle.directive.js#L11)):</sup>
Can you expand on the `bindToController` and why it's needed for this directive (i.e. why is this directive tightly coupled to the controller).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/ui/common/morph.directive.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KyELuCqa7UG8d-1Zb)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/common/morph.directive.js#L2)):</sup>
Done.


---

<sup>**[src/app/ui/mapnav/mapnav-button.html, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzQJY3vffR9-H9piP)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav-button.html#L1)):</sup>
Done.


---

<sup>**[src/app/ui/mapnav/mapnav-button.html, line 3 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzOcMCo3sHl8B3xUI)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav-button.html#L3)):</sup>
Done.


---

<sup>**[src/app/ui/mapnav/mapnav-button.html, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzFiB7QNB1PifXy4J)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav-button.html#L4)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by ec-dev** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[.gitignore, line 15 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1Kuxj60CiZkYtCLWNS)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/.gitignore#L15)):</sup>
Agree, no reason. I just copied the way the sample jspm project was set up.
I think this is done mostly to allow serving just the `src` folder and have all libraries in there.


---

<sup>**[src/app/ui/common/toggle-slide.animation.js, line 7 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KyQZYcl5rvw4AkkuK)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/common/toggle-slide.animation.js#L7)):</sup>
Removed `get`.

It was broken actually. This library's bower package is at 1.0.0 version while the project itself is at 1.1.1. In 1.1.1 it provides a `get` function on the return to calculate easing values. Here's why they added get: https://github.com/gre/bezier-easing/issues/20


---

<sup>**[src/app/ui/common/toggle-slide.animation.js, line 76 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1Kyrd1XzmPhK37JEnm)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/common/toggle-slide.animation.js#L76)):</sup>
Done.


---

<sup>**[src/app/ui/mapnav/mapnav.service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1KzdikMyDCz-w_HPiF)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/mapnav/mapnav.service.js#L1)):</sup>
Done.


---

<sup>**[src/app/ui/toc/layer-group-toggle.directive.js, line 11 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53#-K1L-AV2UIHpfgK7viGM)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/140080b4cb28f9f9e9a05f0707fd83a675e0bece/src/app/ui/toc/layer-group-toggle.directive.js#L11)):</sup>
This controller doesn't do anything yet, and I don't yet know if it needs to do anything. I just kept the boilerplate code.
Generally, `bindToController` is used to avoid binding things to the scope as scope will be removed in Angular 2.0.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Comment by jolevesq** [comment]
Reviewed 3 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/53)

**Pull request merged**
