### PR TITLE
fix(bug): zoom to feature is present when layer is hidden and zoom to…

### LINKED ISSUE #1137: "zoom to feature" when layer is out of scale does not zoom to the proper zoom level
When a user click "zoom to feature" from the data grid and the layer is out of scale this is not the expected behaviour. The first time the user click, the layer is zoom to the maximum level and the second time to the expected level. It should go to the minimum level the first time or the default zoom level if it is in the range.

Open datagrid
screen shot 2016-09-01 at 1 54 26 pm

When user click a first time to zoom to feature
screen shot 2016-09-01 at 1 54 36 pm

When user click a second time to zoom to feature
screen shot 2016-09-01 at 1 54 47 pm

### PR DESCRIPTION
**Pull request by jolevesq**
… feature does not zoom to proper zoom level

Closes #1137, #1171

---

This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1309)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/details/details.directive.js, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVAulkApVSSjADeiEkH:-KVAulkApVSSjADeiEkI:bgkkgzl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/ui/details/details.directive.js#L89)):*
> ```JavaScript
>             }
> 
>             // get legend entry from the requester to watch modification on visiiblity for sublayer
> ```

typo: visibility

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309)*

**Comment by AleksueiR** [comment]
No layers are loaded in the [Demo](http://fgpv.cloudapp.net/demo/users/jolevesq/1171-zoom-feature/samples/index-one.html). Probably because this is not rebased on develop.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVAwwyiWDP_x8ZHG5gz:bwozn7f)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 459 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVBBZ_0t3nv7ashqO6u:-KVBBZ_0t3nv7ashqO6v:b-3sgc8c) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/geo/layer-registry.service.js#L459)):*
> ```JavaScript
>                 // the layer to zoom to the maximum scale allowed for the layer. In this case, zoomIn must be
>                 // always false
>                 zoomIn = (zoomGraphic) ? false : zoomIn;
> ```

Can't check if this is working cause the demo is broken.

---

*[src/app/ui/details/details.directive.js, line 88 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVB9qEehXje44e4URfY:-KVB9qEehXje44e4URfZ:bo3oi2h) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/ui/details/details.directive.js#L88)):*
> ```JavaScript
>                     item.data.map(d => d.oid));
>             }
> ```

`$watch`es affect performance and I always suggest avoiding them if possible. There is a `featureIdx` property stored on the `requester` object which is the feature's index of its sublayer. Using it, we can get feature's direct `legendEntry` object and store in on `self` in `details-record-esrifeature.directive.js` file:
```js
self.directLegendEntry = self.requester.layerRec.legendEntry.items.find(le => 
    le.featureIdx === self.requester.featureIdx);
```

And reference it in `details-record-esrifeature.html` file:
```html
ng-disabled="!self.requester.layerRec.visible || !self.directLegendEntry.options.visibility.value">
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309)*

**Comment by jolevesq** [comment]
Humm... work on my local copy. I did a rebase just before my PR.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/ui/details/details.directive.js, line 88 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVB9qEehXje44e4URfY:-KVBR4sFvRufos-8C5eJ:btwjusd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/ui/details/details.directive.js#L88)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> `$watch`es affect performance and I always suggest avoiding them if possible. There is a `featureIdx` property stored on the `requester` object which is the feature's index of its sublayer. Using it, we can get feature's direct `legendEntry` object and store in on `self` in `details-record-esrifeature.directive.js` file:
> ```js
> self.directLegendEntry = self.requester.layerRec.legendEntry.items.find(le => 
>     le.featureIdx === self.requester.featureIdx);
> ```
> 
> And reference it in `details-record-esrifeature.html` file:
> ```html
> ng-disabled="!self.requester.layerRec.visible || !self.directLegendEntry.options.visibility.value">
> ```
> 
</details>
I tried something like that but  I don't why it work only the first time. It was not updated when layer changed . I will give another try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVBQPBBrv7LlZMIMYiY:bul35hs)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 459 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVBBZ_0t3nv7ashqO6u:-KVBkmea4addm4B6Xroq:b-1vjshy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/geo/layer-registry.service.js#L459)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Can't check if this is working cause the demo is broken.
</details>
Repair the PR you can test now

---

*[src/app/ui/details/details.directive.js, line 88 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVB9qEehXje44e4URfY:-KVBklKdK1LwPvG-vzEn:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/ui/details/details.directive.js#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> I tried something like that but  I don't why it work only the first time. It was not updated when layer changed . I will give another try.
</details>
Done.

---

*[src/app/ui/details/details.directive.js, line 89 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVAulkApVSSjADeiEkH:-KVBkkpEckrNtWdcBhjb:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/ui/details/details.directive.js#L89)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo: visibility
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309)*

**Comment by alyec** [comment]
Confirmed that demo is working, but should we change the tooltip when zoom to is disabled?

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVPgb5pHkXt7eeZdG3r:b-g35ufo)*

**Comment by AleksueiR** [comment]
There should be any tooltip if the button is disabled, no?  I don't get any:



---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 459 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-KVBBZ_0t3nv7ashqO6u:-KVPl_rIb8MtAY3USCVf:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/eaea9215340c2b2d1f33f22f344ecf6035309acf/src/app/geo/layer-registry.service.js#L459)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary>
> Repair the PR you can test now
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVPlcncvxwerc9gl022:b-g5nk82)*

**Comment by jolevesq** [comment]
Same for me, no tooltip.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVPnX9efVVzkoW7TtZB:brfaglu)*

**Comment by alyec** [comment]
On FF 49 (sorry cursor doesn't show in this screenshot)

tooltip-on-disabled

If it works for both of you on Firefox as well I'm okay with leaving this as some obscure case.

**Comment by AleksueiR** [comment]
Yeap, tooltips show up in Firefox. I think this can be moved into a separate issue.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVPr8BmqRpk0b6eqEiD:b3tvqla)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVPvAlEzzQVUI1Y7KMi:bnfp4nl)*

**Comment by AleksueiR** [comment]
Created an issue for missing/extra tooltips: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1313

@jolevesq please rebase.

---

Reviewed 1 of 4 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVPx6xTU1F6zrGFVDa6:b33uq7v)*

**Comment by jolevesq** [comment]
Rebase done!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309#-:-KVPz6_zxlSURIqZjG7b:b5pg8a0)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1309)*

**Pull request merged**
