### PR TITLE
Fix console error relating to suggestions when Geo-search was disabled 

### PR DESCRIPTION
**Pull request by barryytm**
## Description

#2005, Fix console error relating to suggestions when Geo-search was disabled

## Testing

Manually

## Documentation

None
## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2012)

### CODE REVIEW

**Comment by milesap** [comment]
The error is gone, but the search is still not disabled. I am still able to type in the search box. The search icon should not be visible in this case, and the user should not be able to access the search box. 



---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2012#-:-KnEnP6RoRebUnD_zWox:b-8i3vyr)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2012)*

**Comment by james-rae** [comment]
Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2012)*

**Comment by milesap** [comment]
:lgtm: tested and womm now as well :+1: 

---

Reviewed 1 of 3 files at r1, 6 of 7 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2012#-:-KnFerZn2KhZHpSG3ViK:berv1p5)*

**Pull request merged**
