### PR TITLE
feat(core): add material design and community iconsets

### PR DESCRIPTION
**Pull request by AleksueiR**
Icon source: https://github.com/nkoterba/material-design-iconsets

Read more here: https://material.angularjs.org/HEAD/api/directive/mdIcon

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/45)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 18 of 18 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Comment by jolevesq** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/app/core/core.run.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45#-K1B4NXlZZkvzRGA63Gg)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b380ef411e795e3f9bdc6029f01aabb9d4de355e/src/app/core/core.run.js#L2)):</sup>
You use the arrow function in other files why not here?


---

<sup>**[src/app/core/core.run.js, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45#-K1B4Vp7X2qTw58jQWAX)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b380ef411e795e3f9bdc6029f01aabb9d4de355e/src/app/core/core.run.js#L29)):</sup>
One parameter,  remove parenthesis.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Comment by AleksueiR** [comment]
Review status: 17 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/app/core/core.run.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45#-K1B4NXlZZkvzRGA63Gg)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b380ef411e795e3f9bdc6029f01aabb9d4de355e/src/app/core/core.run.js#L2)):</sup>
Hm, I wasn't even making changes to this file. Done.


---

<sup>**[src/app/core/core.run.js, line 29 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45#-K1B4Vp7X2qTw58jQWAX)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b380ef411e795e3f9bdc6029f01aabb9d4de355e/src/app/core/core.run.js#L29)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/core.run.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45#-K1B4NXlZZkvzRGA63Gg)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b380ef411e795e3f9bdc6029f01aabb9d4de355e/src/app/core/core.run.js#L2)):</sup>
Do you know why it was in the PR?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/core.run.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45#-K1B4NXlZZkvzRGA63Gg)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b380ef411e795e3f9bdc6029f01aabb9d4de355e/src/app/core/core.run.js#L2)):</sup>
Empty line change :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/core/core.run.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45#-K1B4NXlZZkvzRGA63Gg)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b380ef411e795e3f9bdc6029f01aabb9d4de355e/src/app/core/core.run.js#L2)):</sup>
 Your fault for playing with whitespace


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/45)

**Pull request merged**
