### PR TITLE
Date filter bugs squashed

### PR DESCRIPTION
**Pull request by james-rae**
## Description
Closes 
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1601
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1608
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1597

## Testing
WOMM

## Documentation
Added a missing jsdoc

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1612)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612)*

**Comment by AleksueiR** [comment]
Demo is not deployed. Can't test.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612#-:-KaxATzEGZ1cViKPvFUb:bakec8m)*

**Comment by AleksueiR** [comment]
Anyone know why there is no demo?

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612#-:-KaxGSrVkMXAt-PyKmUZ:b-mdafg5)*

**Comment by james-rae** [comment]
I've re-done travis and still no treats.  You can pull on trust then test develop :elephant: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612#-:-KaxG_gz3D48VsQ8h3yl:blno258)*

**Comment by james-rae** [comment]
Demo is working

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612#-:-KaxS2hWgDL6qoNhtgrm:b-ig1t9)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612#-:-KbAUpAW1Xh1h6msMFtF:bnfp4nl)*

**Comment by milesap** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612)*

**Comment by alyec** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1612)*

**Pull request merged**
