### PR TITLE
fix(scale): scale wont move after projection switch

### PR DESCRIPTION
**Pull request by jolevesq**
## Description

Scale bar is not at the right place after switching basemap. To achieve this it was not easy because there something wrong when the scalebar is on the left side. Application always force it back to the left. I we use bottom-right inside the scalebar init, there is no need for almost 2/3 of the code from this PR.

## Testing

Chrome, FF

## Documentation

Inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1872)

### CODE REVIEW

**Comment by milesap** [comment]
I'll take this under v1.7.0 since that is the last release. Will review once build passes (restarted)

**Comment by AleksueiR** [comment]
Waiting for the demo.

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-:-KjIN0B0sS5frNkCb65G:bbruvpp)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by milesap** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 33 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLO_Sjp9SKTA1_xvJ:-KjNLO_Sjp9SKTA1_xvK:b-eijlek) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/bower.json#L33)):*
> ```JSON
>     "dotjem-angular-tree": "~0.2.1",
>     "file-saver": "^1.3.3",
>     "geoapi": "http://fgpv.cloudapp.net/demo/gapi/geoapi-1.1.5.tgz",
> ```

Use  https://github.com/fgpv-vpgf/geoApi/raw/v1.1.5/dist/geoapi-1.1.5.tgz

---

*[package.json, line 91 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNMBtDfEiYCKJo69Cn:-KjNMBtDfEiYCKJo69Co:b-chm726) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/package.json#L91)):*
> ```JSON
>   },
>   "scripts": {
>     "postinstall": "rm -r -f lib/angular-dragula && bower install --allow-root && git apply fix-ui-delay-drag-start.patch",
> ```

Curious why this is needed

---

*[src/app/geo/init-map.directive.js, line 24 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNM8bHX3rctV7-wB5q:-KjNM8bILj4JJLRlGQ_j:b-rfswjp) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/src/app/geo/init-map.directive.js#L24)):*
> ```JavaScript
>     // jshint maxparams:12
>     function rvInitMap($rootScope, geoService, events, storageService, mapService, gapiService, $rootElement,
>         $interval, globalRegistry, animationService, stateManager, $timeout) {
> ```

:+1: for `$timeout`

---

*[src/app/geo/init-map.directive.js, line 82 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLvOZdc-8W1TDkVDT:-KjNLvOZdc-8W1TDkVDU:bbfhtyy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/src/app/geo/init-map.directive.js#L82)):*
> ```JavaScript
>                         // and we don't need to wait to move it to the right place. Even when application start, if scalebar is on the left, sometime the animation is not done
>                         // for light map there is no problem but for heavy map there is a delay before we can set the scalebar and we can rely on map-update (fire multiple time too fast)
>                         // TODO: investigate what is going on between left and right because if right, no need for most of the following code and it is faster.
> ```

Maybe putting it on the right is better if all this is avoided? Do you think it's worth keeping on the left?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by milesap** [comment]
Moving to v2.0.0 support so v1.7.0 can ship out

**Comment by jolevesq** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[bower.json, line 33 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLO_Sjp9SKTA1_xvJ:-KjsPPl1efGDSrlR0XsC:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/bower.json#L33)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Use  https://github.com/fgpv-vpgf/geoApi/raw/v1.1.5/dist/geoapi-1.1.5.tgz
</blockquote></details>

Done.

---

*[package.json, line 91 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNMBtDfEiYCKJo69Cn:-KjsPRHj9tjqe9IADzmX:b4fjjy7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/package.json#L91)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Curious why this is needed
</blockquote></details>

oups! forgot to remove it... It is use when you want to build on a Mac

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by jolevesq** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/geo/init-map.directive.js, line 82 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLvOZdc-8W1TDkVDT:-KjsQk4MYeXI9o9LuFI6:bsejpau) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/src/app/geo/init-map.directive.js#L82)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Maybe putting it on the right is better if all this is avoided? Do you think it's worth keeping on the left?
</blockquote></details>

Maybe. If we put it on the right we will not have to move it at all. The only concern is you will end up with map navigation control, attribution, scale and coordinates on the same side of the map. We need to check if it will get too crowded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by milesap** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/geo/init-map.directive.js, line 82 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLvOZdc-8W1TDkVDT:-KlOWziF2tpiZ4cddprl:bybm484) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/src/app/geo/init-map.directive.js#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Maybe. If we put it on the right we will not have to move it at all. The only concern is you will end up with map navigation control, attribution, scale and coordinates on the same side of the map. We need to check if it will get too crowded.
</blockquote></details>

@aleksueir and I are ok with this being on the right side to avoid all this manipulation. I was thinking:
- Move map attribution to the left side (it can be behind the legend panel)
- Possibly move ESRI attribution to the left as well (up to you)

---

*[package.json, line 91 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNMBtDfEiYCKJo69Cn:-KlOXgn3GtDBEfy3cK2-:b-salkum) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/package.json#L91)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

oups! forgot to remove it... It is use when you want to build on a Mac
</blockquote></details>

Ah :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by milesap** [comment]
Please rebase or update status if there are issues

---

Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[bower.json, line 33 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLO_Sjp9SKTA1_xvJ:-Klx-ZKKeALNvUG1wzPK:bg3wgk6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/bower.json#L33)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`bower.json` is now gone :smiley: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-:-Klx-gjMIcppcBs1M5Rf:b-svr6x0)*

**Comment by jolevesq** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/geo/init-map.directive.js, line 82 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLvOZdc-8W1TDkVDT:-Km7pZPf33Y19HEZHdEW:b-la5cuo) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/src/app/geo/init-map.directive.js#L82)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

@aleksueir and I are ok with this being on the right side to avoid all this manipulation. I was thinking:
- Move map attribution to the left side (it can be behind the legend panel)
- Possibly move ESRI attribution to the left as well (up to you)
</blockquote></details>

Agree, I will test this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by jolevesq** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/geo/init-map.directive.js, line 24 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNM8bHX3rctV7-wB5q:-KmCxiBBKEMQ0INnFzUi:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/src/app/geo/init-map.directive.js#L24)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

:+1: for `$timeout`
</blockquote></details>

Done.

---

*[src/app/geo/init-map.directive.js, line 82 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-KjNLvOZdc-8W1TDkVDT:-KmCxj4vIzTcxLd6LO4F:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2a7ae588d4c60a9d43d5cb1b1d757e547a5bebb4/src/app/geo/init-map.directive.js#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Agree, I will test this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by james-rae** [comment]
Reviewed 7 of 9 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by AleksueiR** [comment]
:lgtm:
Are we okay with attribution being a little bit obscured by the expanded main panel?

---

Reviewed 7 of 9 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-:-KmSJ02ph8bzOAkmtzdW:b-mscqr1)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872)*

**Comment by jolevesq** [comment]
I am good with it. This is not something you have to read all the time. You can close the menu to see it all

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-:-KmSMTFGY9KjDHwe3TPt:b-hl3qw5)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1872#-:-KmSQHtKXqNWMtp01Z48:bnfp4nl)*

**Pull request merged**
