### PR TITLE
Api 00

### PR DESCRIPTION
**Pull request by milesap**
## Description
- Adds ability to load map via the API directly
    - As a result, `app-seed` has been modified to support both normal and API loading
- Converts our schema JSON to a typescript definition file on webpack
- adds an `XYBounds` class
- namespaces `XY` and `XYBounds` into one geometry module

`core.run` has been modified to support both the current API, while at the same time ignoring the new API. This is to avoid branching away from develop at this stage.

## Testing
`api.html` is a sample page without any FGPV files or elements. It loads jquery and the `self-loader.js` extension which starts up the map. The `hello-world.js` extension now provides an annoying confirmation box when you double click on the map.

## Documentation
Yes, everywhere

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2466)

### CODE REVIEW

**Comment by milesap** [comment]
- Fixed build issue, traced to `app-seed` which I converted to TS
- Angular type definitions added
- Slight change change to tsconfig (allow no export defaults) mostly so jQuery `$` has a proper definition

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-:-KyWc4ZMfMWIEQahHDQ1:b-p4di2c)*

**Comment by james-rae** [comment]
Reviewed 15 of 21 files at r1, 6 of 6 files at r2.
Review status: 20 of 21 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[api/src/geometry.ts, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0EqcFLxGXbPw3P7E-:-Kz0EqcFLxGXbPw3P7E0:b-rny1cw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L11)):*
> ```XML
> 
>     constructor(x: number, y: number) {
>         if (x > 180 || x < -180) {
> ```

Possible we want to support wrap-around conventions?  E.g. if someone supplies `+200`, we convert it internally to `-160`, etc.  @alyec  thoughts?

---

*[api/src/geometry.ts, line 124 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0I3m8VHfQrl2-7p9e:-Kz0I3m8VHfQrl2-7p9f:bsm1nql) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L124)):*
> ```XML
> 
> export interface XYLiteral {
>     0: number,
> ```

Maybe it's just me not understanding typescript; is object properties that are integers good?

---

*[src/app/core/config.class.js, line 1877 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0JWlxs9BUF8C_X3tU:-Kz0JWlyt095S4G1p7Ql:b2ni78k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/25b147a1b1347ee3fa887dd13f1c2ed215895a81/src/app/core/config.class.js#L1877)):*
> ```JavaScript
>                     const originalCenterAt = instance.centerAt;
>                     instance.centerAt = function() {
>                         subscriber.next(new XY(arguments[0].y, arguments[0].x));
> ```

lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by james-rae** [comment]
Reviewed 1 of 21 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[api/src/geometry.ts, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0EqcFLxGXbPw3P7E-:-Kz3hu93FF-2OHMAzZqW:b-k963r4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L11)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Possible we want to support wrap-around conventions?  E.g. if someone supplies `+200`, we convert it internally to `-160`, etc.  @alyec  thoughts?
</blockquote></details>

I like the idea. My question would be - do we simply do the conversion within the API (easy), or instead support it as an additional projection? Currently using `4326`, what would be the projection for only positive degrees? 

---

*[api/src/geometry.ts, line 124 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0I3m8VHfQrl2-7p9e:-Kz3jvQC4tmMkwi8QI6-:b5gkhye) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L124)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Maybe it's just me not understanding typescript; is object properties that are integers good?
</blockquote></details>

In typescript this translates to an array (which in JS is an object) with a length of exactly two, both being numbers. Anything else would not be an `XYLiteral`. 

---

*[src/app/core/config.class.js, line 1877 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0JWlxs9BUF8C_X3tU:-Kz3kqQo5vELAA69xi9D:b-nk8b0x) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/25b147a1b1347ee3fa887dd13f1c2ed215895a81/src/app/core/config.class.js#L1877)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lol
</blockquote></details>

Not sure this is good or bad, I assume lol is your highest compliment? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by james-rae** [comment]
*[api/src/geometry.ts, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0EqcFLxGXbPw3P7E-:-Kz4JU7jJeCa_D2SqbZ0:b-icyak1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L11)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

I like the idea. My question would be - do we simply do the conversion within the API (easy), or instead support it as an additional projection? Currently using `4326`, what would be the projection for only positive degrees? 
</blockquote></details>

I think it would just be an internal conversion. It's more someone has been given co-ords in degrees east instead of degrees west.  They won't want to have to work with other projections.
Also note it can go the other way (e.g. `-210` -> `150`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by milesap** [comment]
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[api/src/geometry.ts, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0EqcFLxGXbPw3P7E-:-Kz5A-slsX4p9xOqG1Qr:b-54b6gg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L11)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I think it would just be an internal conversion. It's more someone has been given co-ords in degrees east instead of degrees west.  They won't want to have to work with other projections.
Also note it can go the other way (e.g. `-210` -> `150`)
</blockquote></details>

Added the conversion :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by james-rae** [comment]
*[api/src/geometry.ts, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0EqcFLxGXbPw3P7E-:-Kz5D3Dr7_C6xg-7f-If:berfe7p) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L11)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Added the conversion :+1: 
</blockquote></details>

Hate to do this...but there is no wrap-around on the Y axis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by milesap** [comment]
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[api/src/geometry.ts, line 11 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz0EqcFLxGXbPw3P7E-:-Kz5DfRje1A-8NxdCAl7:b-4zw8vz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4c9caea60da07e5e46bbf395718dcb36a4d28d74/api/src/geometry.ts#L11)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Hate to do this...but there is no wrap-around on the Y axis
</blockquote></details>

All good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by AleksueiR** [comment]
Reviewed 15 of 21 files at r1, 6 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[api/src/geometry.ts, line 14 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz9-NmsE5KA-5vjiOwh:-Kz9-NmsE5KA-5vjiOwi:b2p1cvy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6ce18ae360f58550bfd088858f1bcb4d63a1665f/api/src/geometry.ts#L14)):*
> ±180°

fancy :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[api/src/geometry.ts, line 14 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466#-Kz9-NmsE5KA-5vjiOwh:-Kz91ivesLPwsjuHujet:bbojkbl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6ce18ae360f58550bfd088858f1bcb4d63a1665f/api/src/geometry.ts#L14)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

> ±180°

fancy :+1: 
</blockquote></details>

:tophat: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2466)*

**Pull request merged**
