### PR TITLE
feat(ui): add icon to close left-side menu

### PR DESCRIPTION
**Pull request by milesap**
Double chevron icon appears in top right corner of left-side menu. Moved marker image source to config file. Minor changes to styling for improved appearance; removed gradient and increased width to 320px.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/579)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_app-menu.scss, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKfJ2d0y9LI32yBS9k:-KHKfJ2d0y9LI32yBS9l:5058373) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d1c06c34c393dcaa6b021321f6c5d045cadd9d7f/src/content/styles/modules/_app-menu.scss#L52)):*
> ```SCSS
> 
>             }
>             
> ```

Please trim the extra whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/content/styles/modules/_app-menu.scss, line 52 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKfJ2d0y9LI32yBS9k:-KHKphL6__H_KRBgouu8:677588487) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d1c06c34c393dcaa6b021321f6c5d045cadd9d7f/src/content/styles/modules/_app-menu.scss#L52)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Please trim the extra whitespace.</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/app/ui/sidenav/sidenav.html, line 7 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKorKLzy-kDRqPJ-Oi:-KHKorKLzy-kDRqPJ-Oj:-1352341931) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2099ee0344d394d15f5489445053770a7a0d2bc2/src/app/ui/sidenav/sidenav.html#L7)):*
> ```HTML
>             <md-icon md-svg-src="navigation:chevron_left"></md-icon>
>         </md-button>
>     </md-button>
> ```

Buttons should not be generally added inside other buttons.

Instead of overlapping two icons, use `community:chevron-double-left`.
```html
<md-button class="md-icon-button black rv-button-32 minimize-button" ng-click="self.minimize()">
     <md-icon md-svg-src="community:chevron-double-left"></md-icon>
</md-button>
```

---

*[src/content/styles/modules/_app-menu.scss, line 5 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKoZjJL1M5c50oxLNW:-KHKoZjJL1M5c50oxLNX:-1521925403) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2099ee0344d394d15f5489445053770a7a0d2bc2/src/content/styles/modules/_app-menu.scss#L5)):*
> ```SCSS
>     md-sidenav {
>         &.site-sidenav {
>             width: 320px;
> ```

Keep the original size, please.

---

*[src/content/styles/modules/_app-menu.scss, line 40 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKogD0S86LgA8daGOa:-KHKogD0S86LgA8daGOb:-308792062) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2099ee0344d394d15f5489445053770a7a0d2bc2/src/content/styles/modules/_app-menu.scss#L40)):*
> ```SCSS
>                 padding: 0 0 16px;
>                 margin: 0 auto;
>                 border-bottom-color: $primary-color-light;
> ```

And keep the gradient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by milesap** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/sidenav/sidenav.html, line 7 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKorKLzy-kDRqPJ-Oi:-KHUVGMdDjmUayt9rlX9:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2099ee0344d394d15f5489445053770a7a0d2bc2/src/app/ui/sidenav/sidenav.html#L7)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Buttons should not be generally added inside other buttons.
> 
> Instead of overlapping two icons, use `community:chevron-double-left`.
> ```html
> <md-button class="md-icon-button black rv-button-32 minimize-button" ng-click="self.minimize()">
>      <md-icon md-svg-src="community:chevron-double-left"></md-icon>
> </md-button>
> ```</details>
complete

---

*[src/content/styles/modules/_app-menu.scss, line 5 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKoZjJL1M5c50oxLNW:-KHU_wIvD_WFsArN4eZU:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2099ee0344d394d15f5489445053770a7a0d2bc2/src/content/styles/modules/_app-menu.scss#L5)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> Keep the original size, please.</details>
complete

---

*[src/content/styles/modules/_app-menu.scss, line 40 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579#-KHKogD0S86LgA8daGOa:-KHU_xjHSEn_Rco3Ck_u:1589014846) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2099ee0344d394d15f5489445053770a7a0d2bc2/src/content/styles/modules/_app-menu.scss#L40)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> And keep the gradient.</details>
complete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/579)*

**Pull request merged**
