### PR TITLE
Detail panel

### PR DESCRIPTION
**Pull request by jolevesq**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/709)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details.directive.js, line 128 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709#-KJLW263sB3A0qhXBL63:-KJLW263sB3A0qhXBL64:1887829498) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7aeeb908ece310804ee52ff00ba53cd8f9ca9e4b/src/app/ui/details/details.directive.js#L128)):*
> ```JavaScript
>                     selectedItem = item;
>                 }
>             });
> ```

I think this can be simplified with `Array.find`:
```js
const selectedItem = items.find(item => `${item.requester.caption}${item.requester.name}` === self.selectedInfo) || items[0];
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709)*

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709)*

**Comment by jolevesq** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details.directive.js, line 128 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709#-KJLW263sB3A0qhXBL63:-KJLcd0C-V0e0mTBW9ol:646183711) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7aeeb908ece310804ee52ff00ba53cd8f9ca9e4b/src/app/ui/details/details.directive.js#L128)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary>
> I think this can be simplified with `Array.find`:
> ```js
> const selectedItem = items.find(item => `${item.requester.caption}${item.requester.name}` === self.selectedInfo) || items[0];
> ```
</details>
Done. Good observation, hope I will remember it next time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/709)*

**Pull request merged**
