### PR TITLE
Schema

### PR DESCRIPTION
**Pull request by alyec**
Partly completed schema.  Enough to start with and something to build on for RCS.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/246)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/246)*

**Comment by ec-dev** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/246)*

**Comment by james-rae** [comment]
Reviewed 1 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/246)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/schema.json, line 198 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/246#-K8zWDVmoX_tdJbpmK1J:-K8zWDVnKQfKW6yJIJuZ:-944040243) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e541f59d9061f8e4ebc81529c31f623c0f36d256/src/schema.json#L198)):*
What's this for?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/246)*

**Pull request merged**
