### PR TITLE
API: add UI support for panels and tooltips

### PR DESCRIPTION
**Pull request by milesap**
### What's been implemented (required for CIP progress on external extention)
- adds api support for panels: open/close, node content replacement, and event streams (opening/closing/opened/closed).
- adds api support for tool tips: allows hover tool tips to be modified in flight with new `attribs` property from geoApi. Also allows any number of tool tips to be placed on the map with custom content.

### To be completed in another PR
- Need to add support for swapping context map (mini map) contents with custom code (for cip highcharts). Ability to open/close among others. 
- UI anchor points need to be defined
- Enable support for stoppable panel events (on opening/closing). Some code is in but not enabled.
- Popup (modal) window support
- More panels (?) - Current support the major three (main, side, table)
- Legend manipulation. This is likely a lot of work and would need extensive analysis on its benefits vs costs to develop 

## Testing
As always in chrome dev tools `RZ` is the global entry point.

```js
RZ.mapInstances[0].ui.panels.byId('main').node.find('.rv-legend-list').first().append('<li>DONE, THANKS!</li>');

RZ.mapInstances[0].ui.panels.byId('main').close();

const a = RZ.mapInstances[0].ui.tooltip.add({x:300,y:500}, 'HELLO');
a.destroy();

RZ.mapInstances[0].ui.tooltip.mouseOver.subscribe(z => {
	console.error(z);
	z.event.preventDefault();
	z.attribs.then(a => {
        z.add(`<span style="padding:10px">City: ${a.City}</span>`);
    });
});

```

## Documentation
tsdocs, can be improved when there is more time but good start

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2543)

### CODE REVIEW

**Comment by james-rae** [comment]
Random thought.  In the past we used terms `Hover` and `Anchor` to differentiate between following the mouse and following the map. Could be that `addHoverTooltip`, `addAnchorTooltip` is more intuitive than `addHoverTooltip`, `addTooltip` . 

---

Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[api/src/events.ts, line 26 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L26vxpK7dzSeMP89wra:-L26vxpK7dzSeMP89wrb:b-q8nmvi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6e6f411b2e41ef0a8d7deb2970734ee5ac9f181/api/src/events.ts#L26)):*
> ```XML
> 
> /**
>  * @TODO: finish once supported by ESRI
> ```

Did the comments [here](https://github.com/fgpv-vpgf/geoApi/issues/275#issuecomment-351423334) satisfy the question?

---

*[api/src/ui.ts, line 153 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L26khdFSv_RT9tl8Std:-L26khdGSa0BrATrw_tF:b-2rj283) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6e6f411b2e41ef0a8d7deb2970734ee5ac9f181/api/src/ui.ts#L153)):*
> ```XML
>     }
> 
>     add (panel: Panel): void {
> ```

do we need a `remove()`?

---

*[api/src/ui.ts, line 181 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L26qxLNSxnHjaVVZ40S:-L26qxLNSxnHjaVVZ40T:b-c7cyea) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6e6f411b2e41ef0a8d7deb2970734ee5ac9f181/api/src/ui.ts#L181)):*
> ```XML
>     }
> 
>     add(screenPosition: ScreenPosition, content: JQuery<HTMLElement>) {
> ```

I might need more explaining about the `screenPosition` aspect. I can see in a file below that we can now swap between follow map & follow mouse. Not sure what happens when follow  mouse update triggers; could be this is ignored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-:-L26vQqIrh8JBx9GZR20:bdc1e7p)*

**Comment by spencerwahl** [comment]
Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by milesap** [comment]
I think this will be less confusing once we can separate an API created tool tip, which is a follow map strategy, vs a listen on layer for tool tip which is a follow mouse strategy.

---

Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[api/src/events.ts, line 26 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L26vxpK7dzSeMP89wra:-L2aPlDJrIkNkiV--OGE:becnahu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6e6f411b2e41ef0a8d7deb2970734ee5ac9f181/api/src/events.ts#L26)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Did the comments [here](https://github.com/fgpv-vpgf/geoApi/issues/275#issuecomment-351423334) satisfy the question?
</blockquote></details>

Good info in that post, solves the issue so I'll close it. Unfortunately `statemanager` is difficult to work with, since panels have child panels, and all panels have opening histories so stoppable panels will need some robust code changes. Also some panels close other panels (like table closes side panel), so atm stopping panels introduces many new bugs.

---

*[api/src/ui.ts, line 153 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L26khdFSv_RT9tl8Std:-L2_z2zfemayfu4uGtn8:b-fbeusn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6e6f411b2e41ef0a8d7deb2970734ee5ac9f181/api/src/ui.ts#L153)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

do we need a `remove()`?
</blockquote></details>

Its a nice-to-have feature, I'll added this in.

---

*[api/src/ui.ts, line 181 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L26qxLNSxnHjaVVZ40S:-L2aP7MQ6XSBp-WItVbg:bhm5q38) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/e6e6f411b2e41ef0a8d7deb2970734ee5ac9f181/api/src/ui.ts#L181)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I might need more explaining about the `screenPosition` aspect. I can see in a file below that we can now swap between follow map & follow mouse. Not sure what happens when follow  mouse update triggers; could be this is ignored.
</blockquote></details>

You currently can only create a follow map tool tip via the API 

`const a = RZ.mapInstances[0].ui.tooltip.add({x:300,y:500}, 'HELLO');`

The hover tips can only have their content changed, as `z.add(`<span style="padding:10px">City: ${a.City}</span>`);` for example only takes a content string and not a screenPosition. Hover tips follow the mouse. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-:-L2aPu6_cyLhNiJvVRfa:b-nfpfog)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by JahidAhmed** [comment]
Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 4 of 5 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[api/src/ui.ts, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L2ewYvuBf_gB7vmYsAf:-L2ewYvuBf_gB7vmYsAg:brz7ual) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b6a4f92f77b8780f4c5e8edaedd9cfad16c8d727/api/src/ui.ts#L176)):*
> ```XML
>  */
> class ToolTip {
>     _mouseOver: Subject<Event> = new Subject();
> ```

We talked about moving `over/out` events to layer objects. Do you plan to change this in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by milesap** [comment]
Still doing sanity checks, will advise when ready to merge

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[api/src/ui.ts, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L2ewYvuBf_gB7vmYsAf:-L2fawSj87asG5fc1RDm:b-ecboca) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b6a4f92f77b8780f4c5e8edaedd9cfad16c8d727/api/src/ui.ts#L176)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

We talked about moving `over/out` events to layer objects. Do you plan to change this in this PR?
</blockquote></details>

No, for now hover tool tips and manual tooltips are equal (except the latter doesn't have an `attribs` value). Once we merge layers into the API this will be separated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-:-L2fbIA_iOROat4cpYMB:b-jp0n3)*

**Comment by milesap** [comment]
Sanity checks complete, looks good to go. Will open another PR for CIP progress

---

Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-:-L2vRBLxC6LZjZuJyHFc:b1bfd5i)*

**Comment by AleksueiR** [comment]
Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 5 files at r5, 1 of 1 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[api/src/ui.ts, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L2ewYvuBf_gB7vmYsAf:-L2z0y2fWJqS5r3AmD5S:b-bepumz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b6a4f92f77b8780f4c5e8edaedd9cfad16c8d727/api/src/ui.ts#L176)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

No, for now hover tool tips and manual tooltips are equal (except the latter doesn't have an `attribs` value). Once we merge layers into the API this will be separated.
</blockquote></details>

Can you add a comment in source about that, so it's not missed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by spencerwahl** [comment]
Reviewed 4 of 4 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by JahidAhmed** [comment]
Reviewed 4 of 4 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by milesap** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[api/src/ui.ts, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L2ewYvuBf_gB7vmYsAf:-L2z5qOYay5ljo5CJWsq:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b6a4f92f77b8780f4c5e8edaedd9cfad16c8d727/api/src/ui.ts#L176)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can you add a comment in source about that, so it's not missed?
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r7, 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by james-rae** [comment]
Reviewed 1 of 4 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543)*

**Comment by AleksueiR** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[api/src/ui.ts, line 176 at r6](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-L2ewYvuBf_gB7vmYsAf:-L2zl8oDXdjFqu6S1UZ-:bevsic7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b6a4f92f77b8780f4c5e8edaedd9cfad16c8d727/api/src/ui.ts#L176)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

:heavy_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2543#-:-L2zlBoAtAbANwpHF6-E:bg7igkv)*

**Pull request merged**
