### PR TITLE
test: add sample karma directive and service tests

### PR DESCRIPTION
**Pull request by AleksueiR**
Updated sample controller test.

Both source code and test specs are babeled, so you can use es6 in test scripts.

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/61)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by jolevesq** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/common/morph.directive.spec.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61#-K1inY-H_Ns6yuLZOQ5S)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4956bd791ed9d684b99f830dbc4fc102aba920a9/src/app/ui/common/morph.directive.spec.js#L4)):</sup>
Should it be let?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by AleksueiR** [comment]
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

<sup>**[src/app/ui/common/morph.directive.spec.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61#-K1inY-H_Ns6yuLZOQ5S)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4956bd791ed9d684b99f830dbc4fc102aba920a9/src/app/ui/common/morph.directive.spec.js#L4)):</sup>
Ah, yes. Do we have a JShint rule to disallow `var`?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by jolevesq** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/common/morph.directive.spec.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61#-K1inY-H_Ns6yuLZOQ5S)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4956bd791ed9d684b99f830dbc4fc102aba920a9/src/app/ui/common/morph.directive.spec.js#L4)):</sup>
I dont see a rule for that in our JSHint. On JSHint web site they say we can use varstmt (When set to true, the use of VariableStatements are forbidden). Do we want to add this?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by alyec** [comment]
Might be worth picking one test and adding a lot more commentary around it.


---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by AleksueiR** [comment]
Ok, which one and how much more?


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/common/morph.directive.spec.js, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61#-K1inY-H_Ns6yuLZOQ5S)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/4956bd791ed9d684b99f830dbc4fc102aba920a9/src/app/ui/common/morph.directive.spec.js#L4)):</sup>
Let's continue in gitter.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by alyec** [comment]
Morph or Mapnav probably.  And comments more in line with explaining how to use the unit tests, what bard is doing, how spies work, etc.  In general making it more of a case study (with a bunch of links to the relevant references).  Not sure if you had this planned for a future PR but it probably makes sense to group this together.


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by ec-dev** [comment]
Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by ec-dev** [comment]
Reviewed 1 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by AleksueiR** [comment]
Don't merge yet - I'm going to add more comments.


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/app/ui/mapnav/mapnav.service.spec.js, line 41 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61#-K1jPc5THdb-PrYAawRR)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c85b74700523831717022060d0a17baaa4140e87/src/app/ui/mapnav/mapnav.service.spec.js#L41)):</sup>
Why is this necessary / important?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by AleksueiR** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/app/ui/mapnav/mapnav.service.spec.js, line 41 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61#-K1jPc5THdb-PrYAawRR)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c85b74700523831717022060d0a17baaa4140e87/src/app/ui/mapnav/mapnav.service.spec.js#L41)):</sup>
Good catch. This is only needed when the component being tested is using `$http` service.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by alyec** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by ec-dev** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by ec-dev** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by jolevesq** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by AleksueiR** [comment]
FYI: Good to merge now.


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by jolevesq** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Comment by ec-dev** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/61)

**Pull request merged**
