### PR TITLE
1495 geosearch ui fixes final

### LINKED ISSUE #1495: Fixes for for geosearch component UI
Here's a list of things:
 - [x] fix style on the "clear search terms" button
 - [x] vertically align search filters and fix their styles (remove floating labels, etc.)
 - [x] add progress indicator when searching
 - [x] fix styles for results list (align items, remove extra padding, extend clickable areas, fix text overflow croppings)
 - [x] fix separator between the search field and the search filters
 - ~~[ ] fix appearance of the "Legend" button visible when search is active~~ removed legend button
 - ~~[ ] make the results list show 10-15 items up front with "load more" button and a label specifying how many results found in total~~ all results are available

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
- move geosearch functionality from 1.7 to 1.6 (1.7 release will have datatable enhancements; 1.6 release will have geosearch and structured legend);
- apply ui enhancements;

Closes #1495

This PR is large because it ports the core geosearch functionality from 1.7 and adds UI fixes on top of it. I can split them into two PRs if people prefer that.

## Testing
Eyeballing.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [ ] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1654)

### CODE REVIEW

**Comment by jolevesq** [comment]
If I set a filter with the drop down there is no way to remove it. You can click the clear filter button but it will remove all the filters. May be we should have the first item in the list an item to reset the filter.

Looks very good!!!

---

Reviewed 5 of 21 files at r1, 31 of 36 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/geo/geo-search.service.js, line 255 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbqRychx2IsdNMyn7zI:-KbqRychx2IsdNMyn7zJ:b-vfv60d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/geo/geo-search.service.js#L255)):*
> ```JavaScript
>             }
> 
>             if (typeof extent === 'object') { // convert to lat/lng geoName readable string
> ```

Typo should be lat/long

---

*[src/content/styles/modules/_geosearch.scss, line 34 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbqWCg3PoJg9n5wZxkK:-KbqWCg3PoJg9n5wZxkL:b-f283ms) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/content/styles/modules/_geosearch.scss#L34)):*
> ```SCSS
>     }*/
>             md-autocomplete-wrap {
>                 box-shadow: none; // remove shadow since it needs to look like a regular forn input field
> ```

Type 'forn'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-:-KbqSqt2OZMSA7mWuMWq:b-tlypiy)*

**Comment by AleksueiR** [comment]
Thanks!

Good point about clearing individual filters. I'll check if it can be done quickly, if not - create a separate issue.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-:-KbtfjUe_4Qh3JV7WeSg:b5ii64j)*

**Comment by alyec** [comment]
Reviewed 5 of 21 files at r1, 31 of 36 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/app/core/constant.service.js, line 39 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuFsQ6Qg-0vumOJwoM:-KbuFsQ6Qg-0vumOJwoN:bs1kgq5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/core/constant.service.js#L39)):*
> ```JavaScript
>              * A shorthand for $rootScope.$on; no need to inject `$rootScope` separately;
>              * @function $on
>              */
> ```

missing param docs

---

*[src/app/geo/geo-search.service.js, line 316 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuEVn1V-B175al6inb:-KbuEVn1V-B175al6inc:bvdlas6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/geo/geo-search.service.js#L316)):*
> ```JavaScript
>          *
>          * @function zoomSearchExtent
>          * @param   {Array}    bbox     4 coordinnates for the bbox
> ```

typo coordinates (repeated below), also probably worth adding a `[xmin, ymin, xmax, ymax]` to clarify the order

---

*[src/app/geo/map.service.js, line 847 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuFJxMuKByQWPU_TFD:-KbuFJxMuKByQWPU_TFE:b-casujw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/geo/map.service.js#L847)):*
> ```JavaScript
>              *
>              * @function validateExtent
>              * @param {Number} factor optional; factor to expand the full extent
> ```

Can you add the jsdoc optional parameter syntax here: http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values ?
`{Number} [factor=1] multiplier used to expand the full extent` ?

---

*[src/app/ui/geosearch/geosearch-bar.html, line 29 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuGu92LAa0a99iUg-F:-KbuGu92LAa0a99iUg-G:b-xucv4n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/ui/geosearch/geosearch-bar.html#L29)):*
> ```HTML
>     </md-input-container>
> 
>

**Comment by AleksueiR** [comment]
Review status: 26 of 36 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/app/core/constant.service.js, line 39 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuFsQ6Qg-0vumOJwoM:-Kbuv71NCHgwYiEgE6nw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/core/constant.service.js#L39)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

missing param docs
</blockquote></details>

Done.

---

*[src/app/geo/geo-search.service.js, line 255 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbqRychx2IsdNMyn7zI:-Kbuv8Wm3vcRgxrhMxeI:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/geo/geo-search.service.js#L255)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo should be lat/long
</blockquote></details>

Done.

---

*[src/app/geo/geo-search.service.js, line 316 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuEVn1V-B175al6inb:-KbuvlRSkom9DwGW4BMu:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/geo/geo-search.service.js#L316)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo coordinates (repeated below), also probably worth adding a `[xmin, ymin, xmax, ymax]` to clarify the order
</blockquote></details>

Done.

---

*[src/app/geo/map.service.js, line 847 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuFJxMuKByQWPU_TFD:-KbuvnaSfIdRXQcprIpf:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/geo/map.service.js#L847)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Can you add the jsdoc optional parameter syntax here: http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values ?
`{Number} [factor=1] multiplier used to expand the full extent` ?
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch-bar.html, line 29 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuGu92LAa0a99iUg-F:-KbuvocBPT_bbUD_U_DO:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/ui/geosearch/geosearch-bar.html#L29)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Can we get rid of this dead code?
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch-filters.service.js, line 62 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuHJQVtbJiTlVyKr-q:-KbuvpRXkB7Ukg8oYHjo:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/ui/geosearch/geosearch-filters.service.js#L62)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: the (first instance)
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch.service.js, line 36 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuKjoQ1F-i0oaOuwW7:-KbuvqGjMWbtay-GVv1V:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/ui/geosearch/geosearch.service.js#L36)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

I get the feeling something was missed here.
</blockquote></details>

Done.

---

*[src/app/ui/geosearch/geosearch.service.js, line 77 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuLiPLAuTMu-FdL-G-:-Kbuvqw9ygm5934J-ZsU:b4lsbh2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/ui/geosearch/geosearch.service.js#L77)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

It's the truth.

---

*[src/app/ui/help/help.service.js, line 36 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuLxl_g8PZ9FspoqL7:-KbuvyHH032KtDk4lt5d:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/ui/help/help.service.js#L36)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

remove deadcode ?
</blockquote></details>

Done.

---

*[src/content/styles/layout/_main.scss, line 229 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuMGZ_HkY_wokdygU_:-Kbuvz4FAr9bdowo_O9T:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/content/styles/layout/_main.scss#L229)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

remove deadcode?
</blockquote></details>

Done.

---

*[src/content/styles/modules/_geosearch.scss, line 34 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbqWCg3PoJg9n5wZxkK:-Kbuw-swO-V62KTT1_tU:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/content/styles/modules/_geosearch.scss#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Type 'forn'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654)*

**Comment by alyec** [comment]
Reviewed 9 of 10 files at r3, 1 of 1 files at r4.
Review status: 35 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/core/constant.service.js, line 40 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuvgEVK43BdyKugDqz:-KbuvgEVK43BdyKugDr-:b-2tqfzt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/025942f71848f97ae10a110746d92efccf103185/src/app/core/constant.service.js#L40)):*
> ```JavaScript
>              * @function $on
>              * @param {String} eventName event name to listen once
>              * @param {Function} listener a callback funcion to execute
> ```

typo: function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654)*

**Comment by AleksueiR** [comment]
Review status: 31 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/constant.service.js, line 40 at r4](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuvgEVK43BdyKugDqz:-Kbuy-CUwAO30FGphs-_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/025942f71848f97ae10a110746d92efccf103185/src/app/core/constant.service.js#L40)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: function
</blockquote></details>

Done.

---

*[src/app/ui/help/help.service.js, line 30 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-KbuM86y5goOV4le3BSp:-Kbuy0LJhIMJ7V5uMnJy:b-ve3yvb) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/81d25a726f64421d3ea7f3f56052a31c1870dbd1/src/app/ui/help/help.service.js#L30)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

:trophy: 
</blockquote></details>

:smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654)*

**Comment by alyec** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-:-Kbv13UOHAMckBWoaV4R:bnfp4nl)*

**Comment by jolevesq** [comment]
When I close geosearch and get back to it later, my previous search is cleared.  Would it be good to keep it as long as the user doesn't clear it himself?  The filters works that way. For small screen when you select an element, you can't see it is the right thing until you close the panel and you lose your search.

Would be great to see the overflow when hovering or tabbing to the element (like in our filter panel). Or when selected, there is a popup like the hovering to show the complete text selection.

Focus is not trap inside geosearch when tabbing. At the end it goes to zoom control but it should go the search text.

In FF and Safari, when I select a filter value with the keyboard FF completely lost focus and Safari bring it url bar then goes back to the filter.

Those are non blocking comments and separate issues can be created later if need be.

:lgtm: 

---

Reviewed 4 of 10 files at r3, 1 of 1 files at r5, 4 of 4 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-:-KbyogbmHuRoQjVcFgkv:b864y21)*

**Comment by AleksueiR** [comment]
Thanks for checking this so thoroughly! :+1: 

I agree - let's merge this and create new issues with your comments. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654#-:-Kbz1y2dZFoKidcIV4_K:bsu9ekq)*

**Comment by jolevesq** [comment]
Reviewed 1 of 10 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1654)*

**Pull request merged**
