### PR TITLE
fix(ui): layer stack order

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Fix the layer stack order for autolegends and as a result, the map layer order 

## Testing
:eyes: - tested with both working and broken initial basemap by importing tile layer and then dynamic layer through API in both autolegend and structured legend

## Documentation
In-line comments, JSDoc

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/geo/map.service.js, line 304 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-LB1qFsl-K661yygaDHZ:-LB1qFsl-K661yygaDH_:bqobtn6) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/38d7bb2e3a738c06657a6badb94e6e25fa711c02/src/app/geo/map.service.js#L304)):*
> ```JavaScript
>                     $http.get(mapConfig.selectedBasemap.url + '?f=json')
>                         .then(response => {
>                             if (!response || typeof response.data.error !== 'undefined') {
> ```

Do we want to initialize the map if this check fails anyway as well?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 304 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-LB1qFsl-K661yygaDHZ:-LB1qmTP6a7dh37_Nq04:b-aeguk5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/38d7bb2e3a738c06657a6badb94e6e25fa711c02/src/app/geo/map.service.js#L304)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Do we want to initialize the map if this check fails anyway as well?
</blockquote></details>

I believe so, in any case where the basemap is broken I think we want to ensure that the entire app doesn't break, so the layers will still be loaded

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Comment by spencerwahl** [comment]
Tested in CIP, fixes the layer order issue :+1: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-:-LB1qi3t1u6TIZSpX-1C:b-1pm6bf)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 304 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-LB1qFsl-K661yygaDHZ:-LB1r2Xq9wKLvTFIGpvt:b9z9v30) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/38d7bb2e3a738c06657a6badb94e6e25fa711c02/src/app/geo/map.service.js#L304)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

I believe so, in any case where the basemap is broken I think we want to ensure that the entire app doesn't break, so the layers will still be loaded
</blockquote></details>

If I understand correctly, this means calling `_initMap();` when `$http.get` fails and when it succeeds. If so, do we need `$http.get` at all?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Comment by JahidAhmed** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 304 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-LB1qFsl-K661yygaDHZ:-LB1sNtF6h2mYfRXTzJQ:bitlg7z) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/38d7bb2e3a738c06657a6badb94e6e25fa711c02/src/app/geo/map.service.js#L304)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

If I understand correctly, this means calling `_initMap();` when `$http.get` fails and when it succeeds. If so, do we need `$http.get` at all?
</blockquote></details>

This is calling on two types of failure, one thats caught and the other where a response is returned but the response returns an error (`typeof response.data.error !== 'undefined'`). I think a response is returned with an error on invalid URLs but the request is caught if the server is down, which is why both cases need to be handled. Nothing happens here on success, that case is handled on `layer-add` for the basemap layer itself

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 304 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-LB1qFsl-K661yygaDHZ:-LB1u5xB7Zis5Vmf6_Vs:b-jp0bbh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/38d7bb2e3a738c06657a6badb94e6e25fa711c02/src/app/geo/map.service.js#L304)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

This is calling on two types of failure, one thats caught and the other where a response is returned but the response returns an error (`typeof response.data.error !== 'undefined'`). I think a response is returned with an error on invalid URLs but the request is caught if the server is down, which is why both cases need to be handled. Nothing happens here on success, that case is handled on `layer-add` for the basemap layer itself
</blockquote></details>

Got it, thank! :+1: Can you add this bit about the success being handled by `layer-add` to the comments, please?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Comment by JahidAhmed** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 304 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-LB1qFsl-K661yygaDHZ:-LB1vFDY7-gDJmJmIHPr:b-277ha0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/38d7bb2e3a738c06657a6badb94e6e25fa711c02/src/app/geo/map.service.js#L304)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Got it, thank! :+1: Can you add this bit about the success being handled by `layer-add` to the comments, please?
</blockquote></details>

Added comments!

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/map.service.js, line 304 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-LB1qFsl-K661yygaDHZ:-LB1vmPD0TyeyaG_BtQZ:bevsic7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/38d7bb2e3a738c06657a6badb94e6e25fa711c02/src/app/geo/map.service.js#L304)):*
<details><summary><i>Previously, JahidAhmed (Jahid Ahmed) wrote…</i></summary><blockquote>

Added comments!
</blockquote></details>

:heavy_check_mark: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677#-:-LB1vrJB46O3dVEdu5Ca:bnfp4nl)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Comment by james-rae** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)*

**Pull request merged**
