### PR TITLE
chore(docs): add docs for layer import and other comments

### LINKED ISSUE #1093: Dev Docs: User Added Layers

### PR DESCRIPTION
**Pull request by AleksueiR**
## Description
Adds a new page to the docs and a bit of jsdoc comments.

Closes #1093

## Testing
Nothing to test.

## Documentation
Yes.

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- ~~[ ] release notes have been updated~~ not needed
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1982)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 4 of 11 files at r1.
Review status: 4 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/developer/function.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kmks_O12-8XLtxPiRAA:-Kmks_O2ESJlrPRZQI48:b-f8r14f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function.md#L1)):*
> ```Markdown
> The above resources are functional descriptions of interesting parst of the codebase. These guides are not a substitution for a thorough reading of the inline and API documentation; however, they will provide an overview and maybe shed some light on why things are done this way.
> ```

typo: parts

---

*[docs/developer/function/layer_import.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmktEO-ZAZcVaeOdHEJ:-KmktEO-ZAZcVaeOdHEK:b-faekye) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L1)):*
> ```Markdown
> The "Layer Import Wizard" or `loader` (as it's referenced in the code), is a majour piece of UI functionality which allows users to add data to a map instance. There are two way this can be done - through a service or a file.
> ```

typo: major

---

*[docs/developer/function/layer_import.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmktSUokkn1nJTwI_7r:-KmktSUokkn1nJTwI_7s:bywk67k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L19)):*
> ```Markdown
> The user can select a file from a local disk using a file selector, drag'n'drop a file onto the layer import wizard, or enter an absolute URL to be loaded over the network. The file path and the HTML5 file object (if any) are then passed to the __layerSource__ service's __fetchFileInfo__ function to parse the data. __geoApi__ is called to analyze the file, test if it contains readable data, and, if possible, determine the file type (we can't just rely on file extension, but a most likely option will be preselected), along with smart defaults for each file type. After the data is read, a three __LayerSourceInfo__ objects are created for three supported file types: CSV, GeoJSON, and ShapeFile.
> 
> A __LayerSourceInfo__ contains a typed config for a Feature Layer and various extra options like lat/long field names or point colour that can be changed by the user, but are not found in the layer config class.Upfront validation is expensive and time consuming, so the user is tasked with correctly identifying the file type.
> ```

spaces between 'class.Upfront'

---

*[docs/developer/function/layer_import.md, line 57 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kmku2EtAHQqdQpyFdCm:-Kmku2EtAHQqdQpyFdCn:b1y0nmz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L57)):*
> ```Markdown
> If this is successful, as the final step, the wizard passed the __LayerFileBlueprint__ object to the __legendService__ to import. The __legendService__ will attempt to make a __LayerRecord__ object from the __LayerFileBlueprint__.
> 
> _Note:_ After multiple validations, the layer might still fail when added to the map. It seems there no way to predict if the layer will load correctly apart from adding it to the map and trying to load it.
> ```

typo: "there is no way"

---

*[src/app/geo/legend-block.class.js, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuHTlk82S17LLB7IQ:-KmkuHTlk82S17LLB7IR:be4tsmy) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L2)):*
> ```JavaScript
> /**
>  * @ngdoc object
> ```

Isn't `@ngdoc` exclusive to dgeni?

---

*[src/app/geo/legend-block.class.js, line 45 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuNTRnyIxGtTQ_3SC:-KmkuNTRnyIxGtTQ_3SD:b-dh1uzd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L45)):*
> ```JavaScript
>     class ProxyWrapper {
>         /**
>          * blah
> ```

very descriptive

---

*[src/app/geo/legend-block.class.js, line 47 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuQ5kHJ1FD7HmraeB:-KmkuQ5kHJ1FD7HmraeC:bmntzac) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L47)):*
> ```JavaScript
>          * blah
>          *
>          * @param {LayerProxy} proxy a layer proxy object which will be coupled with a correspondign layer config object
> ```

typo: corresponding

---

*[src/app/geo/legend-block.class.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuSqRD0GmknwF04hv:-KmkuSqRD0GmknwF04hw:b-fay2ny) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L48)):*
> ```JavaScript
>          *
>          * @param {LayerProxy} proxy a layer proxy object which will be coupled with a correspondign layer config object
>          * @param {LayerNode} layerConfig laye config defintion object from the config file; it may provide overrides and initial settings for the layer proxy object
> ```

typo: layer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by AleksueiR** [comment]
Review status: 4 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/app/geo/legend-block.class.js, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuHTlk82S17LLB7IQ:-KmkujbcVfHQsy8BUKxw:b-nkyoe1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L2)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Isn't `@ngdoc` exclusive to dgeni?
</blockquote></details>

I got very confused yesterday how to markup classes. Yes, you are right, it's dgeni, so we should remove all that nonsense anyway.

---

*[src/app/geo/legend-block.class.js, line 45 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuNTRnyIxGtTQ_3SC:-Kmkv3BOcG3whRj6Cgdd:b55746k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L45)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

very descriptive
</blockquote></details>

Indeed :) Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by james-rae** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[docs/developer/function/layer_import.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmktEO-ZAZcVaeOdHEJ:-Kmkyur2MOw5VAd0V-Rt:brpm3v3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: major
</blockquote></details>

Canadian language logic trap.

---

*[docs/developer/function/layer_import.md, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml0zQF3VL8xqErzN5l:-Kml0zQF3VL8xqErzN5m:b-fxnkke) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L75)):*
> ```Markdown
> At this step, the user can enter service URL which will be passed to the __layerSource__ service's __fetchServiceInfo__ function to parse the data. There is a small validation step to ensure the user input is an actual URL and is not just some garbage text.
> 
> __fetchServiceInfo__ will call geoApi's to check if the URL points to a WMS service. If it's not a WMS, the geoApi's prediction function is called to determine the service type. When the service type is determined, a number of __LayerSourceInfo__ objects is created according to this table:
> ```

`will call geoApi's to check` . I think you either want to add a function name, or get rid of the `'s`

---

*[docs/developer/function/layer_import.md, line 77 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml2czbj2nDxMaBxA-3:-Kml2czcsnlp6n1NGwek:b3t568d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L77)):*
> ```Markdown
> __fetchServiceInfo__ will call geoApi's to check if the URL points to a WMS service. If it's not a WMS, the geoApi's prediction function is called to determine the service type. When the service type is determined, a number of __LayerSourceInfo__ objects is created according to this table:
> 
> | Source Service Type | Target Layer Type                  |
> ```

I understand what the table means, but the words `Source` and `Target` are a bit ambiguous to someone who didn't develop the code. Maybe `Provided` instead of `Target` and `Viewer Layer Type` instead of `Source Service Type`.
As well, the use of `target` in doc below doesn't seem to match this table (e.g. they would never see `Raster` in `Service Type Selection`).

---

*[docs/developer/function/layer_import.md, line 81 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml3hIA8KAqdKppAu1c:-Kml3hIA8KAqdKppAu1d:bgem8zq) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L81)):*
> ```Markdown
> | Feature             | Feature                            |
> | Image               | Image                              |
> | Dynamic             | Feature, Raster, Group, or Tile    |
> ```

Can we not import a Tile as a Tile?

---

*[src/app/ui/toc/symbology-stack.directive.js, line 12 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml6j1qhcx1zao2Qnyt:-Kml6j1rudSS9OwPiaID:b8b0mjd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/ui/toc/symbology-stack.directive.js#L12)):*
> ```JavaScript
> 
> /**
>  * @ngboc service
> ```

`boc` or `doc`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by AleksueiR** [comment]
Review status: 4 of 26 files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/developer/function.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kmks_O12-8XLtxPiRAA:-Kn-5MUAmkq852xW_AlT:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function.md#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: parts
</blockquote></details>

Done.

---

*[docs/developer/function/layer_import.md, line 1 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmktEO-ZAZcVaeOdHEJ:-Kn-4pjniisGbW2XQmZt:b4dhi2f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L1)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Canadian language logic trap.
</blockquote></details>

Aly is correct `majour` is not actually a word at all on both sides of the pond. Change to correct `major`.

---

*[docs/developer/function/layer_import.md, line 19 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmktSUokkn1nJTwI_7r:-Kn-5RAAMEO67L0i4WBy:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L19)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

spaces between 'class.Upfront'
</blockquote></details>

Done.

---

*[docs/developer/function/layer_import.md, line 57 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kmku2EtAHQqdQpyFdCm:-Kn-5RiVAH1dquufNF7s:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L57)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: "there is no way"
</blockquote></details>

Done.

---

*[docs/developer/function/layer_import.md, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml0zQF3VL8xqErzN5l:-Kn-5SGoOm2-w7-M_9r5:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L75)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`will call geoApi's to check` . I think you either want to add a function name, or get rid of the `'s`
</blockquote></details>

Done.

---

*[docs/developer/function/layer_import.md, line 77 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml2czbj2nDxMaBxA-3:-Kn-Ca7SdGILJx-aE89-:bxzh7wt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L77)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I understand what the table means, but the words `Source` and `Target` are a bit ambiguous to someone who didn't develop the code. Maybe `Provided` instead of `Target` and `Viewer Layer Type` instead of `Source Service Type`.
As well, the use of `target` in doc below doesn't seem to match this table (e.g. they would never see `Raster` in `Service Type Selection`).
</blockquote></details>

Updated the table. Is it better now? 

---

*[docs/developer/function/layer_import.md, line 81 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml3hIA8KAqdKppAu1c:-Kn-Cdw5TL2B_pm0zkST:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/docs/developer/function/layer_import.md#L81)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Can we not import a Tile as a Tile?
</blockquote></details>

Done.

---

*[src/app/geo/legend-block.class.js, line 2 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuHTlk82S17LLB7IQ:-Kn-EkN3sJIMdUMKbcUy:b-3pcvzn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I got very confused yesterday how to markup classes. Yes, you are right, it's dgeni, so we should remove all that nonsense anyway.
</blockquote></details>

Removed all of them.

---

*[src/app/geo/legend-block.class.js, line 45 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuNTRnyIxGtTQ_3SC:-Kn-F0i_1UelPKfF_L5B:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L45)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Indeed :) Will fix.
</blockquote></details>

Done.

---

*[src/app/geo/legend-block.class.js, line 47 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuQ5kHJ1FD7HmraeB:-Kn-F3zpwYNKFXAiCsmY:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: corresponding
</blockquote></details>

Done.

---

*[src/app/geo/legend-block.class.js, line 48 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-KmkuSqRD0GmknwF04hv:-Kn-F7NAJURbbIzjD_in:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/geo/legend-block.class.js#L48)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

typo: layer
</blockquote></details>

Done.

---

*[src/app/ui/toc/symbology-stack.directive.js, line 12 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml6j1qhcx1zao2Qnyt:-Kn-FA1NzxRk1xQCfZ-J:b-wqkpb0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/ui/toc/symbology-stack.directive.js#L12)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`boc` or `doc`?
</blockquote></details>

Neither :D 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by james-rae** [comment]
Reviewed 22 of 22 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[docs/developer/function/layer_import.md, line 99 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kn-zZP4BjGpRLU8cgsl:-Kn-zZP4BjGpRLU8cgsm:bwg1ls8) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f8182563074144cbdfff2a701fe636cd7e8e3e9/docs/developer/function/layer_import.md#L99)):*
> ```Markdown
> #### Feature Server
> 
> | ESRI Layer Type / Endpoint | Feature | Raster | Root |
> ```

Feature Server can have a `Group`, and cannot have `Raster`.  If you just change the column heading I think the table is still correct.

---

*[src/app/ui/toc/symbology-stack.directive.js, line 12 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml6j1qhcx1zao2Qnyt:-Kn0-PO1sw7HWBTPyN2p:b-dspg6s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/ui/toc/symbology-stack.directive.js#L12)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Neither :D 
</blockquote></details>

Still lurking :sun_with_face: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by AleksueiR** [comment]
Review status: 24 of 26 files reviewed at latest revision, 10 unresolved discussions.

---

*[docs/developer/function/layer_import.md, line 99 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kn-zZP4BjGpRLU8cgsl:-Kn01W3i4owozfLdfDiP:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3f8182563074144cbdfff2a701fe636cd7e8e3e9/docs/developer/function/layer_import.md#L99)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Feature Server can have a `Group`, and cannot have `Raster`.  If you just change the column heading I think the table is still correct.
</blockquote></details>

Done.

---

*[src/app/ui/toc/symbology-stack.directive.js, line 12 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kml6j1qhcx1zao2Qnyt:-Kn01J3pL8DO0bm3m7jz:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6cab3b18ba95ce11bb2c7bb709a5b5fa53c2e9b3/src/app/ui/toc/symbology-stack.directive.js#L12)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Still lurking :sun_with_face: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by jolevesq** [comment]
Reviewed 2 of 11 files at r1, 19 of 22 files at r3, 2 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[docs/developer/function/layer_import.md, line 31 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kn4MEVjGAUgQ5L1M48D:-Kn4MEVjGAUgQ5L1M48E:b-w9zaw0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1cfb59d4aa640aa140182376a1c101aaa237b4dc/docs/developer/function/layer_import.md#L31)):*
> ```Markdown
> At this step, the user confirms the preselect file type or choses a different one. Update clicking "Continue", the `validate` function is called on a corresponding __LayerSourceInfo__ object. geoApi does its best to check if the selected file type matches its content. If the check succeeds, the wizard moves the next step; if not, the user is informed about the error.
> 
> When a choice is made, the the layer config of the __LayerSourceInfo__ object is saved. This is used to restore any user-made changes tp the config, if the configuration step is canceled.
> ```

There 2 the (the the layer)

---

*[docs/developer/function/layer_import.md, line 123 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kn4Msp_0tFU6TMnMCIy:-Kn4Msp_0tFU6TMnMCIz:b6gib6t) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1cfb59d4aa640aa140182376a1c101aaa237b4dc/docs/developer/function/layer_import.md#L123)):*
> ```Markdown
> ### Service Type Selection
> 
> At this step, the users choses the target layer type from the available choices. When a choice is made, the the layer config of the __LayerSourceInfo__ object is saved. This is used to restore any user-made changes tp the config, if the configuration step is canceled.
> ```

Double the (the the layer)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by AleksueiR** [comment]
Review status: 25 of 26 files reviewed at latest revision, 9 unresolved discussions.

---

*[docs/developer/function/layer_import.md, line 31 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kn4MEVjGAUgQ5L1M48D:-Kn9MAF3jyGLU5bYfdln:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1cfb59d4aa640aa140182376a1c101aaa237b4dc/docs/developer/function/layer_import.md#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There 2 the (the the layer)
</blockquote></details>

Done.

---

*[docs/developer/function/layer_import.md, line 123 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982#-Kn4Msp_0tFU6TMnMCIy:-Kn9MAwJfIYU5bHYGOLf:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/1cfb59d4aa640aa140182376a1c101aaa237b4dc/docs/developer/function/layer_import.md#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Double the (the the layer)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Comment by james-rae** [comment]
Reviewed 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1982)*

**Pull request merged**
