### PR TITLE
Api 05 - Layer Group

### PR DESCRIPTION
**Pull request by JahidAhmed**
## Description
Starts implementation of #2571:
- Adding layers using JSON snippet, removing layers through API. 
- Adding / removing observables 
- Attribute observables
- Layer click in legend observable
- Other small functions

NOTE: Still need to implement adding of layers by other methods (GeoJSON, url, etc.)

## Testing
```js
RZ.mapInstances[0].layers.layerAdded.subscribe(layer => console.log(layer));
RZ.mapInstances[0].layers.addLayer(<JSONSnippet>);
RZ.mapInstances[0].layers.allLayers; // array of all layers
RZ.mapInstances[0].layers.getLayersById('<layerId>').forEach(...);
RZ.mapInstances[0].layers.attributesAdded.subscribe(attrib => console.log(attrib));
RZ.mapInstances[0].layers.click.subscribe(layer => console.log(layer)); // click on layer in legend
// So on and so forth
```

## Documentation
http://fgpv-vpgf.github.io/fgpv-vpgf/api-05-docs/api/classes/_layers_.layergroup.html

## Checklist

- [x]  Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2587)

### CODE REVIEW

**Comment by milesap** [comment]
Excellent work, overall code looks good and well documented. Only minor comments I made (and update elsewhere if I missed) is that todo methods/functionality should either be commented out, or if a method only implements some of its intended purpose to put a todo in the method comments section (so that the docs always reflect the current state of the API).

Apart from that I tested everything in various ways, including IE and works well. :trophy: I'll defer to @james-rae for any final comments.

:lgtm: 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[api/src/layers.ts, line 190 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587#-L5imbLGA8BTuA8lpxQH:-L5imbLGA8BTuA8lpxQI:b-z1393y) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fff270c2494aae6ea183b15f81a117e28deb2385/api/src/layers.ts#L190)):*
> ```XML
>         const oldName: string = this._layerProxy.name;
> 
>         // TODO: currently does not work for dynamics since no setter for LayerInterface, so using layerRecord instead.
> ```

Move up into method comments so it can be seen in generated docs.

---

*[api/src/layers.ts, line 295 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587#-L5im-nZ50czmkMhfGJ9:-L5im-nZ50czmkMhfGJA:bohvg51) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fff270c2494aae6ea183b15f81a117e28deb2385/api/src/layers.ts#L295)):*
> ```XML
>     }
> 
>     /** Exports the layer to a GeoJSON object. */
> ```

Move `TODO` out of method and comment out code (so docs reflect what is actually implemented).

---

*[api/src/layers.ts, line 636 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587#-L5inBuo64yY5i8oo9Bh:-L5inBuo64yY5i8oo9Bi:bohvg51) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fff270c2494aae6ea183b15f81a117e28deb2385/api/src/layers.ts#L636)):*
> ```XML
>     /** Exports the layers in the group to a GeoJSON object. */
>     toGeoJson(callback: (obj: Object) => void): void {
>         // TODO: complete this function
> ```

Move `TODO` out of method and comment out code (so docs reflect what is actually implemented).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587#-:-L5iohz2qjNECjm0j8rv:bogeeq)*

**Comment by james-rae** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587)*

**Comment by JahidAhmed** [comment]
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[api/src/layers.ts, line 190 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587#-L5imbLGA8BTuA8lpxQH:-L5isQ4DCRCi44GtMV1u:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fff270c2494aae6ea183b15f81a117e28deb2385/api/src/layers.ts#L190)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Move up into method comments so it can be seen in generated docs.
</blockquote></details>

done

---

*[api/src/layers.ts, line 295 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587#-L5im-nZ50czmkMhfGJ9:-L5ir7WAwiDR7e-9q5PS:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fff270c2494aae6ea183b15f81a117e28deb2385/api/src/layers.ts#L295)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Move `TODO` out of method and comment out code (so docs reflect what is actually implemented).
</blockquote></details>

done

---

*[api/src/layers.ts, line 636 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587#-L5inBuo64yY5i8oo9Bh:-L5irD-Bcj8HRYsR3LX4:bb7f2mf) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fff270c2494aae6ea183b15f81a117e28deb2385/api/src/layers.ts#L636)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

Move `TODO` out of method and comment out code (so docs reflect what is actually implemented).
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587)*

**Comment by milesap** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2587)*

**Pull request merged**
