### PR TITLE
fix(ui): zoom to feature placement on map now cenetered

### LINKED ISSUE #1629: Zoom to feature extent is offset
When zooming to a feature, it's placed about 3/4 down the height of the viewer instead of putting it in the middle.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Main panel width and filters panel height now accounted for when
centering the zoom to feature item.

Closes #1629

## Testing
👁 

## Documentation
inline where needed

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1707)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/map.service.js, line 18 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707#-KdRz2rPmuL9L-0gfo_T:-KdRz2rPmuL9L-0gfo_U:b-kgubth) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5e4bd5756873f2a2e314e748ab992803110abfbe/src/app/geo/map.service.js#L18)):*
> ```JavaScript
> 
>     function mapServiceFactory($q, $timeout, gapiService, storageService, $rootElement, $compile, $rootScope,
>         stateManager) {
> ```

instead of having stuff in geo depend on stateManager can you shift this to be the caller's responsibility

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by AleksueiR** [comment]
Please, rebase, the demo doesn't work because of the Rcolor libarary.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707#-:-KdS0jXhQn3ME03mgOFT:b18eeb1)*

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/map.service.js, line 18 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707#-KdRz2rPmuL9L-0gfo_T:-KdW1YwUqHiyi_SLU3PG:b61bphd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/3e4e975ac6ca48fcab93ce526d500fae4579950e/src/app/geo/map.service.js#L18)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

instead of having stuff in geo depend on stateManager can you shift this to be the caller's responsibility
</blockquote></details>

Can you clarify what you mean by this? My understanding of this is that we move `computeDimention` into `stateManager`, but then geo will still require `stateManager`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by jolevesq** [comment]
Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 7 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Comment by AleksueiR** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1707)*

**Pull request merged**
