### PR TITLE
chore(cleanup): remove old / unused code

### LINKED ISSUE #2030: Remove 1.x dead code left over after move to 2.0
There lots of dead code left over after move to 2.0. This gets confusing as it's hard to tell what code executes at runtime and what is not. Also, the build size will get a tiny bit smaller.

### PR DESCRIPTION
**Pull request by milesap**
## Description
Closes #2030

## Testing
:eye: 

## Documentation
none

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] ~~release notes have been updated~~
- [x] PR targets the correct release version

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2137)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Seems safe :)
There is some more dead code in `layer-registry.service` though.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137#-:-KolQBqG_u3fZrfAkgj5:bx3zrea)*

**Comment by milesap** [comment]
:+1: Pruned down layer-registry, let me know if there are any other large swaths of code I missed

---

Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137#-:-KolTKC-ZQlIosvXmwCH:b33pc3i)*

**Comment by AleksueiR** [comment]
:+1:  Notices there is some more in 'settings' directives, but otherwise I think this is mostly it.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/geo.constant.service.js, line 84 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137#-KolhW23VXS-agcTJjPk:-KolhW23VXS-agcTJjPl:bdnh660) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c65b7446074b1eeb91dc3938afaa9061a39ed028/src/app/geo/geo.constant.service.js#L84)):*
> ```JavaScript
>     .module('app.geo')
>     .constant('Geo', GEO)
>     .service('layerDefaults', () => {
> ```

The `layerDefaults` service can go as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137#-:-Koli4kGpBTvmJ7Iyd4P:b-h9hab8)*

**Comment by milesap** [comment]
Removed the commented code in `settings.directive.js`

---

Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137#-:-KoqP9_7v3OXBXD5iPAu:b-irn2xd)*

**Comment by milesap** [comment]
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/geo.constant.service.js, line 84 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137#-KolhW23VXS-agcTJjPk:-KoqPWfBGdfBJiLLlsXN:b-8fx2u7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/c65b7446074b1eeb91dc3938afaa9061a39ed028/src/app/geo/geo.constant.service.js#L84)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

The `layerDefaults` service can go as well.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137)*

**Comment by AleksueiR** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2137)*

**Pull request merged**
