### PR TITLE
feat(wizard): remove service prediction

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
## Description

Removes service type prediction from the import wizard. The predictor was taking too long to load some types of services (WFS, for example). We made the decision to remove the predictor all together and have the user decide on the service type. 

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3432

PR also fixes some other issues, such as https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2986 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2937.

## Testing

Tested by importing different files directly, and using each of the service types.

### Checklist

- [x] works in IE11
- [x] works in Edge
- [ ] works with projection change
- [ ] works with language change
- [ ] works via config file
- [x] works via wizard
- [ ] works via API
- [ ] works via RCS
- [ ] works via bookmark load
- [ ] works in auto-legend
- [ ] works in structured legend
- [ ] works on layer reload
- [ ] datagrid works
- [ ] identify works

## Documentation

Inline comments

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated
- [x] original issue has been reviewed & updated to reflect the PR content

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3709)

### CODE REVIEW

**Comment by glitch-again** [comment]
Hey, I updated your PR Demo:

| Dev Builds                      | Prod Builds                     |
| ------------------------------- | ------------------------------- |
| [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-one.html)    | [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-one.html)    |
| [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-mobile.html)    | [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-mobile.html)    |
| [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-samples.html)    | [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-samples.html)    |
| [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-en.html) | [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-en.html) |
| [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-fr.html) | [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-fr.html) |

Is it working as expected?

**Comment by glitch-again** [comment]
Hey, I updated your PR Demo:

| Dev Builds                      | Prod Builds                     |
| ------------------------------- | ------------------------------- |
| [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-one.html)    | [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-one.html)    |
| [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-mobile.html)    | [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-mobile.html)    |
| [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-samples.html)    | [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-samples.html)    |
| [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-en.html) | [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-en.html) |
| [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-fr.html) | [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-fr.html) |

Is it working as expected?

**Comment by glitch-again** [comment]
Hey, I updated your PR Demo:

| Dev Builds                      | Prod Builds                     |
| ------------------------------- | ------------------------------- |
| [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-one.html)    | [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-one.html)    |
| [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-mobile.html)    | [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-mobile.html)    |
| [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-samples.html)    | [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-samples.html)    |
| [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-en.html) | [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-en.html) |
| [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-fr.html) | [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-fr.html) |

Is it working as expected?

**Comment by glitch-again** [comment]
Hey, I updated your PR Demo:

| Dev Builds                      | Prod Builds                     |
| ------------------------------- | ------------------------------- |
| [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-one.html)    | [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-one.html)    |
| [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-mobile.html)    | [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-mobile.html)    |
| [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-samples.html)    | [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-samples.html)    |
| [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-en.html) | [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-en.html) |
| [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-fr.html) | [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-fr.html) |

Is it working as expected?

**Comment by james-rae** [comment]
___
*[src/app/ui/loader/layer-source.service.js, line 39 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3709#-LmKjYvB1FXALtGbLD4k:-LmKjYvB1FXALtGbLD4l:by1t8lc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7018cf1188bb0f448a7c6f51d002f7d995c799e6/src/app/ui/loader/layer-source.service.js#L39)):*
> ```JavaScript
>         // fetchServiceInfo can precede layer creation so CORS checking has to be done here as well
>         // if ESRI JSAPI fixes it's CORS bug this can be removed
>         configService.getSync.map.instance.checkCorsException(serviceUrl);
> ```

3.1.0 block

**Comment by glitch-again** [comment]
Hey, I updated your PR Demo:

| Dev Builds                      | Prod Builds                     |
| ------------------------------- | ------------------------------- |
| [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-one.html)    | [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-one.html)    |
| [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-mobile.html)    | [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-mobile.html)    |
| [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-samples.html)    | [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-samples.html)    |
| [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-en.html) | [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-en.html) |
| [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/dev/samples/index-fgp-fr.html) | [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/remove-pred/prod/samples/index-fgp-fr.html) |

Is it working as expected?

**Pull request merged**
