### PR TITLE
Show an Image when data was failed to load

### PR DESCRIPTION
**Pull request by barryytm**
## Description

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/710

As title.
## Testing

Manually, try sample 48 and 49 in `index-samples`
## Documentation

sample 29, 48, and, 49 in `index-samples`
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2399)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Demo works.

The sadpanda image should be configurable via the config and the one with have should be used as a default only, if nothing is specified in the config..

---

Reviewed 7 of 16 files at r1.
Review status: 7 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/help/help-summary.html, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-KuttpL7opIWetPQHILU:-KuttpL7opIWetPQHILV:b-z0xix0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44837b1226558dc05af75f7fbfbeb85e8ead0ab5/src/app/ui/help/help-summary.html#L10)):*
> ```HTML
>         header-controls-scope="self.scope">
> 
>         <md-icon ng-if="self.hasNoHelp" style="width: 40%; height: 40%;" md-svg-src="sadpanda"></md-icon>
> ```

Please, don't use `style` to style stuff inline :D All styles should be defined in `.scss` files.

---

*[src/app/ui/help/help.service.js, line 240 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-KutuDPmNj602KQWrXwi:-KutuDPmNj602KQWrXwj:bo1acla) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44837b1226558dc05af75f7fbfbeb85e8ead0ab5/src/app/ui/help/help.service.js#L240)):*
> ```JavaScript
>             }).catch(error => {
>                 self.hasNoHelp = true;
>                 self.parent.css('text-align', 'center');
> ```

If you want to center the sad-panda image, it should be done using styles and markup if possible. If you wrap `md-icon` in a `div` with `display: flex`, it should center the image for you.

---

*[src/app/ui/sidenav/about-dialog.html, line 5 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-KutvVruUE-WNrkg6Sp7:-KutvVruUE-WNrkg6Sp8:b-w1cyqu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/44837b1226558dc05af75f7fbfbeb85e8ead0ab5/src/app/ui/sidenav/about-dialog.html#L5)):*
> ```HTML
>         <p class="rv-aboutDesc" ng-bind-html="self.about" tabindex="-2"></p> 
>     </rv-content-pane>
>     <rv-content-pane ng-if="!self.about" style="text-align: center;" close-panel="self.close()" title-style="title" title-value="{{'sidenav.label.about' | translate}}">
> ```

Instead of duplicating `rv-content-pane`, you can move `ng-if` to the `rv-aboutDesc` and move the icon to the same `rv-content-pane` with another `ng-if`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-:-Kutw85s3rO4ovdxzOQJ:bjcth3z)*

**Comment by james-rae** [comment]
Reviewed 4 of 16 files at r1, 5 of 18 files at r2, 1 of 3 files at r3, 12 of 17 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 16 files at r1, 6 of 18 files at r2, 2 of 3 files at r3, 12 of 17 files at r4, 1 of 3 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[_failure-image.scss, line 3 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv7LeTnfR3uaJDsOxQ_:-Kv7LeTnfR3uaJDsOxQa:b4tnwwr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/_failure-image.scss#L3)):*
> ```SCSS
> @mixin failure-image {
>     rv-failure-image {
>         display: flex;
> ```

To avoid specifying multiple sets of rules and using absolute units, we can size the image using `max-height/width` and some flexboxing:

```css
rv-failure-image {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    // force container to take all available space
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;

    .rv-fail-before {
        flex: 1;
    }

    .rv-fail-after {
        flex: 3;
    }

    md-icon, img {
        flex: 1;
        // constrain maximum size of the fail image
        max-width: 60%;
        max-height: 70%;
    }
}
```



---

*[src/app/ui/common/failure-image.html, line 2 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv7Im_G-NmxEM2-XBsr:-Kv7Im_G-NmxEM2-XBss:b3pk1y4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/src/app/ui/common/failure-image.html#L2)):*
> ```HTML
> <md-icon ng-if="!self.failureImageUrl" md-svg-src="sadpanda"></md-icon>
> 
> ```

I think it would be helpful to add an option fail text message underneath the fail image (if not specified, a default value from the translation file should be used). This will also need a trivial change to the config schema.

Also, let's make the image align properly in all containers:
```html
<div class="rv-fail-before"></div>

<md-icon ng-if="!self.failureImageUrl" md-svg-src="sadpanda"></md-icon>
<img ng-if="self.failureImageUrl" ng-src="{{ self.failureImageUrl }}">

<p class="md-subhead">{{ self.failMessage || 'fail.message' | translate }}</p>

<div class="rv-fail-after"></div>
```

---

*[src/app/ui/sidenav/about-dialog.html, line 4 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv7LTQHuYXEwleQR-5e:-Kv7LTQHuYXEwleQR-5f:b-p30y24) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/src/app/ui/sidenav/about-dialog.html#L4)):*
> ```HTML
>     <rv-content-pane close-panel="self.close()" title-style="title" title-value="{{'sidenav.label.about' | translate}}">
>         <p class="rv-aboutDesc" ng-if="self.about" ng-bind-html="self.about" tabindex="-2"></p> 
>         <rv-failure-image class="rv-failure-image-medium" ng-if="!self.about"></rv-failure-image>
> ```

There is no need to use `rv-failure-image-X` classes - you can target the `<rv-failure-image>` element directly in your CSS.

---

*[src/app/ui/toc/toc.service.js, line 14 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv3DGaD_mYT7f5CWqgm:-Kv3DGaD_mYT7f5CWqgn:b1oc0v5) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/src/app/ui/toc/toc.service.js#L14)):*
> ```JavaScript
>     .factory('tocService', tocService);
> 
> function tocService($q, $rootScope, $mdToast, $translate, $compile, referenceService, common, stateManager, graphicsService,
> ```

Do you still need `$compile` here?

---

*[src/app/geo/metadata.service.js, line 19 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv26FoCLPdRMFZEynaL:-Kv26FoCLPdRMFZEynaM:bpp0fof) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/851fc5cc1a0e9aff5cf43fdd4d83e0bbe5e64da2/src/app/geo/metadata.service.js#L19)):*
> ```JavaScript
> 
>     const service = {
>         loadFromURL,
> ```

Dangling coma.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399)*

**Comment by barryytm** [comment]
Review status: 12 of 23 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/app/ui/common/failure-image.html, line 2 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv7Im_G-NmxEM2-XBsr:-Kv7kr5ETCQ5SaNStPQO:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/src/app/ui/common/failure-image.html#L2)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

I think it would be helpful to add an option fail text message underneath the fail image (if not specified, a default value from the translation file should be used). This will also need a trivial change to the config schema.

Also, let's make the image align properly in all containers:
```html
<div class="rv-fail-before"></div>

<md-icon ng-if="!self.failureImageUrl" md-svg-src="sadpanda"></md-icon>
<img ng-if="self.failureImageUrl" ng-src="{{ self.failureImageUrl }}">

<p class="md-subhead">{{ self.failMessage || 'fail.message' | translate }}</p>

<div class="rv-fail-after"></div>
```
</blockquote></details>

done, thanks

---

*[src/app/ui/help/help-summary.html, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-KuttpL7opIWetPQHILU:-Kv7ksX1G4O66IH-tkcf:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/18a44f60dfda5fa96f10f4998f416ad16b2980f8/src/app/ui/help/help-summary.html#L10)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Please, don't use `style` to style stuff inline :D All styles should be defined in `.scss` files.
</blockquote></details>

done, thanks

---

*[src/app/ui/help/help.service.js, line 240 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-KutuDPmNj602KQWrXwi:-Kv7ktz3i5vGB5YAI0Zg:b-r18wje) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/18a44f60dfda5fa96f10f4998f416ad16b2980f8/src/app/ui/help/help.service.js#L240)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

If you want to center the sad-panda image, it should be done using styles and markup if possible. If you wrap `md-icon` in a `div` with `display: flex`, it should center the image for you.
</blockquote></details>

done, thanks

---

*[src/app/ui/sidenav/about-dialog.html, line 5 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-KutvVruUE-WNrkg6Sp7:-Kv7l4r9-u_yfkmrHNKQ:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/18a44f60dfda5fa96f10f4998f416ad16b2980f8/src/app/ui/sidenav/about-dialog.html#L5)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Instead of duplicating `rv-content-pane`, you can move `ng-if` to the `rv-aboutDesc` and move the icon to the same `rv-content-pane` with another `ng-if`.
</blockquote></details>

done, thanks

---

*[src/app/ui/sidenav/about-dialog.html, line 4 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv7LTQHuYXEwleQR-5e:-Kv7kv8688va7iTrl_9S:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/src/app/ui/sidenav/about-dialog.html#L4)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

There is no need to use `rv-failure-image-X` classes - you can target the `<rv-failure-image>` element directly in your CSS.
</blockquote></details>

done, thanks

---

*[_failure-image.scss, line 3 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv7LeTnfR3uaJDsOxQ_:-Kv7kx4dEBNnt1Iwx37g:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/_failure-image.scss#L3)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

To avoid specifying multiple sets of rules and using absolute units, we can size the image using `max-height/width` and some flexboxing:

```css
rv-failure-image {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    // force container to take all available space
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;

    .rv-fail-before {
        flex: 1;
    }

    .rv-fail-after {
        flex: 3;
    }

    md-icon, img {
        flex: 1;
        // constrain maximum size of the fail image
        max-width: 60%;
        max-height: 70%;
    }
}
```


</blockquote></details>

done, thanks

---

*[src/app/geo/metadata.service.js, line 19 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv26FoCLPdRMFZEynaL:-Kv7kysaK6WMjB-i6ft_:b-eaetjv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/851fc5cc1a0e9aff5cf43fdd4d83e0bbe5e64da2/src/app/geo/metadata.service.js#L19)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Dangling coma.
</blockquote></details>

Got rid of it, thanks

---

*[src/app/ui/toc/toc.service.js, line 14 at r5](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-Kv3DGaD_mYT7f5CWqgm:-Kv7kyV1aUraFvL-1qMz:b-eaetjv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/76c8f10eb23d9bb2f8dfbcae101b3935e8ab725a/src/app/ui/toc/toc.service.js#L14)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Do you still need `$compile` here?
</blockquote></details>

Got rid of it, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399)*

**Comment by AleksueiR** [comment]
Looks great, thanks :+1: 

---

Reviewed 1 of 3 files at r5, 13 of 13 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399#-:-Kv7s08NYRyiKS3_YjZ9:b-2fwqdd)*

**Comment by james-rae** [comment]
Reviewed 11 of 13 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2399)*

**Pull request merged**
