### PR TITLE
feat(ui): cleanup menu items

### LINKED ISSUE #729: Cleanup Menu Items
- [x] Menu item Options currently does nothing.  Remove
- [x] Replace image with FGP logo

### PR DESCRIPTION
**Pull request by milesap**
Closes #729

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/827)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/content/styles/modules/_app-menu.scss, line 12 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827#-KL1OqJpvXWJlC7BkdQK:-KL1OqJpvXWJlC7BkdQL:-919054834) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a6ca94a008dc8ba1bb835ee85221e2a7907e7e5f/src/content/styles/modules/_app-menu.scss#L12)):*
> ```SCSS
>                 flex-direction: column;
>                 display: flex;
>                 flex: 1;
> ```

Add `padding: rem(0.8) 0;` here to add a little space before the side menu option buttons.

---

*[src/content/styles/modules/_app-menu.scss, line 39 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827#-KL1RbFJQYaECMVXEDgo:-KL1RbFKwokMgzWkxg_w:-1409374094) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/02a52635f0d3a6d6d92875bca47e69adbded66b6/src/content/styles/modules/_app-menu.scss#L39)):*
> ```SCSS
>                 flex-direction: column;
>                 align-items: center;
>                 padding: 0 0 16px;
> ```

Keep the padding, it adds some white space.

---

*[src/content/styles/modules/_app-menu.scss, line 49 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827#-KL1RnOnVRGOckcEsitc:-KL1RnOnVRGOckcEsitd:1647254576) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a6ca94a008dc8ba1bb835ee85221e2a7907e7e5f/src/content/styles/modules/_app-menu.scss#L49)):*
> ```SCSS
>                     margin-top: 30px;
>                     max-width: 90%;
>                     max-height: 90%;
> ```

This is not enough as the big images will be too big.



Let's wrap this img tag in a 150x150 flexbox div:
```css
    width: rem(15);
    height: rem(15);
    margin-top: rem(3);
    display: flex;
    justify-content: center;
    align-items: center;
```
This will serve as the container for the image, so large images are contained. flex attributes will center smaller images inside the box. 
The image needs only its maximum dimensions specified, to prevent it from spilling over its container:
```css
    max-width: 100%;
    max-height: 100%;
}
```

Result:



---

*[src/content/styles/modules/_app-menu.scss, line 60 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827#-KL1O6V3BlMXoV_9WMUu:-KL1O6V5DK55eJUiUnFx:-1486022614) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/02a52635f0d3a6d6d92875bca47e69adbded66b6/src/content/styles/modules/_app-menu.scss#L60)):*
> ```SCSS
> 
>             > .minimize-button {
>                 margin: 10px;
> ```

Keep this margin, otherwise the button is too close to the edge. Can be merged with the `.minize-button` rule above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827)*

**Comment by AleksueiR** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827#-:-KLGiArrS0CB1dJoRnGW:1417088721)*

**Comment by alyec** [comment]
Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827)*

**Comment by cynngah** [comment]
Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/827)*

**Pull request merged**
