### PR TITLE
feat(ui): detail & filter i18n support

### PR DESCRIPTION
**Pull request by james-rae**
i18n for Detail Pane, Content Pane, and Filter.
Icons in filter menu prevent nice approach of translate directive

[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/292)

### CODE REVIEW

**Comment by ec-dev** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292#-K9iJ98uEdGd3HReA91w:-K9iJ98vAEZ2uyNkEFOX:-197718307) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffcf51ebdbbf6f9b5f3e1267a9a92e63fc28c40f/src/app/ui/details/details.html#L5)):*
`translate-attr-title-value="..."` doesn't work?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292#-K9iJ98uEdGd3HReA91w:-K9j7bmuQsF2brw7rqM4:1922270622) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffcf51ebdbbf6f9b5f3e1267a9a92e63fc28c40f/src/app/ui/details/details.html#L5)):*
I'm not in the loop on angular-translate, can you fill me in on why that way is better?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292#-K9iJ98uEdGd3HReA91w:-K9lJR1x0-QsOsdKXCnG:1974583698) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffcf51ebdbbf6f9b5f3e1267a9a92e63fc28c40f/src/app/ui/details/details.html#L5)):*
Translate filter seems to be setting more watches than translate directive. Although in this case, I think filter is better (I'm not sure how the `title-value` binding would react in this case), so please disregard my previous comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by james-rae** [comment]
*[src/app/ui/details/details.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292#-K9iJ98uEdGd3HReA91w:-K9ll2GIsySLBgkbzfjJ:-150072351) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffcf51ebdbbf6f9b5f3e1267a9a92e63fc28c40f/src/app/ui/details/details.html#L5)):*
adding the `translate` directive fights with the `rv-content-pane` over scope

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/details/details.html, line 5 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292#-K9iJ98uEdGd3HReA91w:-K9lovtrTk-dp75V5KIN:-1024557721) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/ffcf51ebdbbf6f9b5f3e1267a9a92e63fc28c40f/src/app/ui/details/details.html#L5)):*
Fair enough.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/app/ui/mapnav/mapnav.html, line 7 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292#-K9m5XbSah_5fRCmWTJ9:-K9m5XbSah_5fRCmWTJA:999448724) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7afe70d02b5ce24cc654a2dec186bcb4c962c098/src/app/ui/mapnav/mapnav.html#L7)):*
Ops, this was supposed  to be an internal comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by spencerwahl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Comment by james-rae** [comment]
*[src/app/ui/mapnav/mapnav.html, line 7 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292#-K9m5XbSah_5fRCmWTJ9:-K9m8e7PlqpS5FCYLof9:1305382797) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/7afe70d02b5ce24cc654a2dec186bcb4c962c098/src/app/ui/mapnav/mapnav.html#L7)):*
lol well removing the code gives me another chance to bump travis, so its a good thing :dragon_face: :dash: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/292)*

**Pull request closed without merging**
