### PR TITLE
Add label to show that child opacity values differ from parent

### LINKED ISSUE #2535: Please add a label/indicator to indicate default opacity value of 0.5 in parent entries when opacity value differ with child entries
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-qa/prod/samples/index-samples.html

 Related :#2372

Default value of opacity is set to 0.5 in cases where opacity values are different for parent and child items.  Please add a label/indicator of some sort to indicate this setting

image

### PR DESCRIPTION
**Pull request by dane-thomas**
## Description

Closes #2535

## Testing

:eyes:
index-sample.html - Sample 4

## Documentation

In-line commenting 

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 7 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LDwpgmC2RtaJEMiXR2C:-LDwpgmDAOQEbarhvee4:b-jqt4bh) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/409c06b8bd99236f89b1192555dffdf12e1edcc7/src/app/ui/toc/templates/legend-control-slider.html#L7)):*
> ```HTML
> 
>         
>         <span class="rv-slider-header-subtitle" ng-if="self.uiControl._controlName === 'opacity' && self.uiControl.isGroup" translate="toc.slider.nested"></span>
> ```

This adds very specific conditions (control name being a certain value) to the generic control and makes this less maintainable. 
It would be better to assume that all slider controls can display this "mixed values" message based on that `self.uiControl.same` property.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by james-rae** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/locales/translations.csv, line 106 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LDwtCIh19V1L1HSE-73:-LDwtCIj5CEcDjjeydwQ:b-9l5c1n) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/409c06b8bd99236f89b1192555dffdf12e1edcc7/src/locales/translations.csv#L106)):*
> ```CSV
> Geosearch FSA type,geosearch.type.fsa,Postal Code,1,Code postal,1
> Geosearch National Topographic System type,geosearch.type.nts,NTS,1,SNRC,1
> ,geosearch.nomatches.label,"No matches found for """"{{ noResultsSearchValue }}""""",1,"Aucun résultat correspondant à """"{{ noResultsSearchValue }}"""".",1
> ```

I think your text editor / excel might have added some extra double-quotes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by dane-thomas** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 7 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LDwpgmC2RtaJEMiXR2C:-LE9YQTm3lZfeLbc84KE:b-4z0hrw) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/409c06b8bd99236f89b1192555dffdf12e1edcc7/src/app/ui/toc/templates/legend-control-slider.html#L7)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

This adds very specific conditions (control name being a certain value) to the generic control and makes this less maintainable. 
It would be better to assume that all slider controls can display this "mixed values" message based on that `self.uiControl.same` property.
</blockquote></details>

Done. 

The main reason I put the check in was in case `self.uiControl.same` wasn't defined. I'm not 100% sure if an explicit check is needed though. 

---

*[src/locales/translations.csv, line 106 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LDwtCIh19V1L1HSE-73:-LE9Yy3EA_eI0SAjccd4:btn6has) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/409c06b8bd99236f89b1192555dffdf12e1edcc7/src/locales/translations.csv#L106)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I think your text editor / excel might have added some extra double-quotes.
</blockquote></details>

Done thanks. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by AleksueiR** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 7 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LDwpgmC2RtaJEMiXR2C:-LE9el1i2M25egSc5bG7:b-6wiwo3) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/409c06b8bd99236f89b1192555dffdf12e1edcc7/src/app/ui/toc/templates/legend-control-slider.html#L7)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

Done. 

The main reason I put the check in was in case `self.uiControl.same` wasn't defined. I'm not 100% sure if an explicit check is needed though. 
</blockquote></details>

If it's not defined, it will resolve as a falsy value in the template.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 16 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LE9f4IG-174bHnmNNbp:-LE9f4IG-174bHnmNNbq:b-ldyu4d) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9fc23f3287514e4e6f42df31d4138665fb4001fc/src/app/ui/toc/templates/legend-control-slider.html#L16)):*
> ```HTML
>             ng-class="{ 'rv-slider-mixed' : !self.uiControl.same }"
>             max="1" min="0" step="0.01" ng-model="self.uiControl.value"></md-slider>
>         <span class="rv-slider-indicator">{{ self.uiControl.same ? self.Math.round(self.uiControl.value * 100) : null }}%</span>
> ```

Do you think it's better to hide this span completely if the `same` is falsy? Otherwise it leaves a lonely percent sign beside the slider


I know this how it looked in the original issue, but I don't think it makes sense to display it like that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by dane-thomas** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 16 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LE9f4IG-174bHnmNNbp:-LE9gOo05d7u_NrifSpI:b-rf51bn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9fc23f3287514e4e6f42df31d4138665fb4001fc/src/app/ui/toc/templates/legend-control-slider.html#L16)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Do you think it's better to hide this span completely if the `same` is falsy? Otherwise it leaves a lonely percent sign beside the slider


I know this how it looked in the original issue, but I don't think it makes sense to display it like that.
</blockquote></details>

So like this?


---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by AleksueiR** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 16 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LE9f4IG-174bHnmNNbp:-LE9gqG04dHppq8xyTZ3:b-ot6mmd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9fc23f3287514e4e6f42df31d4138665fb4001fc/src/app/ui/toc/templates/legend-control-slider.html#L16)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

So like this?


</blockquote></details>

Yes. What do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by dane-thomas** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 16 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LE9f4IG-174bHnmNNbp:-LE9h7t0CmfZ3RtWzGzc:boyuil2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9fc23f3287514e4e6f42df31d4138665fb4001fc/src/app/ui/toc/templates/legend-control-slider.html#L16)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Yes. What do you think?
</blockquote></details>

The lonely percent sign did look kinda out of place. The only thing is the bar now expands to the entire width making it significantly longer than the others. The other option would just be something like this. 


---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by AleksueiR** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 16 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LE9f4IG-174bHnmNNbp:-LE9ijjw-dDhxxKk5Wlj:bgyakwi) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9fc23f3287514e4e6f42df31d4138665fb4001fc/src/app/ui/toc/templates/legend-control-slider.html#L16)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

The lonely percent sign did look kinda out of place. The only thing is the bar now expands to the entire width making it significantly longer than the others. The other option would just be something like this. 


</blockquote></details>

Sure, sound good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/toc/templates/legend-control-slider.html, line 16 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-LE9f4IG-174bHnmNNbp:-LE9nMaHEJwW16VMsq4p:b6x532s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/9fc23f3287514e4e6f42df31d4138665fb4001fc/src/app/ui/toc/templates/legend-control-slider.html#L16)):*
<details><summary><i>Previously, dane-thomas (Dane Thomas) wrote…</i></summary><blockquote>

Ok done. 
</blockquote></details>

Thanks :+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)*

**Comment by JahidAhmed** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752#-:-LEAeUMe7XCEHxbsz-Tr:bnfp4nl)*

**Pull request merged**
