### PR TITLE
Make on/off of hover tips configurable

### PR DESCRIPTION
**Pull request by barryytm**
## Description

As title.  Modify schema and add a sample of hover tips being turned off

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2001
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2231
## Testing

Sample\#47
## Documentation

Add Sample\#47 and modify `index-samples.html`
## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2332)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.class.js, line 252 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2332#-Krki1udVe1ICdKdPeN-:-Krki1udVe1ICdKdPeN0:bpcwcfv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8dd7a32a8c6f0d8e425a43c3cc23e098bf35e3de/src/app/core/config.class.js#L252)):*
> ```JavaScript
>             this._snapshot = source.snapshot;
>             this._userAdded = source.userAdded;
>             this._hovertips = source.hovertips;
> ```

Hovertips don't work at all. There is no defaulting to `true`, so it ends up as falsy `undefined` which just turns them all off.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2332)*

**Comment by milesap** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2332)*

**Comment by barryytm** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/config.class.js, line 252 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2332#-Krki1udVe1ICdKdPeN-:-KrklzJSUSCNKTLPfRhf:b-lhs69o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8dd7a32a8c6f0d8e425a43c3cc23e098bf35e3de/src/app/core/config.class.js#L252)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Hovertips don't work at all. There is no defaulting to `true`, so it ends up as falsy `undefined` which just turns them all off.
</blockquote></details>

done, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2332)*

**Comment by AleksueiR** [comment]
Demo works. :lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/2332#-:-KrlQNd3MP75Q_Aq7YcH:b-xl99c8)*

**Pull request merged**
