### PR TITLE
style clean up for docs code

### PR DESCRIPTION
**Pull request by ec-dev**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/47)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 13 of 13 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47)

**Comment by jolevesq** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 2 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KTf9ZzmuRjdlPNfY-)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/app/js/app.js#L2)):</sup>
Use arrow function like Aleks start to use?


---

<sup>**[docs/app/js/app.js, line 44 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KULY2KnFT6sXns3i_)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/app/js/app.js#L44)):</sup>
Do we want to use ES6 const and let like the code for the viewer?


---

<sup>**[docs/config/dgeni-conf.js, line 37 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KV6rMgMG46ShD7H9F)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/config/dgeni-conf.js#L37)):</sup>
Space before closing curly brackets


---

<sup>**[docs/config/dgeni-conf.js, line 43 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KVBMQvLagqCtmVzeL)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/config/dgeni-conf.js#L43)):</sup>
Space before closing curly brackets


---

<sup>**[docs/config/processor/docMergeProcessor.js, line 48 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KVd42h3xYtQWq_pdr)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/config/processor/docMergeProcessor.js#L48)):</sup>
Space afet opening curly bracket and before closing curly brackets


---

<sup>**[docs/config/processor/navMenu.js, line 13 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KVxd-_qgGKRTN9QmP)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/config/processor/navMenu.js#L13)):</sup>
Space after opening curly brackets and before closing curly brackets


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47)

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 44 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KULY2KnFT6sXns3i_)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/app/js/app.js#L44)):</sup>
We don't have the doc task polyfilled.  It's probably doable but might not be worth the effort of converting.  As I understand we stole most of this code from Angular material.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47)

**Comment by AleksueiR** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[docs/app/js/app.js, line 44 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47#-K1KULY2KnFT6sXns3i_)** ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/929bdb31da69795bd68601bb211df5785d49cb3f/docs/app/js/app.js#L44)):</sup>
I agree, let's keep docs code in es5.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47)

**Comment by jolevesq** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47)

**Comment by alyec** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/47)

**Pull request merged**
