### PR TITLE
feat(ui): throttle initial layer loading

### LINKED ISSUE #618: Throttle initial layer loading
With about ten layers added upfront, the app become unresponsive for a while when layer data is loaded (after the loading screen is removed). 

In this gif, I clicked on the legend button in the first frame and it takes a couple of seconds for the main panel to simply open:
layer_lag

I think we can improve (visible) performance here by not allowing all the layers to load at the same time. We can add a timeout to start loading layers in a staggered fashion or impose a limit on how many layers can be loading at a time (thanks @alyec Aly).

### PR DESCRIPTION
**Pull request by milesap**
## Description
Throttles initial layer loading to 2 concurrent loads at any time. Unfortunately placeholders are tightly coupled with layer loading, so layers only appear in the legend once they have started loading.

Closes #618

## Testing
Tested with 3 concurrent loads however there was a noticeable performance impact. 

## Documentation
jsdoc, inline

## Checklist

- [x] commits messages follow the guidelines
- [x] code passes unit tests
- [x] release notes have been updated
- [x] PR targets the correct release version

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1554)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 378 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554#-K__7FHx6vXv7kGM3Rxa:-K__7FHx6vXv7kGM3Rxb:bnijxhg) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0446acc7c59eb618b13bdb3960bd1910063c00a8/src/app/geo/layer-registry.service.js#L378)):*
> ```JavaScript
>              * @param  {Number} processNumLayers the number of concurrent layers to load from layerBlueprints array
>              */
>             function constructLayers(layerBlueprints, processNumLayers = 2) {
> ```

Can we show all the layer placeholders at once, so the user knows there are, say, ten layers loading? Otherwise, if two layers are taking longer to load, it will look like some layers are missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554)*

**Comment by milesap** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/geo/layer-registry.service.js, line 378 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554#-K__7FHx6vXv7kGM3Rxa:-K__9uN70BSZZYdScYz_:byh20ws) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0446acc7c59eb618b13bdb3960bd1910063c00a8/src/app/geo/layer-registry.service.js#L378)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

Can we show all the layer placeholders at once, so the user knows there are, say, ten layers loading? Otherwise, if two layers are taking longer to load, it will look like some layers are missing.
</blockquote></details>

That was the initial goal. Though it seems that to create a placeholder, you [need to provide a layerRecord](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/legend.service.js#L227) which gets loaded when you create it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554)*

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 378 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554#-K__7FHx6vXv7kGM3Rxa:-K__kDI938P2AnhtE4NV:bkgs1ev) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0446acc7c59eb618b13bdb3960bd1910063c00a8/src/app/geo/layer-registry.service.js#L378)):*
<details><summary><i>Previously, milesap (Miles Petrov) wrote…</i></summary><blockquote>

That was the initial goal. Though it seems that to create a placeholder, you [need to provide a layerRecord](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/legend.service.js#L227) which gets loaded when you create it.
</blockquote></details>

For a placeholder, all you need is the layer type and its name. It should be possible to create a placeholder and stall actual layer loading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554)*

**Comment by milesap** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/geo/layer-registry.service.js, line 378 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554#-K__7FHx6vXv7kGM3Rxa:-K__puykI7iyFlXMLY94:behwwl2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/0446acc7c59eb618b13bdb3960bd1910063c00a8/src/app/geo/layer-registry.service.js#L378)):*
<details><summary><i>Previously, AleksueiR (Aleksuei Riabtsev) wrote…</i></summary><blockquote>

For a placeholder, all you need is the layer type and its name. It should be possible to create a placeholder and stall actual layer loading.
</blockquote></details>

It seems there is no direct way to get a layerRecord without it loading. `addPlaceholder` in `legend.service.js` requires a `layerRecord` object since it handles removing the placeholder and its listeners when the layer is finished loading. I made a note in the original issue for further discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1554)*

**Pull request closed without merging**
