### PR TITLE
fix(ui): add map object description

### LINKED ISSUE #1144: Map object describes itself better
When a user tabs or mouses over the map, it should describe itself so that it is obvious to someone using a screen reader that they are viewing a complex map (WCAG 2.0 AA 1.1.1)

### PR DESCRIPTION
**Pull request by milesap**
Closes #1144

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1183)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Have you tried it with a screen reader? :) http://www.nvaccess.org/download/

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183#-:-KRhrwWPYx-HVakKYksZ:bhwe8nw)*

**Comment by AleksueiR** [comment]
When you tab to the viewer on `index-fgp-en`, which node is it focused on while showing the "keyboard focus" dialog? If it's not focused on the `.rv-esri-map` not, it probably will not read the description.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183#-:-KRnKZQJeCigthi42_eb:b-5epq1t)*

**Comment by AleksueiR** [comment]
Seems you need to also add `translate`. This worked for me:

```js
<div class="rv-esri-map" rv-init-map tabindex="0" translate translate-attr-aria-label="geo.aria.overviewtoggle"></div>
```

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183#-:-KS6QmncPaA5H3sdsljv:b-8qtnr8)*

**Comment by milesap** [comment]
Perfect, it needed the `translate` property to work. I can confirm focus is on `<div class="rv-esri-map" ...` and `aria-label` is rendered correctly. Should this be reviewed by Paul Huppe?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183#-:-KS6XiopUBzg9o58YsA5:b-lq73od)*

**Comment by AleksueiR** [comment]
Might as well (I'm just afraid we will get lots more errors after he reviews it :) ).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183#-:-KS6Yb5Qo_tBZ43VZESo:b5u6jdz)*

**Comment by milesap** [comment]
Sent an email to Paul Huppé to review this issue - I'll update here when I hear back (and push needed changes).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183#-:-KS6kYjMZI_o_GZhuYM1:b2jxqfd)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183)*

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpv-vpgf/1183)*

**Pull request merged**
